/**
 * devocionales.js — Devocionales para la familia del pastor: hijos, esposa,
 * esposo y la pareja juntos.
 *
 * Cada devocional parte de un pasaje (el texto se carga de la RV1909, no se
 * copia aquí), con una nota de contexto exegético, una idea central, reflexión,
 * preguntas, una aplicación concreta, oración y un versículo para memorizar.
 * Los de los hijos traen además una versión para los más pequeños y una
 * pregunta para adolescentes.
 */

export const DESTINATARIOS = [
  { id: 'hijos', nombre: 'Hijos', icono: '🧒', descripcion: 'Culto familiar de 10-15 minutos. El cuerpo está pensado para 8-12 años, con adaptación para pequeños (4-7) y una pregunta para adolescentes.' },
  { id: 'esposa', nombre: 'Esposa', icono: '🌷', descripcion: 'Para la esposa: identidad en Cristo, sabiduría, descanso y ministerio desde el hogar y la iglesia.' },
  { id: 'esposo', nombre: 'Esposo', icono: '🛡️', descripcion: 'Para el esposo: liderazgo de siervo, integridad, amor sacrificial y paternidad.' },
  { id: 'pareja', nombre: 'Pareja', icono: '💞', descripcion: 'Para leer juntos: pacto, comunicación, perdón, oración y propósito compartido.' },
];

export const DEVOCIONALES = [
  // ======================================================================= HIJOS
  {
    id: 'h01', para: 'hijos', serie: 'Dios y su creación', titulo: 'Dios lo hizo todo, y lo hizo bueno',
    texto: 'Gn 1:1-5', memoria: 'Gn 1:1',
    contexto: 'Génesis 1 no empieza hablando del hombre sino de Dios: "En el principio… Dios". El verbo hebreo bará (crear) en el AT siempre tiene a Dios como sujeto; solo Él crea de esa manera. El capítulo repite siete veces que lo creado era "bueno".',
    idea: 'Todo lo que existe tiene dueño y tiene propósito, porque Dios lo creó.',
    reflexion: 'Antes de que hubiera luz, estrellas o personas, Dios ya estaba. No necesitó materiales ni ayuda: habló, y fue. Eso nos dice dos cosas: que Dios es muy poderoso, y que nada de lo que vemos está aquí por casualidad.\n\nTú también fuiste pensado por Dios. El mismo que ordenó "sea la luz" sabe tu nombre. Cuando miras el cielo, un árbol o a tu hermano, estás viendo algo que Dios hizo con cuidado.',
    preguntas: ['¿Qué fue lo primero que Dios creó según este pasaje?', '¿Qué significa que Dios lo hizo "bueno"?', '¿Qué cosa creada por Dios te gusta más, y por qué?'],
    aplicacion: 'Salgan juntos (o miren por la ventana) y nombren diez cosas que Dios hizo. Den gracias por cada una.',
    oracion: 'Dios Creador, gracias porque todo lo hiciste bueno, y porque me hiciste a mí. Ayúdame a cuidar lo que hiciste y a darte gracias cada día. Amén.',
    pequenos: 'Dios es tan grande que solo habló y apareció la luz. Apaguen la luz del cuarto y enciéndanla: "¡Dios dijo: sea la luz!". Dios hizo todo, y te hizo a ti.',
    adolescentes: 'Si el universo tiene Autor, ¿qué cambia en la manera de ver tu cuerpo, tu tiempo y tu futuro? ¿Es lo mismo "existo por azar" que "fui creado"?',
  },
  {
    id: 'h02', para: 'hijos', serie: 'Dios y su creación', titulo: 'Hechos a imagen de Dios',
    texto: 'Gn 1:26-31', memoria: 'Gn 1:27',
    contexto: 'Solo del ser humano se dice que fue hecho "a imagen" (tsélem) y "semejanza" (demut) de Dios. En el mundo antiguo, los reyes ponían estatuas con su imagen para mostrar su dominio; Dios pone al hombre y la mujer en la tierra como sus representantes.',
    idea: 'Cada persona vale mucho porque lleva la imagen de Dios.',
    reflexion: 'Dios hizo animales increíbles, pero a ninguno le dijo lo que le dijo al ser humano: "Hagamos al hombre a nuestra imagen". Eso significa que podemos conocer a Dios, amarlo, pensar, crear y cuidar el mundo en su nombre.\n\nTambién significa que nadie es "menos": ni el niño que se burlan en la escuela, ni el anciano, ni el que habla otro idioma. Cuando tratamos mal a alguien, tratamos mal a alguien que lleva la imagen de Dios.',
    preguntas: ['¿Qué dice el versículo 27 sobre el hombre y la mujer?', '¿En qué nos parecemos a Dios que no se parece un animal?', '¿Cómo deberíamos tratar a alguien que es diferente a nosotros?'],
    aplicacion: 'Esta semana, busca a alguien que suele quedarse solo y trátalo como alguien que lleva la imagen de Dios: salúdalo, siéntate con él o invítalo a jugar.',
    oracion: 'Señor, gracias por hacerme a tu imagen. Ayúdame a verte en los demás y a tratarlos con respeto y amor. Amén.',
    pequenos: 'Mírense en un espejo: el espejo muestra tu imagen. Dios nos hizo para mostrar cómo es Él: amoroso, bueno y creativo.',
    adolescentes: '¿Cómo afecta la verdad de la imagen de Dios a temas como el acoso, las redes sociales o la manera en que hablas de tu propio cuerpo?',
  },
  {
    id: 'h03', para: 'hijos', serie: 'El problema y la promesa', titulo: 'La primera desobediencia',
    texto: 'Gn 3:1-13', memoria: 'Ro 3:23',
    contexto: 'La serpiente no niega de frente a Dios: empieza con una duda ("¿Conque Dios os ha dicho…?") y termina con una mentira ("No moriréis"). El pecado entra al desconfiar de la bondad de Dios. Después vienen la vergüenza, el esconderse y la culpa hacia otros.',
    idea: 'Pecar es desconfiar de Dios y hacer lo que Él dijo que no; y todos lo hemos hecho.',
    reflexion: 'Adán y Eva tenían todo lo bueno, pero escucharon una voz que les decía que Dios les estaba escondiendo algo. Desobedecieron, y lo primero que hicieron después fue esconderse y echarle la culpa a otro.\n\nNosotros hacemos lo mismo: cuando hacemos algo malo queremos escondernos o decir "fue él". Pero Dios fue a buscarlos: "¿Dónde estás tú?". Dios sigue buscando a los que se esconden, no para aplastarlos, sino para traerlos de vuelta.',
    preguntas: ['¿Qué mentira dijo la serpiente?', '¿Qué hicieron Adán y Eva después de desobedecer?', '¿Por qué nos cuesta decir "fui yo, me equivoqué"?'],
    aplicacion: 'Practiquen en familia la frase: "Me equivoqué, lo siento, ¿me perdonas?". Si hay algo pendiente entre hermanos o con papá y mamá, arréglenlo hoy.',
    oracion: 'Padre, yo también he desobedecido. Gracias porque me buscas en vez de abandonarme. Ayúdame a decir la verdad cuando me equivoco. Amén.',
    pequenos: 'Jueguen a las escondidas un momento. Luego expliquen: Adán y Eva se escondieron de Dios después de desobedecer, pero Dios los buscó porque los amaba.',
    adolescentes: 'La tentación empezó sembrando duda sobre la bondad de Dios. ¿Qué "voces" de hoy te dicen que Dios te está quitando algo bueno?',
  },
  {
    id: 'h04', para: 'hijos', serie: 'El problema y la promesa', titulo: 'La primera promesa del Salvador',
    texto: 'Gn 3:14-15, 21', memoria: 'Gn 3:15',
    contexto: 'Gn 3:15 ha sido llamado el protoevangelio ("primer evangelio"): Dios anuncia que la simiente de la mujer herirá la cabeza de la serpiente, aunque sea herido en el talón. El NT lo ve cumplido en Cristo (Ro 16:20; He 2:14). En el v. 21, Dios mismo cubre a Adán y Eva con pieles: alguien muere para cubrirlos.',
    idea: 'En el mismo día del primer pecado, Dios prometió un Salvador.',
    reflexion: 'Parecía que todo se había arruinado. Pero Dios no se quedó en el castigo: prometió que un descendiente de la mujer vencería a la serpiente. Ese descendiente es Jesús, que en la cruz fue herido, pero venció al diablo.\n\nY mira el versículo 21: Dios les hizo ropa de pieles. Para eso un animal tuvo que morir. Desde el principio Dios estaba enseñando que para cubrir el pecado hacía falta un sacrificio.',
    preguntas: ['¿Qué promete Dios en el versículo 15?', '¿Quién es el que vencería a la serpiente?', '¿Qué hizo Dios en el versículo 21 y qué nos enseña?'],
    aplicacion: 'Dibujen una línea del tiempo simple: "Promesa (Génesis 3)" → "Cumplimiento (la cruz)". Péguenla donde hacen el culto familiar y vayan agregando promesas.',
    oracion: 'Dios fiel, gracias porque desde el principio tenías un plan para salvarnos por medio de Jesús. Amén.',
    pequenos: 'Dios estaba triste por la desobediencia, pero hizo una promesa: "Voy a mandar a alguien que gane contra el malo". ¡Ese es Jesús!',
    adolescentes: 'El evangelio no es un "plan B". ¿Qué te dice sobre Dios que la promesa de redención aparezca en el mismo capítulo de la caída?',
  },
  {
    id: 'h05', para: 'hijos', serie: 'Confiar en Dios', titulo: 'Noé obedeció cuando nadie más lo hacía',
    texto: 'Gn 6:5-9, 22', memoria: 'Gn 6:22',
    contexto: 'El texto contrasta la maldad generalizada ("todo designio… de continuo solamente el mal", v. 5) con Noé, que "halló gracia" (v. 8). El orden importa: primero la gracia de Dios, luego la descripción de Noé como justo. Su obediencia es completa: "conforme a todo lo que Dios le mandó; así lo hizo".',
    idea: 'Obedecer a Dios vale la pena aunque seas el único.',
    reflexion: 'Todos a su alrededor hacían lo malo, y Noé podía pensar: "Si todos lo hacen, no debe ser tan grave". Pero Noé caminó con Dios. Construyó un barco enorme lejos del mar, y seguramente se burlaron de él.\n\nFíjate que primero dice que Noé "halló gracia". Noé no se ganó el amor de Dios por ser bueno; Dios fue bueno con él, y por eso Noé quiso obedecer.',
    preguntas: ['¿Cómo era la gente en tiempos de Noé?', '¿Qué dice el versículo 22 sobre la obediencia de Noé?', '¿En qué situación te cuesta obedecer a Dios porque "todos hacen otra cosa"?'],
    aplicacion: 'Piensa en una regla de Dios que en tu escuela casi nadie sigue (decir la verdad, no burlarse, no copiar). Decide cómo obedecerla esta semana y cuéntalo en el próximo culto.',
    oracion: 'Señor, dame valor para obedecerte aunque otros no lo hagan. Gracias por tu gracia que me cuida. Amén.',
    pequenos: 'Construyan un "arca" con cojines. Noé hizo exactamente lo que Dios le dijo, ¡todo, todo, todo! Nosotros también podemos obedecer a la primera.',
    adolescentes: 'La presión de grupo existía también en tiempos de Noé. ¿Qué te ayuda a sostener convicciones cuando tu grupo piensa distinto?',
  },
  {
    id: 'h06', para: 'hijos', serie: 'Confiar en Dios', titulo: 'Abraham confió en la promesa',
    texto: 'Gn 15:1-6', memoria: 'Gn 15:6',
    contexto: 'Abram ya era anciano y no tenía hijos. Dios lo saca a mirar las estrellas y promete una descendencia innumerable. El v. 6 es clave en toda la Biblia: "Y creyó a Jehová, y contóselo por justicia". Pablo lo usa para explicar la justificación por la fe (Ro 4:3; Gá 3:6).',
    idea: 'Dios nos acepta cuando confiamos en Él, no cuando somos perfectos.',
    reflexion: 'Parecía imposible: un anciano sin hijos que iba a tener tantos descendientes como estrellas. Abraham no entendía cómo, pero creyó que Dios cumpliría. Y Dios lo consideró justo por creer.\n\nAsí nos salva Dios también: no porque nunca fallemos, sino porque confiamos en lo que Jesús hizo por nosotros.',
    preguntas: ['¿Qué le mostró Dios a Abram para explicarle su promesa?', '¿Qué significa "creyó a Jehová"?', '¿Hay algo que te cueste creer que Dios puede hacer?'],
    aplicacion: 'Esta noche, si se puede, salgan a mirar las estrellas. Intenten contarlas y recuerden que Dios cumple lo que promete.',
    oracion: 'Dios de Abraham, quiero confiar en ti aunque no entienda todo. Gracias porque me aceptas por medio de Jesús. Amén.',
    pequenos: '¿Cuántas estrellas hay? ¡Muchísimas! Dios le dijo a Abraham: "Así de grande será tu familia". Y Dios cumplió.',
    adolescentes: 'Pablo usa este versículo para explicar el evangelio. ¿Qué diferencia hay entre "ser bueno para que Dios me acepte" y "confiar en Dios, que me acepta"?',
  },
  {
    id: 'h07', para: 'hijos', serie: 'Confiar en Dios', titulo: 'José: Dios convierte lo malo en bien',
    texto: 'Gn 50:15-21', memoria: 'Gn 50:20',
    contexto: 'Al final de la historia de José, sus hermanos temen venganza. José responde con una de las afirmaciones más profundas sobre la providencia: los hermanos "pensaron mal", pero Dios "lo encaminó a bien". Ambas cosas son verdad a la vez: la responsabilidad humana y el control soberano de Dios.',
    idea: 'Dios puede usar incluso lo malo que nos pasa para hacer algo bueno.',
    reflexion: 'Los hermanos de José lo vendieron como esclavo. Luego estuvo en la cárcel injustamente. Pero Dios lo llevó a ser gobernador de Egipto y salvar a muchas familias del hambre, incluida la de sus hermanos.\n\nJosé pudo vengarse, pero perdonó. No dijo que lo que hicieron estuvo bien; dijo que Dios fue más grande que el mal que le hicieron.',
    preguntas: ['¿De qué tenían miedo los hermanos de José?', '¿Qué respondió José en el versículo 20?', '¿Recuerdas algo difícil que después Dios usó para bien?'],
    aplicacion: 'Si alguien te hizo daño esta semana, ora por esa persona por nombre. Perdonar no es decir "no pasó nada", es dejarle el asunto a Dios.',
    oracion: 'Señor, gracias porque tú estás en control incluso cuando pasan cosas malas. Ayúdame a perdonar como José. Amén.',
    pequenos: 'Arruguen una hoja y luego úsenla para hacer una bolita de nieve o una flor de papel. Dios puede hacer algo bonito aun de lo que se arruinó.',
    adolescentes: 'El texto sostiene a la vez la culpa de los hermanos y el plan de Dios. ¿Cómo te ayuda eso a no justificar el mal, pero tampoco a perder la esperanza?',
  },
  {
    id: 'h08', para: 'hijos', serie: 'Dios que libera', titulo: 'La noche de la Pascua',
    texto: 'Éx 12:21-28', memoria: 'Éx 12:13',
    contexto: 'La Pascua es el centro de la salida de Egipto: la sangre de un cordero sin defecto en los dinteles hace que el juicio "pase de largo". El v. 26 prevé que los hijos preguntarán "¿Qué es este rito?", y los padres deben explicarlo: la fe se transmite en casa. Pablo llama a Cristo "nuestra pascua" (1 Co 5:7).',
    idea: 'Jesús es nuestro Cordero: por su sangre el juicio pasa de largo.',
    reflexion: 'Dios iba a juzgar a Egipto, pero dio una salida: cada familia debía sacrificar un cordero y poner su sangre en la puerta. Donde estaba la sangre, el juicio no entraba.\n\nDios mismo dijo que los niños preguntarían qué significaba eso. ¡Tus preguntas sobre Dios le importan a Dios! Y la respuesta más grande es Jesús, el Cordero de Dios, que murió para que nosotros fuéramos libres.',
    preguntas: ['¿Qué tenían que poner las familias en la puerta?', '¿Qué pasaba en las casas donde estaba la sangre?', '¿Por qué a Jesús se le llama "el Cordero de Dios"?'],
    aplicacion: 'Invita a tus hijos a hacer cualquier pregunta sobre Dios o la Biblia. Anótenlas y respóndanlas en los próximos cultos.',
    oracion: 'Jesús, Cordero de Dios, gracias por dar tu vida para librarme. Amén.',
    pequenos: 'Recorten un cordero de papel. Jesús es como el cordero de la Pascua: Él nos protege y nos salva.',
    adolescentes: 'Lee Juan 1:29 y 1 Corintios 5:7. ¿Por qué los autores del NT explican la cruz con imágenes del AT?',
  },
  {
    id: 'h09', para: 'hijos', serie: 'Dios que libera', titulo: 'Los Diez Mandamientos: un regalo, no una jaula',
    texto: 'Éx 20:1-17', memoria: 'Éx 20:2',
    contexto: 'Los mandamientos empiezan con una declaración de gracia: "Yo soy Jehová tu Dios, que te saqué de la tierra de Egipto" (v. 2). Dios no da la ley para que Israel sea rescatado, sino a un pueblo ya rescatado. Primero redención, luego obediencia.',
    idea: 'Obedecemos a Dios porque ya nos salvó, no para que nos salve.',
    reflexion: 'Antes del primer mandamiento, Dios recuerda: "Yo te saqué de la esclavitud". Los mandamientos son como las reglas de una familia que te ama: te muestran cómo vivir libre y feliz, amando a Dios y a los demás.\n\nJesús resumió todo en dos: amar a Dios con todo el corazón y al prójimo como a uno mismo.',
    preguntas: ['¿Qué dice Dios antes de dar los mandamientos (v. 2)?', '¿Cuáles mandamientos hablan de Dios y cuáles de las personas?', '¿Cuál te cuesta más obedecer?'],
    aplicacion: 'Escriban los diez mandamientos en frases cortas y aprendan uno por día. Conviertan cada uno en una acción positiva (no robar → compartir).',
    oracion: 'Padre, gracias por rescatarme. Quiero obedecerte porque te amo. Amén.',
    pequenos: 'Cuenten con los dedos: diez reglas de Dios. Dios nos da reglas como papá y mamá: porque nos ama y quiere cuidarnos.',
    adolescentes: '¿Por qué importa el orden "rescate → ley"? ¿Cómo cambia tu obediencia si la ves como gratitud y no como examen?',
  },
  {
    id: 'h10', para: 'hijos', serie: 'Valientes con Dios', titulo: 'David y Goliat: la batalla es de Jehová',
    texto: '1 S 17:41-50', memoria: '1 S 17:47',
    contexto: 'El centro del relato no es la habilidad de David con la honda, sino su confesión: "Jehová no salva con espada y lanza; porque de Jehová es la guerra" (v. 47). David pelea para que "sepa toda la tierra que hay Dios en Israel" (v. 46). Muchos intérpretes ven en David un anticipo del Rey que vence por su pueblo.',
    idea: 'El valor verdadero viene de confiar en lo grande que es Dios, no en lo grandes que somos nosotros.',
    reflexion: 'Todo el ejército tenía miedo. Goliat era enorme y se burlaba de Dios. David era un muchacho, pero sabía quién era su Dios. No fue confiado en su fuerza, sino en el Señor.\n\nNosotros también enfrentamos "gigantes": el miedo, una enfermedad, un examen, un problema en casa. No somos más fuertes que ellos, pero Dios sí lo es.',
    preguntas: ['¿En nombre de quién fue David a pelear (v. 45)?', '¿Qué dijo David en el versículo 47?', '¿Cuál es un "gigante" que te da miedo?'],
    aplicacion: 'Cada miembro de la familia nombra un "gigante" que enfrenta. Oren unos por otros, por nombre.',
    oracion: 'Señor, tú eres más grande que cualquier problema. Dame valor para confiar en ti. Amén.',
    pequenos: 'Pongan una torre de cajas o cojines como Goliat. David no confiaba en su tamaño, sino en Dios. ¡Dios es más grande!',
    adolescentes: 'David pelea por la honra de Dios, no por fama. ¿Qué motivaciones mueven tus "batallas" (notas, deportes, redes)?',
  },
  {
    id: 'h11', para: 'hijos', serie: 'Valientes con Dios', titulo: 'Daniel oraba siempre',
    texto: 'Dn 6:10-23', memoria: 'Dn 6:10',
    contexto: 'Daniel sabe que el decreto ya fue firmado (v. 10) y aun así ora "como lo solía hacer antes". Su fidelidad no es un acto heroico repentino, sino un hábito de años. Oraba tres veces al día, con las ventanas hacia Jerusalén, recordando la promesa de 1 R 8:48-49.',
    idea: 'La fidelidad en los momentos difíciles se construye con hábitos en los días normales.',
    reflexion: 'Hicieron una ley para que nadie orara a Dios. Daniel podía esconderse o dejar de orar un mes. Pero hizo lo que siempre hacía: se arrodilló y oró, dando gracias.\n\nDaniel no se volvió valiente ese día; llevaba años hablando con Dios cada día. Por eso, cuando llegó la prueba, siguió confiando. Y Dios cerró la boca de los leones.',
    preguntas: ['¿Qué hizo Daniel cuando supo que la ley ya estaba firmada?', '¿Cada cuánto oraba Daniel?', '¿En qué momentos del día podrías orar tú?'],
    aplicacion: 'Elijan tres momentos fijos para orar esta semana (al despertar, antes de comer, al dormir) y hagan una tabla para marcarlos.',
    oracion: 'Dios de Daniel, enséñame a hablar contigo todos los días, en lo fácil y en lo difícil. Amén.',
    pequenos: 'Rujan como leones y luego "cierren la boca" con las manos: ¡Dios cerró la boca de los leones! Daniel oraba siempre.',
    adolescentes: '¿Qué hábitos espirituales tienes hoy que te sostendrían si tu fe te costara algo? ¿Cuáles necesitas empezar?',
  },
  {
    id: 'h12', para: 'hijos', serie: 'Jesús', titulo: 'Jesús, el Buen Pastor',
    texto: 'Jn 10:11-18', memoria: 'Jn 10:11',
    contexto: 'Jesús usa la fórmula "Yo soy" (egō eimi), eco del nombre de Dios en Éx 3:14. El adjetivo kalós ("buen") indica no solo bondad moral sino excelencia: el pastor verdadero, genuino, en contraste con el asalariado. Lo distintivo: "su vida da por las ovejas" (v. 11).',
    idea: 'Jesús nos conoce por nombre y dio su vida por nosotros.',
    reflexion: 'Un pastor cuida a sus ovejas: las guía, las protege y busca a la que se pierde. Jesús dice que Él es el Buen Pastor, pero hace algo que ningún pastor quiere hacer: dar su vida por las ovejas.\n\nTambién dice: "conozco mis ovejas". Jesús no te ve como uno más en la multitud; te conoce por nombre.',
    preguntas: ['¿Qué hace el buen pastor por sus ovejas?', '¿Qué hace el asalariado cuando viene el lobo?', '¿Cómo te hace sentir saber que Jesús te conoce?'],
    aplicacion: 'Lean también el Salmo 23 y hagan un dibujo del Buen Pastor. Memoricen juntos Jn 10:11.',
    oracion: 'Jesús, mi Buen Pastor, gracias por conocerme y dar tu vida por mí. Quiero seguirte. Amén.',
    pequenos: 'Jueguen a "ovejas y pastor": el pastor llama a cada oveja por su nombre. Jesús sabe tu nombre.',
    adolescentes: 'El "asalariado" huye cuando cuesta. ¿En quién estás confiando para tu seguridad: en quien te usa o en quien dio su vida por ti?',
  },
  {
    id: 'h13', para: 'hijos', serie: 'Jesús', titulo: 'El hijo que volvió a casa',
    texto: 'Lc 15:11-24', memoria: 'Lc 15:20',
    contexto: 'Pedir la herencia en vida equivalía a desear la muerte del padre. En la cultura del siglo I, un padre anciano no corría; correr era indigno. Jesús describe a un padre que se humilla para recibir al hijo antes de que termine su discurso. La parábola se dirige también a los fariseos que murmuraban (15:2), representados en el hermano mayor.',
    idea: 'Dios corre a recibir al que vuelve arrepentido.',
    reflexion: 'El hijo menor despreció a su padre, gastó todo y terminó cuidando cerdos con hambre. Pensó volver como sirviente. Pero cuando todavía estaba lejos, su padre lo vio, tuvo compasión, corrió, lo abrazó y lo besó.\n\nAsí es Dios con nosotros. No importa cuán lejos te hayas ido: si vuelves, Él sale a tu encuentro con fiesta.',
    preguntas: ['¿Qué hizo el hijo menor con la herencia?', '¿Qué hizo el padre cuando lo vio venir?', '¿Qué nos enseña esto sobre cómo es Dios?'],
    aplicacion: 'Papá y mamá: cuenten a sus hijos una vez en que ustedes se alejaron de Dios y Él los recibió. Hijos: hagan un abrazo familiar de "bienvenida".',
    oracion: 'Padre, gracias porque me recibes cuando vuelvo a ti. Quiero quedarme cerca de ti. Amén.',
    pequenos: 'Uno sale del cuarto y vuelve; los demás corren a abrazarlo. ¡Así nos recibe Dios cuando volvemos!',
    adolescentes: 'Lee el final (vv. 25-32). ¿Te pareces más al hijo que se fue o al que se quedó pero con el corazón lejos?',
  },
  {
    id: 'h14', para: 'hijos', serie: 'Jesús', titulo: '¡Resucitó!',
    texto: 'Mt 28:1-10', memoria: 'Mt 28:6',
    contexto: 'Las primeras testigos de la resurrección fueron mujeres, cuyo testimonio tenía poco peso legal en la época: un detalle que nadie inventaría. El ángel invita a "ver el lugar" (evidencia) y a "ir y decir" (misión). La resurrección es el fundamento de la fe cristiana (1 Co 15:14-17).',
    idea: 'Jesús venció la muerte, y por eso nuestra fe está viva.',
    reflexion: 'Las mujeres fueron al sepulcro esperando encontrar un cuerpo. Encontraron una tumba vacía y un ángel que dijo: "No está aquí, porque ha resucitado, como dijo".\n\nJesús había prometido que resucitaría, y cumplió. Por eso no tenemos que tener miedo a la muerte: el que está con Jesús vivirá para siempre.',
    preguntas: ['¿A qué fueron las mujeres al sepulcro?', '¿Qué les dijo el ángel?', '¿Por qué es tan importante que Jesús haya resucitado?'],
    aplicacion: 'Las mujeres corrieron a contarlo. Piensen a quién le pueden contar esta semana que Jesús está vivo.',
    oracion: 'Jesús resucitado, gracias porque venciste la muerte. Ayúdame a contarle a otros que estás vivo. Amén.',
    pequenos: 'Pongan una piedra (o un cojín) tapando una caja vacía. ¡Quítenla! Está vacía: ¡Jesús resucitó!',
    adolescentes: 'Pablo dice que si Cristo no resucitó, nuestra fe es vana. ¿Por qué la resurrección es un hecho histórico y no solo un símbolo?',
  },
  {
    id: 'h15', para: 'hijos', serie: 'Vivir como hijos de Dios', titulo: 'Honra a tu padre y a tu madre',
    texto: 'Ef 6:1-4', memoria: 'Ef 6:1',
    contexto: 'Pablo se dirige directamente a los niños, lo que supone que estaban presentes cuando se leía la carta en la iglesia. Cita el quinto mandamiento, "el primero con promesa". Inmediatamente habla a los padres: "no provoquéis a ira a vuestros hijos". La obediencia de los hijos y la paciencia de los padres van juntas.',
    idea: 'Obedecer y honrar a los padres es una manera de obedecer al Señor.',
    reflexion: 'Pablo dice "en el Señor": obedecer a papá y mamá no es solo porque ellos lo dicen, sino porque Jesús nos lo pide. Honrar es más que obedecer: es hablar con respeto, agradecer y cuidar a los padres.\n\nY Dios también habla a los papás: que no hagan enojar a sus hijos, sino que los críen con amor y enseñanza del Señor. En la familia, todos obedecemos a Dios.',
    preguntas: ['¿Qué les pide Pablo a los hijos?', '¿Qué les pide a los padres en el v. 4?', '¿Qué diferencia hay entre obedecer y honrar?'],
    aplicacion: 'Hijos: hagan algo esta semana para honrar a sus padres sin que se lo pidan. Padres: pidan perdón si han provocado a ira a sus hijos.',
    oracion: 'Señor, ayúdanos a amarnos en esta familia: a los hijos a honrar y a los padres a guiar con paciencia. Amén.',
    pequenos: 'Obedecer "a la primera, con alegría y completo". Practiquen con instrucciones divertidas: "¡Tócate la nariz!".',
    adolescentes: '¿Cómo se honra a los padres cuando no estás de acuerdo con ellos? ¿Qué parte de este texto es para tus padres y cómo orarías por ellos?',
  },

  // ======================================================================= ESPOSA
  {
    id: 'a01', para: 'esposa', serie: 'Identidad en Cristo', titulo: 'Escogida antes de la fundación del mundo',
    texto: 'Ef 1:3-8', memoria: 'Ef 1:4',
    contexto: 'Ef 1:3-14 es una sola oración en griego, un himno de alabanza trinitario. Las bendiciones son "en Cristo" (la expresión aparece una y otra vez) y "en lugares celestiales": son reales ya, aunque no siempre visibles. La elección tiene un propósito: "que fuésemos santos y sin mancha delante de él en amor".',
    idea: 'Tu identidad no depende de tu rol ni de tu rendimiento, sino de la elección amorosa de Dios en Cristo.',
    reflexion: 'En el ministerio es fácil que la identidad se mezcle con el rol: "la esposa del pastor", "la que siempre ayuda", "la que no puede fallar". Pablo te recuerda algo anterior a todo rol: antes de que existiera el mundo, Dios ya te había escogido en Cristo, te adoptó como hija y te perdonó conforme a las riquezas de su gracia.\n\nLas expectativas de la congregación cambian; la elección de Dios no. Descansar en esto no te hace menos diligente, te hace libre: sirves desde la aceptación, no para conseguirla.',
    preguntas: ['¿Cuáles de las bendiciones de los vv. 3-8 te cuesta más creer que son para ti hoy?', '¿Qué expectativas (propias o ajenas) están ocupando el lugar de tu identidad en Cristo?', '¿Cómo cambiaría tu semana si sirvieras desde la aceptación y no para ganarla?'],
    aplicacion: 'Escribe en una tarjeta "Escogida, adoptada, redimida, perdonada (Ef 1:4-7)" y ponla donde la veas cada mañana.',
    oracion: 'Padre, gracias porque me escogiste en Cristo antes de todo. Sácame de la tiranía de las expectativas y enséñame a servir desde tu amor. Amén.',
  },
  {
    id: 'a02', para: 'esposa', serie: 'Identidad en Cristo', titulo: 'Ayuda idónea: una palabra de fuerza',
    texto: 'Gn 2:18-24', memoria: 'Gn 2:18',
    contexto: 'La expresión hebrea ʿézer kenegdó ("ayuda idónea") no implica inferioridad: ʿézer se usa mayormente para Dios mismo como ayuda de su pueblo (Sal 33:20; 121:1-2). Kenegdó significa "correspondiente a él", "frente a él": alguien a su altura. Lo único "no bueno" en la creación es que el hombre esté solo.',
    idea: 'Ser ayuda idónea es reflejar a Dios, que es la Ayuda de su pueblo.',
    reflexion: 'A veces "ayuda idónea" se ha entendido como asistente o figura secundaria. Pero la palabra que Dios usa es la misma con que se describe a sí mismo: "Nuestra ayuda está en el nombre de Jehová". Tu llamado no es pequeño; es un reflejo de cómo Dios sostiene, fortalece y acompaña.\n\nEn un matrimonio pastoral, esto significa que tu voz, tu discernimiento y tus dones no son accesorios: son parte de cómo Dios completa lo que "no es bueno" que esté solo.',
    preguntas: ['¿Qué te revela que ʿézer se use sobre todo para Dios?', '¿En qué áreas tu esposo necesita tu perspectiva y quizá no la has ofrecido?', '¿Dónde necesitas tú ayuda, y a quién se la has pedido?'],
    aplicacion: 'Conversa con tu esposo sobre un área del ministerio o del hogar donde tus dones podrían aportar más, y pregúntale cómo verlo juntos.',
    oracion: 'Señor, tú eres mi Ayuda. Hazme reflejo de tu fortaleza y tu fidelidad en mi matrimonio. Amén.',
  },
  {
    id: 'a03', para: 'esposa', serie: 'Identidad en Cristo', titulo: 'La mujer virtuosa teme a Jehová',
    texto: 'Pr 31:10-31', memoria: 'Pr 31:30',
    contexto: 'Pr 31:10-31 es un poema acróstico: cada versículo empieza con una letra sucesiva del alfabeto hebreo, como diciendo "la sabiduría de la A a la Z". La expresión ʾéshet jáyil ("mujer virtuosa") usa jáyil, término de fuerza, valor y capacidad (el mismo usado para guerreros). El clímax no es la productividad, sino el temor de Jehová (v. 30).',
    idea: 'La virtud que Dios alaba nace del temor de Jehová, no de la perfección en todo.',
    reflexion: 'Este pasaje puede leerse como una lista imposible: se levanta de noche, compra campos, teje, vende, enseña, cuida. Pero es un poema, no un horario; retrata la sabiduría encarnada a lo largo de una vida, no en una semana.\n\nY el versículo que lo sostiene todo es el 30: "la mujer que teme a Jehová, esa será alabada". Tu valor ante Dios no está en hacerlo todo, sino en vivir delante de Él con reverencia y confianza.',
    preguntas: ['¿Leías este pasaje como un ideal inalcanzable? ¿Qué cambia al saber que es un poema acróstico?', '¿Qué significa para ti "temer a Jehová" en tu rutina concreta?', '¿Qué rasgo del poema ves que Dios ya está formando en ti?'],
    aplicacion: 'Elige un solo rasgo del poema (fuerza, generosidad, sabiduría al hablar, v. 26) y pide a Dios crecer en él este mes. Suelta la culpa por los demás.',
    oracion: 'Dios, líbrame de medirme por listas imposibles. Forma en mí el temor de tu nombre, que es el principio de la sabiduría. Amén.',
  },
  {
    id: 'a04', para: 'esposa', serie: 'Descanso y cuidado del alma', titulo: 'Venid a mí… y yo os haré descansar',
    texto: 'Mt 11:28-30', memoria: 'Mt 11:28',
    contexto: 'Jesús habla a los "trabajados y cargados" bajo el peso de la tradición religiosa. El yugo era también una imagen rabínica para la enseñanza de un maestro ("el yugo de la Torá"). El yugo de Jesús es "fácil" (jrēstós: bueno, que se ajusta bien). Él no elimina el trabajo, cambia la carga y el compañero de yugo.',
    idea: 'El descanso que Jesús ofrece no es ausencia de trabajo, sino cambiar de yugo y de compañero.',
    reflexion: 'El ministerio cansa de una manera particular: cargas emocionales ajenas, horarios impredecibles, la sensación de estar siempre "disponible". Jesús no dice "descansa cuando termines"; dice "venid a mí" ahora, en medio de la carga.\n\nSu yugo se ajusta bien porque Él lo lleva contigo. Descansar en Cristo también implica decisiones concretas: límites, pausas, pedir ayuda. No es falta de fe; es aprender de Aquel que es "manso y humilde de corazón".',
    preguntas: ['¿Qué cargas llevas que Jesús nunca te pidió llevar?', '¿Cómo se ve para ti "aprender de mí, que soy manso y humilde"?', '¿Qué límite concreto necesitas poner esta semana?'],
    aplicacion: 'Programa en tu semana un tiempo de descanso real (no productivo) y protégelo como protegerías una cita importante.',
    oracion: 'Jesús, vengo a ti cansada. Toma lo que no me toca cargar y enséñame a caminar a tu ritmo. Amén.',
  },
  {
    id: 'a05', para: 'esposa', serie: 'Descanso y cuidado del alma', titulo: 'Echando toda ansiedad sobre Él',
    texto: '1 P 5:6-10', memoria: '1 P 5:7',
    contexto: 'En griego, el v. 7 es un participio que depende del v. 6: "humillaos… echando toda vuestra ansiedad sobre él". Echar la ansiedad sobre Dios es una forma de humildad: reconocer que no controlamos todo. Pedro escribe a creyentes que sufrían por su fe, y promete que Dios mismo "os perfeccione, confirme, fortalezca y establezca" (v. 10).',
    idea: 'Entregar la ansiedad a Dios es un acto de humildad, no de debilidad.',
    reflexion: 'La ansiedad a menudo esconde una convicción silenciosa: "si yo no lo sostengo, todo se cae". Pedro une dos verbos que parecen distintos: humillarse y echar la ansiedad. Confiar a Dios lo que nos preocupa es admitir que Él es Dios y nosotros no.\n\nY la razón no es una técnica, sino una persona: "porque él tiene cuidado de vosotros". El mismo pasaje advierte sobre el adversario; la ansiedad no entregada se convierte en terreno donde él trabaja.',
    preguntas: ['¿Qué te preocupa hoy que estás intentando controlar sola?', '¿Por qué crees que Pedro relaciona la ansiedad con la humildad?', '¿Qué promesa del v. 10 necesitas recibir?'],
    aplicacion: 'Haz una lista de tus preocupaciones actuales. Ora por cada una en voz alta, diciendo: "Esto te lo entrego porque tú cuidas de mí".',
    oracion: 'Señor, me humillo bajo tu poderosa mano. Te entrego cada ansiedad. Perfecciona, confirma y fortalece mi fe. Amén.',
  },
  {
    id: 'a06', para: 'esposa', serie: 'Descanso y cuidado del alma', titulo: 'Marta y María: lo necesario',
    texto: 'Lc 10:38-42', memoria: 'Lc 10:42',
    contexto: 'Sentarse "a los pies" de un maestro era la postura del discípulo (cf. Hch 22:3, Pablo a los pies de Gamaliel). Que María ocupe ese lugar era llamativo para la época. Marta estaba "distraída" (periespáto: tironeada en muchas direcciones) con "mucho servicio" (diakonía). Jesús no desprecia el servicio, sino el afán que desplaza lo esencial.',
    idea: 'El servicio fiel brota de estar primero a los pies de Jesús.',
    reflexion: 'Marta no hacía nada malo: servía, recibía, trabajaba. Pero estaba tironeada por muchas cosas, y eso la llevó a la queja y a la comparación. María eligió "la buena parte": escuchar a Jesús.\n\nPara quien sirve en el ministerio, el peligro no es la pereza, sino que el servicio a Jesús reemplace el tiempo con Jesús. Jesús te invita, no a dejar de servir, sino a empezar donde empezó María.',
    preguntas: ['¿En qué te pareces a Marta esta semana?', '¿Qué "muchas cosas" te tironean ahora mismo?', '¿Cómo puedes proteger "la buena parte" en tu rutina?'],
    aplicacion: 'Antes de cualquier tarea mañana, dedica 15 minutos solo a leer y orar, sin teléfono. Nota cómo cambia el resto del día.',
    oracion: 'Jesús, quiero sentarme a tus pies antes de servirte. Ordena mi corazón y mis prioridades. Amén.',
  },
  {
    id: 'a07', para: 'esposa', serie: 'Sabiduría para el hogar', titulo: 'La mujer sabia edifica su casa',
    texto: 'Pr 14:1; 24:3-4', memoria: 'Pr 14:1',
    contexto: 'En Proverbios, la sabiduría (jokmá) no es erudición, sino la habilidad de vivir bien en el mundo de Dios. "Edificar la casa" incluye el hogar físico, la familia y el legado. El contraste es fuerte: la necia "con sus manos la derriba", a veces sin darse cuenta.',
    idea: 'Cada día, con pequeñas decisiones, edificamos o derribamos nuestra casa.',
    reflexion: 'Nadie decide destruir su casa en un día. Las casas se derriban poco a poco: con palabras duras, con amarguras no resueltas, con prioridades desordenadas. Y se edifican igual: con sabiduría, inteligencia y ciencia (24:3-4), aplicadas en lo cotidiano.\n\nLa sabiduría para edificar se pide a Dios (Stg 1:5). No tienes que tenerla toda; tienes que buscarla cada día.',
    preguntas: ['¿Qué hábitos están edificando tu casa?', '¿Hay algo que, sin darte cuenta, podría estar derribándola?', '¿Qué "tesoro precioso" (24:4) quieres que llene tu hogar?'],
    aplicacion: 'Identifica una práctica pequeña que edifique (una comida sin pantallas, una palabra de afirmación diaria) y comiénzala hoy.',
    oracion: 'Señor, dame sabiduría para edificar mi casa. Muéstrame lo que la derriba y dame gracia para cambiar. Amén.',
  },
  {
    id: 'a08', para: 'esposa', serie: 'Sabiduría para el hogar', titulo: 'Palabras sazonadas con sal',
    texto: 'Col 4:5-6; Pr 31:26', memoria: 'Col 4:6',
    contexto: 'En el mundo grecorromano, la "sal" en el hablar se asociaba con ingenio y gracia. Pablo pide que la palabra sea "siempre con gracia (járis)": la misma palabra para la gracia de Dios. Pr 31:26 describe a la mujer virtuosa: "abre su boca con sabiduría, y la ley de clemencia (tórat jésed) está en su lengua".',
    idea: 'La gracia que recibimos de Dios debe notarse en cómo hablamos.',
    reflexion: 'La esposa de un pastor habla con muchas personas: hermanos heridos, líderes, vecinos, sus propios hijos. Pablo pide que cada conversación esté marcada por la gracia: palabras que no endulzan la verdad, pero que la hacen agradable y nutritiva, como la sal.\n\nProverbios va más lejos: la "ley de la clemencia" en la lengua. Es decir, que la bondad sea tu regla al hablar, especialmente en casa, donde es más fácil olvidarla.',
    preguntas: ['¿Con quién te cuesta más hablar con gracia?', '¿Cómo se ve la diferencia entre ser amable y ser complaciente?', '¿Qué palabra de gracia puedes decir hoy a alguien de tu casa?'],
    aplicacion: 'Durante tres días, antes de responder en momentos tensos, haz una pausa y pregúntate: "¿Esto está sazonado con gracia?".',
    oracion: 'Señor, pon tu ley de clemencia en mi lengua. Que mis palabras den gracia a los que me oyen. Amén.',
  },
  {
    id: 'a09', para: 'esposa', serie: 'Sabiduría para el hogar', titulo: 'Criar en la fe: el ejemplo de Loida y Eunice',
    texto: '2 Ti 1:3-7; 3:14-15', memoria: '2 Ti 3:15',
    contexto: 'Pablo atribuye la fe de Timoteo a su abuela Loida y su madre Eunice (1:5). Su padre era griego (Hch 16:1), probablemente no creyente. Timoteo conoció "las Sagradas Escrituras" "desde la niñez" (apo bréfous: desde bebé). La fe "no fingida" (anypókritos) se transmitió por convivencia auténtica, no solo por enseñanza formal.',
    idea: 'La fe se transmite por Escritura enseñada y vida auténtica, desde muy temprano.',
    reflexion: 'Timoteo llegó a ser pastor y colaborador de Pablo, y la raíz de su fe fue un hogar donde dos mujeres enseñaron la Palabra y vivieron una fe sin máscara. No hay mención de grandes programas: solo Escrituras desde bebé y fe genuina.\n\nEn un hogar pastoral, los hijos ven el ministerio por dentro. Lo que más los forma no es cuánto sabes, sino que vean que tu fe es real en la cocina igual que en el templo.',
    preguntas: ['¿Quién sembró la fe en tu vida en la niñez?', '¿Qué ven tus hijos de tu fe cuando nadie de la iglesia está mirando?', '¿Cómo puedes hacer más natural la Escritura en el día a día de tu casa?'],
    aplicacion: 'Escoge un versículo para la semana y úsalo naturalmente en conversaciones con tus hijos (al llevarlos, al cocinar, al dormir).',
    oracion: 'Señor, hazme como Loida y Eunice: que mi fe sea sin fingimiento y que mis hijos conozcan tu Palabra desde pequeños. Amén.',
  },
  {
    id: 'a10', para: 'esposa', serie: 'Ministerio y llamado', titulo: 'Febe, Priscila y las colaboradoras de Pablo',
    texto: 'Ro 16:1-7', memoria: 'Ro 16:3-4',
    contexto: 'Pablo recomienda a Febe, diákonos de la iglesia en Cencrea y "ayudadora (prostátis: patrona, protectora) de muchos", probablemente portadora de la carta a Roma. Menciona a Priscila antes que a Aquila, pareja que "expusieron su vida" por él y tenían una iglesia en su casa. Ro 16 muestra a muchas mujeres activas en la obra.',
    idea: 'Dios usa a mujeres fieles de manera decisiva en la extensión del evangelio.',
    reflexion: 'Romanos, quizá la carta más importante de la teología cristiana, termina con una lista de nombres. Muchos son mujeres: Febe, Priscila, María, Trifena, Trifosa, Pérsida "la cual ha trabajado mucho en el Señor". Pablo las conoce, las honra y reconoce su trabajo.\n\nTu servicio, muchas veces invisible, es visto y recordado por Dios. Hospitalidad, discipulado, intercesión, protección de otros: son parte del mismo evangelio que Pablo expuso en los capítulos anteriores.',
    preguntas: ['¿Qué te llama la atención de la manera en que Pablo habla de estas mujeres?', '¿Qué parte de tu servicio sientes que nadie ve?', '¿A qué mujer podrías animar esta semana reconociendo su trabajo?'],
    aplicacion: 'Escribe una nota de gratitud a una mujer de la iglesia que sirve en silencio, como Pablo hizo en Romanos 16.',
    oracion: 'Señor, gracias porque ves el trabajo hecho en tu nombre. Úsame, y ayúdame a honrar a quienes sirven a mi lado. Amén.',
  },
  {
    id: 'a11', para: 'esposa', serie: 'Ministerio y llamado', titulo: 'Ana: el dolor derramado ante Dios',
    texto: '1 S 1:9-18', memoria: '1 S 1:15',
    contexto: 'Ana sufre la esterilidad y la provocación de Penina año tras año. En el templo, ora "con amargura de alma" y llora abundantemente; Elí la confunde con una ebria. Su respuesta es clave: "he derramado mi alma delante de Jehová". Después de orar "no estuvo más triste" (v. 18), antes de ver la respuesta.',
    idea: 'Dios recibe la oración sincera del corazón herido.',
    reflexion: 'Ana no disimuló su dolor delante de Dios. No oró bonito; derramó el alma. Incluso el sacerdote la malinterpretó. Muchas veces, en el ministerio, se espera que la esposa del pastor esté siempre bien. Pero Dios no te pide fingir.\n\nLo notable es que la paz de Ana llegó después de orar, no después de recibir. La oración honesta cambió su corazón antes de que cambiara su situación.',
    preguntas: ['¿Qué dolor estás guardando en lugar de derramarlo ante Dios?', '¿Te has sentido malinterpretada como Ana? ¿Cómo respondió ella?', '¿Qué significa para ti que Ana "no estuvo más triste" antes de ver la respuesta?'],
    aplicacion: 'Aparta un tiempo a solas para orar con total honestidad, incluso escribiendo tu oración como un salmo de lamento.',
    oracion: 'Dios, aquí derramo mi alma delante de ti. Tú conoces mi dolor. Dame tu paz mientras espero. Amén.',
  },
  {
    id: 'a12', para: 'esposa', serie: 'Ministerio y llamado', titulo: 'La hospitalidad como ministerio',
    texto: 'Ro 12:9-13; 1 P 4:8-10', memoria: '1 P 4:9',
    contexto: 'La palabra griega para hospitalidad, filoxenía, significa literalmente "amor al extraño". En la iglesia primitiva los hogares eran lugares de culto, hospedaje de misioneros y cuidado de necesitados. Pedro añade "sin murmuraciones": la hospitalidad puede volverse carga resentida.',
    idea: 'Abrir la casa es abrir el evangelio; pero debe hacerse con gozo, no con queja.',
    reflexion: 'Los hogares pastorales suelen ser lugares de paso: reuniones, visitas, personas en crisis. La Biblia llama a eso ministerio. Pero Pedro sabe que la hospitalidad también cansa, y pide que sea "sin murmuraciones".\n\nLa hospitalidad bíblica no es perfección decorativa, sino amor al extraño: una mesa sencilla, una conversación atenta. Y también incluye sabiduría: saber cuándo abrir y cuándo cuidar el descanso de tu familia.',
    preguntas: ['¿Vives la hospitalidad como gozo o como carga?', '¿Qué necesitas soltar (perfeccionismo, comparación) para abrir tu casa con libertad?', '¿Qué límites protegen a tu familia sin cerrar la puerta?'],
    aplicacion: 'Planifica una comida sencilla con alguien nuevo en la iglesia, sin preparativos excesivos.',
    oracion: 'Señor, hazme hospitalaria como tú, que me recibiste a mí. Dame gozo y sabiduría en abrir mi casa. Amén.',
  },
  {
    id: 'a13', para: 'esposa', serie: 'Fe en la prueba', titulo: 'Sara: nada es difícil para Dios',
    texto: 'Gn 18:9-15; He 11:11', memoria: 'Gn 18:14',
    contexto: 'Sara ríe incrédula al oír la promesa; el nombre de su hijo, Isaac (Yitsjaq), significa "él ríe". Dios responde con la pregunta retórica "¿Hay para Dios alguna cosa difícil?" (usando pala, "maravilloso", "demasiado difícil"). Hebreos 11:11 recuerda a Sara como mujer de fe: la incredulidad inicial no fue la última palabra.',
    idea: 'Dios es fiel aun cuando nuestra fe vacila.',
    reflexion: 'Sara se rió por dentro: era demasiado tarde, demasiado imposible. Dios no la rechazó por eso; le hizo una pregunta: "¿Hay algo difícil para Dios?". Tiempo después, Sara se reía de alegría con Isaac en brazos.\n\nHebreos la incluye entre los héroes de la fe. Qué consuelo: Dios no escribe tu historia con tus momentos de duda, sino con su fidelidad.',
    preguntas: ['¿Qué promesa de Dios te ha parecido "demasiado tarde" o imposible?', '¿Cómo te consuela que Sara aparezca en Hebreos 11?', '¿Cómo respondes a la pregunta del v. 14 en tu situación actual?'],
    aplicacion: 'Escribe la pregunta "¿Hay para Dios alguna cosa difícil?" y debajo la situación que te desafía. Ora con ella cada día esta semana.',
    oracion: 'Dios fiel, perdona mi incredulidad. Tú puedes hacer lo imposible. Enséñame a esperar en ti. Amén.',
  },
  {
    id: 'a14', para: 'esposa', serie: 'Fe en la prueba', titulo: 'Mi gracia te basta',
    texto: '2 Co 12:7-10', memoria: '2 Co 12:9',
    contexto: 'Pablo pidió tres veces que se le quitara el "aguijón en la carne", cuya naturaleza exacta el texto no revela. La respuesta de Cristo está en tiempo perfecto: "Bástate (arkeî) mi gracia", una suficiencia que permanece. El poder "se perfecciona" (teleîtai: llega a su plenitud) en la debilidad.',
    idea: 'La debilidad no es un obstáculo para el poder de Dios, sino el lugar donde se muestra.',
    reflexion: 'Pablo oró tres veces y la respuesta fue "no", pero con una promesa mejor: "mi gracia te basta". Dios no siempre quita el aguijón; a veces da gracia suficiente para cada día con él.\n\nEn el ministerio se valora la fortaleza. Pero Dios dice que su poder se ve mejor en vasos frágiles. Tu cansancio, tu enfermedad o tu límite no te descalifican; pueden ser el escenario de su gracia.',
    preguntas: ['¿Qué "aguijón" le has pedido a Dios que quite?', '¿Qué significa para ti que su gracia "baste" hoy, no mañana?', '¿Cómo podrías gloriarte en tu debilidad sin negarla?'],
    aplicacion: 'Comparte con una amiga de confianza una debilidad que sueles esconder, y pídele que ore contigo.',
    oracion: 'Señor, tu gracia me basta. Muestra tu poder en mi debilidad. Amén.',
  },
  {
    id: 'a15', para: 'esposa', serie: 'Fe en la prueba', titulo: 'Esperar en silencio: Salmo 62',
    texto: 'Sal 62:1-8', memoria: 'Sal 62:5',
    contexto: 'El Salmo 62 repite la partícula hebrea ʾaj ("solamente", "ciertamente") seis veces, subrayando que solo Dios es refugio. "En silencio" (dumiyyá) no es pasividad, sino quietud confiada. El v. 8 invita a "derramar el corazón" delante de Él, como Ana.',
    idea: 'Solo en Dios reposa el alma; todo otro apoyo es provisional.',
    reflexion: 'David estaba rodeado de personas que lo atacaban con palabras (v. 4). En vez de defenderse con más palabras, dice: "Alma mía, en Dios solamente reposa". Repite "solamente" una y otra vez, como quien se convence a sí mismo.\n\nA veces el silencio delante de Dios es la respuesta más poderosa ante la crítica o la incertidumbre. No porque no importe, sino porque Él es tu roca.',
    preguntas: ['¿En qué, además de Dios, buscas reposo para tu alma?', '¿Cómo se ve para ti "esperar en silencio" ante una crítica?', '¿Qué necesitas "derramar" delante de Él hoy (v. 8)?'],
    aplicacion: 'Dedica cinco minutos en silencio total ante Dios, repitiendo solo el v. 5, antes de empezar el día.',
    oracion: 'Dios, solo en ti reposa mi alma. Tú eres mi roca y mi refugio. Amén.',
  },

  // ======================================================================= ESPOSO
  {
    id: 'o01', para: 'esposo', serie: 'Liderazgo de siervo', titulo: 'Amar como Cristo amó a la iglesia',
    texto: 'Ef 5:25-33', memoria: 'Ef 5:25',
    contexto: 'El imperativo a los maridos es agapáte ("amad"), no "gobernad". La medida es Cristo, que "se entregó a sí mismo" (paredóken heautón). El propósito del amor de Cristo es santificar y presentar a la iglesia "gloriosa". Ef 5:21 enmarca todo: "sujetos los unos a los otros en el temor de Dios".',
    idea: 'El liderazgo del esposo se mide por la entrega de Cristo, no por la autoridad.',
    reflexion: 'Pablo pudo decir "maridos, mandad", pero dijo "amad, así como Cristo amó a la iglesia, y se entregó a sí mismo por ella". Es un llamado mucho más exigente: el esposo debe dar primero, sacrificarse primero, servir primero.\n\nPara un pastor, el riesgo es entregarse a la iglesia y dar a su esposa lo que sobra. Pero Pablo pone el amor a la esposa como la imagen misma del amor de Cristo por su iglesia. Tu matrimonio es tu primer sermón.',
    preguntas: ['¿Qué ha sacrificado Cristo por su iglesia que tú puedas imitar esta semana?', '¿Recibe tu esposa lo mejor de ti o lo que sobra del ministerio?', '¿Cómo contribuyes a que tu esposa florezca ("gloriosa") en su fe y sus dones?'],
    aplicacion: 'Pregúntale a tu esposa: "¿En qué área te sentirías más amada si yo cambiara algo?". Escucha sin defenderte y actúa.',
    oracion: 'Señor Jesús, que me amaste hasta la cruz, enséñame a amar a mi esposa como tú amas a tu iglesia. Amén.',
  },
  {
    id: 'o02', para: 'esposo', serie: 'Liderazgo de siervo', titulo: 'El que quiera ser grande, sea servidor',
    texto: 'Mr 10:35-45', memoria: 'Mr 10:45',
    contexto: 'Santiago y Juan piden los lugares de honor. Jesús contrasta el modelo de "los gobernantes de las naciones" que "se enseñorean" (katakyrieúousin) con el reino: el grande es diákonos, el primero es doûlos (esclavo). El v. 45 es la clave del evangelio de Marcos: el Hijo del hombre vino a servir y dar su vida "en rescate (lýtron) por muchos".',
    idea: 'En el reino de Dios, la grandeza se mide por el servicio.',
    reflexion: 'Los discípulos querían posiciones; Jesús les habló de una copa y un bautismo de sufrimiento. Luego dio la definición de liderazgo del reino: el que quiera ser el primero, será siervo de todos.\n\nEn casa, liderar como Jesús significa ser el primero en servir, el primero en pedir perdón, el primero en orar, el primero en cargar lo pesado. No hay tarea "debajo" de un pastor, porque no hubo tarea debajo de Jesús.',
    preguntas: ['¿Dónde buscas reconocimiento más que servicio?', '¿Qué tarea en tu casa consideras "no mía" y podrías asumir con humildad?', '¿Cómo modelas el v. 45 ante tus hijos?'],
    aplicacion: 'Asume esta semana una tarea doméstica que normalmente hace tu esposa, sin anunciarlo ni esperar gratitud.',
    oracion: 'Hijo del hombre que viniste a servir, líbrame de buscar grandeza. Hazme siervo en mi casa y en tu iglesia. Amén.',
  },
  {
    id: 'o03', para: 'esposo', serie: 'Liderazgo de siervo', titulo: 'Vivid sabiamente con ellas',
    texto: '1 P 3:7', memoria: '1 P 3:7',
    contexto: 'Literalmente: "vivid juntos conforme a conocimiento (katá gnôsin)". El marido debe conocer a su esposa, su mundo y sus necesidades. "Vaso más frágil" no alude a inferioridad espiritual (ella es "coheredera de la gracia de la vida"), sino a vulnerabilidad en un mundo donde la mujer tenía menos protección. La advertencia es seria: descuidarla estorba las oraciones.',
    idea: 'Conocer y honrar a tu esposa es condición para una vida de oración sin estorbo.',
    reflexion: 'Pedro pide a los maridos que vivan con sus esposas "según ciencia": estudiándolas, entendiéndolas. Un pastor puede conocer bien a su congregación y poco a la mujer que duerme a su lado: sus miedos, sus sueños, lo que la cansa.\n\nY añade algo que debería detenernos: si no la honramos como coheredera, nuestras oraciones tienen estorbo. La vida espiritual pública del pastor está conectada con cómo trata a su esposa en privado.',
    preguntas: ['¿Qué sabes hoy de las preocupaciones más profundas de tu esposa?', '¿Cómo la honras como "coheredera de la gracia"?', '¿Hay algo en tu trato con ella que pueda estar estorbando tus oraciones?'],
    aplicacion: 'Aparta una cita semanal solo para escucharla. Haz preguntas abiertas y toma nota mental de lo que necesita.',
    oracion: 'Señor, enséñame a conocer a mi esposa y a honrarla como coheredera de tu gracia. Quita todo estorbo de mis oraciones. Amén.',
  },
  {
    id: 'o04', para: 'esposo', serie: 'Integridad', titulo: 'Irreprensible: el carácter antes que el don',
    texto: '1 Ti 3:1-7', memoria: '1 Ti 3:2',
    contexto: 'La lista de requisitos del obispo (epískopos) es casi toda de carácter, no de habilidades; solo "apto para enseñar" es una capacidad. Irreprensible (anepílēmptos) significa que no haya de qué acusarlo con fundamento. "Marido de una sola mujer" (literalmente "hombre de una mujer") apunta a fidelidad conyugal. El v. 5 conecta el gobierno de la casa con el cuidado de la iglesia.',
    idea: 'Dios evalúa al pastor primero por su carácter y su casa.',
    reflexion: 'Es sorprendente lo poco que Pablo habla de talento en esta lista. Dios no pide un orador brillante, sino un hombre sobrio, prudente, hospitalario, no pendenciero, no avaro, que cuida bien su casa.\n\nEl ministerio público puede ocultar grietas privadas por un tiempo, pero no para siempre. Examinar esta lista cada cierto tiempo, con honestidad y ante alguien de confianza, es una forma de proteger tu matrimonio, tu familia y tu iglesia.',
    preguntas: ['¿Qué requisito de la lista te confronta más hoy?', '¿Quién tiene permiso para preguntarte sobre tu integridad?', '¿Qué relación ves entre cómo gobiernas tu casa y cómo pastoreas?'],
    aplicacion: 'Revisa la lista con tu esposa o un colega de confianza y pídeles que te digan con honestidad dónde necesitas crecer.',
    oracion: 'Señor, forma en mí un carácter irreprensible. Que mi casa sea el primer lugar donde se vea tu gracia. Amén.',
  },
  {
    id: 'o05', para: 'esposo', serie: 'Integridad', titulo: 'Hice pacto con mis ojos',
    texto: 'Job 31:1-4; Mt 5:27-30', memoria: 'Job 31:1',
    contexto: 'Job, en su última defensa, afirma haber hecho "pacto" (berit) con sus ojos: una decisión previa, no una reacción en el momento. Jesús radicaliza el mandamiento: el adulterio comienza en la mirada con intención (pros to epithymêsai). La imagen de sacar el ojo es hiperbólica, pero exige medidas drásticas contra el pecado.',
    idea: 'La pureza se decide antes de la tentación, con límites firmes.',
    reflexion: 'Job no esperaba a estar frente a la tentación para decidir: había hecho un pacto antes. Jesús enseña que el pecado sexual empieza en la mirada y el deseo, y pide tomar medidas radicales.\n\nEn la era digital, esto implica decisiones concretas: filtros, rendición de cuentas, horarios, dispositivos fuera del dormitorio. No es legalismo; es sabiduría para proteger tu matrimonio y tu ministerio, que tanto le importan a Dios.',
    preguntas: ['¿Qué "pacto" concreto has hecho con tus ojos?', '¿Dónde eres más vulnerable (horarios, dispositivos, cansancio)?', '¿Quién te pide cuentas en esta área?'],
    aplicacion: 'Implementa una medida concreta esta semana (filtro, compañero de rendición de cuentas, dispositivo fuera del cuarto) y cuéntasela a alguien.',
    oracion: 'Señor, hago pacto con mis ojos. Guárdame puro para mi esposa y para ti. Amén.',
  },
  {
    id: 'o06', para: 'esposo', serie: 'Integridad', titulo: 'Guarda tu corazón',
    texto: 'Pr 4:20-27', memoria: 'Pr 4:23',
    contexto: 'En la antropología hebrea, el corazón (leb) es el centro de la vida interior: pensamiento, voluntad y emociones. "Sobre toda cosa guardada" (mikkol-mishmar) sugiere guardarlo con más vigilancia que cualquier otra cosa. El pasaje recorre el cuerpo: oídos, ojos, boca, pies. La integridad es integral.',
    idea: 'Lo que guardas en el corazón determina el rumbo de tu vida.',
    reflexion: 'Los pastores cuidan corazones ajenos todo el tiempo, y pueden descuidar el propio. Salomón dice que del corazón "mana la vida": lo que está dentro termina saliendo en palabras, miradas y pasos.\n\nGuardar el corazón es vigilar qué escuchas, qué miras, qué dices y a dónde vas. Es revisar resentimientos, ambiciones y cansancios antes de que se conviertan en decisiones.',
    preguntas: ['¿Qué está entrando en tu corazón por los oídos y los ojos esta semana?', '¿Hay algún resentimiento o ambición que necesitas revisar?', '¿Cómo cuidas tu propio corazón mientras cuidas los de otros?'],
    aplicacion: 'Haz un examen breve cada noche esta semana: ¿qué entró hoy a mi corazón? ¿qué salió de él?',
    oracion: 'Señor, examina mi corazón. Ayúdame a guardarlo sobre toda cosa, porque de él mana la vida. Amén.',
  },
  {
    id: 'o07', para: 'esposo', serie: 'Paternidad', titulo: 'Estas palabras estarán en tu corazón',
    texto: 'Dt 6:4-9', memoria: 'Dt 6:6-7',
    contexto: 'El Shemá (Escucha, Israel) es la confesión central de Israel. Antes de enseñar a los hijos, las palabras deben estar "sobre tu corazón" (v. 6). La enseñanza es "repetida" (shinnantám: afilarlas, inculcarlas) en cuatro momentos: sentado en casa, andando, al acostarse y al levantarse. La fe se enseña en la vida diaria, no solo en momentos formales.',
    idea: 'El padre transmite la fe primero viviéndola y luego conversándola en lo cotidiano.',
    reflexion: 'El orden importa: primero amar a Dios con todo, luego tener sus palabras en el corazón, y solo después enseñarlas a los hijos. No podemos dar lo que no tenemos.\n\nY la enseñanza no se limita al culto familiar: ocurre en el auto, en la mesa, al acostarlos. Para un pastor que predica cada domingo, el desafío es que sus hijos también reciban la Palabra en conversaciones naturales y personales.',
    preguntas: ['¿Tus hijos te ven amar a Dios fuera del púlpito?', '¿En cuál de los cuatro momentos (casa, camino, acostarse, levantarse) puedes hablar más de Dios?', '¿Qué preguntas de fe tienen tus hijos ahora?'],
    aplicacion: 'Elige un momento cotidiano (el trayecto a la escuela, la hora de dormir) para conversar sobre Dios de forma natural esta semana.',
    oracion: 'Dios, que tus palabras estén primero en mi corazón, y enséñame a transmitirlas a mis hijos en lo cotidiano. Amén.',
  },
  {
    id: 'o08', para: 'esposo', serie: 'Paternidad', titulo: 'No provoquéis a ira a vuestros hijos',
    texto: 'Ef 6:4; Col 3:21', memoria: 'Ef 6:4',
    contexto: 'Pablo se dirige a los padres (pateres), responsables de la educación en la cultura romana, donde la patria potestas daba enorme poder al padre. Contra esa cultura, prohíbe provocar a ira (parorgízete) y, en Colosenses, "exasperar" para que no se desalienten (athymôsin). Lo positivo: criar "en disciplina (paideía) y amonestación (nouthesía) del Señor".',
    idea: 'La disciplina bíblica corrige sin desalentar.',
    reflexion: 'En un contexto donde el padre tenía poder casi absoluto, Pablo le pone límites: no exasperes, no desanimes. La crianza cristiana no es autoritarismo ni permisividad, sino disciplina e instrucción "del Señor": como Él nos disciplina a nosotros, con amor y propósito.\n\nLos hijos de pastores enfrentan expectativas altas y a menudo injustas. Un padre que corrige con dureza, o que exige por la imagen del ministerio, puede sembrar ira y desaliento.',
    preguntas: ['¿En qué situaciones tiendes a exasperar a tus hijos?', '¿Tus correcciones buscan su corazón o tu imagen?', '¿Tus hijos sienten que pueden fallar delante de ti sin perder tu amor?'],
    aplicacion: 'Pide perdón a tus hijos por una ocasión reciente en que los exasperaste. Deja que vean a su padre arrepentirse.',
    oracion: 'Padre celestial, enséñame a disciplinar como tú: con amor, paciencia y propósito. Guárdame de desanimar a mis hijos. Amén.',
  },
  {
    id: 'o09', para: 'esposo', serie: 'Paternidad', titulo: 'Como el padre se compadece',
    texto: 'Sal 103:8-14', memoria: 'Sal 103:13',
    contexto: 'El Salmo 103 evoca Éx 34:6 ("misericordioso y clemente… lento para la ira y grande en misericordia"). "Se compadece" traduce rajam, relacionado con réjem (vientre): compasión entrañable. El v. 14 da la razón: "él conoce nuestra condición; acuérdase que somos polvo".',
    idea: 'La paternidad humana debe reflejar la compasión del Padre celestial.',
    reflexion: 'David describe a Dios con la imagen de un padre compasivo que conoce la fragilidad de sus hijos. No aparta la vista del pecado, pero no nos trata conforme a nuestras iniquidades.\n\nSer padre es aprender a mirar a los hijos como Dios nos mira: recordando que son polvo, que están creciendo, que necesitan paciencia más que perfección. Tus hijos aprenderán cómo es Dios, en parte, viendo cómo eres tú.',
    preguntas: ['¿Qué imagen de Dios Padre están formando tus hijos al verte?', '¿Cómo equilibras la verdad y la compasión en tu crianza?', '¿Qué significa para tu paternidad que Dios "se acuerda que somos polvo"?'],
    aplicacion: 'Pasa tiempo uno a uno con cada hijo esta semana, sin agenda, solo para disfrutar de él o ella.',
    oracion: 'Padre, gracias por tu compasión conmigo. Hazme un padre que refleje tu misericordia. Amén.',
  },
  {
    id: 'o10', para: 'esposo', serie: 'Ministerio y hogar', titulo: 'Elías bajo el enebro',
    texto: '1 R 19:1-8', memoria: '1 R 19:7',
    contexto: 'Después de la victoria del Carmelo, Elías huye, se aísla y pide morir. Dios no lo reprende primero: le da sueño, comida y un ángel lo toca dos veces. "Largo camino te resta" (v. 7): Dios reconoce el desgaste. Solo después viene la palabra en el silbo apacible (vv. 11-13).',
    idea: 'Dios cuida el cuerpo cansado del siervo antes de hablarle de nuevo.',
    reflexion: 'Elías venía de un triunfo espiritual enorme y cayó en un agotamiento profundo. Pidió morir. La respuesta de Dios fue tierna y práctica: dormir, comer, dormir otra vez, comer otra vez. "Largo camino te resta".\n\nEl agotamiento pastoral es real. A veces lo más espiritual que puedes hacer es descansar, alimentarte bien y dejar que otros te sirvan. Dios no te ve como una herramienta; te ve como un hijo que necesita cuidado.',
    preguntas: ['¿Reconoces señales de agotamiento en ti (aislamiento, desesperanza, irritabilidad)?', '¿Qué necesita tu cuerpo en esta temporada?', '¿Quién puede servirte como el ángel sirvió a Elías?'],
    aplicacion: 'Habla con tu esposa sobre tu nivel real de cansancio y acuerden una medida concreta de descanso (un día libre protegido, vacaciones, ayuda profesional si hace falta).',
    oracion: 'Señor, estoy cansado. Gracias porque me cuidas como a Elías. Dame descanso y fuerza para el camino que me resta. Amén.',
  },
  {
    id: 'o11', para: 'esposo', serie: 'Ministerio y hogar', titulo: 'Si alguno no provee para los suyos',
    texto: '1 Ti 5:8; Pr 27:23-27', memoria: '1 Ti 5:8',
    contexto: 'En 1 Ti 5 Pablo trata el cuidado de las viudas y exhorta a las familias a hacerse cargo de los suyos. "Proveer" (pronoéi) significa literalmente "pensar de antemano": planificar. Proverbios 27 habla de "considerar atentamente" el estado del rebaño: diligencia y previsión.',
    idea: 'Proveer para la familia es un deber espiritual que incluye previsión y cuidado integral.',
    reflexion: 'Pablo usa palabras fuertes: quien no provee para los suyos "ha negado la fe". Proveer no es solo dinero: es pensar de antemano en el bienestar de la familia, su salud, su futuro, su tiempo.\n\nLos pastores a veces descuidan las finanzas personales, la planificación o el tiempo familiar, pensando que el ministerio lo justifica. Pero el cuidado de los tuyos es parte de tu fe, no una distracción de ella.',
    preguntas: ['¿Cómo estás "pensando de antemano" en las necesidades de tu familia?', '¿Hay áreas (finanzas, salud, seguro, tiempo) que has descuidado?', '¿Cómo puede tu esposa participar en la planificación?'],
    aplicacion: 'Siéntate con tu esposa a revisar el presupuesto familiar y un plan a cinco años. Oren juntos por las decisiones.',
    oracion: 'Señor, dame sabiduría y diligencia para proveer para mi familia. Que mi casa vea tu fidelidad en mi cuidado. Amén.',
  },
  {
    id: 'o12', para: 'esposo', serie: 'Ministerio y hogar', titulo: 'Nehemías: orar y trabajar',
    texto: 'Neh 4:6-14', memoria: 'Neh 4:14',
    contexto: 'Ante la amenaza, Nehemías combina oración ("oramos a nuestro Dios") y acción ("pusimos guarda contra ellos de día y de noche", v. 9). Coloca al pueblo "por familias" junto al muro (v. 13) y exhorta: "pelead por vuestros hermanos, por vuestros hijos y por vuestras hijas, por vuestras mujeres y por vuestras casas" (v. 14).',
    idea: 'El liderazgo fiel ora con fe y actúa con responsabilidad para proteger a la familia.',
    reflexion: 'Nehemías no eligió entre orar o trabajar: hizo ambas cosas. Y cuando el desánimo llegó, recordó por qué se construía el muro: por los hijos, las esposas y las casas.\n\nEl pastor también construye muros: espirituales, relacionales, emocionales, alrededor de su familia. Requiere oración constante y acciones concretas: tiempo, límites, conversaciones difíciles, vigilancia.',
    preguntas: ['¿Qué "muros" necesita tu familia en esta temporada?', '¿Tiendes más a orar sin actuar o a actuar sin orar?', '¿Qué te recuerda el v. 14 sobre por qué vale la pena el esfuerzo?'],
    aplicacion: 'Identifica una amenaza concreta a la salud espiritual de tu familia y define una acción y una petición de oración para esta semana.',
    oracion: 'Señor grande y temible, ayúdame a orar y a trabajar por mi familia. Protege mi casa. Amén.',
  },
  {
    id: 'o13', para: 'esposo', serie: 'Fe en la prueba', titulo: 'Josué: esfuérzate y sé valiente',
    texto: 'Jos 1:1-9', memoria: 'Jos 1:9',
    contexto: 'El mandato "esfuérzate y sé valiente" (jazaq veʾemats) se repite tres veces (vv. 6, 7, 9). El valor de Josué no descansa en su capacidad sino en la presencia de Dios ("Jehová tu Dios será contigo") y en la meditación constante en la ley (v. 8: hagá, murmurar, repetir en voz baja).',
    idea: 'El valor para liderar nace de la presencia de Dios y de la meditación en su Palabra.',
    reflexion: 'Josué heredó un liderazgo enorme después de Moisés. Dios le repitió tres veces "esfuérzate y sé valiente", lo que sugiere que Josué tenía miedo. Pero el valor no vino de un discurso motivacional, sino de dos fuentes: la promesa "yo estaré contigo" y la Palabra meditada día y noche.\n\nLos desafíos del ministerio pueden parecer más grandes que tú. La receta de Dios sigue siendo la misma.',
    preguntas: ['¿Qué desafío te hace sentir como Josué frente al Jordán?', '¿Cómo es tu meditación en la Palabra fuera de la preparación de sermones?', '¿Qué significa hoy para ti "Jehová tu Dios será contigo"?'],
    aplicacion: 'Separa la lectura devocional de la preparación de sermones: lee un pasaje cada día solo para tu alma.',
    oracion: 'Señor, dame valor. No por mi fuerza, sino porque tú estás conmigo. Que tu Palabra esté en mi boca día y noche. Amén.',
  },
  {
    id: 'o14', para: 'esposo', serie: 'Fe en la prueba', titulo: 'Pablo: he aprendido a contentarme',
    texto: 'Fil 4:10-13', memoria: 'Fil 4:11',
    contexto: 'Pablo escribe desde la prisión. "Contentarme" traduce autárkēs, término estoico de autosuficiencia, que Pablo redefine: su suficiencia no está en sí mismo, sino "en Cristo que me fortalece" (v. 13). "He aprendido" (émathon) y "estoy enseñado" (memýēmai, iniciado en un secreto) muestran que el contentamiento es un proceso.',
    idea: 'El contentamiento se aprende en Cristo, en abundancia y en escasez.',
    reflexion: 'Pablo no nació contento; aprendió a estarlo, en cárceles, naufragios y también en abundancia. Su secreto no era la fuerza de voluntad, sino Cristo que lo fortalecía.\n\nEl ministerio trae comparaciones: iglesias más grandes, salarios mayores, reconocimiento ajeno. El contentamiento cristiano no es conformismo, sino libertad: servir con gozo donde Dios te puso.',
    preguntas: ['¿En qué área de tu vida o ministerio luchas con el descontento?', '¿Cómo te afecta la comparación con otros pastores?', '¿Qué significa en tu situación "todo lo puedo en Cristo"?'],
    aplicacion: 'Haz una lista de diez bendiciones concretas de tu situación actual y dale gracias a Dios en voz alta con tu familia.',
    oracion: 'Señor, enséñame el secreto del contentamiento. Que mi suficiencia esté en ti. Amén.',
  },
  {
    id: 'o15', para: 'esposo', serie: 'Fe en la prueba', titulo: 'Pedro restaurado: ¿me amas?',
    texto: 'Jn 21:15-19', memoria: 'Jn 21:17',
    contexto: 'Tres preguntas de Jesús corresponden a las tres negaciones de Pedro, junto a otra fogata (Jn 18:18; 21:9). Se ha discutido el cambio entre agapáo y filéo; más importante es que Jesús restaura a Pedro y le confía el pastoreo: "apacienta mis ovejas". El amor a Cristo precede al ministerio.',
    idea: 'Cristo restaura al siervo caído y le confía de nuevo el cuidado de sus ovejas.',
    reflexion: 'Pedro había negado a Jesús tres veces. Junto a una fogata, Jesús le hace tres preguntas: "¿Me amas?". No le pregunta por su preparación ni por su valentía, sino por su amor. Y lo vuelve a enviar: "Apacienta mis ovejas".\n\nTodo pastor falla. La pregunta de Jesús sigue siendo la misma, y el ministerio sigue siendo un encargo de Él, no una posesión nuestra. Las ovejas son "mis ovejas", dice Jesús.',
    preguntas: ['¿Hay un fracaso del que necesitas ser restaurado?', '¿Cómo responderías hoy a la pregunta "¿me amas?"?', '¿Qué cambia en tu ministerio recordar que son "sus" ovejas?'],
    aplicacion: 'Escribe tu respuesta a Jesús como una carta personal y compártela con tu esposa.',
    oracion: 'Señor, tú lo sabes todo; tú sabes que te amo. Restáurame y ayúdame a apacentar tus ovejas. Amén.',
  },

  // ======================================================================= PAREJA
  {
    id: 'p01', para: 'pareja', serie: 'Pacto', titulo: 'Una sola carne',
    texto: 'Gn 2:24; Mt 19:4-6', memoria: 'Mt 19:6',
    contexto: 'Gn 2:24 establece tres movimientos: dejar (ʿazab: abandonar la prioridad anterior), unirse (dabaq: adherirse, pegarse) y ser una sola carne. Jesús cita este texto para mostrar que el matrimonio es obra de Dios ("lo que Dios juntó") y no un contrato humano revocable a voluntad.',
    idea: 'El matrimonio es una unión hecha por Dios que exige dejar, unirse y ser uno.',
    reflexion: 'Dejar, unirse, ser uno. Cada paso es un reto. Dejar implica que ninguna otra relación (padres, ministerio, amigos) tenga prioridad sobre el cónyuge. Unirse implica perseverancia, como algo pegado que no se despega fácilmente. Ser uno implica compartir todo: cuerpo, tiempo, bienes, sueños.\n\nJesús recuerda que es Dios quien los juntó. Su matrimonio no es solo un acuerdo entre ustedes, sino algo que Dios hizo y sostiene.',
    preguntas: ['¿Hay algo que aún no han "dejado" completamente?', '¿Qué los ayuda a mantenerse "unidos" en tiempos difíciles?', '¿En qué área les gustaría ser más "uno"?'],
    aplicacion: 'Relean juntos sus votos matrimoniales (o escríbanlos de nuevo) y renueven su compromiso en oración.',
    oracion: 'Señor, tú nos uniste. Ayúdanos a dejar, a unirnos y a ser uno, para tu gloria. Amén.',
  },
  {
    id: 'p02', para: 'pareja', serie: 'Pacto', titulo: 'El cordón de tres dobleces',
    texto: 'Ec 4:9-12', memoria: 'Ec 4:12',
    contexto: 'Eclesiastés observa la vida "debajo del sol". Aquí presenta beneficios prácticos del compañerismo: mejor fruto, ayuda al caer, calor, defensa. La imagen del "cordón de tres dobleces" originalmente es proverbial (tres es más fuerte que dos); la tradición cristiana la ha aplicado al matrimonio con Dios como tercer hilo.',
    idea: 'Un matrimonio con Dios en el centro resiste lo que dos solos no podrían.',
    reflexion: 'El Predicador dice que dos son mejor que uno: se levantan mutuamente, se dan calor, se defienden. Y añade que un cordón de tres hilos no se rompe fácilmente.\n\nCuando Dios es el tercer hilo, su matrimonio tiene una fuerza que no depende solo de sus emociones o capacidades. En las temporadas donde uno cae, el otro levanta, y Dios sostiene a ambos.',
    preguntas: ['¿Cuándo fue la última vez que uno levantó al otro?', '¿Cómo se ve en la práctica que Dios sea el "tercer hilo" en su matrimonio?', '¿Qué los hace vulnerables a "romperse"?'],
    aplicacion: 'Cada uno escriba una manera en que el otro lo ha levantado este año y compártanla.',
    oracion: 'Dios, sé el tercer hilo en nuestro matrimonio. Sostennos cuando caigamos. Amén.',
  },
  {
    id: 'p03', para: 'pareja', serie: 'Comunicación', titulo: 'Pronto para oír, tardo para hablar',
    texto: 'Stg 1:19-20; Ef 4:25-32', memoria: 'Stg 1:19',
    contexto: 'Santiago da una fórmula de tres partes: pronto para oír, tardo para hablar, tardo para airarse. Pablo en Ef 4 conecta la verdad ("hablad verdad cada uno con su prójimo"), el enojo con límite ("no se ponga el sol sobre vuestro enojo") y la edificación ("que sea buena para la necesaria edificación").',
    idea: 'La comunicación sana escucha primero, habla con verdad y resuelve pronto.',
    reflexion: 'Muchos conflictos matrimoniales no son por el tema, sino por cómo se habla: interrumpir, suponer, levantar la voz. Santiago propone invertir el orden natural: escuchar mucho, hablar poco, enojarse lento.\n\nPablo añade que el enojo no debe durar la noche: no porque sea mágico resolver todo antes de dormir, sino porque el enojo que se guarda "da lugar al diablo".',
    preguntas: ['¿Quién de los dos tiende a hablar más rápido y quién a callar?', '¿Hay algún enojo que se ha quedado "más allá de la puesta del sol"?', '¿Qué palabra edificante necesita el otro hoy?'],
    aplicacion: 'Practiquen la escucha: uno habla 5 minutos sobre algo que le preocupa; el otro solo escucha y luego resume lo que entendió sin opinar. Luego inviertan los roles.',
    oracion: 'Señor, haznos prontos para oír y tardos para hablar. Que nuestras palabras edifiquen. Amén.',
  },
  {
    id: 'p04', para: 'pareja', serie: 'Comunicación', titulo: 'Perdonándoos unos a otros',
    texto: 'Col 3:12-15', memoria: 'Col 3:13',
    contexto: 'Pablo describe la "ropa" del creyente: entrañable misericordia, benignidad, humildad, mansedumbre, paciencia. "Soportándoos" (anejómenoi) implica tolerar las debilidades del otro. El perdón tiene una medida: "de la manera que Cristo os perdonó". El vínculo que une todo es el amor (v. 14).',
    idea: 'Perdonamos como fuimos perdonados: completa y repetidamente.',
    reflexion: 'En el matrimonio se acumulan pequeñas ofensas: olvidos, palabras, hábitos. Pablo no dice "cuando el otro cambie", sino "soportándoos y perdonándoos". El modelo es Cristo, que nos perdonó sin que lo mereciéramos.\n\nPerdonar no es negar el daño ni evitar conversaciones difíciles; es renunciar a cobrar la deuda. Y el perdón continuo permite que "la paz de Dios gobierne" en el corazón y en la casa.',
    preguntas: ['¿Hay alguna ofensa que aún están "cobrando" en silencio?', '¿Qué les cuesta más: pedir perdón o darlo?', '¿Cómo les ayuda recordar el perdón de Cristo?'],
    aplicacion: 'Cada uno pida perdón por algo concreto de las últimas semanas, con las palabras: "Me equivoqué en…, ¿me perdonas?".',
    oracion: 'Señor, perdónanos como nosotros queremos perdonarnos. Que tu paz gobierne nuestros corazones. Amén.',
  },
  {
    id: 'p05', para: 'pareja', serie: 'Intimidad y oración', titulo: 'El amor es sufrido, es benigno',
    texto: '1 Co 13:4-8', memoria: '1 Co 13:7',
    contexto: 'Aunque se lee en bodas, 1 Co 13 fue escrito a una iglesia dividida por la competencia de dones. Pablo define el amor (agápē) con quince verbos: es activo, no solo un sentimiento. "Todo lo sufre" (pánta stégei) puede traducirse "todo lo cubre", como un techo que protege.',
    idea: 'El amor bíblico es una serie de decisiones diarias, no un sentimiento constante.',
    reflexion: 'Pablo no define el amor por lo que se siente, sino por lo que se hace: es paciente, es amable, no es envidioso, no se jacta, no guarda rencor. Cada frase es una decisión.\n\nUn ejercicio útil es leer el pasaje poniendo el nombre propio en lugar de "amor": "Juan es sufrido, Juan es benigno…". Rápidamente se ve dónde falta crecer, y cuánto necesitamos el amor de Cristo que sí cumple cada frase.',
    preguntas: ['¿Qué frase del pasaje describe mejor al otro?', '¿Cuál es la más difícil para ti?', '¿Cómo pueden "cubrirse" mutuamente como un techo?'],
    aplicacion: 'Cada uno lea el pasaje en voz alta sustituyendo "el amor" por su propio nombre. Elijan una frase para practicar esta semana.',
    oracion: 'Señor, que tu amor, que todo lo sufre y todo lo espera, viva en nosotros. Amén.',
  },
  {
    id: 'p06', para: 'pareja', serie: 'Intimidad y oración', titulo: 'Orad juntos: donde están dos o tres',
    texto: 'Mt 18:19-20; 1 P 3:7', memoria: 'Mt 18:19',
    contexto: 'Mt 18:19-20 está en el contexto de la disciplina y reconciliación en la comunidad, pero expresa un principio: la presencia de Cristo en el acuerdo de dos o tres reunidos en su nombre. 1 P 3:7 llama a esposo y esposa "coherederos de la gracia de la vida" y relaciona la relación conyugal con la vida de oración.',
    idea: 'Orar juntos es una de las formas más profundas de intimidad matrimonial.',
    reflexion: 'Muchas parejas cristianas, incluso pastorales, oran por otros juntos, pero rara vez oran el uno por el otro con vulnerabilidad. Orar juntos expone el corazón: miedos, pecados, sueños.\n\nJesús promete su presencia donde dos se ponen de acuerdo en su nombre. Su matrimonio es el grupo de oración más pequeño y más importante de su iglesia.',
    preguntas: ['¿Con qué frecuencia oran juntos, no por el ministerio, sino por ustedes?', '¿Qué les impide orar juntos más a menudo?', '¿Qué necesita cada uno que el otro ore por él o ella?'],
    aplicacion: 'Establezcan un momento breve y fijo (cinco minutos al acostarse) para orar uno por el otro durante un mes.',
    oracion: 'Señor, aquí estamos dos en tu nombre. Te pedimos que estés en medio de nosotros y nos unas más en ti. Amén.',
  },
  {
    id: 'p07', para: 'pareja', serie: 'Propósito compartido', titulo: 'Priscila y Aquila: ministerio en pareja',
    texto: 'Hch 18:1-4, 24-28', memoria: 'Hch 18:26',
    contexto: 'Priscila y Aquila aparecen siempre juntos en el NT (seis veces), a menudo con ella nombrada primero. Trabajaban haciendo tiendas y hospedaron a Pablo. Con Apolos, "le tomaron y le declararon más particularmente el camino de Dios": discipulado privado, en casa, con respeto por un predicador elocuente.',
    idea: 'Dios puede usar a la pareja unida como un equipo ministerial.',
    reflexion: 'Priscila y Aquila no tenían un título ministerial, pero su casa fue escuela, iglesia y refugio. Cuando vieron que Apolos predicaba con poder pero con conocimiento incompleto, no lo criticaron en público: lo invitaron a casa y le enseñaron con más exactitud.\n\nEn un matrimonio pastoral, ambos tienen dones que se complementan. El ministerio no tiene que ser "de él" con ella de apoyo, ni al revés; puede ser una obra compartida según los dones de cada uno.',
    preguntas: ['¿Qué dones ven en el otro que complementan los propios?', '¿Qué parte del ministerio podrían hacer mejor juntos?', '¿Cómo pueden, como Priscila y Aquila, corregir con gracia y en privado?'],
    aplicacion: 'Identifiquen una persona o pareja a la que puedan discipular juntos en su casa este año.',
    oracion: 'Señor, úsanos como equipo en tu obra. Que nuestro hogar sea un lugar donde otros aprendan tu camino. Amén.',
  },
  {
    id: 'p08', para: 'pareja', serie: 'Propósito compartido', titulo: 'Yo y mi casa serviremos a Jehová',
    texto: 'Jos 24:14-15', memoria: 'Jos 24:15',
    contexto: 'Al final de su vida, Josué convoca a Israel en Siquem para renovar el pacto. Pone ante el pueblo una elección clara entre los dioses de sus padres, los de los amorreos, o Jehová. Su declaración es personal y familiar: "yo y mi casa". La fe es decisión individual y, a la vez, dirección para el hogar.',
    idea: 'Cada familia debe decidir, y renovar, a quién servirá.',
    reflexion: 'Josué no esperó a que el pueblo decidiera para definir su casa. Eligió, y lo dijo en voz alta. Hoy también hay "dioses" que compiten por el hogar: éxito, comodidad, imagen, entretenimiento, incluso el propio ministerio como ídolo.\n\nRenovar el pacto como familia es declarar, una y otra vez, que Cristo está en el centro. No como una frase en la pared, sino como criterio para decisiones concretas.',
    preguntas: ['¿Qué "dioses" compiten por el centro de su hogar?', '¿Cómo se ve en decisiones concretas que su casa sirve a Jehová?', '¿Cómo pueden involucrar a sus hijos en esta decisión?'],
    aplicacion: 'Escriban juntos una breve "declaración familiar" (misión, valores, prácticas) y compártanla con sus hijos.',
    oracion: 'Señor, nosotros y nuestra casa te serviremos. Ayúdanos a vivir esta decisión cada día. Amén.',
  },
];

export const devocionalesPara = (para) => DEVOCIONALES.filter((d) => d.para === para);
export const devocional = (id) => DEVOCIONALES.find((d) => d.id === id);

/** Devocional del día para un destinatario: rota por fecha, así cada día toca uno distinto. */
export function delDia(para, fecha = new Date()) {
  const lista = devocionalesPara(para);
  if (!lista.length) return null;
  const inicio = new Date(fecha.getFullYear(), 0, 0);
  const dia = Math.floor((fecha - inicio) / 86_400_000);
  return lista[dia % lista.length];
}

export function fechaClave(fecha = new Date()) {
  const f = new Date(fecha);
  return `${f.getFullYear()}-${String(f.getMonth() + 1).padStart(2, '0')}-${String(f.getDate()).padStart(2, '0')}`;
}

/** Días seguidos con al menos un devocional hecho para ese destinatario (hasta hoy o ayer). */
export function rachaDevocional(diario, para, hoy = new Date()) {
  const dias = new Set(diario.filter((d) => d.para === para && d.hecho).map((d) => d.fecha));
  const f = new Date(hoy);
  if (!dias.has(fechaClave(f))) f.setDate(f.getDate() - 1);
  let n = 0;
  while (dias.has(fechaClave(f))) { n++; f.setDate(f.getDate() - 1); }
  return n;
}
