/**
 * introducciones.js — Introducción a cada libro de la Biblia: autor, fecha,
 * destinatarios, género, propósito, tema, estructura, versículo clave, cómo
 * apunta a Cristo y los debates críticos principales.
 *
 * Se presenta la posición tradicional y, en "debate", las alternativas más
 * serias de la erudición, para que el predicador las conozca y decida.
 * Las fechas son aproximadas.
 */

const AT = {
  1: {
    autor: 'Moisés, según la tradición judía y cristiana (cf. Lc 24:44; Jn 5:46).', fecha: 'c. 1446-1406 a.C. (fecha temprana del éxodo)',
    destinatarios: 'Israel en el desierto, antes de entrar a Canaán.', genero: 'Narrativa (historia primitiva y patriarcal) con genealogías.',
    proposito: 'Mostrar el origen del mundo, del pecado y del pueblo del pacto, y el plan de Dios para bendecir a todas las naciones por medio de Abraham.',
    tema: 'Dios crea, juzga y elige; su promesa avanza a pesar del pecado humano.', clave: 'Gn 12:1-3',
    cristo: 'La simiente de la mujer (3:15), la bendición a las naciones por la descendencia de Abraham (Gá 3:16), Melquisedec (He 7) y el cordero provisto (22:8).',
    debate: 'La crítica documentaria (J, E, D, P) propone fuentes compuestas y una redacción posterior al exilio; el género de Gn 1-11 y la relación con la ciencia se debaten.',
    estructura: [['Historia primitiva: creación, caída, diluvio, Babel', 'Gn 1-11'], ['Abraham', 'Gn 12-25'], ['Isaac y Jacob', 'Gn 25-36'], ['José', 'Gn 37-50']],
  },
  2: {
    autor: 'Moisés (Éx 17:14; 24:4; Mr 12:26).', fecha: 'c. 1446-1406 a.C.', destinatarios: 'Israel redimido de Egipto.',
    genero: 'Narrativa y ley (código del pacto, instrucciones del tabernáculo).',
    proposito: 'Relatar cómo Dios libera a su pueblo, hace pacto con él y viene a habitar en medio de él.',
    tema: 'Redención, pacto y presencia: "Yo soy JEHOVÁ tu Dios, que te saqué de Egipto".', clave: 'Éx 6:6-7',
    cristo: 'La Pascua (1 Co 5:7), el maná (Jn 6), la roca (1 Co 10:4), el tabernáculo (Jn 1:14) y el sumo sacerdote (He 8-9).',
    debate: 'Fecha del éxodo (s. XV o s. XIII a.C.), la ruta y la historicidad de la salida; composición del libro.',
    estructura: [['Esclavitud y liberación', 'Éx 1-18'], ['El pacto en el Sinaí y la ley', 'Éx 19-24'], ['El tabernáculo y el becerro de oro', 'Éx 25-40']],
  },
  3: {
    autor: 'Moisés (1:1; 27:34).', fecha: 'c. 1445 a.C.', destinatarios: 'Los sacerdotes y el pueblo de Israel.',
    genero: 'Ley ritual y moral.', proposito: 'Enseñar cómo un pueblo pecador puede acercarse a un Dios santo y vivir en su presencia.',
    tema: 'Santidad: "Santos seréis, porque santo soy yo".', clave: 'Lv 19:2',
    cristo: 'Los sacrificios y el Día de la Expiación (cap. 16) se cumplen en el sacrificio único de Cristo (He 9-10).',
    debate: 'Muchos críticos atribuyen el libro a la fuente sacerdotal (P) postexílica; el Código de Santidad (17-26) como unidad propia.',
    estructura: [['Los sacrificios', 'Lv 1-7'], ['El sacerdocio', 'Lv 8-10'], ['Pureza e impureza', 'Lv 11-15'], ['El Día de la Expiación', 'Lv 16'], ['El código de santidad', 'Lv 17-27']],
  },
  4: {
    autor: 'Moisés (33:2).', fecha: 'c. 1406 a.C.', destinatarios: 'La segunda generación, a punto de entrar en la tierra.',
    genero: 'Narrativa, censos y leyes.', proposito: 'Mostrar la fidelidad de Dios y el juicio sobre la incredulidad durante los cuarenta años en el desierto.',
    tema: 'Incredulidad y fidelidad de Dios en el camino.', clave: 'Nm 14:22-24',
    cristo: 'La serpiente de bronce (21:8-9; Jn 3:14), la roca y el maná; la estrella de Jacob (24:17).',
    debate: 'Los números de los censos (600 000 hombres) y cómo interpretarlos; fuentes del libro.',
    estructura: [['Preparación en el Sinaí', 'Nm 1-10'], ['Rebelión y peregrinaje', 'Nm 11-25'], ['La nueva generación en Moab', 'Nm 26-36']],
  },
  5: {
    autor: 'Moisés (31:9), con el relato de su muerte añadido después (cap. 34).', fecha: 'c. 1406 a.C.',
    destinatarios: 'Israel en las llanuras de Moab.', genero: 'Discursos de renovación del pacto, con forma de tratado antiguo.',
    proposito: 'Renovar el pacto y llamar a Israel a amar y obedecer a Dios de todo corazón en la tierra.',
    tema: 'Amar a Dios y guardar su palabra: bendición o maldición.', clave: 'Dt 6:4-5',
    cristo: 'El profeta como Moisés (18:15; Hch 3:22); Jesús responde a la tentación con Deuteronomio (Mt 4).',
    debate: 'Muchos lo vinculan con la reforma de Josías (622 a.C.); otros señalan su parecido con tratados hititas del segundo milenio.',
    estructura: [['Primer discurso: historia', 'Dt 1-4'], ['Segundo discurso: la ley', 'Dt 5-26'], ['Bendiciones y maldiciones', 'Dt 27-30'], ['Últimas palabras y muerte de Moisés', 'Dt 31-34']],
  },
  6: {
    autor: 'Anónimo; la tradición judía lo atribuye a Josué, con añadidos posteriores.', fecha: 'c. 1400-1370 a.C. (o después)',
    destinatarios: 'Israel en la tierra.', genero: 'Narrativa histórica.', proposito: 'Mostrar que Dios cumplió su promesa de dar la tierra y llamar a la fidelidad al pacto.',
    tema: 'Conquista y herencia por la fidelidad de Dios.', clave: 'Jos 21:43-45',
    cristo: 'Josué (= Jesús, "Jehová salva") conduce al reposo (He 4:8); Rahab en la genealogía (Mt 1:5).',
    debate: 'La arqueología de Jericó y Hai; modelos de conquista, infiltración o surgimiento interno; la ética de la guerra santa.',
    estructura: [['Entrada en la tierra', 'Jos 1-5'], ['Conquista', 'Jos 6-12'], ['Reparto de la tierra', 'Jos 13-22'], ['Despedida y renovación del pacto', 'Jos 23-24']],
  },
  7: {
    autor: 'Anónimo (tradición: Samuel).', fecha: 'Periodo de c. 1375-1050 a.C.; escrito en la monarquía temprana.', destinatarios: 'Israel en tiempos de la monarquía.',
    genero: 'Narrativa histórica cíclica.', proposito: 'Mostrar la decadencia de Israel cuando "cada uno hacía lo que bien le parecía" y la necesidad de un rey justo.',
    tema: 'Ciclo de pecado, opresión, clamor y liberación.', clave: 'Jue 21:25',
    cristo: 'Los jueces-libertadores imperfectos anticipan al Libertador perfecto; Sansón muere venciendo (16:30).',
    debate: 'Cronología (suma de los periodos), relación con la historia deuteronomista.',
    estructura: [['Conquista incompleta', 'Jue 1-2'], ['Los jueces', 'Jue 3-16'], ['Epílogos de decadencia', 'Jue 17-21']],
  },
  8: {
    autor: 'Anónimo (tradición: Samuel).', fecha: 'Hechos en tiempo de los jueces; escrito en la época de David o después.', destinatarios: 'Israel.',
    genero: 'Narrativa corta.', proposito: 'Mostrar la providencia de Dios en una familia fiel y el origen de la línea de David.',
    tema: 'Jésed (misericordia leal) y redención.', clave: 'Rt 1:16',
    cristo: 'Booz, el pariente redentor (goel), prefigura a Cristo; Rut, moabita, en la genealogía del Mesías.',
    debate: 'Fecha: preexílica o postexílica (como respuesta a Esdras-Nehemías sobre matrimonios mixtos).',
    estructura: [['Pérdida', 'Rt 1'], ['Encuentro en el campo', 'Rt 2'], ['La era', 'Rt 3'], ['Redención y genealogía', 'Rt 4']],
  },
  9: {
    autor: 'Anónimo; incluye material de Samuel, Natán y Gad (1 Cr 29:29).', fecha: 'c. 1100-1010 a.C.; escrito después de la división del reino.', destinatarios: 'Israel.',
    genero: 'Narrativa histórica.', proposito: 'Relatar el paso de los jueces a la monarquía: Samuel, Saúl y el ascenso de David.',
    tema: 'Dios exalta al humilde y desecha al desobediente; mira el corazón.', clave: '1 S 16:7',
    cristo: 'David, el ungido, rey según el corazón de Dios; el cántico de Ana (2:10) anuncia al Ungido.',
    debate: 'Fuentes (historia del arca, ascenso de David) y la llamada historia deuteronomista.',
    estructura: [['Samuel', '1 S 1-7'], ['Saúl', '1 S 8-15'], ['Saúl y David', '1 S 16-31']],
  },
  10: {
    autor: 'Anónimo (continúa 1 Samuel).', fecha: 'c. 1010-970 a.C.', destinatarios: 'Israel.', genero: 'Narrativa histórica.',
    proposito: 'Presentar el reinado de David, el pacto davídico y las consecuencias de su pecado.',
    tema: 'El pacto con David: una casa y un reino para siempre.', clave: '2 S 7:12-16',
    cristo: 'El pacto davídico se cumple en Cristo, Hijo de David (Lc 1:32-33; Hch 2:30).',
    debate: 'La "narración de la sucesión" (9-20; 1 R 1-2) como unidad literaria; historicidad del reino davídico.',
    estructura: [['Triunfos de David', '2 S 1-10'], ['Pecado con Betsabé', '2 S 11-12'], ['Problemas en la familia y el reino', '2 S 13-20'], ['Apéndices', '2 S 21-24']],
  },
  11: {
    autor: 'Anónimo (tradición: Jeremías); usa crónicas reales.', fecha: 'Hechos de c. 970-850 a.C.; redacción final en el exilio (c. 560 a.C.).',
    destinatarios: 'Los exiliados.', genero: 'Narrativa histórica teológica.',
    proposito: 'Explicar la división del reino y el camino hacia el exilio por la infidelidad al pacto.',
    tema: 'La fidelidad del rey determina la suerte del pueblo.', clave: '1 R 9:4-7',
    cristo: 'Un rey mayor que Salomón (Mt 12:42); el templo como anticipo de Cristo (Jn 2:19-21).',
    debate: 'Cronología de los reyes (sincronismos), historia deuteronomista.',
    estructura: [['Salomón', '1 R 1-11'], ['División del reino', '1 R 12-16'], ['Elías y Acab', '1 R 17-22']],
  },
  12: {
    autor: 'Anónimo (continúa 1 Reyes).', fecha: 'Hechos de c. 850-560 a.C.; redacción en el exilio.', destinatarios: 'Los exiliados.',
    genero: 'Narrativa histórica teológica.', proposito: 'Mostrar la caída de Samaria (722) y de Jerusalén (586) como juicio, sin que se apague la promesa (25:27-30).',
    tema: 'Juicio por la idolatría y esperanza en la línea de David.', clave: '2 R 17:13-14',
    cristo: 'Eliseo anticipa milagros de Jesús (4:42-44); la lámpara de David no se apaga.',
    debate: 'Relación con la arqueología asiria y babilónica (bien atestiguada); la reforma de Josías.',
    estructura: [['Eliseo', '2 R 1-8'], ['Los dos reinos hasta la caída de Israel', '2 R 9-17'], ['Judá hasta el exilio', '2 R 18-25']],
  },
  13: {
    autor: 'El Cronista (tradición judía: Esdras).', fecha: 'c. 450-400 a.C.', destinatarios: 'La comunidad que volvió del exilio.',
    genero: 'Historia teológica con genealogías.', proposito: 'Dar identidad a la comunidad restaurada: su lugar en la historia, el culto y la línea de David.',
    tema: 'David, el templo y la adoración correcta.', clave: '1 Cr 17:11-14',
    cristo: 'El trono de David eterno; las genealogías llevan a Mateo 1.',
    debate: 'Autoría (¿el mismo de Esdras-Nehemías?), uso de Samuel-Reyes como fuente.',
    estructura: [['Genealogías', '1 Cr 1-9'], ['Reinado de David', '1 Cr 10-29']],
  },
  14: {
    autor: 'El Cronista.', fecha: 'c. 450-400 a.C.', destinatarios: 'La comunidad postexílica.', genero: 'Historia teológica.',
    proposito: 'Mostrar que la bendición depende de buscar a Dios, con el templo en el centro, y terminar con la esperanza del regreso.',
    tema: 'Buscar a Dios, humillarse y ser restaurado.', clave: '2 Cr 7:14',
    cristo: 'El templo lleno de la gloria (5:14) anticipa la gloria de Dios en Cristo y su iglesia.',
    debate: 'Selección teológica frente a Reyes (omite el reino del norte).',
    estructura: [['Salomón y el templo', '2 Cr 1-9'], ['Los reyes de Judá', '2 Cr 10-36']],
  },
  15: {
    autor: 'Esdras (en parte en primera persona, 7-10).', fecha: 'Hechos de 538-457 a.C.; escrito c. 440 a.C.', destinatarios: 'La comunidad restaurada.',
    genero: 'Historia con memorias y documentos oficiales (en parte en arameo).',
    proposito: 'Relatar el regreso, la reconstrucción del templo y la reforma según la ley.',
    tema: 'Restauración del culto y de la obediencia a la Palabra.', clave: 'Esd 7:10',
    cristo: 'La fidelidad de Dios a su promesa de volver; la ley enseñada prepara al pueblo del Mesías.',
    debate: 'Orden cronológico de Esdras y Nehemías (¿quién llegó primero?).',
    estructura: [['Primer regreso y el templo', 'Esd 1-6'], ['Regreso de Esdras y reforma', 'Esd 7-10']],
  },
  16: {
    autor: 'Nehemías (memorias en primera persona) y el redactor de Esdras-Nehemías.', fecha: '445-430 a.C.', destinatarios: 'La comunidad restaurada.',
    genero: 'Historia y memorias.', proposito: 'Relatar la reconstrucción de los muros y la renovación del pacto.',
    tema: 'Oración y trabajo para restaurar la ciudad de Dios.', clave: 'Neh 8:8-10',
    cristo: 'Dios reúne y protege a su pueblo; la lectura de la ley anticipa la predicación de la Palabra.',
    debate: 'Unidad con Esdras; cronología.',
    estructura: [['Reconstrucción del muro', 'Neh 1-7'], ['Renovación espiritual', 'Neh 8-10'], ['Repoblación y reformas', 'Neh 11-13']],
  },
  17: {
    autor: 'Anónimo.', fecha: 'Hechos c. 483-473 a.C.; escrito en el periodo persa.', destinatarios: 'Judíos de la diáspora.',
    genero: 'Narrativa histórica.', proposito: 'Mostrar la providencia de Dios que preserva a su pueblo, y explicar la fiesta de Purim.',
    tema: 'La providencia oculta: Dios no se nombra, pero gobierna.', clave: 'Est 4:14',
    cristo: 'Una mediadora que arriesga su vida por el pueblo; la línea del Mesías preservada.',
    debate: 'Historicidad (paralelos persas, reina Vasti); ausencia del nombre de Dios; adiciones griegas.',
    estructura: [['Ester llega a ser reina', 'Est 1-2'], ['El complot de Amán', 'Est 3-5'], ['Inversión y victoria', 'Est 6-10']],
  },
  18: {
    autor: 'Desconocido.', fecha: 'Ambientado en la era patriarcal; composición incierta (s. X-VI a.C.).', destinatarios: 'El pueblo de Dios.',
    genero: 'Literatura sapiencial: marco en prosa y diálogos poéticos.',
    proposito: 'Enfrentar el sufrimiento del justo y mostrar la soberanía y sabiduría de Dios más allá de la retribución simple.',
    tema: 'El sufrimiento del justo y la soberanía de Dios.', clave: 'Job 19:25-27',
    cristo: 'El Redentor que vive (19:25); el mediador que Job anhela (9:33; 16:19-21) se cumple en Cristo.',
    debate: 'Fecha, unidad (discursos de Eliú), relación con literatura sapiencial del antiguo Oriente.',
    estructura: [['Prólogo', 'Job 1-2'], ['Diálogos con los amigos', 'Job 3-31'], ['Eliú', 'Job 32-37'], ['Discursos de Dios', 'Job 38-41'], ['Epílogo', 'Job 42']],
  },
  19: {
    autor: 'David (73 títulos), Asaf, los hijos de Coré, Salomón, Moisés, Hemán, Etán y anónimos.', fecha: 'c. 1400-450 a.C.; compilación final postexílica.',
    destinatarios: 'Israel en su adoración.', genero: 'Poesía: himnos, lamentos, acción de gracias, reales, sapienciales.',
    proposito: 'Dar al pueblo de Dios palabras para orar y alabar en toda circunstancia.',
    tema: 'Jehová reina: alabanza, lamento y confianza.', clave: 'Sal 1:1-2',
    cristo: 'Salmos mesiánicos citados en el NT: 2, 16, 22, 45, 69, 110, 118; Cristo ora los salmos.',
    debate: 'Valor de los títulos; la forma canónica en cinco libros como mensaje (Wilson).',
    estructura: [['Libro I', 'Sal 1-41'], ['Libro II', 'Sal 42-72'], ['Libro III', 'Sal 73-89'], ['Libro IV', 'Sal 90-106'], ['Libro V', 'Sal 107-150']],
  },
  20: {
    autor: 'Salomón principalmente (1:1; 10:1; 25:1), Agur (30) y Lemuel (31).', fecha: 'c. 970-700 a.C. (compilación en tiempo de Ezequías).',
    destinatarios: 'Jóvenes y todo el pueblo.', genero: 'Literatura sapiencial: discursos y dichos breves.',
    proposito: 'Enseñar la sabiduría práctica para vivir bien en el mundo de Dios.', tema: 'El temor de Jehová es el principio de la sabiduría.', clave: 'Pr 1:7',
    cristo: 'Cristo es la sabiduría de Dios (1 Co 1:24, 30; Col 2:3); la Sabiduría personificada de Pr 8.',
    debate: 'Relación con la sabiduría egipcia (Amenemope, 22:17-24:22).',
    estructura: [['La sabiduría y la necedad', 'Pr 1-9'], ['Proverbios de Salomón', 'Pr 10-22'], ['Dichos de los sabios', 'Pr 22-24'], ['Proverbios copiados por Ezequías', 'Pr 25-29'], ['Agur, Lemuel y la mujer virtuosa', 'Pr 30-31']],
  },
  21: {
    autor: 'Qohélet, "el Predicador, hijo de David" (tradición: Salomón).', fecha: 'Salomónica (c. 935 a.C.) o postexílica según muchos.', destinatarios: 'Israel.',
    genero: 'Literatura sapiencial reflexiva.', proposito: 'Mostrar la vanidad (hébel, vapor) de la vida "debajo del sol" y llamar a temer a Dios y disfrutar sus dones.',
    tema: 'Todo es vapor sin Dios; teme a Dios y guarda sus mandamientos.', clave: 'Ec 12:13-14',
    cristo: 'Cristo redime la vanidad de la creación (Ro 8:20) y da sentido a lo que "debajo del sol" parece absurdo.',
    debate: 'Autoría y fecha (lenguaje tardío), relación entre el narrador y el epílogo.',
    estructura: [['Prólogo: todo es vanidad', 'Ec 1'], ['La búsqueda de sentido', 'Ec 2-6'], ['Consejos sabios', 'Ec 7-11'], ['Acuérdate de tu Creador; conclusión', 'Ec 12']],
  },
  22: {
    autor: 'Salomón (1:1), según la tradición.', fecha: 'c. 960 a.C.', destinatarios: 'Israel.', genero: 'Poesía amorosa.',
    proposito: 'Celebrar el amor conyugal como don de Dios.', tema: 'El amor fuerte como la muerte.', clave: 'Cnt 8:6-7',
    cristo: 'Lectura tradicional: el amor de Cristo y su iglesia (Ef 5:32); lectura literal: la bondad del matrimonio.',
    debate: 'Interpretación alegórica, dramática o lírica; autoría.',
    estructura: [['Cortejo', 'Cnt 1-3'], ['Boda', 'Cnt 3-5'], ['Madurez del amor', 'Cnt 5-8']],
  },
  23: {
    autor: 'Isaías hijo de Amoz (1:1; Jn 12:38-41).', fecha: 'c. 740-680 a.C.', destinatarios: 'Judá y Jerusalén; los caps. 40-66 consuelan a los exiliados.',
    genero: 'Profecía (oráculos, narrativa, poesía).', proposito: 'Llamar al arrepentimiento, anunciar el juicio y la salvación por medio del Mesías y el Siervo.',
    tema: 'El Santo de Israel juzga y salva.', clave: 'Is 53:5-6',
    cristo: 'Emanuel (7:14), el niño rey (9:6-7), la raíz de Isaí (11), el Siervo sufriente (52:13-53:12), el Ungido (61:1; Lc 4:18).',
    debate: 'Hipótesis de dos o tres Isaías (40-55 y 56-66 exílico y postexílico); unidad defendida por la tradición y por el NT.',
    estructura: [['Juicio y esperanza', 'Is 1-12'], ['Oráculos contra las naciones', 'Is 13-23'], ['Apocalipsis de Isaías', 'Is 24-27'], ['Ayes y Ezequías', 'Is 28-39'], ['Consolación y el Siervo', 'Is 40-55'], ['Gloria futura', 'Is 56-66']],
  },
  24: {
    autor: 'Jeremías, con Baruc como escriba (36:4).', fecha: 'c. 627-580 a.C.', destinatarios: 'Judá antes y después de la caída de Jerusalén.',
    genero: 'Profecía, biografía y lamento.', proposito: 'Anunciar el juicio inevitable y el nuevo pacto.', tema: 'Juicio y nuevo pacto.', clave: 'Jer 31:31-34',
    cristo: 'El nuevo pacto en su sangre (Lc 22:20; He 8); el Renuevo justo (23:5-6).',
    debate: 'Diferencias entre el texto hebreo y la Septuaginta (más corta y en otro orden).',
    estructura: [['Llamamiento', 'Jer 1'], ['Profecías a Judá', 'Jer 2-25'], ['Conflictos y consolación', 'Jer 26-35'], ['Caída de Jerusalén', 'Jer 36-45'], ['Contra las naciones', 'Jer 46-51'], ['Apéndice histórico', 'Jer 52']],
  },
  25: {
    autor: 'Anónimo (tradición: Jeremías).', fecha: 'Poco después de 586 a.C.', destinatarios: 'Los sobrevivientes de la caída de Jerusalén.',
    genero: 'Poesía de lamento (acrósticos).', proposito: 'Dar voz al duelo por Jerusalén y afirmar la fidelidad de Dios en medio del juicio.',
    tema: 'Grandes son tus misericordias en medio del dolor.', clave: 'Lm 3:22-23',
    cristo: 'El varón que ha visto aflicción (3:1) prefigura al Siervo que lleva el juicio.',
    debate: 'Autoría y uso litúrgico.',
    estructura: [['Jerusalén desolada', 'Lm 1'], ['La ira de Dios', 'Lm 2'], ['Esperanza en la aflicción', 'Lm 3'], ['Asedio', 'Lm 4'], ['Oración', 'Lm 5']],
  },
  26: {
    autor: 'Ezequiel, sacerdote exiliado.', fecha: '593-571 a.C.', destinatarios: 'Los exiliados en Babilonia.',
    genero: 'Profecía con visiones y actos simbólicos.', proposito: 'Justificar el juicio y anunciar la restauración: un corazón nuevo y la presencia de Dios de regreso.',
    tema: '"Y sabrán que yo soy Jehová": la gloria que se va y regresa.', clave: 'Ez 36:26-27',
    cristo: 'El buen pastor, siervo David (34:23-24); el templo del que brota el río de vida (47; Jn 7:38).',
    debate: 'Interpretación del templo (40-48): literal, simbólica o escatológica.',
    estructura: [['Llamamiento', 'Ez 1-3'], ['Juicio sobre Jerusalén', 'Ez 4-24'], ['Contra las naciones', 'Ez 25-32'], ['Restauración', 'Ez 33-39'], ['El nuevo templo', 'Ez 40-48']],
  },
  27: {
    autor: 'Daniel (tradición; Mt 24:15).', fecha: 'Siglo VI a.C. (tradicional); mediados del s. II a.C. según la crítica.', destinatarios: 'Los judíos bajo imperios paganos.',
    genero: 'Narrativa y apocalíptica (2:4-7:28 en arameo).', proposito: 'Mostrar que el Dios Altísimo gobierna los reinos humanos y dará el reino eterno a sus santos.',
    tema: 'La soberanía de Dios sobre los imperios.', clave: 'Dn 2:44',
    cristo: 'El Hijo del hombre que viene con las nubes (7:13-14), título preferido de Jesús; la piedra que llena la tierra (2:34-35).',
    debate: 'Fecha y género de las profecías (exilio o época macabea); interpretación de las setenta semanas (9:24-27).',
    estructura: [['Relatos en la corte', 'Dn 1-6'], ['Visiones apocalípticas', 'Dn 7-12']],
  },
  28: { autor: 'Oseas hijo de Beeri.', fecha: 'c. 755-715 a.C.', destinatarios: 'El reino del norte (Israel/Efraín).', genero: 'Profecía.',
    proposito: 'Denunciar la infidelidad de Israel con la imagen del matrimonio y proclamar el amor persistente de Dios.', tema: 'El amor fiel de Dios por un pueblo adúltero.', clave: 'Os 11:8-9',
    cristo: '"De Egipto llamé a mi hijo" (11:1; Mt 2:15); la resurrección al tercer día (6:2).', debate: 'Carácter literal o simbólico del matrimonio con Gomer.',
    estructura: [['El matrimonio del profeta', 'Os 1-3'], ['Acusaciones y juicio', 'Os 4-13'], ['Llamado al arrepentimiento', 'Os 14']] },
  29: { autor: 'Joel hijo de Petuel.', fecha: 'Incierta: siglo IX o postexílica.', destinatarios: 'Judá.', genero: 'Profecía.',
    proposito: 'Usar una plaga de langostas para llamar al arrepentimiento ante el Día de Jehová.', tema: 'El Día de Jehová y el derramamiento del Espíritu.', clave: 'Jl 2:28-29',
    cristo: 'Pentecostés cumple 2:28-32 (Hch 2:16-21); "todo aquel que invocare el nombre" (Ro 10:13).', debate: 'Fecha del libro.',
    estructura: [['La plaga y el llamado', 'Jl 1-2'], ['El Espíritu y el juicio de las naciones', 'Jl 3']] },
  30: { autor: 'Amós, pastor de Tecoa.', fecha: 'c. 760 a.C.', destinatarios: 'El reino del norte en su prosperidad.', genero: 'Profecía.',
    proposito: 'Denunciar la injusticia social y la religión vacía.', tema: 'Justicia como impetuosa corriente.', clave: 'Am 5:24',
    cristo: 'El tabernáculo caído de David levantado (9:11-12; Hch 15:16-17).', debate: 'Autenticidad del final esperanzador (9:11-15).',
    estructura: [['Juicio sobre las naciones e Israel', 'Am 1-2'], ['Mensajes', 'Am 3-6'], ['Visiones', 'Am 7-9']] },
  31: { autor: 'Abdías.', fecha: 'Probablemente poco después de 586 a.C.', destinatarios: 'Judá, sobre Edom.', genero: 'Profecía (oráculo).',
    proposito: 'Anunciar el juicio sobre Edom por su orgullo y violencia contra Judá.', tema: 'El orgullo es abatido; el reino será de Jehová.', clave: 'Abd 1:15',
    cristo: 'El reino de Jehová sobre los montes de Sion (v. 21).', debate: 'Fecha y relación con Jer 49.',
    estructura: [['Juicio sobre Edom', 'Abd 1:1-14'], ['El Día de Jehová', 'Abd 1:15-21']] },
  32: { autor: 'Jonás hijo de Amitai (2 R 14:25).', fecha: 'c. 780-750 a.C.', destinatarios: 'Israel.', genero: 'Narrativa profética.',
    proposito: 'Mostrar la misericordia de Dios hacia las naciones y confrontar el nacionalismo estrecho.', tema: 'La compasión de Dios alcanza a los enemigos.', clave: 'Jon 4:11',
    cristo: 'La señal de Jonás: tres días y tres noches (Mt 12:40); "más que Jonás en este lugar".', debate: 'Carácter histórico o parabólico del relato.',
    estructura: [['Huida', 'Jon 1'], ['Oración en el pez', 'Jon 2'], ['Nínive se arrepiente', 'Jon 3'], ['La lección de la calabacera', 'Jon 4']] },
  33: { autor: 'Miqueas de Moreset.', fecha: 'c. 735-700 a.C.', destinatarios: 'Judá e Israel.', genero: 'Profecía.',
    proposito: 'Denunciar la injusticia y anunciar al rey que nacerá en Belén.', tema: 'Hacer justicia, amar misericordia, humillarse ante Dios.', clave: 'Miq 6:8',
    cristo: 'El gobernante que sale de Belén (5:2; Mt 2:6).', debate: 'Unidad del libro.',
    estructura: [['Juicio', 'Miq 1-3'], ['Esperanza y el rey de Belén', 'Miq 4-5'], ['El pleito de Dios y la esperanza', 'Miq 6-7']] },
  34: { autor: 'Nahúm de Elcos.', fecha: 'Entre 663 y 612 a.C.', destinatarios: 'Judá, sobre Nínive.', genero: 'Profecía (oráculo).',
    proposito: 'Anunciar la caída de Nínive y consolar a Judá.', tema: 'Jehová es bueno, fortaleza en el día de la angustia.', clave: 'Nah 1:7',
    cristo: 'Las buenas nuevas de paz (1:15; Ro 10:15).', debate: 'Ética del regocijo por la caída del enemigo.',
    estructura: [['El Dios vengador y bueno', 'Nah 1'], ['La caída de Nínive', 'Nah 2-3']] },
  35: { autor: 'Habacuc.', fecha: 'c. 609-598 a.C.', destinatarios: 'Judá.', genero: 'Diálogo profético y salmo.',
    proposito: 'Responder a por qué Dios permite el mal y usa a Babilonia: el justo vivirá por la fe.', tema: 'El justo por su fe vivirá.', clave: 'Hab 2:4',
    cristo: 'Texto clave del evangelio (Ro 1:17; Gá 3:11; He 10:38).', debate: 'Relación del salmo (cap. 3) con el resto.',
    estructura: [['Las quejas del profeta y las respuestas', 'Hab 1-2'], ['Oración de confianza', 'Hab 3']] },
  36: { autor: 'Sofonías, descendiente de Ezequías.', fecha: 'c. 640-621 a.C. (Josías).', destinatarios: 'Judá.', genero: 'Profecía.',
    proposito: 'Anunciar el Día de Jehová y la restauración de un remanente humilde.', tema: 'El Día de Jehová y el gozo de Dios sobre su pueblo.', clave: 'Sof 3:17',
    cristo: 'El Rey de Israel en medio de su pueblo (3:15).', debate: '—',
    estructura: [['El Día de Jehová', 'Sof 1'], ['Juicio de las naciones', 'Sof 2'], ['Restauración', 'Sof 3']] },
  37: { autor: 'Hageo.', fecha: '520 a.C.', destinatarios: 'Los que volvieron del exilio.', genero: 'Profecía fechada.',
    proposito: 'Exhortar a reconstruir el templo poniendo a Dios primero.', tema: 'Meditad sobre vuestros caminos.', clave: 'Hag 1:4-8',
    cristo: 'La gloria postrera mayor que la primera (2:9); Zorobabel como anillo de sellar (2:23), en la línea de Cristo.', debate: '—',
    estructura: [['Reconstruir el templo', 'Hag 1'], ['La gloria futura y la bendición', 'Hag 2']] },
  38: { autor: 'Zacarías hijo de Berequías.', fecha: '520-480 a.C.', destinatarios: 'La comunidad postexílica.', genero: 'Profecía y visiones apocalípticas.',
    proposito: 'Animar a terminar el templo y revelar al rey mesiánico y el futuro de Jerusalén.', tema: 'Volveos a mí y yo me volveré a vosotros.', clave: 'Zac 9:9',
    cristo: 'El rey humilde en un asno (9:9), las treinta piezas de plata (11:12-13), el traspasado (12:10), el pastor herido (13:7).', debate: 'Unidad (1-8 y 9-14).',
    estructura: [['Ocho visiones nocturnas', 'Zac 1-6'], ['Ayuno y restauración', 'Zac 7-8'], ['El rey y el pastor', 'Zac 9-11'], ['El día futuro de Jerusalén', 'Zac 12-14']] },
  39: { autor: 'Malaquías ("mi mensajero").', fecha: 'c. 460-430 a.C.', destinatarios: 'La comunidad postexílica.', genero: 'Profecía en forma de disputas.',
    proposito: 'Confrontar la indiferencia religiosa y anunciar al mensajero que prepara el camino.', tema: 'Yo os he amado: el Señor vendrá a su templo.', clave: 'Mal 3:1',
    cristo: 'El mensajero (Juan el Bautista, Mt 11:10) y el Señor que viene a su templo; el Sol de justicia (4:2).', debate: '¿Nombre propio o título?',
    estructura: [['El amor de Dios y los sacerdotes', 'Mal 1-2'], ['El mensajero y el día que viene', 'Mal 3-4']] },
};

const NT = {
  40: { autor: 'Mateo (Leví), apóstol y ex publicano (testimonio de Papías).', fecha: 'c. 50-70 d.C.', destinatarios: 'Cristianos de origen judío.', genero: 'Evangelio.',
    proposito: 'Mostrar que Jesús es el Mesías, Hijo de David, que cumple las Escrituras y establece el reino de los cielos.', tema: 'Jesús, el Rey prometido.', clave: 'Mt 28:18-20',
    cristo: 'Las fórmulas de cumplimiento ("para que se cumpliese") y cinco grandes discursos, como un nuevo Moisés.', debate: 'Relación sinóptica: prioridad de Marcos y la fuente Q, o prioridad de Mateo.',
    estructura: [['Nacimiento', 'Mt 1-2'], ['Sermón del monte', 'Mt 5-7'], ['Misión de los doce', 'Mt 10'], ['Parábolas del reino', 'Mt 13'], ['La comunidad', 'Mt 18'], ['Discurso escatológico', 'Mt 24-25'], ['Pasión y resurrección', 'Mt 26-28']] },
  41: { autor: 'Juan Marcos, compañero de Pedro (Papías).', fecha: 'c. 55-65 d.C.', destinatarios: 'Cristianos gentiles, probablemente en Roma.', genero: 'Evangelio.',
    proposito: 'Presentar a Jesús como el Hijo de Dios que sirve y da su vida en rescate.', tema: 'El Hijo de Dios, siervo sufriente.', clave: 'Mr 10:45',
    cristo: 'El secreto mesiánico y la confesión del centurión (15:39).', debate: 'El final largo (16:9-20) no está en los manuscritos más antiguos.',
    estructura: [['Ministerio en Galilea', 'Mr 1-8'], ['Camino a Jerusalén', 'Mr 8-10'], ['Semana de la pasión y resurrección', 'Mr 11-16']] },
  42: { autor: 'Lucas, médico y compañero de Pablo (Col 4:14).', fecha: 'c. 60-62 d.C.', destinatarios: 'Teófilo y lectores gentiles.', genero: 'Evangelio (historia ordenada).',
    proposito: 'Dar certeza de lo enseñado: Jesús es el Salvador de todos, especialmente de los marginados.', tema: 'El Hijo del hombre vino a buscar y salvar lo perdido.', clave: 'Lc 19:10',
    cristo: 'El Salvador universal; énfasis en la oración, el Espíritu y la misericordia (Lc 15).', debate: 'Fecha (antes o después del 70) y fuentes.',
    estructura: [['Nacimiento e infancia', 'Lc 1-2'], ['Ministerio en Galilea', 'Lc 3-9'], ['Viaje a Jerusalén', 'Lc 9-19'], ['Jerusalén: pasión y resurrección', 'Lc 19-24']] },
  43: { autor: 'Juan, el discípulo amado (21:24).', fecha: 'c. 85-95 d.C.', destinatarios: 'Creyentes e inquiridores del mundo grecorromano.', genero: 'Evangelio.',
    proposito: 'Que creáis que Jesús es el Cristo, el Hijo de Dios, y creyendo tengáis vida.', tema: 'Creer en el Hijo para tener vida eterna.', clave: 'Jn 20:31',
    cristo: 'El Verbo encarnado; siete señales y siete "Yo soy".', debate: 'Autoría (el apóstol o un "Juan el anciano"), relación con los sinópticos, Jn 7:53-8:11.',
    estructura: [['Prólogo', 'Jn 1:1-18'], ['Libro de las señales', 'Jn 1-12'], ['Discurso del aposento alto', 'Jn 13-17'], ['Pasión y resurrección', 'Jn 18-21']] },
  44: { autor: 'Lucas.', fecha: 'c. 62 d.C.', destinatarios: 'Teófilo.', genero: 'Historia.',
    proposito: 'Relatar cómo el Espíritu llevó el evangelio de Jerusalén hasta Roma.', tema: 'Testigos hasta lo último de la tierra.', clave: 'Hch 1:8',
    cristo: 'El Cristo resucitado y exaltado actúa por su Espíritu en la iglesia; sermones apostólicos cristocéntricos.', debate: 'Historicidad y relación con las cartas de Pablo.',
    estructura: [['Jerusalén', 'Hch 1-7'], ['Judea y Samaria', 'Hch 8-12'], ['Viajes misioneros de Pablo', 'Hch 13-21'], ['Pablo prisionero hasta Roma', 'Hch 21-28']] },
  45: { autor: 'Pablo.', fecha: 'c. 57 d.C., desde Corinto.', destinatarios: 'La iglesia en Roma (judíos y gentiles).', genero: 'Carta (tratado teológico).',
    proposito: 'Exponer el evangelio de la justicia de Dios por la fe, unir a judíos y gentiles y preparar la misión a España.', tema: 'La justicia de Dios revelada en el evangelio.', clave: 'Ro 1:16-17',
    cristo: 'Cristo, propiciación (3:25), el segundo Adán (5), el fin de la ley (10:4).', debate: 'La "nueva perspectiva sobre Pablo"; el yo de Romanos 7; Israel en 9-11.',
    estructura: [['El pecado universal', 'Ro 1-3'], ['Justificación por la fe', 'Ro 3-5'], ['Santificación y el Espíritu', 'Ro 6-8'], ['Israel en el plan de Dios', 'Ro 9-11'], ['Vida transformada', 'Ro 12-16']] },
  46: { autor: 'Pablo (con Sóstenes).', fecha: 'c. 55 d.C., desde Éfeso.', destinatarios: 'La iglesia en Corinto.', genero: 'Carta pastoral.',
    proposito: 'Corregir divisiones, inmoralidad y desorden en el culto, y responder preguntas.', tema: 'La cruz y el amor edifican a la iglesia.', clave: '1 Co 1:18',
    cristo: 'Cristo crucificado, sabiduría de Dios; la resurrección como primicias (15).', debate: 'El papel de la mujer (11; 14:34-35), los dones.',
    estructura: [['Divisiones y la cruz', '1 Co 1-4'], ['Problemas morales', '1 Co 5-6'], ['Matrimonio y libertad', '1 Co 7-10'], ['El culto y los dones', '1 Co 11-14'], ['La resurrección', '1 Co 15'], ['Conclusión', '1 Co 16']] },
  47: { autor: 'Pablo (con Timoteo).', fecha: 'c. 56 d.C., desde Macedonia.', destinatarios: 'La iglesia en Corinto.', genero: 'Carta personal y apologética.',
    proposito: 'Defender su ministerio frente a los "súper apóstoles" y organizar la ofrenda.', tema: 'El poder de Dios en la debilidad.', clave: '2 Co 12:9',
    cristo: 'El nuevo pacto, la reconciliación en Cristo (5:17-21).', debate: 'Unidad de la carta (¿varias cartas unidas?).',
    estructura: [['El ministerio del nuevo pacto', '2 Co 1-7'], ['La ofrenda', '2 Co 8-9'], ['Defensa de su apostolado', '2 Co 10-13']] },
  48: { autor: 'Pablo.', fecha: 'c. 48-55 d.C.', destinatarios: 'Las iglesias de Galacia.', genero: 'Carta polémica.',
    proposito: 'Defender la justificación por la fe sin las obras de la ley frente a los judaizantes.', tema: 'Libertad en Cristo.', clave: 'Gá 2:20',
    cristo: 'Cristo nos redimió de la maldición de la ley (3:13).', debate: 'Destinatarios del norte o del sur de Galacia y la fecha.',
    estructura: [['Defensa personal', 'Gá 1-2'], ['Argumento doctrinal', 'Gá 3-4'], ['Vida en el Espíritu', 'Gá 5-6']] },
  49: { autor: 'Pablo, desde la prisión.', fecha: 'c. 60-62 d.C.', destinatarios: 'Los santos en Éfeso (quizá circular).', genero: 'Carta.',
    proposito: 'Mostrar el plan eterno de Dios en Cristo y la unidad de la iglesia.', tema: 'Todas las cosas reunidas en Cristo; la iglesia, su cuerpo.', clave: 'Ef 1:9-10',
    cristo: 'Cabeza de la iglesia, nuestra paz (2:14).', debate: 'Autoría paulina discutida por la crítica; "en Éfeso" ausente en manuscritos antiguos.',
    estructura: [['Doctrina: la obra de Dios en Cristo', 'Ef 1-3'], ['Práctica: la vida nueva', 'Ef 4-6']] },
  50: { autor: 'Pablo (con Timoteo), en prisión.', fecha: 'c. 61 d.C.', destinatarios: 'La iglesia en Filipos.', genero: 'Carta de amistad.',
    proposito: 'Agradecer, informar y animar al gozo, la unidad y la humildad.', tema: 'El gozo en Cristo.', clave: 'Fil 1:21',
    cristo: 'El himno cristológico (2:5-11): se despojó y fue exaltado.', debate: 'Lugar de la prisión (Roma, Éfeso o Cesarea).',
    estructura: [['Gozo en el sufrimiento', 'Fil 1'], ['El ejemplo de Cristo', 'Fil 2'], ['Conocer a Cristo', 'Fil 3'], ['Paz y contentamiento', 'Fil 4']] },
  51: { autor: 'Pablo (con Timoteo), en prisión.', fecha: 'c. 60-62 d.C.', destinatarios: 'La iglesia en Colosas.', genero: 'Carta.',
    proposito: 'Refutar una falsa enseñanza mostrando la supremacía y suficiencia de Cristo.', tema: 'Cristo, preeminente en todo.', clave: 'Col 2:9-10',
    cristo: 'Imagen del Dios invisible, creador y reconciliador (1:15-20).', debate: 'Naturaleza de la herejía colosense; autoría.',
    estructura: [['La supremacía de Cristo', 'Col 1'], ['Libertad frente a la falsa enseñanza', 'Col 2'], ['La vida nueva', 'Col 3-4']] },
  52: { autor: 'Pablo, Silvano y Timoteo.', fecha: 'c. 50-51 d.C., desde Corinto.', destinatarios: 'La iglesia en Tesalónica.', genero: 'Carta.',
    proposito: 'Animar a una iglesia nueva perseguida y enseñar sobre la venida del Señor.', tema: 'Esperar al Señor viviendo en santidad.', clave: '1 Ts 4:16-17',
    cristo: 'La venida (parusía) de Cristo en cada capítulo.', debate: '—',
    estructura: [['Gratitud y defensa del ministerio', '1 Ts 1-3'], ['Santidad y la venida del Señor', '1 Ts 4-5']] },
  53: { autor: 'Pablo, Silvano y Timoteo.', fecha: 'c. 51 d.C.', destinatarios: 'La iglesia en Tesalónica.', genero: 'Carta.',
    proposito: 'Corregir la idea de que el Día del Señor ya había llegado y exhortar al trabajo.', tema: 'Firmeza hasta la venida del Señor.', clave: '2 Ts 2:15',
    cristo: 'El Señor vence al hombre de pecado con el espíritu de su boca (2:8).', debate: 'Autoría; identidad del "que lo detiene".',
    estructura: [['Consuelo en la persecución', '2 Ts 1'], ['El hombre de pecado', '2 Ts 2'], ['Contra la ociosidad', '2 Ts 3']] },
  54: { autor: 'Pablo.', fecha: 'c. 62-64 d.C.', destinatarios: 'Timoteo, en Éfeso.', genero: 'Carta pastoral.',
    proposito: 'Instruir sobre la sana doctrina, el orden de la iglesia y sus líderes.', tema: 'La conducta en la casa de Dios.', clave: '1 Ti 3:15-16',
    cristo: 'Un solo mediador (2:5); el misterio de la piedad (3:16).', debate: 'Autoría de las cartas pastorales; el ministerio de la mujer (2:11-15).',
    estructura: [['Contra los falsos maestros', '1 Ti 1'], ['Oración y culto', '1 Ti 2'], ['Obispos y diáconos', '1 Ti 3'], ['El buen ministro', '1 Ti 4-6']] },
  55: { autor: 'Pablo, en su última prisión.', fecha: 'c. 64-67 d.C.', destinatarios: 'Timoteo.', genero: 'Carta pastoral (testamento).',
    proposito: 'Animar a Timoteo a guardar el evangelio, sufrir y predicar la Palabra.', tema: 'Predica la palabra; persevera.', clave: '2 Ti 4:1-2',
    cristo: 'Jesucristo resucitado, del linaje de David (2:8).', debate: 'Autoría.',
    estructura: [['Guardar el depósito', '2 Ti 1'], ['Soldado, atleta, labrador', '2 Ti 2'], ['Los postreros días y la Escritura', '2 Ti 3'], ['Predica la palabra', '2 Ti 4']] },
  56: { autor: 'Pablo.', fecha: 'c. 63-65 d.C.', destinatarios: 'Tito, en Creta.', genero: 'Carta pastoral.',
    proposito: 'Establecer ancianos y enseñar que la sana doctrina produce buenas obras.', tema: 'La gracia que enseña a vivir.', clave: 'Tit 2:11-14',
    cristo: 'Nuestro gran Dios y Salvador Jesucristo (2:13).', debate: 'Autoría.',
    estructura: [['Ancianos', 'Tit 1'], ['Conducta en la iglesia', 'Tit 2'], ['Conducta en el mundo', 'Tit 3']] },
  57: { autor: 'Pablo, en prisión.', fecha: 'c. 60-62 d.C.', destinatarios: 'Filemón (y la iglesia en su casa).', genero: 'Carta personal.',
    proposito: 'Interceder por Onésimo, esclavo fugitivo convertido.', tema: 'Reconciliación y hermandad en Cristo.', clave: 'Flm 1:15-17',
    cristo: 'Pablo como intercesor que carga la deuda ajena (v. 18) refleja la obra de Cristo.', debate: 'La carta y la esclavitud.',
    estructura: [['Saludo y gratitud', 'Flm 1:1-7'], ['Intercesión por Onésimo', 'Flm 1:8-25']] },
  58: { autor: 'Desconocido (Pablo, Apolos, Bernabé y Lucas se han propuesto).', fecha: 'Antes del 70 d.C.', destinatarios: 'Cristianos judíos tentados a volver al judaísmo.', genero: 'Sermón escrito (palabra de exhortación, 13:22).',
    proposito: 'Mostrar la superioridad de Cristo y exhortar a perseverar.', tema: 'Jesús, mejor: mejor pacto, mejor sacerdote, mejor sacrificio.', clave: 'He 4:14-16',
    cristo: 'Sumo sacerdote según el orden de Melquisedec; sacrificio único (He 7-10).', debate: 'Autoría; las advertencias sobre la apostasía (6:4-6).',
    estructura: [['Superior a los ángeles y a Moisés', 'He 1-4'], ['Sumo sacerdote superior', 'He 5-7'], ['Nuevo pacto y sacrificio', 'He 8-10'], ['La fe y la perseverancia', 'He 11-13']] },
  59: { autor: 'Santiago, hermano del Señor.', fecha: 'c. 45-50 d.C. (quizá el primer escrito del NT).', destinatarios: 'Las doce tribus en la dispersión (cristianos judíos).', genero: 'Carta sapiencial.',
    proposito: 'Exhortar a una fe genuina que se muestra en obras.', tema: 'La fe que obra.', clave: 'Stg 2:17',
    cristo: 'La sabiduría de lo alto; ecos del Sermón del monte.', debate: 'Relación con Pablo sobre fe y obras.',
    estructura: [['Pruebas y tentaciones', 'Stg 1'], ['Fe y obras', 'Stg 2'], ['La lengua y la sabiduría', 'Stg 3'], ['Humildad, paciencia y oración', 'Stg 4-5']] },
  60: { autor: 'Pedro, apóstol (con Silvano).', fecha: 'c. 62-64 d.C., desde "Babilonia" (Roma).', destinatarios: 'Expatriados en Asia Menor.', genero: 'Carta.',
    proposito: 'Animar a cristianos que sufren a vivir con esperanza y santidad.', tema: 'Esperanza viva en medio del sufrimiento.', clave: '1 P 1:3-4',
    cristo: 'El Cordero sin mancha, el ejemplo en el sufrimiento (2:21-25), la piedra angular.', debate: 'Autoría (griego pulido); el descenso a los espíritus (3:19).',
    estructura: [['Salvación y santidad', '1 P 1-2'], ['Sumisión y sufrimiento', '1 P 2-4'], ['Pastores y firmeza', '1 P 5']] },
  61: { autor: 'Pedro.', fecha: 'c. 65-68 d.C.', destinatarios: 'Los mismos creyentes (3:1).', genero: 'Carta testamento.',
    proposito: 'Advertir contra los falsos maestros y afirmar la venida del Señor.', tema: 'Creced en la gracia y el conocimiento.', clave: '2 P 1:20-21',
    cristo: 'La transfiguración (1:16-18); el día del Señor.', debate: 'Autoría y relación con Judas; canonicidad debatida en la iglesia antigua.',
    estructura: [['Crecimiento y Escritura', '2 P 1'], ['Falsos maestros', '2 P 2'], ['La venida del Señor', '2 P 3']] },
  62: { autor: 'Juan, apóstol.', fecha: 'c. 85-95 d.C.', destinatarios: 'Iglesias de Asia.', genero: 'Carta-tratado.',
    proposito: 'Dar seguridad de la vida eterna y refutar a quienes negaban la encarnación.', tema: 'Dios es luz y Dios es amor.', clave: '1 Jn 5:13',
    cristo: 'Jesucristo venido en carne, abogado y propiciación (2:1-2).', debate: 'El "coma joánico" (5:7-8) no está en los manuscritos antiguos.',
    estructura: [['Andar en la luz', '1 Jn 1-2'], ['Hijos de Dios y amor', '1 Jn 3-4'], ['Fe y seguridad', '1 Jn 5']] },
  63: { autor: 'Juan, "el anciano".', fecha: 'c. 90 d.C.', destinatarios: '"La señora elegida y sus hijos" (una iglesia).', genero: 'Carta breve.',
    proposito: 'Exhortar al amor y a no recibir a los engañadores.', tema: 'Verdad y amor.', clave: '2 Jn 1:6',
    cristo: 'Confesar a Jesucristo venido en carne (v. 7).', debate: '—',
    estructura: [['Andar en verdad y amor', '2 Jn 1:1-6'], ['Advertencia', '2 Jn 1:7-13']] },
  64: { autor: 'Juan, "el anciano".', fecha: 'c. 90 d.C.', destinatarios: 'Gayo.', genero: 'Carta personal.',
    proposito: 'Alabar la hospitalidad de Gayo y corregir a Diótrefes.', tema: 'Colaboradores de la verdad.', clave: '3 Jn 1:11',
    cristo: 'Salen por amor del Nombre (v. 7).', debate: '—',
    estructura: [['Gayo', '3 Jn 1:1-8'], ['Diótrefes y Demetrio', '3 Jn 1:9-15']] },
  65: { autor: 'Judas, hermano de Santiago y del Señor.', fecha: 'c. 65-80 d.C.', destinatarios: 'Llamados, amados y guardados.', genero: 'Carta.',
    proposito: 'Exhortar a contender por la fe frente a los impíos infiltrados.', tema: 'Contender por la fe una vez dada.', clave: 'Jud 1:3',
    cristo: 'Aquel que es poderoso para guardaros sin caída (vv. 24-25).', debate: 'Citas de Enoc y de la Asunción de Moisés.',
    estructura: [['Propósito', 'Jud 1:1-4'], ['Los impíos y su juicio', 'Jud 1:5-16'], ['Exhortación y doxología', 'Jud 1:17-25']] },
  66: { autor: 'Juan (1:1, 4, 9).', fecha: 'c. 95 d.C. (Domiciano) o c. 68 d.C.', destinatarios: 'Las siete iglesias de Asia.', genero: 'Apocalíptica, profecía y carta.',
    proposito: 'Revelar a Jesucristo y animar a la iglesia perseguida a vencer: el Cordero reina y hará nuevas todas las cosas.', tema: 'El Cordero vence.', clave: 'Ap 1:19',
    cristo: 'El Hijo del hombre glorificado, el Cordero inmolado en el trono, el Rey de reyes.', debate: 'Escuelas de interpretación: preterista, historicista, futurista e idealista; el milenio (20).',
    estructura: [['Visión de Cristo', 'Ap 1'], ['Cartas a las siete iglesias', 'Ap 2-3'], ['El trono y el Cordero', 'Ap 4-5'], ['Sellos, trompetas y copas', 'Ap 6-16'], ['Caída de Babilonia', 'Ap 17-19'], ['El milenio y el juicio', 'Ap 20'], ['Cielo nuevo y tierra nueva', 'Ap 21-22']] },
};

export const INTRODUCCIONES = { ...AT, ...NT };
export const introduccion = (b) => INTRODUCCIONES[b] || null;
