/**
 * ciudadania.js — Banco de política y ciudadanía.
 *
 * Es el área que el Saber 11 llama "sociales y ciudadanas" y el EXANI-II ubica
 * en ciencias sociales: cómo está organizado el Estado, qué dice la
 * Constitución, qué derechos hay y cómo se ejercen, cómo funcionan las
 * elecciones y de dónde sale el dinero público.
 *
 * Dos reglas al escribirlo: nada de nombres de gobernantes ni de cifras que
 * caducan, y nada de tomar partido. Se pregunta cómo funcionan las reglas, no
 * quién tiene razón. Cuando una figura cambia de nombre según el país (tutela,
 * amparo), se dicen los dos.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const CIUDADANIA = [
  // ----- El Estado y las ramas del poder -----
  {
    id: 'civ-001', tema: 'estado-poderes', dificultad: 1,
    enunciado: '¿Cuáles son las tres ramas clásicas del poder público?',
    opciones: [
      'Ejecutiva, legislativa y judicial',
      'Nacional, departamental y municipal',
      'Civil, militar y religiosa',
      'Política, económica y social',
    ],
    correcta: 0,
    explicacion: 'Es la separación de poderes que formuló Montesquieu: quien hace las leyes no es quien las ejecuta ni quien las aplica en un juicio. Lo nacional, departamental y municipal son niveles de gobierno, no ramas.',
  },
  {
    id: 'civ-002', tema: 'estado-poderes', dificultad: 1,
    enunciado: '¿Cuál es la función principal del poder legislativo?',
    opciones: [
      'Hacer, reformar y derogar las leyes',
      'Administrar el presupuesto del Estado día a día',
      'Juzgar a quienes incumplen las leyes',
      'Nombrar a los jueces de todo el país',
    ],
    correcta: 0,
    explicacion: 'El congreso o parlamento legisla y además controla políticamente al gobierno. Administrar es tarea del ejecutivo y juzgar, del judicial.',
  },
  {
    id: 'civ-003', tema: 'estado-poderes', dificultad: 1,
    enunciado: 'Aplicar la ley a un caso concreto y resolver el conflicto entre dos partes le corresponde a:',
    opciones: ['El poder judicial', 'El poder legislativo', 'El poder ejecutivo', 'La policía'],
    correcta: 0,
    explicacion: 'Los jueces interpretan la ley y deciden el caso. La policía ejecuta las decisiones y pertenece al ejecutivo, pero no juzga.',
  },
  {
    id: 'civ-004', tema: 'estado-poderes', dificultad: 2,
    enunciado: '¿Para qué sirve la separación de poderes?',
    opciones: [
      'Para que ningún órgano concentre todo el poder y cada uno controle a los otros',
      'Para que el gobierno pueda tomar decisiones más rápido',
      'Para repartir el territorio entre distintas autoridades',
      'Para que cada rama se ocupe de una región del país',
    ],
    correcta: 0,
    explicacion: 'La idea es de frenos y contrapesos: el poder limita al poder. Suele hacer las decisiones más lentas, y eso es parte del diseño, no un defecto.',
  },
  {
    id: 'civ-005', tema: 'estado-poderes', dificultad: 2,
    enunciado: '¿Cuál de estas es una forma de control del legislativo sobre el ejecutivo?',
    opciones: [
      'Aprobar o rechazar el presupuesto que presenta el gobierno',
      'Nombrar a los alcaldes de las ciudades',
      'Declarar inconstitucional una ley',
      'Dictar sentencia en un juicio penal',
    ],
    correcta: 0,
    explicacion: 'El control del presupuesto y la citación de ministros son las herramientas típicas del congreso. Declarar inconstitucional una ley le corresponde al tribunal o corte constitucional.',
  },
  {
    id: 'civ-006', tema: 'estado-poderes', dificultad: 2,
    enunciado: 'El presidente objeta (veta) una ley aprobada por el congreso. ¿Qué suele ocurrir después?',
    opciones: [
      'El congreso puede insistir y aprobarla de nuevo, normalmente con una mayoría más alta',
      'La ley queda eliminada de forma definitiva',
      'La ley entra en vigor igualmente sin cambios',
      'La ley pasa a votación popular obligatoria',
    ],
    correcta: 0,
    explicacion: 'El veto es un freno, no un poder absoluto: si el legislativo insiste con la mayoría exigida, la ley sigue adelante. Otra vez, frenos y contrapesos.',
  },
  {
    id: 'civ-007', tema: 'estado-poderes', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre Estado y gobierno?',
    opciones: [
      'El Estado es la organización permanente; el gobierno es transitorio y se renueva con las elecciones',
      'Son sinónimos usados en contextos distintos',
      'El Estado es el territorio y el gobierno es la población',
      'El Estado es local y el gobierno es nacional',
    ],
    correcta: 0,
    explicacion: 'Cambian los gobiernos y el Estado permanece con su territorio, su población, sus instituciones y sus compromisos. Por eso las deudas y los tratados siguen vigentes tras un cambio de gobierno.',
  },
  {
    id: 'civ-008', tema: 'estado-poderes', dificultad: 2,
    enunciado: 'La descentralización consiste en:',
    opciones: [
      'Transferir competencias y recursos del gobierno nacional a los gobiernos locales',
      'Trasladar la capital del país a otra ciudad',
      'Eliminar los niveles intermedios de gobierno',
      'Privatizar los servicios públicos',
    ],
    correcta: 0,
    explicacion: 'La idea es que decida quien está más cerca del problema. Su riesgo es que si se transfieren funciones sin recursos ni capacidad técnica, el servicio empeora.',
  },
  {
    id: 'civ-009', tema: 'estado-poderes', dificultad: 2,
    enunciado: '¿Cuál de estas funciones corresponde al poder ejecutivo?',
    opciones: [
      'Dirigir la administración pública y hacer cumplir las leyes',
      'Aprobar el código penal',
      'Resolver una demanda entre dos empresas',
      'Reformar la Constitución por su cuenta',
    ],
    correcta: 0,
    explicacion: 'El ejecutivo gobierna y administra: ministerios, fuerza pública, servicios y política exterior. Legislar y juzgar son de las otras dos ramas.',
  },
  {
    id: 'civ-010', tema: 'estado-poderes', dificultad: 3,
    enunciado: 'Un tribunal declara inconstitucional una ley que el congreso aprobó y el presidente sancionó. ¿Qué principio se está aplicando?',
    opciones: [
      'El control constitucional, una forma de freno entre poderes',
      'La soberanía popular, porque el pueblo eligió a los jueces',
      'La jerarquía militar del Estado',
      'La autonomía de los gobiernos locales',
    ],
    correcta: 0,
    explicacion: 'Que dos poderes estén de acuerdo no basta si la norma contradice la Constitución. Ese control es lo que impide que una mayoría del momento cambie las reglas básicas por la puerta de atrás.',
    pista: 'Fíjate en quién vigila a quién.',
  },

  // ----- Constitución y jerarquía de las normas -----
  {
    id: 'civ-011', tema: 'constitucion', dificultad: 1,
    enunciado: '¿Qué es la Constitución de un país?',
    opciones: [
      'La norma suprema que organiza el Estado y reconoce los derechos de las personas',
      'El conjunto de leyes aprobadas por el congreso cada año',
      'El programa de gobierno del presidente electo',
      'El reglamento interno de los tribunales',
    ],
    correcta: 0,
    explicacion: 'Por eso se le llama carta magna o ley de leyes: todas las demás normas deben ajustarse a ella.',
  },
  {
    id: 'civ-012', tema: 'constitucion', dificultad: 2,
    enunciado: 'Si una ley contradice la Constitución, ¿qué sucede?',
    opciones: [
      'Prevalece la Constitución y la ley puede ser declarada inconstitucional',
      'Prevalece la ley, porque es más reciente',
      'Las dos se aplican a la vez y decide cada juez',
      'La Constitución se reforma automáticamente',
    ],
    correcta: 0,
    explicacion: 'Es el principio de supremacía constitucional. La fecha no importa: una ley nueva no puede sobreponerse a la Constitución.',
  },
  {
    id: 'civ-013', tema: 'constitucion', dificultad: 2,
    enunciado: 'Ordena de mayor a menor jerarquía: decreto del gobierno, Constitución, ley del congreso.',
    opciones: [
      'Constitución, ley, decreto',
      'Ley, Constitución, decreto',
      'Decreto, ley, Constitución',
      'Todas tienen la misma jerarquía',
    ],
    correcta: 0,
    explicacion: 'Cada norma debe respetar a la superior. Un decreto que contradiga una ley es nulo, igual que una ley que contradiga la Constitución.',
  },
  {
    id: 'civ-014', tema: 'constitucion', dificultad: 2,
    enunciado: '¿Qué significa que un país sea un Estado de derecho?',
    opciones: [
      'Que gobernantes y gobernados están sometidos por igual a la ley',
      'Que el Estado tiene derecho a hacer lo que considere necesario',
      'Que existe una constitución escrita',
      'Que hay elecciones cada cierto número de años',
    ],
    correcta: 0,
    explicacion: 'Lo decisivo es que el poder también tenga límites jurídicos y que haya jueces capaces de hacerlos valer. Tener constitución escrita o elecciones no basta si el poder no responde ante la ley.',
  },
  {
    id: 'civ-015', tema: 'constitucion', dificultad: 2,
    enunciado: 'En una Constitución, la parte dogmática contiene:',
    opciones: [
      'Los derechos, deberes y principios fundamentales',
      'La estructura y las funciones de los órganos del Estado',
      'El procedimiento para reformar la propia Constitución',
      'El presupuesto anual de la nación',
    ],
    correcta: 0,
    explicacion: 'La parte orgánica es la que describe cómo está armado el Estado: ramas, competencias y procedimientos.',
  },
  {
    id: 'civ-016', tema: 'constitucion', dificultad: 3,
    enunciado: '¿Por qué reformar la Constitución suele ser más difícil que aprobar una ley?',
    opciones: [
      'Para dar estabilidad a las reglas básicas y proteger derechos frente a mayorías del momento',
      'Porque el texto constitucional es más largo',
      'Porque solo los jueces pueden proponer reformas',
      'Porque las constituciones no se pueden cambiar nunca',
    ],
    correcta: 0,
    explicacion: 'Se llaman constituciones rígidas: exigen mayorías especiales, varias votaciones o incluso referendo. La idea es que las reglas del juego no cambien con cada gobierno.',
  },
  {
    id: 'civ-017', tema: 'constitucion', dificultad: 2,
    enunciado: 'Un decreto es una norma:',
    opciones: [
      'Expedida por el poder ejecutivo y subordinada a la ley',
      'Aprobada por el congreso en tres debates',
      'Dictada por un juez para resolver un caso',
      'Votada directamente por los ciudadanos',
    ],
    correcta: 0,
    explicacion: 'Sirve para reglamentar y ejecutar lo que la ley dispone. Si un decreto va más allá de la ley que reglamenta, puede ser anulado.',
  },
  {
    id: 'civ-018', tema: 'constitucion', dificultad: 3,
    enunciado: 'El principio de irretroactividad de la ley significa que:',
    opciones: [
      'La ley rige hacia el futuro y no se aplica a hechos anteriores, salvo cuando favorece al procesado',
      'Una ley no puede ser derogada por otra posterior',
      'Las leyes solo valen mientras dure el gobierno que las aprobó',
      'Ninguna ley puede aplicarse antes de un año desde su publicación',
    ],
    correcta: 0,
    explicacion: 'Nadie puede ser castigado por algo que no era delito cuando lo hizo. La excepción es la ley penal más benigna, que sí se aplica hacia atrás.',
  },
  {
    id: 'civ-019', tema: 'constitucion', dificultad: 2,
    enunciado: 'La regla de que nadie puede ser juzgado dos veces por el mismo hecho se conoce como:',
    opciones: ['Cosa juzgada (non bis in idem)', 'Presunción de inocencia', 'Debido proceso', 'Habeas corpus'],
    correcta: 0,
    explicacion: 'Una vez que hay sentencia en firme, el asunto queda cerrado. Es una garantía frente a la persecución indefinida del Estado.',
  },
  {
    id: 'civ-020', tema: 'constitucion', dificultad: 2,
    enunciado: 'La presunción de inocencia implica que:',
    opciones: [
      'Corresponde a quien acusa probar la culpabilidad, no al acusado probar su inocencia',
      'Nadie puede ser detenido antes de un juicio',
      'El acusado puede negarse a comparecer ante el juez',
      'Los delitos graves no admiten defensa',
    ],
    correcta: 0,
    explicacion: 'La carga de la prueba está en la acusación. Por eso, cuando la prueba es insuficiente, la duda favorece al acusado.',
  },

  // ----- Derechos humanos y mecanismos de protección -----
  {
    id: 'civ-021', tema: 'derechos', dificultad: 1,
    enunciado: 'La Declaración Universal de los Derechos Humanos fue adoptada en 1948 por:',
    opciones: ['La Organización de las Naciones Unidas', 'La Unión Europea', 'La Organización de Estados Americanos', 'La Cruz Roja Internacional'],
    correcta: 0,
    explicacion: 'Se aprobó tras la Segunda Guerra Mundial y es el texto del que derivan la mayoría de los tratados de derechos humanos posteriores.',
  },
  {
    id: 'civ-022', tema: 'derechos', dificultad: 2,
    enunciado: 'Que los derechos humanos sean inalienables significa que:',
    opciones: [
      'Nadie puede renunciar a ellos ni ser despojado de ellos',
      'Solo los tienen los ciudadanos de un país',
      'Se pierden si la persona comete un delito',
      'Solo valen dentro del territorio donde se firmaron',
    ],
    correcta: 0,
    explicacion: 'Son además universales (los tiene toda persona) e indivisibles (no se puede sacrificar uno para cumplir otro). Una condena limita algunos derechos, como la libertad, pero no anula la dignidad ni el resto.',
  },
  {
    id: 'civ-023', tema: 'derechos', dificultad: 2,
    enunciado: 'El derecho a un ambiente sano se clasifica habitualmente como un derecho de:',
    opciones: [
      'Tercera generación, porque es colectivo y afecta a toda la comunidad',
      'Primera generación, junto a las libertades civiles y políticas',
      'Segunda generación, junto a los derechos económicos y sociales',
      'No es un derecho, sino un objetivo de política pública',
    ],
    correcta: 0,
    explicacion: 'Los de primera generación son civiles y políticos (libertad, voto); los de segunda, económicos, sociales y culturales (salud, educación, trabajo); los de tercera son colectivos: ambiente, paz, desarrollo.',
  },
  {
    id: 'civ-024', tema: 'derechos', dificultad: 2,
    enunciado: 'El habeas corpus es un mecanismo que protege:',
    opciones: [
      'La libertad personal frente a una detención ilegal o arbitraria',
      'Los datos personales frente a bases de datos erróneas',
      'El derecho a la educación de los menores',
      'La propiedad privada frente a una expropiación',
    ],
    correcta: 0,
    explicacion: 'Obliga a que una autoridad judicial revise de inmediato si la privación de libertad es legal. Su equivalente para los datos personales es el habeas data.',
  },
  {
    id: 'civ-025', tema: 'derechos', dificultad: 2,
    enunciado: 'La acción de tutela (llamada amparo en varios países) sirve para:',
    opciones: [
      'Proteger de forma rápida un derecho fundamental que está siendo vulnerado',
      'Demandar a una empresa por incumplir un contrato',
      'Solicitar la revisión de una sentencia penal',
      'Pedir una pensión al sistema de seguridad social',
    ],
    correcta: 0,
    explicacion: 'Es un procedimiento breve y sin formalismos, pensado para cuando esperar un proceso ordinario haría inútil la protección.',
  },
  {
    id: 'civ-026', tema: 'derechos', dificultad: 3,
    enunciado: 'El derecho a la igualdad admite que la ley trate distinto a personas en situaciones distintas. Ese trato diferenciado es legítimo cuando:',
    opciones: [
      'Busca corregir una desigualdad real y existe una razón objetiva que lo justifique',
      'Lo aprueba la mayoría de la población',
      'Beneficia al grupo más numeroso del país',
      'Está escrito en cualquier norma vigente',
    ],
    correcta: 0,
    explicacion: 'Es la diferencia entre distinción y discriminación: una rampa de acceso o una cuota de admisión buscan equiparar puntos de partida desiguales. Que una mayoría lo apruebe no hace legítima una distinción arbitraria.',
  },
  {
    id: 'civ-027', tema: 'derechos', dificultad: 3,
    enunciado: 'La libertad de expresión es un derecho fundamental, pero no ampara:',
    opciones: [
      'La incitación a la violencia ni la difamación deliberada',
      'Las críticas duras a un gobernante',
      'Las opiniones que ofenden a una parte de la sociedad',
      'La publicación de información incómoda para el poder',
    ],
    correcta: 0,
    explicacion: 'Los límites son estrechos y deben estar definidos en la ley. Criticar al poder o incomodar con una opinión es justamente lo que el derecho protege; incitar a dañar a alguien, no.',
  },
  {
    id: 'civ-028', tema: 'derechos', dificultad: 2,
    enunciado: 'El habeas data permite a una persona:',
    opciones: [
      'Conocer, actualizar y corregir los datos que existen sobre ella en bases de datos',
      'Acceder gratuitamente a internet',
      'Impedir que la prensa publique noticias sobre ella',
      'Obtener copia de cualquier documento del Estado',
    ],
    correcta: 0,
    explicacion: 'Es clave frente a los registros de deudores o a las bases de datos comerciales. El acceso a documentos públicos se ejerce con el derecho de petición o de acceso a la información.',
  },
  {
    id: 'civ-029', tema: 'derechos', dificultad: 2,
    enunciado: 'El principio del interés superior del niño significa que:',
    opciones: [
      'Ante un conflicto de derechos, prevalece lo que mejor proteja al menor',
      'Los niños tienen más derechos que los adultos en cualquier situación',
      'Los padres deciden siempre lo que es mejor para el menor',
      'Los menores no tienen obligaciones de ningún tipo',
    ],
    correcta: 0,
    explicacion: 'No significa que el niño mande, sino que su bienestar es el criterio que orienta la decisión de jueces, autoridades y familias.',
  },
  {
    id: 'civ-030', tema: 'derechos', dificultad: 3,
    enunciado: 'Se dice que todo derecho implica un deber correlativo. ¿Qué ejemplo lo ilustra mejor?',
    opciones: [
      'Mi derecho a un juicio justo implica el deber del Estado de garantizar un juez imparcial',
      'Mi derecho al voto implica el deber de votar por el mejor candidato',
      'Mi derecho a la salud implica el deber de no enfermarme',
      'Mi derecho a la educación implica el deber de sacar buenas notas',
    ],
    correcta: 0,
    explicacion: 'El deber correlativo recae en quien debe hacer posible el derecho: el Estado o los demás ciudadanos. Las otras opciones confunden el derecho con una obligación personal de resultado.',
  },

  // ----- Democracia y participación -----
  {
    id: 'civ-031', tema: 'democracia', dificultad: 1,
    enunciado: '¿Cuál es la diferencia entre democracia directa y representativa?',
    opciones: [
      'En la directa los ciudadanos deciden por sí mismos; en la representativa eligen a quienes deciden por ellos',
      'La directa se usa en países pequeños y la representativa en grandes',
      'La directa es antigua y la representativa es la única válida hoy',
      'En la directa solo vota una parte de la población',
    ],
    correcta: 0,
    explicacion: 'La mayoría de los sistemas actuales son mixtos: eligen representantes y además conservan mecanismos directos como el referendo.',
  },
  {
    id: 'civ-032', tema: 'democracia', dificultad: 1,
    enunciado: 'El sufragio universal significa que pueden votar:',
    opciones: [
      'Todos los ciudadanos mayores de edad, sin distinción de sexo, origen o riqueza',
      'Únicamente quienes pagan impuestos',
      'Todos los habitantes del país, incluidos los extranjeros en cualquier elección',
      'Solo quienes se inscriben en un partido político',
    ],
    correcta: 0,
    explicacion: 'Se opone al sufragio censitario, que exigía propiedad o renta, y al masculino, que excluía a las mujeres. Ambas restricciones fueron la norma hasta bien entrado el siglo XX.',
  },
  {
    id: 'civ-033', tema: 'democracia', dificultad: 2,
    enunciado: '¿Por qué el voto es secreto?',
    opciones: [
      'Para que nadie pueda presionar, comprar o castigar el voto de otra persona',
      'Para que las autoridades no conozcan los resultados antes de tiempo',
      'Para evitar que se cuenten mal las papeletas',
      'Porque así lo exigen los partidos políticos',
    ],
    correcta: 0,
    explicacion: 'Sin secreto no hay libertad: el jefe, el líder local o el comprador de votos podría verificar el cumplimiento. Es la garantía que hace posible el voto libre.',
  },
  {
    id: 'civ-034', tema: 'democracia', dificultad: 2,
    enunciado: 'Un referendo es un mecanismo mediante el cual:',
    opciones: [
      'Los ciudadanos aprueban o rechazan directamente una norma o decisión',
      'El congreso interpela a un ministro',
      'Un juez revisa la constitucionalidad de una ley',
      'Un partido elige a su candidato',
    ],
    correcta: 0,
    explicacion: 'Junto al plebiscito, la consulta popular y la iniciativa legislativa, es una de las formas de participación directa que conservan las democracias representativas.',
  },
  {
    id: 'civ-035', tema: 'democracia', dificultad: 2,
    enunciado: 'La revocatoria del mandato permite que:',
    opciones: [
      'Los electores den por terminado antes de tiempo el mandato de un gobernante que eligieron',
      'El congreso destituya a un juez',
      'El presidente disuelva el parlamento',
      'Un partido expulse a uno de sus militantes',
    ],
    correcta: 0,
    explicacion: 'Es un control ciudadano posterior a la elección. Suele exigir un número alto de firmas y una participación mínima para que el resultado sea válido.',
  },
  {
    id: 'civ-036', tema: 'democracia', dificultad: 2,
    enunciado: 'La iniciativa popular legislativa consiste en que:',
    opciones: [
      'Un grupo de ciudadanos presenta un proyecto de ley recogiendo firmas',
      'Los ciudadanos eligen directamente a los ministros',
      'Una ley entra en vigor sin pasar por el congreso',
      'El pueblo redacta una nueva constitución cada década',
    ],
    correcta: 0,
    explicacion: 'El proyecto entra al trámite legislativo como cualquier otro: la iniciativa es ciudadana, pero la decisión sigue siendo del congreso.',
  },
  {
    id: 'civ-037', tema: 'democracia', dificultad: 3,
    enunciado: 'Se dice que la democracia no se agota en votar cada cuatro años. ¿Qué ejemplo respalda mejor esa idea?',
    opciones: [
      'Las veedurías ciudadanas, los cabildos abiertos y el derecho de petición',
      'La existencia de varios partidos en el congreso',
      'La publicación de encuestas antes de las elecciones',
      'El conteo rápido de votos la misma noche electoral',
    ],
    correcta: 0,
    explicacion: 'La participación entre elecciones —vigilar el gasto, pedir información, asistir a audiencias— es lo que hace que el mandato se ejerza con control y no en blanco.',
  },
  {
    id: 'civ-038', tema: 'democracia', dificultad: 2,
    enunciado: 'En una democracia, ¿qué ocurre con los derechos de las minorías?',
    opciones: [
      'Se respetan, porque la mayoría no puede decidir sobre los derechos fundamentales de nadie',
      'Se suspenden mientras gobierne la mayoría',
      'Dependen de que la minoría llegue a acuerdos con el gobierno',
      'Solo se protegen si están escritos en una ley ordinaria',
    ],
    correcta: 0,
    explicacion: 'Regla de mayoría para decidir, límites constitucionales para lo que no se puede decidir. Sin ese segundo elemento, la democracia se convierte en el gobierno del más numeroso.',
  },
  {
    id: 'civ-039', tema: 'democracia', dificultad: 3,
    enunciado: 'Una elección se gana con el 52 % de los votos, pero solo participó el 40 % de los habilitados. ¿Qué problema plantea?',
    opciones: [
      'El ganador representa en realidad a una fracción pequeña del electorado, lo que debilita su legitimidad',
      'La elección es jurídicamente nula',
      'El ganador debe repetir la votación al año siguiente',
      'No plantea ningún problema, porque ganó la mayoría',
    ],
    correcta: 0,
    explicacion: 'El 52 % del 40 % es cerca del 21 % del censo. La elección es válida, pero la abstención alta es una señal de desconexión entre las instituciones y la gente.',
    pista: 'Calcula qué porcentaje del total de habilitados lo votó.',
  },
  {
    id: 'civ-040', tema: 'democracia', dificultad: 2,
    enunciado: '¿Cuál de las siguientes es un deber ciudadano y no un derecho?',
    opciones: [
      'Respetar los derechos de los demás y cumplir la ley',
      'Elegir y ser elegido',
      'Recibir educación básica',
      'Asociarse con otras personas',
    ],
    correcta: 0,
    explicacion: 'La ciudadanía es un vínculo de doble vía: derechos y deberes. Los otros tres enunciados son derechos reconocidos en casi todas las constituciones.',
  },

  // ----- Formas de gobierno y sistemas políticos -----
  {
    id: 'civ-041', tema: 'sistemas-politicos', dificultad: 1,
    enunciado: '¿Cuál es la diferencia esencial entre una república y una monarquía?',
    opciones: [
      'En la república la jefatura del Estado es electiva y temporal; en la monarquía es hereditaria y vitalicia',
      'En la república hay elecciones y en la monarquía no las hay nunca',
      'En la república hay separación de poderes y en la monarquía no',
      'La república es moderna y la monarquía ya no existe',
    ],
    correcta: 0,
    explicacion: 'Hay monarquías parlamentarias plenamente democráticas, con elecciones y separación de poderes, donde el rey reina pero no gobierna.',
  },
  {
    id: 'civ-042', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: '¿Qué distingue a un sistema parlamentario de uno presidencialista?',
    opciones: [
      'En el parlamentario el jefe de gobierno surge del parlamento y este puede removerlo',
      'En el parlamentario no existe jefe de Estado',
      'En el presidencialista el presidente no es elegido por los ciudadanos',
      'En el parlamentario no hay partidos políticos',
    ],
    correcta: 0,
    explicacion: 'En el presidencialismo el presidente tiene mandato fijo y legitimidad propia; en el parlamentarismo el gobierno depende de la confianza de la cámara y puede caer con una moción de censura.',
  },
  {
    id: 'civ-043', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: 'Que un Estado sea laico significa que:',
    opciones: [
      'No adopta una religión oficial y garantiza la libertad de culto',
      'Prohíbe la práctica de cualquier religión',
      'Obliga a los ciudadanos a declararse sin religión',
      'Financia por igual a todas las iglesias del país',
    ],
    correcta: 0,
    explicacion: 'La laicidad separa Estado y religión para que nadie sea favorecido ni perjudicado por su creencia. No es lo mismo que el ateísmo de Estado.',
  },
  {
    id: 'civ-044', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: '¿Cuál es un rasgo característico de un régimen autoritario?',
    opciones: [
      'La concentración del poder sin elecciones competitivas ni controles independientes',
      'La existencia de un parlamento con varias cámaras',
      'La celebración de elecciones periódicas de cualquier tipo',
      'La presencia de un jefe de Estado con funciones ceremoniales',
    ],
    correcta: 0,
    explicacion: 'Lo decisivo no es que haya elecciones, sino que sean competitivas y que existan prensa libre, oposición y jueces independientes. Un régimen puede votar y seguir siendo autoritario.',
  },
  {
    id: 'civ-045', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: 'La alternancia en el poder consiste en que:',
    opciones: [
      'Distintas fuerzas políticas se turnan en el gobierno mediante elecciones',
      'El presidente y el vicepresidente se reparten el mandato',
      'Cada región gobierna el país por turnos',
      'El poder pasa del ejecutivo al legislativo cada cierto tiempo',
    ],
    correcta: 0,
    explicacion: 'Es uno de los indicadores más usados para evaluar si un sistema es realmente competitivo: que perder una elección sea una posibilidad real para quien gobierna.',
  },
  {
    id: 'civ-046', tema: 'sistemas-politicos', dificultad: 3,
    enunciado: 'En el eje político clásico, la discusión entre izquierda y derecha se ha organizado históricamente alrededor de:',
    opciones: [
      'El papel que debe tener el Estado en la economía y la redistribución',
      'La preferencia por la guerra o por la paz',
      'La aceptación o el rechazo de la democracia',
      'El tamaño del territorio que debe tener el país',
    ],
    correcta: 0,
    explicacion: 'Es una simplificación, pero sigue siendo el eje principal: más intervención y redistribución frente a más mercado y menos Estado. Hoy se cruza con otros ejes, como los temas culturales o ambientales.',
  },
  {
    id: 'civ-047', tema: 'sistemas-politicos', dificultad: 3,
    enunciado: '¿Por qué un sistema con controles débiles entre poderes tiende al abuso, aunque el gobernante haya sido elegido?',
    opciones: [
      'Porque sin un órgano capaz de frenarlo, nada impide que use el poder en su propio beneficio',
      'Porque los gobernantes electos siempre quieren perpetuarse',
      'Porque las elecciones no tienen valor jurídico',
      'Porque la ciudadanía nunca protesta contra un gobierno electo',
    ],
    correcta: 0,
    explicacion: 'El argumento no es sobre las intenciones de nadie, sino sobre el diseño institucional: un poder sin contrapeso depende por completo de la buena voluntad de quien lo ejerce.',
  },
  {
    id: 'civ-048', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: '¿Cuál de estas situaciones NO corresponde a una democracia plena?',
    opciones: [
      'Un solo partido puede presentarse a las elecciones',
      'La oposición controla algunas gobernaciones',
      'Los jueces anulan decisiones del gobierno',
      'Los medios critican abiertamente al presidente',
    ],
    correcta: 0,
    explicacion: 'Sin competencia real no hay elección, solo ratificación. Las otras tres son justamente señales de que los contrapesos funcionan.',
  },
  {
    id: 'civ-049', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: 'Se llama Estado de bienestar al modelo en el que:',
    opciones: [
      'El Estado garantiza servicios básicos como salud, educación y pensiones mediante impuestos',
      'El Estado es dueño de todas las empresas del país',
      'El Estado no interviene en la economía',
      'El bienestar depende exclusivamente de la caridad privada',
    ],
    correcta: 0,
    explicacion: 'Se consolidó en Europa tras la Segunda Guerra Mundial. No implica que el Estado sea dueño de todo: convive con economías de mercado.',
  },
  {
    id: 'civ-050', tema: 'sistemas-politicos', dificultad: 3,
    enunciado: '¿Qué se entiende por tiranía de la mayoría?',
    opciones: [
      'Que una mayoría use su poder para anular derechos básicos de un grupo minoritario',
      'Que la mayoría gane todas las elecciones seguidas',
      'Que un gobierno tenga mayoría absoluta en el congreso',
      'Que la mayoría de la población se oponga al gobierno',
    ],
    correcta: 0,
    explicacion: 'Tener los votos no vuelve legítima cualquier decisión. Contar con mayoría en el congreso es normal y necesario para gobernar; usarla para suprimir derechos es lo que describe el término.',
  },

  // ----- Partidos, elecciones y opinión pública -----
  {
    id: 'civ-051', tema: 'partidos-elecciones', dificultad: 1,
    enunciado: '¿Cuál es la función principal de los partidos políticos?',
    opciones: [
      'Organizar corrientes de opinión, presentar candidatos y ofrecer programas de gobierno',
      'Administrar el presupuesto del Estado',
      'Vigilar el conteo oficial de los votos',
      'Redactar las sentencias de los tribunales',
    ],
    correcta: 0,
    explicacion: 'Son los intermediarios entre la sociedad y el Estado: agregan demandas dispersas y las convierten en propuestas y candidaturas. El conteo lo hace la autoridad electoral.',
  },
  {
    id: 'civ-052', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: '¿Qué distingue a un sistema electoral proporcional de uno mayoritario?',
    opciones: [
      'En el proporcional los escaños se reparten según el porcentaje de votos de cada lista',
      'En el proporcional gana quien obtiene más votos y se lleva todo',
      'En el proporcional solo pueden competir dos partidos',
      'En el proporcional el voto no es secreto',
    ],
    correcta: 0,
    explicacion: 'El mayoritario tiende a producir gobiernos de un solo partido y deja sin representación a las minorías; el proporcional refleja mejor la diversidad, pero suele obligar a formar coaliciones.',
  },
  {
    id: 'civ-053', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: 'El umbral electoral es:',
    opciones: [
      'El porcentaje mínimo de votos que necesita una lista para obtener escaños',
      'La edad mínima para votar',
      'El número de firmas para inscribir un partido',
      'El máximo de dinero que puede gastar una campaña',
    ],
    correcta: 0,
    explicacion: 'Busca evitar una fragmentación excesiva del parlamento. Su costo es que los votos de quienes quedan por debajo no se traducen en representación.',
  },
  {
    id: 'civ-054', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: '¿Por qué se regula el financiamiento de las campañas electorales?',
    opciones: [
      'Para evitar que quien aporta dinero compre decisiones públicas después de la elección',
      'Para que todos los candidatos gasten exactamente lo mismo',
      'Para que las campañas sean más cortas',
      'Para impedir que los ciudadanos hagan donaciones',
    ],
    correcta: 0,
    explicacion: 'Los topes, la publicidad de los aportes y la rendición de cuentas buscan cortar el vínculo entre financiación y contratos o favores posteriores.',
  },
  {
    id: 'civ-055', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: 'En un congreso de 100 escaños repartidos de forma estrictamente proporcional, un partido que obtiene el 30 % de los votos consigue aproximadamente:',
    opciones: ['30 escaños', '50 escaños', '15 escaños', '100 escaños'],
    correcta: 0,
    explicacion: 'La proporcionalidad traduce porcentaje de votos en porcentaje de escaños. En la práctica los métodos de reparto y el umbral producen pequeñas diferencias.',
  },
  {
    id: 'civ-056', tema: 'partidos-elecciones', dificultad: 3,
    enunciado: 'Una encuesta da 42 % a un candidato y 39 % a otro, con un margen de error de ±3 puntos. ¿Qué se puede concluir?',
    opciones: [
      'Que están en empate técnico: la diferencia cabe dentro del margen de error',
      'Que el primero ganará con seguridad',
      'Que la encuesta está mal hecha',
      'Que el segundo remontará en los próximos días',
    ],
    correcta: 0,
    explicacion: 'Con ese margen, el primero podría estar entre 39 y 45 y el segundo entre 36 y 42: los rangos se superponen. Leer una encuesta sin mirar el margen de error es el error más común al informar sobre ellas.',
    pista: 'Súmale y réstale el margen a cada cifra y mira si los rangos se tocan.',
  },
  {
    id: 'civ-057', tema: 'partidos-elecciones', dificultad: 3,
    enunciado: '¿Por qué la forma de trazar los distritos electorales puede cambiar el resultado de una elección?',
    opciones: [
      'Porque agrupando a los votantes de cierta manera se puede desperdiciar o concentrar su voto',
      'Porque en distritos grandes la gente vota más',
      'Porque los distritos determinan quién puede ser candidato',
      'Porque cada distrito usa un sistema de conteo distinto',
    ],
    correcta: 0,
    explicacion: 'Se conoce como gerrymandering: con los mismos votos totales, un trazado puede dar la mayoría a un partido y otro trazado a su rival. Por eso la delimitación suele encargarse a órganos independientes.',
  },
  {
    id: 'civ-058', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: 'Cuando se dice que los medios de comunicación fijan la agenda pública, se quiere decir que:',
    opciones: [
      'Influyen menos en lo que la gente piensa que en los temas sobre los que la gente piensa',
      'Deciden directamente el resultado de las elecciones',
      'Obligan a los gobiernos a cambiar sus políticas',
      'Solo publican lo que los partidos les ordenan',
    ],
    correcta: 0,
    explicacion: 'Es la hipótesis clásica de la agenda setting: al destacar unos temas y omitir otros, los medios definen cuáles son los asuntos que se discuten.',
  },
  {
    id: 'civ-059', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre voto en blanco y voto nulo?',
    opciones: [
      'El voto en blanco es una opción válida que expresa rechazo a las candidaturas; el nulo es un voto mal marcado o anulado',
      'Son lo mismo y se cuentan juntos',
      'El voto en blanco se anula y el nulo se cuenta',
      'El voto en blanco solo existe en las elecciones presidenciales',
    ],
    correcta: 0,
    explicacion: 'En varios países el voto en blanco tiene efectos jurídicos si supera cierto umbral. El nulo, en cambio, no expresa una preferencia: simplemente no se puede contabilizar.',
  },
  {
    id: 'civ-060', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: 'La observación electoral, nacional o internacional, sirve para:',
    opciones: [
      'Verificar de forma independiente que el proceso se desarrolle conforme a las reglas',
      'Decidir quién es el ganador cuando el resultado es estrecho',
      'Sustituir a la autoridad electoral del país',
      'Elegir a los jurados de votación',
    ],
    correcta: 0,
    explicacion: 'Los observadores no organizan ni deciden nada: documentan y reportan. Su valor está justamente en ser externos al proceso.',
  },

  // ----- Estado, economía y políticas públicas -----
  {
    id: 'civ-061', tema: 'economia-politica', dificultad: 1,
    enunciado: '¿Para qué sirven principalmente los impuestos?',
    opciones: [
      'Para financiar bienes y servicios públicos como salud, educación, seguridad e infraestructura',
      'Para pagar los sueldos de los partidos políticos',
      'Para controlar cuánto dinero gasta cada familia',
      'Para reducir el número de empresas en el país',
    ],
    correcta: 0,
    explicacion: 'Además de financiar, los impuestos sirven para redistribuir ingreso y para desincentivar consumos dañinos, como los que gravan el tabaco.',
  },
  {
    id: 'civ-062', tema: 'economia-politica', dificultad: 2,
    enunciado: 'Un impuesto es progresivo cuando:',
    opciones: [
      'Quien tiene más ingresos paga una proporción mayor de ellos',
      'Aumenta un poco cada año',
      'Todos pagan exactamente la misma cantidad',
      'Se cobra solo a las empresas',
    ],
    correcta: 0,
    explicacion: 'El impuesto sobre la renta suele ser progresivo por tramos. El IVA tiende a ser regresivo: como todos pagan la misma tasa, pesa proporcionalmente más en el bolsillo de quien menos gana.',
  },
  {
    id: 'civ-063', tema: 'economia-politica', dificultad: 2,
    enunciado: 'El presupuesto público de un país es:',
    opciones: [
      'El plan anual de ingresos y gastos del Estado, aprobado por el congreso',
      'La cantidad de dinero que tiene el banco central',
      'El total de impuestos recaudados en la historia del país',
      'La deuda que el país tiene con otros Estados',
    ],
    correcta: 0,
    explicacion: 'Es la ley más política del año: ahí se ve en qué se traducen realmente las prioridades de un gobierno, más allá de sus discursos.',
  },
  {
    id: 'civ-064', tema: 'economia-politica', dificultad: 2,
    enunciado: 'Hay déficit fiscal cuando el Estado:',
    opciones: [
      'Gasta más de lo que ingresa y debe financiar la diferencia con deuda',
      'Recauda más impuestos de los previstos',
      'Reduce el gasto por debajo de lo presupuestado',
      'Exporta menos de lo que importa',
    ],
    correcta: 0,
    explicacion: 'Un déficit puntual puede ser razonable para sostener la economía en una crisis; sostenido en el tiempo obliga a pagar cada vez más intereses y deja menos dinero para lo demás. Exportar menos de lo que se importa es déficit comercial, otra cosa.',
  },
  {
    id: 'civ-065', tema: 'economia-politica', dificultad: 1,
    enunciado: 'La inflación es:',
    opciones: [
      'El aumento general y sostenido de los precios, que reduce el poder adquisitivo del dinero',
      'La subida del precio de un producto concreto',
      'El aumento de los impuestos',
      'La caída del valor de las exportaciones',
    ],
    correcta: 0,
    explicacion: 'Lo clave es que sea general y sostenido: que suba el tomate una semana no es inflación. Con inflación, el mismo billete compra menos cosas cada mes.',
  },
  {
    id: 'civ-066', tema: 'economia-politica', dificultad: 3,
    enunciado: 'Un trabajador recibe un aumento salarial del 5 % en un año en el que la inflación fue del 8 %. ¿Qué pasó con su capacidad de compra?',
    opciones: [
      'Cayó alrededor de un 3 %, porque los precios subieron más que su salario',
      'Subió un 5 %, porque su salario aumentó',
      'Subió un 3 %, porque la diferencia lo favorece',
      'No cambió, porque el salario y los precios se compensan',
    ],
    correcta: 0,
    explicacion: 'El aumento nominal es 5 %, pero el real es aproximadamente 5 − 8 = −3 %. Distinguir cifras nominales de reales es la clave para leer cualquier noticia económica.',
  },
  {
    id: 'civ-067', tema: 'economia-politica', dificultad: 3,
    enunciado: '¿Cuál de estos es un bien público en sentido económico?',
    opciones: [
      'El alumbrado de una calle',
      'Una entrada de cine',
      'Un almuerzo en un restaurante',
      'Una camiseta comprada en una tienda',
    ],
    correcta: 0,
    explicacion: 'Un bien público no es rival (que yo lo use no impide que tú lo uses) ni excluyente (no se puede impedir el acceso). Por eso el mercado no lo provee bien y suele financiarse con impuestos.',
  },
  {
    id: 'civ-068', tema: 'economia-politica', dificultad: 2,
    enunciado: '¿Qué diferencia a un subsidio focalizado de uno universal?',
    opciones: [
      'El focalizado se dirige solo a quienes cumplen ciertos criterios; el universal llega a toda la población',
      'El focalizado lo paga el sector privado',
      'El universal es siempre más barato para el Estado',
      'El focalizado solo se aplica en zonas rurales',
    ],
    correcta: 0,
    explicacion: 'Focalizar concentra el gasto donde más falta hace, pero exige identificar bien a los beneficiarios y deja fuera a quienes no aparecen en los registros. El universal es más simple y más caro.',
  },
  {
    id: 'civ-069', tema: 'economia-politica', dificultad: 3,
    enunciado: '¿Por qué la evasión de impuestos perjudica también a quienes sí los pagan?',
    opciones: [
      'Porque hay menos recursos para los servicios públicos y la carga recae sobre menos contribuyentes',
      'Porque obliga al banco central a emitir moneda',
      'Porque hace subir el precio de las exportaciones',
      'Porque reduce la población económicamente activa',
    ],
    correcta: 0,
    explicacion: 'Con menos recaudación hay dos salidas, y las dos duelen: recortar servicios o subir la carga sobre quienes ya cumplen. Además pone en desventaja competitiva a las empresas que declaran todo.',
  },
  {
    id: 'civ-070', tema: 'economia-politica', dificultad: 2,
    enunciado: 'La función principal de un banco central suele ser:',
    opciones: [
      'Velar por la estabilidad de los precios controlando la inflación',
      'Recaudar los impuestos del país',
      'Aprobar el presupuesto nacional',
      'Fijar los salarios de los trabajadores',
    ],
    correcta: 0,
    explicacion: 'Lo hace sobre todo con la tasa de interés y el manejo de la cantidad de dinero. Suele ser independiente del gobierno, precisamente para que no se emita dinero por conveniencia política.',
  },

  // ----- Convivencia y resolución de conflictos -----
  {
    id: 'civ-071', tema: 'convivencia', dificultad: 2,
    enunciado: 'Desde el punto de vista de la convivencia, un conflicto es:',
    opciones: [
      'Una diferencia de intereses o necesidades, que no equivale a violencia',
      'Siempre un hecho negativo que hay que evitar',
      'Lo mismo que una agresión física',
      'Un problema que solo puede resolver una autoridad',
    ],
    correcta: 0,
    explicacion: 'El conflicto es inevitable y hasta útil: señala que algo hay que negociar. La violencia es una de las formas —la peor— de tramitarlo.',
  },
  {
    id: 'civ-072', tema: 'convivencia', dificultad: 2,
    enunciado: '¿Qué caracteriza a la mediación frente al arbitraje?',
    opciones: [
      'El mediador ayuda a que las partes construyan su propio acuerdo, sin imponer una solución',
      'El mediador dicta una decisión obligatoria',
      'La mediación solo se usa en procesos penales',
      'En la mediación no pueden participar abogados',
    ],
    correcta: 0,
    explicacion: 'En el arbitraje un tercero decide y su laudo obliga. En la mediación y la conciliación el acuerdo lo construyen las partes, lo que suele hacerlo más duradero.',
  },
  {
    id: 'civ-073', tema: 'convivencia', dificultad: 2,
    enunciado: 'Hay discriminación cuando:',
    opciones: [
      'Se da un trato desfavorable a alguien por una característica como su origen, sexo, religión o discapacidad',
      'Se trata de forma distinta a personas en situaciones distintas con una razón objetiva',
      'Alguien recibe una nota más baja en un examen',
      'Una empresa contrata a quien tiene mejor desempeño',
    ],
    correcta: 0,
    explicacion: 'La clave es que el criterio del trato sea irrelevante para el asunto. Evaluar el desempeño es una distinción legítima; usar el apellido o el color de piel no lo es.',
  },
  {
    id: 'civ-074', tema: 'convivencia', dificultad: 2,
    enunciado: '¿Qué tres rasgos distinguen el acoso escolar de una pelea aislada?',
    opciones: [
      'Es intencional, se repite en el tiempo y hay desequilibrio de poder entre las partes',
      'Ocurre fuera del colegio, es anónimo y no deja huellas',
      'Involucra a más de dos personas, es público y lo sanciona la ley penal',
      'Es físico, deja lesiones visibles y ocurre en el recreo',
    ],
    correcta: 0,
    explicacion: 'Sin repetición y sin asimetría de poder hay conflicto, no acoso. Por eso las respuestas efectivas trabajan sobre el grupo entero y no solo sobre los dos implicados.',
  },
  {
    id: 'civ-075', tema: 'convivencia', dificultad: 2,
    enunciado: 'Ante una situación de acoso, ¿cuál es el papel más útil de quien la presencia?',
    opciones: [
      'Dejar de ser espectador pasivo: apoyar a quien lo sufre y reportarlo a un adulto responsable',
      'No intervenir para no empeorar la situación',
      'Responder con la misma agresión hacia el agresor',
      'Esperar a que la víctima lo denuncie sola',
    ],
    correcta: 0,
    explicacion: 'El silencio del grupo es lo que sostiene el acoso: le da audiencia al agresor y deja sola a la víctima. Los programas que funcionan se dirigen justamente a los espectadores.',
  },
  {
    id: 'civ-076', tema: 'convivencia', dificultad: 3,
    enunciado: 'Una respuesta asertiva ante un desacuerdo consiste en:',
    opciones: [
      'Expresar la propia posición con claridad y sin agredir, reconociendo la del otro',
      'Ceder para evitar el enfrentamiento',
      'Imponer el punto de vista propio con firmeza',
      'Guardar silencio y retirarse de la conversación',
    ],
    correcta: 0,
    explicacion: 'La asertividad está entre la pasividad (ceder siempre) y la agresividad (imponerse). Es decir lo que se piensa sin pisar al otro.',
  },
  {
    id: 'civ-077', tema: 'convivencia', dificultad: 2,
    enunciado: 'Las normas de convivencia de una institución se justifican principalmente porque:',
    opciones: [
      'Hacen previsible el comportamiento y protegen los derechos de todos los miembros',
      'Permiten castigar a quienes piensan distinto',
      'Sustituyen a las leyes del país dentro de la institución',
      'Evitan que existan conflictos',
    ],
    correcta: 0,
    explicacion: 'Un reglamento no elimina los conflictos: establece un procedimiento conocido para resolverlos. Y nunca puede contradecir la ley ni los derechos fundamentales.',
  },
  {
    id: 'civ-078', tema: 'convivencia', dificultad: 3,
    enunciado: '¿En qué se diferencia la justicia restaurativa de la puramente punitiva?',
    opciones: [
      'La restaurativa busca reparar el daño y reintegrar, además de establecer responsabilidad',
      'La restaurativa deja el delito sin consecuencias',
      'La punitiva se aplica solo a menores de edad',
      'La restaurativa la aplica la víctima por su cuenta',
    ],
    correcta: 0,
    explicacion: 'No es impunidad: hay reconocimiento de responsabilidad y reparación a la víctima. La diferencia está en el objetivo, que no se agota en el castigo.',
  },
  {
    id: 'civ-079', tema: 'convivencia', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre estereotipo y prejuicio?',
    opciones: [
      'El estereotipo es una creencia generalizada sobre un grupo; el prejuicio es la valoración negativa que se le asocia',
      'El estereotipo es negativo y el prejuicio positivo',
      'El estereotipo es individual y el prejuicio colectivo',
      'Son términos equivalentes',
    ],
    correcta: 0,
    explicacion: 'Del estereotipo (creencia) al prejuicio (actitud) y de ahí a la discriminación (conducta). Reconocer la cadena ayuda a cortarla antes del último paso.',
  },
  {
    id: 'civ-080', tema: 'convivencia', dificultad: 2,
    enunciado: 'La interculturalidad va más allá de la simple multiculturalidad porque:',
    opciones: [
      'No se limita a que convivan varias culturas: propone intercambio y relación en condiciones de igualdad',
      'Exige que todos adopten la cultura mayoritaria',
      'Implica que cada cultura viva separada de las demás',
      'Se refiere únicamente a la enseñanza de idiomas',
    ],
    correcta: 0,
    explicacion: 'Multicultural describe un hecho: hay varias culturas en el mismo territorio. Intercultural propone una relación, y eso incluye discutir las desigualdades entre ellas.',
  },

  // ----- Organismos internacionales -----
  {
    id: 'civ-081', tema: 'organismos', dificultad: 1,
    enunciado: 'El órgano de la ONU en el que están representados todos los Estados miembros con un voto cada uno es:',
    opciones: ['La Asamblea General', 'El Consejo de Seguridad', 'La Corte Internacional de Justicia', 'La Secretaría General'],
    correcta: 0,
    explicacion: 'La Asamblea General es el foro plenario. El Consejo de Seguridad tiene 15 miembros, de los cuales 5 son permanentes.',
  },
  {
    id: 'civ-082', tema: 'organismos', dificultad: 2,
    enunciado: 'El derecho de veto en el Consejo de Seguridad de la ONU permite que:',
    opciones: [
      'Cualquiera de los cinco miembros permanentes bloquee por sí solo una resolución',
      'La Asamblea General anule una decisión del Consejo',
      'El secretario general suspenda a un país miembro',
      'Un país sea expulsado de la organización',
    ],
    correcta: 0,
    explicacion: 'Es la crítica más frecuente al diseño de la ONU: cuando el conflicto involucra a un miembro permanente o a sus aliados, el Consejo suele quedar paralizado.',
  },
  {
    id: 'civ-083', tema: 'organismos', dificultad: 1,
    enunciado: 'La UNESCO es el organismo de la ONU especializado en:',
    opciones: ['Educación, ciencia y cultura', 'Salud pública mundial', 'Comercio internacional', 'Ayuda humanitaria en desastres'],
    correcta: 0,
    explicacion: 'Entre otras cosas administra la lista de Patrimonio de la Humanidad. La salud le corresponde a la OMS.',
  },
  {
    id: 'civ-084', tema: 'organismos', dificultad: 1,
    enunciado: 'La Organización Mundial de la Salud (OMS) se encarga de:',
    opciones: [
      'Coordinar la respuesta internacional en materia de salud y emitir recomendaciones sanitarias',
      'Financiar la construcción de hospitales en todos los países',
      'Autorizar la venta de medicamentos en cada país',
      'Administrar los sistemas de salud nacionales',
    ],
    correcta: 0,
    explicacion: 'Coordina, vigila y recomienda, pero la autorización de medicamentos y la gestión de los hospitales siguen siendo competencia de cada Estado.',
  },
  {
    id: 'civ-085', tema: 'organismos', dificultad: 2,
    enunciado: 'La Organización de Estados Americanos (OEA) es un foro:',
    opciones: [
      'Regional del continente americano para la cooperación política y la defensa de la democracia',
      'Mundial para la regulación del comercio',
      'Militar del Atlántico Norte',
      'Financiero para otorgar créditos a los países pobres',
    ],
    correcta: 0,
    explicacion: 'A ella está vinculado el sistema interamericano de derechos humanos, con la Comisión y la Corte Interamericana.',
  },
  {
    id: 'civ-086', tema: 'organismos', dificultad: 2,
    enunciado: 'La Corte Penal Internacional juzga a:',
    opciones: [
      'Personas acusadas de genocidio, crímenes de guerra y crímenes de lesa humanidad',
      'Estados que incumplen tratados comerciales',
      'Empresas que contaminan el medio ambiente',
      'Gobiernos que no pagan su deuda externa',
    ],
    correcta: 0,
    explicacion: 'Juzga individuos, no Estados, y actúa de forma complementaria: solo interviene cuando el país no puede o no quiere investigar. Los litigios entre Estados van a la Corte Internacional de Justicia.',
  },
  {
    id: 'civ-087', tema: 'organismos', dificultad: 3,
    enunciado: 'El derecho internacional humanitario se aplica:',
    opciones: [
      'Durante los conflictos armados, para proteger a la población civil y a quienes ya no combaten',
      'Solo en tiempos de paz, para proteger a los refugiados',
      'Únicamente en las guerras entre dos Estados',
      'Para sancionar a los países que declaran la guerra',
    ],
    correcta: 0,
    explicacion: 'No discute si la guerra es justa: regula cómo se combate. Protege a civiles, heridos y prisioneros, y se aplica también en conflictos internos.',
  },
  {
    id: 'civ-088', tema: 'organismos', dificultad: 2,
    enunciado: 'Un tratado internacional se vuelve obligatorio para un país cuando:',
    opciones: [
      'Ese país lo ratifica conforme a su procedimiento interno',
      'Lo firma el ministro de relaciones exteriores en la ceremonia',
      'La mayoría de los países del mundo lo aprueba',
      'La ONU lo aprueba en la Asamblea General',
    ],
    correcta: 0,
    explicacion: 'Firmar expresa la intención; ratificar —normalmente con aprobación del congreso— es lo que obliga. Por eso hay tratados firmados por muchos países y ratificados por pocos.',
  },
  {
    id: 'civ-089', tema: 'organismos', dificultad: 2,
    enunciado: '¿Cuál es la diferencia jurídica entre un refugiado y un migrante económico?',
    opciones: [
      'El refugiado huye de persecución o conflicto y tiene derecho a protección internacional',
      'El refugiado siempre cruza una frontera y el migrante no',
      'El migrante económico no puede ser devuelto a su país',
      'No hay diferencia: los dos términos son intercambiables',
    ],
    correcta: 0,
    explicacion: 'De ahí el principio de no devolución: a un refugiado no se le puede regresar a donde su vida corre peligro. Los desplazados internos también huyen, pero sin cruzar una frontera.',
  },
  {
    id: 'civ-090', tema: 'organismos', dificultad: 3,
    enunciado: '¿Por qué muchas resoluciones de organismos internacionales no llegan a cumplirse?',
    opciones: [
      'Porque su aplicación depende de la voluntad de Estados soberanos y no hay un poder coercitivo por encima de ellos',
      'Porque se redactan en idiomas que pocos países entienden',
      'Porque los organismos no tienen presupuesto',
      'Porque no se publican oficialmente',
    ],
    correcta: 0,
    explicacion: 'Esa es la diferencia estructural con el derecho interno: no existe una policía mundial. Lo que hay son sanciones, presión diplomática y costo reputacional.',
  },

  // ----- Ética pública, corrupción y transparencia -----
  {
    id: 'civ-091', tema: 'etica-publica', dificultad: 1,
    enunciado: 'La corrupción se define como:',
    opciones: [
      'El uso de un cargo o recurso público para obtener un beneficio privado',
      'Cualquier error cometido por un funcionario',
      'La lentitud de los trámites en una entidad pública',
      'El desacuerdo entre dos autoridades sobre una decisión',
    ],
    correcta: 0,
    explicacion: 'La clave es el desvío del interés público hacia el privado, con o sin dinero de por medio: también lo es nombrar a un familiar sin concurso.',
  },
  {
    id: 'civ-092', tema: 'etica-publica', dificultad: 2,
    enunciado: 'Hay conflicto de interés cuando un funcionario:',
    opciones: [
      'Debe decidir sobre un asunto en el que tiene un interés personal, familiar o económico',
      'No está de acuerdo con la política de su superior',
      'Trabaja en dos entidades públicas a la vez',
      'Recibe críticas de la prensa por una decisión',
    ],
    correcta: 0,
    explicacion: 'No hace falta que la decisión sea indebida: la sola situación obliga a declararla y a apartarse. Por eso existen los impedimentos y las recusaciones.',
  },
  {
    id: 'civ-093', tema: 'etica-publica', dificultad: 2,
    enunciado: 'El derecho de acceso a la información pública implica que:',
    opciones: [
      'Cualquier persona puede solicitar información del Estado sin tener que justificar para qué la quiere',
      'Solo los periodistas pueden pedir documentos oficiales',
      'Toda la información del Estado es pública sin excepción',
      'La información se entrega únicamente a quien demuestre un interés legítimo',
    ],
    correcta: 0,
    explicacion: 'La regla es la publicidad y la excepción, la reserva, que debe estar prevista en la ley y motivarse. No hay que explicar por qué se pide: la información es de todos.',
  },
  {
    id: 'civ-094', tema: 'etica-publica', dificultad: 2,
    enunciado: 'La rendición de cuentas consiste en que:',
    opciones: [
      'Quien ejerce un cargo público explica públicamente qué hizo con los recursos y responde por ello',
      'El Estado publica su presupuesto una vez al año',
      'Los ciudadanos pagan impuestos puntualmente',
      'Los funcionarios entregan su declaración de renta',
    ],
    correcta: 0,
    explicacion: 'Tiene dos partes que suelen olvidarse juntas: informar y responder por lo informado. Publicar datos sin consecuencias no es rendición de cuentas.',
  },
  {
    id: 'civ-095', tema: 'etica-publica', dificultad: 2,
    enunciado: '¿Por qué las compras del Estado suelen hacerse mediante licitación pública?',
    opciones: [
      'Para que varios oferentes compitan en condiciones conocidas y se elija la mejor propuesta',
      'Para que el proceso dure más y se revise mejor',
      'Para que solo participen empresas grandes',
      'Porque lo exige el banco central',
    ],
    correcta: 0,
    explicacion: 'La competencia abierta y las reglas publicadas de antemano son la principal defensa contra el contrato a la medida de un amigo.',
  },
  {
    id: 'civ-096', tema: 'etica-publica', dificultad: 3,
    enunciado: '¿Por qué la corrupción encarece las obras públicas incluso cuando la obra llega a terminarse?',
    opciones: [
      'Porque el sobrecosto se traslada al presupuesto y se elige al contratista por el soborno y no por su capacidad',
      'Porque las obras corruptas siempre se hacen dos veces',
      'Porque los materiales suben de precio durante la investigación',
      'Porque obliga al Estado a contratar más ingenieros',
    ],
    correcta: 0,
    explicacion: 'Hay dos costos: el dinero de más y el peor ejecutor. Por eso las obras con corrupción tienden además a durar menos y a fallar antes.',
  },
  {
    id: 'civ-097', tema: 'etica-publica', dificultad: 2,
    enunciado: 'Una veeduría ciudadana es:',
    opciones: [
      'Un grupo de ciudadanos organizado para vigilar la gestión pública y el uso de los recursos',
      'Un órgano de control creado por el gobierno',
      'Un tribunal que sanciona a los funcionarios',
      'Una comisión del congreso',
    ],
    correcta: 0,
    explicacion: 'Es control social: no sanciona, pero puede pedir información, hacer seguimiento y denunciar ante los órganos que sí sancionan.',
  },
  {
    id: 'civ-098', tema: 'etica-publica', dificultad: 2,
    enunciado: 'El clientelismo político consiste en:',
    opciones: [
      'Intercambiar apoyo electoral por favores, puestos o beneficios particulares',
      'Hacer campaña puerta a puerta',
      'Financiar una campaña con aportes de simpatizantes',
      'Atender a los ciudadanos en las oficinas del gobierno',
    ],
    correcta: 0,
    explicacion: 'Convierte un derecho en una mercancía: el voto deja de expresar una preferencia y pasa a pagar un favor. Corroe la representación aunque las elecciones sean formalmente limpias.',
  },
  {
    id: 'civ-099', tema: 'etica-publica', dificultad: 3,
    enunciado: '¿Por qué muchas legislaciones protegen a quien denuncia hechos de corrupción dentro de una entidad?',
    opciones: [
      'Porque sin protección frente a represalias casi nadie denunciaría lo que ocurre puertas adentro',
      'Porque el denunciante tiene derecho a quedarse con parte del dinero recuperado',
      'Porque la denuncia lo convierte automáticamente en testigo protegido de por vida',
      'Porque así se evita que la prensa publique el caso',
    ],
    correcta: 0,
    explicacion: 'Quien está dentro es quien ve el hecho, y también quien más arriesga: el empleo, el ascenso, la reputación. Sin garantías, la información nunca sale.',
  },
  {
    id: 'civ-100', tema: 'etica-publica', dificultad: 3,
    enunciado: 'Un funcionario acepta un regalo costoso de un contratista. La ley no lo prohíbe expresamente. ¿Cómo se evalúa éticamente?',
    opciones: [
      'Es cuestionable: aunque sea legal, compromete su imparcialidad y la confianza pública',
      'Es correcto, porque lo que no está prohibido está permitido',
      'Es correcto si lo declara después de recibirlo',
      'Solo sería incorrecto si el contratista pidiera algo a cambio por escrito',
    ],
    correcta: 0,
    explicacion: 'Lo legal y lo ético no coinciden siempre, y la ética pública exige el estándar más alto: no basta con no delinquir, hay que no comprometer la imparcialidad ni su apariencia.',
  },
];
