/**
 * ciudadania.js — Banco de política y ciudadanía.
 *
 * Es el área que el Saber 11 llama "sociales y ciudadanas" y el EXANI-II ubica
 * en ciencias sociales: cómo está organizado el Estado, qué dice la
 * Constitución, qué derechos hay y cómo se ejercen, cómo funcionan las
 * elecciones y de dónde sale el dinero público.
 *
 * Dos reglas al escribirlo: nada de nombres de gobernantes ni de cifras que
 * caducan, y nada de tomar partido. Se pregunta cómo funcionan las reglas, no
 * quién tiene razón. Cuando una figura cambia de nombre según el país (tutela,
 * amparo), se dicen los dos.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const CIUDADANIA = [
  // ----- El Estado y las ramas del poder -----
  {
    id: 'civ-001', tema: 'estado-poderes', dificultad: 1,
    enunciado: '¿Cuáles son las tres ramas clásicas del poder público?',
    opciones: [
      'Ejecutiva, legislativa y judicial',
      'Nacional, departamental y municipal',
      'Civil, militar y religiosa',
      'Política, económica y social',
    ],
    correcta: 0,
    explicacion: 'Es la separación de poderes que formuló Montesquieu: quien hace las leyes no es quien las ejecuta ni quien las aplica en un juicio. Lo nacional, departamental y municipal son niveles de gobierno, no ramas.',
  },
  {
    id: 'civ-002', tema: 'estado-poderes', dificultad: 1,
    enunciado: '¿Cuál es la función principal del poder legislativo?',
    opciones: [
      'Hacer, reformar y derogar las leyes',
      'Administrar el presupuesto del Estado día a día',
      'Juzgar a quienes incumplen las leyes',
      'Nombrar a los jueces de todo el país',
    ],
    correcta: 0,
    explicacion: 'El congreso o parlamento legisla y además controla políticamente al gobierno. Administrar es tarea del ejecutivo y juzgar, del judicial.',
  },
  {
    id: 'civ-003', tema: 'estado-poderes', dificultad: 1,
    enunciado: 'Aplicar la ley a un caso concreto y resolver el conflicto entre dos partes le corresponde a:',
    opciones: ['El poder judicial', 'El poder legislativo', 'El poder ejecutivo', 'La policía'],
    correcta: 0,
    explicacion: 'Los jueces interpretan la ley y deciden el caso. La policía ejecuta las decisiones y pertenece al ejecutivo, pero no juzga.',
  },
  {
    id: 'civ-004', tema: 'estado-poderes', dificultad: 2,
    enunciado: '¿Para qué sirve la separación de poderes?',
    opciones: [
      'Para que ningún órgano concentre todo el poder y cada uno controle a los otros',
      'Para que el gobierno pueda tomar decisiones más rápido',
      'Para repartir el territorio entre distintas autoridades',
      'Para que cada rama se ocupe de una región del país',
    ],
    correcta: 0,
    explicacion: 'La idea es de frenos y contrapesos: el poder limita al poder. Suele hacer las decisiones más lentas, y eso es parte del diseño, no un defecto.',
  },
  {
    id: 'civ-005', tema: 'estado-poderes', dificultad: 2,
    enunciado: '¿Cuál de estas es una forma de control del legislativo sobre el ejecutivo?',
    opciones: [
      'Aprobar o rechazar el presupuesto que presenta el gobierno',
      'Nombrar a los alcaldes de las ciudades',
      'Declarar inconstitucional una ley',
      'Dictar sentencia en un juicio penal',
    ],
    correcta: 0,
    explicacion: 'El control del presupuesto y la citación de ministros son las herramientas típicas del congreso. Declarar inconstitucional una ley le corresponde al tribunal o corte constitucional.',
  },
  {
    id: 'civ-006', tema: 'estado-poderes', dificultad: 2,
    enunciado: 'El presidente objeta (veta) una ley aprobada por el congreso. ¿Qué suele ocurrir después?',
    opciones: [
      'El congreso puede insistir y aprobarla de nuevo, normalmente con una mayoría más alta',
      'La ley queda eliminada de forma definitiva',
      'La ley entra en vigor igualmente sin cambios',
      'La ley pasa a votación popular obligatoria',
    ],
    correcta: 0,
    explicacion: 'El veto es un freno, no un poder absoluto: si el legislativo insiste con la mayoría exigida, la ley sigue adelante. Otra vez, frenos y contrapesos.',
  },
  {
    id: 'civ-007', tema: 'estado-poderes', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre Estado y gobierno?',
    opciones: [
      'El Estado es la organización permanente; el gobierno es transitorio y se renueva con las elecciones',
      'Son sinónimos usados en contextos distintos',
      'El Estado es el territorio y el gobierno es la población',
      'El Estado es local y el gobierno es nacional',
    ],
    correcta: 0,
    explicacion: 'Cambian los gobiernos y el Estado permanece con su territorio, su población, sus instituciones y sus compromisos. Por eso las deudas y los tratados siguen vigentes tras un cambio de gobierno.',
  },
  {
    id: 'civ-008', tema: 'estado-poderes', dificultad: 2,
    enunciado: 'La descentralización consiste en:',
    opciones: [
      'Transferir competencias y recursos del gobierno nacional a los gobiernos locales',
      'Trasladar la capital del país a otra ciudad',
      'Eliminar los niveles intermedios de gobierno',
      'Privatizar los servicios públicos',
    ],
    correcta: 0,
    explicacion: 'La idea es que decida quien está más cerca del problema. Su riesgo es que si se transfieren funciones sin recursos ni capacidad técnica, el servicio empeora.',
  },
  {
    id: 'civ-009', tema: 'estado-poderes', dificultad: 2,
    enunciado: '¿Cuál de estas funciones corresponde al poder ejecutivo?',
    opciones: [
      'Dirigir la administración pública y hacer cumplir las leyes',
      'Aprobar el código penal',
      'Resolver una demanda entre dos empresas',
      'Reformar la Constitución por su cuenta',
    ],
    correcta: 0,
    explicacion: 'El ejecutivo gobierna y administra: ministerios, fuerza pública, servicios y política exterior. Legislar y juzgar son de las otras dos ramas.',
  },
  {
    id: 'civ-010', tema: 'estado-poderes', dificultad: 3,
    enunciado: 'Un tribunal declara inconstitucional una ley que el congreso aprobó y el presidente sancionó. ¿Qué principio se está aplicando?',
    opciones: [
      'El control constitucional, una forma de freno entre poderes',
      'La soberanía popular, porque el pueblo eligió a los jueces',
      'La jerarquía militar del Estado',
      'La autonomía de los gobiernos locales',
    ],
    correcta: 0,
    explicacion: 'Que dos poderes estén de acuerdo no basta si la norma contradice la Constitución. Ese control es lo que impide que una mayoría del momento cambie las reglas básicas por la puerta de atrás.',
    pista: 'Fíjate en quién vigila a quién.',
  },

  // ----- Constitución y jerarquía de las normas -----
  {
    id: 'civ-011', tema: 'constitucion', dificultad: 1,
    enunciado: '¿Qué es la Constitución de un país?',
    opciones: [
      'La norma suprema que organiza el Estado y reconoce los derechos de las personas',
      'El conjunto de leyes aprobadas por el congreso cada año',
      'El programa de gobierno del presidente electo',
      'El reglamento interno de los tribunales',
    ],
    correcta: 0,
    explicacion: 'Por eso se le llama carta magna o ley de leyes: todas las demás normas deben ajustarse a ella.',
  },
  {
    id: 'civ-012', tema: 'constitucion', dificultad: 2,
    enunciado: 'Si una ley contradice la Constitución, ¿qué sucede?',
    opciones: [
      'Prevalece la Constitución y la ley puede ser declarada inconstitucional',
      'Prevalece la ley, porque es más reciente',
      'Las dos se aplican a la vez y decide cada juez',
      'La Constitución se reforma automáticamente',
    ],
    correcta: 0,
    explicacion: 'Es el principio de supremacía constitucional. La fecha no importa: una ley nueva no puede sobreponerse a la Constitución.',
  },
  {
    id: 'civ-013', tema: 'constitucion', dificultad: 2,
    enunciado: 'Ordena de mayor a menor jerarquía: decreto del gobierno, Constitución, ley del congreso.',
    opciones: [
      'Constitución, ley, decreto',
      'Ley, Constitución, decreto',
      'Decreto, ley, Constitución',
      'Todas tienen la misma jerarquía',
    ],
    correcta: 0,
    explicacion: 'Cada norma debe respetar a la superior. Un decreto que contradiga una ley es nulo, igual que una ley que contradiga la Constitución.',
  },
  {
    id: 'civ-014', tema: 'constitucion', dificultad: 2,
    enunciado: '¿Qué significa que un país sea un Estado de derecho?',
    opciones: [
      'Que gobernantes y gobernados están sometidos por igual a la ley',
      'Que el Estado tiene derecho a hacer lo que considere necesario',
      'Que existe una constitución escrita',
      'Que hay elecciones cada cierto número de años',
    ],
    correcta: 0,
    explicacion: 'Lo decisivo es que el poder también tenga límites jurídicos y que haya jueces capaces de hacerlos valer. Tener constitución escrita o elecciones no basta si el poder no responde ante la ley.',
  },
  {
    id: 'civ-015', tema: 'constitucion', dificultad: 2,
    enunciado: 'En una Constitución, la parte dogmática contiene:',
    opciones: [
      'Los derechos, deberes y principios fundamentales',
      'La estructura y las funciones de los órganos del Estado',
      'El procedimiento para reformar la propia Constitución',
      'El presupuesto anual de la nación',
    ],
    correcta: 0,
    explicacion: 'La parte orgánica es la que describe cómo está armado el Estado: ramas, competencias y procedimientos.',
  },
  {
    id: 'civ-016', tema: 'constitucion', dificultad: 3,
    enunciado: '¿Por qué reformar la Constitución suele ser más difícil que aprobar una ley?',
    opciones: [
      'Para dar estabilidad a las reglas básicas y proteger derechos frente a mayorías del momento',
      'Porque el texto constitucional es más largo',
      'Porque solo los jueces pueden proponer reformas',
      'Porque las constituciones no se pueden cambiar nunca',
    ],
    correcta: 0,
    explicacion: 'Se llaman constituciones rígidas: exigen mayorías especiales, varias votaciones o incluso referendo. La idea es que las reglas del juego no cambien con cada gobierno.',
  },
  {
    id: 'civ-017', tema: 'constitucion', dificultad: 2,
    enunciado: 'Un decreto es una norma:',
    opciones: [
      'Expedida por el poder ejecutivo y subordinada a la ley',
      'Aprobada por el congreso en tres debates',
      'Dictada por un juez para resolver un caso',
      'Votada directamente por los ciudadanos',
    ],
    correcta: 0,
    explicacion: 'Sirve para reglamentar y ejecutar lo que la ley dispone. Si un decreto va más allá de la ley que reglamenta, puede ser anulado.',
  },
  {
    id: 'civ-018', tema: 'constitucion', dificultad: 3,
    enunciado: 'El principio de irretroactividad de la ley significa que:',
    opciones: [
      'La ley rige hacia el futuro y no se aplica a hechos anteriores, salvo cuando favorece al procesado',
      'Una ley no puede ser derogada por otra posterior',
      'Las leyes solo valen mientras dure el gobierno que las aprobó',
      'Ninguna ley puede aplicarse antes de un año desde su publicación',
    ],
    correcta: 0,
    explicacion: 'Nadie puede ser castigado por algo que no era delito cuando lo hizo. La excepción es la ley penal más benigna, que sí se aplica hacia atrás.',
  },
  {
    id: 'civ-019', tema: 'constitucion', dificultad: 2,
    enunciado: 'La regla de que nadie puede ser juzgado dos veces por el mismo hecho se conoce como:',
    opciones: ['Cosa juzgada (non bis in idem)', 'Presunción de inocencia', 'Debido proceso', 'Habeas corpus'],
    correcta: 0,
    explicacion: 'Una vez que hay sentencia en firme, el asunto queda cerrado. Es una garantía frente a la persecución indefinida del Estado.',
  },
  {
    id: 'civ-020', tema: 'constitucion', dificultad: 2,
    enunciado: 'La presunción de inocencia implica que:',
    opciones: [
      'Corresponde a quien acusa probar la culpabilidad, no al acusado probar su inocencia',
      'Nadie puede ser detenido antes de un juicio',
      'El acusado puede negarse a comparecer ante el juez',
      'Los delitos graves no admiten defensa',
    ],
    correcta: 0,
    explicacion: 'La carga de la prueba está en la acusación. Por eso, cuando la prueba es insuficiente, la duda favorece al acusado.',
  },

  // ----- Derechos humanos y mecanismos de protección -----
  {
    id: 'civ-021', tema: 'derechos', dificultad: 1,
    enunciado: 'La Declaración Universal de los Derechos Humanos fue adoptada en 1948 por:',
    opciones: ['La Organización de las Naciones Unidas', 'La Unión Europea', 'La Organización de Estados Americanos', 'La Cruz Roja Internacional'],
    correcta: 0,
    explicacion: 'Se aprobó tras la Segunda Guerra Mundial y es el texto del que derivan la mayoría de los tratados de derechos humanos posteriores.',
  },
  {
    id: 'civ-022', tema: 'derechos', dificultad: 2,
    enunciado: 'Que los derechos humanos sean inalienables significa que:',
    opciones: [
      'Nadie puede renunciar a ellos ni ser despojado de ellos',
      'Solo los tienen los ciudadanos de un país',
      'Se pierden si la persona comete un delito',
      'Solo valen dentro del territorio donde se firmaron',
    ],
    correcta: 0,
    explicacion: 'Son además universales (los tiene toda persona) e indivisibles (no se puede sacrificar uno para cumplir otro). Una condena limita algunos derechos, como la libertad, pero no anula la dignidad ni el resto.',
  },
  {
    id: 'civ-023', tema: 'derechos', dificultad: 2,
    enunciado: 'El derecho a un ambiente sano se clasifica habitualmente como un derecho de:',
    opciones: [
      'Tercera generación, porque es colectivo y afecta a toda la comunidad',
      'Primera generación, junto a las libertades civiles y políticas',
      'Segunda generación, junto a los derechos económicos y sociales',
      'No es un derecho, sino un objetivo de política pública',
    ],
    correcta: 0,
    explicacion: 'Los de primera generación son civiles y políticos (libertad, voto); los de segunda, económicos, sociales y culturales (salud, educación, trabajo); los de tercera son colectivos: ambiente, paz, desarrollo.',
  },
  {
    id: 'civ-024', tema: 'derechos', dificultad: 2,
    enunciado: 'El habeas corpus es un mecanismo que protege:',
    opciones: [
      'La libertad personal frente a una detención ilegal o arbitraria',
      'Los datos personales frente a bases de datos erróneas',
      'El derecho a la educación de los menores',
      'La propiedad privada frente a una expropiación',
    ],
    correcta: 0,
    explicacion: 'Obliga a que una autoridad judicial revise de inmediato si la privación de libertad es legal. Su equivalente para los datos personales es el habeas data.',
  },
  {
    id: 'civ-025', tema: 'derechos', dificultad: 2,
    enunciado: 'La acción de tutela (llamada amparo en varios países) sirve para:',
    opciones: [
      'Proteger de forma rápida un derecho fundamental que está siendo vulnerado',
      'Demandar a una empresa por incumplir un contrato',
      'Solicitar la revisión de una sentencia penal',
      'Pedir una pensión al sistema de seguridad social',
    ],
    correcta: 0,
    explicacion: 'Es un procedimiento breve y sin formalismos, pensado para cuando esperar un proceso ordinario haría inútil la protección.',
  },
  {
    id: 'civ-026', tema: 'derechos', dificultad: 3,
    enunciado: 'El derecho a la igualdad admite que la ley trate distinto a personas en situaciones distintas. Ese trato diferenciado es legítimo cuando:',
    opciones: [
      'Busca corregir una desigualdad real y existe una razón objetiva que lo justifique',
      'Lo aprueba la mayoría de la población',
      'Beneficia al grupo más numeroso del país',
      'Está escrito en cualquier norma vigente',
    ],
    correcta: 0,
    explicacion: 'Es la diferencia entre distinción y discriminación: una rampa de acceso o una cuota de admisión buscan equiparar puntos de partida desiguales. Que una mayoría lo apruebe no hace legítima una distinción arbitraria.',
  },
  {
    id: 'civ-027', tema: 'derechos', dificultad: 3,
    enunciado: 'La libertad de expresión es un derecho fundamental, pero no ampara:',
    opciones: [
      'La incitación a la violencia ni la difamación deliberada',
      'Las críticas duras a un gobernante',
      'Las opiniones que ofenden a una parte de la sociedad',
      'La publicación de información incómoda para el poder',
    ],
    correcta: 0,
    explicacion: 'Los límites son estrechos y deben estar definidos en la ley. Criticar al poder o incomodar con una opinión es justamente lo que el derecho protege; incitar a dañar a alguien, no.',
  },
  {
    id: 'civ-028', tema: 'derechos', dificultad: 2,
    enunciado: 'El habeas data permite a una persona:',
    opciones: [
      'Conocer, actualizar y corregir los datos que existen sobre ella en bases de datos',
      'Acceder gratuitamente a internet',
      'Impedir que la prensa publique noticias sobre ella',
      'Obtener copia de cualquier documento del Estado',
    ],
    correcta: 0,
    explicacion: 'Es clave frente a los registros de deudores o a las bases de datos comerciales. El acceso a documentos públicos se ejerce con el derecho de petición o de acceso a la información.',
  },
  {
    id: 'civ-029', tema: 'derechos', dificultad: 2,
    enunciado: 'El principio del interés superior del niño significa que:',
    opciones: [
      'Ante un conflicto de derechos, prevalece lo que mejor proteja al menor',
      'Los niños tienen más derechos que los adultos en cualquier situación',
      'Los padres deciden siempre lo que es mejor para el menor',
      'Los menores no tienen obligaciones de ningún tipo',
    ],
    correcta: 0,
    explicacion: 'No significa que el niño mande, sino que su bienestar es el criterio que orienta la decisión de jueces, autoridades y familias.',
  },
  {
    id: 'civ-030', tema: 'derechos', dificultad: 3,
    enunciado: 'Se dice que todo derecho implica un deber correlativo. ¿Qué ejemplo lo ilustra mejor?',
    opciones: [
      'Mi derecho a un juicio justo implica el deber del Estado de garantizar un juez imparcial',
      'Mi derecho al voto implica el deber de votar por el mejor candidato',
      'Mi derecho a la salud implica el deber de no enfermarme',
      'Mi derecho a la educación implica el deber de sacar buenas notas',
    ],
    correcta: 0,
    explicacion: 'El deber correlativo recae en quien debe hacer posible el derecho: el Estado o los demás ciudadanos. Las otras opciones confunden el derecho con una obligación personal de resultado.',
  },

  // ----- Democracia y participación -----
  {
    id: 'civ-031', tema: 'democracia', dificultad: 1,
    enunciado: '¿Cuál es la diferencia entre democracia directa y representativa?',
    opciones: [
      'En la directa los ciudadanos deciden por sí mismos; en la representativa eligen a quienes deciden por ellos',
      'La directa se usa en países pequeños y la representativa en grandes',
      'La directa es antigua y la representativa es la única válida hoy',
      'En la directa solo vota una parte de la población',
    ],
    correcta: 0,
    explicacion: 'La mayoría de los sistemas actuales son mixtos: eligen representantes y además conservan mecanismos directos como el referendo.',
  },
  {
    id: 'civ-032', tema: 'democracia', dificultad: 1,
    enunciado: 'El sufragio universal significa que pueden votar:',
    opciones: [
      'Todos los ciudadanos mayores de edad, sin distinción de sexo, origen o riqueza',
      'Únicamente quienes pagan impuestos',
      'Todos los habitantes del país, incluidos los extranjeros en cualquier elección',
      'Solo quienes se inscriben en un partido político',
    ],
    correcta: 0,
    explicacion: 'Se opone al sufragio censitario, que exigía propiedad o renta, y al masculino, que excluía a las mujeres. Ambas restricciones fueron la norma hasta bien entrado el siglo XX.',
  },
  {
    id: 'civ-033', tema: 'democracia', dificultad: 2,
    enunciado: '¿Por qué el voto es secreto?',
    opciones: [
      'Para que nadie pueda presionar, comprar o castigar el voto de otra persona',
      'Para que las autoridades no conozcan los resultados antes de tiempo',
      'Para evitar que se cuenten mal las papeletas',
      'Porque así lo exigen los partidos políticos',
    ],
    correcta: 0,
    explicacion: 'Sin secreto no hay libertad: el jefe, el líder local o el comprador de votos podría verificar el cumplimiento. Es la garantía que hace posible el voto libre.',
  },
  {
    id: 'civ-034', tema: 'democracia', dificultad: 2,
    enunciado: 'Un referendo es un mecanismo mediante el cual:',
    opciones: [
      'Los ciudadanos aprueban o rechazan directamente una norma o decisión',
      'El congreso interpela a un ministro',
      'Un juez revisa la constitucionalidad de una ley',
      'Un partido elige a su candidato',
    ],
    correcta: 0,
    explicacion: 'Junto al plebiscito, la consulta popular y la iniciativa legislativa, es una de las formas de participación directa que conservan las democracias representativas.',
  },
  {
    id: 'civ-035', tema: 'democracia', dificultad: 2,
    enunciado: 'La revocatoria del mandato permite que:',
    opciones: [
      'Los electores den por terminado antes de tiempo el mandato de un gobernante que eligieron',
      'El congreso destituya a un juez',
      'El presidente disuelva el parlamento',
      'Un partido expulse a uno de sus militantes',
    ],
    correcta: 0,
    explicacion: 'Es un control ciudadano posterior a la elección. Suele exigir un número alto de firmas y una participación mínima para que el resultado sea válido.',
  },
  {
    id: 'civ-036', tema: 'democracia', dificultad: 2,
    enunciado: 'La iniciativa popular legislativa consiste en que:',
    opciones: [
      'Un grupo de ciudadanos presenta un proyecto de ley recogiendo firmas',
      'Los ciudadanos eligen directamente a los ministros',
      'Una ley entra en vigor sin pasar por el congreso',
      'El pueblo redacta una nueva constitución cada década',
    ],
    correcta: 0,
    explicacion: 'El proyecto entra al trámite legislativo como cualquier otro: la iniciativa es ciudadana, pero la decisión sigue siendo del congreso.',
  },
  {
    id: 'civ-037', tema: 'democracia', dificultad: 3,
    enunciado: 'Se dice que la democracia no se agota en votar cada cuatro años. ¿Qué ejemplo respalda mejor esa idea?',
    opciones: [
      'Las veedurías ciudadanas, los cabildos abiertos y el derecho de petición',
      'La existencia de varios partidos en el congreso',
      'La publicación de encuestas antes de las elecciones',
      'El conteo rápido de votos la misma noche electoral',
    ],
    correcta: 0,
    explicacion: 'La participación entre elecciones —vigilar el gasto, pedir información, asistir a audiencias— es lo que hace que el mandato se ejerza con control y no en blanco.',
  },
  {
    id: 'civ-038', tema: 'democracia', dificultad: 2,
    enunciado: 'En una democracia, ¿qué ocurre con los derechos de las minorías?',
    opciones: [
      'Se respetan, porque la mayoría no puede decidir sobre los derechos fundamentales de nadie',
      'Se suspenden mientras gobierne la mayoría',
      'Dependen de que la minoría llegue a acuerdos con el gobierno',
      'Solo se protegen si están escritos en una ley ordinaria',
    ],
    correcta: 0,
    explicacion: 'Regla de mayoría para decidir, límites constitucionales para lo que no se puede decidir. Sin ese segundo elemento, la democracia se convierte en el gobierno del más numeroso.',
  },
  {
    id: 'civ-039', tema: 'democracia', dificultad: 3,
    enunciado: 'Una elección se gana con el 52 % de los votos, pero solo participó el 40 % de los habilitados. ¿Qué problema plantea?',
    opciones: [
      'El ganador representa en realidad a una fracción pequeña del electorado, lo que debilita su legitimidad',
      'La elección es jurídicamente nula',
      'El ganador debe repetir la votación al año siguiente',
      'No plantea ningún problema, porque ganó la mayoría',
    ],
    correcta: 0,
    explicacion: 'El 52 % del 40 % es cerca del 21 % del censo. La elección es válida, pero la abstención alta es una señal de desconexión entre las instituciones y la gente.',
    pista: 'Calcula qué porcentaje del total de habilitados lo votó.',
  },
  {
    id: 'civ-040', tema: 'democracia', dificultad: 2,
    enunciado: '¿Cuál de las siguientes es un deber ciudadano y no un derecho?',
    opciones: [
      'Respetar los derechos de los demás y cumplir la ley',
      'Elegir y ser elegido',
      'Recibir educación básica',
      'Asociarse con otras personas',
    ],
    correcta: 0,
    explicacion: 'La ciudadanía es un vínculo de doble vía: derechos y deberes. Los otros tres enunciados son derechos reconocidos en casi todas las constituciones.',
  },

  // ----- Formas de gobierno y sistemas políticos -----
  {
    id: 'civ-041', tema: 'sistemas-politicos', dificultad: 1,
    enunciado: '¿Cuál es la diferencia esencial entre una república y una monarquía?',
    opciones: [
      'En la república la jefatura del Estado es electiva y temporal; en la monarquía es hereditaria y vitalicia',
      'En la república hay elecciones y en la monarquía no las hay nunca',
      'En la república hay separación de poderes y en la monarquía no',
      'La república es moderna y la monarquía ya no existe',
    ],
    correcta: 0,
    explicacion: 'Hay monarquías parlamentarias plenamente democráticas, con elecciones y separación de poderes, donde el rey reina pero no gobierna.',
  },
  {
    id: 'civ-042', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: '¿Qué distingue a un sistema parlamentario de uno presidencialista?',
    opciones: [
      'En el parlamentario el jefe de gobierno surge del parlamento y este puede removerlo',
      'En el parlamentario no existe jefe de Estado',
      'En el presidencialista el presidente no es elegido por los ciudadanos',
      'En el parlamentario no hay partidos políticos',
    ],
    correcta: 0,
    explicacion: 'En el presidencialismo el presidente tiene mandato fijo y legitimidad propia; en el parlamentarismo el gobierno depende de la confianza de la cámara y puede caer con una moción de censura.',
  },
  {
    id: 'civ-043', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: 'Que un Estado sea laico significa que:',
    opciones: [
      'No adopta una religión oficial y garantiza la libertad de culto',
      'Prohíbe la práctica de cualquier religión',
      'Obliga a los ciudadanos a declararse sin religión',
      'Financia por igual a todas las iglesias del país',
    ],
    correcta: 0,
    explicacion: 'La laicidad separa Estado y religión para que nadie sea favorecido ni perjudicado por su creencia. No es lo mismo que el ateísmo de Estado.',
  },
  {
    id: 'civ-044', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: '¿Cuál es un rasgo característico de un régimen autoritario?',
    opciones: [
      'La concentración del poder sin elecciones competitivas ni controles independientes',
      'La existencia de un parlamento con varias cámaras',
      'La celebración de elecciones periódicas de cualquier tipo',
      'La presencia de un jefe de Estado con funciones ceremoniales',
    ],
    correcta: 0,
    explicacion: 'Lo decisivo no es que haya elecciones, sino que sean competitivas y que existan prensa libre, oposición y jueces independientes. Un régimen puede votar y seguir siendo autoritario.',
  },
  {
    id: 'civ-045', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: 'La alternancia en el poder consiste en que:',
    opciones: [
      'Distintas fuerzas políticas se turnan en el gobierno mediante elecciones',
      'El presidente y el vicepresidente se reparten el mandato',
      'Cada región gobierna el país por turnos',
      'El poder pasa del ejecutivo al legislativo cada cierto tiempo',
    ],
    correcta: 0,
    explicacion: 'Es uno de los indicadores más usados para evaluar si un sistema es realmente competitivo: que perder una elección sea una posibilidad real para quien gobierna.',
  },
  {
    id: 'civ-046', tema: 'sistemas-politicos', dificultad: 3,
    enunciado: 'En el eje político clásico, la discusión entre izquierda y derecha se ha organizado históricamente alrededor de:',
    opciones: [
      'El papel que debe tener el Estado en la economía y la redistribución',
      'La preferencia por la guerra o por la paz',
      'La aceptación o el rechazo de la democracia',
      'El tamaño del territorio que debe tener el país',
    ],
    correcta: 0,
    explicacion: 'Es una simplificación, pero sigue siendo el eje principal: más intervención y redistribución frente a más mercado y menos Estado. Hoy se cruza con otros ejes, como los temas culturales o ambientales.',
  },
  {
    id: 'civ-047', tema: 'sistemas-politicos', dificultad: 3,
    enunciado: '¿Por qué un sistema con controles débiles entre poderes tiende al abuso, aunque el gobernante haya sido elegido?',
    opciones: [
      'Porque sin un órgano capaz de frenarlo, nada impide que use el poder en su propio beneficio',
      'Porque los gobernantes electos siempre quieren perpetuarse',
      'Porque las elecciones no tienen valor jurídico',
      'Porque la ciudadanía nunca protesta contra un gobierno electo',
    ],
    correcta: 0,
    explicacion: 'El argumento no es sobre las intenciones de nadie, sino sobre el diseño institucional: un poder sin contrapeso depende por completo de la buena voluntad de quien lo ejerce.',
  },
  {
    id: 'civ-048', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: '¿Cuál de estas situaciones NO corresponde a una democracia plena?',
    opciones: [
      'Un solo partido puede presentarse a las elecciones',
      'La oposición controla algunas gobernaciones',
      'Los jueces anulan decisiones del gobierno',
      'Los medios critican abiertamente al presidente',
    ],
    correcta: 0,
    explicacion: 'Sin competencia real no hay elección, solo ratificación. Las otras tres son justamente señales de que los contrapesos funcionan.',
  },
  {
    id: 'civ-049', tema: 'sistemas-politicos', dificultad: 2,
    enunciado: 'Se llama Estado de bienestar al modelo en el que:',
    opciones: [
      'El Estado garantiza servicios básicos como salud, educación y pensiones mediante impuestos',
      'El Estado es dueño de todas las empresas del país',
      'El Estado no interviene en la economía',
      'El bienestar depende exclusivamente de la caridad privada',
    ],
    correcta: 0,
    explicacion: 'Se consolidó en Europa tras la Segunda Guerra Mundial. No implica que el Estado sea dueño de todo: convive con economías de mercado.',
  },
  {
    id: 'civ-050', tema: 'sistemas-politicos', dificultad: 3,
    enunciado: '¿Qué se entiende por tiranía de la mayoría?',
    opciones: [
      'Que una mayoría use su poder para anular derechos básicos de un grupo minoritario',
      'Que la mayoría gane todas las elecciones seguidas',
      'Que un gobierno tenga mayoría absoluta en el congreso',
      'Que la mayoría de la población se oponga al gobierno',
    ],
    correcta: 0,
    explicacion: 'Tener los votos no vuelve legítima cualquier decisión. Contar con mayoría en el congreso es normal y necesario para gobernar; usarla para suprimir derechos es lo que describe el término.',
  },

  // ----- Partidos, elecciones y opinión pública -----
  {
    id: 'civ-051', tema: 'partidos-elecciones', dificultad: 1,
    enunciado: '¿Cuál es la función principal de los partidos políticos?',
    opciones: [
      'Organizar corrientes de opinión, presentar candidatos y ofrecer programas de gobierno',
      'Administrar el presupuesto del Estado',
      'Vigilar el conteo oficial de los votos',
      'Redactar las sentencias de los tribunales',
    ],
    correcta: 0,
    explicacion: 'Son los intermediarios entre la sociedad y el Estado: agregan demandas dispersas y las convierten en propuestas y candidaturas. El conteo lo hace la autoridad electoral.',
  },
  {
    id: 'civ-052', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: '¿Qué distingue a un sistema electoral proporcional de uno mayoritario?',
    opciones: [
      'En el proporcional los escaños se reparten según el porcentaje de votos de cada lista',
      'En el proporcional gana quien obtiene más votos y se lleva todo',
      'En el proporcional solo pueden competir dos partidos',
      'En el proporcional el voto no es secreto',
    ],
    correcta: 0,
    explicacion: 'El mayoritario tiende a producir gobiernos de un solo partido y deja sin representación a las minorías; el proporcional refleja mejor la diversidad, pero suele obligar a formar coaliciones.',
  },
  {
    id: 'civ-053', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: 'El umbral electoral es:',
    opciones: [
      'El porcentaje mínimo de votos que necesita una lista para obtener escaños',
      'La edad mínima para votar',
      'El número de firmas para inscribir un partido',
      'El máximo de dinero que puede gastar una campaña',
    ],
    correcta: 0,
    explicacion: 'Busca evitar una fragmentación excesiva del parlamento. Su costo es que los votos de quienes quedan por debajo no se traducen en representación.',
  },
  {
    id: 'civ-054', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: '¿Por qué se regula el financiamiento de las campañas electorales?',
    opciones: [
      'Para evitar que quien aporta dinero compre decisiones públicas después de la elección',
      'Para que todos los candidatos gasten exactamente lo mismo',
      'Para que las campañas sean más cortas',
      'Para impedir que los ciudadanos hagan donaciones',
    ],
    correcta: 0,
    explicacion: 'Los topes, la publicidad de los aportes y la rendición de cuentas buscan cortar el vínculo entre financiación y contratos o favores posteriores.',
  },
  {
    id: 'civ-055', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: 'En un congreso de 100 escaños repartidos de forma estrictamente proporcional, un partido que obtiene el 30 % de los votos consigue aproximadamente:',
    opciones: ['30 escaños', '50 escaños', '15 escaños', '100 escaños'],
    correcta: 0,
    explicacion: 'La proporcionalidad traduce porcentaje de votos en porcentaje de escaños. En la práctica los métodos de reparto y el umbral producen pequeñas diferencias.',
  },
  {
    id: 'civ-056', tema: 'partidos-elecciones', dificultad: 3,
    enunciado: 'Una encuesta da 42 % a un candidato y 39 % a otro, con un margen de error de ±3 puntos. ¿Qué se puede concluir?',
    opciones: [
      'Que están en empate técnico: la diferencia cabe dentro del margen de error',
      'Que el primero ganará con seguridad',
      'Que la encuesta está mal hecha',
      'Que el segundo remontará en los próximos días',
    ],
    correcta: 0,
    explicacion: 'Con ese margen, el primero podría estar entre 39 y 45 y el segundo entre 36 y 42: los rangos se superponen. Leer una encuesta sin mirar el margen de error es el error más común al informar sobre ellas.',
    pista: 'Súmale y réstale el margen a cada cifra y mira si los rangos se tocan.',
  },
  {
    id: 'civ-057', tema: 'partidos-elecciones', dificultad: 3,
    enunciado: '¿Por qué la forma de trazar los distritos electorales puede cambiar el resultado de una elección?',
    opciones: [
      'Porque agrupando a los votantes de cierta manera se puede desperdiciar o concentrar su voto',
      'Porque en distritos grandes la gente vota más',
      'Porque los distritos determinan quién puede ser candidato',
      'Porque cada distrito usa un sistema de conteo distinto',
    ],
    correcta: 0,
    explicacion: 'Se conoce como gerrymandering: con los mismos votos totales, un trazado puede dar la mayoría a un partido y otro trazado a su rival. Por eso la delimitación suele encargarse a órganos independientes.',
  },
  {
    id: 'civ-058', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: 'Cuando se dice que los medios de comunicación fijan la agenda pública, se quiere decir que:',
    opciones: [
      'Influyen menos en lo que la gente piensa que en los temas sobre los que la gente piensa',
      'Deciden directamente el resultado de las elecciones',
      'Obligan a los gobiernos a cambiar sus políticas',
      'Solo publican lo que los partidos les ordenan',
    ],
    correcta: 0,
    explicacion: 'Es la hipótesis clásica de la agenda setting: al destacar unos temas y omitir otros, los medios definen cuáles son los asuntos que se discuten.',
  },
  {
    id: 'civ-059', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre voto en blanco y voto nulo?',
    opciones: [
      'El voto en blanco es una opción válida que expresa rechazo a las candidaturas; el nulo es un voto mal marcado o anulado',
      'Son lo mismo y se cuentan juntos',
      'El voto en blanco se anula y el nulo se cuenta',
      'El voto en blanco solo existe en las elecciones presidenciales',
    ],
    correcta: 0,
    explicacion: 'En varios países el voto en blanco tiene efectos jurídicos si supera cierto umbral. El nulo, en cambio, no expresa una preferencia: simplemente no se puede contabilizar.',
  },
  {
    id: 'civ-060', tema: 'partidos-elecciones', dificultad: 2,
    enunciado: 'La observación electoral, nacional o internacional, sirve para:',
    opciones: [
      'Verificar de forma independiente que el proceso se desarrolle conforme a las reglas',
      'Decidir quién es el ganador cuando el resultado es estrecho',
      'Sustituir a la autoridad electoral del país',
      'Elegir a los jurados de votación',
    ],
    correcta: 0,
    explicacion: 'Los observadores no organizan ni deciden nada: documentan y reportan. Su valor está justamente en ser externos al proceso.',
  },

  // ----- Estado, economía y políticas públicas -----
  {
    id: 'civ-061', tema: 'economia-politica', dificultad: 1,
    enunciado: '¿Para qué sirven principalmente los impuestos?',
    opciones: [
      'Para financiar bienes y servicios públicos como salud, educación, seguridad e infraestructura',
      'Para pagar los sueldos de los partidos políticos',
      'Para controlar cuánto dinero gasta cada familia',
      'Para reducir el número de empresas en el país',
    ],
    correcta: 0,
    explicacion: 'Además de financiar, los impuestos sirven para redistribuir ingreso y para desincentivar consumos dañinos, como los que gravan el tabaco.',
  },
  {
    id: 'civ-062', tema: 'economia-politica', dificultad: 2,
    enunciado: 'Un impuesto es progresivo cuando:',
    opciones: [
      'Quien tiene más ingresos paga una proporción mayor de ellos',
      'Aumenta un poco cada año',
      'Todos pagan exactamente la misma cantidad',
      'Se cobra solo a las empresas',
    ],
    correcta: 0,
    explicacion: 'El impuesto sobre la renta suele ser progresivo por tramos. El IVA tiende a ser regresivo: como todos pagan la misma tasa, pesa proporcionalmente más en el bolsillo de quien menos gana.',
  },
  {
    id: 'civ-063', tema: 'economia-politica', dificultad: 2,
    enunciado: 'El presupuesto público de un país es:',
    opciones: [
      'El plan anual de ingresos y gastos del Estado, aprobado por el congreso',
      'La cantidad de dinero que tiene el banco central',
      'El total de impuestos recaudados en la historia del país',
      'La deuda que el país tiene con otros Estados',
    ],
    correcta: 0,
    explicacion: 'Es la ley más política del año: ahí se ve en qué se traducen realmente las prioridades de un gobierno, más allá de sus discursos.',
  },
  {
    id: 'civ-064', tema: 'economia-politica', dificultad: 2,
    enunciado: 'Hay déficit fiscal cuando el Estado:',
    opciones: [
      'Gasta más de lo que ingresa y debe financiar la diferencia con deuda',
      'Recauda más impuestos de los previstos',
      'Reduce el gasto por debajo de lo presupuestado',
      'Exporta menos de lo que importa',
    ],
    correcta: 0,
    explicacion: 'Un déficit puntual puede ser razonable para sostener la economía en una crisis; sostenido en el tiempo obliga a pagar cada vez más intereses y deja menos dinero para lo demás. Exportar menos de lo que se importa es déficit comercial, otra cosa.',
  },
  {
    id: 'civ-065', tema: 'economia-politica', dificultad: 1,
    enunciado: 'La inflación es:',
    opciones: [
      'El aumento general y sostenido de los precios, que reduce el poder adquisitivo del dinero',
      'La subida del precio de un producto concreto',
      'El aumento de los impuestos',
      'La caída del valor de las exportaciones',
    ],
    correcta: 0,
    explicacion: 'Lo clave es que sea general y sostenido: que suba el tomate una semana no es inflación. Con inflación, el mismo billete compra menos cosas cada mes.',
  },
  {
    id: 'civ-066', tema: 'economia-politica', dificultad: 3,
    enunciado: 'Un trabajador recibe un aumento salarial del 5 % en un año en el que la inflación fue del 8 %. ¿Qué pasó con su capacidad de compra?',
    opciones: [
      'Cayó alrededor de un 3 %, porque los precios subieron más que su salario',
      'Subió un 5 %, porque su salario aumentó',
      'Subió un 3 %, porque la diferencia lo favorece',
      'No cambió, porque el salario y los precios se compensan',
    ],
    correcta: 0,
    explicacion: 'El aumento nominal es 5 %, pero el real es aproximadamente 5 − 8 = −3 %. Distinguir cifras nominales de reales es la clave para leer cualquier noticia económica.',
  },
  {
    id: 'civ-067', tema: 'economia-politica', dificultad: 3,
    enunciado: '¿Cuál de estos es un bien público en sentido económico?',
    opciones: [
      'El alumbrado de una calle',
      'Una entrada de cine',
      'Un almuerzo en un restaurante',
      'Una camiseta comprada en una tienda',
    ],
    correcta: 0,
    explicacion: 'Un bien público no es rival (que yo lo use no impide que tú lo uses) ni excluyente (no se puede impedir el acceso). Por eso el mercado no lo provee bien y suele financiarse con impuestos.',
  },
  {
    id: 'civ-068', tema: 'economia-politica', dificultad: 2,
    enunciado: '¿Qué diferencia a un subsidio focalizado de uno universal?',
    opciones: [
      'El focalizado se dirige solo a quienes cumplen ciertos criterios; el universal llega a toda la población',
      'El focalizado lo paga el sector privado',
      'El universal es siempre más barato para el Estado',
      'El focalizado solo se aplica en zonas rurales',
    ],
    correcta: 0,
    explicacion: 'Focalizar concentra el gasto donde más falta hace, pero exige identificar bien a los beneficiarios y deja fuera a quienes no aparecen en los registros. El universal es más simple y más caro.',
  },
  {
    id: 'civ-069', tema: 'economia-politica', dificultad: 3,
    enunciado: '¿Por qué la evasión de impuestos perjudica también a quienes sí los pagan?',
    opciones: [
      'Porque hay menos recursos para los servicios públicos y la carga recae sobre menos contribuyentes',
      'Porque obliga al banco central a emitir moneda',
      'Porque hace subir el precio de las exportaciones',
      'Porque reduce la población económicamente activa',
    ],
    correcta: 0,
    explicacion: 'Con menos recaudación hay dos salidas, y las dos duelen: recortar servicios o subir la carga sobre quienes ya cumplen. Además pone en desventaja competitiva a las empresas que declaran todo.',
  },
  {
    id: 'civ-070', tema: 'economia-politica', dificultad: 2,
    enunciado: 'La función principal de un banco central suele ser:',
    opciones: [
      'Velar por la estabilidad de los precios controlando la inflación',
      'Recaudar los impuestos del país',
      'Aprobar el presupuesto nacional',
      'Fijar los salarios de los trabajadores',
    ],
    correcta: 0,
    explicacion: 'Lo hace sobre todo con la tasa de interés y el manejo de la cantidad de dinero. Suele ser independiente del gobierno, precisamente para que no se emita dinero por conveniencia política.',
  },

  // ----- Convivencia y resolución de conflictos -----
  {
    id: 'civ-071', tema: 'convivencia', dificultad: 2,
    enunciado: 'Desde el punto de vista de la convivencia, un conflicto es:',
    opciones: [
      'Una diferencia de intereses o necesidades, que no equivale a violencia',
      'Siempre un hecho negativo que hay que evitar',
      'Lo mismo que una agresión física',
      'Un problema que solo puede resolver una autoridad',
    ],
    correcta: 0,
    explicacion: 'El conflicto es inevitable y hasta útil: señala que algo hay que negociar. La violencia es una de las formas —la peor— de tramitarlo.',
  },
  {
    id: 'civ-072', tema: 'convivencia', dificultad: 2,
    enunciado: '¿Qué caracteriza a la mediación frente al arbitraje?',
    opciones: [
      'El mediador ayuda a que las partes construyan su propio acuerdo, sin imponer una solución',
      'El mediador dicta una decisión obligatoria',
      'La mediación solo se usa en procesos penales',
      'En la mediación no pueden participar abogados',
    ],
    correcta: 0,
    explicacion: 'En el arbitraje un tercero decide y su laudo obliga. En la mediación y la conciliación el acuerdo lo construyen las partes, lo que suele hacerlo más duradero.',
  },
  {
    id: 'civ-073', tema: 'convivencia', dificultad: 2,
    enunciado: 'Hay discriminación cuando:',
    opciones: [
      'Se da un trato desfavorable a alguien por una característica como su origen, sexo, religión o discapacidad',
      'Se trata de forma distinta a personas en situaciones distintas con una razón objetiva',
      'Alguien recibe una nota más baja en un examen',
      'Una empresa contrata a quien tiene mejor desempeño',
    ],
    correcta: 0,
    explicacion: 'La clave es que el criterio del trato sea irrelevante para el asunto. Evaluar el desempeño es una distinción legítima; usar el apellido o el color de piel no lo es.',
  },
  {
    id: 'civ-074', tema: 'convivencia', dificultad: 2,
    enunciado: '¿Qué tres rasgos distinguen el acoso escolar de una pelea aislada?',
    opciones: [
      'Es intencional, se repite en el tiempo y hay desequilibrio de poder entre las partes',
      'Ocurre fuera del colegio, es anónimo y no deja huellas',
      'Involucra a más de dos personas, es público y lo sanciona la ley penal',
      'Es físico, deja lesiones visibles y ocurre en el recreo',
    ],
    correcta: 0,
    explicacion: 'Sin repetición y sin asimetría de poder hay conflicto, no acoso. Por eso las respuestas efectivas trabajan sobre el grupo entero y no solo sobre los dos implicados.',
  },
  {
    id: 'civ-075', tema: 'convivencia', dificultad: 2,
    enunciado: 'Ante una situación de acoso, ¿cuál es el papel más útil de quien la presencia?',
    opciones: [
      'Dejar de ser espectador pasivo: apoyar a quien lo sufre y reportarlo a un adulto responsable',
      'No intervenir para no empeorar la situación',
      'Responder con la misma agresión hacia el agresor',
      'Esperar a que la víctima lo denuncie sola',
    ],
    correcta: 0,
    explicacion: 'El silencio del grupo es lo que sostiene el acoso: le da audiencia al agresor y deja sola a la víctima. Los programas que funcionan se dirigen justamente a los espectadores.',
  },
  {
    id: 'civ-076', tema: 'convivencia', dificultad: 3,
    enunciado: 'Una respuesta asertiva ante un desacuerdo consiste en:',
    opciones: [
      'Expresar la propia posición con claridad y sin agredir, reconociendo la del otro',
      'Ceder para evitar el enfrentamiento',
      'Imponer el punto de vista propio con firmeza',
      'Guardar silencio y retirarse de la conversación',
    ],
    correcta: 0,
    explicacion: 'La asertividad está entre la pasividad (ceder siempre) y la agresividad (imponerse). Es decir lo que se piensa sin pisar al otro.',
  },
  {
    id: 'civ-077', tema: 'convivencia', dificultad: 2,
    enunciado: 'Las normas de convivencia de una institución se justifican principalmente porque:',
    opciones: [
      'Hacen previsible el comportamiento y protegen los derechos de todos los miembros',
      'Permiten castigar a quienes piensan distinto',
      'Sustituyen a las leyes del país dentro de la institución',
      'Evitan que existan conflictos',
    ],
    correcta: 0,
    explicacion: 'Un reglamento no elimina los conflictos: establece un procedimiento conocido para resolverlos. Y nunca puede contradecir la ley ni los derechos fundamentales.',
  },
  {
    id: 'civ-078', tema: 'convivencia', dificultad: 3,
    enunciado: '¿En qué se diferencia la justicia restaurativa de la puramente punitiva?',
    opciones: [
      'La restaurativa busca reparar el daño y reintegrar, además de establecer responsabilidad',
      'La restaurativa deja el delito sin consecuencias',
      'La punitiva se aplica solo a menores de edad',
      'La restaurativa la aplica la víctima por su cuenta',
    ],
    correcta: 0,
    explicacion: 'No es impunidad: hay reconocimiento de responsabilidad y reparación a la víctima. La diferencia está en el objetivo, que no se agota en el castigo.',
  },
  {
    id: 'civ-079', tema: 'convivencia', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre estereotipo y prejuicio?',
    opciones: [
      'El estereotipo es una creencia generalizada sobre un grupo; el prejuicio es la valoración negativa que se le asocia',
      'El estereotipo es negativo y el prejuicio positivo',
      'El estereotipo es individual y el prejuicio colectivo',
      'Son términos equivalentes',
    ],
    correcta: 0,
    explicacion: 'Del estereotipo (creencia) al prejuicio (actitud) y de ahí a la discriminación (conducta). Reconocer la cadena ayuda a cortarla antes del último paso.',
  },
  {
    id: 'civ-080', tema: 'convivencia', dificultad: 2,
    enunciado: 'La interculturalidad va más allá de la simple multiculturalidad porque:',
    opciones: [
      'No se limita a que convivan varias culturas: propone intercambio y relación en condiciones de igualdad',
      'Exige que todos adopten la cultura mayoritaria',
      'Implica que cada cultura viva separada de las demás',
      'Se refiere únicamente a la enseñanza de idiomas',
    ],
    correcta: 0,
    explicacion: 'Multicultural describe un hecho: hay varias culturas en el mismo territorio. Intercultural propone una relación, y eso incluye discutir las desigualdades entre ellas.',
  },

  // ----- Organismos internacionales -----
  {
    id: 'civ-081', tema: 'organismos', dificultad: 1,
    enunciado: 'El órgano de la ONU en el que están representados todos los Estados miembros con un voto cada uno es:',
    opciones: ['La Asamblea General', 'El Consejo de Seguridad', 'La Corte Internacional de Justicia', 'La Secretaría General'],
    correcta: 0,
    explicacion: 'La Asamblea General es el foro plenario. El Consejo de Seguridad tiene 15 miembros, de los cuales 5 son permanentes.',
  },
  {
    id: 'civ-082', tema: 'organismos', dificultad: 2,
    enunciado: 'El derecho de veto en el Consejo de Seguridad de la ONU permite que:',
    opciones: [
      'Cualquiera de los cinco miembros permanentes bloquee por sí solo una resolución',
      'La Asamblea General anule una decisión del Consejo',
      'El secretario general suspenda a un país miembro',
      'Un país sea expulsado de la organización',
    ],
    correcta: 0,
    explicacion: 'Es la crítica más frecuente al diseño de la ONU: cuando el conflicto involucra a un miembro permanente o a sus aliados, el Consejo suele quedar paralizado.',
  },
  {
    id: 'civ-083', tema: 'organismos', dificultad: 1,
    enunciado: 'La UNESCO es el organismo de la ONU especializado en:',
    opciones: ['Educación, ciencia y cultura', 'Salud pública mundial', 'Comercio internacional', 'Ayuda humanitaria en desastres'],
    correcta: 0,
    explicacion: 'Entre otras cosas administra la lista de Patrimonio de la Humanidad. La salud le corresponde a la OMS.',
  },
  {
    id: 'civ-084', tema: 'organismos', dificultad: 1,
    enunciado: 'La Organización Mundial de la Salud (OMS) se encarga de:',
    opciones: [
      'Coordinar la respuesta internacional en materia de salud y emitir recomendaciones sanitarias',
      'Financiar la construcción de hospitales en todos los países',
      'Autorizar la venta de medicamentos en cada país',
      'Administrar los sistemas de salud nacionales',
    ],
    correcta: 0,
    explicacion: 'Coordina, vigila y recomienda, pero la autorización de medicamentos y la gestión de los hospitales siguen siendo competencia de cada Estado.',
  },
  {
    id: 'civ-085', tema: 'organismos', dificultad: 2,
    enunciado: 'La Organización de Estados Americanos (OEA) es un foro:',
    opciones: [
      'Regional del continente americano para la cooperación política y la defensa de la democracia',
      'Mundial para la regulación del comercio',
      'Militar del Atlántico Norte',
      'Financiero para otorgar créditos a los países pobres',
    ],
    correcta: 0,
    explicacion: 'A ella está vinculado el sistema interamericano de derechos humanos, con la Comisión y la Corte Interamericana.',
  },
  {
    id: 'civ-086', tema: 'organismos', dificultad: 2,
    enunciado: 'La Corte Penal Internacional juzga a:',
    opciones: [
      'Personas acusadas de genocidio, crímenes de guerra y crímenes de lesa humanidad',
      'Estados que incumplen tratados comerciales',
      'Empresas que contaminan el medio ambiente',
      'Gobiernos que no pagan su deuda externa',
    ],
    correcta: 0,
    explicacion: 'Juzga individuos, no Estados, y actúa de forma complementaria: solo interviene cuando el país no puede o no quiere investigar. Los litigios entre Estados van a la Corte Internacional de Justicia.',
  },
  {
    id: 'civ-087', tema: 'organismos', dificultad: 3,
    enunciado: 'El derecho internacional humanitario se aplica:',
    opciones: [
      'Durante los conflictos armados, para proteger a la población civil y a quienes ya no combaten',
      'Solo en tiempos de paz, para proteger a los refugiados',
      'Únicamente en las guerras entre dos Estados',
      'Para sancionar a los países que declaran la guerra',
    ],
    correcta: 0,
    explicacion: 'No discute si la guerra es justa: regula cómo se combate. Protege a civiles, heridos y prisioneros, y se aplica también en conflictos internos.',
  },
  {
    id: 'civ-088', tema: 'organismos', dificultad: 2,
    enunciado: 'Un tratado internacional se vuelve obligatorio para un país cuando:',
    opciones: [
      'Ese país lo ratifica conforme a su procedimiento interno',
      'Lo firma el ministro de relaciones exteriores en la ceremonia',
      'La mayoría de los países del mundo lo aprueba',
      'La ONU lo aprueba en la Asamblea General',
    ],
    correcta: 0,
    explicacion: 'Firmar expresa la intención; ratificar —normalmente con aprobación del congreso— es lo que obliga. Por eso hay tratados firmados por muchos países y ratificados por pocos.',
  },
  {
    id: 'civ-089', tema: 'organismos', dificultad: 2,
    enunciado: '¿Cuál es la diferencia jurídica entre un refugiado y un migrante económico?',
    opciones: [
      'El refugiado huye de persecución o conflicto y tiene derecho a protección internacional',
      'El refugiado siempre cruza una frontera y el migrante no',
      'El migrante económico no puede ser devuelto a su país',
      'No hay diferencia: los dos términos son intercambiables',
    ],
    correcta: 0,
    explicacion: 'De ahí el principio de no devolución: a un refugiado no se le puede regresar a donde su vida corre peligro. Los desplazados internos también huyen, pero sin cruzar una frontera.',
  },
  {
    id: 'civ-090', tema: 'organismos', dificultad: 3,
    enunciado: '¿Por qué muchas resoluciones de organismos internacionales no llegan a cumplirse?',
    opciones: [
      'Porque su aplicación depende de la voluntad de Estados soberanos y no hay un poder coercitivo por encima de ellos',
      'Porque se redactan en idiomas que pocos países entienden',
      'Porque los organismos no tienen presupuesto',
      'Porque no se publican oficialmente',
    ],
    correcta: 0,
    explicacion: 'Esa es la diferencia estructural con el derecho interno: no existe una policía mundial. Lo que hay son sanciones, presión diplomática y costo reputacional.',
  },

  // ----- Ética pública, corrupción y transparencia -----
  {
    id: 'civ-091', tema: 'etica-publica', dificultad: 1,
    enunciado: 'La corrupción se define como:',
    opciones: [
      'El uso de un cargo o recurso público para obtener un beneficio privado',
      'Cualquier error cometido por un funcionario',
      'La lentitud de los trámites en una entidad pública',
      'El desacuerdo entre dos autoridades sobre una decisión',
    ],
    correcta: 0,
    explicacion: 'La clave es el desvío del interés público hacia el privado, con o sin dinero de por medio: también lo es nombrar a un familiar sin concurso.',
  },
  {
    id: 'civ-092', tema: 'etica-publica', dificultad: 2,
    enunciado: 'Hay conflicto de interés cuando un funcionario:',
    opciones: [
      'Debe decidir sobre un asunto en el que tiene un interés personal, familiar o económico',
      'No está de acuerdo con la política de su superior',
      'Trabaja en dos entidades públicas a la vez',
      'Recibe críticas de la prensa por una decisión',
    ],
    correcta: 0,
    explicacion: 'No hace falta que la decisión sea indebida: la sola situación obliga a declararla y a apartarse. Por eso existen los impedimentos y las recusaciones.',
  },
  {
    id: 'civ-093', tema: 'etica-publica', dificultad: 2,
    enunciado: 'El derecho de acceso a la información pública implica que:',
    opciones: [
      'Cualquier persona puede solicitar información del Estado sin tener que justificar para qué la quiere',
      'Solo los periodistas pueden pedir documentos oficiales',
      'Toda la información del Estado es pública sin excepción',
      'La información se entrega únicamente a quien demuestre un interés legítimo',
    ],
    correcta: 0,
    explicacion: 'La regla es la publicidad y la excepción, la reserva, que debe estar prevista en la ley y motivarse. No hay que explicar por qué se pide: la información es de todos.',
  },
  {
    id: 'civ-094', tema: 'etica-publica', dificultad: 2,
    enunciado: 'La rendición de cuentas consiste en que:',
    opciones: [
      'Quien ejerce un cargo público explica públicamente qué hizo con los recursos y responde por ello',
      'El Estado publica su presupuesto una vez al año',
      'Los ciudadanos pagan impuestos puntualmente',
      'Los funcionarios entregan su declaración de renta',
    ],
    correcta: 0,
    explicacion: 'Tiene dos partes que suelen olvidarse juntas: informar y responder por lo informado. Publicar datos sin consecuencias no es rendición de cuentas.',
  },
  {
    id: 'civ-095', tema: 'etica-publica', dificultad: 2,
    enunciado: '¿Por qué las compras del Estado suelen hacerse mediante licitación pública?',
    opciones: [
      'Para que varios oferentes compitan en condiciones conocidas y se elija la mejor propuesta',
      'Para que el proceso dure más y se revise mejor',
      'Para que solo participen empresas grandes',
      'Porque lo exige el banco central',
    ],
    correcta: 0,
    explicacion: 'La competencia abierta y las reglas publicadas de antemano son la principal defensa contra el contrato a la medida de un amigo.',
  },
  {
    id: 'civ-096', tema: 'etica-publica', dificultad: 3,
    enunciado: '¿Por qué la corrupción encarece las obras públicas incluso cuando la obra llega a terminarse?',
    opciones: [
      'Porque el sobrecosto se traslada al presupuesto y se elige al contratista por el soborno y no por su capacidad',
      'Porque las obras corruptas siempre se hacen dos veces',
      'Porque los materiales suben de precio durante la investigación',
      'Porque obliga al Estado a contratar más ingenieros',
    ],
    correcta: 0,
    explicacion: 'Hay dos costos: el dinero de más y el peor ejecutor. Por eso las obras con corrupción tienden además a durar menos y a fallar antes.',
  },
  {
    id: 'civ-097', tema: 'etica-publica', dificultad: 2,
    enunciado: 'Una veeduría ciudadana es:',
    opciones: [
      'Un grupo de ciudadanos organizado para vigilar la gestión pública y el uso de los recursos',
      'Un órgano de control creado por el gobierno',
      'Un tribunal que sanciona a los funcionarios',
      'Una comisión del congreso',
    ],
    correcta: 0,
    explicacion: 'Es control social: no sanciona, pero puede pedir información, hacer seguimiento y denunciar ante los órganos que sí sancionan.',
  },
  {
    id: 'civ-098', tema: 'etica-publica', dificultad: 2,
    enunciado: 'El clientelismo político consiste en:',
    opciones: [
      'Intercambiar apoyo electoral por favores, puestos o beneficios particulares',
      'Hacer campaña puerta a puerta',
      'Financiar una campaña con aportes de simpatizantes',
      'Atender a los ciudadanos en las oficinas del gobierno',
    ],
    correcta: 0,
    explicacion: 'Convierte un derecho en una mercancía: el voto deja de expresar una preferencia y pasa a pagar un favor. Corroe la representación aunque las elecciones sean formalmente limpias.',
  },
  {
    id: 'civ-099', tema: 'etica-publica', dificultad: 3,
    enunciado: '¿Por qué muchas legislaciones protegen a quien denuncia hechos de corrupción dentro de una entidad?',
    opciones: [
      'Porque sin protección frente a represalias casi nadie denunciaría lo que ocurre puertas adentro',
      'Porque el denunciante tiene derecho a quedarse con parte del dinero recuperado',
      'Porque la denuncia lo convierte automáticamente en testigo protegido de por vida',
      'Porque así se evita que la prensa publique el caso',
    ],
    correcta: 0,
    explicacion: 'Quien está dentro es quien ve el hecho, y también quien más arriesga: el empleo, el ascenso, la reputación. Sin garantías, la información nunca sale.',
  },
  {
    id: 'civ-100', tema: 'etica-publica', dificultad: 3,
    enunciado: 'Un funcionario acepta un regalo costoso de un contratista. La ley no lo prohíbe expresamente. ¿Cómo se evalúa éticamente?',
    opciones: [
      'Es cuestionable: aunque sea legal, compromete su imparcialidad y la confianza pública',
      'Es correcto, porque lo que no está prohibido está permitido',
      'Es correcto si lo declara después de recibirlo',
      'Solo sería incorrecto si el contratista pidiera algo a cambio por escrito',
    ],
    correcta: 0,
    explicacion: 'Lo legal y lo ético no coinciden siempre, y la ética pública exige el estándar más alto: no basta con no delinquir, hay que no comprometer la imparcialidad ni su apariencia.',
  },
  // ----- Ampliación por niveles -----
  {
    id: 'civ-101', tema: 'estado-poderes', dificultad: 3,
    enunciado: 'Además de hacer las leyes, ¿qué otra función central cumple el Congreso de la República?',
    opciones: [
      'Ejercer control político sobre el Gobierno',
      'Juzgar a los delincuentes comunes',
      'Nombrar a los alcaldes de las ciudades',
      'Administrar el presupuesto de los municipios',
    ],
    correcta: 0,
    explicacion: 'El Congreso legisla y vigila: cita a los ministros, hace debates de control y puede censurarlos. Juzgar corresponde a la rama judicial y los alcaldes se eligen por voto popular.',
  },
  {
    id: 'civ-102', tema: 'estado-poderes', dificultad: 3,
    enunciado: '¿Qué órgano decide si una ley aprobada por el Congreso se ajusta a la Constitución?',
    opciones: ['La Corte Constitucional', 'La Corte Suprema de Justicia', 'El Consejo de Estado', 'La Procuraduría General'],
    correcta: 0,
    explicacion: 'La Corte Constitucional es la guardiana de la Constitución y declara exequible o inexequible una ley. La Corte Suprema es el tribunal máximo de la justicia ordinaria y el Consejo de Estado, de la contencioso-administrativa.',
  },
  {
    id: 'civ-103', tema: 'estado-poderes', dificultad: 4,
    enunciado: 'La moción de censura en Colombia sirve para que el Congreso:',
    opciones: [
      'Separe de su cargo a un ministro por asuntos relacionados con sus funciones',
      'Destituya al presidente de la República',
      'Anule una sentencia judicial',
      'Revoque el mandato de un alcalde',
    ],
    correcta: 0,
    explicacion: 'Es una herramienta de control político sobre los ministros, superintendentes y directores de departamentos administrativos. Al presidente solo puede investigarlo la Comisión de Acusación y juzgarlo el Senado, y la revocatoria del mandato es un mecanismo de los ciudadanos, no del Congreso.',
  },
  {
    id: 'civ-104', tema: 'estado-poderes', dificultad: 4,
    enunciado: '¿Cuál es la diferencia entre la Fiscalía y los jueces en un proceso penal?',
    opciones: [
      'La Fiscalía investiga y acusa; el juez decide si hay responsabilidad y condena o absuelve',
      'La Fiscalía dicta la sentencia y el juez la ejecuta',
      'El juez investiga y la Fiscalía juzga',
      'Los dos hacen lo mismo, pero en instancias distintas',
    ],
    correcta: 0,
    explicacion: 'Separar quién acusa de quién juzga es la base del sistema acusatorio: si el mismo funcionario investigara y condenara, difícilmente sería imparcial.',
  },
  {
    id: 'civ-105', tema: 'estado-poderes', dificultad: 4,
    enunciado: 'Cuando el presidente declara un estado de excepción (por ejemplo, conmoción interior):',
    opciones: [
      'Obtiene facultades extraordinarias limitadas en el tiempo y sometidas al control automático de la Corte Constitucional',
      'Puede suspender la Constitución mientras dure la emergencia',
      'Gobierna sin límite hasta que decida levantarlo',
      'Queda facultado para disolver el Congreso',
    ],
    correcta: 0,
    explicacion: 'La Constitución de 1991 acotó deliberadamente esos poderes tras décadas de estado de sitio: hay plazos, los derechos fundamentales intangibles no se suspenden, el Congreso sigue funcionando y la Corte revisa los decretos sin que nadie se lo pida.',
  },
  {
    id: 'civ-106', tema: 'constitucion', dificultad: 1,
    enunciado: '¿De qué año es la Constitución Política vigente en Colombia?',
    opciones: ['1991', '1886', '1936', '2002'],
    correcta: 0,
    explicacion: 'Fue expedida por una Asamblea Nacional Constituyente y reemplazó a la de 1886, que había regido más de un siglo.',
  },
  {
    id: 'civ-107', tema: 'constitucion', dificultad: 1,
    enunciado: 'Según su artículo primero, Colombia es:',
    opciones: [
      'Un Estado social de derecho, organizado como república unitaria y descentralizada',
      'Una monarquía constitucional',
      'Un Estado federal',
      'Una república confesional',
    ],
    correcta: 0,
    explicacion: 'La fórmula "Estado social de derecho" implica que el Estado no solo respeta las leyes, sino que debe garantizar condiciones materiales de vida digna.',
  },
  {
    id: 'civ-108', tema: 'constitucion', dificultad: 3,
    enunciado: '¿En qué plazo debe resolver un juez una acción de tutela?',
    opciones: ['En diez días', 'En treinta días', 'En seis meses', 'No tiene plazo fijo'],
    correcta: 0,
    explicacion: 'La tutela es un procedimiento preferente y sumario: diez días hábiles. Esa rapidez es justamente lo que la hace útil para proteger un derecho fundamental amenazado.',
  },
  {
    id: 'civ-109', tema: 'constitucion', dificultad: 4,
    enunciado: '¿Qué significa que ciertos tratados internacionales formen parte del "bloque de constitucionalidad"?',
    opciones: [
      'Que los tratados de derechos humanos ratificados por Colombia se usan junto con la Constitución para juzgar la validez de las leyes',
      'Que los tratados están por encima de la Constitución',
      'Que el Congreso no puede aprobar tratados internacionales',
      'Que los jueces no pueden citar normas internacionales',
    ],
    correcta: 0,
    explicacion: 'El artículo 93 incorpora esos tratados al parámetro de control. No reemplazan a la Constitución: se leen con ella, y por eso una ley puede ser inexequible por desconocer un convenio de derechos humanos.',
  },
  {
    id: 'civ-110', tema: 'constitucion', dificultad: 4,
    enunciado: '¿Por cuáles vías puede reformarse la Constitución colombiana?',
    opciones: [
      'Por acto legislativo del Congreso, por referendo o por una asamblea constituyente',
      'Solo por decreto del presidente',
      'Solo por sentencia de la Corte Constitucional',
      'Por acuerdo de los concejos municipales',
    ],
    correcta: 0,
    explicacion: 'El artículo 374 prevé esos tres caminos. Los dos últimos exigen participación ciudadana directa; el primero es el más usado y necesita dos vueltas de debate en el Congreso.',
  },
  {
    id: 'civ-111', tema: 'constitucion', dificultad: 4,
    enunciado: 'Si una ley aprobada por el Congreso contradice la Constitución, lo que ocurre es que:',
    opciones: [
      'La Corte Constitucional puede declararla inexequible y sacarla del ordenamiento',
      'La ley prevalece por ser posterior a la Constitución',
      'Ambas se aplican y el juez escoge la que prefiera',
      'La ley solo puede ser derogada por otra ley',
    ],
    correcta: 0,
    explicacion: 'La Constitución es norma de normas: ninguna ley puede contrariarla, sin importar que sea más reciente. Esa jerarquía es lo que distingue a una constitución rígida de una ley común.',
  },
  {
    id: 'civ-112', tema: 'derechos', dificultad: 1,
    enunciado: '¿Cuál de estos es un derecho fundamental reconocido por la Constitución?',
    opciones: ['El derecho a la vida', 'El derecho a conducir', 'El derecho a tener celular', 'El derecho a ganar un concurso'],
    correcta: 0,
    explicacion: 'Los derechos fundamentales son los inherentes a la persona, como la vida, la igualdad, la libertad y el debido proceso. Conducir es una autorización que el Estado concede bajo requisitos.',
  },
  {
    id: 'civ-113', tema: 'derechos', dificultad: 1,
    enunciado: '¿Qué protege el habeas corpus?',
    opciones: [
      'La libertad personal de quien cree estar privado de ella ilegalmente',
      'El derecho a la vivienda',
      'La propiedad privada',
      'El derecho al trabajo',
    ],
    correcta: 0,
    explicacion: 'Permite pedir a un juez que revise de inmediato la legalidad de una detención y ordene la libertad si no hay fundamento. Debe resolverse en 36 horas.',
  },
  {
    id: 'civ-114', tema: 'derechos', dificultad: 4,
    enunciado: 'El derecho a gozar de un ambiente sano suele clasificarse como un derecho:',
    opciones: [
      'Colectivo, porque su titular es la comunidad y no solo una persona',
      'Civil y político de primera generación',
      'Exclusivamente económico',
      'Que solo puede reclamar el Estado',
    ],
    correcta: 0,
    explicacion: 'Es un derecho de tercera generación o colectivo, y por eso se protege con acciones populares más que con tutela, salvo cuando su vulneración afecta directamente un derecho fundamental como la salud o la vida.',
  },
  {
    id: 'civ-115', tema: 'derechos', dificultad: 4,
    enunciado: '¿En qué casos procede la acción de tutela contra un particular?',
    opciones: [
      'Cuando presta un servicio público o cuando el solicitante está en estado de subordinación o indefensión frente a él',
      'Nunca: la tutela solo procede contra autoridades públicas',
      'Siempre que haya un desacuerdo entre dos personas',
      'Solo cuando el particular es una empresa extranjera',
    ],
    correcta: 0,
    explicacion: 'El artículo 86 lo permite en esos supuestos: un colegio frente a un estudiante, una EPS frente a un afiliado, un empleador frente a un trabajador. Lo que se busca es cubrir las relaciones donde hay una desigualdad real de poder.',
  },
  {
    id: 'civ-116', tema: 'derechos', dificultad: 4,
    enunciado: 'La libertad de expresión es un derecho fundamental, pero:',
    opciones: [
      'No ampara la calumnia, la injuria ni la incitación a la violencia',
      'Permite decir cualquier cosa sin consecuencia alguna',
      'Solo la tienen los periodistas',
      'Puede suspenderse por orden de un alcalde',
    ],
    correcta: 0,
    explicacion: 'Ningún derecho es absoluto: la protección es amplísima frente a la crítica y la opinión, incluso incómoda, pero no cubre afirmaciones falsas que dañan la honra ni los llamados a agredir a alguien.',
  },
  {
    id: 'civ-117', tema: 'democracia', dificultad: 1,
    enunciado: 'En una democracia representativa, los ciudadanos:',
    opciones: [
      'Eligen mediante el voto a quienes toman las decisiones en su nombre',
      'Deciden personalmente cada asunto público',
      'Delegan todo el poder en un solo líder vitalicio',
      'No participan en la elección de autoridades',
    ],
    correcta: 0,
    explicacion: 'La representación resuelve un problema práctico: millones de personas no pueden votar cada decisión. Por eso eligen a quien decide, y lo hacen periódicamente para poder cambiarlo.',
  },
  {
    id: 'civ-118', tema: 'democracia', dificultad: 3,
    enunciado: '¿Cuál de los siguientes NO es un mecanismo de participación ciudadana previsto en Colombia?',
    opciones: [
      'La moción de censura',
      'El cabildo abierto',
      'La consulta popular',
      'La iniciativa legislativa popular',
    ],
    correcta: 0,
    explicacion: 'La moción de censura la ejerce el Congreso, no la ciudadanía. Los mecanismos de participación de la Ley 134 son el voto, el plebiscito, el referendo, la consulta popular, el cabildo abierto, la iniciativa popular y la revocatoria del mandato.',
  },
  {
    id: 'civ-119', tema: 'democracia', dificultad: 4,
    enunciado: '¿Cuál es la diferencia entre un plebiscito y un referendo?',
    opciones: [
      'El plebiscito somete a votación una decisión política del presidente; el referendo, un texto normativo que se aprueba o se deroga',
      'El plebiscito lo convoca el Congreso y el referendo, el presidente',
      'El plebiscito es obligatorio y el referendo, voluntario',
      'No hay diferencia: son dos nombres para lo mismo',
    ],
    correcta: 0,
    explicacion: 'En el referendo el ciudadano vota sobre un articulado concreto; en el plebiscito respalda o rechaza una política del gobernante. La consulta popular, por su parte, plantea una pregunta general de interés para un territorio.',
  },
  {
    id: 'civ-120', tema: 'democracia', dificultad: 4,
    enunciado: 'La revocatoria del mandato en Colombia puede aplicarse a:',
    opciones: ['Alcaldes y gobernadores', 'El presidente de la República', 'Los senadores', 'Los magistrados de las altas cortes'],
    correcta: 0,
    explicacion: 'Solo procede frente a cargos uninominales de elección popular en el nivel territorial, porque son los que se eligen con un programa de gobierno inscrito. El voto programático es lo que da sentido a la revocatoria.',
  },
  {
    id: 'civ-121', tema: 'democracia', dificultad: 4,
    enunciado: '¿Por qué en una democracia constitucional una mayoría no puede decidir eliminar los derechos fundamentales de una minoría?',
    opciones: [
      'Porque esos derechos son un límite al poder de las mayorías y por eso están en la Constitución',
      'Porque las minorías tienen más votos en el Congreso',
      'Porque solo el presidente puede modificar derechos',
      'Porque los derechos los otorgan los organismos internacionales',
    ],
    correcta: 0,
    explicacion: 'Una democracia no es solo la regla de la mayoría: es la regla de la mayoría dentro de unos límites. Si el 51 % pudiera suprimir los derechos del 49 %, el voto dejaría de proteger a nadie.',
  },
  {
    id: 'civ-122', tema: 'sistemas-politicos', dificultad: 1,
    enunciado: 'En un sistema presidencial:',
    opciones: [
      'El presidente es elegido por voto popular y es a la vez jefe de Estado y jefe de Gobierno',
      'El jefe de Gobierno lo elige el parlamento',
      'El jefe de Estado hereda el cargo',
      'No existen elecciones',
    ],
    correcta: 0,
    explicacion: 'Es el modelo de Colombia y de casi toda América Latina: el presidente tiene su propia legitimidad electoral, distinta de la del Congreso.',
  },
  {
    id: 'civ-123', tema: 'sistemas-politicos', dificultad: 1,
    enunciado: 'En una monarquía parlamentaria como la española o la británica:',
    opciones: [
      'El rey cumple funciones simbólicas y el gobierno responde ante el parlamento',
      'El rey gobierna con poder absoluto',
      'No hay elecciones ni parlamento',
      'El rey es elegido cada cuatro años',
    ],
    correcta: 0,
    explicacion: 'Se resume en la fórmula "el rey reina pero no gobierna": el poder real está en el primer ministro y en el parlamento que lo sostiene.',
  },
  {
    id: 'civ-124', tema: 'sistemas-politicos', dificultad: 4,
    enunciado: '¿Cuál es la diferencia de fondo entre un sistema parlamentario y uno presidencial?',
    opciones: [
      'En el parlamentario el gobierno necesita la confianza del parlamento y puede caer sin esperar elecciones',
      'En el parlamentario no hay partidos políticos',
      'En el presidencial no existe poder legislativo',
      'En el parlamentario los ciudadanos no votan',
    ],
    correcta: 0,
    explicacion: 'El presidente tiene un período fijo y solo sale por juicio; un primer ministro cae con una moción de censura. Eso hace al presidencialismo más estable pero más rígido cuando hay bloqueo entre poderes.',
  },
  {
    id: 'civ-125', tema: 'sistemas-politicos', dificultad: 4,
    enunciado: 'Colombia es una república unitaria descentralizada. Eso significa que:',
    opciones: [
      'Hay un solo ordenamiento jurídico nacional, pero los departamentos y municipios tienen autonomía para administrar sus asuntos',
      'Cada departamento tiene su propia constitución y sus propias leyes',
      'Todas las decisiones se toman en Bogotá sin excepción',
      'Los municipios pueden separarse del país si lo deciden',
    ],
    correcta: 0,
    explicacion: 'En un Estado federal, como Brasil o México, las entidades tienen constituciones y legislaturas propias. En el modelo unitario colombiano la ley es una sola, pero alcaldes y gobernadores se eligen y manejan recursos y competencias propias.',
  },
  {
    id: 'civ-126', tema: 'sistemas-politicos', dificultad: 4,
    enunciado: '¿Qué distingue a un régimen democrático de uno autoritario que también celebra elecciones?',
    opciones: [
      'Que en el democrático las elecciones son competitivas y existen libertades y controles al poder',
      'Que en el democrático siempre gana la oposición',
      'Que el autoritario no tiene constitución escrita',
      'Que en el democrático el voto es obligatorio',
    ],
    correcta: 0,
    explicacion: 'Muchos regímenes autoritarios votan; lo que falta es que la competencia sea real: prensa libre, oposición con opciones de ganar, árbitro electoral independiente y jueces capaces de frenar al gobernante.',
  },
  {
    id: 'civ-127', tema: 'partidos-elecciones', dificultad: 1,
    enunciado: 'En Colombia, el voto es:',
    opciones: ['Un derecho y un deber ciudadano, pero no obligatorio', 'Obligatorio, con multa para quien no vote', 'Un privilegio reservado a los mayores de 25 años', 'Optativo solo en elecciones locales'],
    correcta: 0,
    explicacion: 'La Constitución lo define como derecho y deber, pero no sanciona a quien se abstiene; sí ofrece estímulos a quien vota. En países como Argentina o Brasil sí es obligatorio.',
  },
  {
    id: 'civ-128', tema: 'partidos-elecciones', dificultad: 1,
    enunciado: '¿Cuánto dura el período presidencial en Colombia?',
    opciones: ['Cuatro años, sin reelección inmediata', 'Cinco años, con reelección', 'Seis años, sin reelección', 'Cuatro años, con reelección indefinida'],
    correcta: 0,
    explicacion: 'El período es de cuatro años. La reelección inmediata, permitida entre 2005 y 2015, fue eliminada por un acto legislativo.',
  },
  {
    id: 'civ-129', tema: 'partidos-elecciones', dificultad: 3,
    enunciado: '¿Para qué sirve el umbral electoral en las elecciones de Senado y Cámara?',
    opciones: [
      'Para exigir un mínimo de votos a una lista antes de que pueda acceder a curules',
      'Para limitar cuánto dinero puede gastar una campaña',
      'Para fijar la edad mínima de los candidatos',
      'Para determinar el orden de los nombres en el tarjetón',
    ],
    correcta: 0,
    explicacion: 'El umbral evita la fragmentación extrema del Congreso. Las listas que lo superan entran al reparto de curules, que se hace con la cifra repartidora.',
  },
  {
    id: 'civ-130', tema: 'partidos-elecciones', dificultad: 4,
    enunciado: '¿Cuándo hay segunda vuelta en la elección presidencial colombiana?',
    opciones: [
      'Cuando ningún candidato obtiene más de la mitad de los votos válidos en la primera',
      'Siempre, por mandato constitucional',
      'Cuando la diferencia entre los dos primeros es menor al 5 %',
      'Cuando el voto en blanco supera el 10 %',
    ],
    correcta: 0,
    explicacion: 'La regla busca que el presidente llegue con el respaldo de una mayoría absoluta. Si alguien pasa del 50 % más uno en la primera vuelta, no hay segunda.',
  },
  {
    id: 'civ-131', tema: 'partidos-elecciones', dificultad: 4,
    enunciado: '¿Qué efecto tiene que el voto en blanco obtenga la mayoría de los votos válidos en una elección?',
    opciones: [
      'La elección se repite por una sola vez y los mismos candidatos no pueden presentarse',
      'Gana el candidato que quedó en segundo lugar',
      'El cargo queda vacante durante todo el período',
      'No tiene ningún efecto jurídico',
    ],
    correcta: 0,
    explicacion: 'El voto en blanco es una manifestación política con consecuencias: obliga a repetir la elección con nuevas opciones. Eso lo diferencia del voto nulo o de la abstención, que no producen ningún efecto.',
  },
  {
    id: 'civ-132', tema: 'partidos-elecciones', dificultad: 4,
    enunciado: 'El Senado colombiano se elige en circunscripción nacional y la Cámara de Representantes por departamentos. ¿Qué consecuencia tiene esa diferencia?',
    opciones: [
      'Los senadores responden a electorados dispersos por todo el país y los representantes, a uno territorial concreto',
      'Los senadores solo pueden ser de Bogotá',
      'La Cámara no puede aprobar leyes de alcance nacional',
      'Los representantes duran ocho años en el cargo',
    ],
    correcta: 0,
    explicacion: 'Un senador puede armar su votación sumando apoyos de muchas regiones; un representante depende de su departamento. Eso cambia los incentivos de cada uno a la hora de legislar y de negociar el presupuesto.',
  },
  {
    id: 'civ-133', tema: 'economia-politica', dificultad: 1,
    enunciado: '¿Para qué sirven principalmente los impuestos que recauda el Estado?',
    opciones: [
      'Para financiar bienes y servicios públicos como salud, educación, seguridad e infraestructura',
      'Para aumentar las utilidades de los bancos',
      'Para pagar únicamente los salarios de los congresistas',
      'Para sustituir el ahorro de las familias',
    ],
    correcta: 0,
    explicacion: 'El gasto público se financia sobre todo con impuestos. Sin recaudo no hay colegios, hospitales, vías ni justicia.',
  },
  {
    id: 'civ-134', tema: 'economia-politica', dificultad: 4,
    enunciado: '¿Por qué se dice que el IVA es un impuesto regresivo?',
    opciones: [
      'Porque todos pagan la misma tarifa y eso pesa proporcionalmente más en los ingresos bajos',
      'Porque solo lo pagan las personas de ingresos altos',
      'Porque su tarifa baja cada año',
      'Porque se cobra únicamente sobre los salarios',
    ],
    correcta: 0,
    explicacion: 'Una familia que gasta todo lo que gana destina un porcentaje mayor de su ingreso al IVA que una que ahorra la mitad. El impuesto de renta, con tarifas que suben según el ingreso, funciona al revés: es progresivo.',
  },
  {
    id: 'civ-135', tema: 'economia-politica', dificultad: 4,
    enunciado: 'Cuando el Banco de la República sube su tasa de interés de intervención, lo que busca es:',
    opciones: [
      'Encarecer el crédito, enfriar la demanda y contener la inflación',
      'Aumentar el consumo de los hogares',
      'Devaluar la moneda para exportar más',
      'Financiar directamente el gasto del Gobierno',
    ],
    correcta: 0,
    explicacion: 'Con tasas más altas, endeudarse cuesta más y ahorrar rinde más; eso frena el gasto y presiona los precios a la baja. El costo es un menor crecimiento en el corto plazo, y ese es justamente el dilema de la política monetaria.',
  },
  {
    id: 'civ-136', tema: 'economia-politica', dificultad: 4,
    enunciado: '¿Por qué la Constitución le dio autonomía al Banco de la República frente al Gobierno?',
    opciones: [
      'Para que la política monetaria no se use con fines electorales y la inflación no se dispare',
      'Para que el banco pueda cobrar impuestos',
      'Para que el Gobierno no tenga que rendir cuentas del presupuesto',
      'Para que los bancos privados fijen las tasas de interés',
    ],
    correcta: 0,
    explicacion: 'Un gobierno con control de la emisión tiene la tentación de imprimir dinero antes de unas elecciones, y la factura llega después en forma de inflación. La independencia del banco central es una forma de atarse las manos por anticipado.',
  },
  {
    id: 'civ-137', tema: 'convivencia', dificultad: 1,
    enunciado: '¿Qué es un conflicto?',
    opciones: [
      'Una situación en la que dos partes tienen intereses o necesidades que se oponen',
      'Una agresión física entre dos personas',
      'Un delito tipificado en el código penal',
      'Una discusión que siempre termina mal',
    ],
    correcta: 0,
    explicacion: 'El conflicto es normal en cualquier grupo humano y no es en sí mismo negativo: lo que puede ser destructivo es la forma de tramitarlo.',
  },
  {
    id: 'civ-138', tema: 'convivencia', dificultad: 1,
    enunciado: 'En una mediación, el mediador:',
    opciones: [
      'Es un tercero imparcial que ayuda a las partes a construir su propio acuerdo',
      'Decide quién tiene la razón e impone una solución',
      'Representa a una de las partes',
      'Sanciona a quien causó el conflicto',
    ],
    correcta: 0,
    explicacion: 'La diferencia con un juez o un árbitro es clave: el mediador no falla, facilita. El acuerdo lo construyen las partes y por eso suele cumplirse mejor.',
  },
  {
    id: 'civ-139', tema: 'convivencia', dificultad: 1,
    enunciado: '¿Qué es el manual de convivencia de un colegio?',
    opciones: [
      'El conjunto de normas, derechos y deberes que rigen la vida de la comunidad educativa',
      'El horario de clases del año',
      'La lista de útiles escolares',
      'El reglamento interno de trabajo de los docentes',
    ],
    correcta: 0,
    explicacion: 'Define las reglas del juego y los procedimientos para resolver los conflictos escolares. Debe construirse con participación de la comunidad y respetar los derechos fundamentales de los estudiantes.',
  },
  {
    id: 'civ-140', tema: 'convivencia', dificultad: 3,
    enunciado: '¿Cuál es la diferencia entre conflicto y violencia?',
    opciones: [
      'El conflicto es una diferencia de intereses; la violencia es una forma destructiva de tramitarlo',
      'Son sinónimos en el lenguaje jurídico',
      'La violencia es un conflicto entre países y el conflicto, entre personas',
      'El conflicto siempre se puede evitar y la violencia no',
    ],
    correcta: 0,
    explicacion: 'Eliminar el conflicto es imposible y ni siquiera deseable: de ahí salen los cambios sociales. Lo que sí se puede evitar es que se resuelva con daño, y para eso existen el diálogo, la mediación y las normas.',
  },
  {
    id: 'civ-141', tema: 'convivencia', dificultad: 4,
    enunciado: 'En la negociación colaborativa, la clave para llegar a un acuerdo duradero es:',
    opciones: [
      'Identificar los intereses que están detrás de las posiciones de cada parte',
      'Sostener la posición inicial sin ceder nada',
      'Repartir la diferencia por la mitad siempre',
      'Conseguir que un tercero decida por las partes',
    ],
    correcta: 0,
    explicacion: 'Dos personas pueden pelear por la misma naranja: si se pregunta para qué la quieren, resulta que una necesita el jugo y la otra la cáscara. La posición es lo que se pide; el interés, la razón por la que se pide.',
  },
  {
    id: 'civ-142', tema: 'convivencia', dificultad: 4,
    enunciado: 'Una empresa exige una estatura mínima para un cargo de oficina en el que la estatura no influye. Aunque la regla se aplica a todos, es discriminatoria porque:',
    opciones: [
      'Es una medida aparentemente neutra que perjudica sin justificación a un grupo determinado',
      'Las empresas no pueden poner requisitos a sus empleados',
      'Solo el Estado puede fijar requisitos de contratación',
      'Toda diferencia de trato está prohibida sin excepción',
    ],
    correcta: 0,
    explicacion: 'Es lo que se llama discriminación indirecta: la norma no menciona a nadie en particular, pero su efecto excluye a un grupo y no hay una razón funcional que lo justifique. Un requisito de estatura para bomberos sí podría justificarse; para archivar documentos, no.',
  },
  {
    id: 'civ-143', tema: 'convivencia', dificultad: 4,
    enunciado: 'Frente a un caso de acoso escolar, la ruta de atención prevista en Colombia indica que el colegio debe:',
    opciones: [
      'Activar el comité de convivencia escolar, documentar el caso y remitirlo a las autoridades cuando corresponda',
      'Expulsar de inmediato al agresor sin más trámite',
      'Dejar que las familias lo resuelvan por su cuenta',
      'Esperar a que el caso se repita tres veces antes de actuar',
    ],
    correcta: 0,
    explicacion: 'La Ley 1620 de 2013 creó un sistema con rutas de promoción, prevención, atención y seguimiento. Actuar sin debido proceso o no actuar en absoluto son las dos fallas más frecuentes.',
  },
  {
    id: 'civ-144', tema: 'organismos', dificultad: 3,
    enunciado: '¿Cuál es la función de la Contraloría General de la República?',
    opciones: [
      'Vigilar la gestión fiscal y el uso de los recursos públicos',
      'Defender los derechos humanos ante las autoridades',
      'Investigar disciplinariamente a los funcionarios',
      'Acusar a los delincuentes ante los jueces',
    ],
    correcta: 0,
    explicacion: 'Las tres se confunden con frecuencia: la Contraloría mira la plata, la Procuraduría la conducta disciplinaria de los funcionarios y la Defensoría acompaña a los ciudadanos en la defensa de sus derechos.',
  },
  {
    id: 'civ-145', tema: 'organismos', dificultad: 4,
    enunciado: '¿Por qué el Consejo de Seguridad de la ONU suele quedar bloqueado en crisis internacionales?',
    opciones: [
      'Porque sus cinco miembros permanentes tienen derecho de veto sobre cualquier resolución',
      'Porque necesita la aprobación de los 193 países miembros',
      'Porque sus decisiones deben ser ratificadas por la Corte Internacional de Justicia',
      'Porque solo se reúne una vez al año',
    ],
    correcta: 0,
    explicacion: 'Estados Unidos, Rusia, China, Francia y el Reino Unido pueden hundir una resolución con su solo voto en contra. Ese diseño, heredado de 1945, garantiza que las grandes potencias permanezcan en la organización, pero la paraliza cuando una de ellas es parte del conflicto.',
  },
  {
    id: 'civ-146', tema: 'organismos', dificultad: 4,
    enunciado: 'Para que un caso colombiano llegue a la Corte Interamericana de Derechos Humanos, por regla general:',
    opciones: [
      'Deben haberse agotado los recursos judiciales internos y haber pasado antes por la Comisión Interamericana',
      'Basta con que la víctima presente una demanda directa ante la Corte',
      'Se requiere autorización del Gobierno colombiano',
      'Debe tratarse de un delito cometido fuera del país',
    ],
    correcta: 0,
    explicacion: 'El sistema interamericano es subsidiario: primero debe darse al Estado la oportunidad de reparar por sus propios medios. Además, las personas no demandan directamente ante la Corte; es la Comisión la que somete el caso.',
  },
  {
    id: 'civ-147', tema: 'organismos', dificultad: 4,
    enunciado: '¿Qué caracteriza a la Corte Penal Internacional?',
    opciones: [
      'Juzga a personas por crímenes graves y solo actúa si el Estado no puede o no quiere hacerlo',
      'Juzga a los Estados por incumplir tratados comerciales',
      'Reemplaza a los tribunales nacionales en todos los delitos',
      'Depende del Consejo de Seguridad para cada una de sus sentencias',
    ],
    correcta: 0,
    explicacion: 'Es complementaria, no sustituta: interviene por genocidio, crímenes de guerra, de lesa humanidad y agresión cuando la justicia nacional falla. Juzga individuos; los litigios entre Estados van a la Corte Internacional de Justicia.',
  },
  {
    id: 'civ-148', tema: 'etica-publica', dificultad: 1,
    enunciado: '¿Qué es la corrupción?',
    opciones: [
      'El uso del poder o de un cargo público para obtener un beneficio privado indebido',
      'Cualquier error cometido por un funcionario',
      'La demora en la prestación de un servicio',
      'El desacuerdo entre dos entidades del Estado',
    ],
    correcta: 0,
    explicacion: 'La clave está en el desvío: el cargo se ejerce para provecho propio o de terceros y no para el fin público que lo justifica.',
  },
  {
    id: 'civ-149', tema: 'etica-publica', dificultad: 1,
    enunciado: 'Un funcionario debe declararse impedido cuando:',
    opciones: [
      'Tiene un interés personal o familiar en el asunto que va a decidir',
      'El trámite es complicado',
      'No está de acuerdo con la ley que debe aplicar',
      'El solicitante pertenece a otro partido político',
    ],
    correcta: 0,
    explicacion: 'Es el conflicto de intereses: no hace falta que haya un daño consumado, basta con que su imparcialidad quede comprometida. Declararse impedido protege tanto al ciudadano como al propio funcionario.',
  },
  {
    id: 'civ-150', tema: 'etica-publica', dificultad: 4,
    enunciado: 'Un pliego de condiciones que exige requisitos que solo una empresa puede cumplir es problemático porque:',
    opciones: [
      'Elimina la competencia y convierte una licitación pública en una adjudicación a la medida',
      'Retrasa innecesariamente el contrato',
      'Obliga a la entidad a pagar por anticipado',
      'Impide que el contratista subcontrate',
    ],
    correcta: 0,
    explicacion: 'Es una de las formas más comunes de corrupción en contratación: la apariencia es legal, se publica y se abren sobres, pero el resultado estaba decidido desde la redacción del pliego. Por eso la vigilancia debe empezar antes de la adjudicación.',
  },
  {
    id: 'civ-151', tema: 'etica-publica', dificultad: 4,
    enunciado: '¿Qué consecuencia tiene para la democracia que un candidato compre votos?',
    opciones: [
      'El elegido responde a quien financió la compra y no a los electores, y se deteriora la calidad de la representación',
      'Ninguna, porque el ciudadano vota libremente al final',
      'Solo afecta al candidato, que gasta más dinero',
      'Mejora la participación, porque más gente va a las urnas',
    ],
    correcta: 0,
    explicacion: 'La compra de votos convierte una decisión colectiva en una transacción privada, y el costo se recupera después con contratos o puestos. Además es delito, tanto para quien paga como para quien vende el voto.',
  },
  {
    id: 'civ-152', tema: 'etica-publica', dificultad: 4,
    enunciado: 'Las veedurías ciudadanas y el derecho de petición son herramientas contra la corrupción porque:',
    opciones: [
      'Permiten a cualquier persona pedir información y vigilar cómo se gasta el dinero público',
      'Autorizan a los ciudadanos a sancionar directamente a los funcionarios',
      'Suspenden los contratos mientras se investiga',
      'Reemplazan el trabajo de los órganos de control',
    ],
    correcta: 0,
    explicacion: 'La corrupción necesita opacidad. Obligar a que la información sea pública y verificable no castiga por sí solo, pero es lo que hace posible que los órganos de control y la prensa encuentren algo que investigar.',
  },
];
