/**
 * cotidiana.js — Banco de vida cotidiana y cultura general.
 *
 * Es la parte del examen que no se estudia en ninguna materia y que aparece
 * cada vez más: leer un recibo, comparar dos precios, calcular una dosis,
 * reconocer una estafa, entender un contrato o interpretar un gráfico. Las
 * pruebas la llaman de distintas formas —pensamiento analítico, competencia
 * lectora y matemática aplicada—, pero todas apuntan a lo mismo: usar lo que
 * se sabe en una situación real.
 *
 * Por eso casi ninguna pregunta se responde recordando un dato: hay que hacer
 * la cuenta o razonar la situación.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const COTIDIANA = [
  // ----- Dinero, presupuesto y deudas -----
  {
    id: 'cot-001', tema: 'dinero', dificultad: 1,
    enunciado: 'Un presupuesto personal equilibrado es aquel en el que:',
    opciones: [
      'Los gastos son iguales o menores que los ingresos',
      'Los ingresos y los gastos crecen al mismo ritmo',
      'Se gasta todo lo que se gana cada mes',
      'Se usa el crédito solo para lo indispensable',
    ],
    correcta: 0,
    explicacion: 'Si los gastos superan a los ingresos, la diferencia se cubre con deuda y la deuda cobra intereses. Gastar exactamente todo tampoco es equilibrio: no deja margen para un imprevisto.',
  },
  {
    id: 'cot-002', tema: 'dinero', dificultad: 2,
    enunciado: 'Una persona recibe 1 200 000 al mes, tiene 800 000 de gastos fijos y quiere ahorrar el 10 % de su ingreso. ¿Cuánto le queda para gastos variables?',
    opciones: ['280 000', '400 000', '320 000', '120 000'],
    correcta: 0,
    explicacion: 'El ahorro es 10 % de 1 200 000 = 120 000. Entonces 1 200 000 − 800 000 − 120 000 = 280 000. La clave del método es apartar el ahorro al principio, no con lo que sobre al final.',
  },
  {
    id: 'cot-003', tema: 'dinero', dificultad: 2,
    enunciado: 'Un artículo cuesta 600 000 de contado o 12 cuotas de 60 000. ¿Cuánto se paga de más al financiarlo?',
    opciones: ['120 000, es decir un 20 % más', '60 000, es decir un 10 % más', 'Nada, porque son cuotas sin interés', '720 000 más'],
    correcta: 0,
    explicacion: '12 × 60 000 = 720 000, frente a 600 000 de contado: 120 000 de diferencia, que sobre 600 000 es un 20 %. Cuando se anuncian cuotas, la pregunta útil siempre es cuánto suma el total.',
    pista: 'Multiplica la cuota por el número de cuotas y compara con el precio de contado.',
  },
  {
    id: 'cot-004', tema: 'dinero', dificultad: 2,
    enunciado: 'Una tarjeta de crédito cobra 2 % de interés mensual. Sin considerar la capitalización, ¿a cuánto equivale aproximadamente en un año?',
    opciones: ['24 %', '2 %', '12 %', '6 %'],
    correcta: 0,
    explicacion: '2 % × 12 meses = 24 %. Si además los intereses se capitalizan, la cifra real es todavía mayor. Las tasas mensuales parecen pequeñas justamente porque se leen de a una.',
  },
  {
    id: 'cot-005', tema: 'dinero', dificultad: 2,
    enunciado: 'Un fondo de emergencia es un ahorro disponible que suele recomendarse equivalente a:',
    opciones: [
      'Entre tres y seis meses de gastos básicos',
      'El valor de un mes de salario, como máximo',
      'El 50 % del ingreso anual',
      'Lo que cueste el bien más caro de la casa',
    ],
    correcta: 0,
    explicacion: 'Sirve para que un imprevisto —desempleo, una reparación, una urgencia médica— no se convierta en deuda cara. Debe estar en un lugar de fácil acceso, no invertido a largo plazo.',
  },
  {
    id: 'cot-006', tema: 'dinero', dificultad: 3,
    enunciado: '¿Por qué pagar siempre el mínimo de la tarjeta de crédito resulta caro?',
    opciones: [
      'Porque casi todo el pago cubre intereses, la deuda baja muy poco y se alarga durante años',
      'Porque el banco cobra una multa por pagar el mínimo',
      'Porque el mínimo aumenta cada mes automáticamente',
      'Porque impide seguir usando la tarjeta',
    ],
    correcta: 0,
    explicacion: 'El mínimo está calculado para mantener la deuda viva, no para terminarla. Una compra pequeña pagada así puede terminar costando el doble.',
  },
  {
    id: 'cot-007', tema: 'dinero', dificultad: 2,
    enunciado: 'En finanzas personales, la relación entre riesgo y rentabilidad suele ser:',
    opciones: [
      'A mayor rentabilidad esperada, mayor riesgo de perder parte del dinero',
      'A mayor rentabilidad, menor riesgo',
      'No existe relación entre ambos',
      'El riesgo desaparece si la inversión es a largo plazo',
    ],
    correcta: 0,
    explicacion: 'Nadie paga más por asumir menos riesgo. Por eso una promesa de alta rentabilidad sin riesgo es, casi por definición, una señal de alarma.',
  },
  {
    id: 'cot-008', tema: 'dinero', dificultad: 3,
    enunciado: 'Alguien ofrece una inversión que "garantiza 20 % mensual, sin riesgo, y paga más si traes amigos". ¿Qué indica?',
    opciones: [
      'Es casi con certeza una estafa piramidal: paga a los primeros con el dinero de los nuevos',
      'Es una buena oportunidad si se invierte poco dinero',
      'Es legítima si la empresa tiene oficina y página web',
      'Es legítima porque ofrece garantía por escrito',
    ],
    correcta: 0,
    explicacion: 'Las tres señales juntas son el patrón clásico: rentabilidad imposible, promesa de ausencia de riesgo y premio por reclutar. Oficina, web y contrato son lo más fácil de fabricar.',
  },
  {
    id: 'cot-009', tema: 'dinero', dificultad: 2,
    enunciado: 'Se presta 1 000 000 al 10 % anual de interés simple durante 3 años. ¿Cuánto se paga solo de intereses?',
    opciones: ['300 000', '100 000', '331 000', '1 300 000'],
    correcta: 0,
    explicacion: 'Interés simple: 1 000 000 × 0,10 × 3 = 300 000. Con interés compuesto serían 331 000, porque cada año los intereses también generan intereses.',
  },
  {
    id: 'cot-010', tema: 'dinero', dificultad: 2,
    enunciado: '¿Para qué sirve el historial crediticio de una persona?',
    opciones: [
      'Para que las entidades evalúen si ha cumplido sus pagos antes de prestarle dinero',
      'Para calcular cuántos impuestos debe pagar',
      'Para determinar su salario en un nuevo empleo',
      'Para registrar sus compras de contado',
    ],
    correcta: 0,
    explicacion: 'Un historial limpio abre crédito más barato; uno con moras lo encarece o lo cierra. También hay derecho a conocerlo y a corregir la información errónea.',
  },

  // ----- Compras, precios y consumo -----
  {
    id: 'cot-011', tema: 'compras-precios', dificultad: 2,
    enunciado: 'Un detergente viene en presentación de 1,5 L a 4 500 y de 2 L a 5 600. ¿Cuál conviene más por litro?',
    opciones: [
      'El de 2 L, porque sale a 2 800 por litro frente a 3 000',
      'El de 1,5 L, porque cuesta menos en total',
      'Cuestan lo mismo por litro',
      'No se puede comparar sin saber la marca',
    ],
    correcta: 0,
    explicacion: '4 500 ÷ 1,5 = 3 000 y 5 600 ÷ 2 = 2 800. Comparar precio por unidad es la operación más rentable del supermercado, y casi siempre está impresa en la etiqueta del estante.',
  },
  {
    id: 'cot-012', tema: 'compras-precios', dificultad: 2,
    enunciado: 'Una promoción "lleve 3 y pague 2" equivale a un descuento aproximado de:',
    opciones: ['33 %', '50 %', '66 %', '25 %'],
    correcta: 0,
    explicacion: 'Se pagan 2 de 3, es decir el 66,7 % del precio: el descuento es del 33,3 %. La promoción solo conviene si de verdad se necesitan las tres unidades.',
  },
  {
    id: 'cot-013', tema: 'compras-precios', dificultad: 1,
    enunciado: 'Un producto de 80 000 tiene 30 % de descuento. ¿Cuál es el precio final?',
    opciones: ['56 000', '50 000', '24 000', '60 000'],
    correcta: 0,
    explicacion: 'Se paga el 70 %: 80 000 × 0,70 = 56 000. Calcular directamente lo que se paga evita el paso intermedio de restar el descuento.',
  },
  {
    id: 'cot-014', tema: 'compras-precios', dificultad: 3,
    enunciado: 'Una tienda ofrece 50 % de descuento y, sobre ese precio, un 20 % adicional. ¿Cuál es el descuento total real?',
    opciones: ['60 %', '70 %', '65 %', '50 %'],
    correcta: 0,
    explicacion: 'Los descuentos sucesivos se multiplican: 0,50 × 0,80 = 0,40, así que se paga el 40 % y el descuento total es del 60 %, no del 70 %.',
    pista: 'El segundo descuento se aplica sobre el precio ya rebajado.',
  },
  {
    id: 'cot-015', tema: 'compras-precios', dificultad: 2,
    enunciado: 'Si un electrodoméstico falla dentro del periodo de garantía por un defecto de fábrica, el consumidor tiene derecho a:',
    opciones: [
      'La reparación, el cambio o la devolución del dinero, según el caso y sin costo',
      'Un descuento en la compra de un producto nuevo',
      'Nada, si ya se abrió el empaque',
      'Solo la reparación, pagando la mano de obra',
    ],
    correcta: 0,
    explicacion: 'La garantía legal existe aunque el vendedor no la mencione y no depende de conservar el empaque. Sí conviene guardar la factura como prueba de la fecha de compra.',
  },
  {
    id: 'cot-016', tema: 'compras-precios', dificultad: 1,
    enunciado: '¿Por qué conviene conservar la factura de una compra importante?',
    opciones: [
      'Porque prueba la fecha, el precio y el vendedor, y es lo que permite reclamar la garantía',
      'Porque es obligatorio presentarla en la declaración de renta',
      'Porque sin ella el producto no funciona',
      'Porque permite devolver el producto en cualquier momento',
    ],
    correcta: 0,
    explicacion: 'Sin fecha de compra no hay forma de demostrar que la garantía sigue vigente. Una foto legible del documento suele bastar.',
  },
  {
    id: 'cot-017', tema: 'compras-precios', dificultad: 2,
    enunciado: 'Un aviso muestra "antes 200 000, ahora 150 000", pero el producto nunca se vendió a 200 000. Esa práctica es:',
    opciones: [
      'Publicidad engañosa, porque inventa un precio de referencia que no existió',
      'Legítima, porque el precio final sigue siendo bajo',
      'Un simple error de impresión sin consecuencias',
      'Correcta si el descuento se aplica de verdad',
    ],
    correcta: 0,
    explicacion: 'El precio tachado funciona como ancla: hace parecer ganga lo que es el precio normal. Por eso muchas normativas exigen que el precio anterior haya estado vigente un tiempo mínimo.',
  },
  {
    id: 'cot-018', tema: 'compras-precios', dificultad: 2,
    enunciado: 'Un servicio cuesta 100 000 antes de un impuesto del 19 %. ¿Cuánto se paga en total?',
    opciones: ['119 000', '181 000', '110 000', '119 900'],
    correcta: 0,
    explicacion: '100 000 × 1,19 = 119 000. El camino inverso es distinto: para sacar la base de un precio que ya incluye impuesto se divide entre 1,19, no se resta el 19 %.',
  },
  {
    id: 'cot-019', tema: 'compras-precios', dificultad: 3,
    enunciado: 'En muchas legislaciones, al comprar por internet existe el derecho de retracto, que permite:',
    opciones: [
      'Devolver el producto dentro de un plazo corto sin tener que justificar el motivo',
      'Cambiar el producto solo si llegó defectuoso',
      'Cancelar la compra únicamente antes del despacho',
      'Exigir un descuento si el precio bajó después',
    ],
    correcta: 0,
    explicacion: 'Existe porque en la compra a distancia no se pudo ver ni probar el producto. Suele ser de unos pocos días hábiles desde la entrega y no aplica a bienes personalizados o perecederos.',
  },
  {
    id: 'cot-020', tema: 'compras-precios', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre "fecha de vencimiento" y "consumir preferentemente antes de"?',
    opciones: [
      'La primera marca un límite de seguridad; la segunda se refiere sobre todo a la calidad del producto',
      'Son lo mismo con distinta redacción',
      'La primera es voluntaria y la segunda obligatoria',
      'La segunda indica que el producto ya no se puede vender',
    ],
    correcta: 0,
    explicacion: 'Pasada la fecha de vencimiento el consumo puede ser riesgoso. Pasada la de consumo preferente el alimento suele seguir siendo seguro aunque pierda textura o sabor: confundirlas genera desperdicio.',
  },

  // ----- Documentos, trámites y servicios -----
  {
    id: 'cot-021', tema: 'documentos', dificultad: 1,
    enunciado: 'El documento de identidad sirve principalmente para:',
    opciones: [
      'Acreditar la identidad de una persona ante cualquier autoridad o entidad',
      'Demostrar la dirección de residencia',
      'Comprobar los ingresos de quien lo presenta',
      'Autorizar la salida del país en cualquier caso',
    ],
    correcta: 0,
    explicacion: 'Para salir del país suele hacer falta pasaporte y, si la persona es menor, autorización de los padres. La dirección se acredita con un recibo de servicios.',
  },
  {
    id: 'cot-022', tema: 'documentos', dificultad: 2,
    enunciado: 'Antes de firmar un contrato, lo más importante es:',
    opciones: [
      'Leerlo completo, incluidas las cláusulas en letra pequeña, y pedir copia firmada',
      'Verificar únicamente el monto y la fecha',
      'Confiar en la explicación verbal de quien lo ofrece',
      'Firmar rápido para no perder la oferta',
    ],
    correcta: 0,
    explicacion: 'Lo que obliga es lo escrito, no lo prometido de palabra. La urgencia para firmar es, por sí sola, una señal para desconfiar.',
  },
  {
    id: 'cot-023', tema: 'documentos', dificultad: 2,
    enunciado: 'Según este recibo, ¿cuánta energía se consumió en el periodo?',
    codigo: [
      'RECIBO DE ENERGÍA - periodo: 30 días',
      '',
      'Lectura anterior ............  4 512 kWh',
      'Lectura actual ..............  4 738 kWh',
      'Valor del kWh ...............      780',
    ].join('\n'),
    opciones: ['226 kWh', '4 738 kWh', '9 250 kWh', '780 kWh'],
    correcta: 0,
    explicacion: 'El consumo es la diferencia entre lecturas: 4 738 − 4 512 = 226 kWh. El medidor es acumulativo, así que la lectura actual no es lo que se gastó este mes.',
    pista: 'El medidor no se reinicia cada mes.',
  },
  {
    id: 'cot-024', tema: 'documentos', dificultad: 2,
    enunciado: 'En un comprobante de nómina, la diferencia entre salario bruto y salario neto se explica porque:',
    opciones: [
      'Al bruto se le restan los aportes de ley y otros descuentos autorizados',
      'El neto incluye las horas extra y el bruto no',
      'El bruto es lo que se recibe y el neto lo que se declara',
      'El neto es siempre mayor que el bruto',
    ],
    correcta: 0,
    explicacion: 'Salud, pensión, impuestos y descuentos acordados salen del bruto. Al negociar un sueldo conviene aclarar de cuál de los dos se está hablando.',
  },
  {
    id: 'cot-025', tema: 'documentos', dificultad: 2,
    enunciado: 'Una copia autenticada de un documento es aquella que:',
    opciones: [
      'Un funcionario autorizado certifica que corresponde fielmente al original',
      'Se imprime en papel de seguridad',
      'Está firmada por el interesado',
      'Se obtiene en cualquier fotocopiadora',
    ],
    correcta: 0,
    explicacion: 'Lo que da valor no es el papel, sino la certificación de quien tiene fe pública, normalmente un notario. Una fotocopia simple no acredita nada por sí sola.',
  },
  {
    id: 'cot-026', tema: 'documentos', dificultad: 3,
    enunciado: '¿Por qué nunca se debe firmar un documento con espacios en blanco?',
    opciones: [
      'Porque quien lo reciba puede completarlo después con condiciones distintas y la firma seguirá siendo válida',
      'Porque el documento pierde validez legal',
      'Porque no se podría fotocopiar correctamente',
      'Porque obliga a firmar de nuevo ante notario',
    ],
    correcta: 0,
    explicacion: 'La firma avala todo lo que aparezca en el documento, se haya escrito antes o después. Lo prudente es tachar los espacios vacíos antes de firmar y quedarse con una copia.',
  },
  {
    id: 'cot-027', tema: 'documentos', dificultad: 2,
    enunciado: 'Ante un mal servicio de una empresa, el reclamo formal por escrito es preferible a la queja verbal porque:',
    opciones: [
      'Deja constancia de la fecha y del contenido, y obliga a una respuesta que se puede exigir después',
      'Se resuelve siempre más rápido',
      'Evita tener que dar datos personales',
      'Impide que la empresa cobre el servicio',
    ],
    correcta: 0,
    explicacion: 'Sin radicado ni fecha no hay forma de demostrar que se reclamó. Ese registro es lo que permite escalar el caso a la autoridad de protección al consumidor.',
  },
  {
    id: 'cot-028', tema: 'documentos', dificultad: 2,
    enunciado: 'En un seguro, el deducible es:',
    opciones: [
      'La parte del daño que asume el asegurado antes de que la aseguradora pague el resto',
      'El valor total que paga la aseguradora',
      'La cuota mensual del seguro',
      'El descuento por no haber tenido siniestros',
    ],
    correcta: 0,
    explicacion: 'Un deducible alto abarata la prima y encarece cada siniestro; uno bajo hace lo contrario. Por eso comparar seguros solo por el precio mensual es insuficiente.',
  },
  {
    id: 'cot-029', tema: 'documentos', dificultad: 1,
    enunciado: 'Después de pagar una deuda o un servicio, lo recomendable es:',
    opciones: [
      'Conservar el comprobante hasta confirmar que el pago quedó aplicado',
      'Desecharlo de inmediato para no acumular papeles',
      'Guardarlo solo si el pago fue en efectivo',
      'Anotar el valor y botar el comprobante',
    ],
    correcta: 0,
    explicacion: 'Los errores de aplicación de pagos existen, y la carga de probar que se pagó recae en quien pagó. Un comprobante fotografiado ocupa menos que un cobro indebido.',
  },
  {
    id: 'cot-030', tema: 'documentos', dificultad: 3,
    enunciado: 'Un trámite tiene un plazo máximo de 15 días hábiles para presentar documentos. Eso significa que:',
    opciones: [
      'No se cuentan sábados, domingos ni festivos, así que el plazo real en el calendario es mayor',
      'Se cuentan todos los días seguidos desde el inicio',
      'El plazo empieza a correr el mismo día de la notificación',
      'Se pueden pedir prórrogas indefinidas',
    ],
    correcta: 0,
    explicacion: 'Días hábiles y días calendario no son lo mismo, y confundirlos hace perder plazos. La regla general es que el conteo arranca al día siguiente de la notificación.',
  },

  // ----- Medidas, dosis y conversiones -----
  {
    id: 'cot-031', tema: 'medidas', dificultad: 1,
    enunciado: 'Una receta pide 2,5 kg de harina. ¿A cuántos gramos equivalen?',
    opciones: ['2 500 g', '250 g', '25 000 g', '2,5 g'],
    correcta: 0,
    explicacion: '1 kg = 1 000 g, así que 2,5 × 1 000 = 2 500 g. El prefijo kilo siempre significa mil.',
  },
  {
    id: 'cot-032', tema: 'medidas', dificultad: 2,
    enunciado: 'Un jarabe se toma en dosis de 5 mL, tres veces al día, durante 7 días. ¿Qué frasco alcanza justo para el tratamiento?',
    opciones: ['Uno de 105 mL', 'Uno de 35 mL', 'Uno de 60 mL', 'Uno de 150 mL'],
    correcta: 0,
    explicacion: '5 mL × 3 veces = 15 mL diarios; 15 × 7 = 105 mL. Calcularlo antes evita quedarse sin medicamento a mitad del tratamiento, que es cuando aparecen las recaídas.',
  },
  {
    id: 'cot-033', tema: 'medidas', dificultad: 2,
    enunciado: 'Una receta para 4 personas lleva 300 g de arroz. ¿Cuánto se necesita para 6 personas?',
    opciones: ['450 g', '400 g', '500 g', '600 g'],
    correcta: 0,
    explicacion: 'Regla de tres directa: 300 ÷ 4 = 75 g por persona, y 75 × 6 = 450 g.',
  },
  {
    id: 'cot-034', tema: 'medidas', dificultad: 3,
    enunciado: 'Un termómetro marca 98,6 °F. Usando °C = (°F − 32) × 5/9, ¿cuál es la temperatura en grados Celsius?',
    opciones: ['37 °C', '36 °C', '39 °C', '66,6 °C'],
    correcta: 0,
    explicacion: '(98,6 − 32) × 5/9 = 66,6 × 5/9 = 37 °C, la temperatura corporal normal. El error frecuente es restar 32 y olvidar multiplicar por 5/9.',
  },
  {
    id: 'cot-035', tema: 'medidas', dificultad: 2,
    enunciado: 'Un viaje de 240 km se hace a una velocidad promedio de 80 km/h. ¿Cuánto tarda?',
    opciones: ['3 horas', '2 horas', '4 horas', '3 horas y 20 minutos'],
    correcta: 0,
    explicacion: 'Tiempo = distancia ÷ velocidad = 240 ÷ 80 = 3 horas. El promedio ya incluye los cambios de ritmo del recorrido.',
  },
  {
    id: 'cot-036', tema: 'medidas', dificultad: 2,
    enunciado: 'Un evento comienza a las 14:45 y termina a las 17:20. ¿Cuánto dura?',
    opciones: ['2 horas y 35 minutos', '3 horas y 35 minutos', '2 horas y 75 minutos', '2 horas y 25 minutos'],
    correcta: 0,
    explicacion: 'De 14:45 a 17:45 habría 3 horas, pero termina 25 minutos antes: 3 h − 25 min = 2 h 35 min. Con el tiempo hay que restar en base 60, no en base 10.',
  },
  {
    id: 'cot-037', tema: 'medidas', dificultad: 3,
    enunciado: 'Un medicamento se dosifica a 10 mg por kilogramo de peso. ¿Qué dosis corresponde a una persona de 25 kg?',
    opciones: ['250 mg', '25 mg', '10 mg', '2 500 mg'],
    correcta: 0,
    explicacion: '10 × 25 = 250 mg. Las dosis por peso son la regla en pediatría, y es donde más errores de cálculo se cometen: conviene verificarlas dos veces.',
  },
  {
    id: 'cot-038', tema: 'medidas', dificultad: 2,
    enunciado: 'Un galón de pintura rinde 30 m². Para pintar 45 m² se necesita:',
    opciones: ['2 galones, porque uno no alcanza', '1 galón', '3 galones', '1,5 galones que se venden fraccionados'],
    correcta: 0,
    explicacion: '45 ÷ 30 = 1,5 galones, pero la pintura se vende en unidades enteras: hay que comprar 2. En problemas de reparto siempre conviene preguntarse si el resultado admite fracciones.',
  },
  {
    id: 'cot-039', tema: 'medidas', dificultad: 2,
    enunciado: 'Un tanque de 500 litros se llena con una manguera que entrega 20 litros por minuto. ¿En cuánto tiempo se llena?',
    opciones: ['25 minutos', '20 minutos', '50 minutos', '10 minutos'],
    correcta: 0,
    explicacion: '500 ÷ 20 = 25 minutos. Es la misma estructura que un problema de velocidad: cantidad total dividida entre la cantidad por unidad de tiempo.',
  },
  {
    id: 'cot-040', tema: 'medidas', dificultad: 3,
    enunciado: 'Un plan de datos trae 10 GB al mes. Al día 20 de un mes de 30 días se llevan consumidos 6,5 GB. Si el ritmo se mantiene:',
    opciones: [
      'Alcanzará, porque el consumo proyectado es de unos 9,75 GB',
      'No alcanzará, porque se superarán los 10 GB',
      'Se agotará justo el último día',
      'No se puede estimar sin saber el consumo diario exacto',
    ],
    correcta: 0,
    explicacion: '6,5 ÷ 20 = 0,325 GB por día, y 0,325 × 30 = 9,75 GB. Proyectar con una regla de tres es lo mismo que se hace para estimar un presupuesto a fin de mes.',
  },

  // ----- Tecnología y seguridad digital -----
  {
    id: 'cot-041', tema: 'tecnologia', dificultad: 1,
    enunciado: '¿Cuál de estas es la mejor contraseña?',
    opciones: [
      'Una frase larga y poco predecible, distinta para cada servicio',
      'El nombre y el año de nacimiento',
      'Una palabra corta con símbolos al final, usada en todos los sitios',
      'La misma clave del correo, para no olvidarla',
    ],
    correcta: 0,
    explicacion: 'La longitud importa más que los símbolos raros, y reutilizar claves es el mayor riesgo: si se filtra un servicio, se abren todos los demás. Un gestor de contraseñas resuelve el problema de recordarlas.',
  },
  {
    id: 'cot-042', tema: 'tecnologia', dificultad: 2,
    enunciado: 'Llega un correo del "banco" pidiendo confirmar la clave en un enlace porque la cuenta será bloqueada hoy. ¿Qué es?',
    opciones: [
      'Un intento de phishing: ningún banco pide claves por correo ni por enlace',
      'Una notificación legítima que conviene atender rápido',
      'Un error del sistema del banco',
      'Publicidad molesta pero inofensiva',
    ],
    correcta: 0,
    explicacion: 'El patrón siempre es el mismo: urgencia, amenaza y un enlace. Lo correcto es no hacer clic y entrar al banco por la aplicación oficial o escribiendo la dirección a mano.',
  },
  {
    id: 'cot-043', tema: 'tecnologia', dificultad: 2,
    enunciado: 'La verificación en dos pasos protege una cuenta porque:',
    opciones: [
      'Aunque alguien obtenga la contraseña, necesita además un segundo factor que está en tu poder',
      'Cambia la contraseña automáticamente cada mes',
      'Impide que la cuenta se abra desde otro país',
      'Cifra todos los archivos del dispositivo',
    ],
    correcta: 0,
    explicacion: 'Es la medida que más riesgo elimina por el menor esfuerzo. Conviene activarla al menos en el correo, porque desde ahí se recuperan todas las demás cuentas.',
  },
  {
    id: 'cot-044', tema: 'tecnologia', dificultad: 2,
    enunciado: 'En una red wifi pública y abierta, lo recomendable es:',
    opciones: [
      'Evitar operaciones bancarias y compras, o usarlas solo con datos móviles',
      'Usarla con normalidad si tiene el nombre del establecimiento',
      'Desactivar la pantalla de bloqueo para navegar más rápido',
      'Compartir la conexión con otros dispositivos',
    ],
    correcta: 0,
    explicacion: 'En una red abierta cualquiera puede interceptar tráfico o montar una red falsa con el nombre del café. Para lo sensible, mejor los datos móviles.',
  },
  {
    id: 'cot-045', tema: 'tecnologia', dificultad: 2,
    enunciado: 'La regla más citada para respaldar archivos importantes recomienda:',
    opciones: [
      'Tener varias copias, en al menos dos medios distintos y una de ellas fuera del lugar',
      'Guardar todo en el mismo disco pero en carpetas distintas',
      'Confiar en que el dispositivo no falle',
      'Imprimir los archivos en papel',
    ],
    correcta: 0,
    explicacion: 'Un robo, un incendio o un daño del disco se llevan todo lo que esté en el mismo sitio. Una copia en la nube o en un disco externo guardado en otro lugar cubre ese escenario.',
  },
  {
    id: 'cot-046', tema: 'tecnologia', dificultad: 3,
    enunciado: 'Un mensaje avisa que ganaste un premio en un sorteo en el que nunca participaste y pide un pago para "liberarlo". ¿Qué indica?',
    opciones: [
      'Es una estafa: ningún premio legítimo exige pagar por adelantado para reclamarlo',
      'Es legítimo si el pago es pequeño',
      'Es legítimo si el mensaje llega por un canal oficial',
      'Conviene responder para verificar si es real',
    ],
    correcta: 0,
    explicacion: 'El pago por adelantado es el objetivo de la estafa, no un requisito administrativo. Responder solo confirma que el número está activo y atrae más intentos.',
  },
  {
    id: 'cot-047', tema: 'tecnologia', dificultad: 2,
    enunciado: 'Al instalar una aplicación conviene revisar los permisos que pide porque:',
    opciones: [
      'Una app puede solicitar acceso a datos que no necesita para funcionar, como contactos o ubicación',
      'Los permisos determinan cuánta batería consume',
      'Sin permisos la aplicación no se puede desinstalar',
      'Los permisos definen el precio de la aplicación',
    ],
    correcta: 0,
    explicacion: 'Una linterna que pide acceso a los contactos y a la ubicación no los necesita para alumbrar: los quiere para otra cosa. Los permisos se pueden revocar después desde los ajustes.',
  },
  {
    id: 'cot-048', tema: 'tecnologia', dificultad: 2,
    enunciado: 'La llamada huella digital que dejamos en internet implica que:',
    opciones: [
      'Lo publicado puede permanecer y ser encontrado años después, aunque se borre el original',
      'Todo contenido se elimina definitivamente al borrarlo',
      'Solo queda registro si la cuenta es pública',
      'Las capturas de pantalla no tienen valor',
    ],
    correcta: 0,
    explicacion: 'Copias, capturas y caché sobreviven al borrado. Es la razón práctica para pensar antes de publicar, sobre todo en procesos de admisión o selección laboral.',
  },
  {
    id: 'cot-049', tema: 'tecnologia', dificultad: 3,
    enunciado: 'Alguien llama diciendo ser del banco y pide el código de seis dígitos que acaba de llegarte por mensaje. ¿Qué corresponde hacer?',
    opciones: [
      'No entregarlo y colgar: ese código es de un solo uso y ninguna entidad legítima lo pide',
      'Entregarlo si la persona conoce tu nombre y número de cuenta',
      'Entregarlo solo si la llamada viene del número oficial del banco',
      'Reenviarlo por escrito para dejar constancia',
    ],
    correcta: 0,
    explicacion: 'Ese código es justamente lo que le falta al estafador para completar la operación. Los datos personales se consiguen fácil y el número que aparece en pantalla se puede falsificar.',
  },
  {
    id: 'cot-050', tema: 'tecnologia', dificultad: 2,
    enunciado: '¿Por qué conviene instalar las actualizaciones del sistema y de las aplicaciones?',
    opciones: [
      'Porque suelen corregir fallos de seguridad ya conocidos y explotados por atacantes',
      'Porque hacen el dispositivo más rápido siempre',
      'Porque liberan espacio de almacenamiento',
      'Porque son obligatorias por ley',
    ],
    correcta: 0,
    explicacion: 'Cuando se publica una actualización de seguridad, la vulnerabilidad se hace pública: quedarse sin actualizar deja la puerta abierta y señalizada.',
  },

  // ----- Evaluar información y noticias -----
  {
    id: 'cot-051', tema: 'informacion', dificultad: 2,
    enunciado: 'Llega por mensajería una noticia alarmante sin fecha ni autor. ¿Cuál es el primer paso para verificarla?',
    opciones: [
      'Buscar si medios reconocidos la reportan y rastrear la fuente original',
      'Reenviarla pidiendo a otros que la confirmen',
      'Fijarse en si tiene faltas de ortografía',
      'Contar cuántas personas ya la compartieron',
    ],
    correcta: 0,
    explicacion: 'La ausencia de fecha, autor y medio es la primera señal. Reenviar para consultar amplifica el rumor aunque la intención sea verificarlo.',
  },
  {
    id: 'cot-052', tema: 'informacion', dificultad: 2,
    enunciado: 'Un titular afirma algo mucho más rotundo que el contenido de la nota. Eso suele indicar que:',
    opciones: [
      'El titular busca atraer clics y no resume fielmente la información',
      'La nota fue editada después de publicarse',
      'El periodista no leyó su propia nota',
      'La información es falsa en su totalidad',
    ],
    correcta: 0,
    explicacion: 'El titular se escribe para competir por atención y con frecuencia lo escribe otra persona. Leer solo titulares es la forma más rápida de formarse una idea equivocada.',
  },
  {
    id: 'cot-053', tema: 'informacion', dificultad: 3,
    enunciado: 'Un estudio encuentra que los barrios con más heladerías tienen más robos. ¿Qué conclusión es válida?',
    opciones: [
      'Que ambas cosas podrían depender de un tercer factor, como la densidad de población',
      'Que las heladerías atraen delincuencia',
      'Que cerrar heladerías reduciría los robos',
      'Que los robos hacen que abran más heladerías',
    ],
    correcta: 0,
    explicacion: 'Donde hay más gente hay más de todo: más comercios y más delitos. Confundir correlación con causa es el error más explotado en titulares y en publicidad.',
    pista: 'Pregúntate si algo más podría estar causando las dos cosas a la vez.',
  },
  {
    id: 'cot-054', tema: 'informacion', dificultad: 2,
    enunciado: 'Una encuesta abierta en redes sociales concluye que el 80 % de la población apoya una medida. ¿Por qué no es confiable?',
    opciones: [
      'Porque responde quien quiere, y sus seguidores no representan al conjunto de la población',
      'Porque el número de respuestas siempre es pequeño',
      'Porque las redes sociales no permiten contar votos',
      'Porque las encuestas solo valen si las hace el gobierno',
    ],
    correcta: 0,
    explicacion: 'Es un problema de muestra autoseleccionada: refleja a quien sigue esa cuenta y decidió responder. Una encuesta seria define la muestra antes, no después.',
  },
  {
    id: 'cot-055', tema: 'informacion', dificultad: 3,
    enunciado: 'Un gráfico de barras empieza el eje vertical en 95 en lugar de en 0. ¿Qué efecto produce?',
    opciones: [
      'Exagera visualmente diferencias que en realidad son pequeñas',
      'Hace que las diferencias parezcan menores',
      'No altera la lectura si los datos son correctos',
      'Solo afecta a los gráficos de líneas',
    ],
    correcta: 0,
    explicacion: 'Una diferencia de 96 a 98 se ve como si una barra doblara a la otra. El dato no es falso, pero la imagen sí engaña: siempre conviene mirar dónde empieza el eje.',
  },
  {
    id: 'cot-056', tema: 'informacion', dificultad: 2,
    enunciado: 'Que un mensaje haya sido reenviado miles de veces indica:',
    opciones: [
      'Solo que circuló mucho, no que sea cierto',
      'Que fue verificado por muchas personas',
      'Que proviene de una fuente confiable',
      'Que es un tema de interés público comprobado',
    ],
    correcta: 0,
    explicacion: 'Lo que más se reenvía suele ser lo que más indigna o asusta, no lo más verificado. La difusión mide emoción, no veracidad.',
  },
  {
    id: 'cot-057', tema: 'informacion', dificultad: 2,
    enunciado: 'Circula una foto real acompañada de un texto sobre un hecho ocurrido en otro país y en otro año. Esa técnica se llama:',
    opciones: [
      'Descontextualización: material auténtico usado para respaldar una afirmación falsa',
      'Montaje digital',
      'Fuente secundaria',
      'Cita indirecta',
    ],
    correcta: 0,
    explicacion: 'Es más eficaz que una imagen falsa, porque resiste cualquier análisis técnico: la foto es real. Una búsqueda inversa de imagen suele revelar su origen.',
  },
  {
    id: 'cot-058', tema: 'informacion', dificultad: 3,
    enunciado: 'Un titular dice que una enfermedad "duplicó sus casos, con un aumento del 100 %". En el texto se lee que pasó de 2 a 4 casos. ¿Qué conviene notar?',
    opciones: [
      'Que el porcentaje es correcto pero irrelevante: las cifras absolutas son muy pequeñas',
      'Que el porcentaje está mal calculado',
      'Que el aumento fue del 200 %',
      'Que los datos no permiten calcular ningún porcentaje',
    ],
    correcta: 0,
    explicacion: 'Los porcentajes sobre bases minúsculas producen titulares espectaculares. La pregunta que ordena la lectura es siempre: ¿cuántos casos son, de cuántos?',
  },
  {
    id: 'cot-059', tema: 'informacion', dificultad: 2,
    enunciado: 'El sesgo de confirmación consiste en:',
    opciones: [
      'Buscar y creer con más facilidad la información que coincide con lo que ya se pensaba',
      'Confirmar una noticia con una segunda fuente',
      'Repetir una información hasta que se vuelve creíble',
      'Publicar solo noticias positivas',
    ],
    correcta: 0,
    explicacion: 'Es el motivo por el que dos personas leen el mismo dato y cada una se reafirma en su postura. La contramedida práctica es buscar deliberadamente el mejor argumento contrario.',
  },
  {
    id: 'cot-060', tema: 'informacion', dificultad: 2,
    enunciado: 'Una fuente primaria es:',
    opciones: [
      'El documento o testimonio original: el estudio, la ley, la grabación',
      'El medio de comunicación más leído del país',
      'La primera nota que se publicó sobre el tema',
      'La versión resumida y explicada por un experto',
    ],
    correcta: 0,
    explicacion: 'Las notas y los resúmenes son fuentes secundarias y pueden introducir errores. Cuando algo importa de verdad, vale la pena ir al documento original.',
  },

  // ----- Seguridad vial y prevención -----
  {
    id: 'cot-061', tema: 'seguridad', dificultad: 1,
    enunciado: 'El cinturón de seguridad debe usarse:',
    opciones: [
      'En todos los asientos del vehículo, adelante y atrás, en cualquier trayecto',
      'Solo en los asientos delanteros',
      'Solo en carretera, no dentro de la ciudad',
      'Solo cuando se supera cierta velocidad',
    ],
    correcta: 0,
    explicacion: 'La mayoría de los accidentes graves ocurre cerca de casa y a velocidades moderadas. Un pasajero trasero sin cinturón sale despedido y puede lesionar además a quien va adelante.',
  },
  {
    id: 'cot-062', tema: 'seguridad', dificultad: 1,
    enunciado: 'El casco en moto y bicicleta reduce principalmente el riesgo de:',
    opciones: [
      'Traumatismo craneoencefálico, la lesión que más muertes causa en estos siniestros',
      'Fracturas de brazos y piernas',
      'Lesiones de columna lumbar',
      'Quemaduras por el motor',
    ],
    correcta: 0,
    explicacion: 'Debe estar bien ajustado y certificado: uno suelto sale despedido en el impacto y no protege.',
  },
  {
    id: 'cot-063', tema: 'seguridad', dificultad: 3,
    enunciado: 'Al duplicar la velocidad de un vehículo, la distancia necesaria para detenerlo:',
    opciones: [
      'Se multiplica aproximadamente por cuatro, porque la energía crece con el cuadrado de la velocidad',
      'Se duplica exactamente',
      'Se mantiene igual si los frenos están en buen estado',
      'Aumenta solo un poco',
    ],
    correcta: 0,
    explicacion: 'A la distancia de frenado hay que sumar la de reacción, que sí crece proporcionalmente. Por eso un pequeño exceso de velocidad cambia tanto el desenlace de un atropello.',
  },
  {
    id: 'cot-064', tema: 'seguridad', dificultad: 2,
    enunciado: 'El alcohol afecta la conducción porque:',
    opciones: [
      'Alarga el tiempo de reacción y reduce la coordinación y la percepción del riesgo',
      'Produce sueño solo después de varias horas',
      'Afecta la visión pero no los reflejos',
      'Solo es peligroso en cantidades muy altas',
    ],
    correcta: 0,
    explicacion: 'El deterioro empieza con dosis bajas y, además, la persona se siente más capaz de lo que está: esa falsa seguridad es parte del riesgo.',
  },
  {
    id: 'cot-065', tema: 'seguridad', dificultad: 2,
    enunciado: 'Usar el celular mientras se conduce es peligroso incluso con manos libres porque:',
    opciones: [
      'La distracción principal es de atención, no solo de manos',
      'La señal del teléfono interfiere con el vehículo',
      'Obliga a mirar la pantalla en todo momento',
      'Solo es riesgoso si se escriben mensajes',
    ],
    correcta: 0,
    explicacion: 'Se puede mirar la vía sin ver lo que ocurre en ella: la atención está en la conversación. Es lo que se conoce como ceguera por falta de atención.',
  },
  {
    id: 'cot-066', tema: 'seguridad', dificultad: 2,
    enunciado: 'Como peatón, lo más seguro al cruzar una calle es:',
    opciones: [
      'Cruzar por la esquina o el paso peatonal, mirando a ambos lados y sin usar el celular',
      'Cruzar por donde el trayecto sea más corto',
      'Cruzar corriendo para exponerse menos tiempo',
      'Confiar en que los vehículos cederán el paso',
    ],
    correcta: 0,
    explicacion: 'Los conductores esperan peatones en los cruces, no a mitad de cuadra. Correr, además, aumenta el riesgo de caída y reduce el tiempo para ver lo que viene.',
  },
  {
    id: 'cot-067', tema: 'seguridad', dificultad: 2,
    enunciado: 'En señalización vial, una señal octagonal de fondo rojo indica:',
    opciones: ['Pare', 'Ceda el paso', 'Prohibido girar', 'Zona escolar'],
    correcta: 0,
    explicacion: 'La forma y el color comunican antes que el texto: el octágono rojo es universal para detenerse, y el triángulo invertido significa ceda el paso.',
  },
  {
    id: 'cot-068', tema: 'seguridad', dificultad: 2,
    enunciado: '¿Cuál es una medida básica de prevención de accidentes domésticos con niños pequeños?',
    opciones: [
      'Guardar medicamentos y productos de limpieza fuera de su alcance y en su envase original',
      'Dejar los productos en botellas de bebidas para identificarlos mejor',
      'Guardar todo en el mueble más bajo para tenerlo a mano',
      'Explicarles que no deben tocarlos y dejarlos accesibles',
    ],
    correcta: 0,
    explicacion: 'Trasvasar un producto a una botella de gaseosa es una de las causas más frecuentes de intoxicación infantil. El envase original además trae las instrucciones en caso de accidente.',
  },
  {
    id: 'cot-069', tema: 'seguridad', dificultad: 3,
    enunciado: 'Durante un sismo, estando dentro de un edificio, lo recomendado es:',
    opciones: [
      'Protegerse bajo una estructura resistente lejos de ventanas y evacuar cuando cese el movimiento',
      'Correr de inmediato hacia las escaleras',
      'Usar el ascensor para bajar rápido',
      'Salir al balcón para pedir ayuda',
    ],
    correcta: 0,
    explicacion: 'La mayoría de las lesiones se produce por caída de objetos y por correr durante el movimiento. El ascensor puede quedar detenido y las escaleras se congestionan.',
  },
  {
    id: 'cot-070', tema: 'seguridad', dificultad: 2,
    enunciado: 'Conocer de antemano la ruta de evacuación y el punto de encuentro de un lugar sirve para:',
    opciones: [
      'Actuar rápido y ordenadamente cuando no hay tiempo de pensar ni visibilidad',
      'Cumplir un requisito legal del edificio',
      'Evitar que ocurran emergencias',
      'Saber dónde están los extintores únicamente',
    ],
    correcta: 0,
    explicacion: 'En una emergencia real hay humo, ruido y prisa: solo se ejecuta lo que ya se sabía. Por eso los simulacros se hacen antes y no durante.',
  },

  // ----- Consumo responsable en casa -----
  {
    id: 'cot-071', tema: 'ambiente-hogar', dificultad: 1,
    enunciado: 'Separar los residuos en el hogar sirve principalmente para:',
    opciones: [
      'Permitir que los materiales aprovechables se reciclen en lugar de terminar en el relleno sanitario',
      'Reducir el volumen total de basura generada',
      'Evitar que la basura huela mal',
      'Cumplir con el reglamento del edificio',
    ],
    correcta: 0,
    explicacion: 'Un material aprovechable contaminado con residuos orgánicos suele perder su valor y ya no se recicla. Separar en origen es lo que hace viable todo el proceso.',
  },
  {
    id: 'cot-072', tema: 'ambiente-hogar', dificultad: 2,
    enunciado: 'En la regla de las tres erres, el orden reducir, reutilizar y reciclar importa porque:',
    opciones: [
      'Lo más efectivo es no generar el residuo; reciclar es la última opción, no la primera',
      'Es simplemente un orden alfabético',
      'Reciclar es imposible sin reutilizar antes',
      'Reducir solo aplica a las empresas',
    ],
    correcta: 0,
    explicacion: 'Reciclar consume energía, agua y transporte. El residuo con menor impacto es el que nunca existió.',
  },
  {
    id: 'cot-073', tema: 'ambiente-hogar', dificultad: 2,
    enunciado: 'Las pilas y los aparatos electrónicos no deben ir a la basura común porque:',
    opciones: [
      'Contienen metales pesados que contaminan el suelo y el agua',
      'Ocupan demasiado espacio en el camión recolector',
      'Pueden encenderse solos en el relleno',
      'Son difíciles de compactar',
    ],
    correcta: 0,
    explicacion: 'Plomo, mercurio y cadmio se filtran y permanecen en el ambiente. Por eso existen puntos de recolección específicos para residuos peligrosos.',
  },
  {
    id: 'cot-074', tema: 'ambiente-hogar', dificultad: 2,
    enunciado: 'Un aparato de 1 000 W funciona 3 horas. ¿Cuánta energía consume?',
    opciones: ['3 kWh', '3 000 kWh', '1 kWh', '0,3 kWh'],
    correcta: 0,
    explicacion: '1 000 W = 1 kW, y 1 kW × 3 h = 3 kWh. El recibo se cobra por kilovatios hora, así que multiplicar por la tarifa da el costo exacto de usarlo.',
  },
  {
    id: 'cot-075', tema: 'ambiente-hogar', dificultad: 2,
    enunciado: 'Dejar aparatos en modo de espera (standby) o cargadores conectados sin uso:',
    opciones: [
      'Consume una pequeña cantidad de energía de forma continua, que suma a lo largo del mes',
      'No consume absolutamente nada',
      'Consume lo mismo que si estuvieran encendidos',
      'Daña el aparato pero no gasta energía',
    ],
    correcta: 0,
    explicacion: 'Es el llamado consumo fantasma. Cada aparato gasta poco, pero sumados y multiplicados por 24 horas explican una parte apreciable del recibo.',
  },
  {
    id: 'cot-076', tema: 'ambiente-hogar', dificultad: 3,
    enunciado: 'Una llave que gotea una vez por segundo desperdicia cerca de 30 litros al día. En un mes eso equivale aproximadamente a:',
    opciones: ['900 litros', '90 litros', '300 litros', '30 litros'],
    correcta: 0,
    explicacion: '30 × 30 = 900 litros, casi un metro cúbico por una sola llave. Los desperdicios pequeños y continuos suelen superar a los grandes y esporádicos.',
  },
  {
    id: 'cot-077', tema: 'ambiente-hogar', dificultad: 2,
    enunciado: 'El aceite de cocina usado no debe verterse por el desagüe porque:',
    opciones: [
      'Contamina grandes volúmenes de agua y obstruye las tuberías y el alcantarillado',
      'Daña la cerámica del lavaplatos',
      'Se solidifica y genera mal olor únicamente',
      'Atrae insectos a la vivienda',
    ],
    correcta: 0,
    explicacion: 'Un litro de aceite puede contaminar miles de litros de agua y forma tapones de grasa en la red. Lo correcto es envasarlo y llevarlo a un punto de recolección.',
  },
  {
    id: 'cot-078', tema: 'ambiente-hogar', dificultad: 2,
    enunciado: 'El compostaje doméstico consiste en:',
    opciones: [
      'Transformar residuos orgánicos en abono mediante descomposición controlada',
      'Quemar los residuos del jardín',
      'Enterrar la basura en el patio',
      'Separar el plástico del vidrio',
    ],
    correcta: 0,
    explicacion: 'Los residuos orgánicos son cerca de la mitad de la basura doméstica. Compostarlos reduce el volumen enviado al relleno y evita emisiones de metano.',
  },
  {
    id: 'cot-079', tema: 'ambiente-hogar', dificultad: 3,
    enunciado: 'Una bolsa reutilizable de tela tiene mayor impacto ambiental por unidad que una bolsa plástica. ¿Cuándo resulta preferible?',
    opciones: [
      'Cuando se usa muchas veces, de modo que su impacto se reparte entre todos esos usos',
      'Siempre, porque no es de plástico',
      'Nunca, porque su fabricación contamina más',
      'Solo si es de algodón orgánico',
    ],
    correcta: 0,
    explicacion: 'Lo que decide es el número de usos, no el material. Una bolsa de tela comprada y olvidada en un cajón es peor que la plástica que habría reemplazado.',
  },
  {
    id: 'cot-080', tema: 'ambiente-hogar', dificultad: 2,
    enunciado: 'La etiqueta de eficiencia energética de un electrodoméstico indica:',
    opciones: [
      'Cuánta energía consume respecto a otros equipos equivalentes',
      'Cuántos años va a durar el aparato',
      'La potencia máxima que puede alcanzar',
      'El nivel de ruido que produce',
    ],
    correcta: 0,
    explicacion: 'Un equipo eficiente suele costar más al comprarlo y menos cada mes. En aparatos que funcionan todo el día, como una nevera, la diferencia acumulada supera al sobreprecio inicial.',
  },

  // ----- Primer empleo y derechos laborales -----
  {
    id: 'cot-081', tema: 'trabajo', dificultad: 1,
    enunciado: 'Un contrato de trabajo debe establecer, como mínimo:',
    opciones: [
      'Las funciones, el salario, la jornada y la duración del vínculo',
      'Únicamente el salario acordado',
      'Solo la fecha de inicio y el cargo',
      'La firma del trabajador, sin más detalles',
    ],
    correcta: 0,
    explicacion: 'Aunque un acuerdo verbal puede generar obligaciones, sin contrato escrito es muy difícil demostrar lo pactado cuando aparece un desacuerdo.',
  },
  {
    id: 'cot-082', tema: 'trabajo', dificultad: 2,
    enunciado: 'Las horas trabajadas por encima de la jornada legal:',
    opciones: [
      'Deben pagarse con un recargo sobre el valor de la hora ordinaria',
      'Se compensan siempre con días libres, a elección del empleador',
      'No se pagan si el trabajador acepta quedarse',
      'Se pagan igual que las horas normales',
    ],
    correcta: 0,
    explicacion: 'El recargo existe justamente para desincentivar la extensión de la jornada. Que el trabajador acepte no elimina el derecho: los derechos laborales mínimos son irrenunciables.',
  },
  {
    id: 'cot-083', tema: 'trabajo', dificultad: 2,
    enunciado: 'Los descuentos de salud y pensión que aparecen en el comprobante de pago:',
    opciones: [
      'Son aportes obligatorios que financian la atención médica y la pensión futura del trabajador',
      'Son una comisión que cobra el empleador',
      'Son voluntarios y se pueden suspender',
      'Se devuelven al terminar el contrato',
    ],
    correcta: 0,
    explicacion: 'Un empleo que paga más "en efectivo y sin descuentos" está transfiriendo al trabajador un riesgo que luego aparece en forma de falta de atención médica o de pensión.',
  },
  {
    id: 'cot-084', tema: 'trabajo', dificultad: 1,
    enunciado: 'En una hoja de vida para un primer empleo, lo más conveniente es:',
    opciones: [
      'Incluir formación, experiencia relevante y datos de contacto actualizados, en una o dos páginas',
      'Incluir toda la información personal posible para dar confianza',
      'Usar un diseño muy llamativo para destacar',
      'Omitir la formación si aún no se ha terminado',
    ],
    correcta: 0,
    explicacion: 'Quien selecciona revisa decenas de hojas: la claridad gana. Datos como estado civil o número de documento no aportan y exponen información innecesaria.',
  },
  {
    id: 'cot-085', tema: 'trabajo', dificultad: 2,
    enunciado: 'Antes de una entrevista de trabajo, lo más útil es:',
    opciones: [
      'Informarse sobre la organización y preparar ejemplos concretos de lo que se sabe hacer',
      'Memorizar respuestas generales para cualquier pregunta',
      'Averiguar quién más se presentó al cargo',
      'Llevar el mayor número posible de certificados',
    ],
    correcta: 0,
    explicacion: 'Un ejemplo concreto demuestra más que un adjetivo: en lugar de decirse responsable, conviene contar una situación en la que se resolvió algo.',
  },
  {
    id: 'cot-086', tema: 'trabajo', dificultad: 3,
    enunciado: 'Una oferta laboral pide pagar por el curso de inducción o por el uniforme antes de ser contratado. ¿Qué indica?',
    opciones: [
      'Es una señal clara de estafa: un empleo no se compra',
      'Es normal en empresas grandes',
      'Es aceptable si el monto es bajo',
      'Es válido si luego se devuelve con el primer salario',
    ],
    correcta: 0,
    explicacion: 'El patrón se repite con distintas excusas: examen médico, materiales, capacitación. Ninguna empresa legítima cobra por darte trabajo.',
  },
  {
    id: 'cot-087', tema: 'trabajo', dificultad: 2,
    enunciado: 'El periodo de prueba en un contrato laboral sirve para:',
    opciones: [
      'Que ambas partes evalúen si la relación funciona, con reglas especiales de terminación',
      'Que el trabajador labore sin remuneración durante unas semanas',
      'Que la empresa evite pagar aportes durante ese tiempo',
      'Que el trabajador renuncie a sus derechos temporalmente',
    ],
    correcta: 0,
    explicacion: 'Durante ese periodo el trabajo se paga y los aportes se hacen igual. Lo único que cambia son las condiciones para dar por terminado el contrato.',
  },
  {
    id: 'cot-088', tema: 'trabajo', dificultad: 2,
    enunciado: 'El derecho a vacaciones y descanso remunerado existe porque:',
    opciones: [
      'El descanso es necesario para la salud y la seguridad, y por eso es un derecho irrenunciable',
      'Es un beneficio que concede cada empresa si quiere',
      'Solo aplica a contratos de más de cinco años',
      'Sustituye al pago de horas extra',
    ],
    correcta: 0,
    explicacion: 'La fatiga acumulada aumenta los errores y los accidentes laborales. Que sea irrenunciable significa que no vale un acuerdo para cambiarlo por dinero de forma indefinida.',
  },
  {
    id: 'cot-089', tema: 'trabajo', dificultad: 3,
    enunciado: 'La informalidad laboral implica para el trabajador que:',
    opciones: [
      'Queda sin seguridad social, sin prestaciones y sin protección ante un accidente o un despido',
      'Gana siempre menos dinero al mes',
      'No puede trabajar más de ocho horas',
      'Debe pagar más impuestos',
    ],
    correcta: 0,
    explicacion: 'El ingreso inmediato puede parecer mayor porque no hay descuentos, pero el costo aparece en la primera enfermedad, el primer accidente o la vejez sin pensión.',
  },
  {
    id: 'cot-090', tema: 'trabajo', dificultad: 2,
    enunciado: 'Se considera acoso laboral la conducta que:',
    opciones: [
      'De forma persistente busca infundir miedo, desmotivar o humillar a un trabajador',
      'Consiste en asignar tareas difíciles o exigentes',
      'Implica una llamada de atención por un error puntual',
      'Ocurre entre compañeros del mismo nivel jerárquico únicamente',
    ],
    correcta: 0,
    explicacion: 'Lo que define el acoso es la persistencia y la intención de dañar, no la exigencia. Una corrección justificada, aunque incómoda, no es acoso.',
  },

  // ----- Cultura general -----
  {
    id: 'cot-091', tema: 'cultura-general', dificultad: 1,
    enunciado: '¿Quién propuso la teoría de la evolución por selección natural?',
    opciones: ['Charles Darwin', 'Isaac Newton', 'Gregor Mendel', 'Louis Pasteur'],
    correcta: 0,
    explicacion: 'La publicó en 1859 en "El origen de las especies". Mendel describió las leyes de la herencia y Pasteur, el papel de los microorganismos en las enfermedades.',
  },
  {
    id: 'cot-092', tema: 'cultura-general', dificultad: 1,
    enunciado: 'El lema asociado a la Revolución Francesa de 1789 fue:',
    opciones: ['Libertad, igualdad, fraternidad', 'Paz, tierra y pan', 'Orden y progreso', 'Unidad, trabajo y justicia'],
    correcta: 0,
    explicacion: 'La Revolución Francesa y la Declaración de los Derechos del Hombre y del Ciudadano son el antecedente directo de las constituciones modernas.',
  },
  {
    id: 'cot-093', tema: 'cultura-general', dificultad: 2,
    enunciado: 'El Renacimiento fue:',
    opciones: [
      'Un movimiento cultural europeo de los siglos XV y XVI que recuperó el interés por la cultura clásica y puso al ser humano en el centro',
      'Un periodo de guerras religiosas en el norte de Europa',
      'La etapa de expansión del Imperio romano',
      'El movimiento artístico posterior a la Revolución Industrial',
    ],
    correcta: 0,
    explicacion: 'De ahí el humanismo y figuras como Leonardo da Vinci o Miguel Ángel. Marca el paso de la Edad Media a la Edad Moderna.',
  },
  {
    id: 'cot-094', tema: 'cultura-general', dificultad: 2,
    enunciado: 'La imprenta de tipos móviles de Gutenberg (siglo XV) tuvo como principal consecuencia:',
    opciones: [
      'Abaratar y multiplicar la circulación de libros, difundiendo ideas a una escala nunca vista',
      'Permitir la escritura en lenguas distintas del latín',
      'Sustituir la escritura a mano en la vida cotidiana',
      'Crear las primeras bibliotecas del mundo',
    ],
    correcta: 0,
    explicacion: 'Es el caso clásico de una tecnología que cambia la sociedad: sin imprenta es difícil explicar la Reforma, la ciencia moderna o la alfabetización masiva.',
  },
  {
    id: 'cot-095', tema: 'cultura-general', dificultad: 1,
    enunciado: '¿Entre qué años se desarrolló la Segunda Guerra Mundial?',
    opciones: ['1939 y 1945', '1914 y 1918', '1945 y 1950', '1929 y 1939'],
    correcta: 0,
    explicacion: 'La Primera Guerra Mundial fue entre 1914 y 1918. De la Segunda salieron la ONU y la Declaración Universal de los Derechos Humanos.',
  },
  {
    id: 'cot-096', tema: 'cultura-general', dificultad: 2,
    enunciado: 'En informática, un algoritmo es:',
    opciones: [
      'Una secuencia ordenada y finita de pasos para resolver un problema',
      'Un programa de computador ya compilado',
      'El lenguaje en el que se escribe el código',
      'La memoria que usa una aplicación',
    ],
    correcta: 0,
    explicacion: 'Una receta de cocina es un algoritmo: pasos definidos, en orden y con un final. El programa es la implementación de ese algoritmo en un lenguaje concreto.',
  },
  {
    id: 'cot-097', tema: 'cultura-general', dificultad: 2,
    enunciado: '¿Quién escribió "Cien años de soledad"?',
    opciones: ['Gabriel García Márquez', 'Mario Vargas Llosa', 'Julio Cortázar', 'Pablo Neruda'],
    correcta: 0,
    explicacion: 'Publicada en 1967, es la obra central del realismo mágico latinoamericano. Neruda fue poeta, y Vargas Llosa y Cortázar escribieron otras obras del boom.',
  },
  {
    id: 'cot-098', tema: 'cultura-general', dificultad: 2,
    enunciado: 'La Revolución Industrial se asocia sobre todo con:',
    opciones: [
      'La máquina de vapor y el paso de la producción artesanal a la fabril',
      'La invención de la electricidad doméstica',
      'La llegada de los europeos a América',
      'La aparición de la computadora personal',
    ],
    correcta: 0,
    explicacion: 'Comenzó en Inglaterra a finales del siglo XVIII y transformó el trabajo, las ciudades y el ambiente: es el punto de partida del aumento de emisiones que hoy se estudia como cambio climático.',
  },
  {
    id: 'cot-099', tema: 'cultura-general', dificultad: 2,
    enunciado: 'La mayoría de los procesos de independencia de los países hispanoamericanos ocurrió:',
    opciones: [
      'En las primeras décadas del siglo XIX',
      'A finales del siglo XVIII',
      'A mediados del siglo XX',
      'Durante el siglo XVII',
    ],
    correcta: 0,
    explicacion: 'Se concentran entre 1810 y 1825, favorecidos por la crisis de la monarquía española tras la invasión napoleónica. Brasil siguió un camino distinto, con un imperio propio.',
  },
  {
    id: 'cot-100', tema: 'cultura-general', dificultad: 1,
    enunciado: 'La primera llegada de seres humanos a la Luna ocurrió en:',
    opciones: ['1969, con la misión Apolo 11', '1957, con el Sputnik', '1961, con Yuri Gagarin', '1981, con el transbordador espacial'],
    correcta: 0,
    explicacion: 'El Sputnik (1957) fue el primer satélite artificial y Gagarin (1961) el primer humano en el espacio, pero no en la Luna.',
  },
  // ----- Ampliación por niveles -----
  {
    id: 'cot-101', tema: 'dinero', dificultad: 1,
    enunciado: '¿Qué es el ahorro?',
    opciones: [
      'La parte del ingreso que no se gasta y se guarda para después',
      'El dinero que se pide prestado a un banco',
      'El interés que cobra una entidad financiera',
      'El total de los gastos de un mes',
    ],
    correcta: 0,
    explicacion: 'Ahorrar es apartar hoy una parte del ingreso para usarla más adelante, sea por seguridad o para una meta concreta.',
  },
  {
    id: 'cot-102', tema: 'dinero', dificultad: 1,
    enunciado: 'En un crédito, la tasa de interés representa:',
    opciones: [
      'Lo que cuesta el dinero prestado, expresado como un porcentaje',
      'El monto total que se debe devolver',
      'La comisión que cobra el cajero automático',
      'El plazo en meses del préstamo',
    ],
    correcta: 0,
    explicacion: 'Es el precio del dinero en el tiempo: cuanto mayor la tasa, más caro sale pedir prestado y más se paga por encima del monto original.',
  },
  {
    id: 'cot-103', tema: 'dinero', dificultad: 3,
    enunciado: '¿Cuál es la diferencia entre interés simple e interés compuesto?',
    opciones: [
      'El simple se calcula siempre sobre el capital inicial; el compuesto, sobre el capital más los intereses ya acumulados',
      'El simple se aplica a los ahorros y el compuesto, a los créditos',
      'El compuesto siempre tiene una tasa menor',
      'El simple se cobra mensual y el compuesto, anual',
    ],
    correcta: 0,
    explicacion: 'En el compuesto los intereses generan intereses, así que la deuda o el ahorro crecen cada vez más rápido. En plazos largos la diferencia entre los dos es enorme.',
  },
  {
    id: 'cot-104', tema: 'dinero', dificultad: 4,
    enunciado: 'Una persona debe $1 000 000 con una tasa del 2 % mensual. Si cada mes paga solamente los intereses, ¿cuánto paga y cómo queda la deuda?',
    opciones: [
      'Paga $20 000 al mes y la deuda sigue en $1 000 000',
      'Paga $20 000 al mes y la deuda baja a $980 000',
      'Paga $200 000 al mes y la deuda baja a $800 000',
      'Paga $20 000 una sola vez y queda a paz y salvo',
    ],
    correcta: 0,
    explicacion: '2 % de 1 000 000 son 20 000. Si el pago solo cubre el interés, no abona nada al capital: se puede pagar durante años y seguir debiendo lo mismo.',
  },
  {
    id: 'cot-105', tema: 'dinero', dificultad: 4,
    enunciado: '¿Por qué pagar cada mes solo el "pago mínimo" de una tarjeta de crédito suele ser costoso?',
    opciones: [
      'Porque la mayor parte de ese pago cubre intereses y el saldo baja muy lentamente',
      'Porque el banco cobra una multa por pagar el mínimo',
      'Porque la tarjeta se bloquea al mes siguiente',
      'Porque el pago mínimo no se reporta a las centrales de riesgo',
    ],
    correcta: 0,
    explicacion: 'El mínimo está diseñado para mantener la cuenta al día, no para salir de la deuda. Con tasas altas, una compra pequeña puede terminar costando el doble si solo se abona el mínimo.',
  },
  {
    id: 'cot-106', tema: 'dinero', dificultad: 4,
    enunciado: '¿Para qué sirve un fondo de emergencia?',
    opciones: [
      'Para cubrir gastos imprevistos sin tener que endeudarse',
      'Para invertir en el mercado de valores',
      'Para pagar las vacaciones de fin de año',
      'Para aumentar el cupo de la tarjeta de crédito',
    ],
    correcta: 0,
    explicacion: 'Se recomienda tener entre tres y seis meses de gastos básicos disponibles. Su función no es rendir, sino estar accesible el día en que se daña la nevera o se pierde el empleo.',
  },
  {
    id: 'cot-107', tema: 'compras-precios', dificultad: 1,
    enunciado: 'Un artículo cuesta $50 000 y tiene un descuento del 10 %. ¿Cuánto se paga?',
    opciones: ['$45 000', '$40 000', '$49 000', '$5 000'],
    correcta: 0,
    explicacion: 'El 10 % de 50 000 son 5 000, y al restarlo quedan 45 000.',
  },
  {
    id: 'cot-108', tema: 'compras-precios', dificultad: 3,
    enunciado: 'Una tienda aplica un 20 % de descuento y, sobre ese precio, otro 10 %. ¿A qué descuento total equivale?',
    opciones: ['28 %', '30 %', '25 %', '32 %'],
    correcta: 0,
    explicacion: 'Los descuentos sucesivos no se suman: se pagan 0,8 × 0,9 = 0,72 del precio original, es decir un 28 % de rebaja, no un 30 %.',
    pista: 'Multiplica lo que queda por pagar en cada paso en lugar de sumar los porcentajes.',
  },
  {
    id: 'cot-109', tema: 'compras-precios', dificultad: 4,
    enunciado: 'Un paquete de 900 g cuesta $9 000 y otro de 1,2 kg cuesta $11 400. ¿Cuál conviene más?',
    opciones: [
      'El de 1,2 kg, porque sale a $9 500 el kilo frente a $10 000',
      'El de 900 g, porque cuesta menos en total',
      'Cuestan exactamente lo mismo por kilo',
      'No se puede comparar porque los tamaños son distintos',
    ],
    correcta: 0,
    explicacion: 'Hay que llevar los dos al mismo patrón: 9 000 ÷ 0,9 = 10 000 por kilo y 11 400 ÷ 1,2 = 9 500 por kilo. El precio total engaña; el precio por unidad no.',
  },
  {
    id: 'cot-110', tema: 'compras-precios', dificultad: 4,
    enunciado: 'Una promoción "lleve 3 y pague 2" equivale a un descuento aproximado de:',
    opciones: ['33 %', '50 %', '66 %', '25 %'],
    correcta: 0,
    explicacion: 'Se pagan 2 de cada 3 unidades, o sea el 66,7 % del precio: el ahorro es un tercio, alrededor del 33 %. Solo conviene si de verdad se necesitan las tres unidades.',
  },
  {
    id: 'cot-111', tema: 'compras-precios', dificultad: 4,
    enunciado: 'Un producto se vende en $119 000 con el IVA del 19 % ya incluido. ¿Cuál es el precio antes de impuesto?',
    opciones: ['$100 000', '$96 390', '$101 000', '$119 000 menos $19 000 de IVA es imposible de saber'],
    correcta: 0,
    explicacion: 'El precio final es el 119 % del valor base, así que se divide: 119 000 ÷ 1,19 = 100 000. Restar el 19 % al precio final es el error típico y da un resultado distinto.',
  },
  {
    id: 'cot-112', tema: 'documentos', dificultad: 1,
    enunciado: '¿A qué edad se tramita la cédula de ciudadanía en Colombia?',
    opciones: ['A los 18 años', 'A los 14 años', 'A los 21 años', 'Al nacer'],
    correcta: 0,
    explicacion: 'Antes de los 18 el documento de identidad es la tarjeta de identidad, que se saca a los 7 años y se renueva a los 14.',
  },
  {
    id: 'cot-113', tema: 'documentos', dificultad: 3,
    enunciado: 'Por regla general, ¿en cuánto tiempo debe responderse un derecho de petición?',
    opciones: ['En 15 días hábiles', 'En 48 horas', 'En tres meses', 'No existe plazo definido'],
    correcta: 0,
    explicacion: 'Ese es el plazo general; hay plazos especiales más cortos para pedir información (10 días) y más largos para consultas (30 días). Si la entidad no responde, se puede acudir a la tutela.',
  },
  {
    id: 'cot-114', tema: 'documentos', dificultad: 4,
    enunciado: '¿Para qué sirve el certificado de tradición y libertad de un inmueble?',
    opciones: [
      'Para conocer quién es el dueño y si la propiedad tiene hipotecas o embargos',
      'Para calcular el impuesto predial del año',
      'Para autorizar una remodelación',
      'Para acreditar que el inmueble tiene servicios públicos',
    ],
    correcta: 0,
    explicacion: 'Es la historia jurídica del predio, expedida por la Oficina de Registro. Comprar sin revisarlo es exponerse a adquirir un bien embargado o con varios dueños.',
  },
  {
    id: 'cot-115', tema: 'documentos', dificultad: 4,
    enunciado: 'En un contrato de arrendamiento de vivienda urbana en Colombia, el incremento anual del canon:',
    opciones: [
      'No puede superar el IPC del año inmediatamente anterior',
      'Lo fija libremente el arrendador cada año',
      'Está prohibido durante los tres primeros años',
      'Debe ser del 10 % anual',
    ],
    correcta: 0,
    explicacion: 'La Ley 820 de 2003 ata el reajuste a la inflación certificada. Un aumento superior no es válido aunque esté escrito en el contrato.',
  },
  {
    id: 'cot-116', tema: 'documentos', dificultad: 4,
    enunciado: 'Si una entidad pública no responde una petición dentro del plazo legal, lo que ocurre es que:',
    opciones: [
      'Se vulnera el derecho fundamental de petición y puede reclamarse por tutela',
      'La petición se entiende negada y no hay nada más que hacer',
      'Hay que volver a radicarla desde cero',
      'Se pierde el derecho a pedir esa información',
    ],
    correcta: 0,
    explicacion: 'El derecho de petición no es solo a radicar un escrito: es a obtener respuesta de fondo y oportuna. El silencio es una violación en sí misma, y por eso la tutela procede contra la omisión.',
  },
  {
    id: 'cot-117', tema: 'medidas', dificultad: 1,
    enunciado: '¿A cuántos metros equivale un kilómetro?',
    opciones: ['1 000 m', '100 m', '10 000 m', '500 m'],
    correcta: 0,
    explicacion: 'El prefijo "kilo" significa mil, así que un kilómetro son mil metros y un kilogramo, mil gramos.',
  },
  {
    id: 'cot-118', tema: 'medidas', dificultad: 1,
    enunciado: '¿Cuántos mililitros hay en un litro?',
    opciones: ['1 000 ml', '100 ml', '10 ml', '500 ml'],
    correcta: 0,
    explicacion: 'El prefijo "mili" significa una milésima parte: un mililitro es la milésima parte de un litro.',
  },
  {
    id: 'cot-119', tema: 'medidas', dificultad: 4,
    enunciado: 'Un tanque tiene 2 m de largo, 1 m de ancho y 0,5 m de alto. ¿Cuántos litros de agua caben en él?',
    opciones: ['1 000 L', '100 L', '10 L', '1 L'],
    correcta: 0,
    explicacion: 'El volumen es 2 × 1 × 0,5 = 1 m³, y un metro cúbico equivale a 1 000 litros. Esa equivalencia es la que permite pasar de medidas de construcción a medidas de consumo.',
  },
  {
    id: 'cot-120', tema: 'medidas', dificultad: 4,
    enunciado: 'Un carro va a 72 km/h. ¿Cuántos metros recorre en un segundo?',
    opciones: ['20 m', '72 m', '7,2 m', '12 m'],
    correcta: 0,
    explicacion: 'Para pasar de km/h a m/s se divide entre 3,6: 72 ÷ 3,6 = 20 m/s. Sirve para entender por qué a esa velocidad un segundo de distracción son veinte metros a ciegas.',
  },
  {
    id: 'cot-121', tema: 'medidas', dificultad: 4,
    enunciado: 'Un bombillo de 100 W permanece encendido 10 horas. ¿Cuánta energía consume?',
    opciones: ['1 kWh', '100 kWh', '10 kWh', '1 000 kWh'],
    correcta: 0,
    explicacion: '100 W × 10 h = 1 000 Wh = 1 kWh. El recibo de la luz se cobra justamente en kilovatios-hora, así que ese es el número que conviene saber estimar.',
  },
  {
    id: 'cot-122', tema: 'tecnologia', dificultad: 1,
    enunciado: '¿Cuál de estas es la mejor práctica para una contraseña?',
    opciones: [
      'Que sea larga, distinta en cada servicio y difícil de adivinar',
      'Usar la misma en todos los sitios para no olvidarla',
      'Usar la fecha de nacimiento',
      'Usar el nombre de la mascota',
    ],
    correcta: 0,
    explicacion: 'La longitud pesa más que los símbolos raros, y repetir contraseñas es lo más peligroso: una filtración en un servicio abre la puerta a todos los demás.',
  },
  {
    id: 'cot-123', tema: 'tecnologia', dificultad: 1,
    enunciado: 'Cuando se dice que un archivo está "en la nube", significa que:',
    opciones: [
      'Está guardado en servidores de internet a los que se accede en línea',
      'Está guardado únicamente en el disco del computador',
      'Se borra automáticamente cada cierto tiempo',
      'Solo puede abrirse desde un celular',
    ],
    correcta: 0,
    explicacion: 'La nube no es un lugar etéreo: son computadores de alguien más. Por eso el archivo está disponible desde cualquier dispositivo, pero también depende de tener conexión y de la seguridad de esa cuenta.',
  },
  {
    id: 'cot-124', tema: 'tecnologia', dificultad: 3,
    enunciado: '¿Cuál es la diferencia entre la memoria RAM y el almacenamiento de un dispositivo?',
    opciones: [
      'La RAM guarda temporalmente lo que se está usando y el almacenamiento conserva los archivos de forma permanente',
      'La RAM guarda los archivos y el almacenamiento, los programas',
      'Son dos nombres para lo mismo',
      'La RAM solo existe en los computadores de escritorio',
    ],
    correcta: 0,
    explicacion: 'La RAM se borra al apagar el equipo: es el escritorio donde se trabaja. El almacenamiento es el archivador. Un equipo lento con espacio libre suele necesitar más RAM, no más disco.',
  },
  {
    id: 'cot-125', tema: 'tecnologia', dificultad: 4,
    enunciado: '¿Por qué la verificación en dos pasos protege una cuenta aunque roben la contraseña?',
    opciones: [
      'Porque exige además un segundo factor, como un código temporal que solo tiene el dueño',
      'Porque cambia la contraseña automáticamente cada día',
      'Porque cifra todos los archivos del dispositivo',
      'Porque impide que la cuenta se abra desde otro país',
    ],
    correcta: 0,
    explicacion: 'Combina algo que se sabe con algo que se tiene. Quien obtenga la contraseña por una filtración o un engaño seguirá sin el segundo factor, y ahí se detiene el ataque.',
  },
  {
    id: 'cot-126', tema: 'tecnologia', dificultad: 4,
    enunciado: 'Llega un correo del "banco" que advierte que la cuenta será bloqueada hoy y pide entrar por un enlace a confirmar los datos. Lo correcto es:',
    opciones: [
      'No usar el enlace y comunicarse con el banco por su canal oficial',
      'Entrar por el enlace y verificar si la página se ve igual a la del banco',
      'Responder el correo pidiendo más información',
      'Reenviarlo a los contactos para advertirles',
    ],
    correcta: 0,
    explicacion: 'Es el patrón clásico del phishing: urgencia, amenaza y un enlace. Una página puede copiarse píxel por píxel, así que verla "igual" no prueba nada; lo único seguro es entrar por la vía que uno ya conoce.',
  },
  {
    id: 'cot-127', tema: 'tecnologia', dificultad: 4,
    enunciado: '¿Por qué no basta con tener una copia de seguridad en el mismo computador donde están los archivos?',
    opciones: [
      'Porque un daño, un robo o un programa malicioso afectaría a la vez el original y la copia',
      'Porque las copias ocupan demasiado espacio',
      'Porque el sistema operativo borra las copias al actualizarse',
      'Porque una copia local no se puede restaurar',
    ],
    correcta: 0,
    explicacion: 'Una copia sirve contra un riesgo solo si no comparte ese riesgo con el original. Por eso la recomendación habitual es tener al menos dos copias en medios distintos y una fuera del sitio.',
  },
  {
    id: 'cot-128', tema: 'informacion', dificultad: 1,
    enunciado: '¿Qué caracteriza a una fuente de información confiable?',
    opciones: [
      'Que identifica a su autor, cita de dónde saca los datos y puede verificarse',
      'Que tiene muchos seguidores en redes sociales',
      'Que confirma lo que uno ya piensa',
      'Que está escrita en mayúsculas y con signos de admiración',
    ],
    correcta: 0,
    explicacion: 'La confiabilidad no la da la popularidad sino la posibilidad de rastrear la afirmación hasta su origen.',
  },
  {
    id: 'cot-129', tema: 'informacion', dificultad: 1,
    enunciado: 'Una noticia falsa es aquella que:',
    opciones: [
      'Presenta información inventada o manipulada como si fuera un hecho verificado',
      'Contiene una opinión con la que uno no está de acuerdo',
      'Fue publicada hace varios años',
      'Está escrita en otro idioma',
    ],
    correcta: 0,
    explicacion: 'Lo que la define es la falsedad presentada con apariencia de información, no que resulte incómoda o antigua.',
  },
  {
    id: 'cot-130', tema: 'informacion', dificultad: 1,
    enunciado: 'Antes de reenviar un mensaje alarmante recibido por WhatsApp, lo más razonable es:',
    opciones: [
      'Verificar en medios o fuentes oficiales si la información es cierta',
      'Reenviarlo rápido por si acaso es verdad',
      'Reenviarlo solo a la familia',
      'Borrarlo sin leerlo',
    ],
    correcta: 0,
    explicacion: 'Reenviar "por si acaso" es justamente lo que hace circular los bulos. Basta una búsqueda de treinta segundos para cortar la cadena.',
  },
  {
    id: 'cot-131', tema: 'informacion', dificultad: 4,
    enunciado: 'El sesgo de confirmación consiste en:',
    opciones: [
      'Buscar y aceptar con más facilidad la información que coincide con lo que ya se cree',
      'Creer todo lo que dice un medio de comunicación',
      'Repetir una noticia hasta que parezca cierta',
      'Confundir una opinión con un hecho',
    ],
    correcta: 0,
    explicacion: 'No se trata de falta de inteligencia: todos tendemos a examinar con lupa lo que nos contradice y a aceptar sin revisar lo que nos da la razón. Reconocerlo es lo que permite buscar deliberadamente la evidencia contraria.',
  },
  {
    id: 'cot-132', tema: 'informacion', dificultad: 4,
    enunciado: 'Circula la foto de una inundación acompañada del texto "así está la ciudad hoy". ¿Qué conviene revisar primero?',
    opciones: [
      'La fecha y el lugar originales de la imagen, con una búsqueda inversa',
      'Cuántas veces ha sido compartida',
      'Si la foto tiene buena resolución',
      'Si quien la comparte es conocido',
    ],
    correcta: 0,
    explicacion: 'Una de las formas más comunes de desinformación no usa imágenes falsas, sino imágenes reales sacadas de contexto: otra ciudad, otro año, otro suceso. La búsqueda inversa revela dónde apareció antes.',
  },
  {
    id: 'cot-133', tema: 'informacion', dificultad: 4,
    enunciado: 'Un artículo elogia un producto y lleva la etiqueta "contenido patrocinado". Eso significa que:',
    opciones: [
      'Es publicidad pagada por el anunciante, aunque tenga la apariencia de una nota periodística',
      'El medio verificó el producto antes de recomendarlo',
      'El artículo fue premiado por su calidad',
      'El contenido es gratuito para el lector',
    ],
    correcta: 0,
    explicacion: 'La etiqueta existe precisamente porque el formato imita al periodístico. Saber quién paga por un contenido es parte de evaluarlo, igual que saber quién lo firma.',
  },
  {
    id: 'cot-134', tema: 'seguridad', dificultad: 1,
    enunciado: '¿Cuál es el número único de emergencias en Colombia?',
    opciones: ['123', '911', '119', '132'],
    correcta: 0,
    explicacion: 'El 123 conecta con policía, bomberos y atención médica de urgencias en todo el país.',
  },
  {
    id: 'cot-135', tema: 'seguridad', dificultad: 3,
    enunciado: 'Durante un sismo, dentro de un edificio, lo indicado es:',
    opciones: [
      'Protegerse junto a una estructura firme, lejos de ventanas, y no usar el ascensor',
      'Correr de inmediato hacia las escaleras',
      'Usar el ascensor para salir más rápido',
      'Asomarse a la ventana para ver qué ocurre',
    ],
    correcta: 0,
    explicacion: 'La mayoría de las lesiones son por objetos que caen y por correr durante el movimiento. El ascensor puede quedar sin energía y atrapar a quien esté dentro; la evacuación se hace cuando el sismo termina.',
  },
  {
    id: 'cot-136', tema: 'seguridad', dificultad: 4,
    enunciado: 'Si se incendia el aceite de una sartén en la cocina, lo que NUNCA debe hacerse es:',
    opciones: [
      'Echarle agua',
      'Tapar la sartén con una tapa metálica',
      'Apagar la fuente de calor',
      'Usar un extintor apropiado',
    ],
    correcta: 0,
    explicacion: 'El agua se evapora de golpe al contacto con el aceite ardiendo y proyecta el fuego hacia arriba. Lo correcto es cortar el oxígeno tapando la sartén y apagar la estufa.',
  },
  {
    id: 'cot-137', tema: 'seguridad', dificultad: 4,
    enunciado: 'Si un conductor duplica su velocidad, la distancia que necesita para detenerse:',
    opciones: [
      'Se multiplica aproximadamente por cuatro',
      'Se duplica exactamente',
      'No cambia si los frenos están en buen estado',
      'Se reduce a la mitad',
    ],
    correcta: 0,
    explicacion: 'La energía cinética crece con el cuadrado de la velocidad, y con ella la distancia de frenado. Por eso los límites de velocidad en zonas escolares o residenciales no son un detalle burocrático.',
  },
  {
    id: 'cot-138', tema: 'seguridad', dificultad: 4,
    enunciado: '¿Por qué el casco y el cinturón de seguridad reducen las lesiones en un choque?',
    opciones: [
      'Porque alargan el tiempo de la desaceleración y reparten la fuerza en una superficie mayor',
      'Porque reducen la velocidad del vehículo antes del impacto',
      'Porque impiden que el vehículo se deforme',
      'Porque evitan por completo el movimiento del cuerpo',
    ],
    correcta: 0,
    explicacion: 'En un choque, lo que hiere es frenar de golpe. Al estirar unos milisegundos esa frenada y distribuir la carga, la fuerza sobre el cuerpo baja drásticamente; es el mismo principio de las zonas de deformación del carro.',
  },
  {
    id: 'cot-139', tema: 'ambiente-hogar', dificultad: 1,
    enunciado: 'Según el código de colores vigente en Colombia, en la bolsa blanca van:',
    opciones: [
      'Los residuos aprovechables, como plástico, vidrio, papel y cartón limpios',
      'Los residuos orgánicos de la cocina',
      'Los residuos peligrosos',
      'Todo lo que no se pueda reciclar',
    ],
    correcta: 0,
    explicacion: 'El código unificado usa blanco para aprovechables, verde para orgánicos y negro para no aprovechables.',
  },
  {
    id: 'cot-140', tema: 'ambiente-hogar', dificultad: 1,
    enunciado: '¿Cuál de estas acciones ahorra más agua en el hogar?',
    opciones: [
      'Cerrar la llave mientras se cepilla los dientes o se enjabona',
      'Lavar los platos con agua caliente',
      'Usar jabón biodegradable',
      'Regar las plantas al mediodía',
    ],
    correcta: 0,
    explicacion: 'Dejar la llave abierta desperdicia varios litros por minuto sin que se esté usando el agua. El tipo de jabón importa para la contaminación, no para el consumo.',
  },
  {
    id: 'cot-141', tema: 'ambiente-hogar', dificultad: 3,
    enunciado: '¿Cuál de estos residuos NO debe ir en la bolsa de reciclaje aunque sea de papel?',
    opciones: [
      'Una servilleta usada con restos de comida',
      'Una hoja de cuaderno escrita',
      'Una caja de cartón desarmada',
      'Un periódico viejo',
    ],
    correcta: 0,
    explicacion: 'El papel contaminado con grasa o comida no se puede reprocesar y además puede echar a perder el resto del material limpio de la bolsa. Va con los no aprovechables o, si el servicio existe, con los orgánicos.',
  },
  {
    id: 'cot-142', tema: 'ambiente-hogar', dificultad: 4,
    enunciado: 'Las pilas usadas, los medicamentos vencidos y las bombillas fluorescentes deben llevarse a puntos posconsumo porque:',
    opciones: [
      'Contienen sustancias peligrosas que contaminan suelo y agua si van a la basura común',
      'Son residuos aprovechables de alto valor comercial',
      'Ocupan demasiado espacio en el relleno sanitario',
      'La ley prohíbe tenerlos en casa',
    ],
    correcta: 0,
    explicacion: 'Metales pesados como el mercurio y el cadmio se filtran desde el relleno sanitario hacia el agua subterránea. Son pocos gramos por unidad, pero muy tóxicos y persistentes.',
  },
  {
    id: 'cot-143', tema: 'ambiente-hogar', dificultad: 4,
    enunciado: 'Los aparatos que quedan en modo de espera (con la luz roja encendida):',
    opciones: [
      'Siguen consumiendo energía, y sumados representan una parte apreciable del recibo',
      'No consumen nada mientras no se usen',
      'Consumen más que cuando están encendidos',
      'Se dañan si se desconectan del todo',
    ],
    correcta: 0,
    explicacion: 'Es el llamado consumo fantasma: cada aparato gasta poco, pero un hogar con televisor, consola, módem y cargadores permanentemente conectados acumula un gasto constante las 24 horas.',
  },
  {
    id: 'cot-144', tema: 'ambiente-hogar', dificultad: 4,
    enunciado: '¿Qué ventaja ambiental tiene compostar los residuos orgánicos de la cocina?',
    opciones: [
      'Se evita que se descompongan en el relleno sanitario generando metano y se obtiene abono',
      'Se reduce el consumo de agua de la vivienda',
      'Se eliminan los residuos peligrosos del hogar',
      'Se aumenta el volumen total de basura recogida',
    ],
    correcta: 0,
    explicacion: 'Enterrados y sin oxígeno, los orgánicos generan metano, un gas de efecto invernadero mucho más potente que el CO₂. Compostados con aire, se convierten en materia orgánica útil para el suelo.',
  },
  {
    id: 'cot-145', tema: 'trabajo', dificultad: 1,
    enunciado: '¿Qué elemento distingue a un contrato de trabajo?',
    opciones: [
      'Que hay subordinación: el empleador da órdenes y fija horarios',
      'Que se firma ante notario',
      'Que dura como mínimo un año',
      'Que se paga siempre en efectivo',
    ],
    correcta: 0,
    explicacion: 'Los tres elementos son la prestación personal del servicio, la remuneración y la subordinación. Esta última es la que diferencia al empleado del contratista independiente.',
  },
  {
    id: 'cot-146', tema: 'trabajo', dificultad: 3,
    enunciado: '¿Cuáles de estos son prestaciones sociales de un trabajador con contrato laboral en Colombia?',
    opciones: [
      'La prima de servicios, las cesantías y sus intereses',
      'El salario básico y las horas extra',
      'El auxilio de transporte y el recargo nocturno',
      'La indemnización por despido',
    ],
    correcta: 0,
    explicacion: 'Las prestaciones son pagos adicionales al salario: prima, cesantías, intereses a las cesantías y dotación. Las horas extra y los recargos son parte de la remuneración del trabajo realizado.',
  },
  {
    id: 'cot-147', tema: 'trabajo', dificultad: 4,
    enunciado: '¿Cuál es la diferencia de fondo entre un contrato laboral y uno de prestación de servicios?',
    opciones: [
      'En el laboral hay subordinación y derecho a prestaciones; en el de servicios, autonomía y pago por el resultado',
      'El de prestación de servicios siempre paga mejor',
      'El laboral solo puede ser a término fijo',
      'El de prestación de servicios exige cumplir horario en la oficina',
    ],
    correcta: 0,
    explicacion: 'Si en la práctica hay horario, órdenes y permanencia, hay contrato de trabajo aunque el papel diga otra cosa: es el principio de primacía de la realidad. Firmar prestación de servicios para encubrir un empleo es una forma frecuente de elusión.',
  },
  {
    id: 'cot-148', tema: 'trabajo', dificultad: 4,
    enunciado: 'En un contrato laboral, la afiliación a riesgos laborales (ARL):',
    opciones: [
      'La paga íntegramente el empleador',
      'La paga el trabajador con un descuento de su salario',
      'Se reparte entre las dos partes por mitades',
      'Es opcional si el trabajo es de oficina',
    ],
    correcta: 0,
    explicacion: 'Salud y pensión se cotizan entre empleador y trabajador, pero el aporte a riesgos laborales corre por cuenta exclusiva del empleador y es obligatorio, sea cual sea el oficio.',
  },
  {
    id: 'cot-149', tema: 'trabajo', dificultad: 4,
    enunciado: 'Si a un trabajador lo despiden sin justa causa, lo que procede es:',
    opciones: [
      'El pago de una indemnización además de la liquidación de salarios y prestaciones',
      'Solo el pago de los días trabajados',
      'La reincorporación automática al cargo',
      'Nada, porque el empleador puede terminar el contrato cuando quiera',
    ],
    correcta: 0,
    explicacion: 'El empleador puede terminar el contrato sin causa, pero debe pagar por ello: la indemnización se calcula según el tipo de contrato y el tiempo servido, y es distinta de la liquidación, que se debe siempre.',
  },
  {
    id: 'cot-150', tema: 'cultura-general', dificultad: 3,
    enunciado: '¿Qué escritor colombiano recibió el Premio Nobel de Literatura en 1982?',
    opciones: ['Gabriel García Márquez', 'Álvaro Mutis', 'Jorge Isaacs', 'Germán Arciniegas'],
    correcta: 0,
    explicacion: 'Se lo concedieron principalmente por "Cien años de soledad". Mutis ganó el Cervantes, y Jorge Isaacs, autor de "María", pertenece al siglo XIX.',
  },
  {
    id: 'cot-151', tema: 'cultura-general', dificultad: 3,
    enunciado: '¿Qué se conmemora el 7 de agosto en Colombia?',
    opciones: [
      'La batalla de Boyacá, que selló la independencia en 1819',
      'El grito de independencia de 1810',
      'La firma de la Constitución de 1991',
      'La fundación de Bogotá',
    ],
    correcta: 0,
    explicacion: 'El 20 de julio se recuerda el grito de independencia de 1810; el 7 de agosto, la victoria militar que la hizo efectiva nueve años después.',
  },
  {
    id: 'cot-152', tema: 'cultura-general', dificultad: 3,
    enunciado: 'El Carnaval de Barranquilla fue declarado por la Unesco:',
    opciones: [
      'Obra Maestra del Patrimonio Oral e Inmaterial de la Humanidad',
      'Patrimonio natural del mundo',
      'Reserva de la biosfera',
      'Monumento arquitectónico protegido',
    ],
    correcta: 0,
    explicacion: 'El patrimonio inmaterial cubre prácticas vivas: fiestas, músicas, saberes y oficios. Por eso también están en esa lista el vallenato tradicional y el sistema normativo wayú.',
  },
  {
    id: 'cot-153', tema: 'cultura-general', dificultad: 4,
    enunciado: 'El término "realismo mágico", asociado a la obra de García Márquez, se refiere a:',
    opciones: [
      'Narrar hechos extraordinarios como si fueran parte natural de la vida cotidiana',
      'Escribir únicamente sobre acontecimientos históricos comprobados',
      'Usar un lenguaje sencillo y sin metáforas',
      'Ambientar las historias en mundos de fantasía ajenos a la realidad',
    ],
    correcta: 0,
    explicacion: 'Lo característico no es que ocurran prodigios, sino que nadie se asombre de ellos: en Macondo una lluvia de cuatro años se narra con el mismo tono que una cosecha. Eso lo distingue de la literatura fantástica.',
  },
  {
    id: 'cot-154', tema: 'cultura-general', dificultad: 4,
    enunciado: '¿Qué fue el Bogotazo?',
    opciones: [
      'La revuelta que estalló en Bogotá tras el asesinato de Jorge Eliécer Gaitán en 1948',
      'Un terremoto que destruyó el centro de la capital',
      'La toma del Palacio de Justicia en 1985',
      'La primera elección popular de alcaldes',
    ],
    correcta: 0,
    explicacion: 'El magnicidio desató disturbios que arrasaron el centro de la ciudad y marcó el inicio del período conocido como La Violencia, que enfrentó a liberales y conservadores durante más de una década.',
  },
  {
    id: 'cot-155', tema: 'cultura-general', dificultad: 4,
    enunciado: '¿Qué caracteriza la obra plástica de Fernando Botero?',
    opciones: [
      'El volumen exagerado de las figuras, que deforma personas y objetos',
      'El uso exclusivo del blanco y negro',
      'La pintura abstracta sin figuras reconocibles',
      'La representación realista y minuciosa del cuerpo humano',
    ],
    correcta: 0,
    explicacion: 'Botero no pinta personas gordas: infla el volumen de todo lo que representa, incluidos instrumentos, frutas y animales. Esa exageración es un recurso formal, y en series como la de Abu Ghraib la usó con intención crítica.',
  },
];
