/**
 * economia.js — Banco de economía.
 *
 * El razonamiento cuantitativo del Saber Pro y las sociales del Saber 11
 * preguntan por esto: costo de oportunidad, oferta y demanda, inflación,
 * desempleo, comercio y desigualdad. Antes estaba disperso entre ciudadanía y
 * vida cotidiana; aquí queda como asignatura propia.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const ECONOMIA = [
  // ----- Escasez y decisiones -----
  {
    id: 'eco-001', tema: 'escasez', dificultad: 1,
    enunciado: '¿Qué estudia la economía?',
    opciones: [
      'Cómo las sociedades asignan recursos escasos entre necesidades ilimitadas',
      'Cómo se imprime el dinero',
      'Cómo se administran únicamente las empresas',
      'Cómo se calculan los impuestos',
    ],
    correcta: 0,
    explicacion: 'La escasez es el punto de partida: si todo abundara no habría que elegir, y sin elección no hay problema económico.',
  },
  {
    id: 'eco-002', tema: 'escasez', dificultad: 1,
    enunciado: '¿Qué es el costo de oportunidad?',
    opciones: [
      'El valor de la mejor alternativa a la que se renuncia al tomar una decisión',
      'El dinero que se gasta en una compra',
      'El costo de producir un bien',
      'El precio de mercado de un producto',
    ],
    correcta: 0,
    explicacion: 'Toda elección tiene un costo aunque no implique pagar: estudiar una carrera cuesta también los años y el salario que se habrían ganado trabajando.',
  },
  {
    id: 'eco-003', tema: 'escasez', dificultad: 1,
    enunciado: '¿Cuál de estos es un bien económico?',
    opciones: [
      'Un par de zapatos',
      'El aire que respiramos en campo abierto',
      'La luz solar',
      'La lluvia',
    ],
    correcta: 0,
    explicacion: 'Los bienes económicos son escasos y requieren esfuerzo o pago para obtenerse. Los libres están disponibles sin costo, al menos mientras no se degraden.',
  },
  {
    id: 'eco-004', tema: 'escasez', dificultad: 2,
    enunciado: 'Una persona deja un empleo de 3 millones al mes para estudiar. ¿Cuál es el costo de oportunidad de un año de estudio?',
    opciones: [
      'Los 36 millones de salario que deja de recibir, además de la matrícula que paga',
      'Solo el valor de la matrícula',
      'Cero, porque estudiar es una inversión',
      'El valor de los libros y materiales',
    ],
    correcta: 0,
    explicacion: 'El costo de oportunidad incluye lo que se sacrifica, no solo lo que se desembolsa. Por eso estudiar es más caro para quien ya tiene un salario alto.',
  },
  {
    id: 'eco-005', tema: 'escasez', dificultad: 2,
    enunciado: '¿Qué representa la frontera de posibilidades de producción?',
    opciones: [
      'Las combinaciones máximas de dos bienes que una economía puede producir con sus recursos disponibles',
      'El límite de las exportaciones de un país',
      'La frontera geográfica de un mercado',
      'El techo del gasto público',
    ],
    correcta: 0,
    explicacion: 'Un punto sobre la curva indica uso pleno de los recursos; uno interior, desempleo o ineficiencia; uno exterior es inalcanzable sin más recursos o mejor tecnología.',
  },
  {
    id: 'eco-006', tema: 'escasez', dificultad: 2,
    enunciado: '¿Cuáles son los tres problemas económicos básicos de toda sociedad?',
    opciones: [
      'Qué producir, cómo producirlo y para quién',
      'Cuánto ahorrar, cuánto gastar y cuánto invertir',
      'Qué exportar, qué importar y a qué precio',
      'Cuántos impuestos cobrar, a quién y cuándo',
    ],
    correcta: 0,
    explicacion: 'Cada sistema económico responde de una manera: el mercado lo hace por precios, la planificación central por decisión administrativa, y las economías reales combinan ambos.',
  },
  {
    id: 'eco-007', tema: 'escasez', dificultad: 2,
    enunciado: '¿Qué distingue a los factores de producción?',
    opciones: [
      'Son los recursos que se combinan para producir: tierra, trabajo, capital y capacidad empresarial',
      'Son los productos terminados que compra el consumidor',
      'Son los impuestos que paga una empresa',
      'Son las etapas de distribución de un bien',
    ],
    correcta: 0,
    explicacion: 'Cada uno recibe una remuneración: renta la tierra, salario el trabajo, interés el capital y beneficio la función empresarial.',
  },
  {
    id: 'eco-008', tema: 'escasez', dificultad: 2,
    enunciado: '¿Qué significa que un recurso se use de forma eficiente?',
    opciones: [
      'Que no es posible producir más de un bien sin producir menos de otro',
      'Que se produce la mayor cantidad posible de todo',
      'Que se gasta la menor cantidad de dinero',
      'Que se reparte por igual entre todos',
    ],
    correcta: 0,
    explicacion: 'Es la eficiencia en el sentido de Pareto. Ojo: eficiente no significa justo, y una asignación muy desigual puede ser perfectamente eficiente.',
  },
  {
    id: 'eco-009', tema: 'escasez', dificultad: 3,
    enunciado: '¿Por qué la frontera de posibilidades de producción suele dibujarse cóncava y no como una recta?',
    opciones: [
      'Porque los recursos no son igualmente productivos en todos los usos, y el costo de oportunidad aumenta a medida que se especializa',
      'Porque la población crece con el tiempo',
      'Porque los precios cambian',
      'Por una simple convención gráfica',
    ],
    correcta: 0,
    explicacion: 'Al pasar de producir alimentos a producir máquinas se emplean primero los recursos más aptos. Cada unidad adicional exige sacrificar cada vez más del otro bien.',
  },
  {
    id: 'eco-010', tema: 'escasez', dificultad: 3,
    enunciado: '¿Qué es un costo hundido y por qué no debería influir en una decisión?',
    opciones: [
      'Es un gasto ya realizado e irrecuperable, y como no cambia con la decisión, considerarlo lleva a errores',
      'Es un costo futuro que conviene anticipar',
      'Es el costo de oportunidad de una inversión',
      'Es el costo de cerrar una empresa',
    ],
    correcta: 0,
    explicacion: 'Seguir viendo una película aburrida porque ya se pagó la entrada es la falacia del costo hundido: el dinero no vuelve, y lo único que está en juego es el tiempo que queda.',
    pista: 'Pregúntate qué cambia según lo que decidas ahora: lo que ya ocurrió, no.',
  },
  {
    id: 'eco-011', tema: 'escasez', dificultad: 3,
    enunciado: '¿Qué significa razonar "en el margen" en economía?',
    opciones: [
      'Evaluar el beneficio y el costo de una unidad adicional, no del total',
      'Considerar solo las actividades poco rentables',
      'Trabajar con los datos menos importantes',
      'Calcular el promedio de todos los costos',
    ],
    correcta: 0,
    explicacion: 'La decisión relevante casi nunca es todo o nada: no es si beber agua o diamantes, sino si conviene una unidad más de cada cosa dada la situación actual.',
  },
  {
    id: 'eco-012', tema: 'escasez', dificultad: 3,
    enunciado: '¿Qué diferencia hay entre economía positiva y normativa?',
    opciones: [
      'La positiva describe cómo funciona la economía; la normativa dice cómo debería funcionar',
      'La positiva estudia el crecimiento y la normativa las crisis',
      'La positiva usa datos y la normativa también, sin diferencia',
      'La normativa se ocupa de las leyes vigentes',
    ],
    correcta: 0,
    explicacion: '"Un aumento del salario mínimo reduce el empleo formal" es positiva y se contrasta con datos. "El salario mínimo debería subir" es normativa e implica un juicio de valor.',
  },
  {
    id: 'eco-013', tema: 'escasez', dificultad: 4,
    enunciado: '¿Por qué el supuesto del agente perfectamente racional ha sido cuestionado?',
    opciones: [
      'Porque la evidencia experimental muestra sesgos sistemáticos: aversión a la pérdida, exceso de confianza y decisiones dependientes de cómo se presenta la opción',
      'Porque las personas nunca calculan nada',
      'Porque la economía no puede usar modelos',
      'Porque los precios no influyen en las decisiones',
    ],
    correcta: 0,
    explicacion: 'Kahneman y Tversky documentaron esos patrones y dieron origen a la economía del comportamiento. No son errores aleatorios: son predecibles, y por eso se pueden modelar.',
  },
  {
    id: 'eco-014', tema: 'escasez', dificultad: 4,
    enunciado: 'Un país invierte todo en consumo presente y nada en educación o infraestructura. ¿Qué ocurre con su frontera de posibilidades?',
    opciones: [
      'Se mantiene o se contrae en el futuro, porque no se amplía la capacidad productiva',
      'Se desplaza hacia afuera automáticamente',
      'No hay relación entre inversión y frontera',
      'Se vuelve una línea recta',
    ],
    correcta: 0,
    explicacion: 'Elegir entre consumo presente y bienes de capital es una decisión intertemporal: lo que se deja de consumir hoy es lo que permite producir más mañana.',
  },
  {
    id: 'eco-015', tema: 'escasez', dificultad: 4,
    enunciado: '¿Por qué decir que "el Estado debería gastar más en salud" no se resuelve solo con datos económicos?',
    opciones: [
      'Porque implica un juicio sobre prioridades: los datos dicen qué cuesta y qué efectos tiene, no qué vale más',
      'Porque no existen datos sobre salud',
      'Porque el gasto público no puede medirse',
      'Porque la economía no estudia el sector público',
    ],
    correcta: 0,
    explicacion: 'La economía puede estimar el costo de oportunidad de destinar recursos a salud en lugar de a educación. Cuál de los dos importa más es una decisión política, no técnica.',
  },

  // ----- Oferta, demanda y precios -----
  {
    id: 'eco-016', tema: 'oferta-demanda', dificultad: 1,
    enunciado: 'Según la ley de la demanda, si el precio de un bien sube:',
    opciones: [
      'La cantidad demandada tiende a bajar',
      'La cantidad demandada tiende a subir',
      'La demanda no se ve afectada',
      'La oferta desaparece',
    ],
    correcta: 0,
    explicacion: 'Se cumple manteniendo todo lo demás constante. El encarecimiento lleva a comprar menos o a buscar sustitutos.',
  },
  {
    id: 'eco-017', tema: 'oferta-demanda', dificultad: 1,
    enunciado: 'Según la ley de la oferta, si el precio de un bien sube:',
    opciones: [
      'Los productores están dispuestos a ofrecer una cantidad mayor',
      'Los productores ofrecen menos',
      'La oferta no cambia',
      'Los consumidores compran más',
    ],
    correcta: 0,
    explicacion: 'Un precio más alto hace rentable producir unidades que antes no compensaban. Por eso la curva de oferta tiene pendiente positiva.',
  },
  {
    id: 'eco-018', tema: 'oferta-demanda', dificultad: 1,
    enunciado: '¿Qué es el precio de equilibrio?',
    opciones: [
      'Aquel en el que la cantidad ofrecida iguala a la cantidad demandada',
      'El precio más bajo posible del mercado',
      'El precio fijado por el gobierno',
      'El costo de producción de un bien',
    ],
    correcta: 0,
    explicacion: 'En ese punto no hay presión al alza ni a la baja: el mercado se vacía, sin excedente ni escasez.',
  },
  {
    id: 'eco-019', tema: 'oferta-demanda', dificultad: 2,
    enunciado: 'Si el precio está por encima del equilibrio, ¿qué ocurre?',
    opciones: [
      'Hay excedente: se ofrece más de lo que se demanda y el precio tiende a bajar',
      'Hay escasez y el precio sube',
      'El mercado se mantiene estable',
      'Desaparece la oferta',
    ],
    correcta: 0,
    explicacion: 'El invendido presiona a la baja. Si el precio estuviera por debajo del equilibrio ocurriría lo contrario: faltaría producto y el precio subiría.',
  },
  {
    id: 'eco-020', tema: 'oferta-demanda', dificultad: 2,
    enunciado: '¿Qué desplaza la curva de demanda hacia la derecha?',
    opciones: [
      'Un aumento del ingreso de los consumidores, si el bien es normal',
      'Una subida del precio del propio bien',
      'Una bajada del precio del propio bien',
      'Un aumento de los costos de producción',
    ],
    correcta: 0,
    explicacion: 'El precio del propio bien mueve a lo largo de la curva; lo que la desplaza son otros factores: ingreso, gustos, precio de sustitutos o complementarios y expectativas.',
    pista: 'Distingue "moverse sobre la curva" de "mover la curva entera".',
  },
  {
    id: 'eco-021', tema: 'oferta-demanda', dificultad: 2,
    enunciado: 'Si sube el precio del café, ¿qué ocurre con la demanda de té, su sustituto?',
    opciones: ['Aumenta', 'Disminuye', 'No cambia', 'Desaparece'],
    correcta: 0,
    explicacion: 'Los bienes sustitutos satisfacen una necesidad parecida. Con los complementarios pasa lo contrario: si sube el precio de los carros, baja la demanda de gasolina.',
  },
  {
    id: 'eco-022', tema: 'oferta-demanda', dificultad: 2,
    enunciado: '¿Qué mide la elasticidad precio de la demanda?',
    opciones: [
      'Cuánto varía la cantidad demandada ante un cambio en el precio',
      'Cuánto tarda el mercado en llegar al equilibrio',
      'La diferencia entre oferta y demanda',
      'El margen de ganancia del productor',
    ],
    correcta: 0,
    explicacion: 'La demanda de sal es inelástica: aunque suba el precio se sigue comprando casi lo mismo. La de un restaurante concreto es elástica: hay muchas alternativas.',
  },
  {
    id: 'eco-023', tema: 'oferta-demanda', dificultad: 2,
    enunciado: 'Una sequía destruye parte de la cosecha de arroz. ¿Qué se espera?',
    opciones: [
      'La curva de oferta se desplaza a la izquierda y el precio de equilibrio sube',
      'La curva de demanda se desplaza a la derecha',
      'El precio baja por falta de producto',
      'No hay efecto sobre el precio',
    ],
    correcta: 0,
    explicacion: 'Menos producto disponible a cada precio significa oferta reducida. Con la demanda intacta, el nuevo equilibrio tiene precio más alto y cantidad menor.',
  },
  {
    id: 'eco-024', tema: 'oferta-demanda', dificultad: 3,
    enunciado: 'El gobierno fija un precio máximo por debajo del equilibrio para un alimento básico. ¿Qué efecto es previsible?',
    opciones: [
      'Escasez del producto y aparición de mercados informales',
      'Excedente del producto en las tiendas',
      'Aumento inmediato de la producción',
      'Ningún efecto sobre la cantidad ofrecida',
    ],
    correcta: 0,
    explicacion: 'A ese precio se demanda más de lo que se produce. La medida busca proteger al consumidor y termina reduciendo la disponibilidad, salvo que se acompañe de otras políticas.',
  },
  {
    id: 'eco-025', tema: 'oferta-demanda', dificultad: 3,
    enunciado: '¿Por qué la demanda de medicamentos esenciales suele ser inelástica?',
    opciones: [
      'Porque no tienen sustitutos y son necesarios, así que se compran aunque suba el precio',
      'Porque son muy baratos',
      'Porque el Estado los produce',
      'Porque su demanda es estacional',
    ],
    correcta: 0,
    explicacion: 'Eso da mucho poder de fijación de precios a quien los produce, y es la razón económica que justifica la regulación de precios en ese mercado.',
  },
  {
    id: 'eco-026', tema: 'oferta-demanda', dificultad: 3,
    enunciado: 'Si un bien es inelástico y el productor sube el precio un 10 %, ¿qué pasa con sus ingresos?',
    opciones: [
      'Aumentan, porque la cantidad vendida cae menos que proporcionalmente',
      'Disminuyen siempre',
      'Se mantienen exactamente iguales',
      'Dependen solo de los costos',
    ],
    correcta: 0,
    explicacion: 'Con demanda elástica ocurre lo contrario: subir el precio reduce tanto las ventas que el ingreso total cae. Por eso conocer la elasticidad es clave para fijar precios.',
  },
  {
    id: 'eco-027', tema: 'oferta-demanda', dificultad: 3,
    enunciado: '¿Qué es un bien inferior?',
    opciones: [
      'Aquel cuya demanda disminuye cuando aumenta el ingreso del consumidor',
      'Aquel de baja calidad',
      'Aquel que tiene precio bajo',
      'Aquel que no se puede exportar',
    ],
    correcta: 0,
    explicacion: 'No se refiere a la calidad sino al comportamiento de la demanda: al mejorar el ingreso, muchas familias sustituyen el transporte público por uno propio, por ejemplo.',
  },
  {
    id: 'eco-028', tema: 'oferta-demanda', dificultad: 4,
    enunciado: 'Un impuesto se aplica a la venta de un bien con demanda muy inelástica. ¿Quién soporta la mayor parte de la carga?',
    opciones: [
      'El consumidor, porque no puede reducir mucho su consumo ante el alza del precio',
      'El productor, siempre',
      'Se reparte exactamente por mitades',
      'El Estado asume la carga',
    ],
    correcta: 0,
    explicacion: 'La incidencia fiscal no depende de a quién se le cobre legalmente el impuesto, sino de las elasticidades: la parte menos capaz de reaccionar es la que paga.',
  },
  {
    id: 'eco-029', tema: 'oferta-demanda', dificultad: 4,
    enunciado: '¿Por qué los precios funcionan como señales en una economía de mercado?',
    opciones: [
      'Porque transmiten información dispersa sobre escasez y preferencias, y coordinan decisiones sin que nadie las dirija',
      'Porque los fija una autoridad central informada',
      'Porque reflejan siempre el costo de producción exacto',
      'Porque garantizan una distribución justa',
    ],
    correcta: 0,
    explicacion: 'Es el argumento de Hayek sobre el conocimiento disperso. Un precio alto avisa de escasez y atrae producción sin que nadie tenga que saber por qué escasea.',
  },
  {
    id: 'eco-030', tema: 'oferta-demanda', dificultad: 4,
    enunciado: 'Tras un desastre natural, el precio del agua embotellada se dispara. ¿Qué tensión plantea ese caso?',
    opciones: [
      'El precio alto incentiva el abastecimiento y raciona el consumo, pero excluye a quien no puede pagar un bien de primera necesidad',
      'No hay ninguna tensión: el precio siempre es justo',
      'El precio alto no tiene efecto sobre la oferta',
      'La demanda desaparece en las emergencias',
    ],
    correcta: 0,
    explicacion: 'Es el debate sobre el "precio abusivo" en emergencias. La eficiencia asignativa y la equidad apuntan aquí en direcciones opuestas, y por eso muchos países lo regulan.',
  },
  // ----- Mercados y competencia -----
  {
    id: 'eco-031', tema: 'mercados', dificultad: 1,
    enunciado: '¿Qué caracteriza a un monopolio?',
    opciones: [
      'Un único vendedor controla el mercado de un bien sin sustitutos cercanos',
      'Muchos vendedores compiten en igualdad',
      'Solo hay un comprador',
      'Los precios los fija el gobierno',
    ],
    correcta: 0,
    explicacion: 'Al no haber competencia, el monopolista puede fijar precio o cantidad. Cuando hay un único comprador se habla de monopsonio.',
  },
  {
    id: 'eco-032', tema: 'mercados', dificultad: 1,
    enunciado: '¿Qué es un bien público?',
    opciones: [
      'Aquel cuyo consumo por una persona no impide el de otra y del que nadie puede ser excluido, como el alumbrado',
      'Cualquier bien producido por el Estado',
      'Un bien que se vende barato',
      'Un servicio prestado por una empresa pública',
    ],
    correcta: 0,
    explicacion: 'Lo definen la no rivalidad y la no exclusión, no quién lo produzca. Por eso el mercado los provee mal: nadie pagaría por algo de lo que no puede excluirse a los demás.',
  },
  {
    id: 'eco-033', tema: 'mercados', dificultad: 1,
    enunciado: '¿Qué es una externalidad negativa?',
    opciones: [
      'Un costo que la actividad de alguien impone a terceros sin compensarlo, como la contaminación',
      'Una pérdida contable de la empresa',
      'Un impuesto que paga el productor',
      'Una deuda con proveedores externos',
    ],
    correcta: 0,
    explicacion: 'El precio de mercado no la recoge, y por eso se produce más de lo socialmente deseable. Los impuestos ambientales buscan justamente internalizar ese costo.',
  },
  {
    id: 'eco-034', tema: 'mercados', dificultad: 2,
    enunciado: '¿Qué condiciones definen la competencia perfecta?',
    opciones: [
      'Muchos compradores y vendedores, producto homogéneo, información completa y libre entrada y salida',
      'Un solo productor con precios bajos',
      'Pocas empresas que acuerdan precios',
      'Un mercado regulado por el Estado',
    ],
    correcta: 0,
    explicacion: 'Es un modelo de referencia más que una descripción: casi ningún mercado real lo cumple. Sirve para medir cuánto se aleja un mercado concreto del ideal.',
  },
  {
    id: 'eco-035', tema: 'mercados', dificultad: 2,
    enunciado: '¿Qué es un oligopolio?',
    opciones: [
      'Un mercado dominado por pocas empresas, cuyas decisiones se afectan mutuamente',
      'Un mercado con un solo vendedor',
      'Un mercado sin barreras de entrada',
      'Un mercado exclusivamente estatal',
    ],
    correcta: 0,
    explicacion: 'La interdependencia es su rasgo clave: cada empresa debe anticipar la reacción de las demás. Por eso se analiza con teoría de juegos.',
  },
  {
    id: 'eco-036', tema: 'mercados', dificultad: 2,
    enunciado: '¿Qué es un cartel y por qué está prohibido?',
    opciones: [
      'Un acuerdo entre competidores para fijar precios o repartirse el mercado, que perjudica al consumidor',
      'Una asociación de consumidores',
      'Un tipo de empresa pública',
      'Un contrato de distribución exclusiva',
    ],
    correcta: 0,
    explicacion: 'Elimina la competencia sin que el consumidor lo note. En Colombia lo investiga y sanciona la Superintendencia de Industria y Comercio.',
  },
  {
    id: 'eco-037', tema: 'mercados', dificultad: 2,
    enunciado: '¿Qué es una externalidad positiva?',
    opciones: [
      'Un beneficio que la actividad de alguien genera a terceros sin cobrarlo, como la vacunación',
      'Una ganancia extraordinaria de la empresa',
      'Un subsidio estatal',
      'Una donación empresarial',
    ],
    correcta: 0,
    explicacion: 'Quien se vacuna protege también a quienes lo rodean. Como el beneficio social supera al privado, el mercado produce menos de lo deseable y se justifica subsidiarla.',
  },
  {
    id: 'eco-038', tema: 'mercados', dificultad: 2,
    enunciado: '¿Qué es la información asimétrica?',
    opciones: [
      'Una situación en la que una parte de la transacción sabe más que la otra sobre lo que se negocia',
      'Un error en las estadísticas oficiales',
      'La diferencia de precios entre regiones',
      'La falta de publicidad de un producto',
    ],
    correcta: 0,
    explicacion: 'El vendedor de un carro usado conoce sus fallas; el comprador no. Akerlof mostró que eso puede hundir un mercado entero al expulsar a los productos buenos.',
  },
  {
    id: 'eco-039', tema: 'mercados', dificultad: 3,
    enunciado: '¿Qué es un monopolio natural y qué implica para la política pública?',
    opciones: [
      'Un mercado donde una sola empresa produce a menor costo por las enormes economías de escala, lo que justifica regulación en vez de competencia forzada',
      'Un monopolio creado por recursos naturales escasos',
      'Un monopolio que surge sin intervención estatal y debe dejarse operar libremente',
      'Un mercado con muchas empresas pequeñas',
    ],
    correcta: 0,
    explicacion: 'Duplicar redes de acueducto o de transmisión eléctrica sería absurdo. La respuesta habitual es permitir una sola empresa pero regular sus tarifas y su calidad.',
  },
  {
    id: 'eco-040', tema: 'mercados', dificultad: 3,
    enunciado: '¿Qué es la tragedia de los comunes?',
    opciones: [
      'La sobreexplotación de un recurso de acceso abierto porque cada usuario obtiene el beneficio completo y comparte el costo',
      'La quiebra de las empresas públicas',
      'La escasez de bienes de lujo',
      'El exceso de regulación estatal',
    ],
    correcta: 0,
    explicacion: 'Pesquerías, acuíferos y atmósfera funcionan así. Elinor Ostrom documentó que muchas comunidades lo resuelven con reglas propias, sin necesidad de privatizar ni estatizar.',
  },
  {
    id: 'eco-041', tema: 'mercados', dificultad: 3,
    enunciado: '¿Por qué se regula la publicidad engañosa desde una perspectiva económica?',
    opciones: [
      'Porque corrige una falla de información que impide al consumidor decidir con base en datos verdaderos',
      'Porque encarece los productos',
      'Porque la publicidad no genera empleo',
      'Porque reduce la competencia entre empresas',
    ],
    correcta: 0,
    explicacion: 'Un mercado funciona bien si quien compra sabe qué compra. La regulación no sustituye la decisión del consumidor: restablece las condiciones para que sea informada.',
  },
  {
    id: 'eco-042', tema: 'mercados', dificultad: 3,
    enunciado: '¿Qué justifica que el Estado provea o financie la educación básica?',
    opciones: [
      'Sus externalidades positivas y el hecho de que el mercado la proveería por debajo de lo socialmente deseable',
      'Que es más barato producirla públicamente',
      'Que se trata de un bien público puro',
      'Que ninguna empresa privada puede ofrecerla',
    ],
    correcta: 0,
    explicacion: 'La educación es excluible y rival, así que no es un bien público en sentido estricto. Lo que justifica la intervención son sus beneficios sociales y los problemas de acceso y de crédito.',
  },
  {
    id: 'eco-043', tema: 'mercados', dificultad: 4,
    enunciado: '¿Qué es el riesgo moral y por qué importa en los seguros?',
    opciones: [
      'La tendencia a asumir más riesgos cuando otro asume las consecuencias, como conducir con menos cuidado por estar asegurado',
      'La posibilidad de que el asegurado mienta al contratar',
      'El costo de los siniestros imprevistos',
      'La obligación ética de la aseguradora',
    ],
    correcta: 0,
    explicacion: 'Se distingue de la selección adversa, que ocurre antes del contrato: ahí el problema es quién decide asegurarse. Deducibles y copagos existen para mitigar el riesgo moral.',
  },
  {
    id: 'eco-044', tema: 'mercados', dificultad: 4,
    enunciado: 'Una empresa dominante vende por debajo de costo para expulsar competidores. ¿Por qué preocupa a las autoridades de competencia?',
    opciones: [
      'Porque el beneficio al consumidor es temporal: una vez eliminada la competencia, los precios suben y la entrada de rivales se vuelve difícil',
      'Porque vender barato es siempre ilegal',
      'Porque reduce los ingresos fiscales',
      'Porque perjudica de inmediato al consumidor',
    ],
    correcta: 0,
    explicacion: 'Es la práctica llamada precios predatorios. Lo difícil para el regulador es distinguirla de una competencia agresiva legítima, y por eso los casos son largos y discutidos.',
  },
  {
    id: 'eco-045', tema: 'mercados', dificultad: 4,
    enunciado: '¿Qué problema plantean los efectos de red en las plataformas digitales?',
    opciones: [
      'El valor del servicio crece con el número de usuarios, lo que tiende a producir mercados concentrados difíciles de disputar',
      'Que las plataformas no generan ingresos',
      'Que la tecnología cambia demasiado rápido para regular',
      'Que los usuarios pagan precios excesivos',
    ],
    correcta: 0,
    explicacion: 'Nadie se cambia a una red social vacía aunque sea mejor. La concentración no viene de una conducta abusiva sino de la propia lógica del producto, y eso complica la respuesta regulatoria.',
  },

  // ----- Indicadores macroeconómicos -----
  {
    id: 'eco-046', tema: 'indicadores', dificultad: 1,
    enunciado: '¿Qué mide el Producto Interno Bruto (PIB)?',
    opciones: [
      'El valor de todos los bienes y servicios finales producidos en un país durante un periodo',
      'La riqueza acumulada de un país',
      'El total de dinero en circulación',
      'El ingreso promedio de las familias',
    ],
    correcta: 0,
    explicacion: 'Es un flujo anual o trimestral, no un inventario. Se cuentan solo los bienes finales para no sumar dos veces los insumos.',
  },
  {
    id: 'eco-047', tema: 'indicadores', dificultad: 1,
    enunciado: '¿Qué es la inflación?',
    opciones: [
      'El aumento generalizado y sostenido de los precios, que reduce el poder adquisitivo',
      'La subida del precio de un solo producto',
      'El aumento de los salarios',
      'El crecimiento de la economía',
    ],
    correcta: 0,
    explicacion: 'Que suba el tomate no es inflación. Lo que se mide es el nivel general de precios, a través de una canasta representativa de consumo.',
  },
  {
    id: 'eco-048', tema: 'indicadores', dificultad: 1,
    enunciado: '¿Quién forma parte de la población económicamente activa?',
    opciones: [
      'Las personas en edad de trabajar que están ocupadas o buscando empleo',
      'Todos los habitantes del país',
      'Solo quienes tienen contrato formal',
      'Únicamente los desempleados',
    ],
    correcta: 0,
    explicacion: 'Quien no trabaja ni busca trabajo —estudiantes, jubilados, personas dedicadas al hogar— queda fuera de la fuerza laboral y no cuenta como desempleado.',
  },
  {
    id: 'eco-049', tema: 'indicadores', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre PIB nominal y PIB real?',
    opciones: [
      'El real descuenta el efecto de la inflación y permite comparar entre años',
      'El nominal se mide en dólares y el real en pesos',
      'El real incluye la economía informal',
      'El nominal solo cuenta las exportaciones',
    ],
    correcta: 0,
    explicacion: 'Si los precios suben un 10 % y la producción no cambia, el PIB nominal crece un 10 % sin que se produzca una sola unidad más. El PIB real corrige esa ilusión.',
  },
  {
    id: 'eco-050', tema: 'indicadores', dificultad: 2,
    enunciado: '¿Qué mide el IPC?',
    opciones: [
      'La variación del precio de una canasta de bienes y servicios representativa del consumo de los hogares',
      'El precio de los productos exportados',
      'El costo de producción de las empresas',
      'El valor del dólar',
    ],
    correcta: 0,
    explicacion: 'En Colombia lo calcula el DANE y sirve de referencia para ajustar salarios, arriendos y pensiones.',
  },
  {
    id: 'eco-051', tema: 'indicadores', dificultad: 2,
    enunciado: '¿Cómo se calcula la tasa de desempleo?',
    opciones: [
      'Desocupados dividido entre la población económicamente activa, por cien',
      'Desocupados dividido entre la población total',
      'Ocupados dividido entre la población en edad de trabajar',
      'Informales dividido entre ocupados',
    ],
    correcta: 0,
    explicacion: 'El denominador es la fuerza laboral, no toda la población. Por eso una caída del desempleo puede deberse a que la gente dejó de buscar trabajo, y no a que encontró empleo.',
  },
  {
    id: 'eco-052', tema: 'indicadores', dificultad: 2,
    enunciado: '¿Qué es el PIB per cápita?',
    opciones: [
      'El PIB dividido entre el número de habitantes, usado como aproximación al nivel de vida promedio',
      'El ingreso del trabajador promedio',
      'El gasto público por habitante',
      'El salario mínimo anualizado',
    ],
    correcta: 0,
    explicacion: 'Es un promedio y como tal oculta la distribución: dos países con el mismo PIB per cápita pueden tener realidades sociales muy distintas.',
  },
  {
    id: 'eco-053', tema: 'indicadores', dificultad: 2,
    enunciado: '¿Qué es una recesión?',
    opciones: [
      'Una caída sostenida de la actividad económica, habitualmente dos trimestres consecutivos de PIB negativo',
      'Cualquier aumento del desempleo',
      'Una subida general de los precios',
      'Una devaluación de la moneda',
    ],
    correcta: 0,
    explicacion: 'La regla de los dos trimestres es una convención práctica. Organismos como el NBER estadounidense consideran también empleo, ingresos y producción industrial.',
  },
  {
    id: 'eco-054', tema: 'indicadores', dificultad: 3,
    enunciado: '¿Por qué el PIB es una medida incompleta del bienestar?',
    opciones: [
      'No registra el trabajo no remunerado ni la distribución, e incluye como positivo el gasto en reparar daños',
      'Porque se calcula con datos falsos',
      'Porque no incluye a las empresas privadas',
      'Porque solo mide exportaciones',
    ],
    correcta: 0,
    explicacion: 'Un derrame de petróleo aumenta el PIB por el gasto en limpieza. El trabajo doméstico, que sostiene la economía, no aparece por ninguna parte.',
  },
  {
    id: 'eco-055', tema: 'indicadores', dificultad: 3,
    enunciado: 'Si la inflación anual es del 8 % y un salario sube un 5 %, ¿qué ocurre con el poder adquisitivo?',
    opciones: [
      'Disminuye alrededor de un 3 %, porque los precios subieron más que el salario',
      'Aumenta un 5 %',
      'Se mantiene igual',
      'Aumenta un 3 %',
    ],
    correcta: 0,
    explicacion: 'Lo que importa es el salario real, no el nominal. Ganar más pesos no significa poder comprar más si los precios corrieron más rápido.',
  },
  {
    id: 'eco-056', tema: 'indicadores', dificultad: 3,
    enunciado: '¿Qué es la informalidad laboral y por qué el desempleo no la captura?',
    opciones: [
      'Es el trabajo sin protección social ni contrato; quien está en él figura como ocupado aunque su situación sea precaria',
      'Es sinónimo de desempleo',
      'Es el trabajo en empresas pequeñas, siempre protegido',
      'Es el empleo público sin concurso',
    ],
    correcta: 0,
    explicacion: 'Por eso en países como Colombia la tasa de desempleo cuenta solo una parte del problema: buena parte de los ocupados no cotiza a pensión ni tiene estabilidad.',
  },
  {
    id: 'eco-057', tema: 'indicadores', dificultad: 3,
    enunciado: '¿Qué mide el Índice de Desarrollo Humano?',
    opciones: [
      'Combina ingreso, educación y esperanza de vida para evaluar el desarrollo más allá del PIB',
      'Únicamente el ingreso per cápita',
      'La desigualdad de un país',
      'El nivel de industrialización',
    ],
    correcta: 0,
    explicacion: 'Nació del enfoque de capacidades de Amartya Sen. Un país puede tener buen PIB per cápita y un IDH mediocre si su población vive poco o estudia poco.',
  },
  {
    id: 'eco-058', tema: 'indicadores', dificultad: 4,
    enunciado: '¿Por qué una tasa de desempleo que baja no siempre es buena noticia?',
    opciones: [
      'Porque puede reflejar que personas desalentadas dejaron de buscar trabajo y salieron de la fuerza laboral',
      'Porque significa que hay más informalidad, siempre',
      'Porque el indicador se calcula mal',
      'Porque implica inflación automática',
    ],
    correcta: 0,
    explicacion: 'Al reducirse el denominador, el porcentaje cae sin que haya más empleo. Por eso conviene mirar también la tasa de ocupación y la de participación.',
    pista: 'Revisa qué pasa con el denominador del indicador, no solo con el numerador.',
  },
  {
    id: 'eco-059', tema: 'indicadores', dificultad: 4,
    enunciado: '¿Qué es la estanflación y por qué es difícil de combatir?',
    opciones: [
      'La combinación de estancamiento con inflación alta: las políticas para frenar los precios agravan el desempleo y viceversa',
      'Una inflación muy baja con crecimiento alto',
      'Una recesión con deflación',
      'Un crecimiento sostenido con pleno empleo',
    ],
    correcta: 0,
    explicacion: 'Ocurrió en los años setenta tras la crisis del petróleo. Rompió la idea de que siempre existe un intercambio estable entre inflación y desempleo.',
  },
  {
    id: 'eco-060', tema: 'indicadores', dificultad: 4,
    enunciado: '¿Por qué la inflación perjudica más a los hogares de menores ingresos?',
    opciones: [
      'Porque destinan una proporción mayor de su gasto a alimentos y servicios básicos, y tienen menos activos que se revalorizan',
      'Porque pagan más impuestos',
      'Porque sus salarios se indexan automáticamente',
      'Porque ahorran una parte mayor de su ingreso',
    ],
    correcta: 0,
    explicacion: 'La inflación de alimentos suele superar a la general, y quien vive al día no puede protegerse comprando activos. Por eso se la llama a veces el impuesto más regresivo.',
  },
  // ----- Dinero, banca y política monetaria -----
  {
    id: 'eco-061', tema: 'dinero', dificultad: 1,
    enunciado: '¿Cuáles son las funciones del dinero?',
    opciones: [
      'Medio de pago, unidad de cuenta y depósito de valor',
      'Producir bienes, distribuirlos y consumirlos',
      'Ahorrar, invertir y gastar',
      'Medir el PIB, la inflación y el desempleo',
    ],
    correcta: 0,
    explicacion: 'Sin dinero habría que recurrir al trueque, que exige una coincidencia improbable de necesidades entre las dos partes.',
  },
  {
    id: 'eco-062', tema: 'dinero', dificultad: 1,
    enunciado: '¿Cuál es la función principal de un banco comercial?',
    opciones: [
      'Captar ahorro del público y prestarlo a quienes necesitan financiación',
      'Emitir billetes y monedas',
      'Fijar la tasa de interés de intervención',
      'Recaudar impuestos',
    ],
    correcta: 0,
    explicacion: 'Es intermediación financiera: conecta a quien tiene excedente con quien necesita recursos. Emitir moneda corresponde al banco central.',
  },
  {
    id: 'eco-063', tema: 'dinero', dificultad: 1,
    enunciado: '¿Cuál es el objetivo principal del Banco de la República?',
    opciones: [
      'Mantener el poder adquisitivo de la moneda, es decir, controlar la inflación',
      'Financiar el gasto del Gobierno',
      'Otorgar créditos a las empresas',
      'Fijar el salario mínimo',
    ],
    correcta: 0,
    explicacion: 'La Constitución de 1991 le dio autonomía precisamente para que ese objetivo no quedara subordinado a las necesidades fiscales del Gobierno de turno.',
  },
  {
    id: 'eco-064', tema: 'dinero', dificultad: 2,
    enunciado: 'Si el banco central sube la tasa de interés de intervención, ¿qué se espera?',
    opciones: [
      'Que el crédito se encarezca, se enfríe la demanda y ceda la inflación',
      'Que aumente el consumo de los hogares',
      'Que suban los precios de inmediato',
      'Que se incremente la inversión empresarial',
    ],
    correcta: 0,
    explicacion: 'Endeudarse cuesta más y ahorrar rinde más, así que el gasto se frena. El costo es un menor crecimiento en el corto plazo: ese es el dilema de la política monetaria.',
  },
  {
    id: 'eco-065', tema: 'dinero', dificultad: 2,
    enunciado: '¿Qué es la tasa de interés real?',
    opciones: [
      'La tasa nominal descontada la inflación',
      'La tasa que cobran los bancos privados',
      'La tasa fijada por el banco central',
      'El promedio de las tasas del mercado',
    ],
    correcta: 0,
    explicacion: 'Si un depósito rinde 10 % y la inflación es 12 %, la tasa real es negativa: el ahorrador pierde poder de compra aunque su saldo aumente.',
  },
  {
    id: 'eco-066', tema: 'dinero', dificultad: 2,
    enunciado: '¿Qué diferencia hay entre política monetaria y política fiscal?',
    opciones: [
      'La monetaria maneja tasas y cantidad de dinero desde el banco central; la fiscal, impuestos y gasto desde el Gobierno',
      'La monetaria la decide el Congreso',
      'La fiscal regula la emisión de billetes',
      'Son dos nombres para lo mismo',
    ],
    correcta: 0,
    explicacion: 'Separarlas institucionalmente busca evitar que un gobierno financie déficits emitiendo dinero, mecanismo que históricamente ha terminado en inflación alta.',
  },
  {
    id: 'eco-067', tema: 'dinero', dificultad: 2,
    enunciado: '¿Qué es el encaje bancario?',
    opciones: [
      'La proporción de los depósitos que los bancos deben mantener sin prestar',
      'El interés que los bancos pagan a los ahorradores',
      'La comisión por transferencias',
      'El capital mínimo para fundar un banco',
    ],
    correcta: 0,
    explicacion: 'Sirve para la liquidez del sistema y como instrumento de política monetaria: subir el encaje reduce el dinero que los bancos pueden prestar.',
  },
  {
    id: 'eco-068', tema: 'dinero', dificultad: 2,
    enunciado: '¿Qué es la inflación de demanda?',
    opciones: [
      'La que ocurre cuando el gasto agregado crece más rápido que la capacidad productiva',
      'La causada por el alza de los costos de producción',
      'La provocada por una devaluación',
      'La que resulta de una mala cosecha',
    ],
    correcta: 0,
    explicacion: 'Se resume como demasiado dinero persiguiendo pocos bienes. La inflación de costos, en cambio, viene del lado de la oferta: petróleo, salarios o insumos importados.',
  },
  {
    id: 'eco-069', tema: 'dinero', dificultad: 3,
    enunciado: '¿Por qué financiar el gasto público emitiendo dinero suele producir inflación?',
    opciones: [
      'Porque aumenta la cantidad de dinero sin que aumente la producción de bienes',
      'Porque los bancos dejan de prestar',
      'Porque sube el desempleo de inmediato',
      'Porque se reduce la recaudación de impuestos',
    ],
    correcta: 0,
    explicacion: 'Más pesos compitiendo por la misma cantidad de bienes elevan los precios. A ese efecto se le llama impuesto inflacionario: nadie lo aprueba, pero todos lo pagan.',
  },
  {
    id: 'eco-070', tema: 'dinero', dificultad: 3,
    enunciado: '¿Qué es una corrida bancaria?',
    opciones: [
      'El retiro masivo y simultáneo de depósitos, que ningún banco puede atender porque prestó la mayor parte',
      'La quiebra de una empresa industrial',
      'El aumento repentino de los créditos otorgados',
      'La fusión de dos entidades financieras',
    ],
    correcta: 0,
    explicacion: 'Es un problema de expectativas: basta con que muchos crean que el banco caerá para que caiga. El seguro de depósitos existe para romper esa profecía autocumplida.',
  },
  {
    id: 'eco-071', tema: 'dinero', dificultad: 3,
    enunciado: '¿Por qué las tarjetas de crédito suelen tener tasas más altas que un crédito hipotecario?',
    opciones: [
      'Porque no tienen garantía respaldando la deuda y el riesgo de impago es mayor',
      'Porque los plazos son más largos',
      'Porque los bancos las promueven menos',
      'Porque están prohibidas para montos altos',
    ],
    correcta: 0,
    explicacion: 'En una hipoteca el inmueble respalda el préstamo; si se incumple, el banco lo recupera. Sin garantía, el mayor riesgo se traslada al precio del crédito.',
  },
  {
    id: 'eco-072', tema: 'dinero', dificultad: 3,
    enunciado: '¿Qué implica que un crédito se pacte a tasa variable?',
    opciones: [
      'Que la cuota puede subir o bajar según evolucione una tasa de referencia del mercado',
      'Que el banco puede cambiar el monto prestado',
      'Que el plazo se ajusta cada año',
      'Que no se pagan intereses el primer año',
    ],
    correcta: 0,
    explicacion: 'Quien toma una tasa variable asume el riesgo de que suban los tipos. La fija cuesta algo más al inicio y compra previsibilidad: es un intercambio entre precio y certeza.',
  },
  {
    id: 'eco-073', tema: 'dinero', dificultad: 4,
    enunciado: '¿Por qué se considera importante la independencia del banco central?',
    opciones: [
      'Porque un gobierno con control de la emisión tiene incentivos de corto plazo que terminan en inflación alta y pérdida de credibilidad',
      'Porque los técnicos saben más que los políticos en todos los temas',
      'Porque así se reduce el gasto público',
      'Porque lo exigen los organismos internacionales',
    ],
    correcta: 0,
    explicacion: 'Es un caso de inconsistencia temporal: lo que conviene antes de una elección no conviene a cinco años. La independencia funciona como un compromiso creíble frente a esa tentación.',
  },
  {
    id: 'eco-074', tema: 'dinero', dificultad: 4,
    enunciado: '¿Por qué la política monetaria pierde eficacia cuando las tasas están cerca de cero?',
    opciones: [
      'Porque no pueden bajar mucho más para estimular la economía, y aparece la llamada trampa de liquidez',
      'Porque los bancos dejan de existir',
      'Porque la inflación se vuelve imposible',
      'Porque el banco central pierde su independencia',
    ],
    correcta: 0,
    explicacion: 'Japón tras los noventa y las economías avanzadas tras 2008 llegaron a ese límite. De ahí surgieron herramientas no convencionales como la compra masiva de activos.',
  },
  {
    id: 'eco-075', tema: 'dinero', dificultad: 4,
    enunciado: '¿Qué riesgo introduce el sistema de reserva fraccionaria?',
    opciones: [
      'Los bancos prestan más de lo que guardan, así que son solventes a largo plazo pero vulnerables a una pérdida súbita de confianza',
      'Que el dinero pierda su valor automáticamente',
      'Que los bancos no puedan prestar nunca',
      'Que el banco central no pueda emitir',
    ],
    correcta: 0,
    explicacion: 'El sistema crea dinero y financia la inversión, pero convierte plazos cortos en largos. Esa transformación de vencimientos es útil y es exactamente donde está la fragilidad.',
  },

  // ----- Comercio internacional -----
  {
    id: 'eco-076', tema: 'internacional', dificultad: 1,
    enunciado: '¿Qué es un arancel?',
    opciones: [
      'Un impuesto que grava los productos importados',
      'Un subsidio a los exportadores',
      'Una cuota de producción nacional',
      'El precio internacional de una materia prima',
    ],
    correcta: 0,
    explicacion: 'Encarece el producto extranjero y protege al productor local, a costa de un precio más alto para el consumidor.',
  },
  {
    id: 'eco-077', tema: 'internacional', dificultad: 1,
    enunciado: '¿Qué es la balanza comercial?',
    opciones: [
      'La diferencia entre el valor de las exportaciones y el de las importaciones de un país',
      'El total de reservas internacionales',
      'La deuda externa acumulada',
      'El saldo del presupuesto nacional',
    ],
    correcta: 0,
    explicacion: 'Si las exportaciones superan a las importaciones hay superávit; en caso contrario, déficit. Es un componente de la balanza de pagos, que incluye además servicios y capitales.',
  },
  {
    id: 'eco-078', tema: 'internacional', dificultad: 1,
    enunciado: 'Si el peso se devalúa frente al dólar:',
    opciones: [
      'Las importaciones se encarecen y las exportaciones se vuelven más competitivas',
      'Las importaciones se abaratan',
      'No hay efecto sobre el comercio',
      'Bajan los precios internos de inmediato',
    ],
    correcta: 0,
    explicacion: 'Hacen falta más pesos por dólar, así que todo lo comprado afuera cuesta más. Para quien vende afuera, en cambio, los mismos dólares se convierten en más pesos.',
  },
  {
    id: 'eco-079', tema: 'internacional', dificultad: 2,
    enunciado: '¿Qué plantea la teoría de la ventaja comparativa de Ricardo?',
    opciones: [
      'Conviene que cada país se especialice en lo que produce con menor costo de oportunidad, aunque no sea el mejor en nada',
      'Solo debe comerciar quien produce más barato en términos absolutos',
      'El comercio siempre beneficia a un país y perjudica al otro',
      'Los países deben producir todo lo que consumen',
    ],
    correcta: 0,
    explicacion: 'Es contraintuitivo: un país menos productivo en todo puede ganar comerciando, porque lo relevante es a qué renuncia al producir cada bien, no la productividad absoluta.',
  },
  {
    id: 'eco-080', tema: 'internacional', dificultad: 2,
    enunciado: '¿Qué es el proteccionismo?',
    opciones: [
      'La política de restringir importaciones para favorecer la producción nacional',
      'La apertura total de los mercados',
      'La firma de tratados de libre comercio',
      'La eliminación de todos los impuestos',
    ],
    correcta: 0,
    explicacion: 'Aranceles, cuotas y subsidios son sus herramientas. Su justificación clásica es proteger industrias nacientes; su costo, precios más altos y menos competencia.',
  },
  {
    id: 'eco-081', tema: 'internacional', dificultad: 2,
    enunciado: '¿Qué es un tratado de libre comercio?',
    opciones: [
      'Un acuerdo entre países para reducir o eliminar aranceles y barreras al comercio entre ellos',
      'Un pacto para fijar precios internacionales',
      'Un préstamo entre gobiernos',
      'Una alianza militar con cláusulas comerciales',
    ],
    correcta: 0,
    explicacion: 'Colombia tiene varios, entre ellos el vigente con Estados Unidos desde 2012. Suelen incluir además reglas sobre inversión, propiedad intelectual y compras públicas.',
  },
  {
    id: 'eco-082', tema: 'internacional', dificultad: 2,
    enunciado: '¿Qué son las reservas internacionales de un país?',
    opciones: [
      'Los activos en moneda extranjera y oro que mantiene el banco central para responder a sus obligaciones externas',
      'El ahorro de los hogares en dólares',
      'La deuda que otros países tienen con él',
      'El valor de sus exportaciones anuales',
    ],
    correcta: 0,
    explicacion: 'Funcionan como un colchón ante choques externos: permiten pagar importaciones y atender la deuda cuando el acceso al financiamiento se cierra.',
  },
  {
    id: 'eco-083', tema: 'internacional', dificultad: 2,
    enunciado: '¿Qué significa que un país tenga una economía primario-exportadora?',
    opciones: [
      'Que sus ventas externas se concentran en materias primas con poco procesamiento',
      'Que exporta sobre todo tecnología',
      'Que no participa en el comercio internacional',
      'Que produce únicamente para el mercado interno',
    ],
    correcta: 0,
    explicacion: 'Petróleo, carbón, café y flores en el caso colombiano. Esa concentración expone los ingresos del país a los vaivenes de los precios internacionales.',
  },
  {
    id: 'eco-084', tema: 'internacional', dificultad: 3,
    enunciado: '¿Qué es la enfermedad holandesa?',
    opciones: [
      'El auge exportador de un recurso natural aprecia la moneda y resta competitividad a la industria y la agricultura',
      'Una crisis bancaria originada en los Países Bajos',
      'La caída del comercio por una epidemia',
      'El exceso de importaciones de alimentos',
    ],
    correcta: 0,
    explicacion: 'El nombre viene del gas holandés de los años sesenta. Un boom petrolero puede así debilitar al resto de los sectores transables justo cuando el país parece más próspero.',
  },
  {
    id: 'eco-085', tema: 'internacional', dificultad: 3,
    enunciado: '¿Por qué un déficit comercial no es necesariamente malo?',
    opciones: [
      'Puede reflejar una economía que importa bienes de capital para invertir y crecer, financiada con entrada de capitales',
      'Porque siempre indica que el país es más rico',
      'Porque las importaciones no se pagan',
      'Porque el déficit se corrige solo',
    ],
    correcta: 0,
    explicacion: 'Lo que importa es en qué se gasta y cómo se financia. Un déficit por maquinaria financiado con inversión de largo plazo no es lo mismo que uno por consumo financiado con deuda de corto plazo.',
  },
  {
    id: 'eco-086', tema: 'internacional', dificultad: 3,
    enunciado: '¿Qué efecto tiene una devaluación sobre una empresa endeudada en dólares que vende en el mercado interno?',
    opciones: [
      'La perjudica: sus ingresos siguen en pesos pero su deuda, medida en pesos, aumenta',
      'La beneficia, porque exporta más',
      'No la afecta en absoluto',
      'Reduce automáticamente su deuda',
    ],
    correcta: 0,
    explicacion: 'Es el descalce de monedas. Por eso las crisis cambiarias golpean sobre todo a quienes se endeudaron en una moneda distinta a la de sus ingresos.',
    pista: 'Compara en qué moneda entra el dinero y en cuál hay que pagarlo.',
  },
  {
    id: 'eco-087', tema: 'internacional', dificultad: 3,
    enunciado: '¿Qué argumento se usa para proteger temporalmente a una industria naciente?',
    opciones: [
      'Que necesita tiempo para alcanzar escala y productividad antes de competir con productores extranjeros consolidados',
      'Que el libre comercio es siempre perjudicial',
      'Que los consumidores prefieren productos nacionales',
      'Que las importaciones deben prohibirse de forma permanente',
    ],
    correcta: 0,
    explicacion: 'El riesgo conocido es que la protección se vuelva permanente y la industria nunca madure. Los casos exitosos combinaron protección con exigencias crecientes de exportación.',
  },
  {
    id: 'eco-088', tema: 'internacional', dificultad: 4,
    enunciado: '¿Por qué el comercio internacional puede aumentar el bienestar agregado y a la vez perjudicar a grupos concretos?',
    opciones: [
      'Porque las ganancias se reparten entre muchos consumidores mientras las pérdidas se concentran en sectores y regiones específicas',
      'Porque el comercio no genera ganancias reales',
      'Porque siempre perjudica al país más pobre',
      'Porque los consumidores no se benefician nunca',
    ],
    correcta: 0,
    explicacion: 'Esa asimetría explica la política del proteccionismo: quien pierde su empleo lo nota y se organiza; quien ahorra unos pesos en cada compra, no. Compensar a los perdedores es lo que casi nunca se hace.',
  },
  {
    id: 'eco-089', tema: 'internacional', dificultad: 4,
    enunciado: '¿Qué implica para un país exportador de materias primas la volatilidad de los precios internacionales?',
    opciones: [
      'Sus ingresos fiscales y su tasa de cambio dependen de factores externos que no controla, lo que dificulta planear a largo plazo',
      'Que sus precios internos son estables',
      'Que su crecimiento está garantizado',
      'Que no necesita ahorrar en épocas de auge',
    ],
    correcta: 0,
    explicacion: 'Por eso existen los fondos de estabilización: ahorrar durante el auge para sostener el gasto en la caída. La tentación política es gastar el auge como si fuera permanente.',
  },
  {
    id: 'eco-090', tema: 'internacional', dificultad: 4,
    enunciado: '¿Por qué las cadenas globales de valor cambiaron la forma de entender el comercio?',
    opciones: [
      'Porque los países ya no intercambian productos terminados sino tareas: un mismo bien cruza varias fronteras antes de venderse',
      'Porque desapareció el comercio de materias primas',
      'Porque los aranceles dejaron de existir',
      'Porque todos los países producen lo mismo',
    ],
    correcta: 0,
    explicacion: 'Un teléfono se diseña en un país, sus componentes se hacen en varios y se ensambla en otro. Las estadísticas tradicionales, que asignan todo el valor al último exportador, distorsionan el panorama.',
  },
  // ----- Desigualdad, pobreza y desarrollo -----
  {
    id: 'eco-091', tema: 'desigualdad', dificultad: 1,
    enunciado: '¿Qué mide el coeficiente de Gini?',
    opciones: [
      'La desigualdad en la distribución del ingreso, entre 0 (igualdad total) y 1 (concentración máxima)',
      'El nivel de pobreza de un país',
      'La tasa de crecimiento económico',
      'El grado de informalidad laboral',
    ],
    correcta: 0,
    explicacion: 'Colombia está entre los países más desiguales de América Latina, con un Gini históricamente por encima de 0,50.',
  },
  {
    id: 'eco-092', tema: 'desigualdad', dificultad: 1,
    enunciado: '¿Qué es la pobreza monetaria?',
    opciones: [
      'La situación de quien vive con un ingreso inferior al necesario para cubrir una canasta básica',
      'La ausencia total de dinero en efectivo',
      'La falta de acceso a servicios públicos',
      'El desempleo prolongado',
    ],
    correcta: 0,
    explicacion: 'La pobreza multidimensional, en cambio, mide privaciones en educación, salud, vivienda y trabajo, sin depender solo del ingreso.',
  },
  {
    id: 'eco-093', tema: 'desigualdad', dificultad: 1,
    enunciado: '¿Qué es un impuesto progresivo?',
    opciones: [
      'Aquel cuya tarifa aumenta a medida que crece el ingreso o el patrimonio gravado',
      'Aquel que se cobra en varias cuotas',
      'Aquel que grava a todos con la misma tarifa',
      'Aquel que se aplica solo a las empresas',
    ],
    correcta: 0,
    explicacion: 'El impuesto de renta suele serlo. El IVA es regresivo: al cobrar la misma tarifa a todos, pesa proporcionalmente más en los ingresos bajos.',
  },
  {
    id: 'eco-094', tema: 'desigualdad', dificultad: 2,
    enunciado: '¿Qué diferencia hay entre desigualdad y pobreza?',
    opciones: [
      'La pobreza mide si se alcanza un umbral mínimo; la desigualdad, cómo se reparte el total entre la población',
      'Son dos nombres para el mismo fenómeno',
      'La desigualdad solo existe en países pobres',
      'La pobreza se mide en porcentaje y la desigualdad en pesos',
    ],
    correcta: 0,
    explicacion: 'Un país puede reducir la pobreza y seguir siendo muy desigual si el crecimiento se concentra arriba. Son dos preguntas distintas sobre la misma economía.',
  },
  {
    id: 'eco-095', tema: 'desigualdad', dificultad: 2,
    enunciado: '¿Qué es la movilidad social?',
    opciones: [
      'La posibilidad de que una persona cambie de posición socioeconómica respecto a la de sus padres',
      'La migración de personas entre regiones',
      'El cambio de empleo dentro de una empresa',
      'El traslado de fábricas a otros países',
    ],
    correcta: 0,
    explicacion: 'Donde es baja, el origen familiar predice el destino. América Latina tiene de las tasas más bajas del mundo, y Colombia está entre los peores casos medidos.',
  },
  {
    id: 'eco-096', tema: 'desigualdad', dificultad: 2,
    enunciado: '¿Qué son las transferencias monetarias condicionadas?',
    opciones: [
      'Pagos a hogares pobres sujetos a requisitos como la asistencia escolar o los controles de salud',
      'Préstamos otorgados por la banca pública',
      'Subsidios a las empresas exportadoras',
      'Pensiones para adultos mayores sin requisitos',
    ],
    correcta: 0,
    explicacion: 'Familias en Acción en Colombia o Bolsa Família en Brasil siguen ese modelo. Buscan aliviar la pobreza presente y a la vez romper su transmisión entre generaciones.',
  },
  {
    id: 'eco-097', tema: 'desigualdad', dificultad: 2,
    enunciado: '¿Qué es el desarrollo económico, a diferencia del crecimiento?',
    opciones: [
      'Un proceso que incluye mejoras en bienestar, equidad y capacidades, no solo aumento de la producción',
      'El aumento del PIB durante varios años seguidos',
      'La industrialización de un país',
      'El incremento de las exportaciones',
    ],
    correcta: 0,
    explicacion: 'Un país puede crecer con la renta concentrada en pocas manos. El desarrollo pregunta además quién se beneficia y cómo cambia la vida de la gente.',
  },
  {
    id: 'eco-098', tema: 'desigualdad', dificultad: 2,
    enunciado: '¿Qué es la línea de pobreza extrema?',
    opciones: [
      'El ingreso mínimo necesario para cubrir únicamente los requerimientos alimentarios básicos',
      'El salario mínimo legal',
      'El ingreso promedio del decil más bajo',
      'El umbral de la clase media',
    ],
    correcta: 0,
    explicacion: 'También se le llama línea de indigencia. La línea de pobreza general incluye además vivienda, transporte, vestido y otros gastos no alimentarios.',
  },
  {
    id: 'eco-099', tema: 'desigualdad', dificultad: 3,
    enunciado: '¿Por qué dos países con el mismo PIB per cápita pueden tener realidades sociales muy distintas?',
    opciones: [
      'Porque el promedio no dice nada sobre la distribución ni sobre el acceso a servicios',
      'Porque el PIB se calcula de forma distinta en cada país',
      'Porque uno tiene más población',
      'Porque el tipo de cambio distorsiona la comparación',
    ],
    correcta: 0,
    explicacion: 'Un promedio alto puede convivir con una mayoría en condiciones precarias. Por eso se complementa con Gini, pobreza multidimensional e IDH.',
  },
  {
    id: 'eco-100', tema: 'desigualdad', dificultad: 3,
    enunciado: '¿Por qué la educación se considera clave para la movilidad social, y qué la limita?',
    opciones: [
      'Aumenta la productividad y los ingresos, pero si su calidad depende del origen social, reproduce la desigualdad en vez de corregirla',
      'Porque garantiza empleo formal a todos los graduados',
      'Porque elimina por completo la pobreza',
      'Porque no tiene relación con los ingresos futuros',
    ],
    correcta: 0,
    explicacion: 'Cuando el colegio al que se accede depende del barrio y del ingreso familiar, el sistema educativo deja de ser un igualador y pasa a ser un transmisor de la desigualdad.',
  },
  {
    id: 'eco-101', tema: 'desigualdad', dificultad: 3,
    enunciado: '¿Qué mide el índice de pobreza multidimensional?',
    opciones: [
      'Privaciones simultáneas en educación, salud, trabajo, vivienda y servicios, más allá del ingreso',
      'Solo el ingreso de los hogares',
      'La distribución de la riqueza',
      'El acceso al crédito bancario',
    ],
    correcta: 0,
    explicacion: 'Un hogar puede superar la línea de ingreso y seguir sin agua potable ni afiliación a salud. Colombia lo calcula junto con la pobreza monetaria.',
  },
  {
    id: 'eco-102', tema: 'desigualdad', dificultad: 3,
    enunciado: '¿Qué es la economía informal y qué implica para la protección social?',
    opciones: [
      'El conjunto de actividades fuera del marco legal y tributario, cuyos trabajadores quedan sin pensión, cesantías ni estabilidad',
      'El comercio ilegal de bienes prohibidos',
      'El trabajo doméstico no remunerado',
      'El empleo público sin concurso',
    ],
    correcta: 0,
    explicacion: 'En Colombia supera la mitad de los ocupados. Eso limita la recaudación y deja fuera del sistema pensional a una parte enorme de la fuerza laboral.',
  },
  {
    id: 'eco-103', tema: 'desigualdad', dificultad: 4,
    enunciado: '¿Por qué un impuesto plano al consumo es regresivo aunque su tarifa sea igual para todos?',
    opciones: [
      'Porque los hogares de menores ingresos destinan una proporción mayor de lo que ganan al consumo, y ahorran poco o nada',
      'Porque los ricos consumen menos en términos absolutos',
      'Porque los pobres pagan una tarifa más alta',
      'Porque el impuesto se cobra solo a los pobres',
    ],
    correcta: 0,
    explicacion: 'Quien gasta todo su ingreso paga IVA sobre el 100 % de lo que gana; quien ahorra la mitad, sobre la mitad. La tarifa es igual y el esfuerzo relativo no lo es.',
  },
  {
    id: 'eco-104', tema: 'desigualdad', dificultad: 4,
    enunciado: '¿Qué discute Piketty al sostener que el rendimiento del capital tiende a superar el crecimiento de la economía?',
    opciones: [
      'Que si eso se sostiene, la riqueza heredada crece más rápido que los ingresos del trabajo y la desigualdad aumenta estructuralmente',
      'Que el capital dejará de existir',
      'Que el crecimiento económico es siempre nulo',
      'Que los salarios crecen más rápido que las rentas',
    ],
    correcta: 0,
    explicacion: 'Su fórmula "r > g" es discutida en sus detalles, pero puso en el centro del debate el papel de la herencia y la concentración patrimonial, no solo la de ingresos.',
  },
  {
    id: 'eco-105', tema: 'desigualdad', dificultad: 4,
    enunciado: '¿Por qué reducir la desigualdad puede tener efectos económicos y no solo sociales?',
    opciones: [
      'Porque una desigualdad alta limita la demanda interna, desaprovecha talento y erosiona la confianza en las instituciones',
      'Porque garantiza automáticamente el crecimiento',
      'Porque elimina la necesidad de impuestos',
      'Porque no tiene ningún efecto económico',
    ],
    correcta: 0,
    explicacion: 'Un niño talentoso que no accede a educación es una pérdida de productividad para todo el país. Organismos que antes veían la desigualdad como precio del crecimiento hoy la analizan como obstáculo.',
  },

  // ----- Economía colombiana -----
  {
    id: 'eco-106', tema: 'colombiana', dificultad: 1,
    enunciado: '¿Cuál ha sido el principal producto de exportación de Colombia en las últimas décadas?',
    opciones: ['El petróleo', 'El café', 'Las flores', 'El banano'],
    correcta: 0,
    explicacion: 'El café dominó hasta los años ochenta; desde los noventa el grueso de las exportaciones es minero-energético, con el carbón en segundo lugar.',
  },
  {
    id: 'eco-107', tema: 'colombiana', dificultad: 1,
    enunciado: '¿Qué entidad calcula en Colombia la inflación y las cifras de empleo?',
    opciones: ['El DANE', 'El Banco de la República', 'El Ministerio de Hacienda', 'La DIAN'],
    correcta: 0,
    explicacion: 'El DANE produce las estadísticas oficiales; el Banco de la República fija la política monetaria y la DIAN administra los impuestos.',
  },
  {
    id: 'eco-108', tema: 'colombiana', dificultad: 1,
    enunciado: '¿Cómo se determina cada año el salario mínimo en Colombia?',
    opciones: [
      'Por concertación entre gobierno, empresarios y sindicatos, y si no hay acuerdo lo fija el Gobierno por decreto',
      'Lo fija libremente cada empresa',
      'Lo establece el Banco de la República',
      'Se ajusta automáticamente con el IPC sin discusión',
    ],
    correcta: 0,
    explicacion: 'La mesa de concertación laboral discute con base en inflación y productividad. En la práctica, la mayoría de los años termina definiéndose por decreto.',
  },
  {
    id: 'eco-109', tema: 'colombiana', dificultad: 2,
    enunciado: '¿Qué fue la apertura económica de comienzos de los años noventa?',
    opciones: [
      'La reducción de aranceles y la liberalización del comercio y la inversión extranjera',
      'La nacionalización de la banca',
      'El cierre de las importaciones',
      'La creación del Banco de la República',
    ],
    correcta: 0,
    explicacion: 'Rompió con el modelo de sustitución de importaciones vigente desde mediados del siglo XX. Su balance sigue discutiéndose, sobre todo por su efecto en la industria y el agro.',
  },
  {
    id: 'eco-110', tema: 'colombiana', dificultad: 2,
    enunciado: '¿Qué caracteriza al sistema pensional colombiano?',
    opciones: [
      'Coexisten un régimen público de prima media y uno privado de ahorro individual, con baja cobertura por la informalidad',
      'Es exclusivamente público y cubre a toda la población',
      'Es exclusivamente privado',
      'No exige semanas mínimas de cotización',
    ],
    correcta: 0,
    explicacion: 'La competencia entre los dos regímenes y la alta informalidad hacen que solo una minoría de los adultos mayores alcance pensión, lo que explica las sucesivas propuestas de reforma.',
  },
  {
    id: 'eco-111', tema: 'colombiana', dificultad: 2,
    enunciado: '¿Qué es la regla fiscal en Colombia?',
    opciones: [
      'Un límite legal al déficit del Gobierno para asegurar la sostenibilidad de la deuda',
      'La obligación de equilibrar el presupuesto cada mes',
      'Una norma que prohíbe crear impuestos',
      'El techo de gasto de las empresas públicas',
    ],
    correcta: 0,
    explicacion: 'Busca evitar que el gasto crezca sin control en épocas de auge. Contempla cláusulas de escape para emergencias, como se activó durante la pandemia.',
  },
  {
    id: 'eco-112', tema: 'colombiana', dificultad: 2,
    enunciado: '¿Qué peso tiene el sector agropecuario en la economía colombiana?',
    opciones: [
      'Aporta una fracción moderada del PIB pero concentra una parte importante del empleo rural y de la pobreza',
      'Es el sector que más aporta al PIB',
      'Prácticamente ha desaparecido',
      'Genera la mayoría de las exportaciones',
    ],
    correcta: 0,
    explicacion: 'Esa asimetría entre aporte al producto y peso en el empleo señala baja productividad. Es uno de los núcleos del problema del desarrollo rural en el país.',
  },
  {
    id: 'eco-113', tema: 'colombiana', dificultad: 3,
    enunciado: '¿Por qué la dependencia del petróleo hace vulnerable a la economía colombiana?',
    opciones: [
      'Porque una caída del precio internacional golpea a la vez exportaciones, ingresos fiscales y tasa de cambio',
      'Porque el petróleo se agota cada año',
      'Porque no genera empleo directo',
      'Porque no puede exportarse fácilmente',
    ],
    correcta: 0,
    explicacion: 'Lo ocurrido a partir de 2014 lo ilustró: el desplome del crudo obligó a una reforma tributaria, devaluó el peso y recortó la inversión pública, todo al mismo tiempo.',
  },
  {
    id: 'eco-114', tema: 'colombiana', dificultad: 3,
    enunciado: '¿Qué relación tiene la informalidad con el sistema tributario colombiano?',
    opciones: [
      'Reduce la base de contribuyentes, lo que concentra la carga en pocos y presiona hacia impuestos indirectos como el IVA',
      'Aumenta la recaudación del impuesto de renta',
      'No tiene relación con los impuestos',
      'Elimina la necesidad de reformas tributarias',
    ],
    correcta: 0,
    explicacion: 'Es un círculo difícil: como pocos tributan, las tarifas sobre los formales deben ser altas, y eso desincentiva formalizarse. Salir de ahí exige actuar sobre los dos lados a la vez.',
  },
  {
    id: 'eco-115', tema: 'colombiana', dificultad: 3,
    enunciado: '¿Qué efecto tiene la concentración de la propiedad rural en Colombia?',
    opciones: [
      'Limita la productividad agrícola, alimenta el conflicto por la tierra y restringe el acceso de pequeños productores al crédito',
      'Aumenta la eficiencia del campo',
      'No tiene relación con el conflicto armado',
      'Favorece la formalización laboral rural',
    ],
    correcta: 0,
    explicacion: 'Colombia tiene uno de los Gini de tierras más altos del mundo. El punto uno del acuerdo de paz de 2016 aborda precisamente la reforma rural integral.',
  },
  {
    id: 'eco-116', tema: 'colombiana', dificultad: 3,
    enunciado: '¿Qué implicó para Colombia la llegada masiva de migrantes venezolanos en términos económicos?',
    opciones: [
      'Presión de corto plazo sobre servicios y empleo informal, y potencial aporte productivo si se logra la regularización',
      'Un efecto exclusivamente negativo y permanente',
      'Ningún efecto sobre el mercado laboral',
      'Una caída inmediata del PIB',
    ],
    correcta: 0,
    explicacion: 'La evidencia apunta a un impacto agregado moderado y concentrado en el empleo informal. El Estatuto Temporal de Protección busca convertir esa población en fuerza laboral formal y contribuyente.',
  },
  {
    id: 'eco-117', tema: 'colombiana', dificultad: 4,
    enunciado: '¿Por qué se dice que Colombia tuvo estabilidad macroeconómica sin lograr reducir la desigualdad?',
    opciones: [
      'Mantuvo inflación controlada y crecimiento sin grandes crisis, pero el sistema tributario y el gasto social redistribuyen poco',
      'Porque nunca tuvo crecimiento económico',
      'Porque la inflación fue siempre muy alta',
      'Porque no existen datos de desigualdad',
    ],
    correcta: 0,
    explicacion: 'A diferencia de varios vecinos, evitó hiperinflaciones y cesaciones de pagos. Pero su Gini antes y después de impuestos y transferencias cambia mucho menos que en otros países.',
  },
  {
    id: 'eco-118', tema: 'colombiana', dificultad: 4,
    enunciado: '¿Qué tensión plantea la dependencia fiscal de las regalías mineras y petroleras?',
    opciones: [
      'Financian inversión regional hoy, pero atan el presupuesto a un recurso finito y volátil, y a una actividad con costos ambientales',
      'No generan ningún ingreso al Estado',
      'Se distribuyen únicamente en Bogotá',
      'Eliminan la necesidad de impuestos',
    ],
    correcta: 0,
    explicacion: 'El Sistema General de Regalías reparte esos recursos entre los territorios. La discusión de fondo es cómo transformar una renta agotable en capacidad productiva duradera.',
  },
  {
    id: 'eco-119', tema: 'colombiana', dificultad: 4,
    enunciado: '¿Por qué subir el salario mínimo tiene efectos discutidos en un país con alta informalidad?',
    opciones: [
      'Mejora el ingreso de los formales, pero puede encarecer la formalización y no llega a quienes trabajan por fuera del sistema',
      'No tiene ningún efecto sobre el empleo',
      'Beneficia por igual a todos los trabajadores',
      'Reduce automáticamente la informalidad',
    ],
    correcta: 0,
    explicacion: 'Más de la mitad de los ocupados no recibe ese salario ni sus prestaciones. El debate empírico sigue abierto, y la respuesta depende del tamaño del ajuste y del contexto.',
  },
  {
    id: 'eco-120', tema: 'colombiana', dificultad: 4,
    enunciado: '¿Qué significa diversificar la economía colombiana y por qué es difícil?',
    opciones: [
      'Desarrollar sectores con mayor valor agregado, lo que exige infraestructura, capital humano y tiempo, mientras la renta minera resulta más rentable a corto plazo',
      'Exportar más petróleo a nuevos países',
      'Reducir el comercio internacional',
      'Concentrar la producción en un solo sector',
    ],
    correcta: 0,
    explicacion: 'Mientras el crudo sea rentable, los recursos y el tipo de cambio empujan en su dirección: es la enfermedad holandesa operando. Diversificar exige decisiones deliberadas y sostenidas en el tiempo.',
  },
];
