/**
 * filosofia.js — Banco de ética y filosofía.
 *
 * El banco ya tenía ética pública dentro de ciudadanía, pero solo en su versión
 * anticorrupción. Aquí está lo demás: cómo se justifica una decisión moral, qué
 * han respondido las grandes corrientes y cómo se evalúa un argumento.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const FILOSOFIA = [
  // ----- Ética, moral y valores -----
  {
    id: 'fil-001', tema: 'que-es-etica', dificultad: 1,
    enunciado: '¿De qué se ocupa la ética?',
    opciones: [
      'De reflexionar sobre qué hace que una acción sea correcta o incorrecta',
      'De describir las costumbres de cada pueblo sin juzgarlas',
      'De aplicar las leyes vigentes',
      'De estudiar el origen del universo',
    ],
    correcta: 0,
    explicacion: 'La ética justifica; la antropología describe y el derecho aplica normas vigentes. Las tres miran la conducta, pero con preguntas distintas.',
  },
  {
    id: 'fil-002', tema: 'que-es-etica', dificultad: 1,
    enunciado: '¿Qué es un valor?',
    opciones: [
      'Una cualidad que se considera deseable y que orienta las decisiones',
      'Una norma escrita en un código legal',
      'Un hábito adquirido por repetición',
      'Una emoción pasajera',
    ],
    correcta: 0,
    explicacion: 'La honestidad, la justicia o la solidaridad no obligan como una ley, pero funcionan como criterio para decidir y para evaluar lo que hacemos.',
  },
  {
    id: 'fil-003', tema: 'que-es-etica', dificultad: 1,
    enunciado: 'Una acción puede ser legal y a la vez cuestionable éticamente. Eso ocurre porque:',
    opciones: [
      'La ley y la ética no coinciden siempre: la ley fija un mínimo exigible',
      'Las leyes nunca tienen contenido moral',
      'La ética solo se aplica a la vida privada',
      'Toda conducta legal es automáticamente correcta',
    ],
    correcta: 0,
    explicacion: 'Despedir a alguien cumpliendo todos los requisitos legales puede ser injusto; y hubo leyes, como las de segregación racial, claramente inmorales.',
  },
  {
    id: 'fil-004', tema: 'que-es-etica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia más aceptada entre ética y moral?',
    opciones: [
      'La moral es el conjunto de normas vividas por un grupo; la ética es la reflexión filosófica sobre ellas',
      'La ética es religiosa y la moral, civil',
      'La moral se aplica al trabajo y la ética a la familia',
      'Son términos sin ninguna diferencia',
    ],
    correcta: 0,
    explicacion: 'Con frecuencia se usan como sinónimos en el habla, pero la distinción es útil: una comunidad tiene una moral; sobre ella se puede hacer ética.',
  },
  {
    id: 'fil-005', tema: 'que-es-etica', dificultad: 2,
    enunciado: '¿Qué sostiene el relativismo moral?',
    opciones: [
      'Que lo correcto depende de la cultura o del individuo, sin criterios válidos para todos',
      'Que todas las culturas comparten los mismos valores',
      'Que la moral la determina la religión',
      'Que ninguna acción puede juzgarse jamás',
    ],
    correcta: 0,
    explicacion: 'Su fortaleza es el respeto por la diversidad; su problema es que dificulta condenar prácticas como la esclavitud si una cultura las aceptaba.',
  },
  {
    id: 'fil-006', tema: 'que-es-etica', dificultad: 2,
    enunciado: '¿Qué es una norma moral?',
    opciones: [
      'Una regla de conducta cuya fuerza proviene de la conciencia y la presión social, no de una sanción jurídica',
      'Una ley aprobada por el Congreso',
      'Una costumbre sin ningún contenido valorativo',
      'Una orden de una autoridad religiosa',
    ],
    correcta: 0,
    explicacion: 'Incumplir una norma moral no lleva a la cárcel, pero sí genera reproche y culpa. Muchas normas jurídicas nacieron como normas morales compartidas.',
  },
  {
    id: 'fil-007', tema: 'que-es-etica', dificultad: 2,
    enunciado: '¿Qué caracteriza a la dignidad humana en la tradición ética moderna?',
    opciones: [
      'Que toda persona tiene un valor que no depende de su utilidad y no admite precio',
      'Que se gana con el mérito personal',
      'Que la otorga el Estado mediante la ciudadanía',
      'Que solo la poseen quienes cumplen la ley',
    ],
    correcta: 0,
    explicacion: 'Kant lo formuló así: las cosas tienen precio, las personas tienen dignidad. Es el fundamento filosófico de la idea de derechos humanos.',
  },
  {
    id: 'fil-008', tema: 'que-es-etica', dificultad: 2,
    enunciado: '¿Qué distingue una acción moralmente valiosa de una simplemente conveniente?',
    opciones: [
      'La intención y la razón por la que se hace, no solo el resultado favorable',
      'Que sea difícil de realizar',
      'Que la vean otras personas',
      'Que esté recompensada económicamente',
    ],
    correcta: 0,
    explicacion: 'Devolver una billetera por miedo a las cámaras y devolverla por considerarlo debido producen el mismo efecto, pero no valen lo mismo moralmente en la mayoría de las teorías.',
  },
  {
    id: 'fil-009', tema: 'que-es-etica', dificultad: 3,
    enunciado: '¿Qué problema plantea derivar lo que "debe ser" de lo que "es"?',
    opciones: [
      'Es la falacia naturalista: de una descripción de hechos no se sigue por sí sola una conclusión normativa',
      'Que los hechos son siempre discutibles',
      'Que las normas no pueden estudiarse científicamente',
      'Que la naturaleza carece de orden',
    ],
    correcta: 0,
    explicacion: 'Hume lo señaló primero. Que algo ocurra con frecuencia, o sea "natural", no demuestra que deba ocurrir: hace falta una premisa valorativa adicional.',
    pista: 'Pregúntate si el argumento pasa de una descripción a una obligación sin añadir nada.',
  },
  {
    id: 'fil-010', tema: 'que-es-etica', dificultad: 3,
    enunciado: 'Alguien afirma: "esto siempre se ha hecho así, luego es correcto". ¿Qué falla en ese razonamiento?',
    opciones: [
      'Apela a la tradición, que dice cómo han sido las cosas pero no las justifica',
      'Usa un dato falso',
      'Contradice la ley vigente',
      'No define el término "correcto"',
    ],
    correcta: 0,
    explicacion: 'La antigüedad de una práctica no es un argumento a su favor ni en su contra. La esclavitud fue milenaria y eso nunca la hizo defendible.',
  },
  {
    id: 'fil-011', tema: 'que-es-etica', dificultad: 3,
    enunciado: '¿Qué sostiene el universalismo moral frente al relativismo?',
    opciones: [
      'Que existen algunos principios válidos para toda persona, más allá de las diferencias culturales',
      'Que todas las culturas deben adoptar las mismas costumbres',
      'Que la moral la define la mayoría',
      'Que los valores no existen',
    ],
    correcta: 0,
    explicacion: 'No exige uniformidad cultural: sostiene que ciertas cosas, como la tortura de inocentes, no dejan de ser injustas porque una comunidad las acepte.',
  },
  {
    id: 'fil-012', tema: 'que-es-etica', dificultad: 3,
    enunciado: '¿Qué diferencia hay entre autonomía y heteronomía moral?',
    opciones: [
      'La autonomía es darse uno mismo la norma tras examinarla; la heteronomía es obedecer una regla externa sin más',
      'La autonomía significa actuar sin normas',
      'La heteronomía se aplica solo a los menores de edad',
      'Son dos nombres para la libertad',
    ],
    correcta: 0,
    explicacion: 'Autonomía no es hacer lo que se quiera: es actuar por razones que uno reconoce como válidas. Ese es el sentido del lema ilustrado "atrévete a pensar".',
  },
  {
    id: 'fil-013', tema: 'que-es-etica', dificultad: 4,
    enunciado: 'Un relativista afirma: "no existe ninguna verdad moral universal". ¿Qué objeción se le suele plantear?',
    opciones: [
      'Que esa misma afirmación se presenta como universalmente verdadera, y entonces se contradice',
      'Que ignora las leyes de su país',
      'Que no conoce otras culturas',
      'Que confunde la ética con la moral',
    ],
    correcta: 0,
    explicacion: 'Es el problema de autorrefutación. El relativista puede responder matizando su tesis, pero la objeción obliga a precisar de qué relativismo se habla.',
  },
  {
    id: 'fil-014', tema: 'que-es-etica', dificultad: 4,
    enunciado: '¿Por qué la tolerancia es difícil de fundamentar desde un relativismo estricto?',
    opciones: [
      'Porque si ningún valor es universal, la tolerancia tampoco lo sería y no podría exigirse a los intolerantes',
      'Porque la tolerancia es un valor jurídico y no moral',
      'Porque las culturas intolerantes son minoría',
      'Porque la tolerancia exige renunciar a toda opinión',
    ],
    correcta: 0,
    explicacion: 'El relativismo suele invocarse para defender la tolerancia, pero la deja sin fundamento: si todo depende de cada cultura, la intolerancia de otra sería igual de legítima.',
  },
  {
    id: 'fil-015', tema: 'que-es-etica', dificultad: 4,
    enunciado: 'Que distintas culturas tengan normas diferentes, ¿demuestra que no hay valores comunes?',
    opciones: [
      'No: las diferencias pueden estar en las creencias sobre los hechos y no en los valores últimos',
      'Sí, la diversidad prueba el relativismo',
      'No, porque en realidad las culturas son idénticas',
      'Sí, porque los valores son ilusiones',
    ],
    correcta: 0,
    explicacion: 'Dos sociedades pueden compartir el valor "honrar a los muertos" y discrepar en si eso exige enterrarlos o incinerarlos. La conducta difiere; el principio, no.',
  },

  // ----- Corrientes éticas -----
  {
    id: 'fil-016', tema: 'corrientes', dificultad: 1,
    enunciado: 'Según el utilitarismo, una acción es correcta cuando:',
    opciones: [
      'Produce la mayor cantidad de bienestar para el mayor número de personas',
      'Cumple con el deber, sin importar el resultado',
      'La realiza una persona virtuosa',
      'Está permitida por la ley',
    ],
    correcta: 0,
    explicacion: 'Es una ética consecuencialista: lo que decide es el balance de consecuencias. Bentham y Mill son sus formuladores clásicos.',
  },
  {
    id: 'fil-017', tema: 'corrientes', dificultad: 1,
    enunciado: 'La ética kantiana sostiene que el valor moral de una acción está en:',
    opciones: [
      'El deber y la intención con que se actúa',
      'Las consecuencias que produce',
      'La felicidad que genera',
      'La aprobación de la mayoría',
    ],
    correcta: 0,
    explicacion: 'Es una ética deontológica: hay acciones debidas o prohibidas en sí mismas, con independencia de lo que resulte de ellas.',
  },
  {
    id: 'fil-018', tema: 'corrientes', dificultad: 1,
    enunciado: 'La ética de la virtud, de raíz aristotélica, se pregunta ante todo:',
    opciones: [
      'Qué clase de persona debo ser',
      'Qué norma debo cumplir',
      'Qué consecuencia debo maximizar',
      'Qué contrato debo firmar',
    ],
    correcta: 0,
    explicacion: 'Desplaza el foco de la acción al carácter. Las virtudes se adquieren por hábito y apuntan a una vida lograda, no a resolver casos aislados.',
  },
  {
    id: 'fil-019', tema: 'corrientes', dificultad: 2,
    enunciado: '¿Qué dice la primera formulación del imperativo categórico de Kant?',
    opciones: [
      'Obra solo según una máxima que puedas querer que se convierta en ley universal',
      'Busca siempre la mayor felicidad posible',
      'Actúa como lo haría una persona virtuosa',
      'Obedece las leyes de tu país',
    ],
    correcta: 0,
    explicacion: 'Es una prueba de universalización: si la máxima de mentir cuando conviene se volviera ley general, la promesa perdería sentido y la máxima se destruiría a sí misma.',
  },
  {
    id: 'fil-020', tema: 'corrientes', dificultad: 2,
    enunciado: 'La segunda formulación del imperativo categórico pide tratar a la humanidad:',
    opciones: [
      'Siempre como fin y nunca solamente como medio',
      'Como un medio para alcanzar el bien común',
      'Según el mérito de cada persona',
      'Conforme a la utilidad social de cada individuo',
    ],
    correcta: 0,
    explicacion: 'El "solamente" importa: usar a alguien como medio es inevitable en la vida social, lo prohibido es reducirlo a eso e ignorar que tiene fines propios.',
  },
  {
    id: 'fil-021', tema: 'corrientes', dificultad: 2,
    enunciado: '¿Qué es el término medio aristotélico?',
    opciones: [
      'La virtud como punto intermedio entre un exceso y un defecto, relativo a cada persona y situación',
      'La obligación de no destacar en nada',
      'El promedio de opiniones de la comunidad',
      'Una regla matemática para decidir',
    ],
    correcta: 0,
    explicacion: 'El valor está entre la temeridad y la cobardía; la generosidad, entre el derroche y la avaricia. No es un punto fijo: depende de la persona y de la circunstancia.',
  },
  {
    id: 'fil-022', tema: 'corrientes', dificultad: 2,
    enunciado: '¿Qué propone la ética del cuidado?',
    opciones: [
      'Partir de las relaciones concretas y la responsabilidad hacia quien depende de nosotros, y no de principios abstractos',
      'Aplicar reglas universales sin excepción',
      'Maximizar el bienestar colectivo',
      'Priorizar siempre el interés propio',
    ],
    correcta: 0,
    explicacion: 'Carol Gilligan la formuló observando que los modelos dominantes describían mejor un razonamiento de reglas y derechos que otro basado en vínculos y necesidades.',
  },
  {
    id: 'fil-023', tema: 'corrientes', dificultad: 2,
    enunciado: '¿Qué sostiene el contractualismo en ética?',
    opciones: [
      'Que las normas justas son las que personas libres y racionales acordarían en condiciones equitativas',
      'Que solo obligan los contratos firmados ante notario',
      'Que la moral depende de la fuerza',
      'Que las normas las impone la tradición',
    ],
    correcta: 0,
    explicacion: 'Es la línea que va de Hobbes, Locke y Rousseau hasta Rawls y Scanlon. El acuerdo es hipotético: sirve como criterio, no como hecho histórico.',
  },
  {
    id: 'fil-024', tema: 'corrientes', dificultad: 3,
    enunciado: '¿Cuál es la principal objeción que se le hace al utilitarismo?',
    opciones: [
      'Que podría justificar sacrificar a una minoría si con ello aumenta el bienestar total',
      'Que nunca considera las consecuencias',
      'Que es imposible de aplicar en la práctica cotidiana',
      'Que no le interesa el sufrimiento',
    ],
    correcta: 0,
    explicacion: 'Si solo cuenta la suma, los derechos individuales quedan sin protección frente a un beneficio agregado mayor. El utilitarismo de reglas intenta responder a esa objeción.',
  },
  {
    id: 'fil-025', tema: 'corrientes', dificultad: 3,
    enunciado: '¿Cuál es la principal objeción que se le hace a la ética kantiana?',
    opciones: [
      'Su rigorismo: mantener una norma absoluta puede llevar a resultados terribles en casos extremos',
      'Que ignora por completo la razón',
      'Que depende de las emociones del agente',
      'Que no formula ningún principio general',
    ],
    correcta: 0,
    explicacion: 'El caso clásico es el del asesino que pregunta dónde se esconde la víctima. Kant sostuvo que no cabe mentir; muchos kantianos posteriores han buscado matizar esa conclusión.',
  },
  {
    id: 'fil-026', tema: 'corrientes', dificultad: 3,
    enunciado: '¿Qué diferencia al utilitarismo de actos del utilitarismo de reglas?',
    opciones: [
      'El primero evalúa cada acción concreta; el segundo, la regla general que más bienestar produciría si todos la siguieran',
      'El primero considera solo el placer y el segundo solo el dolor',
      'El segundo rechaza las consecuencias',
      'No existe tal distinción',
    ],
    correcta: 0,
    explicacion: 'El utilitarismo de reglas se acerca a la deontología: aunque mentir beneficie en un caso puntual, la regla "no mentir" produce mejores resultados aplicada en general.',
  },
  {
    id: 'fil-027', tema: 'corrientes', dificultad: 3,
    enunciado: 'Un médico reparte un recurso escaso según quién llegó primero, no según quién se beneficia más. ¿Qué enfoque ético refleja?',
    opciones: [
      'Uno deontológico o de equidad procedimental, no consecuencialista',
      'Uno estrictamente utilitarista',
      'La ética de la virtud',
      'El relativismo cultural',
    ],
    correcta: 0,
    explicacion: 'Un utilitarista preguntaría dónde rinde más el recurso. Elegir un procedimiento imparcial, aunque el resultado agregado sea menor, es una decisión de otro tipo.',
  },
  {
    id: 'fil-028', tema: 'corrientes', dificultad: 4,
    enunciado: '¿Por qué se dice que las tres grandes corrientes éticas responden a preguntas distintas y no solo dan respuestas distintas?',
    opciones: [
      'El consecuencialismo pregunta por el resultado, la deontología por el deber y la ética de la virtud por el carácter',
      'Porque cada una se aplica a un país diferente',
      'Porque solo una de ellas es filosófica',
      'Porque las tres coinciden siempre en la conclusión',
    ],
    correcta: 0,
    explicacion: 'Por eso pueden coincidir en el veredicto y diferir por completo en la justificación. Un buen análisis ético suele exigir mirar el caso desde las tres.',
  },
  {
    id: 'fil-029', tema: 'corrientes', dificultad: 4,
    enunciado: 'Alguien dona a una causa solo por la deducción de impuestos. ¿Cómo lo evaluarían un utilitarista y un kantiano?',
    opciones: [
      'El utilitarista la valoraría por sus efectos; el kantiano negaría que tenga valor moral, porque no se hizo por deber',
      'Los dos la condenarían por igual',
      'Los dos la elogiarían por igual',
      'Ninguno de los dos podría pronunciarse',
    ],
    correcta: 0,
    explicacion: 'Es el caso que mejor separa a las dos tradiciones: una mira hacia afuera, al bien producido; la otra, hacia adentro, al motivo de la voluntad.',
  },
  {
    id: 'fil-030', tema: 'corrientes', dificultad: 4,
    enunciado: '¿Qué problema plantea la ética de la virtud a la hora de decidir un caso concreto?',
    opciones: [
      'Ofrece poca orientación específica: decir "actúa con justicia" no resuelve qué hacer cuando dos virtudes chocan',
      'No admite que existan personas virtuosas',
      'Depende de calcular consecuencias imposibles de medir',
      'Exige reglas demasiado rígidas',
    ],
    correcta: 0,
    explicacion: 'Sus defensores responden que la phronesis, la prudencia práctica, es precisamente la capacidad de discernir en el caso particular, y que ninguna regla puede sustituirla.',
  },
  // ----- Dilemas morales -----
  {
    id: 'fil-031', tema: 'dilemas', dificultad: 1,
    enunciado: '¿Qué caracteriza a un dilema moral?',
    opciones: [
      'Que hay razones de peso a favor de dos opciones incompatibles, y elegir una implica sacrificar algo valioso',
      'Que la persona no sabe qué dice la ley',
      'Que una opción es claramente correcta y la otra no',
      'Que no hay información suficiente para decidir',
    ],
    correcta: 0,
    explicacion: 'Si una opción es evidentemente mejor, hay duda o falta de información, pero no dilema. El dilema duele precisamente porque toda salida cuesta.',
  },
  {
    id: 'fil-032', tema: 'dilemas', dificultad: 1,
    enunciado: 'En un conflicto entre dos deberes, lo primero que conviene hacer es:',
    opciones: [
      'Identificar con precisión cuáles son los deberes en juego y a quién obligan',
      'Elegir el que sea más cómodo',
      'Consultar qué haría la mayoría',
      'Aplazar la decisión indefinidamente',
    ],
    correcta: 0,
    explicacion: 'Muchos dilemas aparentes se disuelven al formularlos bien: se descubre que uno de los deberes no obligaba tanto como parecía o que hay una tercera opción.',
  },
  {
    id: 'fil-033', tema: 'dilemas', dificultad: 1,
    enunciado: 'Un profesional descubre que su empresa contamina un río en secreto. El conflicto ético está entre:',
    opciones: [
      'La lealtad a la organización y la responsabilidad hacia terceros afectados',
      'La ley y la costumbre',
      'Su salario y su tiempo libre',
      'La eficiencia y la rentabilidad',
    ],
    correcta: 0,
    explicacion: 'Es el caso típico del denunciante o whistleblower. La confidencialidad es un deber real, pero no cubre el encubrimiento de un daño a terceros.',
  },
  {
    id: 'fil-034', tema: 'dilemas', dificultad: 2,
    enunciado: 'En el clásico dilema del tranvía, desviar el vehículo para salvar a cinco personas sacrificando a una es aprobado por:',
    opciones: [
      'El razonamiento consecuencialista, que compara los resultados',
      'El razonamiento deontológico estricto',
      'La ética del cuidado',
      'El relativismo cultural',
    ],
    correcta: 0,
    explicacion: 'Cinco vidas pesan más que una si solo cuenta el balance. Un deontólogo estricto objetará que desviar el tranvía convierte a alguien en instrumento de la salvación de otros.',
  },
  {
    id: 'fil-035', tema: 'dilemas', dificultad: 2,
    enunciado: '¿Qué es el principio del doble efecto?',
    opciones: [
      'Permite una acción buena con un efecto negativo previsible, si ese daño no es el medio ni el fin buscado',
      'Obliga a duplicar los beneficios de cada acción',
      'Prohíbe toda acción que cause algún daño',
      'Exige consultar siempre a dos personas antes de decidir',
    ],
    correcta: 0,
    explicacion: 'Se usa en ética médica y militar: administrar un analgésico que alivia y acorta la vida es distinto de administrar una dosis para provocar la muerte, aunque el desenlace se parezca.',
  },
  {
    id: 'fil-036', tema: 'dilemas', dificultad: 2,
    enunciado: 'Ante un dilema, apelar a "lo que dice mi conciencia" es insuficiente porque:',
    opciones: [
      'La conciencia orienta pero puede estar mal informada o sesgada, y debe examinarse con razones',
      'La conciencia no existe',
      'Solo importa lo que diga la ley',
      'Las emociones no intervienen en la moral',
    ],
    correcta: 0,
    explicacion: 'La intuición moral es un punto de partida valioso, no un tribunal final. Se contrasta pidiendo razones y comprobando si se sostendrían aplicadas a otros casos.',
  },
  {
    id: 'fil-037', tema: 'dilemas', dificultad: 2,
    enunciado: 'Un periodista obtiene información verdadera de interés público violando la privacidad de una persona. El conflicto es entre:',
    opciones: [
      'El derecho a la información y el derecho a la intimidad',
      'La verdad y la mentira',
      'La libertad de expresión y la censura',
      'El interés comercial y el profesional',
    ],
    correcta: 0,
    explicacion: 'Los dos son derechos legítimos, y por eso hay dilema. El criterio habitual es la proporcionalidad: cuánto interés público real hay y si había otra vía para obtener el dato.',
  },
  {
    id: 'fil-038', tema: 'dilemas', dificultad: 2,
    enunciado: '¿Qué es la objeción de conciencia?',
    opciones: [
      'La negativa a cumplir un deber legal por razones morales profundas, asumiendo las consecuencias',
      'El derecho a incumplir cualquier ley con la que se discrepe',
      'Una forma de protesta colectiva',
      'La crítica pública a una norma',
    ],
    correcta: 0,
    explicacion: 'Se distingue de la desobediencia civil, que busca cambiar la norma y suele ser pública y colectiva. La objeción es individual y pide una excepción, no la derogación.',
  },
  {
    id: 'fil-039', tema: 'dilemas', dificultad: 3,
    enunciado: '¿Por qué la mayoría de las personas aprueban desviar el tranvía pero rechazan empujar a un hombre desde un puente para detenerlo, si el resultado numérico es el mismo?',
    opciones: [
      'Porque en el segundo caso el daño se usa deliberadamente como medio y hay contacto directo, lo que activa intuiciones distintas',
      'Porque en el segundo caso mueren más personas',
      'Porque el primer caso es legal y el segundo no',
      'Porque la gente calcula mal las probabilidades',
    ],
    correcta: 0,
    explicacion: 'El experimento muestra que nuestras intuiciones no son puramente consecuencialistas: distinguen entre causar un daño como efecto colateral y usarlo como instrumento.',
    pista: 'Compara qué papel juega la persona sacrificada en cada versión: ¿es un efecto lateral o la herramienta?',
  },
  {
    id: 'fil-040', tema: 'dilemas', dificultad: 3,
    enunciado: 'Una madre roba un medicamento que no puede pagar para salvar a su hijo. ¿Cómo analiza el caso una ética de principios?',
    opciones: [
      'Reconoce que el deber de salvar una vida puede prevalecer, sin negar que la propiedad es un valor real',
      'Concluye que robar nunca es discutible y cierra el caso',
      'Declara que no hay ningún valor en juego',
      'Sostiene que la ley es irrelevante',
    ],
    correcta: 0,
    explicacion: 'Es el dilema de Heinz, usado por Kohlberg para estudiar el desarrollo moral. Lo revelador no es la respuesta sino el tipo de razones que la persona ofrece.',
  },
  {
    id: 'fil-041', tema: 'dilemas', dificultad: 3,
    enunciado: '¿Qué distingue un dilema genuino de una tentación?',
    opciones: [
      'En el dilema chocan dos deberes; en la tentación, el deber choca con el interés propio',
      'El dilema es siempre más grave',
      'La tentación no tiene contenido moral',
      'Son lo mismo con nombres distintos',
    ],
    correcta: 0,
    explicacion: 'Presentar como dilema lo que es una tentación es una estrategia frecuente de autoengaño: dignifica la duda cuando en realidad ya se sabe qué es lo debido.',
  },
  {
    id: 'fil-042', tema: 'dilemas', dificultad: 3,
    enunciado: 'En un triaje médico con recursos insuficientes, ¿qué criterio se considera éticamente más defendible?',
    opciones: [
      'Un criterio clínico explícito y aplicado por igual, como el beneficio esperado del tratamiento',
      'La capacidad de pago del paciente',
      'La decisión discrecional de cada profesional, sin protocolo',
      'La importancia social del paciente',
    ],
    correcta: 0,
    explicacion: 'Lo que hace aceptable una decisión trágica es que el criterio sea público, pertinente y aplicado sin excepciones. La arbitrariedad es lo que vuelve injusta la escasez.',
  },
  {
    id: 'fil-043', tema: 'dilemas', dificultad: 4,
    enunciado: '¿Qué significa que en un dilema auténtico quede un "resto moral" aun habiendo decidido bien?',
    opciones: [
      'Que el valor sacrificado no desaparece: sigue exigiendo reconocimiento, reparación o al menos pesar',
      'Que la decisión fue necesariamente errónea',
      'Que no había realmente un dilema',
      'Que la culpa es siempre irracional',
    ],
    correcta: 0,
    explicacion: 'Bernard Williams insistió en esto: sentir el peso de lo que se dejó atrás no es un fallo de razonamiento, es la señal de que se percibió bien lo que estaba en juego.',
  },
  {
    id: 'fil-044', tema: 'dilemas', dificultad: 4,
    enunciado: '¿Por qué los dilemas artificiales como el del tranvía reciben críticas?',
    opciones: [
      'Porque aíslan la decisión de todo contexto y certeza real, y las situaciones verdaderas rara vez ofrecen dos opciones cerradas',
      'Porque son demasiado sencillos de resolver',
      'Porque nunca se usan en filosofía académica',
      'Porque no admiten respuestas consecuencialistas',
    ],
    correcta: 0,
    explicacion: 'Su valor es aislar una variable, como en un experimento. El riesgo es tomar el laboratorio por el mundo y olvidar que en la práctica casi siempre cabe buscar una tercera vía.',
  },
  {
    id: 'fil-045', tema: 'dilemas', dificultad: 4,
    enunciado: 'Un empleado descubre un fraude pero denunciarlo dejará sin trabajo a cien compañeros inocentes. ¿Qué exige un análisis ético serio?',
    opciones: [
      'Examinar la gravedad del fraude, las alternativas intermedias y la responsabilidad de quien lo cometió, en lugar de plantearlo como dos únicas salidas',
      'Callar siempre que haya terceros perjudicados',
      'Denunciar sin considerar ninguna consecuencia',
      'Delegar la decisión en la mayoría de los compañeros',
    ],
    correcta: 0,
    explicacion: 'El daño a los compañeros lo causa el fraude, no la denuncia; atribuirlo a quien denuncia es un desplazamiento de responsabilidad. Aun así, el modo y el momento de denunciar sí son decisiones éticas.',
  },

  // ----- Bioética -----
  {
    id: 'fil-046', tema: 'bioetica', dificultad: 1,
    enunciado: '¿Cuáles son los cuatro principios clásicos de la bioética?',
    opciones: [
      'Autonomía, beneficencia, no maleficencia y justicia',
      'Libertad, igualdad, fraternidad y solidaridad',
      'Verdad, prudencia, valor y templanza',
      'Eficacia, eficiencia, equidad y economía',
    ],
    correcta: 0,
    explicacion: 'Los formularon Beauchamp y Childress. No están jerarquizados: en cada caso hay que ponderar cuál pesa más.',
  },
  {
    id: 'fil-047', tema: 'bioetica', dificultad: 1,
    enunciado: '¿Qué es el consentimiento informado?',
    opciones: [
      'La aceptación voluntaria de un procedimiento tras recibir información comprensible sobre riesgos y alternativas',
      'La firma de cualquier documento antes de una cirugía',
      'La autorización de un familiar',
      'El permiso del comité de ética',
    ],
    correcta: 0,
    explicacion: 'Sin información comprensible no hay consentimiento, solo una firma. Es la expresión práctica del principio de autonomía.',
  },
  {
    id: 'fil-048', tema: 'bioetica', dificultad: 1,
    enunciado: 'El principio de no maleficencia se resume en:',
    opciones: [
      'Ante todo, no causar daño',
      'Hacer siempre el mayor bien posible',
      'Respetar la decisión del paciente',
      'Repartir los recursos equitativamente',
    ],
    correcta: 0,
    explicacion: 'Se distingue de la beneficencia, que obliga a procurar el bien. No dañar es una exigencia más básica y menos discutible que hacer el bien.',
  },
  {
    id: 'fil-049', tema: 'bioetica', dificultad: 2,
    enunciado: '¿Qué es el paternalismo médico?',
    opciones: [
      'Decidir por el paciente "por su bien", pasando por alto su voluntad',
      'Informar detalladamente al paciente',
      'Consultar a la familia antes de actuar',
      'Seguir un protocolo clínico',
    ],
    correcta: 0,
    explicacion: 'Fue el modelo dominante durante siglos. El giro hacia la autonomía del paciente es uno de los cambios más profundos de la ética médica contemporánea.',
  },
  {
    id: 'fil-050', tema: 'bioetica', dificultad: 2,
    enunciado: 'La confidencialidad médica puede romperse legítimamente cuando:',
    opciones: [
      'Existe un riesgo grave e inminente para terceros identificables',
      'Lo pide cualquier familiar del paciente',
      'El caso resulta interesante para la docencia',
      'El profesional considera que el paciente se equivoca',
    ],
    correcta: 0,
    explicacion: 'Es una excepción estrecha y justificada por el deber de proteger a otros. Fuera de esos supuestos, el secreto profesional se mantiene incluso después de la muerte del paciente.',
  },
  {
    id: 'fil-051', tema: 'bioetica', dificultad: 2,
    enunciado: '¿Qué establece el principio de justicia en bioética?',
    opciones: [
      'Que los recursos y las cargas sanitarias deben distribuirse de forma equitativa',
      'Que todos los pacientes deben recibir exactamente el mismo tratamiento',
      'Que las decisiones las toma un juez',
      'Que se atiende primero a quien más aporta',
    ],
    correcta: 0,
    explicacion: 'Equidad no es igualdad mecánica: implica atender necesidades distintas de forma distinta, sin que factores irrelevantes como el origen o la capacidad de pago decidan el acceso.',
  },
  {
    id: 'fil-052', tema: 'bioetica', dificultad: 2,
    enunciado: '¿Por qué los ensayos clínicos deben pasar por un comité de ética?',
    opciones: [
      'Para verificar que el riesgo para los participantes es proporcionado y que el consentimiento es genuino',
      'Para asegurar que los resultados sean positivos',
      'Para decidir qué revista publicará el estudio',
      'Para fijar el presupuesto de la investigación',
    ],
    correcta: 0,
    explicacion: 'Los comités nacieron tras abusos documentados, como el estudio de Tuskegee. Su función es proteger a los sujetos, no facilitar la investigación.',
  },
  {
    id: 'fil-053', tema: 'bioetica', dificultad: 2,
    enunciado: '¿Qué es el encarnizamiento u obstinación terapéutica?',
    opciones: [
      'Prolongar tratamientos que ya no ofrecen beneficio y solo alargan el sufrimiento',
      'Administrar analgésicos en fase terminal',
      'Retirar un tratamiento a petición del paciente',
      'Derivar al paciente a cuidados paliativos',
    ],
    correcta: 0,
    explicacion: 'Se considera una mala práctica: el deber de no dañar incluye no someter a alguien a intervenciones fútiles. Limitar el esfuerzo terapéutico no equivale a abandonar al paciente.',
  },
  {
    id: 'fil-054', tema: 'bioetica', dificultad: 3,
    enunciado: 'Un paciente adulto y competente rechaza un tratamiento que le salvaría la vida. ¿Qué principio prevalece según la bioética actual?',
    opciones: [
      'La autonomía: su decisión informada debe respetarse aunque el equipo médico discrepe',
      'La beneficencia: debe tratarse igualmente',
      'La justicia: decide el sistema de salud',
      'La opinión de la familia',
    ],
    correcta: 0,
    explicacion: 'La condición decisiva es la competencia para decidir. Evaluarla con rigor es obligatorio; una vez confirmada, la discrepancia del equipo no autoriza a imponer el tratamiento.',
  },
  {
    id: 'fil-055', tema: 'bioetica', dificultad: 3,
    enunciado: '¿Qué diferencia hay entre eutanasia y suicidio médicamente asistido?',
    opciones: [
      'En la eutanasia es el profesional quien administra la sustancia; en el suicidio asistido, el propio paciente',
      'La eutanasia es siempre involuntaria',
      'El suicidio asistido no requiere consentimiento',
      'No existe ninguna diferencia',
    ],
    correcta: 0,
    explicacion: 'Colombia despenalizó la eutanasia por vía jurisprudencial desde 1997, con requisitos y protocolos. La distinción importa en la regulación y en el debate sobre la responsabilidad del profesional.',
  },
  {
    id: 'fil-056', tema: 'bioetica', dificultad: 3,
    enunciado: '¿Qué preocupación ética central plantea la edición genética en embriones humanos?',
    opciones: [
      'Que los cambios se heredan y afectan a personas que nunca pudieron consentir',
      'Que la técnica es demasiado costosa',
      'Que no existen comités que la regulen',
      'Que retrasa otras investigaciones',
    ],
    correcta: 0,
    explicacion: 'La modificación de la línea germinal desborda al individuo tratado. A eso se suma el riesgo de deslizarse de la terapia hacia la mejora y de ampliar desigualdades.',
  },
  {
    id: 'fil-057', tema: 'bioetica', dificultad: 3,
    enunciado: '¿Por qué es problemático reclutar participantes muy pobres para un ensayo clínico pagando una suma alta?',
    opciones: [
      'Porque el incentivo puede anular la voluntariedad real del consentimiento',
      'Porque los datos serían menos precisos',
      'Porque encarece el estudio',
      'Porque la ley prohíbe pagar a los participantes',
    ],
    correcta: 0,
    explicacion: 'Se llama influencia indebida: cuando la necesidad hace que el riesgo deje de pesar en la decisión, el consentimiento se vuelve formal. Por eso las compensaciones deben cubrir molestias, no funcionar como oferta irresistible.',
  },
  {
    id: 'fil-058', tema: 'bioetica', dificultad: 4,
    enunciado: 'Durante una pandemia, ¿qué justifica éticamente restringir libertades individuales?',
    opciones: [
      'El daño a terceros, siempre que la medida sea necesaria, proporcionada, temporal y revisable',
      'La conveniencia administrativa',
      'La opinión mayoritaria de la población',
      'Cualquier riesgo sanitario, sin más condiciones',
    ],
    correcta: 0,
    explicacion: 'El principio de daño de Mill fundamenta la restricción, pero no la deja abierta: cada condición —necesidad, proporcionalidad, temporalidad— es un límite exigible y verificable.',
  },
  {
    id: 'fil-059', tema: 'bioetica', dificultad: 4,
    enunciado: '¿Qué tensión plantea la medicina predictiva basada en pruebas genéticas?',
    opciones: [
      'El derecho a saber choca con el derecho a no saber, y el dato afecta también a familiares que no lo pidieron',
      'Las pruebas son siempre inexactas',
      'Los pacientes no comprenden los resultados',
      'No existe regulación sobre el tema',
    ],
    correcta: 0,
    explicacion: 'Conocer una predisposición hereditaria informa sobre parientes que quizá prefieren ignorarla, y abre riesgos de discriminación laboral o en seguros. El dato genético nunca es del todo individual.',
  },
  {
    id: 'fil-060', tema: 'bioetica', dificultad: 4,
    enunciado: 'Un sistema de salud decide no financiar un medicamento muy costoso de beneficio pequeño. ¿Cómo se evalúa éticamente?',
    opciones: [
      'Como una decisión de justicia distributiva, defendible si el criterio es público, consistente y revisable',
      'Como una violación automática del derecho a la salud',
      'Como una decisión puramente técnica sin contenido ético',
      'Como un caso de no maleficencia',
    ],
    correcta: 0,
    explicacion: 'Todo recurso destinado a un tratamiento deja de estar disponible para otro: el costo de oportunidad es real. Lo que hace legítima la decisión es la transparencia del criterio y la posibilidad de apelarlo.',
  },

  // ----- Ética ambiental y animal -----
  {
    id: 'fil-061', tema: 'etica-ambiental', dificultad: 1,
    enunciado: '¿Qué sostiene el antropocentrismo en ética ambiental?',
    opciones: [
      'Que la naturaleza tiene valor sobre todo en función de los intereses humanos',
      'Que todos los seres vivos tienen el mismo valor',
      'Que los ecosistemas tienen derechos propios',
      'Que los seres humanos deben desaparecer',
    ],
    correcta: 0,
    explicacion: 'Un antropocentrismo ilustrado puede exigir mucha protección ambiental, porque el bienestar humano depende de ecosistemas sanos y de lo que quede para las generaciones futuras.',
  },
  {
    id: 'fil-062', tema: 'etica-ambiental', dificultad: 1,
    enunciado: '¿Qué defiende el biocentrismo?',
    opciones: [
      'Que los seres vivos tienen valor en sí mismos, no solo por su utilidad para los humanos',
      'Que solo los animales grandes merecen protección',
      'Que la naturaleza no puede ser objeto de la ética',
      'Que la biología determina la moral',
    ],
    correcta: 0,
    explicacion: 'El ecocentrismo va más lejos y atribuye valor a ecosistemas y especies enteras, no solo a los organismos individuales.',
  },
  {
    id: 'fil-063', tema: 'etica-ambiental', dificultad: 1,
    enunciado: '¿Qué significa el desarrollo sostenible?',
    opciones: [
      'Satisfacer las necesidades del presente sin comprometer la capacidad de las generaciones futuras de satisfacer las suyas',
      'Detener todo crecimiento económico',
      'Explotar los recursos hasta agotarlos de forma ordenada',
      'Proteger la naturaleza prohibiendo la presencia humana',
    ],
    correcta: 0,
    explicacion: 'La definición es del informe Brundtland de 1987. Su fuerza ética está en incluir a quienes aún no existen entre los afectados por nuestras decisiones.',
  },
  {
    id: 'fil-064', tema: 'etica-ambiental', dificultad: 2,
    enunciado: '¿En qué se basa el argumento de Peter Singer sobre los animales?',
    opciones: [
      'En la capacidad de sufrir: si un ser puede sufrir, sus intereses deben tenerse en cuenta',
      'En que los animales son racionales',
      'En que los animales tienen lenguaje',
      'En que los animales son útiles para el ser humano',
    ],
    correcta: 0,
    explicacion: 'Retoma la pregunta de Bentham: no es si pueden razonar o hablar, sino si pueden sufrir. Llama "especismo" a excluir intereses por la sola pertenencia a otra especie.',
  },
  {
    id: 'fil-065', tema: 'etica-ambiental', dificultad: 2,
    enunciado: '¿Qué plantea el problema de las generaciones futuras?',
    opciones: [
      'Que nuestras decisiones afectan a personas que no pueden participar ni reclamar hoy',
      'Que el futuro es imposible de prever',
      'Que las generaciones futuras no tendrán derechos',
      'Que la población dejará de crecer',
    ],
    correcta: 0,
    explicacion: 'Es una asimetría radical de poder: quienes sufrirán las consecuencias del cambio climático o de los residuos nucleares no votan hoy ni pueden negociar con nosotros.',
  },
  {
    id: 'fil-066', tema: 'etica-ambiental', dificultad: 2,
    enunciado: '¿Qué es la justicia ambiental?',
    opciones: [
      'El reparto equitativo de las cargas y los beneficios ambientales entre grupos sociales y territorios',
      'La creación de tribunales para juzgar delitos ecológicos',
      'La protección legal de las especies en peligro',
      'El pago de multas por contaminar',
    ],
    correcta: 0,
    explicacion: 'Los vertederos, las refinerías y la minería suelen ubicarse cerca de poblaciones pobres o racializadas, que reciben los daños sin recibir los beneficios.',
  },
  {
    id: 'fil-067', tema: 'etica-ambiental', dificultad: 2,
    enunciado: '¿Qué es el principio de precaución?',
    opciones: [
      'Ante un riesgo grave e irreversible, la falta de certeza científica plena no justifica postergar medidas de protección',
      'Prohibir toda tecnología nueva',
      'Actuar solo cuando el daño esté plenamente demostrado',
      'Dejar la decisión en manos de los expertos',
    ],
    correcta: 0,
    explicacion: 'Invierte la carga de la prueba en casos de riesgo severo. Su aplicación es discutida: llevado al extremo paralizaría cualquier innovación.',
  },
  {
    id: 'fil-068', tema: 'etica-ambiental', dificultad: 2,
    enunciado: '¿Qué significa que un país reconozca derechos a la naturaleza, como hizo Ecuador en 2008?',
    opciones: [
      'Que los ecosistemas pasan a ser sujetos protegibles en sí mismos y no solo propiedad de alguien',
      'Que se prohíbe toda actividad económica en zonas naturales',
      'Que los animales pueden demandar directamente',
      'Que la naturaleza vota en las elecciones',
    ],
    correcta: 0,
    explicacion: 'En Colombia, la Corte Constitucional reconoció al río Atrato como sujeto de derechos en 2016. El cambio es de estatus jurídico: alguien puede actuar en su nombre.',
  },
  {
    id: 'fil-069', tema: 'etica-ambiental', dificultad: 3,
    enunciado: '¿Por qué el cambio climático se considera un problema ético y no solo técnico?',
    opciones: [
      'Porque quienes menos contribuyeron a causarlo suelen ser los más afectados y con menos capacidad de adaptarse',
      'Porque no existe evidencia científica suficiente',
      'Porque solo afecta a los países ricos',
      'Porque sus efectos son inmediatos y visibles',
    ],
    correcta: 0,
    explicacion: 'Hay una doble asimetría: entre países y entre generaciones. La responsabilidad histórica de las emisiones y la vulnerabilidad actual están repartidas casi al revés.',
  },
  {
    id: 'fil-070', tema: 'etica-ambiental', dificultad: 3,
    enunciado: '¿Qué crítica se le hace a la compensación de emisiones mediante bonos de carbono?',
    opciones: [
      'Que puede funcionar como permiso para seguir contaminando sin reducir realmente las emisiones',
      'Que es técnicamente imposible calcular emisiones',
      'Que está prohibida internacionalmente',
      'Que no genera ningún ingreso',
    ],
    correcta: 0,
    explicacion: 'La objeción no es que compensar sea malo, sino que sustituya a la reducción. A eso se suman dudas sobre la adicionalidad y la permanencia real de muchos proyectos.',
  },
  {
    id: 'fil-071', tema: 'etica-ambiental', dificultad: 3,
    enunciado: '¿Qué distingue el bienestar animal del enfoque de derechos animales?',
    opciones: [
      'El bienestarismo busca reducir el sufrimiento dentro del uso de animales; el abolicionismo rechaza ese uso como tal',
      'El bienestarismo es más radical',
      'Los derechos animales solo se refieren a mascotas',
      'No hay diferencia entre los dos enfoques',
    ],
    correcta: 0,
    explicacion: 'Mejorar las condiciones de una granja y sostener que no debería existir son posiciones distintas, y a veces en tensión: los abolicionistas temen que la reforma legitime la práctica.',
  },
  {
    id: 'fil-072', tema: 'etica-ambiental', dificultad: 3,
    enunciado: 'Una comunidad se opone a un proyecto minero que traería empleo pero afecta su fuente de agua. ¿Qué exige un análisis ético?',
    opciones: [
      'Considerar quién asume los riesgos y quién recibe los beneficios, y si la comunidad participó de forma libre e informada',
      'Priorizar siempre el empleo por su impacto inmediato',
      'Priorizar siempre la conservación sin discusión',
      'Dejar la decisión exclusivamente en manos técnicas',
    ],
    correcta: 0,
    explicacion: 'La consulta previa a comunidades étnicas responde justamente a este problema. Lo éticamente decisivo no es solo el balance agregado, sino la distribución y el procedimiento.',
  },
  {
    id: 'fil-073', tema: 'etica-ambiental', dificultad: 4,
    enunciado: '¿Por qué la responsabilidad individual no basta para resolver la crisis ambiental?',
    opciones: [
      'Porque la escala del problema requiere decisiones colectivas e institucionales, y centrarse en el consumidor desplaza la responsabilidad de los mayores emisores',
      'Porque las acciones individuales no tienen ningún efecto',
      'Porque la ética no se aplica a los individuos',
      'Porque los gobiernos ya resolvieron el problema',
    ],
    correcta: 0,
    explicacion: 'Las acciones individuales importan como señal y como coherencia, pero la huella de carbono como concepto de uso masivo fue promovida por la propia industria petrolera. Reconocerlo no exime a nadie; sitúa la responsabilidad donde está la capacidad de decidir.',
  },
  {
    id: 'fil-074', tema: 'etica-ambiental', dificultad: 4,
    enunciado: '¿Qué es la paradoja de la no identidad aplicada a las generaciones futuras?',
    opciones: [
      'Que nuestras decisiones determinan quiénes nacerán, así que es difícil decir que perjudicamos a personas concretas',
      'Que las generaciones futuras no existirán',
      'Que no podemos prever el futuro',
      'Que los daños ambientales son reversibles',
    ],
    correcta: 0,
    explicacion: 'La formuló Derek Parfit: una política distinta habría dado lugar a otras personas, que no pueden quejarse de existir. La salida habitual es evaluar estados de cosas y no solo daños a individuos identificables.',
  },
  {
    id: 'fil-075', tema: 'etica-ambiental', dificultad: 4,
    enunciado: '¿Qué problema ético plantea el argumento "mi país emite poco, así que reducir aquí no sirve"?',
    opciones: [
      'Es un caso de acción colectiva: si todos razonan así, nadie actúa, aunque la suma sí sea decisiva',
      'Es falso que existan países con pocas emisiones',
      'Solo se aplica a países ricos',
      'Confunde emisiones con contaminación local',
    ],
    correcta: 0,
    explicacion: 'Se parece a la tragedia de los comunes: cada actor tiene incentivos para no contribuir aunque el resultado conjunto sea desastroso. Por eso los acuerdos vinculantes importan más que la buena voluntad.',
  },
  // ----- Ética digital y tecnológica -----
  {
    id: 'fil-076', tema: 'etica-digital', dificultad: 1,
    enunciado: '¿Por qué la privacidad se considera un valor y no un simple capricho?',
    opciones: [
      'Porque permite formar opiniones, disentir y equivocarse sin ser vigilado ni castigado por ello',
      'Porque solo interesa a quien tiene algo que ocultar',
      'Porque lo exige la ley en algunos países',
      'Porque impide el desarrollo de la tecnología',
    ],
    correcta: 0,
    explicacion: 'El argumento del "no tengo nada que ocultar" confunde privacidad con secreto: se trata de control sobre la propia información, no de esconder delitos.',
  },
  {
    id: 'fil-077', tema: 'etica-digital', dificultad: 1,
    enunciado: 'Copiar un texto de internet y presentarlo como propio en un trabajo es:',
    opciones: [
      'Plagio, aunque el texto fuera de acceso libre',
      'Legítimo, porque estaba disponible gratis',
      'Aceptable si se cambian algunas palabras',
      'Un problema solo si el autor reclama',
    ],
    correcta: 0,
    explicacion: 'La gratuidad del acceso no tiene relación con la atribución. Lo que define el plagio es presentar como propio lo que es de otro.',
  },
  {
    id: 'fil-078', tema: 'etica-digital', dificultad: 1,
    enunciado: 'Compartir sin permiso una foto íntima de otra persona es:',
    opciones: [
      'Una violación grave de su privacidad y su dignidad, además de un delito en muchos países',
      'Aceptable si la foto fue enviada voluntariamente en su momento',
      'Un asunto privado sin relevancia ética',
      'Un problema solo si la persona es reconocible',
    ],
    correcta: 0,
    explicacion: 'Consentir compartir algo con una persona no es consentir su difusión. En Colombia y en buena parte del mundo hay tipos penales específicos para esa conducta.',
  },
  {
    id: 'fil-079', tema: 'etica-digital', dificultad: 2,
    enunciado: '¿Qué problema ético plantea que un algoritmo decida quién recibe un crédito?',
    opciones: [
      'Puede reproducir y amplificar sesgos presentes en los datos históricos, con apariencia de objetividad',
      'Que las máquinas no pueden hacer cálculos financieros',
      'Que siempre es más lento que un humano',
      'Que la decisión carece de consecuencias',
    ],
    correcta: 0,
    explicacion: 'Si históricamente se negó crédito a ciertos barrios, el modelo aprende ese patrón. El problema se agrava porque la decisión automatizada parece neutral y es difícil de impugnar.',
  },
  {
    id: 'fil-080', tema: 'etica-digital', dificultad: 2,
    enunciado: '¿Qué es el problema de la caja negra en inteligencia artificial?',
    opciones: [
      'Que un sistema puede dar resultados sin que sea posible explicar en qué se basó para decidir',
      'Que los datos se almacenan cifrados',
      'Que el código fuente es privado',
      'Que los sistemas fallan con frecuencia',
    ],
    correcta: 0,
    explicacion: 'Sin explicación no hay forma de detectar un error o un sesgo, ni de que el afectado apele. Por eso varias regulaciones exigen explicabilidad en decisiones de alto impacto.',
  },
  {
    id: 'fil-081', tema: 'etica-digital', dificultad: 2,
    enunciado: 'Cuando un servicio digital es gratuito, ¿qué suele ocurrir desde el punto de vista ético?',
    opciones: [
      'El usuario paga con sus datos y su atención, muchas veces sin comprender el alcance del intercambio',
      'La empresa opera sin ingresos',
      'No hay ningún intercambio de valor',
      'El servicio es necesariamente de peor calidad',
    ],
    correcta: 0,
    explicacion: 'El problema no es que exista el intercambio, sino su opacidad y su asimetría: las condiciones las fija una parte y la otra apenas puede negociarlas.',
  },
  {
    id: 'fil-082', tema: 'etica-digital', dificultad: 2,
    enunciado: '¿Qué responsabilidad ética tiene quien difunde una noticia falsa sin saber que lo era?',
    opciones: [
      'Una responsabilidad por negligencia: existía el deber de verificar antes de amplificar',
      'Ninguna, porque no sabía que era falsa',
      'La misma que quien la fabricó',
      'Solo responde si se demuestra intención de dañar',
    ],
    correcta: 0,
    explicacion: 'La ignorancia atenúa pero no exime cuando verificar estaba al alcance. Es el mismo criterio que aplicamos fuera de internet a quien repite un rumor dañino.',
  },
  {
    id: 'fil-083', tema: 'etica-digital', dificultad: 2,
    enunciado: 'Usar una herramienta de inteligencia artificial para redactar un trabajo académico es problemático cuando:',
    opciones: [
      'Se presenta el resultado como producción propia sin declararlo y sin verificar lo que afirma',
      'Se utiliza para corregir la ortografía',
      'Se emplea para buscar bibliografía',
      'Se usa fuera del horario de clase',
    ],
    correcta: 0,
    explicacion: 'Las dos exigencias habituales son transparencia sobre el uso y responsabilidad del autor humano por el contenido. Una herramienta no responde por lo que afirma: quien firma, sí.',
  },
  {
    id: 'fil-084', tema: 'etica-digital', dificultad: 3,
    enunciado: '¿Qué es el "nudge" o empujón en el diseño de plataformas, y cuándo se vuelve éticamente dudoso?',
    opciones: [
      'Es orientar la conducta modificando cómo se presentan las opciones; es dudoso cuando explota sesgos contra el interés del usuario',
      'Es cualquier notificación enviada al usuario',
      'Es siempre manipulación inaceptable',
      'Es un tipo de publicidad prohibida',
    ],
    correcta: 0,
    explicacion: 'Poner la opción saludable a la vista es un empujón benévolo. Esconder el botón de cancelar suscripción es un patrón oscuro: usa el mismo mecanismo contra quien decide.',
  },
  {
    id: 'fil-085', tema: 'etica-digital', dificultad: 3,
    enunciado: 'Ante un accidente inevitable, ¿por qué el problema del vehículo autónomo no es solo técnico?',
    opciones: [
      'Porque alguien debe decidir de antemano y por escrito qué criterio seguirá la máquina, y esa decisión es moral',
      'Porque los sensores no son suficientemente precisos',
      'Porque los coches autónomos son ilegales',
      'Porque no hay accidentes posibles',
    ],
    correcta: 0,
    explicacion: 'Un conductor humano reacciona por instinto y luego se le juzga; un algoritmo aplica una regla escrita meses antes por alguien identificable. La decisión se traslada del momento al diseño.',
  },
  {
    id: 'fil-086', tema: 'etica-digital', dificultad: 3,
    enunciado: '¿Qué es el derecho al olvido?',
    opciones: [
      'La posibilidad de pedir que se elimine o desindexe información personal que ya no es pertinente',
      'El derecho a borrar cualquier crítica recibida',
      'La obligación de las plataformas de eliminar todo contenido antiguo',
      'El derecho a no ser mencionado en la prensa',
    ],
    correcta: 0,
    explicacion: 'Nace de reconocer que internet no olvida y que un error del pasado puede perseguir a alguien indefinidamente. Choca con la libertad de información, y por eso se resuelve caso a caso.',
  },
  {
    id: 'fil-087', tema: 'etica-digital', dificultad: 3,
    enunciado: '¿Por qué la vigilancia masiva se considera distinta de la vigilancia dirigida?',
    opciones: [
      'Porque invierte la presunción de inocencia al tratar a toda la población como sospechosa sin causa previa',
      'Porque es tecnológicamente más sencilla',
      'Porque solo la usan gobiernos autoritarios',
      'Porque produce menos datos',
    ],
    correcta: 0,
    explicacion: 'La vigilancia dirigida requiere indicios y control judicial sobre una persona concreta. La masiva prescinde de ese filtro, y su efecto documentado es el desaliento de la disidencia y la autocensura.',
  },
  {
    id: 'fil-088', tema: 'etica-digital', dificultad: 4,
    enunciado: 'Si un sistema automatizado causa un daño, ¿dónde se sitúa la responsabilidad?',
    opciones: [
      'Se distribuye entre quienes lo diseñaron, lo entrenaron, lo desplegaron y lo supervisaron: no desaparece por estar automatizada',
      'En el sistema mismo, que es el agente',
      'En nadie, porque fue un fallo técnico',
      'Únicamente en el usuario final',
    ],
    correcta: 0,
    explicacion: 'El riesgo es lo que se llama brecha de responsabilidad: cada actor señala al siguiente y nadie responde. Por eso las regulaciones asignan deberes explícitos en cada eslabón.',
  },
  {
    id: 'fil-089', tema: 'etica-digital', dificultad: 4,
    enunciado: '¿Qué implica que un algoritmo de recomendación optimice el tiempo de permanencia?',
    opciones: [
      'Que su objetivo no coincide con el interés del usuario, y puede favorecer contenidos que retienen aunque no informen',
      'Que el sistema es neutral respecto al contenido',
      'Que el usuario elige libremente sin influencia alguna',
      'Que se maximiza la calidad de la información',
    ],
    correcta: 0,
    explicacion: 'La métrica elegida es una decisión moral disfrazada de decisión técnica: define qué cuenta como éxito. Optimizar permanencia y optimizar comprensión dan sistemas muy distintos.',
  },
  {
    id: 'fil-090', tema: 'etica-digital', dificultad: 4,
    enunciado: '¿Por qué "aceptar los términos y condiciones" difícilmente constituye consentimiento informado?',
    opciones: [
      'Porque el texto es inabarcable, las condiciones no se negocian y la alternativa real suele ser quedarse sin el servicio',
      'Porque los contratos digitales no son válidos',
      'Porque los usuarios no saben leer',
      'Porque las empresas no informan de nada',
    ],
    correcta: 0,
    explicacion: 'Faltan las dos condiciones del consentimiento: información comprensible y libertad real de elegir. Por eso las regulaciones más eficaces prohíben ciertas cláusulas en lugar de confiar en la lectura.',
  },

  // ----- Filosofía antigua -----
  {
    id: 'fil-091', tema: 'antigua', dificultad: 1,
    enunciado: '¿Qué significa el paso "del mito al logos" en los presocráticos?',
    opciones: [
      'Buscar explicaciones racionales sobre la naturaleza en lugar de recurrir a relatos sobre los dioses',
      'Abandonar el estudio de la naturaleza',
      'Sustituir la razón por la fe',
      'Dejar de escribir en griego',
    ],
    correcta: 0,
    explicacion: 'Tales, Anaximandro o Heráclito preguntan de qué está hecho todo y por qué cambia, y responden sin invocar voluntades divinas. Ahí empieza la filosofía occidental.',
  },
  {
    id: 'fil-092', tema: 'antigua', dificultad: 1,
    enunciado: '¿Qué frase se asocia a Sócrates?',
    opciones: ['"Solo sé que nada sé"', '"Pienso, luego existo"', '"El hombre es la medida de todas las cosas"', '"Dios ha muerto"'],
    correcta: 0,
    explicacion: 'Las otras son de Descartes, Protágoras y Nietzsche. El reconocimiento de la propia ignorancia es el punto de partida del método socrático.',
  },
  {
    id: 'fil-093', tema: 'antigua', dificultad: 1,
    enunciado: 'En la filosofía de Platón, las Ideas o Formas son:',
    opciones: [
      'Realidades perfectas e inmutables de las que las cosas sensibles son copias imperfectas',
      'Los pensamientos que cada persona tiene',
      'Las opiniones de la mayoría',
      'Las imágenes que producen los sentidos',
    ],
    correcta: 0,
    explicacion: 'Hay muchos círculos imperfectos, pero un solo Círculo. Esa duplicación del mundo es lo que Aristóteles le criticó a su maestro.',
  },
  {
    id: 'fil-094', tema: 'antigua', dificultad: 2,
    enunciado: '¿Qué ilustra el mito de la caverna de Platón?',
    opciones: [
      'El paso de la ignorancia al conocimiento y la dificultad de volver a explicarlo a quienes siguen encadenados',
      'La imposibilidad de conocer la verdad',
      'La superioridad de los sentidos sobre la razón',
      'El origen de las ciudades griegas',
    ],
    correcta: 0,
    explicacion: 'El prisionero liberado que regresa no es creído, sino ridiculizado. Platón escribe esa parte pensando en la condena de Sócrates.',
  },
  {
    id: 'fil-095', tema: 'antigua', dificultad: 2,
    enunciado: '¿En qué consiste el método socrático o mayéutica?',
    opciones: [
      'Preguntar sucesivamente para que el interlocutor descubra las contradicciones de sus propias creencias',
      'Exponer una doctrina cerrada a los discípulos',
      'Demostrar teoremas a partir de axiomas',
      'Observar la naturaleza y registrar datos',
    ],
    correcta: 0,
    explicacion: 'Sócrates se comparaba con una partera: no aporta el conocimiento, ayuda a darlo a luz. La primera fase, la ironía, consiste en desmontar la falsa certeza.',
  },
  {
    id: 'fil-096', tema: 'antigua', dificultad: 2,
    enunciado: 'Para Aristóteles, la felicidad o eudaimonía consiste en:',
    opciones: [
      'El desarrollo pleno de las capacidades propias del ser humano, especialmente la razón, a lo largo de una vida',
      'La acumulación de placeres',
      'La ausencia total de deseos',
      'La obediencia a las leyes de la ciudad',
    ],
    correcta: 0,
    explicacion: 'No es un estado de ánimo sino una actividad sostenida: por eso decía que una golondrina no hace verano, ni un solo día feliz una vida lograda.',
  },
  {
    id: 'fil-097', tema: 'antigua', dificultad: 2,
    enunciado: '¿Qué proponía el estoicismo?',
    opciones: [
      'Distinguir lo que depende de nosotros de lo que no, y buscar la serenidad aceptando lo segundo',
      'Maximizar el placer en cada momento',
      'Negar la existencia del mundo exterior',
      'Rechazar toda forma de vida en sociedad',
    ],
    correcta: 0,
    explicacion: 'Epicteto, Séneca y Marco Aurelio insisten en la misma idea: no nos perturban las cosas, sino nuestros juicios sobre ellas. De ahí su influencia en la psicología contemporánea.',
  },
  {
    id: 'fil-098', tema: 'antigua', dificultad: 2,
    enunciado: '¿Qué defendía realmente el epicureísmo?',
    opciones: [
      'Una vida de placeres moderados, amistad y ausencia de dolor, no el exceso',
      'La búsqueda de todos los placeres sin límite',
      'La renuncia total a cualquier placer',
      'La obediencia a los dioses',
    ],
    correcta: 0,
    explicacion: 'Epicuro comía pan y queso y valoraba sobre todo la amistad. La imagen del epicúreo glotón es una caricatura posterior, en buena parte de origen polémico.',
  },
  {
    id: 'fil-099', tema: 'antigua', dificultad: 3,
    enunciado: '¿En qué se diferencian Platón y Aristóteles respecto al conocimiento?',
    opciones: [
      'Platón lo sitúa en un mundo de Ideas separado; Aristóteles parte de la experiencia sensible para abstraer las formas',
      'Aristóteles niega que exista el conocimiento',
      'Platón se basa exclusivamente en la observación',
      'Los dos rechazan el uso de la razón',
    ],
    correcta: 0,
    explicacion: 'Rafael lo pintó en "La escuela de Atenas": Platón señala arriba y Aristóteles extiende la mano hacia el mundo. Es la bifurcación más duradera de la filosofía occidental.',
  },
  {
    id: 'fil-100', tema: 'antigua', dificultad: 3,
    enunciado: '¿Por qué la condena de Sócrates es un episodio filosóficamente relevante?',
    opciones: [
      'Plantea el conflicto entre la conciencia individual que cuestiona y la ciudad que se siente amenazada',
      'Demuestra que la democracia no existía en Atenas',
      'Prueba que Sócrates había cometido los delitos',
      'Marca el final de la filosofía griega',
    ],
    correcta: 0,
    explicacion: 'Se le acusó de corromper a la juventud y no reconocer a los dioses de la ciudad. Pudo huir y no lo hizo: obedecer las leyes que lo condenaban fue su último argumento.',
  },
  {
    id: 'fil-101', tema: 'antigua', dificultad: 3,
    enunciado: '¿Qué sostenían los sofistas y por qué chocaron con Sócrates?',
    opciones: [
      'Enseñaban a persuadir y defendían cierto relativismo; Sócrates les reprochaba buscar el triunfo en el debate y no la verdad',
      'Negaban la existencia del lenguaje',
      'Eran los primeros científicos naturales',
      'Rechazaban cobrar por enseñar',
    ],
    correcta: 0,
    explicacion: 'Protágoras afirmó que el hombre es la medida de todas las cosas. El desacuerdo de fondo era si existe una verdad más allá del acuerdo o de la eficacia retórica.',
  },
  {
    id: 'fil-102', tema: 'antigua', dificultad: 3,
    enunciado: 'Para Aristóteles, ¿cómo se adquiere la virtud?',
    opciones: [
      'Por hábito: practicando acciones virtuosas hasta que se vuelven disposición',
      'Por nacimiento',
      'Por conocimiento teórico únicamente',
      'Por revelación divina',
    ],
    correcta: 0,
    explicacion: 'Nos volvemos justos haciendo actos justos, como nos volvemos constructores construyendo. Es su discrepancia con Sócrates, que identificaba virtud con saber.',
  },
  {
    id: 'fil-103', tema: 'antigua', dificultad: 4,
    enunciado: '¿Qué problema plantea el intelectualismo moral socrático ("nadie obra mal a sabiendas")?',
    opciones: [
      'No explica la debilidad de la voluntad: saber qué es correcto y aun así no hacerlo',
      'Supone que el conocimiento es imposible',
      'Niega que existan acciones incorrectas',
      'Depende de creencias religiosas',
    ],
    correcta: 0,
    explicacion: 'Los griegos la llamaron akrasía. Aristóteles dedicó páginas a ella precisamente porque la tesis de su predecesor no daba cuenta de una experiencia cotidiana.',
  },
  {
    id: 'fil-104', tema: 'antigua', dificultad: 4,
    enunciado: '¿Por qué la filosofía helenística (estoicos, epicúreos, escépticos) cambia de foco respecto a Platón y Aristóteles?',
    opciones: [
      'Se concentra en cómo vivir bien y alcanzar la serenidad en un mundo donde la polis perdió autonomía política',
      'Abandona por completo el interés por la ética',
      'Rechaza el uso de la razón',
      'Se limita a comentar a los autores anteriores',
    ],
    correcta: 0,
    explicacion: 'Tras Alejandro, el ciudadano ya no decide sobre su ciudad. La filosofía se vuelve entonces hacia lo que sí queda bajo control: la propia vida interior.',
  },
  {
    id: 'fil-105', tema: 'antigua', dificultad: 4,
    enunciado: 'El estoicismo sostiene que hay que aceptar lo que no depende de nosotros. ¿Qué objeción ética recibe?',
    opciones: [
      'Que puede derivar en resignación ante injusticias que sí serían modificables con acción colectiva',
      'Que niega la existencia del dolor',
      'Que exige renunciar a la razón',
      'Que carece de cualquier aplicación práctica',
    ],
    correcta: 0,
    explicacion: 'Los estoicos respondían que la acción justa sí depende de nosotros, y que lo que no depende es el resultado. La frontera entre aceptar y resignarse es precisamente el punto difícil.',
  },
  // ----- Filosofía moderna -----
  {
    id: 'fil-106', tema: 'moderna', dificultad: 1,
    enunciado: '¿A qué filósofo pertenece la frase "Pienso, luego existo"?',
    opciones: ['René Descartes', 'John Locke', 'David Hume', 'Immanuel Kant'],
    correcta: 0,
    explicacion: 'Es el punto que Descartes encuentra indudable tras dudar de todo lo demás: incluso si me engaño, hay alguien que se engaña.',
  },
  {
    id: 'fil-107', tema: 'moderna', dificultad: 1,
    enunciado: '¿Qué sostiene el empirismo?',
    opciones: [
      'Que todo conocimiento procede de la experiencia sensible',
      'Que el conocimiento es innato',
      'Que la razón basta para conocer el mundo',
      'Que no existe el conocimiento',
    ],
    correcta: 0,
    explicacion: 'Locke describe la mente como una tabla rasa al nacer. El racionalismo de Descartes y Leibniz defiende lo contrario: hay ideas que no vienen de los sentidos.',
  },
  {
    id: 'fil-108', tema: 'moderna', dificultad: 1,
    enunciado: 'La teoría del contrato social explica el origen del Estado como:',
    opciones: [
      'Un acuerdo entre individuos que renuncian a parte de su libertad a cambio de seguridad y orden',
      'Una institución de origen divino',
      'El resultado de la conquista militar',
      'Una evolución biológica de la especie',
    ],
    correcta: 0,
    explicacion: 'Hobbes, Locke y Rousseau la desarrollan de formas muy distintas, pero comparten la idea: la autoridad política se legitima por el consentimiento y no por la tradición o la fuerza.',
  },
  {
    id: 'fil-109', tema: 'moderna', dificultad: 2,
    enunciado: '¿En qué se diferencian el estado de naturaleza de Hobbes y el de Locke?',
    opciones: [
      'Para Hobbes es una guerra de todos contra todos; para Locke ya hay derechos naturales que el Estado debe proteger',
      'Para Hobbes es pacífico y para Locke, violento',
      'Ninguno de los dos habla del estado de naturaleza',
      'Los dos lo describen exactamente igual',
    ],
    correcta: 0,
    explicacion: 'De ahí salen conclusiones políticas opuestas: Hobbes justifica un poder absoluto, Locke un gobierno limitado y con derecho de resistencia si incumple su función.',
  },
  {
    id: 'fil-110', tema: 'moderna', dificultad: 2,
    enunciado: '¿Qué es la duda metódica de Descartes?',
    opciones: [
      'Poner en duda provisionalmente todo lo dudable para encontrar algo absolutamente cierto',
      'Dudar de todo de forma permanente y definitiva',
      'Aceptar solo lo que dicen las autoridades',
      'Rechazar el uso de la razón',
    ],
    correcta: 0,
    explicacion: 'Es un instrumento, no una postura: la duda escéptica se instala, la duda metódica busca un cimiento. Descartes lo encuentra en la existencia del sujeto que piensa.',
  },
  {
    id: 'fil-111', tema: 'moderna', dificultad: 2,
    enunciado: 'David Hume cuestionó la idea de causalidad al señalar que:',
    opciones: [
      'Solo observamos que dos hechos se suceden con regularidad, no una conexión necesaria entre ellos',
      'Las causas no existen en absoluto',
      'La ciencia es imposible',
      'Los sentidos nunca se equivocan',
    ],
    correcta: 0,
    explicacion: 'Vemos la bola chocar y la otra moverse, pero nunca vemos la necesidad. Kant dijo que esa observación lo despertó de su sueño dogmático.',
  },
  {
    id: 'fil-112', tema: 'moderna', dificultad: 2,
    enunciado: '¿Qué propone Rousseau con la "voluntad general"?',
    opciones: [
      'La voluntad orientada al bien común, distinta de la suma de intereses particulares',
      'La opinión de la mayoría en cualquier votación',
      'El deseo del gobernante',
      'La tradición heredada de los antepasados',
    ],
    correcta: 0,
    explicacion: 'Su ambigüedad es célebre: puede fundar la soberanía popular y también servir para que alguien afirme conocer el bien común mejor que los propios ciudadanos.',
  },
  {
    id: 'fil-113', tema: 'moderna', dificultad: 2,
    enunciado: '¿Qué caracterizó a la Ilustración como proyecto filosófico?',
    opciones: [
      'La confianza en la razón y en la crítica para emancipar al ser humano de la tutela y la superstición',
      'El regreso a la autoridad de la tradición',
      'El rechazo de la ciencia experimental',
      'La defensa del absolutismo monárquico',
    ],
    correcta: 0,
    explicacion: 'Kant la resumió en un lema: "sapere aude", atrévete a saber. La minoría de edad de la que habla es culpable porque no se debe a falta de entendimiento sino de valor para usarlo.',
  },
  {
    id: 'fil-114', tema: 'moderna', dificultad: 3,
    enunciado: '¿Cuál es el giro copernicano de Kant en teoría del conocimiento?',
    opciones: [
      'No es la mente la que se ajusta a los objetos, sino los objetos los que se ajustan a las condiciones de nuestra experiencia',
      'La Tierra gira alrededor del Sol',
      'El conocimiento procede exclusivamente de la experiencia',
      'Las ideas son innatas y perfectas',
    ],
    correcta: 0,
    explicacion: 'Espacio, tiempo y categorías no están en las cosas: son la forma en que podemos percibirlas y pensarlas. De ahí que conozcamos fenómenos y no cosas en sí.',
  },
  {
    id: 'fil-115', tema: 'moderna', dificultad: 3,
    enunciado: '¿Cómo intenta Kant resolver la disputa entre racionalismo y empirismo?',
    opciones: [
      'Sosteniendo que el conocimiento requiere la experiencia como materia y las estructuras del sujeto como forma',
      'Dando la razón íntegramente a Hume',
      'Dando la razón íntegramente a Descartes',
      'Negando que exista conocimiento',
    ],
    correcta: 0,
    explicacion: 'Su fórmula lo condensa: los conceptos sin intuiciones están vacíos y las intuiciones sin conceptos son ciegas. Ninguna de las dos fuentes basta sola.',
  },
  {
    id: 'fil-116', tema: 'moderna', dificultad: 3,
    enunciado: '¿Por qué la separación de poderes de Montesquieu es una idea filosófica y no solo administrativa?',
    opciones: [
      'Parte de una tesis sobre la naturaleza humana: todo poder tiende a abusar, así que solo otro poder puede contenerlo',
      'Busca hacer más eficiente la administración',
      'Se deriva de la teología medieval',
      'Responde a un problema contable',
    ],
    correcta: 0,
    explicacion: 'No confía en la virtud de los gobernantes sino en el diseño institucional. Esa desconfianza estructural es lo que la convierte en una teoría y no en un organigrama.',
  },
  {
    id: 'fil-117', tema: 'moderna', dificultad: 3,
    enunciado: '¿Qué criticó Mary Wollstonecraft a los ilustrados de su tiempo?',
    opciones: [
      'Que proclamaran la razón universal y excluyeran a las mujeres de la educación y de los derechos',
      'Que defendieran la monarquía absoluta',
      'Que rechazaran el método científico',
      'Que escribieran en lenguas vernáculas',
    ],
    correcta: 0,
    explicacion: 'En la "Vindicación de los derechos de la mujer" (1792) usa los propios principios ilustrados contra sus autores: si la razón es universal, la exclusión es incoherente.',
  },
  {
    id: 'fil-118', tema: 'moderna', dificultad: 4,
    enunciado: '¿Qué significa que para Kant conocemos fenómenos pero no el noúmeno?',
    opciones: [
      'Conocemos las cosas tal como se nos aparecen bajo nuestras formas de percepción, no como son en sí mismas',
      'El mundo exterior no existe',
      'Todo conocimiento es ilusorio',
      'Solo conocemos lo que podemos medir',
    ],
    correcta: 0,
    explicacion: 'No es escepticismo: el conocimiento científico es plenamente válido dentro del ámbito de la experiencia posible. Lo que Kant marca es un límite, no una renuncia.',
  },
  {
    id: 'fil-119', tema: 'moderna', dificultad: 4,
    enunciado: '¿Qué tensión hay entre la idea de contrato social y las sociedades reales?',
    opciones: [
      'Nadie firmó nunca ese contrato, y quienes quedaron excluidos —esclavizados, mujeres, pueblos colonizados— tampoco fueron parte',
      'Que el contrato social se firmó en la Edad Media',
      'Que los Estados modernos no tienen constituciones',
      'Que el contrato es un documento perdido',
    ],
    correcta: 0,
    explicacion: 'Sus defensores responden que es un criterio hipotético: no qué se pactó, sino qué podría pactarse entre iguales. La crítica poscolonial y feminista señala quiénes quedaron fuera de esa hipótesis.',
  },
  {
    id: 'fil-120', tema: 'moderna', dificultad: 4,
    enunciado: '¿Por qué se dice que la filosofía moderna pone al sujeto en el centro?',
    opciones: [
      'Porque el punto de partida deja de ser el orden del mundo y pasa a ser las condiciones bajo las cuales un sujeto puede conocerlo',
      'Porque los filósofos modernos escribían autobiografías',
      'Porque se abandona el estudio de la naturaleza',
      'Porque se niega la existencia de los objetos',
    ],
    correcta: 0,
    explicacion: 'De Descartes a Kant, la pregunta pasa de "qué hay" a "qué puedo conocer y con qué derecho". Ese desplazamiento es lo que separa a la modernidad de la filosofía antigua y medieval.',
  },

  // ----- Filosofía contemporánea -----
  {
    id: 'fil-121', tema: 'contemporanea', dificultad: 1,
    enunciado: 'Para Karl Marx, el motor de la historia es:',
    opciones: [
      'La lucha de clases derivada de las relaciones materiales de producción',
      'La voluntad de los grandes hombres',
      'El progreso de las ideas religiosas',
      'El azar de los acontecimientos',
    ],
    correcta: 0,
    explicacion: 'El materialismo histórico invierte a Hegel: no son las ideas las que mueven la sociedad, sino las condiciones materiales las que explican las ideas dominantes.',
  },
  {
    id: 'fil-122', tema: 'contemporanea', dificultad: 1,
    enunciado: 'El existencialismo sostiene que, en el ser humano:',
    opciones: [
      'La existencia precede a la esencia: primero se existe y luego se define uno por sus actos',
      'La esencia está fijada desde el nacimiento',
      'La libertad es una ilusión completa',
      'El sentido de la vida viene dado por la naturaleza',
    ],
    correcta: 0,
    explicacion: 'La fórmula es de Sartre. De ahí se sigue que estamos condenados a ser libres: no hay naturaleza previa que decida por nosotros, y esa ausencia produce angustia.',
  },
  {
    id: 'fil-123', tema: 'contemporanea', dificultad: 1,
    enunciado: '¿Quién escribió "El segundo sexo" y afirmó que "no se nace mujer, se llega a serlo"?',
    opciones: ['Simone de Beauvoir', 'Hannah Arendt', 'Judith Butler', 'Martha Nussbaum'],
    correcta: 0,
    explicacion: 'Publicado en 1949, distingue el hecho biológico de la construcción social del género, y es uno de los textos fundacionales del feminismo filosófico contemporáneo.',
  },
  {
    id: 'fil-124', tema: 'contemporanea', dificultad: 2,
    enunciado: '¿Qué significa que Marx, Nietzsche y Freud sean llamados "maestros de la sospecha"?',
    opciones: [
      'Que muestran cómo la conciencia puede estar determinada por fuerzas que no reconoce: la economía, la voluntad de poder, el inconsciente',
      'Que desconfiaban de la ciencia',
      'Que negaban la existencia de la verdad',
      'Que fueron perseguidos por sus ideas',
    ],
    correcta: 0,
    explicacion: 'La expresión es de Paul Ricoeur. Los tres comparten un gesto: lo que decimos creer no es la razón real de lo que pensamos y hacemos.',
  },
  {
    id: 'fil-125', tema: 'contemporanea', dificultad: 2,
    enunciado: 'Cuando Nietzsche escribe "Dios ha muerto", diagnostica:',
    opciones: [
      'El derrumbe de los fundamentos absolutos que sostenían los valores de la cultura occidental',
      'Un hecho religioso literal',
      'La desaparición de todas las iglesias',
      'El triunfo definitivo de la ciencia',
    ],
    correcta: 0,
    explicacion: 'No lo celebra sin más: advierte que la pérdida deja un vacío, el nihilismo, y que la tarea pendiente es crear nuevos valores en lugar de conservar los viejos sin su fundamento.',
  },
  {
    id: 'fil-126', tema: 'contemporanea', dificultad: 2,
    enunciado: '¿Qué es la "banalidad del mal" según Hannah Arendt?',
    opciones: [
      'Que crímenes enormes pueden ser cometidos por personas corrientes que dejan de pensar y se limitan a cumplir',
      'Que el mal es un fenómeno sin importancia',
      'Que todos los criminales son psicópatas',
      'Que el mal solo existe en los regímenes totalitarios',
    ],
    correcta: 0,
    explicacion: 'La formuló cubriendo el juicio a Eichmann. La tesis inquieta precisamente porque no busca un monstruo: señala la ausencia de juicio propio como condición del horror administrativo.',
  },
  {
    id: 'fil-127', tema: 'contemporanea', dificultad: 2,
    enunciado: '¿Qué propone Rawls con el "velo de ignorancia"?',
    opciones: [
      'Elegir los principios de justicia sin saber qué posición se ocupará en la sociedad resultante',
      'Ignorar los datos económicos al legislar',
      'Prohibir la información sobre los ciudadanos',
      'Decidir por sorteo las leyes',
    ],
    correcta: 0,
    explicacion: 'Es un procedimiento para forzar la imparcialidad: si no sé si seré rico o pobre, sano o enfermo, difícilmente aceptaré reglas que castiguen a los peor situados.',
  },
  {
    id: 'fil-128', tema: 'contemporanea', dificultad: 2,
    enunciado: '¿Qué estudia Michel Foucault con la noción de poder-saber?',
    opciones: [
      'Cómo el conocimiento y las instituciones producen formas de control y definen lo normal y lo desviado',
      'Cómo los gobiernos aprueban leyes',
      'Cómo se financia la investigación científica',
      'Cómo se transmiten los saberes tradicionales',
    ],
    correcta: 0,
    explicacion: 'Analiza la prisión, el hospital o la escuela como dispositivos que clasifican y disciplinan. El poder, en su lectura, no solo reprime: produce sujetos y categorías.',
  },
  {
    id: 'fil-129', tema: 'contemporanea', dificultad: 3,
    enunciado: '¿Cuál es el principio de diferencia de Rawls?',
    opciones: [
      'Las desigualdades solo son justas si benefician a los miembros menos aventajados de la sociedad',
      'Todas las desigualdades deben eliminarse',
      'Las desigualdades son siempre justas si hay libertad de mercado',
      'La diferencia entre personas no tiene relevancia moral',
    ],
    correcta: 0,
    explicacion: 'No prohíbe que unos ganen más: exige que esa diferencia mejore la situación de quien está abajo. Es una forma de hacer compatible la eficiencia con la justicia.',
  },
  {
    id: 'fil-130', tema: 'contemporanea', dificultad: 3,
    enunciado: '¿Qué critica Nozick a las teorías redistributivas como la de Rawls?',
    opciones: [
      'Que si las adquisiciones y transferencias fueron justas, redistribuir el resultado vulnera derechos individuales',
      'Que la desigualdad no existe',
      'Que el Estado debe ser aún mayor',
      'Que la justicia no puede discutirse racionalmente',
    ],
    correcta: 0,
    explicacion: 'Su teoría es histórica: mira cómo se llegó a una distribución, no qué patrón tiene. Rawls mira el resultado; Nozick, el proceso. El debate entre los dos organizó la filosofía política reciente.',
  },
  {
    id: 'fil-131', tema: 'contemporanea', dificultad: 3,
    enunciado: '¿Qué aporta el enfoque de las capacidades de Sen y Nussbaum?',
    opciones: [
      'Mide el desarrollo por lo que las personas pueden efectivamente ser y hacer, no solo por sus ingresos',
      'Sustituye la ética por la economía',
      'Propone eliminar los indicadores sociales',
      'Define la pobreza únicamente por el ingreso diario',
    ],
    correcta: 0,
    explicacion: 'Dos personas con el mismo ingreso pueden tener libertades muy distintas si una es analfabeta o vive sin agua potable. El Índice de Desarrollo Humano nació de este enfoque.',
  },
  {
    id: 'fil-132', tema: 'contemporanea', dificultad: 3,
    enunciado: '¿Qué plantea la ética del discurso de Habermas?',
    opciones: [
      'Una norma es válida si podría ser aceptada por todos los afectados en un diálogo libre de coacción',
      'Que solo los expertos pueden establecer normas',
      'Que las normas dependen de cada cultura',
      'Que el diálogo es irrelevante para la moral',
    ],
    correcta: 0,
    explicacion: 'Traslada el criterio kantiano del monólogo de la conciencia al diálogo real. Su exigencia fuerte es la simetría: nadie puede quedar excluido ni forzado en la deliberación.',
  },
  {
    id: 'fil-133', tema: 'contemporanea', dificultad: 4,
    enunciado: '¿Por qué el existencialismo vincula libertad con angustia y responsabilidad?',
    opciones: [
      'Porque si nada fuera de nosotros determina el sentido, cada elección nos compromete sin excusas posibles',
      'Porque la libertad es imposible en la práctica',
      'Porque la angustia es una enfermedad mental',
      'Porque la responsabilidad recae siempre en la sociedad',
    ],
    correcta: 0,
    explicacion: 'Sartre llama "mala fe" al intento de escapar de esa carga fingiendo que no se podía elegir. La angustia no es un defecto del sistema: es la conciencia de la propia libertad.',
  },
  {
    id: 'fil-134', tema: 'contemporanea', dificultad: 4,
    enunciado: '¿Qué objeción central recibe el velo de ignorancia de Rawls?',
    opciones: [
      'Que las personas despojadas de toda identidad concreta difícilmente representan a sujetos reales con vínculos y tradiciones',
      'Que es imposible olvidar información deliberadamente',
      'Que favorece a los más ricos',
      'Que no admite ninguna desigualdad',
    ],
    correcta: 0,
    explicacion: 'Es la crítica comunitarista de Sandel o MacIntyre: no elegimos desde ninguna parte, sino desde una historia y una comunidad que nos constituyen.',
  },
  {
    id: 'fil-135', tema: 'contemporanea', dificultad: 4,
    enunciado: 'Foucault sostiene que el poder no solo reprime sino que produce. ¿Qué implica eso?',
    opciones: [
      'Que el poder genera categorías, saberes y formas de subjetividad, no solo prohibiciones',
      'Que el poder es siempre beneficioso',
      'Que no existen relaciones de dominación',
      'Que el poder reside únicamente en el Estado',
    ],
    correcta: 0,
    explicacion: 'Categorías como "delincuente", "paciente" o "normal" no describen realidades previas: se producen en prácticas e instituciones, y al hacerlo configuran a quienes clasifican.',
  },

  // ----- Lógica y argumentación filosófica -----
  {
    id: 'fil-136', tema: 'logica', dificultad: 1,
    enunciado: '¿Qué es un argumento?',
    opciones: [
      'Un conjunto de premisas ofrecidas como apoyo de una conclusión',
      'Una discusión entre dos personas',
      'Una opinión expresada con firmeza',
      'Un conjunto de datos estadísticos',
    ],
    correcta: 0,
    explicacion: 'Sin conclusión no hay argumento, solo afirmaciones sueltas; sin premisas, solo una tesis sin respaldo.',
  },
  {
    id: 'fil-137', tema: 'logica', dificultad: 1,
    enunciado: 'En "Todos los mamíferos respiran. La ballena es un mamífero. Luego la ballena respira", el razonamiento es:',
    opciones: ['Deductivo', 'Inductivo', 'Analógico', 'Falaz'],
    correcta: 0,
    explicacion: 'En un argumento deductivo válido, si las premisas son verdaderas la conclusión lo es necesariamente. La inducción, en cambio, solo hace probable la conclusión.',
  },
  {
    id: 'fil-138', tema: 'logica', dificultad: 1,
    enunciado: 'Descalificar a quien argumenta en lugar de responder a su argumento es la falacia:',
    opciones: ['Ad hominem', 'De autoridad', 'De falsa causa', 'De generalización apresurada'],
    correcta: 0,
    explicacion: 'Que alguien tenga defectos no hace falso lo que dice. La excepción es cuando la credibilidad del testimonio es justamente lo que está en discusión.',
  },
  {
    id: 'fil-139', tema: 'logica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre validez y verdad?',
    opciones: [
      'La validez es una propiedad de la forma del argumento; la verdad, de las proposiciones',
      'Son sinónimos en lógica',
      'La validez se aplica a las premisas y la verdad a la conclusión',
      'Un argumento válido siempre tiene premisas verdaderas',
    ],
    correcta: 0,
    explicacion: 'Un argumento puede ser válido con premisas falsas y conclusión falsa. Cuando es válido y además sus premisas son verdaderas, se dice que es sólido.',
    pista: 'Pregúntate: si las premisas fueran verdaderas, ¿podría la conclusión ser falsa?',
  },
  {
    id: 'fil-140', tema: 'logica', dificultad: 2,
    enunciado: '"O estás conmigo o estás contra mí" es un ejemplo de:',
    opciones: [
      'Falso dilema: se presentan dos opciones como si fueran las únicas',
      'Argumento ad hominem',
      'Apelación a la autoridad',
      'Petición de principio',
    ],
    correcta: 0,
    explicacion: 'Casi siempre hay posiciones intermedias, matices o una tercera vía. Reducir el campo a dos opciones es una estrategia retórica frecuente en el debate político.',
  },
  {
    id: 'fil-141', tema: 'logica', dificultad: 2,
    enunciado: '¿En qué consiste la falacia del hombre de paja?',
    opciones: [
      'Deformar la posición del adversario para refutar una versión más débil que nadie sostuvo',
      'Usar ejemplos inventados',
      'Apelar a las emociones del público',
      'Repetir la conclusión como premisa',
    ],
    correcta: 0,
    explicacion: 'Se derrota al muñeco, no al oponente. La contrapartida honesta es el "principio de caridad": reconstruir la posición contraria en su versión más fuerte antes de criticarla.',
  },
  {
    id: 'fil-142', tema: 'logica', dificultad: 2,
    enunciado: '"Es verdad porque lo dijo un famoso" incurre en:',
    opciones: [
      'Apelación a la autoridad irrelevante',
      'Falso dilema',
      'Pendiente resbaladiza',
      'Ad hominem',
    ],
    correcta: 0,
    explicacion: 'Citar a un experto en su campo es legítimo y necesario. La falacia aparece cuando la autoridad invocada no lo es en la materia discutida, o cuando se usa para cerrar el debate.',
  },
  {
    id: 'fil-143', tema: 'logica', dificultad: 2,
    enunciado: '¿Qué es la petición de principio?',
    opciones: [
      'Dar por supuesto en las premisas aquello que se quiere demostrar',
      'Pedir que el otro demuestre su afirmación',
      'Empezar el argumento con una definición',
      'Apelar a un principio moral',
    ],
    correcta: 0,
    explicacion: 'Es el razonamiento circular: "esto es cierto porque lo dice el libro, y el libro es fiable porque dice la verdad". La conclusión ya está metida en el punto de partida.',
  },
  {
    id: 'fil-144', tema: 'logica', dificultad: 3,
    enunciado: '"Si legalizamos esto, mañana no habrá límite alguno y todo será permitido." ¿Qué falacia se comete?',
    opciones: [
      'Pendiente resbaladiza: se afirma una cadena de consecuencias sin justificar cada eslabón',
      'Ad hominem',
      'Falsa analogía',
      'Petición de principio',
    ],
    correcta: 0,
    explicacion: 'No toda predicción de consecuencias es falaz: lo es cuando la cadena se da por obvia sin evidencia de que cada paso lleve al siguiente.',
  },
  {
    id: 'fil-145', tema: 'logica', dificultad: 3,
    enunciado: '¿Qué distingue una analogía legítima de una falsa analogía?',
    opciones: [
      'La legítima se apoya en semejanzas pertinentes para lo que se concluye; la falsa, en parecidos superficiales',
      'La legítima compara cosas idénticas',
      'Las analogías nunca son argumentos válidos',
      'La falsa analogía usa ejemplos históricos',
    ],
    correcta: 0,
    explicacion: 'Comparar un Estado con una familia puede iluminar algo y ocultar mucho. La pregunta siempre es si la semejanza invocada es relevante para el punto en disputa.',
  },
  {
    id: 'fil-146', tema: 'logica', dificultad: 3,
    enunciado: 'Un argumento tiene premisas falsas y conclusión verdadera. ¿Puede ser válido?',
    opciones: [
      'Sí: la validez depende de la forma, no de la verdad de las premisas',
      'No: si las premisas son falsas, el argumento es inválido',
      'Solo si es inductivo',
      'Solo si la conclusión es necesaria',
    ],
    correcta: 0,
    explicacion: '"Todos los peces vuelan; los canarios son peces; luego los canarios vuelan" es válido y tiene conclusión verdadera con premisas falsas. Válido no significa bueno: para eso hace falta solidez.',
  },
  {
    id: 'fil-147', tema: 'logica', dificultad: 3,
    enunciado: '¿Por qué la ausencia de evidencia no siempre es evidencia de ausencia?',
    opciones: [
      'Porque depende de si cabría esperar encontrar evidencia en caso de que la afirmación fuera cierta',
      'Porque nunca se puede demostrar nada negativo',
      'Porque la evidencia siempre es incompleta',
      'Porque la lógica no se aplica a los hechos',
    ],
    correcta: 0,
    explicacion: 'Si busco un elefante en la sala y no lo veo, su ausencia sí es concluyente. Si busco una bacteria a simple vista, no. La clave es cuán detectable sería el objeto.',
  },
  {
    id: 'fil-148', tema: 'logica', dificultad: 4,
    enunciado: '¿Sobre quién recae la carga de la prueba en una discusión racional?',
    opciones: [
      'Sobre quien hace la afirmación positiva, no sobre quien la pone en duda',
      'Sobre quien discrepa de la opinión mayoritaria',
      'Siempre sobre las dos partes por igual',
      'Sobre quien habla en segundo lugar',
    ],
    correcta: 0,
    explicacion: 'Exigir al escéptico que demuestre lo contrario es invertir la carga, una maniobra frecuente. Russell la ilustró con su tetera orbitando el Sol: indemostrable, pero eso no obliga a creer en ella.',
  },
  {
    id: 'fil-149', tema: 'logica', dificultad: 4,
    enunciado: 'Un argumento inductivo sólido, ¿qué garantiza?',
    opciones: [
      'Que la conclusión es probable dadas las premisas, pero nunca necesaria',
      'Que la conclusión es necesariamente verdadera',
      'Que las premisas son verdaderas',
      'Que no contiene falacias',
    ],
    correcta: 0,
    explicacion: 'Es el problema de la inducción que planteó Hume: por muchos cisnes blancos que se observen, nada garantiza que el siguiente lo sea. La ciencia trabaja con ese límite, no lo ignora.',
  },
  {
    id: 'fil-150', tema: 'logica', dificultad: 4,
    enunciado: '¿Por qué señalar que un argumento contiene una falacia no demuestra que su conclusión sea falsa?',
    opciones: [
      'Porque una conclusión verdadera puede estar mal defendida: lo que falla es el apoyo, no necesariamente la tesis',
      'Porque las falacias no existen realmente',
      'Porque toda conclusión es siempre verdadera',
      'Porque solo importa la intención de quien argumenta',
    ],
    correcta: 0,
    explicacion: 'A eso se le llama a veces "falacia de la falacia". Detectar un mal argumento obliga a buscar uno mejor, no autoriza a dar por refutada la posición contraria.',
  },
];
