/**
 * fisica.js — Banco de física.
 *
 * Es el componente físico de la prueba de ciencias naturales del Saber 11 y
 * uno de los cinco componentes del examen de admisión de la UNAL. Casi nunca
 * pregunta una fórmula suelta: da una situación, una gráfica o un montaje y
 * pide interpretarlo, explicarlo o calcular algo con lo que hay.
 *
 * Los números están escogidos para poder resolverse sin calculadora, que es
 * como se presenta el examen. Se usa g = 9,8 m/s².
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const FISICA = [
  // ----- Magnitudes, unidades y vectores -----
  {
    id: 'fis-001', tema: 'magnitudes-medida', dificultad: 1,
    enunciado: '¿Cuál es la unidad de fuerza en el Sistema Internacional?',
    opciones: ['El newton (N)', 'El julio (J)', 'El vatio (W)', 'El pascal (Pa)'],
    correcta: 0,
    explicacion: 'El julio mide energía o trabajo, el vatio potencia y el pascal presión. Un newton es la fuerza que da a 1 kg una aceleración de 1 m/s².',
  },
  {
    id: 'fis-002', tema: 'magnitudes-medida', dificultad: 2,
    enunciado: '¿A cuántos metros por segundo equivalen 72 km/h?',
    opciones: ['20 m/s', '72 m/s', '200 m/s', '1,2 m/s'],
    correcta: 0,
    explicacion: 'Se divide entre 3,6: 72 ÷ 3,6 = 20 m/s. El factor sale de pasar 1 000 m por cada 3 600 s.',
    pista: 'De km/h a m/s se divide entre 3,6; al revés se multiplica.',
  },
  {
    id: 'fis-003', tema: 'magnitudes-medida', dificultad: 1,
    enunciado: '¿Cuál de estas magnitudes es vectorial?',
    opciones: ['La velocidad', 'La masa', 'La temperatura', 'El tiempo'],
    correcta: 0,
    explicacion: 'Una magnitud vectorial necesita dirección y sentido además del valor. Masa, temperatura y tiempo quedan totalmente definidos con un número y su unidad: son escalares.',
  },
  {
    id: 'fis-004', tema: 'magnitudes-medida', dificultad: 2,
    enunciado: 'Escribe 0,0045 m en notación científica.',
    opciones: ['4,5 × 10⁻³ m', '45 × 10⁻⁴ m', '4,5 × 10³ m', '0,45 × 10⁻² m'],
    correcta: 0,
    explicacion: 'La notación científica exige un solo dígito distinto de cero antes de la coma: 4,5 × 10⁻³. Las otras dos últimas opciones valen lo mismo pero no están en forma correcta.',
  },
  {
    id: 'fis-005', tema: 'magnitudes-medida', dificultad: 1,
    enunciado: '¿En qué unidad se mide la energía en el Sistema Internacional?',
    opciones: ['Julio (J)', 'Newton (N)', 'Vatio (W)', 'Caloría (cal)'],
    correcta: 0,
    explicacion: 'La caloría también mide energía, pero no es unidad del SI: 1 cal equivale a unos 4,18 J.',
  },
  {
    id: 'fis-006', tema: 'magnitudes-medida', dificultad: 2,
    enunciado: 'Un vector queda completamente definido cuando se conocen:',
    opciones: [
      'Su magnitud, su dirección y su sentido',
      'Solo su magnitud',
      'Su magnitud y su unidad de medida',
      'Su punto de aplicación únicamente',
    ],
    correcta: 0,
    explicacion: 'Por eso 50 N hacia la derecha y 50 N hacia la izquierda son vectores distintos aunque compartan la magnitud.',
  },
  {
    id: 'fis-007', tema: 'magnitudes-medida', dificultad: 2,
    enunciado: 'Sobre un cuerpo actúan dos fuerzas perpendiculares de 3 N y 4 N. ¿Cuál es la magnitud de la fuerza resultante?',
    opciones: ['5 N', '7 N', '1 N', '12 N'],
    correcta: 0,
    explicacion: 'Al ser perpendiculares se combinan con Pitágoras: √(3² + 4²) = √25 = 5 N. Sumarlas directamente solo valdría si tuvieran la misma dirección.',
  },
  {
    id: 'fis-008', tema: 'magnitudes-medida', dificultad: 2,
    enunciado: 'Un objeto tiene 200 g de masa y ocupa 100 cm³. ¿Cuál es su densidad?',
    opciones: ['2 g/cm³', '0,5 g/cm³', '20 000 g/cm³', '100 g/cm³'],
    correcta: 0,
    explicacion: 'Densidad = masa ÷ volumen = 200 ÷ 100 = 2 g/cm³. Como es mayor que la del agua (1 g/cm³), el objeto se hundiría.',
  },
  {
    id: 'fis-009', tema: 'magnitudes-medida', dificultad: 1,
    enunciado: '¿Qué mide un dinamómetro?',
    opciones: ['Fuerzas', 'Masas', 'Volúmenes', 'Temperaturas'],
    correcta: 0,
    explicacion: 'Funciona con un resorte que se estira en proporción a la fuerza aplicada. La masa se mide con una balanza.',
  },
  {
    id: 'fis-010', tema: 'magnitudes-medida', dificultad: 3,
    enunciado: 'Un instrumento da siempre valores muy parecidos entre sí, pero todos alejados del valor real. Se dice que es:',
    opciones: ['Preciso pero no exacto', 'Exacto pero no preciso', 'Exacto y preciso', 'Ni exacto ni preciso'],
    correcta: 0,
    explicacion: 'La precisión es la repetibilidad y la exactitud es la cercanía al valor verdadero. Un instrumento descalibrado suele ser muy preciso y nada exacto.',
  },

  // ----- Cinemática -----
  {
    id: 'fis-011', tema: 'cinematica', dificultad: 1,
    enunciado: 'Un móvil recorre 120 m en 8 s con velocidad constante. ¿Cuál es su velocidad?',
    opciones: ['15 m/s', '960 m/s', '0,07 m/s', '128 m/s'],
    correcta: 0,
    explicacion: 'v = d/t = 120 ÷ 8 = 15 m/s.',
  },
  {
    id: 'fis-012', tema: 'cinematica', dificultad: 2,
    enunciado: 'Un auto pasa de 0 a 20 m/s en 5 s. ¿Cuál es su aceleración media?',
    opciones: ['4 m/s²', '100 m/s²', '0,25 m/s²', '20 m/s²'],
    correcta: 0,
    explicacion: 'a = Δv/Δt = 20 ÷ 5 = 4 m/s². La aceleración mide cuánto cambia la velocidad por cada segundo.',
  },
  {
    id: 'fis-013', tema: 'cinematica', dificultad: 2,
    enunciado: 'Un objeto se deja caer desde el reposo. Despreciando la resistencia del aire, ¿qué velocidad lleva a los 2 segundos? (g = 9,8 m/s²)',
    opciones: ['19,6 m/s', '9,8 m/s', '4,9 m/s', '39,2 m/s'],
    correcta: 0,
    explicacion: 'v = g·t = 9,8 × 2 = 19,6 m/s. Al partir del reposo la velocidad inicial es cero.',
  },
  {
    id: 'fis-014', tema: 'cinematica', dificultad: 3,
    enunciado: 'Un cuerpo cae libremente desde el reposo durante 3 s. ¿Qué distancia recorre? (g = 9,8 m/s²)',
    opciones: ['44,1 m', '29,4 m', '14,7 m', '88,2 m'],
    correcta: 0,
    explicacion: 'd = ½gt² = ½(9,8)(9) = 44,1 m. La distancia crece con el cuadrado del tiempo, así que en el tercer segundo se recorre mucho más que en el primero.',
  },
  {
    id: 'fis-015', tema: 'cinematica', dificultad: 2,
    enunciado: 'En una gráfica de posición contra tiempo, ¿qué representa la pendiente de la recta?',
    opciones: ['La velocidad', 'La aceleración', 'La distancia recorrida', 'El tiempo transcurrido'],
    correcta: 0,
    explicacion: 'La pendiente es el cambio de posición dividido entre el cambio de tiempo, que es justamente la definición de velocidad.',
  },
  {
    id: 'fis-016', tema: 'cinematica', dificultad: 3,
    enunciado: 'En una gráfica de velocidad contra tiempo, el área bajo la curva representa:',
    opciones: ['La distancia recorrida', 'La aceleración', 'La fuerza aplicada', 'La velocidad media'],
    correcta: 0,
    explicacion: 'Velocidad multiplicada por tiempo da distancia, y eso es lo que mide el área. En esa misma gráfica la pendiente representa la aceleración.',
    pista: 'Piensa qué unidades resultan al multiplicar los dos ejes.',
  },
  {
    id: 'fis-017', tema: 'cinematica', dificultad: 2,
    enunciado: 'En una gráfica de velocidad contra tiempo, una línea horizontal indica que el movimiento es:',
    opciones: [
      'Uniforme: velocidad constante y aceleración cero',
      'Uniformemente acelerado',
      'De reposo absoluto',
      'De aceleración creciente',
    ],
    correcta: 0,
    explicacion: 'Si la velocidad no cambia, la aceleración es cero. Una línea horizontal sobre el eje del tiempo a velocidad cero sí indicaría reposo.',
  },
  {
    id: 'fis-018', tema: 'cinematica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre rapidez y velocidad?',
    opciones: [
      'La rapidez es escalar y la velocidad además indica dirección y sentido',
      'La rapidez se mide en km/h y la velocidad en m/s',
      'La velocidad solo se usa en movimientos rectilíneos',
      'Son sinónimos en física',
    ],
    correcta: 0,
    explicacion: 'Por eso un carro que da vueltas en una pista a rapidez constante sí tiene velocidad variable: cambia la dirección todo el tiempo.',
  },
  {
    id: 'fis-019', tema: 'cinematica', dificultad: 3,
    enunciado: 'Un atleta da una vuelta completa a una pista de 400 m y regresa al punto de partida. ¿Cuáles son su distancia recorrida y su desplazamiento?',
    opciones: [
      'Distancia 400 m y desplazamiento 0 m',
      'Distancia 0 m y desplazamiento 400 m',
      'Los dos valen 400 m',
      'Los dos valen 0 m',
    ],
    correcta: 0,
    explicacion: 'La distancia es la longitud del camino recorrido; el desplazamiento es el vector que une la posición inicial con la final, y al volver al mismo punto vale cero.',
  },
  {
    id: 'fis-020', tema: 'cinematica', dificultad: 2,
    enunciado: 'Un móvil parte con 5 m/s y acelera a 2 m/s². ¿Qué velocidad tiene a los 4 s?',
    opciones: ['13 m/s', '8 m/s', '40 m/s', '10 m/s'],
    correcta: 0,
    explicacion: 'v = v₀ + at = 5 + (2)(4) = 13 m/s.',
  },

  // ----- Dinámica -----
  {
    id: 'fis-021', tema: 'dinamica', dificultad: 1,
    enunciado: 'La primera ley de Newton, o ley de la inercia, afirma que un cuerpo:',
    opciones: [
      'Mantiene su reposo o su movimiento rectilíneo uniforme si no actúa una fuerza neta sobre él',
      'Se acelera en proporción a la fuerza aplicada',
      'Ejerce sobre otro una fuerza igual y opuesta',
      'Siempre termina deteniéndose por su propio peso',
    ],
    correcta: 0,
    explicacion: 'En la Tierra los cuerpos se detienen por el rozamiento, no porque el movimiento se agote solo. Sin fuerza neta, el estado de movimiento se conserva.',
  },
  {
    id: 'fis-022', tema: 'dinamica', dificultad: 1,
    enunciado: '¿Qué fuerza neta se necesita para acelerar a 5 m/s² un cuerpo de 10 kg?',
    opciones: ['50 N', '2 N', '15 N', '0,5 N'],
    correcta: 0,
    explicacion: 'Segunda ley de Newton: F = m·a = 10 × 5 = 50 N.',
  },
  {
    id: 'fis-023', tema: 'dinamica', dificultad: 2,
    enunciado: 'Según la tercera ley de Newton, las fuerzas de acción y reacción:',
    opciones: [
      'Son iguales en magnitud, opuestas en sentido y actúan sobre cuerpos distintos',
      'Se anulan entre sí y por eso nada se mueve',
      'Actúan sobre el mismo cuerpo',
      'Aparecen solo cuando hay contacto físico',
    ],
    correcta: 0,
    explicacion: 'No se anulan justamente porque actúan sobre cuerpos diferentes. Al caminar, empujas el suelo hacia atrás y el suelo te empuja hacia adelante.',
  },
  {
    id: 'fis-024', tema: 'dinamica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre masa y peso?',
    opciones: [
      'La masa es la cantidad de materia y no cambia; el peso es una fuerza que depende de la gravedad del lugar',
      'La masa se mide en newtons y el peso en kilogramos',
      'Son lo mismo medido con instrumentos distintos',
      'El peso no cambia nunca y la masa sí',
    ],
    correcta: 0,
    explicacion: 'Por eso un astronauta tiene la misma masa en la Luna y pesa la sexta parte. La masa se mide en kilogramos y el peso, al ser fuerza, en newtons.',
  },
  {
    id: 'fis-025', tema: 'dinamica', dificultad: 2,
    enunciado: '¿Cuál es el peso aproximado de un cuerpo de 10 kg en la superficie terrestre? (g = 9,8 m/s²)',
    opciones: ['98 N', '10 N', '9,8 N', '980 N'],
    correcta: 0,
    explicacion: 'P = m·g = 10 × 9,8 = 98 N.',
  },
  {
    id: 'fis-026', tema: 'dinamica', dificultad: 2,
    enunciado: 'Si la fuerza neta sobre un cuerpo es cero, entonces el cuerpo:',
    opciones: [
      'Está en reposo o se mueve con velocidad constante en línea recta',
      'Necesariamente está en reposo',
      'Se detiene de forma gradual',
      'Se mueve con aceleración constante',
    ],
    correcta: 0,
    explicacion: 'Fuerza neta cero significa aceleración cero, no velocidad cero. Un carro a 80 km/h constantes por una recta tiene fuerza neta nula.',
  },
  {
    id: 'fis-027', tema: 'dinamica', dificultad: 2,
    enunciado: 'La fuerza de rozamiento entre dos superficies:',
    opciones: [
      'Se opone al movimiento relativo entre ellas',
      'Siempre impide por completo el movimiento',
      'Aumenta con el área de contacto en todos los casos',
      'Desaparece cuando el cuerpo se mueve',
    ],
    correcta: 0,
    explicacion: 'Depende sobre todo de la naturaleza de las superficies y de la fuerza normal, no del área aparente de contacto. Sin rozamiento no se podría caminar ni frenar.',
  },
  {
    id: 'fis-028', tema: 'dinamica', dificultad: 2,
    enunciado: 'Si sobre el mismo cuerpo se duplica la fuerza neta, la aceleración:',
    opciones: ['Se duplica', 'Se reduce a la mitad', 'No cambia', 'Se cuadruplica'],
    correcta: 0,
    explicacion: 'En F = ma, con m constante, fuerza y aceleración son directamente proporcionales.',
  },
  {
    id: 'fis-029', tema: 'dinamica', dificultad: 3,
    enunciado: 'Un pasajero de pie en un bus se va hacia adelante cuando el bus frena bruscamente. ¿Por qué?',
    opciones: [
      'Por inercia: su cuerpo tiende a mantener la velocidad que traía',
      'Porque el bus lo empuja hacia adelante al frenar',
      'Porque disminuye su peso durante la frenada',
      'Porque la fuerza de reacción del freno lo impulsa',
    ],
    correcta: 0,
    explicacion: 'Nada lo empuja hacia adelante: lo que ocurre es que el bus frena y él no. Es el mismo principio del cinturón de seguridad.',
  },
  {
    id: 'fis-030', tema: 'dinamica', dificultad: 2,
    enunciado: 'La fuerza normal que ejerce una superficie sobre un cuerpo apoyado es:',
    opciones: [
      'Perpendicular a la superficie de contacto',
      'Siempre igual al peso del cuerpo, sin excepción',
      'Paralela a la superficie',
      'Siempre vertical hacia abajo',
    ],
    correcta: 0,
    explicacion: 'De ahí su nombre: normal significa perpendicular. En un plano inclinado no es vertical y su magnitud es menor que el peso.',
  },

  // ----- Trabajo, energía y potencia -----
  {
    id: 'fis-031', tema: 'trabajo-energia', dificultad: 1,
    enunciado: 'Una fuerza de 20 N desplaza un cuerpo 5 m en su misma dirección. ¿Qué trabajo realiza?',
    opciones: ['100 J', '4 J', '25 J', '100 N'],
    correcta: 0,
    explicacion: 'W = F·d = 20 × 5 = 100 J. El trabajo se mide en julios, no en newtons.',
  },
  {
    id: 'fis-032', tema: 'trabajo-energia', dificultad: 2,
    enunciado: '¿Cuál es la energía cinética de un cuerpo de 2 kg que se mueve a 10 m/s?',
    opciones: ['100 J', '20 J', '200 J', '10 J'],
    correcta: 0,
    explicacion: 'Ec = ½mv² = ½(2)(100) = 100 J.',
  },
  {
    id: 'fis-033', tema: 'trabajo-energia', dificultad: 2,
    enunciado: '¿Cuál es la energía potencial gravitatoria de un cuerpo de 5 kg situado a 4 m de altura? (g = 9,8 m/s²)',
    opciones: ['196 J', '20 J', '49 J', '98 J'],
    correcta: 0,
    explicacion: 'Ep = m·g·h = 5 × 9,8 × 4 = 196 J.',
  },
  {
    id: 'fis-034', tema: 'trabajo-energia', dificultad: 2,
    enunciado: 'Cuando un objeto cae libremente, ¿qué ocurre con su energía?',
    opciones: [
      'La energía potencial disminuye y la cinética aumenta, manteniéndose constante la suma',
      'Las dos aumentan al mismo tiempo',
      'La energía total disminuye porque se gasta al caer',
      'La cinética se convierte en potencial',
    ],
    correcta: 0,
    explicacion: 'Es la conservación de la energía mecánica, válida si se desprecia el rozamiento. La energía no se gasta: cambia de forma.',
  },
  {
    id: 'fis-035', tema: 'trabajo-energia', dificultad: 2,
    enunciado: 'Una máquina realiza 600 J de trabajo en 3 s. ¿Cuál es su potencia?',
    opciones: ['200 W', '1 800 W', '0,005 W', '200 J'],
    correcta: 0,
    explicacion: 'P = W/t = 600 ÷ 3 = 200 W. La potencia mide qué tan rápido se hace el trabajo, no cuánto trabajo se hace.',
  },
  {
    id: 'fis-036', tema: 'trabajo-energia', dificultad: 3,
    enunciado: 'Una persona camina 50 m en horizontal cargando una caja. ¿Qué trabajo hace la fuerza con la que sostiene la caja?',
    opciones: [
      'Cero, porque la fuerza es vertical y el desplazamiento horizontal',
      'El peso de la caja multiplicado por 50 m',
      'Depende de la velocidad a la que camine',
      'El mismo que si la levantara 50 m',
    ],
    correcta: 0,
    explicacion: 'El trabajo solo cuenta la componente de la fuerza en la dirección del desplazamiento, y aquí es nula. Que la persona se canse es otra cosa: su cuerpo gasta energía aunque el trabajo mecánico sea cero.',
    pista: 'Fíjate en la dirección de la fuerza y la del desplazamiento.',
  },
  {
    id: 'fis-037', tema: 'trabajo-energia', dificultad: 1,
    enunciado: 'La unidad de potencia en el Sistema Internacional es:',
    opciones: ['El vatio (W)', 'El julio (J)', 'El newton (N)', 'El caballo de fuerza'],
    correcta: 0,
    explicacion: 'Un vatio es un julio por segundo. El caballo de fuerza equivale a unos 746 W, pero no es unidad del SI.',
  },
  {
    id: 'fis-038', tema: 'trabajo-energia', dificultad: 3,
    enunciado: 'Si la velocidad de un cuerpo se duplica, su energía cinética:',
    opciones: ['Se cuadruplica', 'Se duplica', 'No cambia', 'Se reduce a la mitad'],
    correcta: 0,
    explicacion: 'En Ec = ½mv² la velocidad está al cuadrado: al duplicarla, 2² = 4. Es la razón física de que un pequeño exceso de velocidad multiplique la gravedad de un choque.',
  },
  {
    id: 'fis-039', tema: 'trabajo-energia', dificultad: 2,
    enunciado: 'Una máquina recibe 1 000 J y entrega 700 J de trabajo útil. ¿Cuál es su rendimiento?',
    opciones: ['70 %', '30 %', '143 %', '700 %'],
    correcta: 0,
    explicacion: 'Rendimiento = útil ÷ recibida = 700 ÷ 1 000 = 0,7. Los 300 J restantes se disipan, casi siempre como calor por rozamiento.',
  },
  {
    id: 'fis-040', tema: 'trabajo-energia', dificultad: 2,
    enunciado: 'El principio de conservación de la energía afirma que la energía:',
    opciones: [
      'No se crea ni se destruye, solo se transforma de una forma a otra',
      'Se consume por completo al usarse',
      'Aumenta cada vez que se realiza trabajo',
      'Solo se conserva en los sistemas eléctricos',
    ],
    correcta: 0,
    explicacion: 'Cuando decimos que la energía "se gasta" queremos decir que se degradó a formas menos aprovechables, sobre todo calor disperso.',
  },

  // ----- Fluidos -----
  {
    id: 'fis-041', tema: 'fluidos', dificultad: 1,
    enunciado: 'Una fuerza de 100 N se aplica sobre una superficie de 0,5 m². ¿Cuál es la presión?',
    opciones: ['200 Pa', '50 Pa', '100 Pa', '0,005 Pa'],
    correcta: 0,
    explicacion: 'P = F/A = 100 ÷ 0,5 = 200 Pa.',
  },
  {
    id: 'fis-042', tema: 'fluidos', dificultad: 2,
    enunciado: 'El principio de Pascal establece que la presión aplicada a un fluido encerrado:',
    opciones: [
      'Se transmite con igual intensidad a todos los puntos del fluido',
      'Solo se transmite hacia abajo',
      'Disminuye al alejarse del punto de aplicación',
      'Se transmite únicamente en líquidos, no en gases',
    ],
    correcta: 0,
    explicacion: 'Es el fundamento de los frenos hidráulicos y del gato hidráulico: una fuerza pequeña sobre un área pequeña produce una fuerza grande sobre un área grande.',
  },
  {
    id: 'fis-043', tema: 'fluidos', dificultad: 2,
    enunciado: 'Según el principio de Arquímedes, el empuje que recibe un cuerpo sumergido es igual a:',
    opciones: [
      'El peso del fluido que desaloja',
      'El peso del propio cuerpo',
      'La presión atmosférica sobre el cuerpo',
      'La diferencia entre su masa y su volumen',
    ],
    correcta: 0,
    explicacion: 'Por eso un barco de acero flota: su casco desplaza un volumen de agua cuyo peso iguala al del barco completo.',
  },
  {
    id: 'fis-044', tema: 'fluidos', dificultad: 2,
    enunciado: 'Un cuerpo flota en un líquido cuando:',
    opciones: [
      'Su densidad es menor que la del líquido',
      'Su masa es menor que la del líquido',
      'Su volumen es mayor que el del líquido',
      'Su peso es cero',
    ],
    correcta: 0,
    explicacion: 'Lo que decide es la densidad, no la masa: un tronco enorme flota y una moneda pequeña se hunde.',
  },
  {
    id: 'fis-045', tema: 'fluidos', dificultad: 2,
    enunciado: 'La presión dentro de un líquido en reposo:',
    opciones: [
      'Aumenta con la profundidad',
      'Es la misma a cualquier profundidad',
      'Disminuye con la profundidad',
      'Depende solo de la forma del recipiente',
    ],
    correcta: 0,
    explicacion: 'A mayor profundidad hay más columna de líquido encima. Por eso las paredes de una represa son más gruesas abajo que arriba.',
  },
  {
    id: 'fis-046', tema: 'fluidos', dificultad: 1,
    enunciado: 'La unidad de presión en el Sistema Internacional es:',
    opciones: ['El pascal (Pa)', 'El newton (N)', 'El julio (J)', 'La atmósfera (atm)'],
    correcta: 0,
    explicacion: 'Un pascal es un newton por metro cuadrado. La atmósfera y el milímetro de mercurio se siguen usando, pero no son del SI.',
  },
  {
    id: 'fis-047', tema: 'fluidos', dificultad: 3,
    enunciado: '¿Por qué un clavo con punta afilada penetra más fácilmente que uno de punta roma, aplicando la misma fuerza?',
    opciones: [
      'Porque al reducirse el área de contacto aumenta la presión',
      'Porque la fuerza aplicada es mayor',
      'Porque el clavo afilado pesa menos',
      'Porque disminuye el rozamiento con el material',
    ],
    correcta: 0,
    explicacion: 'P = F/A: con la misma fuerza, menos área significa más presión. Es el mismo principio de los cuchillos afilados y de las raquetas de nieve, que hacen justo lo contrario.',
  },
  {
    id: 'fis-048', tema: 'fluidos', dificultad: 2,
    enunciado: 'La densidad del agua es 1 g/cm³. Un bloque de 0,8 g/cm³ colocado en agua:',
    opciones: [
      'Flota, con una parte sumergida',
      'Se hunde hasta el fondo',
      'Queda suspendido en el centro',
      'Se disuelve',
    ],
    correcta: 0,
    explicacion: 'Al ser menos denso flota, y la fracción sumergida es igual al cociente de densidades: en este caso el 80 % de su volumen queda bajo el agua.',
  },
  {
    id: 'fis-049', tema: 'fluidos', dificultad: 2,
    enunciado: 'La presión atmosférica, a medida que se asciende en altitud:',
    opciones: [
      'Disminuye, porque hay menos aire encima',
      'Aumenta, porque el aire se comprime',
      'Se mantiene constante',
      'Aumenta solo en las montañas',
    ],
    correcta: 0,
    explicacion: 'Por eso en ciudades altas el agua hierve a menos de 100 °C y las bolsas de papas se inflan al subir una montaña.',
  },
  {
    id: 'fis-050', tema: 'fluidos', dificultad: 3,
    enunciado: 'En una prensa hidráulica se aplican 50 N sobre un émbolo de 0,01 m². ¿Qué fuerza se obtiene en otro émbolo de 0,1 m²?',
    opciones: ['500 N', '50 N', '5 N', '5 000 N'],
    correcta: 0,
    explicacion: 'La presión es la misma: 50 ÷ 0,01 = 5 000 Pa. En el émbolo grande: F = 5 000 × 0,1 = 500 N. La fuerza se multiplica por diez, pero ese émbolo recorre diez veces menos distancia: la energía no se multiplica.',
  },

  // ----- Ondas y sonido -----
  {
    id: 'fis-051', tema: 'ondas', dificultad: 2,
    enunciado: 'Una onda tiene longitud de onda de 2 m y frecuencia de 50 Hz. ¿Cuál es su velocidad?',
    opciones: ['100 m/s', '25 m/s', '52 m/s', '0,04 m/s'],
    correcta: 0,
    explicacion: 'v = λ·f = 2 × 50 = 100 m/s.',
  },
  {
    id: 'fis-052', tema: 'ondas', dificultad: 1,
    enunciado: 'Si una onda tiene una frecuencia de 4 Hz, ¿cuál es su periodo?',
    opciones: ['0,25 s', '4 s', '2 s', '40 s'],
    correcta: 0,
    explicacion: 'El periodo es el inverso de la frecuencia: T = 1/f = 1/4 = 0,25 s. Cuatro ciclos por segundo implica un cuarto de segundo por ciclo.',
  },
  {
    id: 'fis-053', tema: 'ondas', dificultad: 2,
    enunciado: '¿Por qué el sonido no se propaga en el vacío?',
    opciones: [
      'Porque necesita un medio material cuyas partículas vibren',
      'Porque en el vacío no hay gravedad',
      'Porque su frecuencia se vuelve cero',
      'Porque la temperatura del vacío es muy baja',
    ],
    correcta: 0,
    explicacion: 'El sonido es una onda mecánica. La luz, en cambio, es electromagnética y sí viaja en el vacío: por eso vemos el Sol pero no lo oímos.',
  },
  {
    id: 'fis-054', tema: 'ondas', dificultad: 2,
    enunciado: 'En una onda sonora, ¿qué percibimos como volumen y qué como tono?',
    opciones: [
      'El volumen depende de la amplitud y el tono de la frecuencia',
      'El volumen depende de la frecuencia y el tono de la amplitud',
      'Los dos dependen de la longitud de onda',
      'Los dos dependen de la velocidad de la onda',
    ],
    correcta: 0,
    explicacion: 'Más amplitud es más energía y por lo tanto más volumen; más frecuencia es un sonido más agudo.',
  },
  {
    id: 'fis-055', tema: 'ondas', dificultad: 2,
    enunciado: 'El sonido es una onda longitudinal porque:',
    opciones: [
      'Las partículas del medio vibran en la misma dirección en que avanza la onda',
      'Viaja siempre en línea recta',
      'Su longitud de onda es muy grande',
      'Solo se propaga en el aire',
    ],
    correcta: 0,
    explicacion: 'En una onda transversal, como la de una cuerda, las partículas vibran perpendicularmente al avance. El sonido comprime y expande el medio en la dirección del viaje.',
  },
  {
    id: 'fis-056', tema: 'ondas', dificultad: 1,
    enunciado: 'El eco es un ejemplo de:',
    opciones: ['Reflexión del sonido', 'Refracción del sonido', 'Difracción del sonido', 'Absorción del sonido'],
    correcta: 0,
    explicacion: 'La onda choca con una superficie y regresa. Si el obstáculo está demasiado cerca, el sonido reflejado se superpone al original y no se percibe como eco separado.',
  },
  {
    id: 'fis-057', tema: 'ondas', dificultad: 2,
    enunciado: 'Un lápiz sumergido parcialmente en agua parece quebrado. Ese fenómeno se llama:',
    opciones: ['Refracción', 'Reflexión', 'Difracción', 'Interferencia'],
    correcta: 0,
    explicacion: 'La luz cambia de velocidad y de dirección al pasar del agua al aire, y el cerebro interpreta que viene en línea recta.',
  },
  {
    id: 'fis-058', tema: 'ondas', dificultad: 3,
    enunciado: 'El sonido de una ambulancia parece más agudo cuando se acerca y más grave cuando se aleja. Ese fenómeno es:',
    opciones: [
      'El efecto Doppler',
      'La resonancia',
      'La difracción',
      'Un cambio real de la frecuencia emitida',
    ],
    correcta: 0,
    explicacion: 'La sirena emite siempre la misma frecuencia: lo que cambia es la frecuencia con que las ondas llegan al oído por el movimiento relativo. El mismo efecto se usa para medir la velocidad de galaxias y de vehículos.',
  },
  {
    id: 'fis-059', tema: 'ondas', dificultad: 2,
    enunciado: 'En una tormenta vemos el relámpago antes de oír el trueno porque:',
    opciones: [
      'La luz viaja mucho más rápido que el sonido',
      'El relámpago se produce antes que el trueno',
      'El sonido se desvía con el viento',
      'El trueno se origina más lejos',
    ],
    correcta: 0,
    explicacion: 'El sonido viaja a unos 340 m/s en el aire y la luz a unos 300 000 km/s. Los dos se originan a la vez en la descarga.',
  },
  {
    id: 'fis-060', tema: 'ondas', dificultad: 3,
    enunciado: 'Si el sonido viaja a 340 m/s y un eco tarda 2 segundos en regresar, ¿a qué distancia está la pared que lo refleja?',
    opciones: ['340 m', '680 m', '170 m', '1 360 m'],
    correcta: 0,
    explicacion: 'En 2 s el sonido recorre 680 m, pero ese es el viaje de ida y vuelta: la pared está a la mitad, 340 m. Olvidar que el recorrido es doble es el error típico.',
    pista: 'El sonido hace el camino dos veces.',
  },

  // ----- Calor y termodinámica -----
  {
    id: 'fis-061', tema: 'termodinamica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre calor y temperatura?',
    opciones: [
      'El calor es energía que se transfiere por diferencia de temperatura; la temperatura mide la agitación de las partículas',
      'Son dos nombres para la misma magnitud',
      'El calor se mide en grados y la temperatura en julios',
      'La temperatura solo existe en los sólidos',
    ],
    correcta: 0,
    explicacion: 'Un vaso y una piscina pueden estar a la misma temperatura y contener cantidades de energía térmica muy distintas.',
  },
  {
    id: 'fis-062', tema: 'termodinamica', dificultad: 2,
    enunciado: '¿A cuántos kelvin equivalen 27 °C?',
    opciones: ['300 K', '273 K', '27 K', '246 K'],
    correcta: 0,
    explicacion: 'K = °C + 273: 27 + 273 = 300 K. La escala Kelvin parte del cero absoluto, donde cesa la agitación térmica.',
  },
  {
    id: 'fis-063', tema: 'termodinamica', dificultad: 2,
    enunciado: 'Calentar una olla metálica sobre la estufa transfiere calor principalmente por:',
    opciones: ['Conducción', 'Convección', 'Radiación', 'Evaporación'],
    correcta: 0,
    explicacion: 'En la conducción el calor viaja por contacto entre partículas. El agua dentro de la olla se calienta sobre todo por convección, y el Sol nos llega por radiación.',
  },
  {
    id: 'fis-064', tema: 'termodinamica', dificultad: 2,
    enunciado: '¿Por qué los puentes y las vías férreas se construyen con juntas de dilatación?',
    opciones: [
      'Porque los materiales se expanden al calentarse y necesitan espacio',
      'Para que la estructura pueda moverse con el viento',
      'Para reducir el peso total de la obra',
      'Para facilitar el drenaje del agua lluvia',
    ],
    correcta: 0,
    explicacion: 'Sin ese espacio, la dilatación térmica generaría esfuerzos capaces de deformar o romper la estructura.',
  },
  {
    id: 'fis-065', tema: 'termodinamica', dificultad: 2,
    enunciado: '¿Cuáles de estos cambios de estado absorben calor?',
    opciones: [
      'La fusión y la evaporación',
      'La solidificación y la condensación',
      'La fusión y la condensación',
      'Ninguno: los cambios de estado no implican calor',
    ],
    correcta: 0,
    explicacion: 'Pasar a un estado más desordenado requiere energía. Los procesos inversos, solidificar y condensar, liberan calor.',
  },
  {
    id: 'fis-066', tema: 'termodinamica', dificultad: 3,
    enunciado: 'Mientras el hielo se derrite a presión normal, la temperatura de la mezcla de hielo y agua:',
    opciones: [
      'Permanece en 0 °C aunque se siga suministrando calor',
      'Sube de forma constante',
      'Baja hasta que todo el hielo desaparece',
      'Sube solo si se agita la mezcla',
    ],
    correcta: 0,
    explicacion: 'Durante un cambio de estado toda la energía se invierte en romper la estructura, no en aumentar la agitación. Es el calor latente de fusión.',
  },
  {
    id: 'fis-067', tema: 'termodinamica', dificultad: 2,
    enunciado: 'Dos cuerpos a distinta temperatura en contacto alcanzan el equilibrio térmico cuando:',
    opciones: [
      'Los dos quedan a la misma temperatura y cesa la transferencia neta de calor',
      'El más caliente transfiere toda su energía al más frío',
      'El más frío alcanza el cero absoluto',
      'Los dos recuperan su temperatura inicial',
    ],
    correcta: 0,
    explicacion: 'El calor fluye siempre del cuerpo más caliente al más frío, nunca al revés de forma espontánea, hasta igualar las temperaturas.',
  },
  {
    id: 'fis-068', tema: 'termodinamica', dificultad: 3,
    enunciado: 'El agua tiene un calor específico alto. ¿Qué consecuencia tiene eso?',
    opciones: [
      'Necesita mucha energía para cambiar su temperatura, así que modera el clima costero',
      'Se calienta más rápido que cualquier otra sustancia',
      'Hierve a menor temperatura que otros líquidos',
      'No puede almacenar energía térmica',
    ],
    correcta: 0,
    explicacion: 'Por eso el mar se calienta y se enfría despacio y las ciudades costeras tienen menos oscilación térmica que las del interior.',
  },
  {
    id: 'fis-069', tema: 'termodinamica', dificultad: 3,
    enunciado: 'Al tocar una mesa de metal y una de madera que están a la misma temperatura ambiente, el metal se siente más frío porque:',
    opciones: [
      'Conduce el calor de la mano más rápido que la madera',
      'Su temperatura real es menor',
      'Absorbe la humedad de la piel',
      'Refleja el calor corporal',
    ],
    correcta: 0,
    explicacion: 'Lo que la piel detecta no es la temperatura del objeto sino la rapidez con que pierde calor. Es un caso clásico de dato sensorial que contradice la medición.',
  },
  {
    id: 'fis-070', tema: 'termodinamica', dificultad: 2,
    enunciado: 'La primera ley de la termodinámica es, en esencia:',
    opciones: [
      'El principio de conservación de la energía aplicado a sistemas térmicos',
      'La afirmación de que el calor pasa del cuerpo frío al caliente',
      'La imposibilidad de alcanzar el cero absoluto',
      'La ley que define el calor específico de cada sustancia',
    ],
    correcta: 0,
    explicacion: 'La energía interna de un sistema cambia por el calor que intercambia y el trabajo que realiza. Que el calor fluya en un solo sentido es la segunda ley.',
  },

  // ----- Electricidad -----
  {
    id: 'fis-071', tema: 'electricidad', dificultad: 2,
    enunciado: 'Por una resistencia de 4 Ω se aplica una diferencia de potencial de 12 V. ¿Qué corriente circula?',
    opciones: ['3 A', '48 A', '0,33 A', '8 A'],
    correcta: 0,
    explicacion: 'Ley de Ohm: I = V/R = 12 ÷ 4 = 3 A.',
  },
  {
    id: 'fis-072', tema: 'electricidad', dificultad: 1,
    enunciado: 'Dos cargas eléctricas del mismo signo:',
    opciones: ['Se repelen', 'Se atraen', 'No interactúan', 'Se neutralizan'],
    correcta: 0,
    explicacion: 'Cargas iguales se repelen y cargas opuestas se atraen, con una fuerza que disminuye con el cuadrado de la distancia.',
  },
  {
    id: 'fis-073', tema: 'electricidad', dificultad: 1,
    enunciado: 'La corriente eléctrica se mide en:',
    opciones: ['Amperios (A)', 'Voltios (V)', 'Ohmios (Ω)', 'Vatios (W)'],
    correcta: 0,
    explicacion: 'El amperio mide el flujo de carga por segundo. El voltio mide la diferencia de potencial y el ohmio, la resistencia.',
  },
  {
    id: 'fis-074', tema: 'electricidad', dificultad: 2,
    enunciado: 'Dos resistencias de 3 Ω y 5 Ω conectadas en serie equivalen a una resistencia de:',
    opciones: ['8 Ω', '1,875 Ω', '15 Ω', '2 Ω'],
    correcta: 0,
    explicacion: 'En serie las resistencias se suman: 3 + 5 = 8 Ω, porque la corriente debe atravesarlas una tras otra.',
  },
  {
    id: 'fis-075', tema: 'electricidad', dificultad: 3,
    enunciado: 'Dos resistencias iguales de 10 Ω conectadas en paralelo equivalen a:',
    opciones: ['5 Ω', '20 Ω', '10 Ω', '100 Ω'],
    correcta: 0,
    explicacion: 'Para dos resistencias iguales en paralelo, la equivalente es la mitad. En paralelo la resistencia total siempre es menor que la menor de ellas, porque hay más caminos para la corriente.',
  },
  {
    id: 'fis-076', tema: 'electricidad', dificultad: 2,
    enunciado: 'Un aparato funciona a 120 V y consume 2 A. ¿Cuál es su potencia?',
    opciones: ['240 W', '60 W', '122 W', '480 W'],
    correcta: 0,
    explicacion: 'P = V·I = 120 × 2 = 240 W.',
  },
  {
    id: 'fis-077', tema: 'electricidad', dificultad: 1,
    enunciado: '¿Cuál de estos materiales es aislante eléctrico?',
    opciones: ['El caucho', 'El cobre', 'El aluminio', 'El agua con sales'],
    correcta: 0,
    explicacion: 'En un aislante los electrones no se desplazan con facilidad. Por eso los cables llevan cobre por dentro y caucho o plástico por fuera.',
  },
  {
    id: 'fis-078', tema: 'electricidad', dificultad: 2,
    enunciado: 'En un circuito en serie de varias bombillas, si una se funde:',
    opciones: [
      'Se apagan todas, porque se interrumpe el único camino de la corriente',
      'Las demás siguen encendidas igual',
      'Las demás brillan más',
      'El circuito se sobrecalienta',
    ],
    correcta: 0,
    explicacion: 'Esa es la desventaja del circuito en serie. En paralelo cada elemento tiene su propio camino y los demás siguen funcionando.',
  },
  {
    id: 'fis-079', tema: 'electricidad', dificultad: 2,
    enunciado: 'Un equipo de 1 500 W funciona 4 horas. ¿Cuánta energía consume?',
    opciones: ['6 kWh', '6 000 kWh', '375 kWh', '1,5 kWh'],
    correcta: 0,
    explicacion: '1 500 W son 1,5 kW, y 1,5 × 4 = 6 kWh. El kilovatio hora es la unidad con la que se factura la electricidad.',
  },
  {
    id: 'fis-080', tema: 'electricidad', dificultad: 3,
    enunciado: '¿Cuál es la función de un fusible o un breaker en una instalación eléctrica?',
    opciones: [
      'Interrumpir el circuito cuando la corriente supera un valor seguro',
      'Aumentar el voltaje disponible en la red',
      'Reducir el consumo de energía de los aparatos',
      'Convertir la corriente alterna en continua',
    ],
    correcta: 0,
    explicacion: 'Una corriente excesiva calienta los conductores y puede provocar un incendio. El fusible es el punto que se sacrifica antes de que eso ocurra.',
  },

  // ----- Magnetismo y electromagnetismo -----
  {
    id: 'fis-081', tema: 'magnetismo', dificultad: 1,
    enunciado: 'Dos polos magnéticos del mismo tipo, al acercarse:',
    opciones: ['Se repelen', 'Se atraen', 'Se anulan', 'No interactúan'],
    correcta: 0,
    explicacion: 'Igual que con las cargas eléctricas: iguales se repelen y opuestos se atraen.',
  },
  {
    id: 'fis-082', tema: 'magnetismo', dificultad: 2,
    enunciado: 'El experimento de Oersted mostró que:',
    opciones: [
      'Una corriente eléctrica genera un campo magnético a su alrededor',
      'Un imán en reposo produce corriente eléctrica',
      'Los imanes pierden su magnetismo al calentarse',
      'La electricidad y el magnetismo son fenómenos independientes',
    ],
    correcta: 0,
    explicacion: 'Vio que una brújula se desviaba al pasar corriente por un cable cercano. Ese hallazgo unió dos fenómenos que se creían separados y abrió el electromagnetismo.',
  },
  {
    id: 'fis-083', tema: 'magnetismo', dificultad: 2,
    enunciado: 'Un electroimán se construye con:',
    opciones: [
      'Una bobina de alambre por la que circula corriente, normalmente con núcleo de hierro',
      'Dos imanes permanentes enfrentados',
      'Una placa de cobre expuesta al sol',
      'Un cable recto sin corriente',
    ],
    correcta: 0,
    explicacion: 'Su ventaja es que se puede encender y apagar, y su intensidad depende de la corriente y del número de vueltas. Por eso se usa en grúas, timbres y motores.',
  },
  {
    id: 'fis-084', tema: 'magnetismo', dificultad: 3,
    enunciado: 'Al mover un imán dentro de una bobina cerrada se genera corriente eléctrica. Ese fenómeno se llama:',
    opciones: [
      'Inducción electromagnética',
      'Conducción eléctrica',
      'Electrización por frotamiento',
      'Efecto Joule',
    ],
    correcta: 0,
    explicacion: 'Lo descubrió Faraday y es la base de todos los generadores: hace falta movimiento relativo, porque un imán quieto dentro de la bobina no induce nada.',
  },
  {
    id: 'fis-085', tema: 'magnetismo', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre un motor y un generador eléctrico?',
    opciones: [
      'El motor convierte energía eléctrica en movimiento y el generador, movimiento en electricidad',
      'El motor usa corriente continua y el generador alterna, siempre',
      'El generador no necesita imanes',
      'El motor produce calor y el generador no',
    ],
    correcta: 0,
    explicacion: 'Son el mismo principio recorrido en sentidos opuestos, y de hecho muchas máquinas pueden funcionar de las dos maneras.',
  },
  {
    id: 'fis-086', tema: 'magnetismo', dificultad: 1,
    enunciado: 'Una brújula señala el norte porque:',
    opciones: [
      'La Tierra se comporta como un enorme imán y orienta la aguja',
      'La aguja apunta hacia la estrella polar',
      'El norte está a mayor altitud',
      'La rotación terrestre arrastra la aguja',
    ],
    correcta: 0,
    explicacion: 'El campo magnético terrestre se origina en los movimientos del núcleo externo de hierro fundido.',
  },
  {
    id: 'fis-087', tema: 'magnetismo', dificultad: 2,
    enunciado: '¿Cuál de estos materiales es ferromagnético?',
    opciones: ['El hierro', 'El aluminio', 'El cobre', 'El vidrio'],
    correcta: 0,
    explicacion: 'Hierro, níquel y cobalto son los ferromagnéticos comunes. El aluminio y el cobre conducen electricidad pero no son atraídos por un imán.',
  },
  {
    id: 'fis-088', tema: 'magnetismo', dificultad: 3,
    enunciado: 'Si se parte un imán de barra por la mitad, se obtienen:',
    opciones: [
      'Dos imanes completos, cada uno con polo norte y polo sur',
      'Un trozo con polo norte y otro con polo sur',
      'Dos trozos sin magnetismo',
      'Un imán y un trozo de metal común',
    ],
    correcta: 0,
    explicacion: 'No existen los monopolos magnéticos: por pequeño que sea el fragmento, siempre tiene los dos polos. Es una diferencia de fondo con la carga eléctrica, que sí puede estar aislada.',
  },
  {
    id: 'fis-089', tema: 'magnetismo', dificultad: 3,
    enunciado: 'Un transformador sirve para:',
    opciones: [
      'Elevar o reducir el voltaje de una corriente alterna',
      'Convertir corriente alterna en continua',
      'Aumentar la energía total del sistema',
      'Almacenar carga eléctrica',
    ],
    correcta: 0,
    explicacion: 'Funciona por inducción, así que solo opera con corriente alterna. Si sube el voltaje, baja la corriente: la potencia se conserva salvo pérdidas.',
  },
  {
    id: 'fis-090', tema: 'magnetismo', dificultad: 2,
    enunciado: 'Los polos magnéticos de la Tierra:',
    opciones: [
      'No coinciden exactamente con los polos geográficos y se desplazan con el tiempo',
      'Coinciden exactamente con los geográficos',
      'Son fijos desde la formación del planeta',
      'Están en el ecuador',
    ],
    correcta: 0,
    explicacion: 'La diferencia angular entre el norte magnético y el geográfico se llama declinación magnética, y hay que corregirla al navegar con brújula.',
  },

  // ----- Gravitación -----
  {
    id: 'fis-091', tema: 'gravitacion', dificultad: 2,
    enunciado: 'Según la ley de gravitación universal, la fuerza entre dos cuerpos:',
    opciones: [
      'Es proporcional al producto de sus masas e inversamente proporcional al cuadrado de la distancia',
      'Es proporcional a la distancia entre ellos',
      'Depende solo de la masa del cuerpo más grande',
      'Solo existe entre cuerpos celestes',
    ],
    correcta: 0,
    explicacion: 'Actúa entre dos cuerpos cualesquiera, pero es tan débil que solo se nota cuando al menos una masa es enorme.',
  },
  {
    id: 'fis-092', tema: 'gravitacion', dificultad: 3,
    enunciado: 'Si la distancia entre dos cuerpos se duplica, la fuerza gravitatoria entre ellos:',
    opciones: ['Se reduce a la cuarta parte', 'Se reduce a la mitad', 'Se duplica', 'No cambia'],
    correcta: 0,
    explicacion: 'Depende del inverso del cuadrado de la distancia: al duplicarla, 1/2² = 1/4.',
    pista: 'Fíjate en que la distancia está elevada al cuadrado.',
  },
  {
    id: 'fis-093', tema: 'gravitacion', dificultad: 2,
    enunciado: 'Un astronauta de 70 kg viaja a la Luna, donde la gravedad es aproximadamente un sexto de la terrestre. Allí:',
    opciones: [
      'Su masa sigue siendo 70 kg pero su peso es la sexta parte',
      'Su masa y su peso se reducen a la sexta parte',
      'Su masa se reduce y su peso no cambia',
      'Su peso aumenta seis veces',
    ],
    correcta: 0,
    explicacion: 'La masa es una propiedad del cuerpo; el peso es la fuerza con que lo atrae el astro donde esté.',
  },
  {
    id: 'fis-094', tema: 'gravitacion', dificultad: 2,
    enunciado: '¿Qué mantiene a un satélite en órbita alrededor de la Tierra?',
    opciones: [
      'La atracción gravitatoria terrestre, que actúa como fuerza centrípeta',
      'La ausencia total de gravedad a esa altura',
      'El empuje continuo de sus motores',
      'La presión de la atmósfera exterior',
    ],
    correcta: 0,
    explicacion: 'Un satélite está cayendo permanentemente hacia la Tierra, pero avanza tan rápido en horizontal que nunca la alcanza. La gravedad a esa altura sigue siendo casi la de la superficie.',
  },
  {
    id: 'fis-095', tema: 'gravitacion', dificultad: 1,
    enunciado: 'El valor aproximado de la aceleración de la gravedad en la superficie terrestre es:',
    opciones: ['9,8 m/s²', '9,8 m/s', '98 m/s²', '1,6 m/s²'],
    correcta: 0,
    explicacion: 'Se mide en metros por segundo al cuadrado porque es una aceleración. El valor 1,6 m/s² corresponde a la Luna.',
  },
  {
    id: 'fis-096', tema: 'gravitacion', dificultad: 3,
    enunciado: 'Si se dejan caer una pluma y una piedra en el vacío, ambas desde la misma altura:',
    opciones: [
      'Llegan al suelo al mismo tiempo, porque la aceleración no depende de la masa',
      'La piedra llega primero por ser más pesada',
      'La pluma llega primero por tener más superficie',
      'Ninguna cae, porque en el vacío no hay gravedad',
    ],
    correcta: 0,
    explicacion: 'En el aire la pluma se retrasa por la resistencia, no por su masa. El experimento se repitió en la Luna durante la misión Apolo 15.',
  },
  {
    id: 'fis-097', tema: 'gravitacion', dificultad: 2,
    enunciado: 'Las mareas se explican principalmente por:',
    opciones: [
      'La atracción gravitatoria de la Luna y, en menor medida, del Sol sobre las aguas',
      'Los vientos que soplan sobre el océano',
      'La rotación terrestre por sí sola',
      'Las corrientes marinas profundas',
    ],
    correcta: 0,
    explicacion: 'Cuando el Sol y la Luna se alinean, sus efectos se suman y se producen las mareas vivas.',
  },
  {
    id: 'fis-098', tema: 'gravitacion', dificultad: 3,
    enunciado: 'Entre dos satélites en órbita circular, el que está más lejos de la Tierra:',
    opciones: [
      'Se mueve más lento y tarda más en dar una vuelta',
      'Se mueve más rápido y tarda menos',
      'Tiene el mismo periodo que el más cercano',
      'No necesita velocidad para mantenerse en órbita',
    ],
    correcta: 0,
    explicacion: 'A mayor distancia la gravedad es menor, así que basta menos velocidad para mantener la órbita, y además el recorrido es más largo. Es lo que describen las leyes de Kepler.',
  },
  {
    id: 'fis-099', tema: 'gravitacion', dificultad: 3,
    enunciado: 'Los astronautas flotan dentro de la Estación Espacial Internacional porque:',
    opciones: [
      'Ellos y la estación caen juntos hacia la Tierra en caída libre permanente',
      'A esa altura la gravedad terrestre es prácticamente nula',
      'La estación gira y anula la gravedad',
      'Están fuera del campo gravitatorio del planeta',
    ],
    correcta: 0,
    explicacion: 'A unos 400 km de altura la gravedad conserva cerca del 90 % de su valor en superficie. Lo que se siente no es ausencia de gravedad sino ingravidez aparente por la caída libre compartida.',
  },
  {
    id: 'fis-100', tema: 'gravitacion', dificultad: 2,
    enunciado: 'El campo gravitatorio de un planeta depende de:',
    opciones: [
      'Su masa y el radio en que se mide',
      'Únicamente de su tamaño aparente',
      'Su velocidad de rotación',
      'La distancia a la que esté de su estrella',
    ],
    correcta: 0,
    explicacion: 'Por eso Marte, que es más pequeño y menos masivo que la Tierra, tiene una gravedad superficial de alrededor de 3,7 m/s².',
  },
];
