/**
 * fisica.js — Banco de física.
 *
 * Es el componente físico de la prueba de ciencias naturales del Saber 11 y
 * uno de los cinco componentes del examen de admisión de la UNAL. Casi nunca
 * pregunta una fórmula suelta: da una situación, una gráfica o un montaje y
 * pide interpretarlo, explicarlo o calcular algo con lo que hay.
 *
 * Los números están escogidos para poder resolverse sin calculadora, que es
 * como se presenta el examen. Se usa g = 9,8 m/s².
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const FISICA = [
  // ----- Magnitudes, unidades y vectores -----
  {
    id: 'fis-001', tema: 'magnitudes-medida', dificultad: 1,
    enunciado: '¿Cuál es la unidad de fuerza en el Sistema Internacional?',
    opciones: ['El newton (N)', 'El julio (J)', 'El vatio (W)', 'El pascal (Pa)'],
    correcta: 0,
    explicacion: 'El julio mide energía o trabajo, el vatio potencia y el pascal presión. Un newton es la fuerza que da a 1 kg una aceleración de 1 m/s².',
  },
  {
    id: 'fis-002', tema: 'magnitudes-medida', dificultad: 2,
    enunciado: '¿A cuántos metros por segundo equivalen 72 km/h?',
    opciones: ['20 m/s', '72 m/s', '200 m/s', '1,2 m/s'],
    correcta: 0,
    explicacion: 'Se divide entre 3,6: 72 ÷ 3,6 = 20 m/s. El factor sale de pasar 1 000 m por cada 3 600 s.',
    pista: 'De km/h a m/s se divide entre 3,6; al revés se multiplica.',
  },
  {
    id: 'fis-003', tema: 'magnitudes-medida', dificultad: 1,
    enunciado: '¿Cuál de estas magnitudes es vectorial?',
    opciones: ['La velocidad', 'La masa', 'La temperatura', 'El tiempo'],
    correcta: 0,
    explicacion: 'Una magnitud vectorial necesita dirección y sentido además del valor. Masa, temperatura y tiempo quedan totalmente definidos con un número y su unidad: son escalares.',
  },
  {
    id: 'fis-004', tema: 'magnitudes-medida', dificultad: 2,
    enunciado: 'Escribe 0,0045 m en notación científica.',
    opciones: ['4,5 × 10⁻³ m', '45 × 10⁻⁴ m', '4,5 × 10³ m', '0,45 × 10⁻² m'],
    correcta: 0,
    explicacion: 'La notación científica exige un solo dígito distinto de cero antes de la coma: 4,5 × 10⁻³. Las otras dos últimas opciones valen lo mismo pero no están en forma correcta.',
  },
  {
    id: 'fis-005', tema: 'magnitudes-medida', dificultad: 1,
    enunciado: '¿En qué unidad se mide la energía en el Sistema Internacional?',
    opciones: ['Julio (J)', 'Newton (N)', 'Vatio (W)', 'Caloría (cal)'],
    correcta: 0,
    explicacion: 'La caloría también mide energía, pero no es unidad del SI: 1 cal equivale a unos 4,18 J.',
  },
  {
    id: 'fis-006', tema: 'magnitudes-medida', dificultad: 2,
    enunciado: 'Un vector queda completamente definido cuando se conocen:',
    opciones: [
      'Su magnitud, su dirección y su sentido',
      'Solo su magnitud',
      'Su magnitud y su unidad de medida',
      'Su punto de aplicación únicamente',
    ],
    correcta: 0,
    explicacion: 'Por eso 50 N hacia la derecha y 50 N hacia la izquierda son vectores distintos aunque compartan la magnitud.',
  },
  {
    id: 'fis-007', tema: 'magnitudes-medida', dificultad: 2,
    enunciado: 'Sobre un cuerpo actúan dos fuerzas perpendiculares de 3 N y 4 N. ¿Cuál es la magnitud de la fuerza resultante?',
    opciones: ['5 N', '7 N', '1 N', '12 N'],
    correcta: 0,
    explicacion: 'Al ser perpendiculares se combinan con Pitágoras: √(3² + 4²) = √25 = 5 N. Sumarlas directamente solo valdría si tuvieran la misma dirección.',
  },
  {
    id: 'fis-008', tema: 'magnitudes-medida', dificultad: 2,
    enunciado: 'Un objeto tiene 200 g de masa y ocupa 100 cm³. ¿Cuál es su densidad?',
    opciones: ['2 g/cm³', '0,5 g/cm³', '20 000 g/cm³', '100 g/cm³'],
    correcta: 0,
    explicacion: 'Densidad = masa ÷ volumen = 200 ÷ 100 = 2 g/cm³. Como es mayor que la del agua (1 g/cm³), el objeto se hundiría.',
  },
  {
    id: 'fis-009', tema: 'magnitudes-medida', dificultad: 1,
    enunciado: '¿Qué mide un dinamómetro?',
    opciones: ['Fuerzas', 'Masas', 'Volúmenes', 'Temperaturas'],
    correcta: 0,
    explicacion: 'Funciona con un resorte que se estira en proporción a la fuerza aplicada. La masa se mide con una balanza.',
  },
  {
    id: 'fis-010', tema: 'magnitudes-medida', dificultad: 3,
    enunciado: 'Un instrumento da siempre valores muy parecidos entre sí, pero todos alejados del valor real. Se dice que es:',
    opciones: ['Preciso pero no exacto', 'Exacto pero no preciso', 'Exacto y preciso', 'Ni exacto ni preciso'],
    correcta: 0,
    explicacion: 'La precisión es la repetibilidad y la exactitud es la cercanía al valor verdadero. Un instrumento descalibrado suele ser muy preciso y nada exacto.',
  },

  // ----- Cinemática -----
  {
    id: 'fis-011', tema: 'cinematica', dificultad: 1,
    enunciado: 'Un móvil recorre 120 m en 8 s con velocidad constante. ¿Cuál es su velocidad?',
    opciones: ['15 m/s', '960 m/s', '0,07 m/s', '128 m/s'],
    correcta: 0,
    explicacion: 'v = d/t = 120 ÷ 8 = 15 m/s.',
  },
  {
    id: 'fis-012', tema: 'cinematica', dificultad: 2,
    enunciado: 'Un auto pasa de 0 a 20 m/s en 5 s. ¿Cuál es su aceleración media?',
    opciones: ['4 m/s²', '100 m/s²', '0,25 m/s²', '20 m/s²'],
    correcta: 0,
    explicacion: 'a = Δv/Δt = 20 ÷ 5 = 4 m/s². La aceleración mide cuánto cambia la velocidad por cada segundo.',
  },
  {
    id: 'fis-013', tema: 'cinematica', dificultad: 2,
    enunciado: 'Un objeto se deja caer desde el reposo. Despreciando la resistencia del aire, ¿qué velocidad lleva a los 2 segundos? (g = 9,8 m/s²)',
    opciones: ['19,6 m/s', '9,8 m/s', '4,9 m/s', '39,2 m/s'],
    correcta: 0,
    explicacion: 'v = g·t = 9,8 × 2 = 19,6 m/s. Al partir del reposo la velocidad inicial es cero.',
  },
  {
    id: 'fis-014', tema: 'cinematica', dificultad: 3,
    enunciado: 'Un cuerpo cae libremente desde el reposo durante 3 s. ¿Qué distancia recorre? (g = 9,8 m/s²)',
    opciones: ['44,1 m', '29,4 m', '14,7 m', '88,2 m'],
    correcta: 0,
    explicacion: 'd = ½gt² = ½(9,8)(9) = 44,1 m. La distancia crece con el cuadrado del tiempo, así que en el tercer segundo se recorre mucho más que en el primero.',
  },
  {
    id: 'fis-015', tema: 'cinematica', dificultad: 2,
    enunciado: 'En una gráfica de posición contra tiempo, ¿qué representa la pendiente de la recta?',
    opciones: ['La velocidad', 'La aceleración', 'La distancia recorrida', 'El tiempo transcurrido'],
    correcta: 0,
    explicacion: 'La pendiente es el cambio de posición dividido entre el cambio de tiempo, que es justamente la definición de velocidad.',
  },
  {
    id: 'fis-016', tema: 'cinematica', dificultad: 3,
    enunciado: 'En una gráfica de velocidad contra tiempo, el área bajo la curva representa:',
    opciones: ['La distancia recorrida', 'La aceleración', 'La fuerza aplicada', 'La velocidad media'],
    correcta: 0,
    explicacion: 'Velocidad multiplicada por tiempo da distancia, y eso es lo que mide el área. En esa misma gráfica la pendiente representa la aceleración.',
    pista: 'Piensa qué unidades resultan al multiplicar los dos ejes.',
  },
  {
    id: 'fis-017', tema: 'cinematica', dificultad: 2,
    enunciado: 'En una gráfica de velocidad contra tiempo, una línea horizontal indica que el movimiento es:',
    opciones: [
      'Uniforme: velocidad constante y aceleración cero',
      'Uniformemente acelerado',
      'De reposo absoluto',
      'De aceleración creciente',
    ],
    correcta: 0,
    explicacion: 'Si la velocidad no cambia, la aceleración es cero. Una línea horizontal sobre el eje del tiempo a velocidad cero sí indicaría reposo.',
  },
  {
    id: 'fis-018', tema: 'cinematica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre rapidez y velocidad?',
    opciones: [
      'La rapidez es escalar y la velocidad además indica dirección y sentido',
      'La rapidez se mide en km/h y la velocidad en m/s',
      'La velocidad solo se usa en movimientos rectilíneos',
      'Son sinónimos en física',
    ],
    correcta: 0,
    explicacion: 'Por eso un carro que da vueltas en una pista a rapidez constante sí tiene velocidad variable: cambia la dirección todo el tiempo.',
  },
  {
    id: 'fis-019', tema: 'cinematica', dificultad: 3,
    enunciado: 'Un atleta da una vuelta completa a una pista de 400 m y regresa al punto de partida. ¿Cuáles son su distancia recorrida y su desplazamiento?',
    opciones: [
      'Distancia 400 m y desplazamiento 0 m',
      'Distancia 0 m y desplazamiento 400 m',
      'Los dos valen 400 m',
      'Los dos valen 0 m',
    ],
    correcta: 0,
    explicacion: 'La distancia es la longitud del camino recorrido; el desplazamiento es el vector que une la posición inicial con la final, y al volver al mismo punto vale cero.',
  },
  {
    id: 'fis-020', tema: 'cinematica', dificultad: 2,
    enunciado: 'Un móvil parte con 5 m/s y acelera a 2 m/s². ¿Qué velocidad tiene a los 4 s?',
    opciones: ['13 m/s', '8 m/s', '40 m/s', '10 m/s'],
    correcta: 0,
    explicacion: 'v = v₀ + at = 5 + (2)(4) = 13 m/s.',
  },

  // ----- Dinámica -----
  {
    id: 'fis-021', tema: 'dinamica', dificultad: 1,
    enunciado: 'La primera ley de Newton, o ley de la inercia, afirma que un cuerpo:',
    opciones: [
      'Mantiene su reposo o su movimiento rectilíneo uniforme si no actúa una fuerza neta sobre él',
      'Se acelera en proporción a la fuerza aplicada',
      'Ejerce sobre otro una fuerza igual y opuesta',
      'Siempre termina deteniéndose por su propio peso',
    ],
    correcta: 0,
    explicacion: 'En la Tierra los cuerpos se detienen por el rozamiento, no porque el movimiento se agote solo. Sin fuerza neta, el estado de movimiento se conserva.',
  },
  {
    id: 'fis-022', tema: 'dinamica', dificultad: 1,
    enunciado: '¿Qué fuerza neta se necesita para acelerar a 5 m/s² un cuerpo de 10 kg?',
    opciones: ['50 N', '2 N', '15 N', '0,5 N'],
    correcta: 0,
    explicacion: 'Segunda ley de Newton: F = m·a = 10 × 5 = 50 N.',
  },
  {
    id: 'fis-023', tema: 'dinamica', dificultad: 2,
    enunciado: 'Según la tercera ley de Newton, las fuerzas de acción y reacción:',
    opciones: [
      'Son iguales en magnitud, opuestas en sentido y actúan sobre cuerpos distintos',
      'Se anulan entre sí y por eso nada se mueve',
      'Actúan sobre el mismo cuerpo',
      'Aparecen solo cuando hay contacto físico',
    ],
    correcta: 0,
    explicacion: 'No se anulan justamente porque actúan sobre cuerpos diferentes. Al caminar, empujas el suelo hacia atrás y el suelo te empuja hacia adelante.',
  },
  {
    id: 'fis-024', tema: 'dinamica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre masa y peso?',
    opciones: [
      'La masa es la cantidad de materia y no cambia; el peso es una fuerza que depende de la gravedad del lugar',
      'La masa se mide en newtons y el peso en kilogramos',
      'Son lo mismo medido con instrumentos distintos',
      'El peso no cambia nunca y la masa sí',
    ],
    correcta: 0,
    explicacion: 'Por eso un astronauta tiene la misma masa en la Luna y pesa la sexta parte. La masa se mide en kilogramos y el peso, al ser fuerza, en newtons.',
  },
  {
    id: 'fis-025', tema: 'dinamica', dificultad: 2,
    enunciado: '¿Cuál es el peso aproximado de un cuerpo de 10 kg en la superficie terrestre? (g = 9,8 m/s²)',
    opciones: ['98 N', '10 N', '9,8 N', '980 N'],
    correcta: 0,
    explicacion: 'P = m·g = 10 × 9,8 = 98 N.',
  },
  {
    id: 'fis-026', tema: 'dinamica', dificultad: 2,
    enunciado: 'Si la fuerza neta sobre un cuerpo es cero, entonces el cuerpo:',
    opciones: [
      'Está en reposo o se mueve con velocidad constante en línea recta',
      'Necesariamente está en reposo',
      'Se detiene de forma gradual',
      'Se mueve con aceleración constante',
    ],
    correcta: 0,
    explicacion: 'Fuerza neta cero significa aceleración cero, no velocidad cero. Un carro a 80 km/h constantes por una recta tiene fuerza neta nula.',
  },
  {
    id: 'fis-027', tema: 'dinamica', dificultad: 2,
    enunciado: 'La fuerza de rozamiento entre dos superficies:',
    opciones: [
      'Se opone al movimiento relativo entre ellas',
      'Siempre impide por completo el movimiento',
      'Aumenta con el área de contacto en todos los casos',
      'Desaparece cuando el cuerpo se mueve',
    ],
    correcta: 0,
    explicacion: 'Depende sobre todo de la naturaleza de las superficies y de la fuerza normal, no del área aparente de contacto. Sin rozamiento no se podría caminar ni frenar.',
  },
  {
    id: 'fis-028', tema: 'dinamica', dificultad: 2,
    enunciado: 'Si sobre el mismo cuerpo se duplica la fuerza neta, la aceleración:',
    opciones: ['Se duplica', 'Se reduce a la mitad', 'No cambia', 'Se cuadruplica'],
    correcta: 0,
    explicacion: 'En F = ma, con m constante, fuerza y aceleración son directamente proporcionales.',
  },
  {
    id: 'fis-029', tema: 'dinamica', dificultad: 3,
    enunciado: 'Un pasajero de pie en un bus se va hacia adelante cuando el bus frena bruscamente. ¿Por qué?',
    opciones: [
      'Por inercia: su cuerpo tiende a mantener la velocidad que traía',
      'Porque el bus lo empuja hacia adelante al frenar',
      'Porque disminuye su peso durante la frenada',
      'Porque la fuerza de reacción del freno lo impulsa',
    ],
    correcta: 0,
    explicacion: 'Nada lo empuja hacia adelante: lo que ocurre es que el bus frena y él no. Es el mismo principio del cinturón de seguridad.',
  },
  {
    id: 'fis-030', tema: 'dinamica', dificultad: 2,
    enunciado: 'La fuerza normal que ejerce una superficie sobre un cuerpo apoyado es:',
    opciones: [
      'Perpendicular a la superficie de contacto',
      'Siempre igual al peso del cuerpo, sin excepción',
      'Paralela a la superficie',
      'Siempre vertical hacia abajo',
    ],
    correcta: 0,
    explicacion: 'De ahí su nombre: normal significa perpendicular. En un plano inclinado no es vertical y su magnitud es menor que el peso.',
  },

  // ----- Trabajo, energía y potencia -----
  {
    id: 'fis-031', tema: 'trabajo-energia', dificultad: 1,
    enunciado: 'Una fuerza de 20 N desplaza un cuerpo 5 m en su misma dirección. ¿Qué trabajo realiza?',
    opciones: ['100 J', '4 J', '25 J', '100 N'],
    correcta: 0,
    explicacion: 'W = F·d = 20 × 5 = 100 J. El trabajo se mide en julios, no en newtons.',
  },
  {
    id: 'fis-032', tema: 'trabajo-energia', dificultad: 2,
    enunciado: '¿Cuál es la energía cinética de un cuerpo de 2 kg que se mueve a 10 m/s?',
    opciones: ['100 J', '20 J', '200 J', '10 J'],
    correcta: 0,
    explicacion: 'Ec = ½mv² = ½(2)(100) = 100 J.',
  },
  {
    id: 'fis-033', tema: 'trabajo-energia', dificultad: 2,
    enunciado: '¿Cuál es la energía potencial gravitatoria de un cuerpo de 5 kg situado a 4 m de altura? (g = 9,8 m/s²)',
    opciones: ['196 J', '20 J', '49 J', '98 J'],
    correcta: 0,
    explicacion: 'Ep = m·g·h = 5 × 9,8 × 4 = 196 J.',
  },
  {
    id: 'fis-034', tema: 'trabajo-energia', dificultad: 2,
    enunciado: 'Cuando un objeto cae libremente, ¿qué ocurre con su energía?',
    opciones: [
      'La energía potencial disminuye y la cinética aumenta, manteniéndose constante la suma',
      'Las dos aumentan al mismo tiempo',
      'La energía total disminuye porque se gasta al caer',
      'La cinética se convierte en potencial',
    ],
    correcta: 0,
    explicacion: 'Es la conservación de la energía mecánica, válida si se desprecia el rozamiento. La energía no se gasta: cambia de forma.',
  },
  {
    id: 'fis-035', tema: 'trabajo-energia', dificultad: 2,
    enunciado: 'Una máquina realiza 600 J de trabajo en 3 s. ¿Cuál es su potencia?',
    opciones: ['200 W', '1 800 W', '0,005 W', '200 J'],
    correcta: 0,
    explicacion: 'P = W/t = 600 ÷ 3 = 200 W. La potencia mide qué tan rápido se hace el trabajo, no cuánto trabajo se hace.',
  },
  {
    id: 'fis-036', tema: 'trabajo-energia', dificultad: 3,
    enunciado: 'Una persona camina 50 m en horizontal cargando una caja. ¿Qué trabajo hace la fuerza con la que sostiene la caja?',
    opciones: [
      'Cero, porque la fuerza es vertical y el desplazamiento horizontal',
      'El peso de la caja multiplicado por 50 m',
      'Depende de la velocidad a la que camine',
      'El mismo que si la levantara 50 m',
    ],
    correcta: 0,
    explicacion: 'El trabajo solo cuenta la componente de la fuerza en la dirección del desplazamiento, y aquí es nula. Que la persona se canse es otra cosa: su cuerpo gasta energía aunque el trabajo mecánico sea cero.',
    pista: 'Fíjate en la dirección de la fuerza y la del desplazamiento.',
  },
  {
    id: 'fis-037', tema: 'trabajo-energia', dificultad: 1,
    enunciado: 'La unidad de potencia en el Sistema Internacional es:',
    opciones: ['El vatio (W)', 'El julio (J)', 'El newton (N)', 'El caballo de fuerza'],
    correcta: 0,
    explicacion: 'Un vatio es un julio por segundo. El caballo de fuerza equivale a unos 746 W, pero no es unidad del SI.',
  },
  {
    id: 'fis-038', tema: 'trabajo-energia', dificultad: 3,
    enunciado: 'Si la velocidad de un cuerpo se duplica, su energía cinética:',
    opciones: ['Se cuadruplica', 'Se duplica', 'No cambia', 'Se reduce a la mitad'],
    correcta: 0,
    explicacion: 'En Ec = ½mv² la velocidad está al cuadrado: al duplicarla, 2² = 4. Es la razón física de que un pequeño exceso de velocidad multiplique la gravedad de un choque.',
  },
  {
    id: 'fis-039', tema: 'trabajo-energia', dificultad: 2,
    enunciado: 'Una máquina recibe 1 000 J y entrega 700 J de trabajo útil. ¿Cuál es su rendimiento?',
    opciones: ['70 %', '30 %', '143 %', '700 %'],
    correcta: 0,
    explicacion: 'Rendimiento = útil ÷ recibida = 700 ÷ 1 000 = 0,7. Los 300 J restantes se disipan, casi siempre como calor por rozamiento.',
  },
  {
    id: 'fis-040', tema: 'trabajo-energia', dificultad: 2,
    enunciado: 'El principio de conservación de la energía afirma que la energía:',
    opciones: [
      'No se crea ni se destruye, solo se transforma de una forma a otra',
      'Se consume por completo al usarse',
      'Aumenta cada vez que se realiza trabajo',
      'Solo se conserva en los sistemas eléctricos',
    ],
    correcta: 0,
    explicacion: 'Cuando decimos que la energía "se gasta" queremos decir que se degradó a formas menos aprovechables, sobre todo calor disperso.',
  },

  // ----- Fluidos -----
  {
    id: 'fis-041', tema: 'fluidos', dificultad: 1,
    enunciado: 'Una fuerza de 100 N se aplica sobre una superficie de 0,5 m². ¿Cuál es la presión?',
    opciones: ['200 Pa', '50 Pa', '100 Pa', '0,005 Pa'],
    correcta: 0,
    explicacion: 'P = F/A = 100 ÷ 0,5 = 200 Pa.',
  },
  {
    id: 'fis-042', tema: 'fluidos', dificultad: 2,
    enunciado: 'El principio de Pascal establece que la presión aplicada a un fluido encerrado:',
    opciones: [
      'Se transmite con igual intensidad a todos los puntos del fluido',
      'Solo se transmite hacia abajo',
      'Disminuye al alejarse del punto de aplicación',
      'Se transmite únicamente en líquidos, no en gases',
    ],
    correcta: 0,
    explicacion: 'Es el fundamento de los frenos hidráulicos y del gato hidráulico: una fuerza pequeña sobre un área pequeña produce una fuerza grande sobre un área grande.',
  },
  {
    id: 'fis-043', tema: 'fluidos', dificultad: 2,
    enunciado: 'Según el principio de Arquímedes, el empuje que recibe un cuerpo sumergido es igual a:',
    opciones: [
      'El peso del fluido que desaloja',
      'El peso del propio cuerpo',
      'La presión atmosférica sobre el cuerpo',
      'La diferencia entre su masa y su volumen',
    ],
    correcta: 0,
    explicacion: 'Por eso un barco de acero flota: su casco desplaza un volumen de agua cuyo peso iguala al del barco completo.',
  },
  {
    id: 'fis-044', tema: 'fluidos', dificultad: 2,
    enunciado: 'Un cuerpo flota en un líquido cuando:',
    opciones: [
      'Su densidad es menor que la del líquido',
      'Su masa es menor que la del líquido',
      'Su volumen es mayor que el del líquido',
      'Su peso es cero',
    ],
    correcta: 0,
    explicacion: 'Lo que decide es la densidad, no la masa: un tronco enorme flota y una moneda pequeña se hunde.',
  },
  {
    id: 'fis-045', tema: 'fluidos', dificultad: 2,
    enunciado: 'La presión dentro de un líquido en reposo:',
    opciones: [
      'Aumenta con la profundidad',
      'Es la misma a cualquier profundidad',
      'Disminuye con la profundidad',
      'Depende solo de la forma del recipiente',
    ],
    correcta: 0,
    explicacion: 'A mayor profundidad hay más columna de líquido encima. Por eso las paredes de una represa son más gruesas abajo que arriba.',
  },
  {
    id: 'fis-046', tema: 'fluidos', dificultad: 1,
    enunciado: 'La unidad de presión en el Sistema Internacional es:',
    opciones: ['El pascal (Pa)', 'El newton (N)', 'El julio (J)', 'La atmósfera (atm)'],
    correcta: 0,
    explicacion: 'Un pascal es un newton por metro cuadrado. La atmósfera y el milímetro de mercurio se siguen usando, pero no son del SI.',
  },
  {
    id: 'fis-047', tema: 'fluidos', dificultad: 3,
    enunciado: '¿Por qué un clavo con punta afilada penetra más fácilmente que uno de punta roma, aplicando la misma fuerza?',
    opciones: [
      'Porque al reducirse el área de contacto aumenta la presión',
      'Porque la fuerza aplicada es mayor',
      'Porque el clavo afilado pesa menos',
      'Porque disminuye el rozamiento con el material',
    ],
    correcta: 0,
    explicacion: 'P = F/A: con la misma fuerza, menos área significa más presión. Es el mismo principio de los cuchillos afilados y de las raquetas de nieve, que hacen justo lo contrario.',
  },
  {
    id: 'fis-048', tema: 'fluidos', dificultad: 2,
    enunciado: 'La densidad del agua es 1 g/cm³. Un bloque de 0,8 g/cm³ colocado en agua:',
    opciones: [
      'Flota, con una parte sumergida',
      'Se hunde hasta el fondo',
      'Queda suspendido en el centro',
      'Se disuelve',
    ],
    correcta: 0,
    explicacion: 'Al ser menos denso flota, y la fracción sumergida es igual al cociente de densidades: en este caso el 80 % de su volumen queda bajo el agua.',
  },
  {
    id: 'fis-049', tema: 'fluidos', dificultad: 2,
    enunciado: 'La presión atmosférica, a medida que se asciende en altitud:',
    opciones: [
      'Disminuye, porque hay menos aire encima',
      'Aumenta, porque el aire se comprime',
      'Se mantiene constante',
      'Aumenta solo en las montañas',
    ],
    correcta: 0,
    explicacion: 'Por eso en ciudades altas el agua hierve a menos de 100 °C y las bolsas de papas se inflan al subir una montaña.',
  },
  {
    id: 'fis-050', tema: 'fluidos', dificultad: 3,
    enunciado: 'En una prensa hidráulica se aplican 50 N sobre un émbolo de 0,01 m². ¿Qué fuerza se obtiene en otro émbolo de 0,1 m²?',
    opciones: ['500 N', '50 N', '5 N', '5 000 N'],
    correcta: 0,
    explicacion: 'La presión es la misma: 50 ÷ 0,01 = 5 000 Pa. En el émbolo grande: F = 5 000 × 0,1 = 500 N. La fuerza se multiplica por diez, pero ese émbolo recorre diez veces menos distancia: la energía no se multiplica.',
  },

  // ----- Ondas y sonido -----
  {
    id: 'fis-051', tema: 'ondas', dificultad: 2,
    enunciado: 'Una onda tiene longitud de onda de 2 m y frecuencia de 50 Hz. ¿Cuál es su velocidad?',
    opciones: ['100 m/s', '25 m/s', '52 m/s', '0,04 m/s'],
    correcta: 0,
    explicacion: 'v = λ·f = 2 × 50 = 100 m/s.',
  },
  {
    id: 'fis-052', tema: 'ondas', dificultad: 1,
    enunciado: 'Si una onda tiene una frecuencia de 4 Hz, ¿cuál es su periodo?',
    opciones: ['0,25 s', '4 s', '2 s', '40 s'],
    correcta: 0,
    explicacion: 'El periodo es el inverso de la frecuencia: T = 1/f = 1/4 = 0,25 s. Cuatro ciclos por segundo implica un cuarto de segundo por ciclo.',
  },
  {
    id: 'fis-053', tema: 'ondas', dificultad: 2,
    enunciado: '¿Por qué el sonido no se propaga en el vacío?',
    opciones: [
      'Porque necesita un medio material cuyas partículas vibren',
      'Porque en el vacío no hay gravedad',
      'Porque su frecuencia se vuelve cero',
      'Porque la temperatura del vacío es muy baja',
    ],
    correcta: 0,
    explicacion: 'El sonido es una onda mecánica. La luz, en cambio, es electromagnética y sí viaja en el vacío: por eso vemos el Sol pero no lo oímos.',
  },
  {
    id: 'fis-054', tema: 'ondas', dificultad: 2,
    enunciado: 'En una onda sonora, ¿qué percibimos como volumen y qué como tono?',
    opciones: [
      'El volumen depende de la amplitud y el tono de la frecuencia',
      'El volumen depende de la frecuencia y el tono de la amplitud',
      'Los dos dependen de la longitud de onda',
      'Los dos dependen de la velocidad de la onda',
    ],
    correcta: 0,
    explicacion: 'Más amplitud es más energía y por lo tanto más volumen; más frecuencia es un sonido más agudo.',
  },
  {
    id: 'fis-055', tema: 'ondas', dificultad: 2,
    enunciado: 'El sonido es una onda longitudinal porque:',
    opciones: [
      'Las partículas del medio vibran en la misma dirección en que avanza la onda',
      'Viaja siempre en línea recta',
      'Su longitud de onda es muy grande',
      'Solo se propaga en el aire',
    ],
    correcta: 0,
    explicacion: 'En una onda transversal, como la de una cuerda, las partículas vibran perpendicularmente al avance. El sonido comprime y expande el medio en la dirección del viaje.',
  },
  {
    id: 'fis-056', tema: 'ondas', dificultad: 1,
    enunciado: 'El eco es un ejemplo de:',
    opciones: ['Reflexión del sonido', 'Refracción del sonido', 'Difracción del sonido', 'Absorción del sonido'],
    correcta: 0,
    explicacion: 'La onda choca con una superficie y regresa. Si el obstáculo está demasiado cerca, el sonido reflejado se superpone al original y no se percibe como eco separado.',
  },
  {
    id: 'fis-057', tema: 'ondas', dificultad: 2,
    enunciado: 'Un lápiz sumergido parcialmente en agua parece quebrado. Ese fenómeno se llama:',
    opciones: ['Refracción', 'Reflexión', 'Difracción', 'Interferencia'],
    correcta: 0,
    explicacion: 'La luz cambia de velocidad y de dirección al pasar del agua al aire, y el cerebro interpreta que viene en línea recta.',
  },
  {
    id: 'fis-058', tema: 'ondas', dificultad: 3,
    enunciado: 'El sonido de una ambulancia parece más agudo cuando se acerca y más grave cuando se aleja. Ese fenómeno es:',
    opciones: [
      'El efecto Doppler',
      'La resonancia',
      'La difracción',
      'Un cambio real de la frecuencia emitida',
    ],
    correcta: 0,
    explicacion: 'La sirena emite siempre la misma frecuencia: lo que cambia es la frecuencia con que las ondas llegan al oído por el movimiento relativo. El mismo efecto se usa para medir la velocidad de galaxias y de vehículos.',
  },
  {
    id: 'fis-059', tema: 'ondas', dificultad: 2,
    enunciado: 'En una tormenta vemos el relámpago antes de oír el trueno porque:',
    opciones: [
      'La luz viaja mucho más rápido que el sonido',
      'El relámpago se produce antes que el trueno',
      'El sonido se desvía con el viento',
      'El trueno se origina más lejos',
    ],
    correcta: 0,
    explicacion: 'El sonido viaja a unos 340 m/s en el aire y la luz a unos 300 000 km/s. Los dos se originan a la vez en la descarga.',
  },
  {
    id: 'fis-060', tema: 'ondas', dificultad: 3,
    enunciado: 'Si el sonido viaja a 340 m/s y un eco tarda 2 segundos en regresar, ¿a qué distancia está la pared que lo refleja?',
    opciones: ['340 m', '680 m', '170 m', '1 360 m'],
    correcta: 0,
    explicacion: 'En 2 s el sonido recorre 680 m, pero ese es el viaje de ida y vuelta: la pared está a la mitad, 340 m. Olvidar que el recorrido es doble es el error típico.',
    pista: 'El sonido hace el camino dos veces.',
  },

  // ----- Calor y termodinámica -----
  {
    id: 'fis-061', tema: 'termodinamica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre calor y temperatura?',
    opciones: [
      'El calor es energía que se transfiere por diferencia de temperatura; la temperatura mide la agitación de las partículas',
      'Son dos nombres para la misma magnitud',
      'El calor se mide en grados y la temperatura en julios',
      'La temperatura solo existe en los sólidos',
    ],
    correcta: 0,
    explicacion: 'Un vaso y una piscina pueden estar a la misma temperatura y contener cantidades de energía térmica muy distintas.',
  },
  {
    id: 'fis-062', tema: 'termodinamica', dificultad: 2,
    enunciado: '¿A cuántos kelvin equivalen 27 °C?',
    opciones: ['300 K', '273 K', '27 K', '246 K'],
    correcta: 0,
    explicacion: 'K = °C + 273: 27 + 273 = 300 K. La escala Kelvin parte del cero absoluto, donde cesa la agitación térmica.',
  },
  {
    id: 'fis-063', tema: 'termodinamica', dificultad: 2,
    enunciado: 'Calentar una olla metálica sobre la estufa transfiere calor principalmente por:',
    opciones: ['Conducción', 'Convección', 'Radiación', 'Evaporación'],
    correcta: 0,
    explicacion: 'En la conducción el calor viaja por contacto entre partículas. El agua dentro de la olla se calienta sobre todo por convección, y el Sol nos llega por radiación.',
  },
  {
    id: 'fis-064', tema: 'termodinamica', dificultad: 2,
    enunciado: '¿Por qué los puentes y las vías férreas se construyen con juntas de dilatación?',
    opciones: [
      'Porque los materiales se expanden al calentarse y necesitan espacio',
      'Para que la estructura pueda moverse con el viento',
      'Para reducir el peso total de la obra',
      'Para facilitar el drenaje del agua lluvia',
    ],
    correcta: 0,
    explicacion: 'Sin ese espacio, la dilatación térmica generaría esfuerzos capaces de deformar o romper la estructura.',
  },
  {
    id: 'fis-065', tema: 'termodinamica', dificultad: 2,
    enunciado: '¿Cuáles de estos cambios de estado absorben calor?',
    opciones: [
      'La fusión y la evaporación',
      'La solidificación y la condensación',
      'La fusión y la condensación',
      'Ninguno: los cambios de estado no implican calor',
    ],
    correcta: 0,
    explicacion: 'Pasar a un estado más desordenado requiere energía. Los procesos inversos, solidificar y condensar, liberan calor.',
  },
  {
    id: 'fis-066', tema: 'termodinamica', dificultad: 3,
    enunciado: 'Mientras el hielo se derrite a presión normal, la temperatura de la mezcla de hielo y agua:',
    opciones: [
      'Permanece en 0 °C aunque se siga suministrando calor',
      'Sube de forma constante',
      'Baja hasta que todo el hielo desaparece',
      'Sube solo si se agita la mezcla',
    ],
    correcta: 0,
    explicacion: 'Durante un cambio de estado toda la energía se invierte en romper la estructura, no en aumentar la agitación. Es el calor latente de fusión.',
  },
  {
    id: 'fis-067', tema: 'termodinamica', dificultad: 2,
    enunciado: 'Dos cuerpos a distinta temperatura en contacto alcanzan el equilibrio térmico cuando:',
    opciones: [
      'Los dos quedan a la misma temperatura y cesa la transferencia neta de calor',
      'El más caliente transfiere toda su energía al más frío',
      'El más frío alcanza el cero absoluto',
      'Los dos recuperan su temperatura inicial',
    ],
    correcta: 0,
    explicacion: 'El calor fluye siempre del cuerpo más caliente al más frío, nunca al revés de forma espontánea, hasta igualar las temperaturas.',
  },
  {
    id: 'fis-068', tema: 'termodinamica', dificultad: 3,
    enunciado: 'El agua tiene un calor específico alto. ¿Qué consecuencia tiene eso?',
    opciones: [
      'Necesita mucha energía para cambiar su temperatura, así que modera el clima costero',
      'Se calienta más rápido que cualquier otra sustancia',
      'Hierve a menor temperatura que otros líquidos',
      'No puede almacenar energía térmica',
    ],
    correcta: 0,
    explicacion: 'Por eso el mar se calienta y se enfría despacio y las ciudades costeras tienen menos oscilación térmica que las del interior.',
  },
  {
    id: 'fis-069', tema: 'termodinamica', dificultad: 3,
    enunciado: 'Al tocar una mesa de metal y una de madera que están a la misma temperatura ambiente, el metal se siente más frío porque:',
    opciones: [
      'Conduce el calor de la mano más rápido que la madera',
      'Su temperatura real es menor',
      'Absorbe la humedad de la piel',
      'Refleja el calor corporal',
    ],
    correcta: 0,
    explicacion: 'Lo que la piel detecta no es la temperatura del objeto sino la rapidez con que pierde calor. Es un caso clásico de dato sensorial que contradice la medición.',
  },
  {
    id: 'fis-070', tema: 'termodinamica', dificultad: 2,
    enunciado: 'La primera ley de la termodinámica es, en esencia:',
    opciones: [
      'El principio de conservación de la energía aplicado a sistemas térmicos',
      'La afirmación de que el calor pasa del cuerpo frío al caliente',
      'La imposibilidad de alcanzar el cero absoluto',
      'La ley que define el calor específico de cada sustancia',
    ],
    correcta: 0,
    explicacion: 'La energía interna de un sistema cambia por el calor que intercambia y el trabajo que realiza. Que el calor fluya en un solo sentido es la segunda ley.',
  },

  // ----- Electricidad -----
  {
    id: 'fis-071', tema: 'electricidad', dificultad: 2,
    enunciado: 'Por una resistencia de 4 Ω se aplica una diferencia de potencial de 12 V. ¿Qué corriente circula?',
    opciones: ['3 A', '48 A', '0,33 A', '8 A'],
    correcta: 0,
    explicacion: 'Ley de Ohm: I = V/R = 12 ÷ 4 = 3 A.',
  },
  {
    id: 'fis-072', tema: 'electricidad', dificultad: 1,
    enunciado: 'Dos cargas eléctricas del mismo signo:',
    opciones: ['Se repelen', 'Se atraen', 'No interactúan', 'Se neutralizan'],
    correcta: 0,
    explicacion: 'Cargas iguales se repelen y cargas opuestas se atraen, con una fuerza que disminuye con el cuadrado de la distancia.',
  },
  {
    id: 'fis-073', tema: 'electricidad', dificultad: 1,
    enunciado: 'La corriente eléctrica se mide en:',
    opciones: ['Amperios (A)', 'Voltios (V)', 'Ohmios (Ω)', 'Vatios (W)'],
    correcta: 0,
    explicacion: 'El amperio mide el flujo de carga por segundo. El voltio mide la diferencia de potencial y el ohmio, la resistencia.',
  },
  {
    id: 'fis-074', tema: 'electricidad', dificultad: 2,
    enunciado: 'Dos resistencias de 3 Ω y 5 Ω conectadas en serie equivalen a una resistencia de:',
    opciones: ['8 Ω', '1,875 Ω', '15 Ω', '2 Ω'],
    correcta: 0,
    explicacion: 'En serie las resistencias se suman: 3 + 5 = 8 Ω, porque la corriente debe atravesarlas una tras otra.',
  },
  {
    id: 'fis-075', tema: 'electricidad', dificultad: 3,
    enunciado: 'Dos resistencias iguales de 10 Ω conectadas en paralelo equivalen a:',
    opciones: ['5 Ω', '20 Ω', '10 Ω', '100 Ω'],
    correcta: 0,
    explicacion: 'Para dos resistencias iguales en paralelo, la equivalente es la mitad. En paralelo la resistencia total siempre es menor que la menor de ellas, porque hay más caminos para la corriente.',
  },
  {
    id: 'fis-076', tema: 'electricidad', dificultad: 2,
    enunciado: 'Un aparato funciona a 120 V y consume 2 A. ¿Cuál es su potencia?',
    opciones: ['240 W', '60 W', '122 W', '480 W'],
    correcta: 0,
    explicacion: 'P = V·I = 120 × 2 = 240 W.',
  },
  {
    id: 'fis-077', tema: 'electricidad', dificultad: 1,
    enunciado: '¿Cuál de estos materiales es aislante eléctrico?',
    opciones: ['El caucho', 'El cobre', 'El aluminio', 'El agua con sales'],
    correcta: 0,
    explicacion: 'En un aislante los electrones no se desplazan con facilidad. Por eso los cables llevan cobre por dentro y caucho o plástico por fuera.',
  },
  {
    id: 'fis-078', tema: 'electricidad', dificultad: 2,
    enunciado: 'En un circuito en serie de varias bombillas, si una se funde:',
    opciones: [
      'Se apagan todas, porque se interrumpe el único camino de la corriente',
      'Las demás siguen encendidas igual',
      'Las demás brillan más',
      'El circuito se sobrecalienta',
    ],
    correcta: 0,
    explicacion: 'Esa es la desventaja del circuito en serie. En paralelo cada elemento tiene su propio camino y los demás siguen funcionando.',
  },
  {
    id: 'fis-079', tema: 'electricidad', dificultad: 2,
    enunciado: 'Un equipo de 1 500 W funciona 4 horas. ¿Cuánta energía consume?',
    opciones: ['6 kWh', '6 000 kWh', '375 kWh', '1,5 kWh'],
    correcta: 0,
    explicacion: '1 500 W son 1,5 kW, y 1,5 × 4 = 6 kWh. El kilovatio hora es la unidad con la que se factura la electricidad.',
  },
  {
    id: 'fis-080', tema: 'electricidad', dificultad: 3,
    enunciado: '¿Cuál es la función de un fusible o un breaker en una instalación eléctrica?',
    opciones: [
      'Interrumpir el circuito cuando la corriente supera un valor seguro',
      'Aumentar el voltaje disponible en la red',
      'Reducir el consumo de energía de los aparatos',
      'Convertir la corriente alterna en continua',
    ],
    correcta: 0,
    explicacion: 'Una corriente excesiva calienta los conductores y puede provocar un incendio. El fusible es el punto que se sacrifica antes de que eso ocurra.',
  },

  // ----- Magnetismo y electromagnetismo -----
  {
    id: 'fis-081', tema: 'magnetismo', dificultad: 1,
    enunciado: 'Dos polos magnéticos del mismo tipo, al acercarse:',
    opciones: ['Se repelen', 'Se atraen', 'Se anulan', 'No interactúan'],
    correcta: 0,
    explicacion: 'Igual que con las cargas eléctricas: iguales se repelen y opuestos se atraen.',
  },
  {
    id: 'fis-082', tema: 'magnetismo', dificultad: 2,
    enunciado: 'El experimento de Oersted mostró que:',
    opciones: [
      'Una corriente eléctrica genera un campo magnético a su alrededor',
      'Un imán en reposo produce corriente eléctrica',
      'Los imanes pierden su magnetismo al calentarse',
      'La electricidad y el magnetismo son fenómenos independientes',
    ],
    correcta: 0,
    explicacion: 'Vio que una brújula se desviaba al pasar corriente por un cable cercano. Ese hallazgo unió dos fenómenos que se creían separados y abrió el electromagnetismo.',
  },
  {
    id: 'fis-083', tema: 'magnetismo', dificultad: 2,
    enunciado: 'Un electroimán se construye con:',
    opciones: [
      'Una bobina de alambre por la que circula corriente, normalmente con núcleo de hierro',
      'Dos imanes permanentes enfrentados',
      'Una placa de cobre expuesta al sol',
      'Un cable recto sin corriente',
    ],
    correcta: 0,
    explicacion: 'Su ventaja es que se puede encender y apagar, y su intensidad depende de la corriente y del número de vueltas. Por eso se usa en grúas, timbres y motores.',
  },
  {
    id: 'fis-084', tema: 'magnetismo', dificultad: 3,
    enunciado: 'Al mover un imán dentro de una bobina cerrada se genera corriente eléctrica. Ese fenómeno se llama:',
    opciones: [
      'Inducción electromagnética',
      'Conducción eléctrica',
      'Electrización por frotamiento',
      'Efecto Joule',
    ],
    correcta: 0,
    explicacion: 'Lo descubrió Faraday y es la base de todos los generadores: hace falta movimiento relativo, porque un imán quieto dentro de la bobina no induce nada.',
  },
  {
    id: 'fis-085', tema: 'magnetismo', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre un motor y un generador eléctrico?',
    opciones: [
      'El motor convierte energía eléctrica en movimiento y el generador, movimiento en electricidad',
      'El motor usa corriente continua y el generador alterna, siempre',
      'El generador no necesita imanes',
      'El motor produce calor y el generador no',
    ],
    correcta: 0,
    explicacion: 'Son el mismo principio recorrido en sentidos opuestos, y de hecho muchas máquinas pueden funcionar de las dos maneras.',
  },
  {
    id: 'fis-086', tema: 'magnetismo', dificultad: 1,
    enunciado: 'Una brújula señala el norte porque:',
    opciones: [
      'La Tierra se comporta como un enorme imán y orienta la aguja',
      'La aguja apunta hacia la estrella polar',
      'El norte está a mayor altitud',
      'La rotación terrestre arrastra la aguja',
    ],
    correcta: 0,
    explicacion: 'El campo magnético terrestre se origina en los movimientos del núcleo externo de hierro fundido.',
  },
  {
    id: 'fis-087', tema: 'magnetismo', dificultad: 2,
    enunciado: '¿Cuál de estos materiales es ferromagnético?',
    opciones: ['El hierro', 'El aluminio', 'El cobre', 'El vidrio'],
    correcta: 0,
    explicacion: 'Hierro, níquel y cobalto son los ferromagnéticos comunes. El aluminio y el cobre conducen electricidad pero no son atraídos por un imán.',
  },
  {
    id: 'fis-088', tema: 'magnetismo', dificultad: 3,
    enunciado: 'Si se parte un imán de barra por la mitad, se obtienen:',
    opciones: [
      'Dos imanes completos, cada uno con polo norte y polo sur',
      'Un trozo con polo norte y otro con polo sur',
      'Dos trozos sin magnetismo',
      'Un imán y un trozo de metal común',
    ],
    correcta: 0,
    explicacion: 'No existen los monopolos magnéticos: por pequeño que sea el fragmento, siempre tiene los dos polos. Es una diferencia de fondo con la carga eléctrica, que sí puede estar aislada.',
  },
  {
    id: 'fis-089', tema: 'magnetismo', dificultad: 3,
    enunciado: 'Un transformador sirve para:',
    opciones: [
      'Elevar o reducir el voltaje de una corriente alterna',
      'Convertir corriente alterna en continua',
      'Aumentar la energía total del sistema',
      'Almacenar carga eléctrica',
    ],
    correcta: 0,
    explicacion: 'Funciona por inducción, así que solo opera con corriente alterna. Si sube el voltaje, baja la corriente: la potencia se conserva salvo pérdidas.',
  },
  {
    id: 'fis-090', tema: 'magnetismo', dificultad: 2,
    enunciado: 'Los polos magnéticos de la Tierra:',
    opciones: [
      'No coinciden exactamente con los polos geográficos y se desplazan con el tiempo',
      'Coinciden exactamente con los geográficos',
      'Son fijos desde la formación del planeta',
      'Están en el ecuador',
    ],
    correcta: 0,
    explicacion: 'La diferencia angular entre el norte magnético y el geográfico se llama declinación magnética, y hay que corregirla al navegar con brújula.',
  },

  // ----- Gravitación -----
  {
    id: 'fis-091', tema: 'gravitacion', dificultad: 2,
    enunciado: 'Según la ley de gravitación universal, la fuerza entre dos cuerpos:',
    opciones: [
      'Es proporcional al producto de sus masas e inversamente proporcional al cuadrado de la distancia',
      'Es proporcional a la distancia entre ellos',
      'Depende solo de la masa del cuerpo más grande',
      'Solo existe entre cuerpos celestes',
    ],
    correcta: 0,
    explicacion: 'Actúa entre dos cuerpos cualesquiera, pero es tan débil que solo se nota cuando al menos una masa es enorme.',
  },
  {
    id: 'fis-092', tema: 'gravitacion', dificultad: 3,
    enunciado: 'Si la distancia entre dos cuerpos se duplica, la fuerza gravitatoria entre ellos:',
    opciones: ['Se reduce a la cuarta parte', 'Se reduce a la mitad', 'Se duplica', 'No cambia'],
    correcta: 0,
    explicacion: 'Depende del inverso del cuadrado de la distancia: al duplicarla, 1/2² = 1/4.',
    pista: 'Fíjate en que la distancia está elevada al cuadrado.',
  },
  {
    id: 'fis-093', tema: 'gravitacion', dificultad: 2,
    enunciado: 'Un astronauta de 70 kg viaja a la Luna, donde la gravedad es aproximadamente un sexto de la terrestre. Allí:',
    opciones: [
      'Su masa sigue siendo 70 kg pero su peso es la sexta parte',
      'Su masa y su peso se reducen a la sexta parte',
      'Su masa se reduce y su peso no cambia',
      'Su peso aumenta seis veces',
    ],
    correcta: 0,
    explicacion: 'La masa es una propiedad del cuerpo; el peso es la fuerza con que lo atrae el astro donde esté.',
  },
  {
    id: 'fis-094', tema: 'gravitacion', dificultad: 2,
    enunciado: '¿Qué mantiene a un satélite en órbita alrededor de la Tierra?',
    opciones: [
      'La atracción gravitatoria terrestre, que actúa como fuerza centrípeta',
      'La ausencia total de gravedad a esa altura',
      'El empuje continuo de sus motores',
      'La presión de la atmósfera exterior',
    ],
    correcta: 0,
    explicacion: 'Un satélite está cayendo permanentemente hacia la Tierra, pero avanza tan rápido en horizontal que nunca la alcanza. La gravedad a esa altura sigue siendo casi la de la superficie.',
  },
  {
    id: 'fis-095', tema: 'gravitacion', dificultad: 1,
    enunciado: 'El valor aproximado de la aceleración de la gravedad en la superficie terrestre es:',
    opciones: ['9,8 m/s²', '9,8 m/s', '98 m/s²', '1,6 m/s²'],
    correcta: 0,
    explicacion: 'Se mide en metros por segundo al cuadrado porque es una aceleración. El valor 1,6 m/s² corresponde a la Luna.',
  },
  {
    id: 'fis-096', tema: 'gravitacion', dificultad: 3,
    enunciado: 'Si se dejan caer una pluma y una piedra en el vacío, ambas desde la misma altura:',
    opciones: [
      'Llegan al suelo al mismo tiempo, porque la aceleración no depende de la masa',
      'La piedra llega primero por ser más pesada',
      'La pluma llega primero por tener más superficie',
      'Ninguna cae, porque en el vacío no hay gravedad',
    ],
    correcta: 0,
    explicacion: 'En el aire la pluma se retrasa por la resistencia, no por su masa. El experimento se repitió en la Luna durante la misión Apolo 15.',
  },
  {
    id: 'fis-097', tema: 'gravitacion', dificultad: 2,
    enunciado: 'Las mareas se explican principalmente por:',
    opciones: [
      'La atracción gravitatoria de la Luna y, en menor medida, del Sol sobre las aguas',
      'Los vientos que soplan sobre el océano',
      'La rotación terrestre por sí sola',
      'Las corrientes marinas profundas',
    ],
    correcta: 0,
    explicacion: 'Cuando el Sol y la Luna se alinean, sus efectos se suman y se producen las mareas vivas.',
  },
  {
    id: 'fis-098', tema: 'gravitacion', dificultad: 3,
    enunciado: 'Entre dos satélites en órbita circular, el que está más lejos de la Tierra:',
    opciones: [
      'Se mueve más lento y tarda más en dar una vuelta',
      'Se mueve más rápido y tarda menos',
      'Tiene el mismo periodo que el más cercano',
      'No necesita velocidad para mantenerse en órbita',
    ],
    correcta: 0,
    explicacion: 'A mayor distancia la gravedad es menor, así que basta menos velocidad para mantener la órbita, y además el recorrido es más largo. Es lo que describen las leyes de Kepler.',
  },
  {
    id: 'fis-099', tema: 'gravitacion', dificultad: 3,
    enunciado: 'Los astronautas flotan dentro de la Estación Espacial Internacional porque:',
    opciones: [
      'Ellos y la estación caen juntos hacia la Tierra en caída libre permanente',
      'A esa altura la gravedad terrestre es prácticamente nula',
      'La estación gira y anula la gravedad',
      'Están fuera del campo gravitatorio del planeta',
    ],
    correcta: 0,
    explicacion: 'A unos 400 km de altura la gravedad conserva cerca del 90 % de su valor en superficie. Lo que se siente no es ausencia de gravedad sino ingravidez aparente por la caída libre compartida.',
  },
  {
    id: 'fis-100', tema: 'gravitacion', dificultad: 2,
    enunciado: 'El campo gravitatorio de un planeta depende de:',
    opciones: [
      'Su masa y el radio en que se mide',
      'Únicamente de su tamaño aparente',
      'Su velocidad de rotación',
      'La distancia a la que esté de su estrella',
    ],
    correcta: 0,
    explicacion: 'Por eso Marte, que es más pequeño y menos masivo que la Tierra, tiene una gravedad superficial de alrededor de 3,7 m/s².',
  },
  // ----- Ampliación por niveles -----
  {
    id: 'fis-101', tema: 'magnitudes-medida', dificultad: 3,
    enunciado: '¿A qué equivale un newton en unidades básicas del Sistema Internacional?',
    opciones: ['kg·m/s²', 'kg·m/s', 'kg/m³', 'kg·m²/s²'],
    correcta: 0,
    explicacion: 'Sale de F = ma: masa en kilogramos por aceleración en metros por segundo al cuadrado. La última opción, kg·m²/s², es el julio.',
  },
  {
    id: 'fis-102', tema: 'magnitudes-medida', dificultad: 3,
    enunciado: '¿Cuántas cifras significativas tiene la medida 0,0250 m?',
    opciones: ['Tres', 'Dos', 'Cuatro', 'Cinco'],
    correcta: 0,
    explicacion: 'Los ceros a la izquierda solo indican la posición de la coma y no cuentan; el cero final sí cuenta porque expresa precisión. Las cifras son 2, 5 y 0.',
  },
  {
    id: 'fis-103', tema: 'magnitudes-medida', dificultad: 4,
    enunciado: 'La expresión v²/r, con v en m/s y r en metros, tiene unidades de:',
    opciones: ['Aceleración (m/s²)', 'Velocidad (m/s)', 'Fuerza (N)', 'Energía (J)'],
    correcta: 0,
    explicacion: '(m/s)² ÷ m = m²/s² ÷ m = m/s². Es la aceleración centrípeta, y el análisis dimensional permite verificarlo sin recordar la fórmula.',
    pista: 'Reemplaza cada magnitud por su unidad y simplifica como si fueran fracciones.',
  },
  {
    id: 'fis-104', tema: 'magnitudes-medida', dificultad: 4,
    enunciado: 'Una longitud se mide como 2,00 m con una incertidumbre de ±0,01 m. ¿Cuál es el error relativo?',
    opciones: ['0,5 %', '1 %', '2 %', '0,01 %'],
    correcta: 0,
    explicacion: 'El error relativo es 0,01 ÷ 2,00 = 0,005, es decir 0,5 %. Expresarlo en porcentaje permite comparar la calidad de medidas de magnitudes muy distintas.',
  },
  {
    id: 'fis-105', tema: 'magnitudes-medida', dificultad: 4,
    enunciado: 'La densidad del agua es 1 g/cm³. ¿A cuánto equivale en kg/m³?',
    opciones: ['1 000 kg/m³', '1 kg/m³', '100 kg/m³', '10 000 kg/m³'],
    correcta: 0,
    explicacion: 'Un gramo es 0,001 kg y un centímetro cúbico es 0,000001 m³. Al dividir, 0,001 ÷ 0,000001 = 1 000. Por eso un metro cúbico de agua pesa una tonelada.',
  },
  {
    id: 'fis-106', tema: 'cinematica', dificultad: 1,
    enunciado: 'Un atleta recorre 100 m en 20 s. ¿Cuál es su velocidad media?',
    opciones: ['5 m/s', '20 m/s', '2 m/s', '80 m/s'],
    correcta: 0,
    explicacion: 'La velocidad media es distancia dividida entre tiempo: 100 ÷ 20 = 5 m/s.',
  },
  {
    id: 'fis-107', tema: 'cinematica', dificultad: 1,
    enunciado: 'En un movimiento rectilíneo uniforme (MRU):',
    opciones: [
      'La velocidad se mantiene constante y la aceleración es cero',
      'La velocidad aumenta de forma constante',
      'La aceleración es constante y distinta de cero',
      'El cuerpo cambia de dirección periódicamente',
    ],
    correcta: 0,
    explicacion: 'Uniforme significa sin cambios de velocidad: recorre distancias iguales en tiempos iguales y no hay aceleración.',
  },
  {
    id: 'fis-108', tema: 'cinematica', dificultad: 4,
    enunciado: 'Un objeto se deja caer desde el reposo. Tomando g = 10 m/s² y despreciando la resistencia del aire, ¿qué distancia recorre en 3 s?',
    opciones: ['45 m', '30 m', '90 m', '15 m'],
    correcta: 0,
    explicacion: 'Con d = ½gt² se obtiene ½ × 10 × 9 = 45 m. Su velocidad en ese instante sería 30 m/s, que es otra cosa: el error típico es confundir distancia con velocidad.',
  },
  {
    id: 'fis-109', tema: 'cinematica', dificultad: 4,
    enunciado: 'Se lanza una pelota verticalmente hacia arriba. En el punto más alto de su trayectoria:',
    opciones: [
      'La velocidad es cero pero la aceleración sigue siendo g hacia abajo',
      'La velocidad y la aceleración son cero',
      'La aceleración cambia de sentido y apunta hacia arriba',
      'La pelota queda momentáneamente sin fuerzas actuando sobre ella',
    ],
    correcta: 0,
    explicacion: 'La gravedad no se apaga en ningún momento: es justamente lo que frena la pelota, la detiene un instante y la hace bajar. Velocidad cero no implica aceleración cero.',
  },
  {
    id: 'fis-110', tema: 'cinematica', dificultad: 4,
    enunciado: 'En una gráfica de velocidad contra tiempo, el área bajo la curva representa:',
    opciones: ['El desplazamiento del cuerpo', 'La aceleración media', 'La fuerza aplicada', 'La energía cinética'],
    correcta: 0,
    explicacion: 'Velocidad multiplicada por tiempo da distancia, y eso es exactamente lo que mide el área. La pendiente de esa misma gráfica, en cambio, es la aceleración.',
  },
  {
    id: 'fis-111', tema: 'dinamica', dificultad: 1,
    enunciado: '¿Qué afirma la primera ley de Newton?',
    opciones: [
      'Un cuerpo permanece en reposo o en movimiento rectilíneo uniforme si no actúa sobre él una fuerza neta',
      'La fuerza es igual a la masa por la aceleración',
      'A toda acción corresponde una reacción igual y opuesta',
      'Todos los cuerpos caen con la misma aceleración',
    ],
    correcta: 0,
    explicacion: 'Es la ley de la inercia: lo que hay que explicar no es que algo siga moviéndose, sino que cambie su movimiento.',
  },
  {
    id: 'fis-112', tema: 'dinamica', dificultad: 3,
    enunciado: 'Sobre un cuerpo de 10 kg se aplica una fuerza neta de 20 N. ¿Cuál es su aceleración?',
    opciones: ['2 m/s²', '200 m/s²', '0,5 m/s²', '30 m/s²'],
    correcta: 0,
    explicacion: 'De F = ma se despeja a = F/m = 20 ÷ 10 = 2 m/s².',
  },
  {
    id: 'fis-113', tema: 'dinamica', dificultad: 3,
    enunciado: 'Según la tercera ley de Newton, las fuerzas de acción y reacción:',
    opciones: [
      'Son iguales en magnitud, opuestas en sentido y actúan sobre cuerpos distintos',
      'Se anulan entre sí y por eso nada se mueve nunca',
      'Actúan sobre el mismo cuerpo',
      'Solo aparecen cuando hay contacto entre dos objetos',
    ],
    correcta: 0,
    explicacion: 'Que actúen sobre cuerpos distintos es la clave: por eso no se cancelan. El pie empuja el suelo y el suelo empuja al pie, y es este último empujón el que hace caminar.',
  },
  {
    id: 'fis-114', tema: 'dinamica', dificultad: 4,
    enunciado: 'Una caja se desliza por el piso a velocidad constante mientras alguien la empuja. ¿Qué se puede afirmar?',
    opciones: [
      'La fuerza neta sobre la caja es cero: el empuje iguala a la fricción',
      'La fuerza del empuje es mayor que la fricción',
      'No hay fuerza de fricción actuando',
      'La caja tiene aceleración constante distinta de cero',
    ],
    correcta: 0,
    explicacion: 'Velocidad constante significa aceleración cero, y por F = ma eso obliga a que la fuerza neta sea nula. Que haya que seguir empujando no contradice la inercia: es porque la fricción no deja de actuar.',
  },
  {
    id: 'fis-115', tema: 'dinamica', dificultad: 4,
    enunciado: 'Un bloque de 10 kg reposa sobre una superficie horizontal con coeficiente de rozamiento 0,3. Con g = 10 m/s², ¿qué fuerza mínima horizontal se necesita para ponerlo en movimiento?',
    opciones: ['30 N', '3 N', '100 N', '300 N'],
    correcta: 0,
    explicacion: 'La normal es igual al peso: 10 × 10 = 100 N. La fricción máxima es μN = 0,3 × 100 = 30 N, así que hay que superar ese valor.',
  },
  {
    id: 'fis-116', tema: 'dinamica', dificultad: 4,
    enunciado: 'Cuando un bus frena bruscamente, los pasajeros se van hacia adelante. La explicación correcta es que:',
    opciones: [
      'Sus cuerpos tienden a seguir en movimiento porque ninguna fuerza los frena a ellos',
      'Una fuerza los empuja hacia adelante',
      'El bus los expulsa por la aceleración',
      'La gravedad cambia de dirección momentáneamente',
    ],
    correcta: 0,
    explicacion: 'El bus frena porque el pavimento lo frena, pero sobre el pasajero no actúa esa fuerza: sigue a la velocidad que traía. Hablar de una "fuerza hacia adelante" es describir el efecto de la inercia como si fuera una causa.',
  },
  {
    id: 'fis-117', tema: 'trabajo-energia', dificultad: 1,
    enunciado: '¿Cuál es la unidad de trabajo y de energía en el Sistema Internacional?',
    opciones: ['El julio (J)', 'El vatio (W)', 'El newton (N)', 'El pascal (Pa)'],
    correcta: 0,
    explicacion: 'Un julio es el trabajo de una fuerza de un newton a lo largo de un metro. El vatio mide potencia, es decir julios por segundo.',
  },
  {
    id: 'fis-118', tema: 'trabajo-energia', dificultad: 3,
    enunciado: 'Un objeto de 2 kg está a 5 m de altura. Con g = 10 m/s², ¿cuál es su energía potencial gravitatoria?',
    opciones: ['100 J', '10 J', '50 J', '25 J'],
    correcta: 0,
    explicacion: 'Ep = mgh = 2 × 10 × 5 = 100 J.',
  },
  {
    id: 'fis-119', tema: 'trabajo-energia', dificultad: 4,
    enunciado: 'Si un vehículo duplica su velocidad, su energía cinética:',
    opciones: ['Se multiplica por cuatro', 'Se duplica', 'Se mantiene igual', 'Se multiplica por ocho'],
    correcta: 0,
    explicacion: 'Ec = ½mv²: la velocidad está elevada al cuadrado, así que al duplicarla la energía crece cuatro veces. Es la razón física de que los choques a alta velocidad sean desproporcionadamente más graves.',
  },
  {
    id: 'fis-120', tema: 'trabajo-energia', dificultad: 4,
    enunciado: 'Un cuerpo cae libremente desde 20 m de altura. Con g = 10 m/s² y sin rozamiento, ¿con qué velocidad llega al suelo?',
    opciones: ['20 m/s', '10 m/s', '40 m/s', '200 m/s'],
    correcta: 0,
    explicacion: 'Toda la energía potencial se convierte en cinética: mgh = ½mv², así que v = √(2gh) = √400 = 20 m/s. La masa se cancela y por eso no hace falta conocerla.',
  },
  {
    id: 'fis-121', tema: 'trabajo-energia', dificultad: 4,
    enunciado: 'Una persona realiza un trabajo de 600 J en 3 s. ¿Cuál es su potencia media?',
    opciones: ['200 W', '1 800 W', '2 W', '600 W'],
    correcta: 0,
    explicacion: 'La potencia es trabajo dividido entre tiempo: 600 ÷ 3 = 200 W. El mismo trabajo hecho en la mitad del tiempo exigiría el doble de potencia.',
  },
  {
    id: 'fis-122', tema: 'fluidos', dificultad: 1,
    enunciado: 'A medida que se asciende en la atmósfera, la presión atmosférica:',
    opciones: ['Disminuye', 'Aumenta', 'Permanece constante', 'Se vuelve negativa'],
    correcta: 0,
    explicacion: 'La presión se debe al peso del aire que queda encima: cuanto más alto, menos aire hay arriba. Por eso el agua hierve a menor temperatura en Bogotá que en Cartagena.',
  },
  {
    id: 'fis-123', tema: 'fluidos', dificultad: 3,
    enunciado: '¿Qué afirma el principio de Arquímedes?',
    opciones: [
      'Todo cuerpo sumergido recibe un empuje hacia arriba igual al peso del fluido que desaloja',
      'La presión en un fluido es igual en todas direcciones',
      'Los cuerpos más pesados siempre se hunden',
      'La presión aumenta con la profundidad',
    ],
    correcta: 0,
    explicacion: 'El empuje depende del volumen desplazado y de la densidad del fluido, no del material del objeto. Un barco de acero flota porque desplaza mucha agua.',
  },
  {
    id: 'fis-124', tema: 'fluidos', dificultad: 4,
    enunciado: 'Un objeto flota en el agua si:',
    opciones: [
      'Su densidad media es menor que la del agua',
      'Su masa es menor que un kilogramo',
      'Su volumen es mayor que el del agua desplazada',
      'Está hecho de madera',
    ],
    correcta: 0,
    explicacion: 'Lo que decide es la densidad media, que incluye el aire encerrado: un casco de acero hueco tiene densidad media menor que el agua y flota, mientras que un tornillo del mismo acero se hunde.',
  },
  {
    id: 'fis-125', tema: 'fluidos', dificultad: 4,
    enunciado: '¿Cuál es aproximadamente la presión que ejerce una columna de agua de 10 m de profundidad? (densidad 1 000 kg/m³, g = 10 m/s²)',
    opciones: ['100 000 Pa, equivalente a una atmósfera adicional', '10 000 Pa', '1 000 Pa', '1 000 000 Pa'],
    correcta: 0,
    explicacion: 'p = ρgh = 1 000 × 10 × 10 = 100 000 Pa. Por eso cada 10 m de descenso en el agua añaden aproximadamente una atmósfera a la presión que soporta un buzo.',
  },
  {
    id: 'fis-126', tema: 'fluidos', dificultad: 4,
    enunciado: 'En una prensa hidráulica, el pistón pequeño tiene 10 cm² y el grande 200 cm². Si se aplican 50 N en el pequeño, ¿qué fuerza se obtiene en el grande?',
    opciones: ['1 000 N', '50 N', '250 N', '2 000 N'],
    correcta: 0,
    explicacion: 'La presión se transmite igual en todo el fluido (principio de Pascal), así que F2 = F1 × (A2/A1) = 50 × 20 = 1 000 N. Lo que no se multiplica es el trabajo: el pistón grande se desplaza veinte veces menos.',
  },
  {
    id: 'fis-127', tema: 'ondas', dificultad: 1,
    enunciado: '¿Por qué el sonido no se propaga en el vacío?',
    opciones: [
      'Porque necesita un medio material cuyas partículas vibren',
      'Porque en el vacío no hay gravedad',
      'Porque su velocidad sería infinita',
      'Porque la luz lo bloquea',
    ],
    correcta: 0,
    explicacion: 'El sonido es una onda mecánica: consiste en compresiones y dilataciones de un medio. La luz, en cambio, es una onda electromagnética y sí viaja por el vacío.',
  },
  {
    id: 'fis-128', tema: 'ondas', dificultad: 3,
    enunciado: 'Si el sonido viaja a 340 m/s y una onda tiene una frecuencia de 170 Hz, ¿cuál es su longitud de onda?',
    opciones: ['2 m', '0,5 m', '170 m', '340 m'],
    correcta: 0,
    explicacion: 'De v = λf se despeja λ = v/f = 340 ÷ 170 = 2 m.',
  },
  {
    id: 'fis-129', tema: 'ondas', dificultad: 4,
    enunciado: 'La sirena de una ambulancia suena más aguda cuando se acerca y más grave cuando se aleja. ¿Cómo se llama ese fenómeno y por qué ocurre?',
    opciones: [
      'Efecto Doppler: al acercarse, los frentes de onda llegan más juntos y la frecuencia percibida aumenta',
      'Reflexión: el sonido rebota en los edificios',
      'Refracción: el sonido cambia de medio',
      'Resonancia: la sirena vibra con la frecuencia del aire',
    ],
    correcta: 0,
    explicacion: 'La fuente no cambia el sonido que emite: lo que cambia es la frecuencia con que las ondas alcanzan al oyente. El mismo efecto, aplicado a la luz de las galaxias, es el corrimiento al rojo.',
  },
  {
    id: 'fis-130', tema: 'ondas', dificultad: 4,
    enunciado: 'Una persona grita frente a una montaña y escucha el eco 2 s después. Si el sonido viaja a 340 m/s, ¿a qué distancia está la montaña?',
    opciones: ['340 m', '680 m', '170 m', '1 020 m'],
    correcta: 0,
    explicacion: 'En 2 s el sonido recorre 680 m, pero ese es el viaje de ida y vuelta. La distancia es la mitad: 340 m.',
    pista: 'El eco recorre dos veces el trayecto: recuerda dividir entre dos.',
  },
  {
    id: 'fis-131', tema: 'ondas', dificultad: 4,
    enunciado: 'El sonido que viaja por el aire es una onda:',
    opciones: [
      'Longitudinal, porque las partículas vibran en la misma dirección en que avanza la onda',
      'Transversal, porque las partículas vibran perpendicularmente al avance',
      'Electromagnética, porque no necesita medio',
      'Estacionaria, porque no se desplaza',
    ],
    correcta: 0,
    explicacion: 'En el aire solo pueden propagarse compresiones y dilataciones, que son longitudinales. Las ondas en una cuerda o la luz sí son transversales.',
  },
  {
    id: 'fis-132', tema: 'termodinamica', dificultad: 1,
    enunciado: 'Cuando se ponen en contacto un cuerpo caliente y uno frío, el calor fluye:',
    opciones: ['Del más caliente al más frío', 'Del más frío al más caliente', 'En ambos sentidos por igual', 'Solo si son del mismo material'],
    correcta: 0,
    explicacion: 'El calor siempre fluye espontáneamente hacia la menor temperatura, hasta que ambas se igualan: es el equilibrio térmico.',
  },
  {
    id: 'fis-133', tema: 'termodinamica', dificultad: 1,
    enunciado: 'A nivel del mar, ¿a qué temperatura se funde el hielo?',
    opciones: ['0 °C', '100 °C', '-10 °C', '32 °C'],
    correcta: 0,
    explicacion: 'El punto de fusión del hielo es 0 °C, y el de ebullición del agua, 100 °C a presión normal. La escala Celsius se definió justamente a partir de esos dos puntos.',
  },
  {
    id: 'fis-134', tema: 'termodinamica', dificultad: 1,
    enunciado: 'Al calentarse, la mayoría de los materiales sólidos:',
    opciones: ['Se dilatan', 'Se contraen', 'Mantienen exactamente su tamaño', 'Se vuelven más densos'],
    correcta: 0,
    explicacion: 'El aumento de temperatura hace vibrar más las partículas y aumenta la separación media entre ellas. Por eso los puentes y las vías férreas llevan juntas de dilatación.',
  },
  {
    id: 'fis-135', tema: 'termodinamica', dificultad: 4,
    enunciado: '¿Cuál es la diferencia entre calor y temperatura?',
    opciones: [
      'La temperatura mide la energía cinética media de las partículas; el calor es energía que se transfiere entre cuerpos',
      'Son sinónimos, pero se miden en unidades distintas',
      'El calor es una propiedad que un cuerpo posee y la temperatura, la que transfiere',
      'La temperatura solo se aplica a gases y el calor, a sólidos',
    ],
    correcta: 0,
    explicacion: 'Un cuerpo no "tiene" calor: tiene energía interna. El calor es el nombre de la energía mientras pasa de un cuerpo a otro por diferencia de temperatura. Por eso una chispa a 800 °C quema menos que una olla de agua a 90 °C: menos masa, menos energía transferida.',
  },
  {
    id: 'fis-136', tema: 'termodinamica', dificultad: 4,
    enunciado: '¿A cuántos kelvin equivalen 27 °C?',
    opciones: ['300 K', '27 K', '273 K', '246 K'],
    correcta: 0,
    explicacion: 'Se suman 273: 27 + 273 = 300 K. La escala kelvin parte del cero absoluto, la temperatura mínima posible, y por eso no admite valores negativos.',
  },
  {
    id: 'fis-137', tema: 'termodinamica', dificultad: 4,
    enunciado: 'Mientras un bloque de hielo se derrite a 0 °C, se le sigue suministrando calor. ¿Qué ocurre con su temperatura?',
    opciones: [
      'Permanece en 0 °C hasta que todo el hielo se haya fundido',
      'Sube de forma constante hasta llegar a 100 °C',
      'Baja, porque el hielo absorbe frío',
      'Sube de golpe apenas empieza a derretirse',
    ],
    correcta: 0,
    explicacion: 'Durante un cambio de estado, la energía se usa en romper la estructura del sólido y no en aumentar la energía cinética: es el calor latente de fusión. Por eso el hielo enfría una bebida de forma tan eficaz.',
  },
  {
    id: 'fis-138', tema: 'electricidad', dificultad: 3,
    enunciado: 'A una resistencia de 4 Ω se le aplican 12 V. ¿Qué corriente circula por ella?',
    opciones: ['3 A', '48 A', '0,33 A', '16 A'],
    correcta: 0,
    explicacion: 'Por la ley de Ohm, I = V/R = 12 ÷ 4 = 3 A.',
  },
  {
    id: 'fis-139', tema: 'electricidad', dificultad: 4,
    enunciado: 'Dos resistencias iguales de 10 Ω se conectan en paralelo. La resistencia equivalente es:',
    opciones: ['5 Ω', '20 Ω', '10 Ω', '0,1 Ω'],
    correcta: 0,
    explicacion: 'En paralelo, 1/R = 1/10 + 1/10 = 2/10, así que R = 5 Ω. La equivalente siempre es menor que la más pequeña, porque se abren más caminos para la corriente; en serie, en cambio, se suman y darían 20 Ω.',
  },
  {
    id: 'fis-140', tema: 'electricidad', dificultad: 4,
    enunciado: 'Un aparato conectado a 120 V consume una corriente de 5 A. ¿Cuál es su potencia?',
    opciones: ['600 W', '24 W', '125 W', '60 W'],
    correcta: 0,
    explicacion: 'P = V × I = 120 × 5 = 600 W. Si funciona dos horas, consume 1,2 kWh, que es lo que aparece en el recibo.',
  },
  {
    id: 'fis-141', tema: 'electricidad', dificultad: 4,
    enunciado: '¿Por qué un cortocircuito puede provocar un incendio?',
    opciones: [
      'Porque la resistencia del camino se hace casi nula y la corriente se dispara, calentando los conductores',
      'Porque el voltaje aumenta de golpe',
      'Porque la corriente deja de circular y se acumula energía',
      'Porque la electricidad cambia de sentido',
    ],
    correcta: 0,
    explicacion: 'Con I = V/R, si R tiende a cero la corriente se vuelve enorme, y el calor disipado crece con el cuadrado de la corriente. Los breakers y fusibles existen para cortar el circuito antes de que eso ocurra.',
  },
  {
    id: 'fis-142', tema: 'magnetismo', dificultad: 1,
    enunciado: 'Si se acercan dos polos magnéticos iguales (norte con norte):',
    opciones: ['Se repelen', 'Se atraen', 'No ocurre nada', 'Se neutralizan y pierden el magnetismo'],
    correcta: 0,
    explicacion: 'Polos iguales se repelen y polos distintos se atraen, igual que ocurre con las cargas eléctricas.',
  },
  {
    id: 'fis-143', tema: 'magnetismo', dificultad: 4,
    enunciado: 'El experimento de Oersted demostró que:',
    opciones: [
      'Una corriente eléctrica genera un campo magnético a su alrededor',
      'Los imanes pierden su fuerza al calentarse',
      'La luz es una onda electromagnética',
      'Las cargas iguales se repelen',
    ],
    correcta: 0,
    explicacion: 'Al pasar corriente por un alambre, la aguja de una brújula cercana se desviaba. Ese hallazgo unió dos fenómenos que se creían independientes y abrió el camino al electromagnetismo y al motor eléctrico.',
  },
  {
    id: 'fis-144', tema: 'magnetismo', dificultad: 4,
    enunciado: 'Si se mueve un imán dentro de una bobina de alambre conectada a un medidor, se observa que:',
    opciones: [
      'Aparece corriente en la bobina mientras el imán se mueve',
      'La bobina se calienta pero no circula corriente',
      'El imán pierde su magnetismo',
      'No ocurre nada, porque no hay batería en el circuito',
    ],
    correcta: 0,
    explicacion: 'Es la inducción electromagnética de Faraday: lo que genera corriente es la variación del flujo magnético, no la presencia del imán. En eso se basan los generadores de todas las centrales eléctricas.',
  },
  {
    id: 'fis-145', tema: 'magnetismo', dificultad: 4,
    enunciado: 'Si se parte un imán de barra por la mitad, se obtiene:',
    opciones: [
      'Dos imanes, cada uno con su polo norte y su polo sur',
      'Un trozo con polo norte y otro con polo sur',
      'Dos trozos sin magnetismo',
      'Un imán más potente y otro sin fuerza',
    ],
    correcta: 0,
    explicacion: 'No existen los monopolos magnéticos: por pequeño que sea el fragmento, siempre tiene los dos polos. Es una diferencia fundamental con la carga eléctrica, que sí puede aislarse positiva o negativa.',
  },
  {
    id: 'fis-146', tema: 'gravitacion', dificultad: 1,
    enunciado: 'La fuerza de gravedad terrestre atrae los objetos hacia:',
    opciones: ['El centro de la Tierra', 'El polo norte', 'El Sol', 'La Luna'],
    correcta: 0,
    explicacion: 'Por eso "abajo" significa cosas distintas en Colombia y en Australia: en ambos casos apunta hacia el centro del planeta.',
  },
  {
    id: 'fis-147', tema: 'gravitacion', dificultad: 1,
    enunciado: 'Un astronauta viaja a la Luna. ¿Qué ocurre con su masa y con su peso?',
    opciones: [
      'La masa no cambia; el peso disminuye porque la gravedad lunar es menor',
      'Los dos disminuyen por igual',
      'La masa disminuye y el peso se mantiene',
      'Los dos se mantienen iguales',
    ],
    correcta: 0,
    explicacion: 'La masa es la cantidad de materia y es la misma en cualquier lugar; el peso es la fuerza con que un astro la atrae, y en la Luna es unas seis veces menor.',
  },
  {
    id: 'fis-148', tema: 'gravitacion', dificultad: 4,
    enunciado: 'Si la distancia entre dos cuerpos se duplica, la fuerza gravitatoria entre ellos:',
    opciones: ['Se reduce a la cuarta parte', 'Se reduce a la mitad', 'Se mantiene igual', 'Se duplica'],
    correcta: 0,
    explicacion: 'La ley de gravitación universal es inversamente proporcional al cuadrado de la distancia: al duplicarla, el denominador se multiplica por cuatro.',
  },
  {
    id: 'fis-149', tema: 'gravitacion', dificultad: 4,
    enunciado: 'Los astronautas flotan dentro de la Estación Espacial Internacional porque:',
    opciones: [
      'Están en caída libre permanente alrededor de la Tierra junto con la estación',
      'A esa altura ya no hay gravedad terrestre',
      'La estación gira y anula la gravedad',
      'El vacío del espacio elimina el peso',
    ],
    correcta: 0,
    explicacion: 'A 400 km de altura la gravedad todavía es cerca del 90 % de la que hay en la superficie. Lo que ocurre es que la estación y sus tripulantes caen juntos: están en órbita, que es caer y errar el planeta continuamente.',
  },
  {
    id: 'fis-150', tema: 'gravitacion', dificultad: 4,
    enunciado: '¿Por qué se producen las mareas en los océanos?',
    opciones: [
      'Por la atracción gravitatoria de la Luna y el Sol, que tira con distinta intensidad de las distintas partes de la Tierra',
      'Por la rotación de la Tierra únicamente',
      'Por los vientos que soplan sobre el mar',
      'Por el calentamiento del agua durante el día',
    ],
    correcta: 0,
    explicacion: 'La cara de la Tierra más cercana a la Luna es atraída con más fuerza que el centro, y el centro más que la cara opuesta. Esa diferencia deforma la masa de agua y genera dos abultamientos, por eso hay dos mareas altas al día.',
  },
];
