/**
 * geografia.js — Banco de geografía.
 *
 * Las pruebas de ingreso no preguntan geografía como una lista de capitales:
 * preguntan por relaciones. El EXANI-II la evalúa dentro de Ciencias Sociales
 * (geografía física, humana, económica y política) y el Saber 11 la organiza en
 * el componente "espacio, territorio, ambiente y población" con tres
 * competencias: interpretar (leer un mapa o un dato), argumentar (explicar por
 * qué pasa algo) y proponer (anticipar consecuencias).
 *
 * Por eso aquí hay tres tipos de pregunta: definición y localización, lectura
 * de datos, y causa-consecuencia. Las opciones se barajan al presentarlas.
 */

export const GEOGRAFIA = [
  // ----- La Tierra y su representación -----
  {
    id: 'geo-001', tema: 'cartografia', dificultad: 1,
    enunciado: '¿Qué mide la latitud de un lugar?',
    opciones: [
      'La distancia angular hacia el norte o el sur del ecuador',
      'La distancia angular al este o al oeste del meridiano de Greenwich',
      'La altura del lugar sobre el nivel del mar',
      'La distancia en kilómetros hasta el polo más cercano',
    ],
    correcta: 0,
    explicacion: 'La latitud se mide desde el ecuador (0°) hacia los polos (90° N o 90° S). La distancia al meridiano de Greenwich es la longitud.',
    pista: 'Latitud: paralelos. Longitud: meridianos.',
  },
  {
    id: 'geo-002', tema: 'cartografia', dificultad: 1,
    enunciado: 'Un punto situado en 20° S, 70° O se encuentra en los hemisferios:',
    opciones: ['Sur y occidental', 'Norte y oriental', 'Sur y oriental', 'Norte y occidental'],
    correcta: 0,
    explicacion: 'La S indica latitud sur y la O (W en inglés) indica longitud oeste, es decir, el hemisferio occidental. Esas coordenadas caen en el norte de Chile.',
  },
  {
    id: 'geo-003', tema: 'cartografia', dificultad: 2,
    enunciado: 'En un mapa a escala 1 : 250 000, dos ciudades están separadas 8 cm. ¿Cuál es la distancia real?',
    opciones: ['20 km', '2 km', '200 km', '31,25 km'],
    correcta: 0,
    explicacion: '8 cm × 250 000 = 2 000 000 cm. Como 100 000 cm son 1 km, la distancia real es 20 km.',
  },
  {
    id: 'geo-004', tema: 'cartografia', dificultad: 2,
    enunciado: '¿Cuál de estos mapas muestra el terreno con más detalle?',
    opciones: ['Uno a escala 1 : 5 000', 'Uno a escala 1 : 500 000', 'Uno a escala 1 : 1 000 000', 'Todos muestran el mismo detalle'],
    correcta: 0,
    explicacion: 'Cuanto menor es el denominador, menos se reduce la realidad y más detalle cabe. Un mapa 1 : 5 000 es de escala grande; uno 1 : 1 000 000, de escala pequeña.',
    pista: 'Escala grande, territorio pequeño y mucho detalle.',
  },
  {
    id: 'geo-005', tema: 'cartografia', dificultad: 2,
    enunciado: '¿Cuál es la principal deformación de la proyección de Mercator?',
    opciones: [
      'Exagera el tamaño de los territorios cercanos a los polos',
      'Deforma los ángulos y por eso no sirve para navegar',
      'Reduce el tamaño de los territorios cercanos a los polos',
      'Representa la Tierra como un cono y corta los océanos',
    ],
    correcta: 0,
    explicacion: 'Mercator conserva los ángulos, lo que la hizo útil para la navegación, pero al estirar los paralelos hacia los polos agranda las superficies: por eso Groenlandia parece del tamaño de África cuando en realidad es unas catorce veces menor.',
  },
  {
    id: 'geo-006', tema: 'cartografia', dificultad: 2,
    enunciado: 'En un mapa topográfico, ¿qué indica que las curvas de nivel estén muy juntas?',
    opciones: [
      'Que la pendiente es muy fuerte',
      'Que el terreno es plano',
      'Que hay una depresión bajo el nivel del mar',
      'Que la escala del mapa es pequeña',
    ],
    correcta: 0,
    explicacion: 'Cada curva une puntos de la misma altitud. Si dos curvas consecutivas están muy cerca, se sube mucho en poca distancia horizontal: la pendiente es fuerte.',
  },
  {
    id: 'geo-007', tema: 'cartografia', dificultad: 1,
    enunciado: 'El meridiano que se toma como referencia (0°) para medir la longitud es el:',
    opciones: ['Meridiano de Greenwich', 'Ecuador', 'Trópico de Cáncer', 'Meridiano de Panamá'],
    correcta: 0,
    explicacion: 'El meridiano de Greenwich divide la Tierra en hemisferio oriental y occidental. El ecuador es el paralelo de 0° y sirve para la latitud.',
  },
  {
    id: 'geo-008', tema: 'cartografia', dificultad: 3,
    enunciado: '¿Cuáles son los valores máximos que pueden tomar la latitud y la longitud?',
    opciones: ['Latitud 90° y longitud 180°', 'Latitud 180° y longitud 90°', 'Ambas 360°', 'Ambas 180°'],
    correcta: 0,
    explicacion: 'La latitud va de 0° en el ecuador a 90° en cada polo. La longitud va de 0° en Greenwich a 180° en cada sentido, porque da media vuelta al planeta hacia el este y media hacia el oeste.',
  },
  {
    id: 'geo-009', tema: 'cartografia', dificultad: 2,
    enunciado: '¿Para qué sirve principalmente un Sistema de Información Geográfica (SIG)?',
    opciones: [
      'Para superponer y analizar capas de datos asociados a un territorio',
      'Para medir la altura de las montañas con láser desde el suelo',
      'Para dibujar a mano mapas a escala',
      'Para fotografiar la superficie terrestre desde un satélite',
    ],
    correcta: 0,
    explicacion: 'Un SIG cruza capas —relieve, ríos, vías, población, riesgo— sobre el mismo espacio para responder preguntas: qué barrios quedarían inundados, dónde conviene un hospital. Fotografiar desde un satélite es teledetección, que alimenta al SIG pero no es lo mismo.',
  },

  // ----- La Tierra en el sistema solar -----
  {
    id: 'geo-010', tema: 'tierra-universo', dificultad: 1,
    enunciado: '¿Qué consecuencia tiene el movimiento de rotación de la Tierra?',
    opciones: [
      'La sucesión del día y la noche',
      'La sucesión de las estaciones del año',
      'Las fases de la Luna',
      'Las mareas vivas y muertas',
    ],
    correcta: 0,
    explicacion: 'La rotación es el giro sobre su propio eje, dura unas 24 horas y produce el día y la noche. Las estaciones dependen de la traslación combinada con la inclinación del eje.',
  },
  {
    id: 'geo-011', tema: 'tierra-universo', dificultad: 2,
    enunciado: '¿Por qué existen las estaciones del año?',
    opciones: [
      'Porque el eje de la Tierra está inclinado unos 23,5° mientras gira alrededor del Sol',
      'Porque la Tierra se acerca y se aleja del Sol en su órbita',
      'Porque la velocidad de rotación cambia a lo largo del año',
      'Porque la Luna tapa parte de la radiación solar en ciertos meses',
    ],
    correcta: 0,
    explicacion: 'La inclinación hace que un hemisferio reciba los rayos más perpendiculares durante unos meses y más inclinados durante otros. La distancia al Sol apenas varía, y de hecho la Tierra está más cerca del Sol en enero, cuando es invierno en el hemisferio norte.',
    pista: 'Si fuera la distancia, las dos mitades del planeta tendrían verano a la vez.',
  },
  {
    id: 'geo-012', tema: 'tierra-universo', dificultad: 2,
    enunciado: '¿Cuántos husos horarios hay y cuántos grados de longitud abarca cada uno?',
    opciones: ['24 husos de 15° cada uno', '12 husos de 30° cada uno', '24 husos de 30° cada uno', '360 husos de 1° cada uno'],
    correcta: 0,
    explicacion: 'La Tierra da una vuelta de 360° en 24 horas, así que gira 15° cada hora. De ahí salen 24 husos de 15°.',
  },
  {
    id: 'geo-013', tema: 'tierra-universo', dificultad: 3,
    enunciado: 'Si en una ciudad con huso horario UTC−5 son las 10:00, ¿qué hora es en otra ciudad con huso UTC+2?',
    opciones: ['17:00', '05:00', '15:00', '12:00'],
    correcta: 0,
    explicacion: 'Entre UTC−5 y UTC+2 hay 7 horas de diferencia hacia el este, así que se suman: 10:00 + 7 = 17:00. Hacia el este el reloj va adelantado.',
  },
  {
    id: 'geo-014', tema: 'tierra-universo', dificultad: 2,
    enunciado: 'Durante el solsticio de junio, el Sol cae perpendicular sobre el trópico de Cáncer. Eso significa que:',
    opciones: [
      'Empieza el verano en el hemisferio norte y el invierno en el sur',
      'Empieza el verano en los dos hemisferios a la vez',
      'El día y la noche duran lo mismo en todo el planeta',
      'Empieza el invierno en el hemisferio norte',
    ],
    correcta: 0,
    explicacion: 'El trópico de Cáncer está en el hemisferio norte: cuando el Sol cae vertical allí, ese hemisferio recibe la radiación más directa y empieza su verano, mientras el sur entra en invierno.',
  },
  {
    id: 'geo-015', tema: 'tierra-universo', dificultad: 2,
    enunciado: '¿Qué ocurre en los equinoccios de marzo y septiembre?',
    opciones: [
      'El día y la noche duran prácticamente lo mismo en todo el planeta',
      'El día dura más que la noche en los dos hemisferios',
      'La Tierra alcanza su punto más cercano al Sol',
      'El Sol no se pone en el círculo polar ártico',
    ],
    correcta: 0,
    explicacion: 'En los equinoccios el Sol cae perpendicular sobre el ecuador y la línea que separa el día de la noche pasa por los dos polos, de modo que reparte doce horas de luz a cada latitud.',
  },
  {
    id: 'geo-016', tema: 'tierra-universo', dificultad: 2,
    enunciado: 'La zona intertropical o cálida del planeta está comprendida entre:',
    opciones: [
      'El trópico de Cáncer y el trópico de Capricornio',
      'Los dos círculos polares',
      'El ecuador y el trópico de Cáncer',
      'El círculo polar ártico y el trópico de Cáncer',
    ],
    correcta: 0,
    explicacion: 'Entre los dos trópicos (23,5° N y 23,5° S) el Sol llega a caer perpendicular alguna vez al año, y por eso es la franja que más energía recibe.',
  },
  {
    id: 'geo-017', tema: 'tierra-universo', dificultad: 3,
    enunciado: '¿Qué ocurre al cruzar la línea internacional de cambio de fecha viajando hacia el oeste?',
    opciones: [
      'Se adelanta un día en el calendario',
      'Se atrasa un día en el calendario',
      'Se cambia de hemisferio norte a sur',
      'No cambia nada: solo se ajusta el reloj una hora',
    ],
    correcta: 0,
    explicacion: 'La línea sigue aproximadamente el meridiano 180°. Al cruzarla hacia el oeste se suma un día, y al cruzarla hacia el este se resta: así el calendario cuadra después de dar la vuelta al mundo.',
  },

  // ----- Tectónica, sismos y volcanes -----
  {
    id: 'geo-018', tema: 'geodinamica-interna', dificultad: 1,
    enunciado: '¿Cuáles son las capas internas de la Tierra, de fuera hacia dentro?',
    opciones: ['Corteza, manto y núcleo', 'Manto, corteza y núcleo', 'Núcleo, corteza y manto', 'Corteza, núcleo y manto'],
    correcta: 0,
    explicacion: 'La corteza es la capa delgada donde vivimos, el manto es la más voluminosa y sus movimientos arrastran las placas, y el núcleo, de hierro y níquel, genera el campo magnético.',
  },
  {
    id: 'geo-019', tema: 'geodinamica-interna', dificultad: 2,
    enunciado: '¿Qué explica la teoría de la tectónica de placas?',
    opciones: [
      'Por qué hay sismos, volcanes y cordilleras justo donde están',
      'Por qué cambian las estaciones del año',
      'Por qué la atmósfera retiene el calor del Sol',
      'Por qué los ríos erosionan sus márgenes',
    ],
    correcta: 0,
    explicacion: 'La corteza está dividida en placas que se mueven unos centímetros al año. Casi toda la actividad sísmica y volcánica y la formación de grandes cordilleras ocurre en sus bordes, no en el interior de las placas.',
  },
  {
    id: 'geo-020', tema: 'geodinamica-interna', dificultad: 2,
    enunciado: '¿Qué sucede donde una placa oceánica choca contra una continental?',
    opciones: [
      'La oceánica se hunde bajo la continental y se forman una fosa marina y una cordillera con volcanes',
      'Las dos se separan y aparece una dorsal en medio del océano',
      'Las dos se deslizan de lado sin crear ni destruir corteza',
      'La continental se hunde bajo la oceánica y desaparece el continente',
    ],
    correcta: 0,
    explicacion: 'Es un borde convergente con subducción: la placa oceánica, más densa, se hunde. Eso abre una fosa frente a la costa y levanta una cordillera volcánica detrás, como ocurre en toda la costa del Pacífico americano.',
  },
  {
    id: 'geo-021', tema: 'geodinamica-interna', dificultad: 1,
    enunciado: 'El llamado Cinturón de Fuego del Pacífico se caracteriza por:',
    opciones: [
      'Concentrar la mayor parte de los volcanes activos y los sismos del planeta',
      'Ser la región más cálida y seca de la Tierra',
      'Reunir las principales reservas de petróleo del mundo',
      'Marcar el recorrido de las corrientes marinas cálidas',
    ],
    correcta: 0,
    explicacion: 'Rodea el océano Pacífico siguiendo los bordes de placas convergentes, desde Chile hasta Alaska y de Japón a Nueva Zelanda. Allí se produce alrededor del 80 % de los sismos importantes.',
  },
  {
    id: 'geo-022', tema: 'geodinamica-interna', dificultad: 2,
    enunciado: '¿En qué se diferencian la escala de magnitud (Richter) y la escala de Mercalli?',
    opciones: [
      'La primera mide la energía liberada por el sismo y la segunda los daños percibidos en un lugar',
      'La primera mide los daños y la segunda la energía liberada',
      'La primera se usa para volcanes y la segunda para sismos',
      'Son dos nombres de la misma escala',
    ],
    correcta: 0,
    explicacion: 'Un mismo sismo tiene una sola magnitud, pero distintas intensidades de Mercalli según la distancia, el tipo de suelo y cómo estén construidos los edificios de cada sitio.',
  },
  {
    id: 'geo-023', tema: 'geodinamica-interna', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre el hipocentro y el epicentro de un sismo?',
    opciones: [
      'El hipocentro es el punto interior donde se origina y el epicentro está en la superficie, justo encima',
      'El hipocentro está en la superficie y el epicentro en el interior',
      'El hipocentro es donde más daños hay y el epicentro donde menos',
      'Son el mismo punto medido con instrumentos distintos',
    ],
    correcta: 0,
    explicacion: 'El foco o hipocentro puede estar a decenas o cientos de kilómetros de profundidad; el epicentro es su proyección vertical en la superficie y suele ser la zona más afectada.',
  },
  {
    id: 'geo-024', tema: 'geodinamica-interna', dificultad: 3,
    enunciado: '¿Qué ocurre en una dorsal oceánica?',
    opciones: [
      'Dos placas se separan y asciende magma que crea corteza nueva',
      'Dos placas chocan y una se hunde bajo la otra',
      'El fondo marino se hunde y forma una fosa profunda',
      'Se acumulan los sedimentos que traen los grandes ríos',
    ],
    correcta: 0,
    explicacion: 'Las dorsales son bordes divergentes: la corteza se fabrica ahí y se destruye en las zonas de subducción, de modo que la superficie del planeta se mantiene constante.',
  },
  {
    id: 'geo-025', tema: 'geodinamica-interna', dificultad: 2,
    enunciado: '¿Cómo se formó la cordillera de los Andes?',
    opciones: [
      'Por la subducción de la placa de Nazca bajo la placa sudamericana',
      'Por la acumulación de sedimentos del río Amazonas',
      'Por la separación de África y América del Sur',
      'Por la erosión del viento sobre una antigua meseta',
    ],
    correcta: 0,
    explicacion: 'La placa oceánica de Nazca se hunde bajo el borde occidental de Sudamérica. Ese empuje pliega y levanta la corteza continental y alimenta el volcanismo andino.',
  },
  {
    id: 'geo-026', tema: 'geodinamica-interna', dificultad: 3,
    enunciado: '¿Por qué países tan distantes como Chile y Japón comparten sismos frecuentes y volcanes activos?',
    opciones: [
      'Porque los dos se asientan sobre bordes de placas convergentes del Pacífico',
      'Porque los dos están a la misma distancia del ecuador',
      'Porque los dos son países alargados y con costa',
      'Porque en los dos hay cordilleras muy jóvenes formadas por erosión',
    ],
    correcta: 0,
    explicacion: 'Lo que comparten no es la latitud ni la forma, sino la posición tectónica: ambos están sobre zonas de subducción del Cinturón de Fuego.',
  },

  // ----- Relieve y geodinámica externa -----
  {
    id: 'geo-027', tema: 'relieve', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre meteorización y erosión?',
    opciones: [
      'La meteorización rompe y altera la roca en su sitio; la erosión arranca y transporta los materiales',
      'La meteorización transporta los materiales y la erosión los deposita',
      'La meteorización solo ocurre en climas fríos y la erosión en climas cálidos',
      'Son sinónimos usados por distintas escuelas',
    ],
    correcta: 0,
    explicacion: 'Primero la roca se fragmenta o se altera químicamente donde está, y después el agua, el hielo o el viento se llevan los trozos. Sin transporte no hay erosión.',
  },
  {
    id: 'geo-028', tema: 'relieve', dificultad: 2,
    enunciado: 'Un valle con perfil en forma de U fue excavado principalmente por:',
    opciones: ['Un glaciar', 'Un río', 'El viento', 'El oleaje del mar'],
    correcta: 0,
    explicacion: 'El hielo, ancho y pesado, desgasta también las paredes y deja un fondo plano. Los ríos, que erosionan sobre todo hacia abajo, dejan valles en forma de V.',
  },
  {
    id: 'geo-029', tema: 'relieve', dificultad: 2,
    enunciado: '¿Cómo se forma un delta?',
    opciones: [
      'Por la acumulación de sedimentos que el río deposita al perder velocidad en su desembocadura',
      'Por el hundimiento del terreno en la costa',
      'Por la erosión del oleaje sobre un acantilado',
      'Por la erupción de volcanes submarinos cerca de la costa',
    ],
    correcta: 0,
    explicacion: 'Al llegar al mar el río pierde fuerza y suelta la carga que traía. Si el oleaje y las corrientes no la retiran, los sedimentos se acumulan y el terreno avanza sobre el mar.',
  },
  {
    id: 'geo-030', tema: 'relieve', dificultad: 2,
    enunciado: '¿En qué tipo de rocas se encuentran normalmente los fósiles y por qué?',
    opciones: [
      'En las sedimentarias, porque se forman por acumulación de capas que sepultan restos sin destruirlos',
      'En las volcánicas, porque la lava conserva las huellas de los seres vivos',
      'En las metamórficas, porque el calor y la presión fijan los restos',
      'En cualquiera por igual, porque el tipo de roca no influye',
    ],
    correcta: 0,
    explicacion: 'Las rocas ígneas se forman a temperaturas que destruyen cualquier resto y el metamorfismo suele borrarlos. Solo la sedimentación, capa sobre capa, permite que se conserven.',
  },
  {
    id: 'geo-031', tema: 'relieve', dificultad: 1,
    enunciado: 'Una meseta o altiplano es:',
    opciones: [
      'Una superficie relativamente plana situada a gran altitud',
      'Una franja estrecha de tierra entre dos mares',
      'Una depresión rodeada de montañas',
      'Una cadena de montañas jóvenes y plegadas',
    ],
    correcta: 0,
    explicacion: 'El altiplano boliviano y el altiplano mexicano son ejemplos: llanuras elevadas, con clima fresco pese a estar en latitudes cálidas.',
  },
  {
    id: 'geo-032', tema: 'relieve', dificultad: 2,
    enunciado: 'En los desiertos, el principal agente que modela el relieve y forma las dunas es:',
    opciones: ['El viento', 'Los glaciares', 'Los ríos permanentes', 'Las mareas'],
    correcta: 0,
    explicacion: 'Con poca vegetación que sujete el suelo, el viento arrastra la arena y la acumula en dunas. Se le llama modelado eólico.',
  },
  {
    id: 'geo-033', tema: 'relieve', dificultad: 3,
    enunciado: '¿Por qué las llanuras y los valles fluviales concentran históricamente más población que las zonas montañosas?',
    opciones: [
      'Porque tienen suelos fértiles, agua disponible y permiten construir vías y cultivar con facilidad',
      'Porque reciben más horas de luz solar al año',
      'Porque están libres de riesgos naturales',
      'Porque en ellas el clima siempre es más frío y sano',
    ],
    correcta: 0,
    explicacion: 'El relieve condiciona el poblamiento por la agricultura y el transporte. De hecho los valles fluviales inundables no están libres de riesgo: son justamente donde más inundaciones hay.',
  },
  {
    id: 'geo-034', tema: 'relieve', dificultad: 2,
    enunciado: 'En un perfil de suelo, el horizonte más rico en materia orgánica es:',
    opciones: [
      'El horizonte A, el más superficial después de la capa de restos vegetales',
      'El horizonte C, formado por la roca madre fragmentada',
      'El horizonte más profundo, donde llega el agua subterránea',
      'Todos tienen la misma cantidad de materia orgánica',
    ],
    correcta: 0,
    explicacion: 'La materia orgánica proviene de la vegetación que se descompone en la superficie, así que se concentra arriba. Por eso la erosión de los primeros centímetros de suelo es tan grave para la agricultura.',
  },

  // ----- Aguas continentales y oceánicas -----
  {
    id: 'geo-035', tema: 'hidrografia', dificultad: 2,
    enunciado: 'Del total de agua del planeta, el agua dulce representa alrededor del 2,5 %. ¿Dónde está la mayor parte de esa agua dulce?',
    opciones: [
      'En los glaciares y los casquetes polares',
      'En los ríos y los lagos',
      'En la atmósfera en forma de vapor',
      'En los seres vivos',
    ],
    correcta: 0,
    explicacion: 'Casi el 70 % del agua dulce está congelada y otra buena parte es subterránea. El agua de ríos y lagos, que es de la que vivimos, es una fracción mínima del total.',
  },
  {
    id: 'geo-036', tema: 'hidrografia', dificultad: 2,
    enunciado: '¿Qué es una cuenca hidrográfica?',
    opciones: [
      'El territorio cuyas aguas desembocan todas en un mismo río, lago o mar',
      'El cauce por donde corre un río durante la temporada de lluvias',
      'La zona donde un río desemboca en el mar',
      'El conjunto de aguas subterráneas de una región',
    ],
    correcta: 0,
    explicacion: 'Las divisorias de agua, normalmente crestas montañosas, separan una cuenca de otra. Es la unidad con la que se gestiona el agua, porque lo que se hace aguas arriba afecta a todos los que están aguas abajo.',
  },
  {
    id: 'geo-037', tema: 'hidrografia', dificultad: 1,
    enunciado: 'En el ciclo del agua, el paso del agua líquida a vapor por acción del calor solar se llama:',
    opciones: ['Evaporación', 'Condensación', 'Precipitación', 'Infiltración'],
    correcta: 0,
    explicacion: 'El vapor asciende, se enfría y se condensa formando nubes; después cae como precipitación y una parte se infiltra en el suelo.',
  },
  {
    id: 'geo-038', tema: 'hidrografia', dificultad: 1,
    enunciado: '¿Cuál es el río más caudaloso del mundo?',
    opciones: ['El Amazonas', 'El Nilo', 'El Misisipi', 'El Danubio'],
    correcta: 0,
    explicacion: 'El Amazonas descarga en el Atlántico más agua que los siguientes ríos más caudalosos juntos, porque recoge las lluvias de una cuenca enorme y muy húmeda.',
  },
  {
    id: 'geo-039', tema: 'hidrografia', dificultad: 3,
    enunciado: '¿Por qué el noroeste de Europa tiene inviernos más suaves que otras regiones de la misma latitud?',
    opciones: [
      'Por la corriente marina cálida del Golfo, que transporta calor desde el trópico',
      'Porque está más cerca del Sol en invierno',
      'Porque su relieve es montañoso y retiene el calor',
      'Porque recibe menos precipitaciones y por eso hace menos frío',
    ],
    correcta: 0,
    explicacion: 'Las corrientes marinas son un factor del clima: la del Golfo templa las costas europeas, mientras que corrientes frías como la de Humboldt enfrían y resecan la costa del Perú y el norte de Chile.',
  },
  {
    id: 'geo-040', tema: 'hidrografia', dificultad: 3,
    enunciado: '¿Qué es el fenómeno de El Niño?',
    opciones: [
      'Un calentamiento anómalo de las aguas del Pacífico ecuatorial que altera las lluvias en varios continentes',
      'Un huracán que se repite cada año en el Caribe',
      'El deshielo estacional de los glaciares andinos',
      'Una corriente fría que enfría la costa de Chile en invierno',
    ],
    correcta: 0,
    explicacion: 'Al calentarse el Pacífico y debilitarse los vientos alisios cambia el patrón de lluvias: suele traer inundaciones a la costa de Perú y Ecuador y sequías en otras regiones. Su fase opuesta y fría es La Niña.',
  },
  {
    id: 'geo-041', tema: 'hidrografia', dificultad: 2,
    enunciado: 'Un acuífero es:',
    opciones: [
      'Una formación de roca permeable capaz de almacenar y ceder agua subterránea',
      'Un lago artificial construido tras una represa',
      'El conjunto de afluentes de un río principal',
      'Una tubería natural que lleva agua desde la montaña',
    ],
    correcta: 0,
    explicacion: 'El agua se infiltra y queda entre los poros y las grietas de la roca. Se extrae con pozos, y si se saca más rápido de lo que se recarga, el acuífero se agota.',
  },
  {
    id: 'geo-042', tema: 'hidrografia', dificultad: 1,
    enunciado: 'Un afluente es:',
    opciones: [
      'Un río que desemboca en otro río',
      'El tramo final de un río antes del mar',
      'El lugar donde nace un río',
      'Un brazo que se separa del río en el delta',
    ],
    correcta: 0,
    explicacion: 'El río principal más sus afluentes forman la red hidrográfica de la cuenca. El punto donde nace es el nacimiento y donde termina, la desembocadura.',
  },
  {
    id: 'geo-043', tema: 'hidrografia', dificultad: 3,
    enunciado: 'Si el 71 % de la superficie del planeta está cubierta de agua, ¿por qué se habla de escasez de agua?',
    opciones: [
      'Porque casi toda es salada y de la dulce la mayor parte está congelada o es subterránea profunda',
      'Porque el agua de los océanos se está evaporando por el calentamiento',
      'Porque la población mundial ha dejado de crecer y se reparte mal',
      'Porque el agua dulce no se renueva nunca',
    ],
    correcta: 0,
    explicacion: 'Lo escaso no es el agua, sino el agua dulce accesible y en buen estado, y además está repartida de forma muy desigual entre regiones y estaciones del año.',
  },

  // ----- Tiempo, clima y atmósfera -----
  {
    id: 'geo-044', tema: 'clima', dificultad: 1,
    enunciado: '¿Cuál es la diferencia entre tiempo atmosférico y clima?',
    opciones: [
      'El tiempo es el estado de la atmósfera en un momento dado; el clima es el promedio de esos estados durante décadas',
      'El tiempo se mide en el campo y el clima en las ciudades',
      'El tiempo se refiere a la temperatura y el clima a las lluvias',
      'Son lo mismo: el clima es el término técnico del tiempo',
    ],
    correcta: 0,
    explicacion: 'Por eso un día frío no desmiente el calentamiento global: lo que cambia es el promedio a largo plazo, no el dato de una tarde.',
  },
  {
    id: 'geo-045', tema: 'clima', dificultad: 2,
    enunciado: '¿Cuál de los siguientes es un FACTOR del clima y no un elemento del clima?',
    opciones: ['La altitud', 'La temperatura', 'La precipitación', 'La humedad'],
    correcta: 0,
    explicacion: 'Los elementos son lo que se mide (temperatura, precipitación, humedad, presión, viento). Los factores son las condiciones que los modifican: latitud, altitud, relieve, distancia al mar y corrientes marinas.',
    pista: 'Los elementos se miden; los factores explican.',
  },
  {
    id: 'geo-046', tema: 'clima', dificultad: 1,
    enunciado: 'Al ascender por una montaña, la temperatura del aire normalmente:',
    opciones: [
      'Disminuye unos grados por cada mil metros de altitud',
      'Aumenta, porque se está más cerca del Sol',
      'Se mantiene igual mientras no cambie la latitud',
      'Aumenta de día y disminuye de noche en la misma proporción',
    ],
    correcta: 0,
    explicacion: 'El aire se calienta sobre todo desde el suelo y se enfría al ascender y expandirse: alrededor de 6 °C por cada 1 000 m. Estar más cerca del Sol es irrelevante a esa escala.',
  },
  {
    id: 'geo-047', tema: 'clima', dificultad: 2,
    enunciado: '¿En qué capa de la atmósfera ocurren las nubes, las lluvias y los vientos?',
    opciones: ['La troposfera', 'La estratosfera', 'La mesosfera', 'La termosfera'],
    correcta: 0,
    explicacion: 'La troposfera es la capa en contacto con la superficie y concentra casi todo el vapor de agua; por eso allí pasa el tiempo atmosférico.',
  },
  {
    id: 'geo-048', tema: 'clima', dificultad: 2,
    enunciado: 'La capa de ozono se encuentra en la estratosfera y su función es:',
    opciones: [
      'Filtrar buena parte de la radiación ultravioleta del Sol',
      'Retener el calor que emite la superficie terrestre',
      'Producir el oxígeno que respiramos',
      'Reflejar las ondas de radio para las comunicaciones',
    ],
    correcta: 0,
    explicacion: 'Conviene no confundirla con el efecto invernadero: el ozono filtra radiación ultravioleta, mientras que el CO₂ y otros gases retienen calor. Son dos problemas ambientales distintos.',
  },
  {
    id: 'geo-049', tema: 'clima', dificultad: 2,
    enunciado: '¿Qué caracteriza al clima tropical húmedo o ecuatorial?',
    opciones: [
      'Temperaturas altas y constantes todo el año con lluvias abundantes',
      'Cuatro estaciones marcadas y lluvias en otoño',
      'Temperaturas bajas todo el año y escasas precipitaciones',
      'Veranos secos y calurosos con inviernos templados y lluviosos',
    ],
    correcta: 0,
    explicacion: 'Cerca del ecuador la radiación es alta y pareja todo el año, así que la diferencia entre meses es mínima: en vez de estaciones térmicas hay temporadas secas y lluviosas. La última opción describe el clima mediterráneo.',
  },
  {
    id: 'geo-050', tema: 'clima', dificultad: 3,
    enunciado: 'Quito está prácticamente sobre la línea ecuatorial y aun así tiene un clima fresco durante todo el año. ¿Por qué?',
    opciones: [
      'Porque está a unos 2 800 metros de altitud',
      'Porque la corriente de Humboldt enfría la ciudad',
      'Porque recibe menos horas de luz que otras ciudades tropicales',
      'Porque está muy lejos del mar',
    ],
    correcta: 0,
    explicacion: 'La latitud fija cuánta energía llega, pero la altitud corrige la temperatura: por eso hay ciudades tropicales de clima fresco, como Quito, Bogotá o La Paz.',
  },
  {
    id: 'geo-051', tema: 'clima', dificultad: 2,
    enunciado: 'Los huracanes se forman sobre:',
    opciones: [
      'Océanos tropicales cuyas aguas superficiales superan unos 26 °C',
      'Zonas continentales muy secas y calientes',
      'Los mares polares, donde el aire es más denso',
      'Las cordilleras costeras durante el invierno',
    ],
    correcta: 0,
    explicacion: 'El agua cálida evapora y libera calor al condensarse, que es la energía que alimenta la tormenta. Por eso los huracanes se debilitan al entrar en tierra o al pasar sobre agua fría.',
  },
  {
    id: 'geo-052', tema: 'clima', dificultad: 3,
    enunciado: 'Una cordillera costera recibe vientos húmedos del océano. ¿Qué ocurre a cada lado?',
    opciones: [
      'La ladera que da al mar recibe lluvias abundantes y la ladera opuesta queda seca',
      'Las dos laderas reciben la misma cantidad de lluvia',
      'La ladera que da al mar queda seca y la opuesta recibe las lluvias',
      'No llueve en ninguna de las dos porque el aire desciende',
    ],
    correcta: 0,
    explicacion: 'El aire húmedo asciende por el barlovento, se enfría y descarga su humedad; al bajar por el sotavento se calienta y se seca. Ese efecto de sombra de lluvia explica desiertos como el de Atacama o la Patagonia argentina.',
  },
  {
    id: 'geo-053', tema: 'clima', dificultad: 2,
    enunciado: 'En un mapa del clima, una isoyeta es una línea que une puntos con:',
    opciones: ['La misma precipitación', 'La misma temperatura', 'La misma presión atmosférica', 'La misma altitud'],
    correcta: 0,
    explicacion: 'Isoyetas para la lluvia, isotermas para la temperatura, isobaras para la presión y curvas de nivel para la altitud.',
  },

  // ----- Regiones naturales y biodiversidad -----
  {
    id: 'geo-054', tema: 'biogeografia', dificultad: 1,
    enunciado: 'Un bioma es:',
    opciones: [
      'Una gran región con clima, vegetación y fauna característicos',
      'El conjunto de especies en peligro de extinción de un país',
      'Una zona protegida por ley para conservar especies',
      'La capa del suelo donde crecen las raíces',
    ],
    correcta: 0,
    explicacion: 'Selva tropical, sabana, desierto, bosque templado, taiga y tundra son biomas. Se reconocen por el tipo de vegetación dominante, que a su vez depende del clima.',
  },
  {
    id: 'geo-055', tema: 'biogeografia', dificultad: 2,
    enunciado: '¿Qué caracteriza a la tundra?',
    opciones: [
      'Suelo helado buena parte del año y vegetación de musgos, líquenes y arbustos bajos',
      'Bosques densos de coníferas y precipitaciones abundantes',
      'Pastizales con árboles dispersos y una estación seca marcada',
      'Lluvias todo el año y la mayor diversidad de especies del planeta',
    ],
    correcta: 0,
    explicacion: 'Está en las latitudes altas, más allá de la taiga. El permafrost impide que las raíces profundicen, así que no crecen árboles.',
  },
  {
    id: 'geo-056', tema: 'biogeografia', dificultad: 1,
    enunciado: '¿Cuál es el bioma terrestre con mayor biodiversidad?',
    opciones: ['La selva tropical húmeda', 'La tundra', 'El desierto cálido', 'La estepa'],
    correcta: 0,
    explicacion: 'Calor constante, lluvia abundante y luz todo el año permiten muchos estratos de vegetación y, con ellos, una enorme cantidad de nichos para las especies.',
  },
  {
    id: 'geo-057', tema: 'biogeografia', dificultad: 2,
    enunciado: 'La sabana se caracteriza por:',
    opciones: [
      'Pastizales con árboles dispersos y una estación seca bien marcada',
      'Bosques cerrados de árboles de hoja ancha que se caen en invierno',
      'Ausencia total de vegetación por falta de agua',
      'Musgos y líquenes sobre suelo permanentemente helado',
    ],
    correcta: 0,
    explicacion: 'Es típica de las zonas tropicales con lluvias concentradas en pocos meses, como los llanos de Colombia y Venezuela o el cerrado brasileño.',
  },
  {
    id: 'geo-058', tema: 'biogeografia', dificultad: 3,
    enunciado: '¿Por qué los páramos andinos se consideran ecosistemas estratégicos?',
    opciones: [
      'Porque regulan y almacenan el agua que abastece a ciudades enteras',
      'Porque son las zonas más productivas para la agricultura intensiva',
      'Porque concentran las mayores reservas minerales de la región',
      'Porque su vegetación produce la mayor parte del oxígeno del continente',
    ],
    correcta: 0,
    explicacion: 'Los suelos y las plantas del páramo, como los frailejones, retienen el agua de las lluvias y las neblinas y la liberan poco a poco. Ciudades como Bogotá o Quito dependen de ellos.',
  },
  {
    id: 'geo-059', tema: 'biogeografia', dificultad: 2,
    enunciado: 'Que un país sea considerado megadiverso significa que:',
    opciones: [
      'Concentra en su territorio un porcentaje muy alto de las especies del planeta',
      'Tiene la mayor superficie de áreas protegidas del mundo',
      'Posee todos los climas del planeta dentro de sus fronteras',
      'Ha firmado todos los tratados internacionales de medio ambiente',
    ],
    correcta: 0,
    explicacion: 'Un puñado de países —entre ellos Brasil, Colombia, México, Perú y Ecuador— reúne la mayor parte de la biodiversidad mundial, gracias a su posición tropical y a la variedad de relieve y climas.',
  },
  {
    id: 'geo-060', tema: 'biogeografia', dificultad: 2,
    enunciado: '¿Cuál es el factor que más determina qué vegetación natural crece en una región?',
    opciones: ['El clima', 'La densidad de población', 'La distancia a la capital del país', 'El tipo de gobierno'],
    correcta: 0,
    explicacion: 'Temperatura y precipitación deciden qué plantas pueden sobrevivir; el suelo y el relieve matizan el resultado. Por eso el mapa de biomas se parece tanto al mapa de climas.',
  },
  {
    id: 'geo-061', tema: 'biogeografia', dificultad: 3,
    enunciado: 'Al subir por una montaña tropical, la vegetación y los cultivos cambian por pisos. ¿Por qué?',
    opciones: [
      'Porque la temperatura baja con la altitud y reproduce condiciones parecidas a las de latitudes mayores',
      'Porque el suelo es más fértil cuanto más alto se sube',
      'Porque en altura llueve siempre menos que al pie de la montaña',
      'Porque la presión atmosférica impide que crezcan plantas con flor',
    ],
    correcta: 0,
    explicacion: 'Son los pisos térmicos: cálido, templado, frío y páramo. Subir mil metros equivale, en temperatura, a alejarse bastante del ecuador, y por eso el café, la papa o el maíz ocupan alturas distintas.',
  },

  // ----- Geografía de la población -----
  {
    id: 'geo-062', tema: 'poblacion', dificultad: 1,
    enunciado: 'Un país tiene 12 millones de habitantes y una superficie de 300 000 km². ¿Cuál es su densidad de población?',
    opciones: ['40 hab/km²', '25 hab/km²', '400 hab/km²', '36 hab/km²'],
    correcta: 0,
    explicacion: 'La densidad es habitantes entre superficie: 12 000 000 ÷ 300 000 = 40 habitantes por kilómetro cuadrado. Es un promedio y esconde grandes diferencias internas.',
  },
  {
    id: 'geo-063', tema: 'poblacion', dificultad: 2,
    enunciado: 'El crecimiento natural o vegetativo de una población se obtiene:',
    opciones: [
      'Restando la mortalidad a la natalidad',
      'Sumando la natalidad y la inmigración',
      'Restando los emigrantes a los inmigrantes',
      'Dividiendo la población entre la superficie del país',
    ],
    correcta: 0,
    explicacion: 'El crecimiento natural solo mira nacimientos y defunciones. Si se añaden las migraciones se obtiene el crecimiento real o total.',
  },
  {
    id: 'geo-064', tema: 'poblacion', dificultad: 2,
    enunciado: '¿En qué consiste la transición demográfica?',
    opciones: [
      'En el paso de natalidad y mortalidad altas a natalidad y mortalidad bajas',
      'En el traslado masivo de población del campo a la ciudad',
      'En el envejecimiento inevitable de todas las poblaciones del mundo',
      'En el cambio de una población rural a una industrial',
    ],
    correcta: 0,
    explicacion: 'Primero cae la mortalidad, por salud y alimentación, y la población crece deprisa; después cae la natalidad y el crecimiento se frena. El éxodo rural es otro proceso distinto.',
  },
  {
    id: 'geo-065', tema: 'poblacion', dificultad: 2,
    enunciado: 'Una pirámide de población con base muy ancha y cima estrecha indica:',
    opciones: [
      'Una población joven, con natalidad alta y esperanza de vida más corta',
      'Una población envejecida con natalidad baja',
      'Un país que recibe muchos inmigrantes adultos',
      'Un país donde emigran sobre todo los jóvenes',
    ],
    correcta: 0,
    explicacion: 'La base representa a los más pequeños: si es ancha, nacen muchos niños. La cima estrecha indica que pocos llegan a edades avanzadas.',
  },
  {
    id: 'geo-066', tema: 'poblacion', dificultad: 3,
    enunciado: 'Un país tiene una pirámide de población con la base más estrecha que el centro. ¿Qué consecuencia es previsible a largo plazo?',
    opciones: [
      'Habrá cada vez menos población activa para sostener a los jubilados',
      'Aumentará la demanda de escuelas primarias',
      'Crecerá rápidamente la población total',
      'Se reducirá la esperanza de vida de la población',
    ],
    correcta: 0,
    explicacion: 'Si nacen menos niños de los que hay en edad de trabajar, dentro de unas décadas la proporción de personas mayores crecerá y la de trabajadores bajará: eso presiona las pensiones y la sanidad.',
    pista: 'Lee la pirámide hacia el futuro: la base de hoy son los trabajadores de mañana.',
  },
  {
    id: 'geo-067', tema: 'poblacion', dificultad: 1,
    enunciado: 'El éxodo rural es el desplazamiento de población:',
    opciones: [
      'Del campo hacia las ciudades',
      'De las ciudades hacia el campo',
      'De un país pobre a uno rico',
      'De la costa hacia el interior del país',
    ],
    correcta: 0,
    explicacion: 'Es una migración interna: se busca trabajo, educación y servicios en la ciudad. En América Latina explica el crecimiento acelerado de las grandes urbes en el siglo XX.',
  },
  {
    id: 'geo-068', tema: 'poblacion', dificultad: 2,
    enunciado: 'Si en un año llegan a un país 80 000 inmigrantes y salen 95 000 emigrantes, su saldo migratorio es:',
    opciones: ['Negativo, de −15 000 personas', 'Positivo, de 15 000 personas', 'Negativo, de −175 000 personas', 'Nulo, porque las cifras se compensan'],
    correcta: 0,
    explicacion: 'Saldo migratorio = inmigrantes − emigrantes = 80 000 − 95 000 = −15 000. El país pierde población por migración.',
  },
  {
    id: 'geo-069', tema: 'poblacion', dificultad: 2,
    enunciado: '¿Qué indica la esperanza de vida al nacer?',
    opciones: [
      'Los años que en promedio viviría un recién nacido si se mantuvieran las condiciones actuales',
      'La edad máxima que alcanzan las personas en un país',
      'La edad promedio de la población en un momento dado',
      'Los años que faltan para que la población deje de crecer',
    ],
    correcta: 0,
    explicacion: 'Es un promedio estadístico y uno de los mejores resúmenes de las condiciones de salud, alimentación y saneamiento de un país. Por eso forma parte del IDH.',
  },
  {
    id: 'geo-070', tema: 'poblacion', dificultad: 3,
    enunciado: 'Un país de 5 millones de habitantes tiene una tasa de natalidad de 18 por cada 1 000 habitantes. ¿Cuántos nacimientos hubo ese año?',
    opciones: ['90 000', '9 000', '180 000', '900 000'],
    correcta: 0,
    explicacion: '5 000 000 ÷ 1 000 = 5 000 grupos de mil habitantes; 5 000 × 18 = 90 000 nacimientos.',
  },
  {
    id: 'geo-071', tema: 'poblacion', dificultad: 2,
    enunciado: 'La siguiente tabla muestra datos de dos países. ¿Qué se puede afirmar con seguridad?',
    codigo: [
      '                        País A      País B',
      'Natalidad (por mil)       32           9',
      'Mortalidad (por mil)      12           10',
      'Esperanza de vida         62          81',
    ].join('\n'),
    opciones: [
      'El país A crece de forma natural y el país B pierde población por crecimiento natural',
      'El país A tiene mejores condiciones de salud que el país B',
      'El país B recibe más inmigrantes que el país A',
      'El país A tiene más habitantes que el país B',
    ],
    correcta: 0,
    explicacion: 'Crecimiento natural de A: 32 − 12 = +20 por mil. El de B: 9 − 10 = −1 por mil, es decir, negativo. La tabla no dice nada sobre migraciones ni sobre el total de habitantes, y la esperanza de vida de B es mayor.',
    pista: 'Responde solo con lo que la tabla permite calcular.',
  },
  {
    id: 'geo-072', tema: 'poblacion', dificultad: 2,
    enunciado: 'América Latina es la región en desarrollo con mayor tasa de urbanización del mundo. Eso significa que:',
    opciones: [
      'La mayor parte de su población vive en ciudades',
      'Sus ciudades son las más grandes del planeta',
      'Su población rural crece más rápido que la urbana',
      'Tiene la mayor densidad de población del mundo',
    ],
    correcta: 0,
    explicacion: 'Alrededor de cuatro de cada cinco latinoamericanos viven en zonas urbanas. Urbanización se refiere a la proporción de población urbana, no al tamaño de las ciudades ni a la densidad.',
  },

  // ----- Geografía económica -----
  {
    id: 'geo-073', tema: 'economica', dificultad: 1,
    enunciado: 'La minería y la pesca pertenecen al sector:',
    opciones: ['Primario', 'Secundario', 'Terciario', 'Cuaternario'],
    correcta: 0,
    explicacion: 'El sector primario obtiene recursos de la naturaleza, el secundario los transforma (industria) y el terciario presta servicios (comercio, transporte, educación).',
  },
  {
    id: 'geo-074', tema: 'economica', dificultad: 1,
    enunciado: '¿Cuál de estos recursos NO es renovable?',
    opciones: ['El petróleo', 'La energía solar', 'La energía eólica', 'La biomasa'],
    correcta: 0,
    explicacion: 'El petróleo tardó millones de años en formarse y se consume mucho más rápido de lo que se genera. Los otros tres se reponen en escalas de tiempo humanas.',
  },
  {
    id: 'geo-075', tema: 'economica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre agricultura de subsistencia y agricultura comercial?',
    opciones: [
      'La de subsistencia produce sobre todo para consumo de la familia y la comercial para vender en el mercado',
      'La de subsistencia usa maquinaria y la comercial trabaja a mano',
      'La de subsistencia se practica en países ricos y la comercial en países pobres',
      'La de subsistencia solo produce cereales y la comercial solo frutas',
    ],
    correcta: 0,
    explicacion: 'La agricultura comercial suele estar más mecanizada, especializada en pocos productos y orientada a la exportación; la de subsistencia ocupa parcelas pequeñas con producción variada.',
  },
  {
    id: 'geo-076', tema: 'economica', dificultad: 2,
    enunciado: '¿Qué mide el PIB per cápita de un país?',
    opciones: [
      'El valor de lo producido en un año dividido entre el número de habitantes',
      'El ingreso que efectivamente recibe cada habitante',
      'La riqueza acumulada por el país a lo largo de su historia',
      'La diferencia entre lo que exporta y lo que importa',
    ],
    correcta: 0,
    explicacion: 'Es un promedio de producción por habitante. No dice nada sobre cómo se reparte: un país puede tener un PIB per cápita alto y a la vez mucha desigualdad.',
  },
  {
    id: 'geo-077', tema: 'economica', dificultad: 2,
    enunciado: 'El Índice de Desarrollo Humano (IDH) combina tres dimensiones:',
    opciones: [
      'Salud, educación y nivel de vida',
      'Producción, exportaciones e inversión extranjera',
      'Población, superficie y densidad',
      'Empleo, inflación y deuda pública',
    ],
    correcta: 0,
    explicacion: 'Se mide con la esperanza de vida, los años de escolaridad y el ingreso por habitante. Nació justamente para no juzgar el desarrollo solo por el dinero.',
  },
  {
    id: 'geo-078', tema: 'economica', dificultad: 3,
    enunciado: '¿Cómo se explica que un país con un PIB per cápita alto tenga un IDH apenas medio?',
    opciones: [
      'La riqueza está muy concentrada y no se traduce en salud y educación para la mayoría',
      'El IDH y el PIB miden exactamente lo mismo, así que debe ser un error de cálculo',
      'El país tiene pocos habitantes y eso reduce el IDH',
      'El país exporta más de lo que importa',
    ],
    correcta: 0,
    explicacion: 'Es el caso típico de las economías que dependen de un recurso muy rentable: el promedio de producción es alto, pero los indicadores de escolaridad y salud se quedan atrás.',
  },
  {
    id: 'geo-079', tema: 'economica', dificultad: 3,
    enunciado: '¿Por qué es riesgoso para un país depender de la exportación de una o dos materias primas?',
    opciones: [
      'Porque sus ingresos quedan a merced de los precios internacionales, que no controla',
      'Porque las materias primas no se pueden exportar en grandes cantidades',
      'Porque los países que las compran siempre acaban produciéndolas ellos mismos',
      'Porque las materias primas no generan empleo de ningún tipo',
    ],
    correcta: 0,
    explicacion: 'Cuando el precio del petróleo, el cobre o el café cae, el presupuesto del Estado y la moneda se resienten de golpe. Diversificar la economía es la forma de amortiguar ese vaivén.',
  },
  {
    id: 'geo-080', tema: 'economica', dificultad: 2,
    enunciado: 'Un país exporta por 40 000 millones e importa por 52 000 millones. Su balanza comercial es:',
    opciones: [
      'Deficitaria en 12 000 millones',
      'Superavitaria en 12 000 millones',
      'Equilibrada, porque las cifras son parecidas',
      'Deficitaria en 92 000 millones',
    ],
    correcta: 0,
    explicacion: 'La balanza comercial es exportaciones menos importaciones: 40 000 − 52 000 = −12 000. Si el resultado es negativo hay déficit comercial.',
  },
  {
    id: 'geo-081', tema: 'economica', dificultad: 2,
    enunciado: '¿Cuál de estas fuentes de energía es renovable?',
    opciones: ['La geotérmica', 'El carbón', 'El gas natural', 'El uranio'],
    correcta: 0,
    explicacion: 'La geotérmica aprovecha el calor del interior de la Tierra, que no se agota a escala humana. El carbón y el gas son fósiles y el uranio es un mineral finito.',
  },
  {
    id: 'geo-082', tema: 'economica', dificultad: 3,
    enunciado: 'La deslocalización industrial consiste en que una empresa traslada su producción a otro país. Su causa más frecuente es:',
    opciones: [
      'Buscar costos laborales y normas más baratos manteniendo el acceso al mercado',
      'Acercarse a los consumidores de mayor poder adquisitivo',
      'Cumplir con normas ambientales más estrictas',
      'Aprovechar que el transporte internacional se ha encarecido',
    ],
    correcta: 0,
    explicacion: 'Es uno de los rasgos de la globalización productiva: se fabrica donde sale barato y se vende donde se paga bien, algo que solo es posible porque el transporte y las comunicaciones se abarataron.',
  },

  // ----- Geografía política y geopolítica -----
  {
    id: 'geo-083', tema: 'politica', dificultad: 1,
    enunciado: 'Los tres elementos que definen a un Estado son:',
    opciones: [
      'Territorio, población y un gobierno soberano',
      'Bandera, himno y escudo',
      'Idioma, religión y moneda propios',
      'Ejército, fronteras naturales y costa',
    ],
    correcta: 0,
    explicacion: 'Sin cualquiera de los tres no hay Estado. Los símbolos y el idioma pueden reforzar la identidad nacional, pero no son la definición jurídica.',
  },
  {
    id: 'geo-084', tema: 'politica', dificultad: 2,
    enunciado: '¿Qué es una frontera natural?',
    opciones: [
      'Un límite que coincide con un accidente geográfico como un río o una cordillera',
      'Un límite trazado con líneas rectas sobre un mapa',
      'Una frontera que no necesita puestos de control',
      'El límite entre dos biomas distintos',
    ],
    correcta: 0,
    explicacion: 'Las fronteras artificiales, en cambio, se trazan por acuerdos o por meridianos y paralelos, como ocurre en buena parte de África y en el oeste de América del Norte.',
  },
  {
    id: 'geo-085', tema: 'politica', dificultad: 1,
    enunciado: 'El objetivo principal de la Organización de las Naciones Unidas es:',
    opciones: [
      'Mantener la paz y la seguridad internacionales y fomentar la cooperación entre Estados',
      'Establecer un gobierno mundial por encima de los Estados',
      'Regular el comercio internacional y fijar los aranceles',
      'Administrar la moneda común de los países miembros',
    ],
    correcta: 0,
    explicacion: 'La ONU nació en 1945 tras la Segunda Guerra Mundial. No es un gobierno mundial: sus resoluciones dependen de que los Estados miembros las acepten.',
  },
  {
    id: 'geo-086', tema: 'politica', dificultad: 2,
    enunciado: 'El Mercosur es:',
    opciones: [
      'Un bloque de integración económica de países sudamericanos',
      'Una alianza militar del Atlántico Sur',
      'Un organismo de la ONU para el medio ambiente',
      'Un acuerdo cultural entre países de habla hispana',
    ],
    correcta: 0,
    explicacion: 'Busca la libre circulación de bienes y una política comercial común entre sus miembros. En la misma lógica están la Comunidad Andina, la Unión Europea o el T-MEC.',
  },
  {
    id: 'geo-087', tema: 'politica', dificultad: 3,
    enunciado: '¿Por qué el canal de Panamá tiene tanto valor geopolítico?',
    opciones: [
      'Porque conecta el Atlántico con el Pacífico y acorta enormemente las rutas marítimas',
      'Porque es la única vía terrestre entre América del Norte y del Sur',
      'Porque en su entorno se concentran las mayores reservas de petróleo del continente',
      'Porque marca el límite entre el hemisferio norte y el sur',
    ],
    correcta: 0,
    explicacion: 'Sin el canal, un barco entre Nueva York y San Francisco tendría que rodear el extremo sur del continente. Quien controla un paso así controla costos y tiempos del comercio mundial, igual que ocurre con Suez o el estrecho de Ormuz.',
  },
  {
    id: 'geo-088', tema: 'politica', dificultad: 2,
    enunciado: 'La Zona Económica Exclusiva (ZEE) de un país costero se extiende hasta:',
    opciones: [
      '200 millas náuticas desde la costa',
      '12 millas náuticas desde la costa',
      '500 millas náuticas desde la costa',
      'La mitad de la distancia al continente más cercano',
    ],
    correcta: 0,
    explicacion: 'En la ZEE el Estado tiene derechos sobre los recursos del mar y del fondo marino. El mar territorial, donde ejerce soberanía plena, llega solo hasta las 12 millas.',
  },
  {
    id: 'geo-089', tema: 'politica', dificultad: 2,
    enunciado: '¿Cuáles son los dos países sudamericanos sin salida al mar?',
    opciones: ['Bolivia y Paraguay', 'Paraguay y Uruguay', 'Bolivia y Ecuador', 'Perú y Paraguay'],
    correcta: 0,
    explicacion: 'Bolivia perdió su litoral en la Guerra del Pacífico y Paraguay nunca lo tuvo. Los dos dependen de acuerdos con sus vecinos y de los ríos de la cuenca del Plata para exportar.',
  },
  {
    id: 'geo-090', tema: 'politica', dificultad: 3,
    enunciado: '¿En qué se diferencia un Estado federal de uno unitario?',
    opciones: [
      'En el federal los territorios tienen gobierno y leyes propias en ciertas materias; en el unitario todo depende del gobierno central',
      'En el federal hay varios presidentes y en el unitario solo uno',
      'El federal tiene fronteras naturales y el unitario artificiales',
      'El federal es siempre más extenso que el unitario',
    ],
    correcta: 0,
    explicacion: 'México, Brasil y Argentina son federales; Chile, Colombia y Perú son unitarios, aunque con distintos grados de descentralización.',
  },

  // ----- Medio ambiente, riesgos y sostenibilidad -----
  {
    id: 'geo-091', tema: 'ambiente', dificultad: 2,
    enunciado: '¿Qué es el efecto invernadero?',
    opciones: [
      'La retención de calor por gases de la atmósfera, un fenómeno natural que la actividad humana ha intensificado',
      'El agujero que dejan los gases industriales en la capa de ozono',
      'El aumento de la radiación solar que llega a la Tierra',
      'El calor que desprenden las ciudades por el asfalto y el tráfico',
    ],
    correcta: 0,
    explicacion: 'Sin efecto invernadero la temperatura media del planeta estaría bajo cero. El problema no es que exista, sino que al aumentar los gases se retiene más calor del que corresponde. Lo último descrito es la isla de calor urbana.',
  },
  {
    id: 'geo-092', tema: 'ambiente', dificultad: 1,
    enunciado: '¿Cuál es la principal causa del aumento de dióxido de carbono en la atmósfera?',
    opciones: [
      'La quema de combustibles fósiles',
      'La erupción de los volcanes activos',
      'La respiración de la población mundial',
      'El uso de aerosoles y refrigerantes',
    ],
    correcta: 0,
    explicacion: 'Carbón, petróleo y gas liberan carbono que llevaba millones de años almacenado. La deforestación agrava el problema porque elimina la vegetación que lo absorbe. Los CFC de los aerosoles afectaban sobre todo al ozono.',
  },
  {
    id: 'geo-093', tema: 'ambiente', dificultad: 2,
    enunciado: '¿Cuál de estas es una consecuencia esperada del calentamiento global?',
    opciones: [
      'El aumento del nivel del mar y mayor frecuencia de eventos climáticos extremos',
      'La desaparición del efecto invernadero natural',
      'El enfriamiento general de las zonas tropicales',
      'El aumento de la capa de ozono sobre los polos',
    ],
    correcta: 0,
    explicacion: 'El mar sube porque el agua se dilata al calentarse y porque se derrite hielo continental. Además, más energía en la atmósfera implica tormentas, sequías y olas de calor más intensas.',
  },
  {
    id: 'geo-094', tema: 'ambiente', dificultad: 2,
    enunciado: 'La principal causa directa de la deforestación en la Amazonía es:',
    opciones: [
      'La expansión de la ganadería y la agricultura',
      'La construcción de ciudades y aeropuertos',
      'El turismo de naturaleza',
      'La extracción de agua para consumo humano',
    ],
    correcta: 0,
    explicacion: 'Se tala y se quema para abrir pastos y cultivos, sobre todo soya. La minería, la tala ilegal y las carreteras completan el cuadro.',
  },
  {
    id: 'geo-095', tema: 'ambiente', dificultad: 2,
    enunciado: 'El desarrollo sostenible se definió como aquel que:',
    opciones: [
      'Satisface las necesidades del presente sin comprometer la capacidad de las generaciones futuras de satisfacer las suyas',
      'Detiene el crecimiento económico para proteger la naturaleza',
      'Sustituye toda la energía del mundo por fuentes renovables en diez años',
      'Traslada la industria contaminante a zonas despobladas',
    ],
    correcta: 0,
    explicacion: 'Es la definición del informe Brundtland (1987). No propone frenar el desarrollo, sino que sea compatible con lo ambiental y lo social a largo plazo.',
  },
  {
    id: 'geo-096', tema: 'ambiente', dificultad: 3,
    enunciado: 'Dos sismos de la misma magnitud causan muy distinto número de víctimas en dos países. ¿Qué lo explica mejor?',
    opciones: [
      'La vulnerabilidad: calidad de las construcciones, planificación urbana y preparación de la población',
      'La profundidad del hipocentro, que siempre es mayor en los países ricos',
      'La hora del día en que ocurre el sismo',
      'La distancia al ecuador, que amortigua las ondas sísmicas',
    ],
    correcta: 0,
    explicacion: 'El riesgo combina la amenaza natural con la vulnerabilidad de la sociedad expuesta. La amenaza no se puede evitar; la vulnerabilidad sí se puede reducir, y ahí está la diferencia entre un susto y una catástrofe.',
    pista: 'Riesgo = amenaza × vulnerabilidad.',
  },
  {
    id: 'geo-097', tema: 'ambiente', dificultad: 2,
    enunciado: 'La lluvia ácida se produce principalmente por:',
    opciones: [
      'Óxidos de azufre y de nitrógeno emitidos por industrias y vehículos',
      'El exceso de dióxido de carbono en la atmósfera',
      'La evaporación del agua de mar cerca de las costas',
      'Los gases CFC usados en refrigeración',
    ],
    correcta: 0,
    explicacion: 'Esos óxidos reaccionan con el vapor de agua y forman ácidos que caen con la lluvia, dañando bosques, suelos, lagos y edificios, a veces a cientos de kilómetros de donde se emitieron.',
  },
  {
    id: 'geo-098', tema: 'ambiente', dificultad: 2,
    enunciado: '¿Qué mide la huella ecológica?',
    opciones: [
      'La superficie de territorio necesaria para producir lo que consume una población y absorber sus residuos',
      'La cantidad de basura que genera una ciudad en un año',
      'El número de especies que se extinguen en un país',
      'La superficie de bosque talada anualmente en el mundo',
    ],
    correcta: 0,
    explicacion: 'Se expresa en hectáreas por persona y permite comparar: si toda la humanidad consumiera como los países más ricos, harían falta varios planetas.',
  },
  {
    id: 'geo-099', tema: 'ambiente', dificultad: 3,
    enunciado: 'El Acuerdo de París (2015) comprometió a los países firmantes a:',
    opciones: [
      'Limitar el aumento de la temperatura media global muy por debajo de 2 °C respecto a la era preindustrial',
      'Prohibir de inmediato el uso de combustibles fósiles',
      'Eliminar los gases que destruyen la capa de ozono',
      'Crear un impuesto mundial único sobre las emisiones',
    ],
    correcta: 0,
    explicacion: 'Cada país presenta sus propias metas de reducción y las revisa periódicamente. La eliminación de los gases que dañan el ozono corresponde al Protocolo de Montreal, de 1987.',
  },
  {
    id: 'geo-100', tema: 'ambiente', dificultad: 3,
    enunciado: 'Tras el Protocolo de Montreal se prohibieron los CFC y el agujero de la capa de ozono empezó a reducirse. ¿Qué muestra ese caso?',
    opciones: [
      'Que un acuerdo internacional con metas claras puede revertir un daño ambiental global',
      'Que los problemas ambientales se resuelven solos con el tiempo',
      'Que el ozono y el clima son el mismo problema',
      'Que prohibir sustancias siempre frena el desarrollo económico',
    ],
    correcta: 0,
    explicacion: 'Suele citarse como el caso de éxito de la cooperación ambiental: hubo alternativas técnicas viables, un objetivo medible y cumplimiento verificado. El clima es más difícil porque afecta a la base energética completa.',
  },

  // ----- Geografía de América Latina -----
  {
    id: 'geo-101', tema: 'america-latina', dificultad: 1,
    enunciado: 'La cordillera de los Andes recorre:',
    opciones: [
      'El borde occidental de América del Sur, de Venezuela a la Patagonia',
      'El borde oriental de América del Sur, junto al Atlántico',
      'América Central, de Guatemala a Panamá',
      'El centro de Brasil, de norte a sur',
    ],
    correcta: 0,
    explicacion: 'Con unos 7 000 km es la cordillera continental más larga del mundo y condiciona el clima, los ríos y el poblamiento de siete países.',
  },
  {
    id: 'geo-102', tema: 'america-latina', dificultad: 1,
    enunciado: 'La selva amazónica se extiende principalmente por la cuenca del río Amazonas y destaca por:',
    opciones: [
      'Ser la mayor selva tropical del planeta y un enorme reservorio de biodiversidad',
      'Ser la región más poblada de América del Sur',
      'Concentrar la mayor producción industrial del continente',
      'Tener el clima más seco de América del Sur',
    ],
    correcta: 0,
    explicacion: 'Ocupa territorio de nueve países, sobre todo Brasil, y además de su biodiversidad influye en el régimen de lluvias de buena parte del continente.',
  },
  {
    id: 'geo-103', tema: 'america-latina', dificultad: 2,
    enunciado: 'El país más extenso y más poblado de América Latina es:',
    opciones: ['Brasil', 'México', 'Argentina', 'Colombia'],
    correcta: 0,
    explicacion: 'Brasil supera los 8,5 millones de km² y los 200 millones de habitantes. Argentina es el segundo en superficie y México el segundo en población.',
  },
  {
    id: 'geo-104', tema: 'america-latina', dificultad: 2,
    enunciado: 'El lago Titicaca, el lago navegable más alto del mundo, se encuentra entre:',
    opciones: ['Perú y Bolivia', 'Chile y Argentina', 'Ecuador y Colombia', 'Bolivia y Paraguay'],
    correcta: 0,
    explicacion: 'Está en el altiplano andino, a unos 3 800 metros de altitud, y su cuenca es compartida por los dos países.',
  },
  {
    id: 'geo-105', tema: 'america-latina', dificultad: 2,
    enunciado: 'El istmo de Panamá cumple la función geográfica de:',
    opciones: [
      'Unir América Central con América del Sur y separar dos océanos',
      'Separar México de Estados Unidos',
      'Unir la isla de Cuba con el continente',
      'Dividir la cuenca del Amazonas de la del Orinoco',
    ],
    correcta: 0,
    explicacion: 'Un istmo es una franja estrecha de tierra entre dos mares. La de Panamá es el punto donde se excavó el canal, precisamente por lo angosto del territorio.',
  },
  {
    id: 'geo-106', tema: 'america-latina', dificultad: 3,
    enunciado: 'El desierto de Atacama, en el norte de Chile, es el más árido del mundo. ¿Qué lo explica?',
    opciones: [
      'La corriente fría de Humboldt y el bloqueo de la humedad por la cordillera de los Andes',
      'Su cercanía al ecuador, que evapora toda la lluvia',
      'La ausencia total de vientos en esa franja del continente',
      'La altitud, que impide la formación de nubes',
    ],
    correcta: 0,
    explicacion: 'La corriente fría enfría el aire sobre el mar e impide que ascienda y llueva, y los Andes bloquean la humedad que viene del Atlántico. Hay estaciones allí donde no se ha registrado lluvia en años.',
  },
  {
    id: 'geo-107', tema: 'america-latina', dificultad: 2,
    enunciado: 'La Patagonia se reparte entre los territorios de:',
    opciones: ['Argentina y Chile', 'Chile y Bolivia', 'Argentina y Uruguay', 'Chile y Perú'],
    correcta: 0,
    explicacion: 'Ocupa el extremo sur del continente a ambos lados de los Andes: la vertiente chilena es húmeda y boscosa y la argentina, una meseta seca y ventosa por el efecto de sombra de lluvia.',
  },
  {
    id: 'geo-108', tema: 'america-latina', dificultad: 3,
    enunciado: 'El Altiplano mexicano está enmarcado por:',
    opciones: [
      'La Sierra Madre Occidental y la Sierra Madre Oriental',
      'La Sierra Madre del Sur y la península de Yucatán',
      'La Sierra Nevada y las Montañas Rocosas',
      'El Eje Neovolcánico y la Sierra Madre de Chiapas',
    ],
    correcta: 0,
    explicacion: 'Las dos Sierras Madre corren de norte a sur y encierran una meseta alta donde se asienta buena parte de la población del país, incluida la Ciudad de México.',
  },
  {
    id: 'geo-109', tema: 'america-latina', dificultad: 2,
    enunciado: 'La cuenca del Plata, la segunda más grande de América del Sur, está formada principalmente por los ríos:',
    opciones: [
      'Paraná, Paraguay y Uruguay',
      'Amazonas, Negro y Madeira',
      'Orinoco, Caroní y Meta',
      'Magdalena, Cauca y Atrato',
    ],
    correcta: 0,
    explicacion: 'Es la salida al mar de Paraguay y Bolivia y una vía de transporte clave para el Cono Sur; en ella están además las grandes represas hidroeléctricas de la región.',
  },
  {
    id: 'geo-110', tema: 'america-latina', dificultad: 3,
    enunciado: '¿Por qué gran parte de la población de América Latina se concentra en las costas y en los altiplanos, y no en el interior de las tierras bajas?',
    opciones: [
      'Por el clima más templado de la altura, la fertilidad de esos suelos y la herencia de las ciudades coloniales y portuarias',
      'Porque en el interior no hay agua dulce disponible',
      'Porque los gobiernos prohibieron poblar el interior del continente',
      'Porque el interior del continente está por debajo del nivel del mar',
    ],
    correcta: 0,
    explicacion: 'Se combinan tres cosas: en el trópico la altura da un clima más cómodo y suelos volcánicos fértiles, los puertos concentraron el comercio colonial y la selva amazónica es de poblamiento difícil.',
  },

  // ----- Complemento hasta la meta de 10 por tema -----
  {
    id: 'geo-111', tema: 'cartografia', dificultad: 3,
    enunciado: 'Dos ciudades están a 15° de longitud de diferencia. ¿Cuánta diferencia horaria hay entre ellas?',
    opciones: ['1 hora', '15 horas', '24 minutos', 'Media hora'],
    correcta: 0,
    explicacion: 'La Tierra gira 360° en 24 horas, es decir 15° por hora. Cada huso horario corresponde justamente a esos 15° de longitud.',
  },
  {
    id: 'geo-112', tema: 'tierra-universo', dificultad: 2,
    enunciado: '¿Cuánto dura aproximadamente el movimiento de traslación de la Tierra alrededor del Sol?',
    opciones: ['365 días y casi 6 horas', '24 horas', '28 días', '180 días'],
    correcta: 0,
    explicacion: 'Esas casi seis horas sobrantes se acumulan y por eso cada cuatro años se añade el 29 de febrero: el año bisiesto.',
  },
  {
    id: 'geo-113', tema: 'tierra-universo', dificultad: 3,
    enunciado: 'En el círculo polar ártico, durante el solsticio de junio, ocurre que:',
    opciones: [
      'El Sol no se oculta durante 24 horas: es el llamado sol de medianoche',
      'La noche dura 24 horas seguidas',
      'El día y la noche duran exactamente lo mismo',
      'El Sol cae perpendicular al mediodía',
    ],
    correcta: 0,
    explicacion: 'La inclinación del eje deja esa franja completamente iluminada durante el verano de su hemisferio, y completamente a oscuras seis meses después.',
  },
  {
    id: 'geo-114', tema: 'geodinamica-interna', dificultad: 2,
    enunciado: 'Un tsunami se origina con mayor frecuencia por:',
    opciones: [
      'Un sismo submarino que desplaza bruscamente una gran masa de agua',
      'Vientos huracanados sobre el océano',
      'El deshielo repentino de los glaciares',
      'La atracción gravitatoria de la Luna',
    ],
    correcta: 0,
    explicacion: 'En mar abierto la ola es baja y larga; al llegar a aguas someras pierde velocidad y gana altura. La atracción de la Luna produce mareas, no tsunamis.',
  },
  {
    id: 'geo-115', tema: 'relieve', dificultad: 2,
    enunciado: 'El proceso por el cual el suelo fértil se pierde por acción del agua y el viento se llama:',
    opciones: ['Erosión del suelo', 'Sedimentación', 'Meteorización química', 'Subducción'],
    correcta: 0,
    explicacion: 'Se acelera cuando se retira la vegetación que sujetaba el terreno. Un suelo tarda siglos en formarse y puede perderse en pocas temporadas de lluvias.',
  },
  {
    id: 'geo-116', tema: 'relieve', dificultad: 3,
    enunciado: '¿Por qué los ríos depositan primero los materiales más gruesos y después los más finos?',
    opciones: [
      'Porque al perder velocidad sueltan primero lo más pesado y arrastran lo ligero más lejos',
      'Porque los materiales gruesos flotan mejor',
      'Porque los finos se disuelven en el agua',
      'Porque los gruesos provienen de la desembocadura',
    ],
    correcta: 0,
    explicacion: 'Es la sedimentación selectiva: cantos rodados cerca de la montaña, arenas en el curso medio y limos y arcillas en la desembocadura. Por eso los deltas tienen suelos tan fértiles.',
  },
  {
    id: 'geo-117', tema: 'hidrografia', dificultad: 2,
    enunciado: 'Una represa hidroeléctrica genera electricidad a partir de:',
    opciones: [
      'La energía del agua almacenada que cae y mueve unas turbinas',
      'El calor del agua acumulada al sol',
      'La evaporación del embalse',
      'El movimiento de las mareas del río',
    ],
    correcta: 0,
    explicacion: 'Es energía renovable, pero no inocua: inunda territorios, desplaza población y altera el régimen del río aguas abajo.',
  },
  {
    id: 'geo-118', tema: 'biogeografia', dificultad: 2,
    enunciado: 'Los manglares, en las costas tropicales, cumplen la función ecológica de:',
    opciones: [
      'Servir de criadero de especies marinas y proteger la costa de la erosión y las tormentas',
      'Producir la mayor parte del agua dulce de la región',
      'Fijar el relieve montañoso cercano',
      'Impedir la llegada de corrientes marinas frías',
    ],
    correcta: 0,
    explicacion: 'Sus raíces amortiguan el oleaje y retienen sedimentos. Su destrucción para camaroneras y turismo deja a las poblaciones costeras mucho más expuestas.',
  },
  {
    id: 'geo-119', tema: 'biogeografia', dificultad: 3,
    enunciado: 'La introducción de una especie exótica invasora en un ecosistema suele provocar:',
    opciones: [
      'Desplazamiento de especies nativas que no tienen defensas ni depredadores frente a ella',
      'Un aumento general de la biodiversidad local',
      'La mejora de la calidad del suelo',
      'Ningún efecto si la especie no es venenosa',
    ],
    correcta: 0,
    explicacion: 'Sin los controles naturales de su lugar de origen, la especie se multiplica y ocupa el nicho de las nativas. Es una de las principales causas de extinción a nivel mundial.',
  },
  {
    id: 'geo-120', tema: 'politica', dificultad: 2,
    enunciado: 'Un Estado archipelágico es aquel que:',
    opciones: [
      'Está formado por un conjunto de islas',
      'No tiene salida al mar',
      'Tiene fronteras solo con un país',
      'Está dividido en dos territorios separados',
    ],
    correcta: 0,
    explicacion: 'Indonesia, Filipinas o Japón son ejemplos. Su condición insular condiciona el transporte, la defensa y la delimitación de sus aguas.',
  },
  {
    id: 'geo-121', tema: 'politica', dificultad: 3,
    enunciado: '¿Por qué el control del Ártico ha ganado importancia geopolítica en las últimas décadas?',
    opciones: [
      'Porque el deshielo abre nuevas rutas de navegación y facilita el acceso a recursos',
      'Porque su población ha crecido rápidamente',
      'Porque allí se concentran las principales rutas aéreas',
      'Porque es el único territorio sin dueño del planeta',
    ],
    correcta: 0,
    explicacion: 'Rutas más cortas entre Asia, Europa y América y yacimientos antes inaccesibles explican las reclamaciones de los países ribereños. Es un caso donde el cambio climático redibuja el mapa político.',
  },
];
