/**
 * historia.js — Banco de historia de Colombia.
 *
 * El Saber 11 la evalúa dentro de sociales y ciudadanas, y el examen de
 * admisión de la UNAL dentro de ciencias sociales. No se pregunta como una
 * lista de fechas: se pregunta por causas, consecuencias y continuidades, y
 * casi siempre a partir de un texto o una fuente.
 *
 * Dos reglas al escribirlo: fechas y hechos verificables, y ninguna valoración
 * de partido. En los asuntos que siguen en disputa pública se describe lo que
 * ocurrió y quiénes sostienen cada posición, sin tomar partido.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const HISTORIA = [
  // ----- Pueblos originarios -----
  {
    id: 'his-001', tema: 'prehispanica', dificultad: 1,
    enunciado: '¿Qué región habitaba el pueblo muisca a la llegada de los españoles?',
    opciones: [
      'El altiplano cundiboyacense',
      'La Sierra Nevada de Santa Marta',
      'La selva amazónica',
      'El valle del río Cauca',
    ],
    correcta: 0,
    explicacion: 'Ocupaban los actuales departamentos de Cundinamarca y Boyacá. Los taironas estaban en la Sierra Nevada y los quimbayas en el eje cafetero.',
  },
  {
    id: 'his-002', tema: 'prehispanica', dificultad: 2,
    enunciado: 'La economía muisca se basaba principalmente en:',
    opciones: [
      'La agricultura de papa y maíz, la explotación de sal y esmeraldas y un activo comercio',
      'La ganadería de vacunos y caballos',
      'La pesca en alta mar',
      'La minería de carbón a gran escala',
    ],
    correcta: 0,
    explicacion: 'La sal de Zipaquirá y Nemocón era su producto de intercambio más valioso. Vacas y caballos llegaron con los europeos: antes no existían en América.',
  },
  {
    id: 'his-003', tema: 'prehispanica', dificultad: 2,
    enunciado: 'Los taironas se destacaron por:',
    opciones: [
      'Su arquitectura en piedra, con terrazas y caminos en la Sierra Nevada',
      'La construcción de pirámides escalonadas de adobe',
      'La navegación transoceánica',
      'El uso de la escritura jeroglífica',
    ],
    correcta: 0,
    explicacion: 'Teyuna, conocida como Ciudad Perdida, es el mayor conjunto conservado. Adaptaron la montaña con terrazas que aún controlan la erosión.',
  },
  {
    id: 'his-004', tema: 'prehispanica', dificultad: 2,
    enunciado: 'La balsa muisca, pieza central del Museo del Oro, se relaciona con:',
    opciones: [
      'El rito de investidura del cacique en la laguna de Guatavita, origen de la leyenda de El Dorado',
      'Un sacrificio humano en el mar Caribe',
      'Un tratado entre los muiscas y los taironas',
      'La fundación de Santafé de Bogotá',
    ],
    correcta: 0,
    explicacion: 'El cacique se cubría de polvo de oro y hacía ofrendas en la laguna. Los europeos convirtieron ese rito en el mito de una ciudad de oro que buscaron durante décadas.',
  },
  {
    id: 'his-005', tema: 'prehispanica', dificultad: 2,
    enunciado: 'El parque arqueológico de San Agustín, en el Huila, es famoso por:',
    opciones: [
      'Sus grandes estatuas de piedra asociadas a rituales funerarios',
      'Sus pirámides de adobe',
      'Sus terrazas de cultivo en la selva',
      'Sus observatorios astronómicos de madera',
    ],
    correcta: 0,
    explicacion: 'Es la mayor concentración de estatuaria megalítica de América del Sur y es Patrimonio de la Humanidad. Tierradentro, en el Cauca, conserva hipogeos excavados en la roca.',
  },
  {
    id: 'his-006', tema: 'prehispanica', dificultad: 3,
    enunciado: 'Los zenúes, en las sabanas del San Jorge, desarrollaron una obra de ingeniería consistente en:',
    opciones: [
      'Un extenso sistema de canales para controlar las inundaciones y cultivar',
      'Una red de acueductos de piedra hacia la Sierra Nevada',
      'Murallas defensivas alrededor de sus poblados',
      'Puentes colgantes sobre el río Magdalena',
    ],
    correcta: 0,
    explicacion: 'Manejaron durante siglos una llanura que se inunda cada año, convirtiendo el agua en aliada. Hoy se estudia ese sistema como referencia frente a las inundaciones de la región.',
  },
  {
    id: 'his-007', tema: 'prehispanica', dificultad: 2,
    enunciado: 'En la organización política muisca, el zipa y el zaque eran:',
    opciones: [
      'Los dos principales jefes, con centros en Bacatá y Hunza respectivamente',
      'Dos deidades del panteón muisca',
      'Los sacerdotes encargados de los templos',
      'Los nombres de sus dos calendarios',
    ],
    correcta: 0,
    explicacion: 'Hunza corresponde a la actual Tunja. No formaban un imperio unificado como el inca: eran confederaciones de cacicazgos que también rivalizaban entre sí.',
  },
  {
    id: 'his-008', tema: 'prehispanica', dificultad: 2,
    enunciado: 'La lengua de los muiscas pertenecía a la familia lingüística:',
    opciones: ['Chibcha', 'Quechua', 'Arawak', 'Caribe'],
    correcta: 0,
    explicacion: 'De esa lengua quedan topónimos como Bogotá, Chía, Zipaquirá y Sogamoso, y palabras de uso corriente como chisga o cuba.',
  },
  {
    id: 'his-009', tema: 'prehispanica', dificultad: 3,
    enunciado: 'A diferencia de los incas o los mexicas, los pueblos del actual territorio colombiano:',
    opciones: [
      'No formaron un Estado unificado, sino múltiples cacicazgos y confederaciones',
      'No practicaban la agricultura',
      'No tenían jerarquías sociales',
      'Desconocían la metalurgia',
    ],
    correcta: 0,
    explicacion: 'Esa fragmentación cambió la conquista: no bastaba con tomar una capital, hubo que someter región por región. En orfebrería, de hecho, alcanzaron un nivel excepcional.',
  },
  {
    id: 'his-010', tema: 'prehispanica', dificultad: 2,
    enunciado: 'Los quimbayas son reconocidos sobre todo por:',
    opciones: [
      'Su orfebrería en oro y tumbaga, de gran refinamiento técnico',
      'Sus construcciones en piedra de varios pisos',
      'Su sistema de escritura pictográfica',
      'Su dominio de la navegación fluvial',
    ],
    correcta: 0,
    explicacion: 'La tumbaga es una aleación de oro y cobre. El llamado Tesoro Quimbaya, hallado en el siglo XIX, es una de las colecciones prehispánicas más valiosas que existen.',
  },

  // ----- Conquista -----
  {
    id: 'his-011', tema: 'conquista', dificultad: 2,
    enunciado: 'Santa Marta, la ciudad más antigua de Colombia aún existente, fue fundada en 1525 por:',
    opciones: ['Rodrigo de Bastidas', 'Gonzalo Jiménez de Quesada', 'Pedro de Heredia', 'Sebastián de Belalcázar'],
    correcta: 0,
    explicacion: 'Heredia fundó Cartagena en 1533, Jiménez de Quesada fundó Santafé de Bogotá en 1538 y Belalcázar fundó Popayán y Cali.',
  },
  {
    id: 'his-012', tema: 'conquista', dificultad: 2,
    enunciado: 'Santafé de Bogotá fue fundada en 1538 por la expedición encabezada por:',
    opciones: ['Gonzalo Jiménez de Quesada', 'Rodrigo de Bastidas', 'Francisco Pizarro', 'Cristóbal Colón'],
    correcta: 0,
    explicacion: 'Su expedición remontó el río Magdalena hasta el altiplano muisca. Casi al mismo tiempo llegaron allí Belalcázar desde el sur y Federmán desde los llanos.',
  },
  {
    id: 'his-013', tema: 'conquista', dificultad: 2,
    enunciado: 'El mito de El Dorado impulsó numerosas expediciones porque:',
    opciones: [
      'Los europeos interpretaron el rito del cacique cubierto de oro como la existencia de una ciudad repleta de riquezas',
      'Existían mapas indígenas que señalaban su ubicación exacta',
      'La Corona española había confirmado su existencia',
      'Se había encontrado una mina de ese nombre',
    ],
    correcta: 0,
    explicacion: 'Se intentó incluso desecar la laguna de Guatavita. Muchas expediciones terminaron en desastre, pero en el camino se exploró y se ocupó buena parte del territorio.',
  },
  {
    id: 'his-014', tema: 'conquista', dificultad: 3,
    enunciado: '¿Cuál fue la principal causa de la enorme caída de la población indígena durante el siglo XVI?',
    opciones: [
      'Las enfermedades traídas por los europeos, frente a las cuales no tenían defensas, sumadas al trabajo forzado',
      'Las migraciones voluntarias hacia el sur del continente',
      'Un cambio climático repentino',
      'La escasez de alimentos por el fin de la agricultura',
    ],
    correcta: 0,
    explicacion: 'Viruela, sarampión y tifus causaron más muertes que las armas. A eso se sumaron el trabajo en minas y encomiendas y la ruptura de las formas de vida y de producción.',
  },
  {
    id: 'his-015', tema: 'conquista', dificultad: 2,
    enunciado: 'La encomienda consistía en:',
    opciones: [
      'La entrega de un grupo de indígenas a un español para que recibiera su tributo o trabajo, a cambio de protegerlos y evangelizarlos',
      'La entrega de un título de propiedad sobre la tierra',
      'Un impuesto que pagaban los españoles a la Corona',
      'Un permiso para comerciar con Europa',
    ],
    correcta: 0,
    explicacion: 'Formalmente no era propiedad de personas ni de tierras, pero en la práctica funcionó como una forma de trabajo forzado. Fue el centro de la denuncia de Bartolomé de las Casas.',
  },
  {
    id: 'his-016', tema: 'conquista', dificultad: 3,
    enunciado: 'Las Leyes Nuevas de 1542 buscaban:',
    opciones: [
      'Limitar la encomienda y prohibir la esclavitud de los indígenas',
      'Ampliar los privilegios de los encomenderos',
      'Autorizar la trata de personas africanas',
      'Independizar administrativamente a las colonias',
    ],
    correcta: 0,
    explicacion: 'Fueron resultado de las denuncias de Las Casas y de la discusión sobre los derechos de los indígenas. La resistencia de los encomenderos hizo que se aplicaran de forma parcial.',
  },
  {
    id: 'his-017', tema: 'conquista', dificultad: 2,
    enunciado: 'La llegada forzada de personas africanas esclavizadas al territorio se intensificó porque:',
    opciones: [
      'La población indígena había disminuido drásticamente y se necesitaba mano de obra en minas y haciendas',
      'Los africanos conocían mejor el territorio',
      'La Corona prohibió el trabajo indígena desde el primer año',
      'Los indígenas se negaron a trabajar en la agricultura',
    ],
    correcta: 0,
    explicacion: 'Cartagena de Indias se convirtió en el principal puerto de entrada de personas esclavizadas en el norte de Suramérica. La minería del oro del Chocó y del Cauca dependió de ese trabajo.',
  },
  {
    id: 'his-018', tema: 'conquista', dificultad: 2,
    enunciado: '¿Cuál de estas afirmaciones sobre la conquista es correcta?',
    opciones: [
      'Hubo una resistencia indígena prolongada en varias regiones, no una sumisión inmediata',
      'El territorio fue ocupado por completo en menos de cinco años',
      'No hubo enfrentamientos armados significativos',
      'Todos los pueblos se aliaron entre sí contra los españoles',
    ],
    correcta: 0,
    explicacion: 'Pijaos, muzos y wayúu, entre otros, resistieron durante décadas o siglos. También hubo alianzas de algunos pueblos con los españoles contra sus rivales.',
  },
  {
    id: 'his-019', tema: 'conquista', dificultad: 2,
    enunciado: 'El mestizaje que se produjo desde el siglo XVI dio origen a:',
    opciones: [
      'Una sociedad diversa con población indígena, europea, africana y sus mezclas',
      'Una población culturalmente homogénea',
      'La desaparición total de las lenguas indígenas',
      'Un territorio habitado solo por europeos',
    ],
    correcta: 0,
    explicacion: 'Esa diversidad es la base de lo que la Constitución de 1991 reconocería como una nación pluriétnica y multicultural.',
  },
  {
    id: 'his-020', tema: 'conquista', dificultad: 3,
    enunciado: 'Cartagena de Indias fue amurallada durante el periodo colonial principalmente para:',
    opciones: [
      'Defenderse de los ataques de piratas y de potencias rivales de España',
      'Contener el crecimiento urbano',
      'Separar los barrios de las distintas castas',
      'Proteger la ciudad de las inundaciones',
    ],
    correcta: 0,
    explicacion: 'Era el puerto donde se concentraban el comercio y las riquezas que iban a España. Las fortificaciones son hoy Patrimonio de la Humanidad.',
  },

  // ----- La Colonia -----
  {
    id: 'his-021', tema: 'colonia', dificultad: 2,
    enunciado: 'Durante buena parte del periodo colonial, el territorio se conoció como:',
    opciones: ['El Nuevo Reino de Granada', 'La Capitanía General de Venezuela', 'El Virreinato del Perú del Norte', 'La Provincia de Castilla de Oro'],
    correcta: 0,
    explicacion: 'Dependía inicialmente del Virreinato del Perú y tenía su propia Real Audiencia en Santafé desde 1550.',
  },
  {
    id: 'his-022', tema: 'colonia', dificultad: 2,
    enunciado: 'El Virreinato de la Nueva Granada fue creado en 1717, suprimido y restablecido de forma definitiva en:',
    opciones: ['1739', '1810', '1550', '1819'],
    correcta: 0,
    explicacion: 'Su creación respondía a la necesidad de mejorar la defensa y el control fiscal de un territorio muy extenso y alejado de Lima.',
  },
  {
    id: 'his-023', tema: 'colonia', dificultad: 2,
    enunciado: 'En la sociedad colonial, los criollos eran:',
    opciones: [
      'Los hijos de españoles nacidos en América',
      'Los españoles nacidos en la península',
      'Los hijos de español e indígena',
      'Las personas africanas libres',
    ],
    correcta: 0,
    explicacion: 'Los peninsulares nacían en España, los mestizos eran hijos de español e indígena y los mulatos, de español y africano. Esa clasificación por origen organizaba derechos y oportunidades.',
  },
  {
    id: 'his-024', tema: 'colonia', dificultad: 3,
    enunciado: 'Uno de los motivos del descontento criollo que alimentó la independencia fue que:',
    opciones: [
      'Pese a su riqueza y educación, estaban excluidos de los altos cargos, reservados a los peninsulares',
      'No podían poseer tierras ni negocios',
      'Se les prohibía hablar español',
      'Estaban obligados a pagar el tributo indígena',
    ],
    correcta: 0,
    explicacion: 'Tenían poder económico pero no político. Las reformas borbónicas del siglo XVIII agravaron esa exclusión y aumentaron los impuestos.',
  },
  {
    id: 'his-025', tema: 'colonia', dificultad: 2,
    enunciado: 'Un palenque era:',
    opciones: [
      'Un poblado fundado y defendido por personas esclavizadas que habían escapado',
      'Una fortaleza construida por la Corona en la costa',
      'Un tipo de hacienda azucarera',
      'Un mercado autorizado para comerciar con extranjeros',
    ],
    correcta: 0,
    explicacion: 'San Basilio de Palenque, asociado a la figura de Benkos Biohó, se considera el primer pueblo libre de América y conserva su propia lengua criolla.',
  },
  {
    id: 'his-026', tema: 'colonia', dificultad: 2,
    enunciado: 'El sistema de estancos en la Colonia consistía en:',
    opciones: [
      'El monopolio de la Corona sobre la producción y venta de ciertos productos, como el tabaco y el aguardiente',
      'La prohibición de cultivar alimentos',
      'La entrega de tierras a los indígenas',
      'El pago de diezmos a la Iglesia',
    ],
    correcta: 0,
    explicacion: 'Eran una fuente clave de ingresos fiscales y, por lo mismo, una fuente constante de descontento popular.',
  },
  {
    id: 'his-027', tema: 'colonia', dificultad: 2,
    enunciado: 'La Real Expedición Botánica, iniciada en 1783, fue dirigida por:',
    opciones: ['José Celestino Mutis', 'Francisco José de Caldas', 'Antonio Nariño', 'Camilo Torres'],
    correcta: 0,
    explicacion: 'Estudió y catalogó la flora del Nuevo Reino de Granada con una colección de láminas extraordinaria. Varios de sus participantes, como Caldas, tuvieron después un papel en la independencia.',
  },
  {
    id: 'his-028', tema: 'colonia', dificultad: 3,
    enunciado: 'Las reformas borbónicas del siglo XVIII buscaban, ante todo:',
    opciones: [
      'Aumentar el control administrativo y los ingresos fiscales de la Corona sobre sus colonias',
      'Conceder autonomía política a los criollos',
      'Abolir la esclavitud en América',
      'Reducir los impuestos al comercio',
    ],
    correcta: 0,
    explicacion: 'Más recaudo y más control central. Ese endurecimiento explica episodios como la Revolución de los Comuneros y fue uno de los detonantes de la crisis posterior.',
  },
  {
    id: 'his-029', tema: 'colonia', dificultad: 2,
    enunciado: 'Durante la Colonia, la Iglesia católica cumplió, además de su función religiosa, el papel de:',
    opciones: [
      'Encargada de buena parte de la educación y del registro de la población',
      'Autoridad militar de las provincias',
      'Administradora exclusiva de las minas',
      'Institución ajena a la vida civil',
    ],
    correcta: 0,
    explicacion: 'Llevaba los libros de bautismos, matrimonios y defunciones, fundó colegios y universidades y tenía una influencia política y económica considerable.',
  },
  {
    id: 'his-030', tema: 'colonia', dificultad: 2,
    enunciado: 'La economía colonial neogranadina se apoyaba sobre todo en:',
    opciones: [
      'La minería del oro y la producción agrícola de las haciendas',
      'La exportación de manufacturas a Europa',
      'La pesca industrial',
      'El comercio de café a gran escala',
    ],
    correcta: 0,
    explicacion: 'El café solo se convirtió en producto principal a finales del siglo XIX. El comercio con el exterior estaba además restringido al monopolio español.',
  },

  // ----- Independencia -----
  {
    id: 'his-031', tema: 'independencia', dificultad: 2,
    enunciado: 'La Revolución de los Comuneros de 1781 estalló principalmente por:',
    opciones: [
      'El aumento de impuestos derivado de las reformas borbónicas',
      'La abolición de la esclavitud',
      'La expulsión de los jesuitas',
      'La independencia de Estados Unidos',
    ],
    correcta: 0,
    explicacion: 'Comenzó en El Socorro, Santander, y avanzó hacia Santafé. Las autoridades firmaron unas capitulaciones que luego desconocieron, y José Antonio Galán fue ejecutado.',
  },
  {
    id: 'his-032', tema: 'independencia', dificultad: 1,
    enunciado: '¿Qué ocurrió el 20 de julio de 1810 en Santafé de Bogotá?',
    opciones: [
      'Un altercado por un florero sirvió de detonante para formar una junta de gobierno',
      'Se firmó el acta de independencia definitiva de España',
      'Se libró la batalla decisiva contra el ejército español',
      'Se proclamó la creación de la Gran Colombia',
    ],
    correcta: 0,
    explicacion: 'La junta juró inicialmente fidelidad a Fernando VII, así que ese día no se rompió del todo con España. La independencia se consolidó nueve años después.',
  },
  {
    id: 'his-033', tema: 'independencia', dificultad: 2,
    enunciado: 'Se conoce como Patria Boba al periodo 1810-1816 porque:',
    opciones: [
      'Los patriotas se enfrentaron entre sí por el modelo de Estado, federalista o centralista, y llegaron divididos a la reconquista',
      'No hubo ningún gobierno organizado',
      'Los españoles gobernaron sin oposición',
      'La población se negó a participar en política',
    ],
    correcta: 0,
    explicacion: 'Hubo guerra civil entre las provincias federalistas y el centralismo de Cundinamarca. Esa división facilitó la reconquista española de 1816.',
  },
  {
    id: 'his-034', tema: 'independencia', dificultad: 2,
    enunciado: 'La Reconquista española de 1816, encabezada por Pablo Morillo, se recuerda como:',
    opciones: [
      'El Régimen del Terror, por los fusilamientos de líderes criollos',
      'Un periodo de amnistía general',
      'La firma de la paz con los patriotas',
      'El inicio del federalismo',
    ],
    correcta: 0,
    explicacion: 'Fueron ejecutados Camilo Torres, Francisco José de Caldas y Policarpa Salavarrieta, entre muchos otros. La represión terminó fortaleciendo la causa independentista.',
  },
  {
    id: 'his-035', tema: 'independencia', dificultad: 3,
    enunciado: 'La Campaña Libertadora de 1819 incluyó una maniobra decisiva:',
    opciones: [
      'El paso del ejército por los llanos y el páramo de Pisba, que los españoles creían imposible',
      'Un desembarco por la costa Caribe',
      'Un ataque naval sobre Cartagena',
      'Una alianza militar con Estados Unidos',
    ],
    correcta: 0,
    explicacion: 'Cruzar la cordillera en plena temporada de lluvias costó muchas bajas, pero permitió sorprender al ejército realista por la retaguardia.',
  },
  {
    id: 'his-036', tema: 'independencia', dificultad: 1,
    enunciado: '¿En qué fecha se libró la Batalla de Boyacá, que selló la independencia de la Nueva Granada?',
    opciones: ['7 de agosto de 1819', '20 de julio de 1810', '7 de agosto de 1810', '24 de junio de 1821'],
    correcta: 0,
    explicacion: 'Tres días después, el ejército libertador entró en Santafé. El 24 de junio de 1821 fue la Batalla de Carabobo, en Venezuela.',
  },
  {
    id: 'his-037', tema: 'independencia', dificultad: 2,
    enunciado: 'El Congreso de Angostura, en 1819, proclamó la creación de:',
    opciones: [
      'La República de Colombia, conocida hoy como la Gran Colombia',
      'La Confederación Granadina',
      'Los Estados Unidos de Colombia',
      'La República de la Nueva Granada',
    ],
    correcta: 0,
    explicacion: 'Reunía los actuales territorios de Colombia, Venezuela, Ecuador y Panamá. El nombre "Gran Colombia" lo usaron después los historiadores para distinguirla.',
  },
  {
    id: 'his-038', tema: 'independencia', dificultad: 2,
    enunciado: 'La Gran Colombia se disolvió alrededor de 1830 debido sobre todo a:',
    opciones: [
      'Las tensiones regionales y las diferencias entre proyectos centralistas y federalistas',
      'Una invasión extranjera',
      'La falta de población en su territorio',
      'La decisión de la Corona española',
    ],
    correcta: 0,
    explicacion: 'Las enormes distancias, las economías regionales distintas y las rivalidades entre líderes hicieron inviable el proyecto. Venezuela y Ecuador se separaron.',
  },
  {
    id: 'his-039', tema: 'independencia', dificultad: 2,
    enunciado: 'Antonio Nariño es recordado en la historia de la independencia por:',
    opciones: [
      'Traducir y publicar la Declaración de los Derechos del Hombre y del Ciudadano en 1794',
      'Comandar la Batalla de Boyacá',
      'Presidir el Congreso de Angostura',
      'Fundar el Partido Conservador',
    ],
    correcta: 0,
    explicacion: 'La publicación le costó la cárcel y el destierro. Difundir esas ideas fue, en su momento, un acto político de primer orden.',
  },
  {
    id: 'his-040', tema: 'independencia', dificultad: 3,
    enunciado: '¿Por qué la independencia no significó un cambio inmediato en la estructura social?',
    opciones: [
      'Porque la esclavitud continuó por décadas y el poder económico siguió en manos de las mismas élites criollas',
      'Porque la población indígena pasó a gobernar el país',
      'Porque España mantuvo el control administrativo',
      'Porque se repartió la tierra entre los campesinos',
    ],
    correcta: 0,
    explicacion: 'Cambió quién gobernaba, no cómo estaba organizada la sociedad. La abolición definitiva de la esclavitud llegó en 1851, treinta años después de Boyacá.',
  },

  // ----- La república del siglo XIX -----
  {
    id: 'his-041', tema: 'siglo-xix', dificultad: 3,
    enunciado: 'El país cambió varias veces de nombre durante el siglo XIX. ¿Cuál es el orden correcto?',
    opciones: [
      'Nueva Granada, Confederación Granadina, Estados Unidos de Colombia, República de Colombia',
      'República de Colombia, Nueva Granada, Confederación Granadina, Estados Unidos de Colombia',
      'Estados Unidos de Colombia, Nueva Granada, República de Colombia, Confederación Granadina',
      'Confederación Granadina, República de Colombia, Nueva Granada, Estados Unidos de Colombia',
    ],
    correcta: 0,
    explicacion: 'Cada nombre corresponde a una constitución distinta. El nombre actual quedó fijado con la Constitución de 1886.',
  },
  {
    id: 'his-042', tema: 'siglo-xix', dificultad: 2,
    enunciado: 'El principal eje de conflicto político del siglo XIX colombiano fue:',
    opciones: [
      'La disputa entre federalismo y centralismo, unida al papel de la Iglesia en el Estado',
      'La política exterior frente a Europa',
      'El reparto de las zonas pesqueras',
      'La elección entre monarquía y república',
    ],
    correcta: 0,
    explicacion: 'Ese doble eje —cómo organizar el territorio y qué papel dar a la Iglesia— está detrás de casi todas las guerras civiles del periodo.',
  },
  {
    id: 'his-043', tema: 'siglo-xix', dificultad: 2,
    enunciado: 'La Constitución de Rionegro de 1863 se caracterizó por:',
    opciones: [
      'Establecer un federalismo radical con estados soberanos y periodos presidenciales de dos años',
      'Implantar un centralismo fuerte',
      'Declarar la religión católica como oficial',
      'Crear la Corte Constitucional',
    ],
    correcta: 0,
    explicacion: 'Dio origen a los Estados Unidos de Colombia. Su extrema descentralización y los cortos mandatos son las razones por las que se le criticó tanta inestabilidad.',
  },
  {
    id: 'his-044', tema: 'siglo-xix', dificultad: 2,
    enunciado: 'La Regeneración, liderada por Rafael Núñez, dio lugar a la Constitución de 1886, que:',
    opciones: [
      'Restableció el centralismo y reconoció un papel privilegiado a la Iglesia católica',
      'Profundizó el federalismo de Rionegro',
      'Abolió la presidencia de la república',
      'Separó por completo la Iglesia del Estado',
    ],
    correcta: 0,
    explicacion: 'Estuvo vigente más de un siglo, hasta 1991. Su lema era "centralización política y descentralización administrativa".',
  },
  {
    id: 'his-045', tema: 'siglo-xix', dificultad: 2,
    enunciado: '¿En qué año se abolió definitivamente la esclavitud en Colombia?',
    opciones: ['1851', '1819', '1886', '1810'],
    correcta: 0,
    explicacion: 'La ley se expidió bajo el gobierno de José Hilario López y entró en vigor el 1 de enero de 1852. Antes existía la libertad de vientres, que liberaba a los hijos pero no a las madres.',
  },
  {
    id: 'his-046', tema: 'siglo-xix', dificultad: 2,
    enunciado: 'Los partidos Liberal y Conservador se formaron en Colombia hacia:',
    opciones: [
      'Mediados del siglo XIX, alrededor de 1848 y 1849',
      'Inmediatamente después de la independencia, en 1819',
      'A comienzos del siglo XX',
      'Durante el Frente Nacional',
    ],
    correcta: 0,
    explicacion: 'Están entre los partidos políticos más antiguos de América. Su rivalidad estructuró la vida política del país durante más de un siglo.',
  },
  {
    id: 'his-047', tema: 'siglo-xix', dificultad: 3,
    enunciado: 'Durante el siglo XIX la economía colombiana dependió de exportaciones sucesivas. El orden aproximado fue:',
    opciones: [
      'Tabaco, quina y añil, y hacia el final del siglo, café',
      'Café, petróleo y carbón',
      'Banano, algodón y flores',
      'Oro, esmeraldas y níquel únicamente',
    ],
    correcta: 0,
    explicacion: 'Cada bonanza duraba unos años y luego caía por competencia externa o por agotamiento. El café resultó más estable y transformó la sociedad rural del occidente del país.',
  },
  {
    id: 'his-048', tema: 'siglo-xix', dificultad: 2,
    enunciado: 'El Concordato firmado en 1887 con la Santa Sede establecía, entre otras cosas, que:',
    opciones: [
      'La educación pública debía impartirse conforme a la religión católica',
      'La Iglesia perdía todos sus bienes',
      'Se establecía la libertad de cultos plena',
      'El Estado dejaba de reconocer el matrimonio religioso',
    ],
    correcta: 0,
    explicacion: 'Fue una pieza central de la Regeneración. La Constitución de 1991 cambió ese marco al declarar la libertad de cultos y el carácter no confesional del Estado.',
  },
  {
    id: 'his-049', tema: 'siglo-xix', dificultad: 3,
    enunciado: '¿Por qué la expansión del café transformó la sociedad rural colombiana?',
    opciones: [
      'Porque se produjo en buena parte en pequeñas y medianas fincas familiares, creando una clase de propietarios rurales',
      'Porque concentró toda la tierra en pocas manos',
      'Porque se cultivaba exclusivamente en la costa Caribe',
      'Porque no requería mano de obra',
    ],
    correcta: 0,
    explicacion: 'La colonización antioqueña extendió ese modelo por el occidente del país. Esa estructura de propiedad distingue al café colombiano de otras economías de plantación.',
  },
  {
    id: 'his-050', tema: 'siglo-xix', dificultad: 2,
    enunciado: 'Las guerras civiles del siglo XIX colombiano fueron:',
    opciones: [
      'Numerosas, en su mayoría entre liberales y conservadores por el modelo de Estado',
      'Un único conflicto contra España',
      'Guerras contra países vecinos por territorios',
      'Inexistentes: el siglo fue pacífico',
    ],
    correcta: 0,
    explicacion: 'Hubo cerca de una decena de guerras civiles de alcance nacional, además de conflictos regionales. La última y más devastadora fue la de los Mil Días.',
  },

  // ----- 1900-1930 -----
  {
    id: 'his-051', tema: 'siglo-xx-inicio', dificultad: 2,
    enunciado: 'La Guerra de los Mil Días se desarrolló entre:',
    opciones: ['1899 y 1902', '1885 y 1888', '1910 y 1913', '1930 y 1933'],
    correcta: 0,
    explicacion: 'Enfrentó a liberales y conservadores y dejó el país arruinado y con decenas de miles de muertos. Terminó con los tratados de Neerlandia y Wisconsin.',
  },
  {
    id: 'his-052', tema: 'siglo-xx-inicio', dificultad: 2,
    enunciado: 'La separación de Panamá de Colombia ocurrió en:',
    opciones: ['1903', '1899', '1910', '1921'],
    correcta: 0,
    explicacion: 'Se produjo poco después de la Guerra de los Mil Días, en el contexto de la negociación del canal interoceánico y con apoyo de Estados Unidos.',
  },
  {
    id: 'his-053', tema: 'siglo-xx-inicio', dificultad: 3,
    enunciado: '¿Qué factores confluyeron en la separación de Panamá?',
    opciones: [
      'El interés de Estados Unidos en el canal, el rechazo del tratado en el Congreso colombiano y el aislamiento del istmo tras la guerra',
      'Una invasión europea del istmo',
      'Un plebiscito organizado por Colombia',
      'La quiebra del comercio panameño',
    ],
    correcta: 0,
    explicacion: 'El Congreso colombiano no aprobó el tratado Herrán-Hay, y poco después se produjo la separación. Colombia reconoció la situación años más tarde, con una indemnización de por medio.',
  },
  {
    id: 'his-054', tema: 'siglo-xx-inicio', dificultad: 2,
    enunciado: 'Se conoce como Hegemonía Conservadora al periodo en que ese partido gobernó de manera continua entre:',
    opciones: ['1886 y 1930', '1930 y 1946', '1958 y 1974', '1902 y 1910'],
    correcta: 0,
    explicacion: 'Terminó con la elección de Enrique Olaya Herrera en 1930, que abrió la llamada República Liberal.',
  },
  {
    id: 'his-055', tema: 'siglo-xx-inicio', dificultad: 2,
    enunciado: 'La llamada "danza de los millones" en los años veinte se refiere a:',
    opciones: [
      'La entrada masiva de recursos por la indemnización de Panamá, los empréstitos y la bonanza cafetera',
      'La inflación desbocada de la posguerra',
      'Una crisis bancaria nacional',
      'El auge del contrabando',
    ],
    correcta: 0,
    explicacion: 'Ese dinero financió obras públicas y ferrocarriles y aceleró la urbanización. La crisis mundial de 1929 cortó el flujo de golpe.',
  },
  {
    id: 'his-056', tema: 'siglo-xx-inicio', dificultad: 2,
    enunciado: 'La masacre de las bananeras, ocurrida en 1928 en Ciénaga, Magdalena, se produjo:',
    opciones: [
      'Durante una huelga de trabajadores de las plantaciones bananeras',
      'En el marco de una guerra con un país vecino',
      'Tras un terremoto que devastó la zona',
      'Durante una elección presidencial',
    ],
    correcta: 0,
    explicacion: 'Los trabajadores reclamaban contratos escritos y mejores condiciones laborales. El número de víctimas sigue siendo objeto de debate histórico, y el episodio aparece recreado en "Cien años de soledad".',
  },
  {
    id: 'his-057', tema: 'siglo-xx-inicio', dificultad: 2,
    enunciado: 'El Banco de la República fue creado en 1923 como resultado de:',
    opciones: [
      'Las recomendaciones de la misión Kemmerer, que reorganizó las finanzas públicas',
      'Un acuerdo con la banca europea tras la independencia',
      'Una decisión de la Asamblea Constituyente de 1991',
      'La nacionalización de la banca privada',
    ],
    correcta: 0,
    explicacion: 'La misión también dio origen a la Contraloría y a la Superintendencia Bancaria. Fue un esfuerzo por dotar al país de instituciones económicas modernas.',
  },
  {
    id: 'his-058', tema: 'siglo-xx-inicio', dificultad: 2,
    enunciado: 'Las primeras décadas del siglo XX vieron el surgimiento en Colombia de:',
    opciones: [
      'Un movimiento obrero organizado, con sindicatos y huelgas',
      'La desaparición de la agricultura',
      'El fin de los partidos políticos tradicionales',
      'La industrialización completa del país',
    ],
    correcta: 0,
    explicacion: 'Trabajadores del petróleo, del transporte fluvial, de los ferrocarriles y de las bananeras protagonizaron las primeras grandes huelgas.',
  },
  {
    id: 'his-059', tema: 'siglo-xx-inicio', dificultad: 3,
    enunciado: '¿Cómo afectó a Colombia la crisis mundial de 1929?',
    opciones: [
      'Cayeron el precio del café y el crédito externo, lo que contribuyó al fin de la Hegemonía Conservadora',
      'No tuvo ningún efecto por el aislamiento del país',
      'Provocó una bonanza exportadora',
      'Llevó al país a una guerra internacional',
    ],
    correcta: 0,
    explicacion: 'Una economía que dependía de un solo producto de exportación quedó muy expuesta. El desgaste económico se sumó a la división interna del conservatismo.',
  },
  {
    id: 'his-060', tema: 'siglo-xx-inicio', dificultad: 2,
    enunciado: 'Durante las primeras décadas del siglo XX, la población colombiana:',
    opciones: [
      'Comenzó a concentrarse en las ciudades, aunque seguía siendo mayoritariamente rural',
      'Era ya mayoritariamente urbana desde 1900',
      'Disminuyó de forma sostenida',
      'Se mantuvo estable sin migraciones internas',
    ],
    correcta: 0,
    explicacion: 'El vuelco definitivo hacia lo urbano se dio a mediados de siglo, acelerado por la violencia y por la industrialización.',
  },

  // ----- República Liberal, Bogotazo y La Violencia -----
  {
    id: 'his-061', tema: 'republica-violencia', dificultad: 2,
    enunciado: 'La llamada República Liberal corresponde al periodo:',
    opciones: ['1930-1946', '1886-1930', '1958-1974', '1948-1958'],
    correcta: 0,
    explicacion: 'Comenzó con Enrique Olaya Herrera y terminó con la elección de Mariano Ospina Pérez, en una elección con el liberalismo dividido.',
  },
  {
    id: 'his-062', tema: 'republica-violencia', dificultad: 2,
    enunciado: 'La "Revolución en Marcha" de Alfonso López Pumarejo incluyó:',
    opciones: [
      'La reforma constitucional de 1936, que introdujo la función social de la propiedad y amplió la intervención del Estado',
      'La disolución del Congreso',
      'El regreso al federalismo',
      'La privatización de la educación',
    ],
    correcta: 0,
    explicacion: 'También impulsó la Ley 200 de 1936 sobre tierras y amplió derechos laborales. Fue el intento más ambicioso de modernización social de la primera mitad del siglo.',
  },
  {
    id: 'his-063', tema: 'republica-violencia', dificultad: 2,
    enunciado: 'La Ley 200 de 1936 buscaba:',
    opciones: [
      'Regular la propiedad de la tierra estableciendo que debía cumplir una función social',
      'Nacionalizar las minas de oro',
      'Prohibir los sindicatos agrarios',
      'Entregar tierras a empresas extranjeras',
    ],
    correcta: 0,
    explicacion: 'Introducía la idea de que la tierra sin explotar podía revertir al Estado. Su aplicación fue limitada y el problema agrario siguió sin resolverse.',
  },
  {
    id: 'his-064', tema: 'republica-violencia', dificultad: 2,
    enunciado: 'El voto femenino se aprobó en Colombia en 1954 y las mujeres lo ejercieron por primera vez en:',
    opciones: [
      'El plebiscito de 1957',
      'Las elecciones presidenciales de 1946',
      'Las elecciones de 1930',
      'El referendo de 1991',
    ],
    correcta: 0,
    explicacion: 'Colombia fue uno de los últimos países de la región en reconocerlo. El plebiscito que aprobó el Frente Nacional fue la primera votación con participación femenina.',
  },
  {
    id: 'his-065', tema: 'republica-violencia', dificultad: 1,
    enunciado: '¿Qué ocurrió el 9 de abril de 1948 en Bogotá?',
    opciones: [
      'El asesinato de Jorge Eliécer Gaitán desató una revuelta conocida como el Bogotazo',
      'Se firmó la Constitución vigente',
      'Se inauguró el Frente Nacional',
      'Se produjo la separación de Panamá',
    ],
    correcta: 0,
    explicacion: 'Gaitán era el líder liberal con mayor respaldo popular y favorito para la presidencia. La revuelta destruyó buena parte del centro de la ciudad y marcó el inicio de la etapa más aguda de La Violencia.',
  },
  {
    id: 'his-066', tema: 'republica-violencia', dificultad: 2,
    enunciado: 'Se conoce como La Violencia al periodo de enfrentamiento:',
    opciones: [
      'Bipartidista entre liberales y conservadores, sobre todo entre 1948 y 1958',
      'Entre el Estado y los carteles del narcotráfico en los años ochenta',
      'Entre Colombia y sus países vecinos',
      'Entre movimientos obreros e industriales',
    ],
    correcta: 0,
    explicacion: 'Se calcula que dejó más de doscientos mil muertos y afectó sobre todo al campo. Provocó un desplazamiento masivo hacia las ciudades.',
  },
  {
    id: 'his-067', tema: 'republica-violencia', dificultad: 2,
    enunciado: 'El general Gustavo Rojas Pinilla gobernó Colombia entre:',
    opciones: ['1953 y 1957', '1946 y 1950', '1958 y 1962', '1930 y 1934'],
    correcta: 0,
    explicacion: 'Llegó al poder mediante un golpe militar en un intento de frenar la violencia bipartidista. Durante su gobierno llegó la televisión al país y se aprobó el voto femenino.',
  },
  {
    id: 'his-068', tema: 'republica-violencia', dificultad: 3,
    enunciado: 'Una consecuencia demográfica duradera de La Violencia fue:',
    opciones: [
      'Un éxodo masivo del campo a las ciudades que aceleró la urbanización',
      'La despoblación de las grandes ciudades',
      'El aumento de la población rural',
      'La llegada de inmigración europea masiva',
    ],
    correcta: 0,
    explicacion: 'Cientos de miles de familias abandonaron sus tierras. El crecimiento desordenado de las ciudades y los cinturones de pobreza urbana tienen ahí una de sus raíces.',
  },
  {
    id: 'his-069', tema: 'republica-violencia', dificultad: 2,
    enunciado: 'El plebiscito de 1957 tuvo como propósito:',
    opciones: [
      'Aprobar el acuerdo entre liberales y conservadores que dio origen al Frente Nacional',
      'Elegir directamente al presidente de la república',
      'Aprobar una nueva constitución política',
      'Decidir sobre la separación de Panamá',
    ],
    correcta: 0,
    explicacion: 'Fue aprobado por una mayoría muy amplia, en la primera votación en la que participaron las mujeres.',
  },
  {
    id: 'his-070', tema: 'republica-violencia', dificultad: 3,
    enunciado: 'Además del conflicto partidista, un factor de fondo de La Violencia fue:',
    opciones: [
      'La disputa por la tierra y la ausencia de una reforma agraria efectiva',
      'La competencia por los recursos pesqueros',
      'La presión de potencias extranjeras por el canal',
      'La escasez de mano de obra en las ciudades',
    ],
    correcta: 0,
    explicacion: 'Detrás de las banderas de partido había despojo y concentración de la propiedad rural. Ese problema agrario no resuelto reaparece en los conflictos posteriores.',
  },

  // ----- Frente Nacional -----
  {
    id: 'his-071', tema: 'frente-nacional', dificultad: 2,
    enunciado: 'El Frente Nacional (1958-1974) consistió en un acuerdo mediante el cual liberales y conservadores:',
    opciones: [
      'Se alternaban la presidencia y repartían por mitades los cargos públicos',
      'Se fusionaban en un solo partido',
      'Cedían el gobierno a los militares',
      'Convocaban elecciones sin restricciones',
    ],
    correcta: 0,
    explicacion: 'La alternancia y la paridad buscaban acabar con la violencia bipartidista, y en eso tuvieron un éxito considerable.',
  },
  {
    id: 'his-072', tema: 'frente-nacional', dificultad: 3,
    enunciado: '¿Cuál fue la principal crítica al Frente Nacional?',
    opciones: [
      'Que cerró el sistema político a las fuerzas distintas de los dos partidos tradicionales',
      'Que permitió el regreso de la monarquía',
      'Que eliminó el Congreso de la República',
      'Que entregó el poder a las Fuerzas Armadas',
    ],
    correcta: 0,
    explicacion: 'Quien no militara en uno de los dos partidos quedaba fuera del reparto. Varios analistas relacionan esa exclusión con el surgimiento de movimientos armados en el mismo periodo.',
  },
  {
    id: 'his-073', tema: 'frente-nacional', dificultad: 2,
    enunciado: 'Las FARC y el ELN surgieron en Colombia alrededor de:',
    opciones: ['1964', '1948', '1991', '1978'],
    correcta: 0,
    explicacion: 'Nacieron en pleno Frente Nacional, en un contexto de conflicto agrario, exclusión política y la influencia de la Revolución cubana. El EPL apareció en 1967 y el M-19 en 1970.',
  },
  {
    id: 'his-074', tema: 'frente-nacional', dificultad: 2,
    enunciado: 'El movimiento guerrillero M-19 tomó su nombre de:',
    opciones: [
      'Las elecciones del 19 de abril de 1970, cuyo resultado sus fundadores consideraron fraudulento',
      'La fecha de la independencia nacional',
      'Un tratado internacional firmado ese día',
      'El número de sus fundadores',
    ],
    correcta: 0,
    explicacion: 'En esas elecciones se enfrentaron Misael Pastrana y Gustavo Rojas Pinilla. La denuncia de fraude fue el detonante del movimiento, que se declaraba nacionalista y urbano.',
  },
  {
    id: 'his-075', tema: 'frente-nacional', dificultad: 2,
    enunciado: 'El INCORA, creado en 1961, tenía como función:',
    opciones: [
      'Adelantar la reforma agraria y titular tierras a campesinos',
      'Administrar el sistema de salud',
      'Regular el comercio exterior',
      'Construir la red de carreteras',
    ],
    correcta: 0,
    explicacion: 'Sus resultados fueron limitados frente a la magnitud del problema, en buena parte por la oposición de los grandes propietarios.',
  },
  {
    id: 'his-076', tema: 'frente-nacional', dificultad: 2,
    enunciado: 'El paro cívico nacional de 1977 fue:',
    opciones: [
      'Una gran movilización sindical y popular contra el costo de vida',
      'Una huelga exclusiva de los trabajadores del petróleo',
      'Una protesta contra la Constitución de 1991',
      'Una manifestación a favor del Frente Nacional',
    ],
    correcta: 0,
    explicacion: 'Convocado por las centrales obreras, es una de las protestas más grandes de la historia del país y mostró el descontento social acumulado.',
  },
  {
    id: 'his-077', tema: 'frente-nacional', dificultad: 3,
    enunciado: 'La llamada bonanza marimbera de los años setenta se refiere a:',
    opciones: [
      'El auge del cultivo y la exportación ilegal de marihuana, sobre todo desde la costa Caribe',
      'Una bonanza de exportación de café',
      'El descubrimiento de yacimientos de esmeraldas',
      'La llegada masiva de turistas al Caribe',
    ],
    correcta: 0,
    explicacion: 'Fue el antecedente del narcotráfico a gran escala: dejó rutas, redes y capitales que en los años ochenta se volcaron hacia la cocaína.',
  },
  {
    id: 'his-078', tema: 'frente-nacional', dificultad: 2,
    enunciado: 'Durante el Frente Nacional, el país experimentó:',
    opciones: [
      'Un rápido crecimiento urbano y la expansión de la educación y los servicios públicos',
      'Un retroceso de la urbanización',
      'La desaparición del sector industrial',
      'El cierre de las universidades públicas',
    ],
    correcta: 0,
    explicacion: 'Hubo modernización económica y social junto con el cierre del sistema político: es la paradoja característica del periodo.',
  },
  {
    id: 'his-079', tema: 'frente-nacional', dificultad: 2,
    enunciado: 'El Frente Nacional terminó formalmente en:',
    opciones: ['1974', '1970', '1978', '1982'],
    correcta: 0,
    explicacion: 'Con la elección de Alfonso López Michelsen se retomó la competencia electoral abierta, aunque el reparto burocrático se mantuvo algunos años más.',
  },
  {
    id: 'his-080', tema: 'frente-nacional', dificultad: 3,
    enunciado: 'Un balance equilibrado del Frente Nacional señala que:',
    opciones: [
      'Redujo drásticamente la violencia entre los partidos, pero al costo de cerrar el sistema a nuevas fuerzas políticas',
      'Fracasó por completo en todos sus objetivos',
      'Resolvió el problema agrario del país',
      'Eliminó cualquier forma de oposición armada',
    ],
    correcta: 0,
    explicacion: 'Las dos cosas son ciertas a la vez, y por eso el periodo se sigue discutiendo. Juzgar un proceso histórico exige sostener sus resultados contradictorios al mismo tiempo.',
  },

  // ----- Conflicto armado, narcotráfico y Constitución de 1991 -----
  {
    id: 'his-081', tema: 'conflicto-constitucion', dificultad: 2,
    enunciado: 'Durante los años ochenta, el narcotráfico en Colombia se caracterizó por:',
    opciones: [
      'La consolidación de grandes organizaciones como los carteles de Medellín y Cali',
      'La producción exclusiva de marihuana',
      'La ausencia de violencia asociada',
      'El control estatal de las exportaciones',
    ],
    correcta: 0,
    explicacion: 'Esas organizaciones combinaron la exportación de cocaína con la corrupción de instituciones y una violencia sin precedentes contra jueces, periodistas y candidatos.',
  },
  {
    id: 'his-082', tema: 'conflicto-constitucion', dificultad: 2,
    enunciado: 'La toma y retoma del Palacio de Justicia ocurrió en:',
    opciones: [
      'Noviembre de 1985, por parte del M-19 y la posterior operación militar',
      'Abril de 1948, durante el Bogotazo',
      'Julio de 1991, durante la Constituyente',
      'Enero de 1974, al final del Frente Nacional',
    ],
    correcta: 0,
    explicacion: 'Murieron magistrados de la Corte Suprema, funcionarios, visitantes y guerrilleros, y hubo personas desaparecidas. Varios aspectos del episodio siguen en investigación judicial.',
  },
  {
    id: 'his-083', tema: 'conflicto-constitucion', dificultad: 3,
    enunciado: 'Entre 1989 y 1990 fueron asesinados varios candidatos presidenciales, entre ellos:',
    opciones: [
      'Luis Carlos Galán, Bernardo Jaramillo y Carlos Pizarro',
      'Jorge Eliécer Gaitán y Rafael Uribe Uribe',
      'Rafael Núñez y Miguel Antonio Caro',
      'Alfonso López Pumarejo y Eduardo Santos',
    ],
    correcta: 0,
    explicacion: 'Esa secuencia de magnicidios marcó el momento más crítico de la crisis institucional y fue uno de los impulsos del movimiento que llevó a la Constituyente.',
  },
  {
    id: 'his-084', tema: 'conflicto-constitucion', dificultad: 2,
    enunciado: 'El movimiento de la Séptima Papeleta, en 1990, consistió en:',
    opciones: [
      'Una iniciativa estudiantil que promovió incluir un voto adicional para convocar una asamblea constituyente',
      'Una propuesta para eliminar el Congreso',
      'Un referendo sobre la extradición',
      'Una campaña por el voto en blanco',
    ],
    correcta: 0,
    explicacion: 'La papeleta no estaba prevista oficialmente, pero el respaldo ciudadano llevó a que se contara y abriera el camino a la Asamblea Nacional Constituyente.',
  },
  {
    id: 'his-085', tema: 'conflicto-constitucion', dificultad: 2,
    enunciado: 'La Constitución Política de Colombia actualmente vigente fue promulgada en:',
    opciones: ['1991', '1886', '1936', '2002'],
    correcta: 0,
    explicacion: 'Reemplazó a la de 1886, que había durado más de un siglo. La redactó una asamblea elegida popularmente, con participación de fuerzas políticas diversas.',
  },
  {
    id: 'his-086', tema: 'conflicto-constitucion', dificultad: 2,
    enunciado: '¿Cuál de estas es una novedad introducida por la Constitución de 1991?',
    opciones: [
      'La acción de tutela y la creación de la Corte Constitucional',
      'La creación del Congreso bicameral',
      'La separación de las tres ramas del poder',
      'El establecimiento del servicio militar',
    ],
    correcta: 0,
    explicacion: 'También definió a Colombia como Estado social de derecho, reconoció su carácter pluriétnico y multicultural y creó la Fiscalía y la Defensoría del Pueblo.',
  },
  {
    id: 'his-087', tema: 'conflicto-constitucion', dificultad: 2,
    enunciado: 'El M-19 participó en la Asamblea Nacional Constituyente de 1991 porque:',
    opciones: [
      'Se había desmovilizado y convertido en partido político tras un acuerdo de paz',
      'Ocupó militarmente la sede de la asamblea',
      'Fue invitado por la comunidad internacional sin dejar las armas',
      'Ganó las elecciones presidenciales de 1990',
    ],
    correcta: 0,
    explicacion: 'Su desmovilización, en 1990, es el antecedente de paz más citado. Su líder Carlos Pizarro fue asesinado poco después, ya como candidato presidencial.',
  },
  {
    id: 'his-088', tema: 'conflicto-constitucion', dificultad: 3,
    enunciado: 'El paramilitarismo en Colombia surgió inicialmente como:',
    opciones: [
      'Grupos armados privados creados para enfrentar a las guerrillas, que luego se expandieron y cometieron graves crímenes',
      'Un cuerpo oficial de la fuerza pública',
      'Un movimiento estudiantil urbano',
      'Una organización sindical campesina',
    ],
    correcta: 0,
    explicacion: 'Se expandieron en alianza con actores locales y con financiación del narcotráfico. Las AUC se desmovilizaron entre 2003 y 2006 en el marco de la Ley de Justicia y Paz.',
  },
  {
    id: 'his-089', tema: 'conflicto-constitucion', dificultad: 3,
    enunciado: 'El desplazamiento forzado interno en Colombia es relevante porque:',
    opciones: [
      'Es el hecho victimizante que más personas ha afectado en el conflicto armado',
      'Solo ocurrió durante los años cincuenta',
      'Afectó exclusivamente a las grandes ciudades',
      'Fue un fenómeno voluntario de migración económica',
    ],
    correcta: 0,
    explicacion: 'El Registro Único de Víctimas contabiliza varios millones de personas desplazadas. Es la razón por la que Colombia figura entre los países con más desplazados internos del mundo.',
  },
  {
    id: 'his-090', tema: 'conflicto-constitucion', dificultad: 2,
    enunciado: 'La elección popular de alcaldes en Colombia comenzó en:',
    opciones: ['1988', '1991', '1974', '2002'],
    correcta: 0,
    explicacion: 'Antes los nombraban los gobernadores, designados a su vez por el presidente. Fue un primer paso de descentralización que la Constitución de 1991 amplió con la elección de gobernadores.',
  },

  // ----- Colombia reciente -----
  {
    id: 'his-091', tema: 'colombia-reciente', dificultad: 2,
    enunciado: 'El acuerdo de paz entre el Estado colombiano y las FARC-EP se firmó en:',
    opciones: ['2016', '2002', '1991', '2010'],
    correcta: 0,
    explicacion: 'Las negociaciones se desarrollaron en La Habana desde 2012 y cubrieron desarrollo rural, participación política, drogas, víctimas y fin del conflicto.',
  },
  {
    id: 'his-092', tema: 'colombia-reciente', dificultad: 3,
    enunciado: 'En el plebiscito de octubre de 2016 sobre el acuerdo de paz:',
    opciones: [
      'Ganó el No por un margen muy estrecho, tras lo cual el acuerdo se renegoció y fue refrendado por el Congreso',
      'Ganó el Sí de forma amplia y el acuerdo entró en vigor de inmediato',
      'No se alcanzó el umbral de participación y se repitió la votación',
      'El resultado fue anulado por la Corte Constitucional',
    ],
    correcta: 0,
    explicacion: 'La diferencia fue inferior al medio punto porcentual y la abstención superó el 60 %. Tras ajustes al texto, el Congreso lo refrendó ese mismo año.',
  },
  {
    id: 'his-093', tema: 'colombia-reciente', dificultad: 2,
    enunciado: 'La Jurisdicción Especial para la Paz (JEP) tiene como función:',
    opciones: [
      'Investigar y juzgar los delitos más graves cometidos en el marco del conflicto armado',
      'Administrar el presupuesto de las víctimas',
      'Reemplazar a la Corte Constitucional',
      'Resolver los litigios comerciales del Estado',
    ],
    correcta: 0,
    explicacion: 'Forma parte del Sistema Integral de Verdad, Justicia, Reparación y No Repetición, junto con la Comisión de la Verdad y la Unidad de Búsqueda de Personas Desaparecidas.',
  },
  {
    id: 'his-094', tema: 'colombia-reciente', dificultad: 2,
    enunciado: 'La Ley de Víctimas y Restitución de Tierras, expedida en 2011, buscaba:',
    opciones: [
      'Reconocer, reparar a las víctimas del conflicto y devolver las tierras despojadas',
      'Amnistiar a todos los actores armados',
      'Privatizar los baldíos de la nación',
      'Crear un nuevo impuesto a la tierra',
    ],
    correcta: 0,
    explicacion: 'Reconoció oficialmente la existencia de un conflicto armado y de víctimas con derechos, lo que constituyó un giro en la política del Estado.',
  },
  {
    id: 'his-095', tema: 'colombia-reciente', dificultad: 2,
    enunciado: 'Las Autodefensas Unidas de Colombia (AUC) se desmovilizaron entre 2003 y 2006 en el marco de:',
    opciones: [
      'La Ley de Justicia y Paz',
      'La Constitución de 1991',
      'El acuerdo de La Habana',
      'El plebiscito de 1957',
    ],
    correcta: 0,
    explicacion: 'La ley ofrecía penas alternativas a cambio de verdad y reparación. Tras la desmovilización surgieron grupos armados que el Estado denominó bandas criminales.',
  },
  {
    id: 'his-096', tema: 'colombia-reciente', dificultad: 2,
    enunciado: 'Desde mediados de la década de 2010, Colombia recibió una migración masiva proveniente de:',
    opciones: ['Venezuela', 'Argentina', 'Perú', 'Brasil'],
    correcta: 0,
    explicacion: 'Es la mayor recepción de migrantes de la historia reciente del país y motivó mecanismos especiales de regularización.',
  },
  {
    id: 'his-097', tema: 'colombia-reciente', dificultad: 3,
    enunciado: 'La Comisión de la Verdad, que entregó su informe final en 2022, tenía el mandato de:',
    opciones: [
      'Esclarecer lo ocurrido en el conflicto y promover el reconocimiento de las víctimas, sin funciones judiciales',
      'Juzgar y condenar a los responsables del conflicto',
      'Administrar las reparaciones económicas',
      'Reformar la Constitución',
    ],
    correcta: 0,
    explicacion: 'Es extrajudicial por diseño: sus conclusiones no producen condenas. Juzgar le corresponde a la JEP y a la justicia ordinaria.',
  },
  {
    id: 'his-098', tema: 'colombia-reciente', dificultad: 2,
    enunciado: 'Que la Constitución de 1991 reconozca a Colombia como un país pluriétnico y multicultural implica que:',
    opciones: [
      'Se reconocen los derechos de los pueblos indígenas y las comunidades afrodescendientes, raizales y rom',
      'Se declara una única cultura nacional oficial',
      'Se limita la libertad de cultos',
      'Se suprimen las lenguas indígenas de la educación',
    ],
    correcta: 0,
    explicacion: 'De ahí derivan las lenguas oficiales en sus territorios, la jurisdicción especial indígena y la consulta previa sobre proyectos que los afecten.',
  },
  {
    id: 'his-099', tema: 'colombia-reciente', dificultad: 3,
    enunciado: '¿Por qué se considera importante la memoria histórica en un país que atravesó un conflicto armado?',
    opciones: [
      'Porque reconocer lo ocurrido a las víctimas es condición para la reparación y para que los hechos no se repitan',
      'Porque permite castigar a toda la población responsable',
      'Porque sustituye la investigación judicial',
      'Porque borra los hechos dolorosos del pasado',
    ],
    correcta: 0,
    explicacion: 'La memoria no reemplaza a la justicia: la acompaña. El objetivo de no repetición es lo que distingue a una sociedad que procesa su pasado de una que lo silencia.',
  },
  {
    id: 'his-100', tema: 'colombia-reciente', dificultad: 3,
    enunciado: 'Al estudiar los hechos más recientes de la historia nacional, una precaución necesaria es:',
    opciones: [
      'Distinguir los hechos verificables de las interpretaciones en disputa y contrastar varias fuentes',
      'Aceptar la versión de la fuente más difundida',
      'Evitar por completo los temas recientes',
      'Basarse solo en testimonios personales',
    ],
    correcta: 0,
    explicacion: 'Cuanto más cercano es el hecho, menos decantada está su interpretación. Por eso el examen suele preguntar por lo comprobable y por la capacidad de identificar el punto de vista de una fuente.',
  },
];
