/**
 * ingles.js — Banco de inglés (nivel A2–B2, el que piden las pruebas de ingreso).
 *
 * Gramática, vocabulario y dos lecturas. Los enunciados de gramática van en
 * inglés, como en el examen; la explicación va en español, que es donde el
 * estudiante necesita entender la regla.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const LECTURAS_EN = [
  {
    id: 'en-t1',
    titulo: 'The library that lends drills',
    parrafos: [
      "Most people who buy an electric drill use it for about thirteen minutes in its entire life. The rest of the time it sits in a cupboard. In 1979, a small town in Ohio decided that this was a strange way to organise a neighbourhood, and opened the first tool library: a place where residents borrow a drill, a ladder or a sewing machine for a week, exactly as they would borrow a book.",
      "The idea spread slowly at first, and then much faster after 2008, when the financial crisis made people think twice before buying equipment they rarely needed. Today there are more than five hundred tool libraries around the world. Some are run by city councils; most are run by volunteers.",
      "The savings are obvious, but the librarians say the real benefit is different. Borrowers usually arrive without knowing how to use what they are taking home, so somebody has to show them. Tool libraries have become, almost by accident, places where people teach each other to repair things instead of replacing them.",
    ],
  },
  {
    id: 'en-t2',
    titulo: 'The city that pays you to cycle',
    parrafos: [
      "For three years, the French city of Strasbourg has been running an unusual experiment: employees who cycle to work receive a small payment for every kilometre they ride. The amount is modest, around twenty-five cents, and it is paid by the employer, who can then deduct it from taxes.",
      "The scheme was not designed to make anyone rich. Its aim was to change a habit. Transport researchers have known for years that people rarely abandon their cars because of information campaigns; they abandon them when an alternative becomes slightly more convenient, or slightly cheaper, than driving.",
      "The results have been encouraging but limited. Cycling to work rose by eleven per cent among the companies that joined, though the study could not determine how many of those cyclists had previously travelled by bus rather than by car. Critics argue that the money would achieve more if it were spent on protected bike lanes, which benefit everyone rather than only those who already work for a participating company.",
    ],
  },
];

export const INGLES = [
  // ----- Verb tenses -----
  {
    id: 'ing-001', tema: 'tiempos-verbales', dificultad: 1,
    enunciado: 'She ______ in London since 2019.',
    opciones: ['has lived', 'lives', 'lived', 'is living'],
    correcta: 0,
    explicacion: '"Since" marca el inicio de una acción que continúa hasta hoy: se usa present perfect (has/have + participio).',
    pista: 'since / for / already / yet piden present perfect.',
  },
  {
    id: 'ing-002', tema: 'tiempos-verbales', dificultad: 1,
    enunciado: 'Look! It ______ again.',
    opciones: ['is raining', 'rains', 'rained', 'has rained'],
    correcta: 0,
    explicacion: '"Look!" señala algo que ocurre en este momento: present continuous.',
  },
  {
    id: 'ing-003', tema: 'tiempos-verbales', dificultad: 2,
    enunciado: 'By the time we arrived, the film ______.',
    opciones: ['had already started', 'already started', 'has already started', 'was already starting'],
    correcta: 0,
    explicacion: 'Past perfect: una acción anterior a otra acción del pasado. Primero empezó la película, después llegamos.',
  },
  {
    id: 'ing-004', tema: 'tiempos-verbales', dificultad: 2,
    enunciado: 'He ______ television when the phone rang.',
    opciones: ['was watching', 'watched', 'has watched', 'is watching'],
    correcta: 0,
    explicacion: 'La acción larga que estaba en curso va en past continuous; la acción breve que la interrumpe, en past simple.',
  },
  {
    id: 'ing-005', tema: 'tiempos-verbales', dificultad: 2,
    enunciado: 'I ______ to Canada last summer, and I loved it.',
    opciones: ['went', 'have gone', 'had gone', 'was going'],
    correcta: 0,
    explicacion: '"Last summer" es un momento pasado terminado y concreto, así que corresponde past simple, no present perfect.',
  },
  {
    id: 'ing-006', tema: 'tiempos-verbales', dificultad: 3,
    enunciado: "Don\u0027t call at eight. We ______ dinner then.",
    opciones: ['will be having', 'will have', 'have', 'are having had'],
    correcta: 0,
    explicacion: 'Future continuous: una acción que estará en curso en un momento concreto del futuro.',
  },

  // ----- Conditionals -----
  {
    id: 'ing-007', tema: 'condicionales', dificultad: 1,
    enunciado: 'If I ______ you, I would apologise.',
    opciones: ['were', 'am', 'will be', 'had been'],
    correcta: 0,
    explicacion: 'Second conditional (situación hipotética): if + past simple + would. Con el verbo to be se usa "were" para todas las personas.',
  },
  {
    id: 'ing-008', tema: 'condicionales', dificultad: 2,
    enunciado: 'If she had studied harder, she ______ the exam.',
    opciones: ['would have passed', 'would pass', 'will pass', 'had passed'],
    correcta: 0,
    explicacion: 'Third conditional: habla de un pasado que ya no se puede cambiar. if + past perfect + would have + participio.',
  },
  {
    id: 'ing-009', tema: 'condicionales', dificultad: 1,
    enunciado: 'If you heat water to 100 °C, it ______.',
    opciones: ['boils', 'will boil', 'would boil', 'boiled'],
    correcta: 0,
    explicacion: 'Zero conditional: para hechos que siempre ocurren se usa present simple en las dos partes.',
  },
  {
    id: 'ing-010', tema: 'condicionales', dificultad: 3,
    enunciado: 'I wish I ______ play the piano.',
    opciones: ['could', 'can', 'will can', 'would can'],
    correcta: 0,
    explicacion: 'Después de "I wish", el verbo va un paso atrás en el tiempo; "can" se convierte en "could".',
  },

  // ----- Modal verbs -----
  {
    id: 'ing-011', tema: 'modales', dificultad: 1,
    enunciado: "You ______ smoke here. It's a hospital.",
    opciones: ["mustn't", "don't have to", "shouldn't have", "couldn't"],
    correcta: 0,
    explicacion: '"Mustn’t" expresa prohibición. Cuidado: "don’t have to" significa que no es necesario, no que esté prohibido.',
    pista: 'Prohibición y ausencia de obligación son cosas distintas.',
  },
  {
    id: 'ing-012', tema: 'modales', dificultad: 2,
    enunciado: "It's Sunday, so you ______ get up early.",
    opciones: ["don't have to", "mustn't", "couldn't", "shouldn't have"],
    correcta: 0,
    explicacion: 'No hay obligación de madrugar, pero tampoco está prohibido: "don’t have to".',
  },
  {
    id: 'ing-013', tema: 'modales', dificultad: 2,
    enunciado: 'He ______ be at home: his car is in the garage and the lights are on.',
    opciones: ['must', "can't", 'should', 'might not'],
    correcta: 0,
    explicacion: 'Deducción lógica con evidencia fuerte a favor: "must be". Si la evidencia fuera en contra se usaría "can’t be".',
  },
  {
    id: 'ing-014', tema: 'modales', dificultad: 3,
    enunciado: 'I ______ her the truth, but I was afraid of her reaction.',
    opciones: ['should have told', 'should tell', 'must have told', 'should have said'],
    correcta: 0,
    explicacion: '"Should have + participio" expresa arrepentimiento por algo que no se hizo. Además, se dice "tell somebody" y "say something": con el objeto "her" corresponde "tell".',
  },

  // ----- Passive voice -----
  {
    id: 'ing-015', tema: 'voz-pasiva', dificultad: 1,
    enunciado: 'The bridge ______ in 1890.',
    opciones: ['was built', 'was build', 'has built', 'built'],
    correcta: 0,
    explicacion: 'Pasiva en past simple: was/were + participio pasado. El participio de "build" es "built".',
  },
  {
    id: 'ing-016', tema: 'voz-pasiva', dificultad: 2,
    enunciado: 'Choose the passive form of: "Someone has stolen my bike."',
    opciones: ['My bike has been stolen.', 'My bike was stolen by someone.', 'My bike has stolen.', 'My bike is being stolen.'],
    correcta: 0,
    explicacion: 'El present perfect activo (has stolen) pasa a "has been + participio". El agente "someone" se omite por ser irrelevante.',
  },
  {
    id: 'ing-017', tema: 'voz-pasiva', dificultad: 2,
    enunciado: 'This room ______ every morning.',
    opciones: ['is cleaned', 'cleans', 'is cleaning', 'has cleaned'],
    correcta: 0,
    explicacion: 'La habitación recibe la acción, así que va en pasiva de present simple: is + participio.',
  },

  // ----- Reported speech -----
  {
    id: 'ing-018', tema: 'reported-speech', dificultad: 2,
    enunciado: 'He said: "I am very tired." → He said that he ______ very tired.',
    opciones: ['was', 'is', 'had been', 'would be'],
    correcta: 0,
    explicacion: 'En estilo indirecto el verbo retrocede un tiempo: present simple pasa a past simple.',
  },
  {
    id: 'ing-019', tema: 'reported-speech', dificultad: 3,
    enunciado: 'She asked: "Where do you live?" → She asked me where ______.',
    opciones: ['I lived', 'did I live', 'do I live', 'I did live'],
    correcta: 0,
    explicacion: 'En las preguntas reportadas se recupera el orden de una afirmación (sujeto + verbo) y desaparece el auxiliar "do".',
    pista: 'En reported questions no hay inversión ni signo de interrogación.',
  },
  {
    id: 'ing-020', tema: 'reported-speech', dificultad: 2,
    enunciado: 'He told me: "Close the door." → He told me ______ the door.',
    opciones: ['to close', 'close', 'closing', 'that close'],
    correcta: 0,
    explicacion: 'Las órdenes reportadas usan el infinitivo con "to": told me to close.',
  },

  // ----- Relative clauses -----
  {
    id: 'ing-021', tema: 'relativas', dificultad: 1,
    enunciado: 'The woman ______ lives next door is a doctor.',
    opciones: ['who', 'which', 'whose', 'where'],
    correcta: 0,
    explicacion: '"Who" se usa para personas y funciona como sujeto de la oración de relativo.',
  },
  {
    id: 'ing-022', tema: 'relativas', dificultad: 2,
    enunciado: "That's the village ______ my grandparents were born.",
    opciones: ['where', 'which', 'that', 'when'],
    correcta: 0,
    explicacion: '"Where" se usa para lugares cuando la relativa indica el sitio en el que ocurre algo.',
  },
  {
    id: 'ing-023', tema: 'relativas', dificultad: 2,
    enunciado: "This is the student ______ project won the prize.",
    opciones: ['whose', "who's", 'which', 'that'],
    correcta: 0,
    explicacion: '"Whose" indica posesión: el proyecto pertenece al estudiante. "Who’s" es la contracción de "who is".',
  },

  // ----- Prepositions -----
  {
    id: 'ing-024', tema: 'preposiciones', dificultad: 1,
    enunciado: "I'm very interested ______ learning Japanese.",
    opciones: ['in', 'on', 'for', 'about'],
    correcta: 0,
    explicacion: 'El adjetivo "interested" va siempre con "in", y después de preposición el verbo va en gerundio: interested in learning.',
  },
  {
    id: 'ing-025', tema: 'preposiciones', dificultad: 2,
    enunciado: "The meeting is ______ Monday ______ nine o\u0027clock.",
    opciones: ['on / at', 'in / on', 'at / in', 'on / in'],
    correcta: 0,
    explicacion: '"On" para días, "at" para horas exactas e "in" para meses, años y partes del día.',
  },
  {
    id: 'ing-026', tema: 'preposiciones', dificultad: 2,
    enunciado: "She's really good ______ solving problems under pressure.",
    opciones: ['at', 'in', 'on', 'with'],
    correcta: 0,
    explicacion: '"Good at" es la combinación fija para hablar de habilidad.',
  },

  // ----- Articles and quantifiers -----
  {
    id: 'ing-027', tema: 'cuantificadores', dificultad: 1,
    enunciado: "There isn't ______ milk left in the fridge.",
    opciones: ['much', 'many', 'a few', 'several'],
    correcta: 0,
    explicacion: '"Milk" es incontable, así que lleva "much". "Many" y "a few" acompañan a contables.',
  },
  {
    id: 'ing-028', tema: 'cuantificadores', dificultad: 2,
    enunciado: "I have ______ friends in Chile, so I'm going to visit them.",
    opciones: ['a few', 'a little', 'much', 'few'],
    correcta: 0,
    explicacion: '"A few" (algunos, contable) tiene sentido positivo. "Few" sin artículo significa "casi ninguno" y contradice la segunda parte de la frase.',
  },
  {
    id: 'ing-029', tema: 'cuantificadores', dificultad: 3,
    enunciado: '______ Mount Everest is in ______ Himalayas.',
    opciones: ['— / the', 'The / the', '— / —', 'The / —'],
    correcta: 0,
    explicacion: 'Las montañas aisladas van sin artículo, pero las cordilleras lo llevan: Mount Everest, the Himalayas, the Andes.',
  },

  // ----- Linking words -----
  {
    id: 'ing-030', tema: 'conectores', dificultad: 2,
    enunciado: '______ the heavy rain, we decided to go out.',
    opciones: ['Despite', 'Although', 'However', 'Because of'],
    correcta: 0,
    explicacion: '"Despite" y "in spite of" van seguidos de sustantivo; "although" necesita sujeto y verbo después.',
    pista: 'Fíjate en si lo que sigue es un sustantivo o una oración completa.',
  },
  {
    id: 'ing-031', tema: 'conectores', dificultad: 2,
    enunciado: 'He was exhausted; ______, he finished the race.',
    opciones: ['however', 'despite', 'although', 'because'],
    correcta: 0,
    explicacion: '"However" enlaza dos oraciones independientes y va entre comas o después de punto y coma.',
  },
  {
    id: 'ing-032', tema: 'conectores', dificultad: 3,
    enunciado: 'It was ______ a difficult exam that half the class failed.',
    opciones: ['such', 'so', 'too', 'very'],
    correcta: 0,
    explicacion: 'La estructura es "such + (a/an) + adjetivo + sustantivo + that". Con solo un adjetivo se usaría "so difficult that".',
  },

  // ----- Phrasal verbs -----
  {
    id: 'ing-033', tema: 'phrasal-verbs', dificultad: 1,
    enunciado: "I don't know this word. I'll ______ it ______ in the dictionary.",
    opciones: ['look / up', 'look / after', 'look / for', 'look / into'],
    correcta: 0,
    explicacion: '"Look up" es buscar información en un diccionario o lista. "Look for" es buscar un objeto y "look after" es cuidar.',
  },
  {
    id: 'ing-034', tema: 'phrasal-verbs', dificultad: 2,
    enunciado: 'The plane will ______ in ten minutes.',
    opciones: ['take off', 'take up', 'take over', 'take out'],
    correcta: 0,
    explicacion: '"Take off" es despegar (y también quitarse una prenda).',
  },
  {
    id: 'ing-035', tema: 'phrasal-verbs', dificultad: 2,
    enunciado: 'She ______ smoking two years ago and she feels much better now.',
    opciones: ['gave up', 'gave in', 'gave away', 'gave back'],
    correcta: 0,
    explicacion: '"Give up" es abandonar un hábito. "Give in" es rendirse ante alguien y "give back" es devolver.',
  },

  // ----- Vocabulary and word formation -----
  {
    id: 'ing-036', tema: 'vocabulario', dificultad: 2,
    enunciado: 'Complete with the correct form of DECIDE: "His ______ surprised everyone."',
    opciones: ['decision', 'decisive', 'deciding', 'decided'],
    correcta: 0,
    explicacion: 'Después del posesivo "his" hace falta un sustantivo, y el sustantivo de "decide" es "decision".',
  },
  {
    id: 'ing-037', tema: 'vocabulario', dificultad: 2,
    enunciado: 'What does the word ACTUALLY mean in "Actually, I prefer tea"?',
    opciones: ['In fact', 'Currently', 'Nowadays', 'Immediately'],
    correcta: 0,
    explicacion: 'Falso amigo clásico: "actually" significa "en realidad, de hecho". Para "actualmente" se usa "currently" o "nowadays".',
  },
  {
    id: 'ing-038', tema: 'vocabulario', dificultad: 1,
    enunciado: 'Choose the correct collocation: "We need to ______ a decision before Friday."',
    opciones: ['make', 'do', 'take', 'have'],
    correcta: 0,
    explicacion: 'En inglés se dice "make a decision". "Do" acompaña tareas (do homework) y "take" otras expresiones (take a photo).',
  },
  {
    id: 'ing-039', tema: 'vocabulario', dificultad: 3,
    enunciado: 'Which word is the opposite of SCARCE?',
    opciones: ['abundant', 'expensive', 'useful', 'hidden'],
    correcta: 0,
    explicacion: '"Scarce" significa escaso, así que su contrario es "abundant" (abundante).',
  },
  {
    id: 'ing-040', tema: 'vocabulario', dificultad: 2,
    enunciado: 'Choose the word that completes the sentence: "The instructions were so ______ that nobody understood them."',
    opciones: ['confusing', 'confused', 'confusion', 'confuse'],
    correcta: 0,
    explicacion: 'Los adjetivos en -ing describen la cosa que provoca el efecto (instrucciones confusas); los de -ed describen a quien lo siente (the students were confused).',
  },

  // ----- Reading 1 -----
  {
    id: 'ing-041', tema: 'reading', dificultad: 2, lectura: 'en-t1',
    enunciado: 'What is the main idea of the text?',
    opciones: [
      'Tool libraries let people share equipment and, unexpectedly, teach each other to repair things',
      'Electric drills are a waste of money for most families',
      'The financial crisis of 2008 destroyed many small businesses',
      'City councils should run more libraries',
    ],
    correcta: 0,
    explicacion: 'El texto empieza con el dato del taladro como ejemplo y termina diciendo cuál es, según los bibliotecarios, el beneficio real: enseñar a reparar. Las demás opciones recogen detalles sueltos.',
  },
  {
    id: 'ing-042', tema: 'reading', dificultad: 1, lectura: 'en-t1',
    enunciado: 'According to the text, how long does an average electric drill work during its whole life?',
    opciones: ['About thirteen minutes', 'About thirteen hours', 'About a week', 'The text does not say'],
    correcta: 0,
    explicacion: 'Primera frase: "about thirteen minutes in its entire life".',
  },
  {
    id: 'ing-043', tema: 'reading', dificultad: 3, lectura: 'en-t1',
    enunciado: 'In the text, "almost by accident" suggests that tool libraries:',
    opciones: [
      'Did not plan to become places for teaching repair skills',
      'Were created after an accident in a workshop',
      'Are dangerous for inexperienced borrowers',
      'Opened without permission from the council',
    ],
    correcta: 0,
    explicacion: 'La expresión indica que ese resultado no era el objetivo inicial: surgió porque quien pide prestada una herramienta suele necesitar que le enseñen a usarla.',
  },
  {
    id: 'ing-044', tema: 'reading', dificultad: 2, lectura: 'en-t1',
    enunciado: 'Which statement is TRUE according to the text?',
    opciones: [
      'Most tool libraries are run by volunteers',
      'All tool libraries belong to city councils',
      'The first tool library opened in 2008',
      'There are fewer than one hundred tool libraries today',
    ],
    correcta: 0,
    explicacion: 'El segundo párrafo dice "Some are run by city councils; most are run by volunteers", que la primera abrió en 1979 y que hoy hay más de quinientas.',
  },

  // ----- Reading 2 -----
  {
    id: 'ing-045', tema: 'reading', dificultad: 2, lectura: 'en-t2',
    enunciado: 'What was the main purpose of the Strasbourg scheme?',
    opciones: [
      'To change a daily habit by making cycling slightly more attractive than driving',
      'To increase the income of low-paid employees',
      'To reduce the number of buses in the city',
      'To finance the construction of new bike lanes',
    ],
    correcta: 0,
    explicacion: 'El texto lo dice expresamente: "The scheme was not designed to make anyone rich. Its aim was to change a habit."',
  },
  {
    id: 'ing-046', tema: 'reading', dificultad: 3, lectura: 'en-t2',
    enunciado: 'Why does the text say the results were "limited"?',
    opciones: [
      'Because the study could not show how many new cyclists had previously driven a car',
      'Because cycling actually decreased in some companies',
      'Because only three companies joined the scheme',
      'Because the payment was stopped after one year',
    ],
    correcta: 0,
    explicacion: 'Si esos ciclistas antes iban en autobús, el beneficio en tráfico y emisiones es mucho menor. Esa es la limitación que menciona el texto.',
  },
  {
    id: 'ing-047', tema: 'reading', dificultad: 2, lectura: 'en-t2',
    enunciado: 'What do the critics of the scheme argue?',
    opciones: [
      'That protected bike lanes would benefit more people than individual payments',
      'That cycling to work is dangerous in Strasbourg',
      'That employers should not receive tax deductions',
      'That twenty-five cents per kilometre is too much money',
    ],
    correcta: 0,
    explicacion: 'Último párrafo: los críticos sostienen que el dinero rendiría más en carriles protegidos, que sirven a todos y no solo a quienes trabajan en una empresa participante.',
  },
  {
    id: 'ing-048', tema: 'reading', dificultad: 3, lectura: 'en-t2',
    enunciado: 'In the text, the word "modest" (paragraph 1) is closest in meaning to:',
    opciones: ['small', 'humble in character', 'secret', 'generous'],
    correcta: 0,
    explicacion: 'Aplicado a una cantidad de dinero, "modest" significa pequeña. El sentido de persona humilde no encaja aquí.',
  },

  // ----- Complemento hasta la meta de 10 por tema -----
  {
    id: 'ing-049', tema: 'tiempos-verbales', dificultad: 1,
    enunciado: 'My brother ______ to the gym every Tuesday.',
    opciones: ['goes', 'go', 'is going', 'has gone'],
    correcta: 0,
    explicacion: 'Present simple para rutinas, y con tercera persona del singular el verbo lleva -s.',
  },
  {
    id: 'ing-050', tema: 'tiempos-verbales', dificultad: 2,
    enunciado: 'They ______ the report yet.',
    opciones: ["haven't finished", "didn't finish", "don't finish", "hadn't finished"],
    correcta: 0,
    explicacion: '"Yet" en frases negativas y en preguntas acompaña al present perfect: algo que se esperaba y todavía no ocurre.',
  },
  {
    id: 'ing-051', tema: 'tiempos-verbales', dificultad: 2,
    enunciado: 'While I ______ dinner, the lights went out.',
    opciones: ['was cooking', 'cooked', 'have cooked', 'cook'],
    correcta: 0,
    explicacion: 'Past continuous para la acción en desarrollo y past simple para la que la interrumpe. "While" suele introducir la primera.',
  },
  {
    id: 'ing-052', tema: 'tiempos-verbales', dificultad: 3,
    enunciado: 'Look at those clouds! It ______ rain.',
    opciones: ['is going to', 'will', 'would', 'is raining'],
    correcta: 0,
    explicacion: '"Going to" se usa cuando hay evidencia presente de lo que va a pasar. "Will" corresponde a decisiones del momento o a predicciones sin evidencia.',
  },
  {
    id: 'ing-053', tema: 'condicionales', dificultad: 1,
    enunciado: 'If it ______ tomorrow, we will cancel the trip.',
    opciones: ['rains', 'will rain', 'rained', 'would rain'],
    correcta: 0,
    explicacion: 'First conditional: if + present simple, y en la otra mitad will + infinitivo. Después de "if" no se usa "will".',
  },
  {
    id: 'ing-054', tema: 'condicionales', dificultad: 2,
    enunciado: 'If I had more time, I ______ a new language.',
    opciones: ['would learn', 'will learn', 'would have learned', 'learn'],
    correcta: 0,
    explicacion: 'Second conditional: situación hipotética en el presente. if + past simple + would + infinitivo.',
  },
  {
    id: 'ing-055', tema: 'condicionales', dificultad: 2,
    enunciado: 'You will miss the bus ______ you hurry up.',
    opciones: ['unless', 'if', 'although', 'so that'],
    correcta: 0,
    explicacion: '"Unless" equivale a "if... not": perderás el bus a menos que te apures. Por eso el verbo que lo sigue va en afirmativo.',
  },
  {
    id: 'ing-056', tema: 'condicionales', dificultad: 3,
    enunciado: 'I wish I ______ told her the truth.',
    opciones: ['had', 'have', 'would have', 'did'],
    correcta: 0,
    explicacion: '"I wish" referido al pasado exige past perfect: I wish I had told. Expresa arrepentimiento por algo que ya no se puede cambiar.',
  },
  {
    id: 'ing-057', tema: 'condicionales', dificultad: 2,
    enunciado: 'If you ______ the mixture, it turns green.',
    opciones: ['heat', 'will heat', 'would heat', 'heated'],
    correcta: 0,
    explicacion: 'Zero conditional: un hecho que siempre ocurre, con present simple en las dos partes.',
  },
  {
    id: 'ing-058', tema: 'condicionales', dificultad: 3,
    enunciado: 'She would have passed the exam if she ______ harder.',
    opciones: ['had studied', 'studied', 'would study', 'has studied'],
    correcta: 0,
    explicacion: 'Third conditional: la parte del "if" va en past perfect y la otra en would have + participio, sin importar el orden en que aparezcan.',
  },
  {
    id: 'ing-059', tema: 'modales', dificultad: 1,
    enunciado: '______ you help me with this box, please?',
    opciones: ['Could', 'Must', 'Should', 'Would have'],
    correcta: 0,
    explicacion: '"Could" y "would" sirven para pedir algo con cortesía. "Must" expresa obligación y sonaría como una orden.',
  },
  {
    id: 'ing-060', tema: 'modales', dificultad: 2,
    enunciado: 'You ______ wear a helmet on a motorbike. It is the law.',
    opciones: ['must', 'might', 'could', 'may not'],
    correcta: 0,
    explicacion: '"Must" expresa obligación fuerte, sobre todo cuando viene de una norma o del propio hablante.',
  },
  {
    id: 'ing-061', tema: 'modales', dificultad: 2,
    enunciado: 'She is not answering. She ______ be in a meeting.',
    opciones: ['might', 'must not', 'should', "can't"],
    correcta: 0,
    explicacion: '"Might" expresa una posibilidad que no se puede confirmar. "Must" sería certeza casi total y "can’t" sería descartarlo.',
  },
  {
    id: 'ing-062', tema: 'modales', dificultad: 2,
    enunciado: 'When I was a child, I ______ swim very well.',
    opciones: ['could', 'can', 'should', 'must'],
    correcta: 0,
    explicacion: '"Could" es el pasado de "can" para hablar de una habilidad general que se tenía.',
  },
  {
    id: 'ing-063', tema: 'modales', dificultad: 3,
    enunciado: 'He is very pale. He ______ seen something terrible.',
    opciones: ['must have', 'must', 'should have', 'can have'],
    correcta: 0,
    explicacion: '"Must have + participio" es una deducción sobre el pasado a partir de una evidencia presente: seguramente vio algo terrible.',
  },
  {
    id: 'ing-064', tema: 'modales', dificultad: 2,
    enunciado: 'You ______ smoke in this area, but most people do not.',
    opciones: ['may', "mustn't", 'have to', 'should not'],
    correcta: 0,
    explicacion: '"May" expresa permiso. La segunda parte de la frase indica que está permitido aunque casi nadie lo haga, así que una prohibición no encajaría.',
  },
  {
    id: 'ing-065', tema: 'voz-pasiva', dificultad: 1,
    enunciado: 'The letters ______ every morning.',
    opciones: ['are delivered', 'deliver', 'are delivering', 'delivers'],
    correcta: 0,
    explicacion: 'Las cartas reciben la acción, así que va en pasiva de present simple: are + participio.',
  },
  {
    id: 'ing-066', tema: 'voz-pasiva', dificultad: 2,
    enunciado: 'The new hospital ______ next year.',
    opciones: ['will be built', 'will build', 'is built', 'has been built'],
    correcta: 0,
    explicacion: 'Pasiva de futuro: will be + participio. "Next year" sitúa la acción por delante.',
  },
  {
    id: 'ing-067', tema: 'voz-pasiva', dificultad: 2,
    enunciado: 'Choose the passive form of: "They are repairing the road."',
    opciones: [
      'The road is being repaired.',
      'The road is repaired.',
      'The road has been repaired.',
      'The road was repaired.',
    ],
    correcta: 0,
    explicacion: 'El present continuous activo pasa a "is/are being + participio".',
  },
  {
    id: 'ing-068', tema: 'voz-pasiva', dificultad: 2,
    enunciado: 'This song ______ by a Colombian artist.',
    opciones: ['was written', 'wrote', 'has wrote', 'was wrote'],
    correcta: 0,
    explicacion: 'El participio de "write" es "written". Con "by" se introduce el agente cuando resulta relevante.',
  },
  {
    id: 'ing-069', tema: 'voz-pasiva', dificultad: 3,
    enunciado: 'Choose the passive form of: "Somebody must clean this room."',
    opciones: [
      'This room must be cleaned.',
      'This room must clean.',
      'This room is must cleaned.',
      'This room must been cleaned.',
    ],
    correcta: 0,
    explicacion: 'Con un verbo modal, la pasiva se forma con modal + be + participio.',
  },
  {
    id: 'ing-070', tema: 'voz-pasiva', dificultad: 2,
    enunciado: 'The windows ______ when we arrived.',
    opciones: ['had been broken', 'had broken', 'have broken', 'were breaking'],
    correcta: 0,
    explicacion: 'Pasiva de past perfect: had been + participio, porque el daño ocurrió antes de nuestra llegada.',
  },
  {
    id: 'ing-071', tema: 'voz-pasiva', dificultad: 3,
    enunciado: 'In which sentence is the passive voice the better choice?',
    opciones: [
      'The vaccine was discovered in 1955.',
      'My sister was cooked the dinner.',
      'The dog was barked all night.',
      'The rain was fallen heavily.',
    ],
    correcta: 0,
    explicacion: 'La pasiva funciona cuando el agente es irrelevante o desconocido. Los verbos intransitivos como "bark" o "fall" no admiten pasiva, porque no tienen objeto que pase a sujeto.',
  },
  {
    id: 'ing-072', tema: 'reported-speech', dificultad: 2,
    enunciado: 'She said: "I will call you tomorrow." → She said she ______ call me the next day.',
    opciones: ['would', 'will', 'would have', 'is going to'],
    correcta: 0,
    explicacion: 'En estilo indirecto "will" pasa a "would", y las referencias de tiempo cambian: tomorrow se convierte en the next day.',
  },
  {
    id: 'ing-073', tema: 'reported-speech', dificultad: 2,
    enunciado: 'He said: "I am working now." → He said he ______ at that moment.',
    opciones: ['was working', 'is working', 'has been working', 'worked'],
    correcta: 0,
    explicacion: 'El present continuous retrocede a past continuous, y "now" se convierte en "at that moment" o "then".',
  },
  {
    id: 'ing-074', tema: 'reported-speech', dificultad: 3,
    enunciado: 'They asked: "Have you seen the film?" → They asked me if I ______ the film.',
    opciones: ['had seen', 'have seen', 'saw', 'did see'],
    correcta: 0,
    explicacion: 'El present perfect retrocede a past perfect. Las preguntas de sí o no se reportan con "if" o "whether".',
  },
  {
    id: 'ing-075', tema: 'reported-speech', dificultad: 2,
    enunciado: 'She told me: "Do not touch that." → She told me ______ that.',
    opciones: ['not to touch', 'to not touch', "don't touch", 'not touching'],
    correcta: 0,
    explicacion: 'Las órdenes negativas se reportan con "not to + infinitivo", con el "not" delante del "to".',
  },
  {
    id: 'ing-076', tema: 'reported-speech', dificultad: 2,
    enunciado: 'He said: "I live here." → He said he lived ______.',
    opciones: ['there', 'here', 'in here', 'at there'],
    correcta: 0,
    explicacion: 'En estilo indirecto también cambian los adverbios de lugar: here pasa a there, y this pasa a that.',
  },
  {
    id: 'ing-077', tema: 'reported-speech', dificultad: 3,
    enunciado: 'Which sentence does NOT change its tense in reported speech?',
    opciones: [
      'She said: "Water boils at 100 °C."',
      'She said: "I am tired."',
      'She said: "I saw him yesterday."',
      'She said: "I will travel soon."',
    ],
    correcta: 0,
    explicacion: 'Cuando lo dicho sigue siendo verdad general, el tiempo verbal puede mantenerse: she said water boils at 100 °C. Es la excepción a la regla del paso atrás.',
  },
  {
    id: 'ing-078', tema: 'reported-speech', dificultad: 2,
    enunciado: 'She asked: "What time does the class start?" → She asked what time the class ______.',
    opciones: ['started', 'does start', 'did start', 'starts'],
    correcta: 0,
    explicacion: 'La pregunta reportada recupera el orden sujeto + verbo, pierde el auxiliar "does" y retrocede a past simple.',
  },
  {
    id: 'ing-079', tema: 'relativas', dificultad: 1,
    enunciado: 'The book ______ I bought yesterday is excellent.',
    opciones: ['that', 'who', 'whose', 'where'],
    correcta: 0,
    explicacion: '"That" o "which" para cosas. Como aquí el relativo es el objeto, incluso podría omitirse: the book I bought yesterday.',
  },
  {
    id: 'ing-080', tema: 'relativas', dificultad: 2,
    enunciado: 'In which sentence can the relative pronoun be omitted?',
    opciones: [
      'The film that we watched was boring.',
      'The man who lives here is my uncle.',
      'The house which has a red door is mine.',
      'The woman who called you is waiting.',
    ],
    correcta: 0,
    explicacion: 'Solo se puede omitir cuando el relativo es el objeto de la oración. En las otras tres es el sujeto y desaparecería el verbo sin sujeto.',
  },
  {
    id: 'ing-081', tema: 'relativas', dificultad: 2,
    enunciado: 'My neighbour, ______ works at the hospital, is very kind.',
    opciones: ['who', 'that', 'which', 'whose'],
    correcta: 0,
    explicacion: 'En las relativas explicativas, entre comas, no se puede usar "that": hay que usar who para personas y which para cosas.',
  },
  {
    id: 'ing-082', tema: 'relativas', dificultad: 2,
    enunciado: 'This is the restaurant ______ we met for the first time.',
    opciones: ['where', 'which', 'that', 'when'],
    correcta: 0,
    explicacion: '"Where" se usa cuando el lugar es la circunstancia en la que ocurre la acción, equivalente a "in which".',
  },
  {
    id: 'ing-083', tema: 'relativas', dificultad: 3,
    enunciado: 'Choose the sentence with correct punctuation and meaning: "the students who failed must repeat".',
    opciones: [
      'The students who failed must repeat the course. (Solo repiten los que reprobaron)',
      'The students, who failed, must repeat the course. (Solo repiten algunos)',
      'The students that, failed must repeat the course.',
      'The students which failed must repeat the course.',
    ],
    correcta: 0,
    explicacion: 'Sin comas, la relativa es especificativa y limita el grupo. Con comas indicaría que todos los estudiantes reprobaron, que es un significado distinto.',
  },
  {
    id: 'ing-084', tema: 'relativas', dificultad: 2,
    enunciado: 'I remember the day ______ we moved to this city.',
    opciones: ['when', 'where', 'which', 'who'],
    correcta: 0,
    explicacion: '"When" se usa con expresiones de tiempo como day, year o moment.',
  },
  {
    id: 'ing-085', tema: 'relativas', dificultad: 2,
    enunciado: 'That is the girl ______ brother plays in the school band.',
    opciones: ['whose', 'who', 'which', 'that'],
    correcta: 0,
    explicacion: '"Whose" marca posesión: el hermano pertenece a la chica. Va seguido directamente del sustantivo, sin artículo.',
  },
  {
    id: 'ing-086', tema: 'preposiciones', dificultad: 1,
    enunciado: 'I was born ______ 2006, ______ May.',
    opciones: ['in / in', 'on / in', 'at / on', 'in / on'],
    correcta: 0,
    explicacion: '"In" acompaña a años, meses y estaciones; "on" a días y fechas concretas, y "at" a horas.',
  },
  {
    id: 'ing-087', tema: 'preposiciones', dificultad: 2,
    enunciado: 'She is afraid ______ spiders.',
    opciones: ['of', 'to', 'with', 'about'],
    correcta: 0,
    explicacion: '"Afraid of" es una combinación fija de adjetivo y preposición, como interested in, good at o worried about.',
  },
  {
    id: 'ing-088', tema: 'preposiciones', dificultad: 2,
    enunciado: 'We arrived ______ the airport two hours early.',
    opciones: ['at', 'to', 'in', 'on'],
    correcta: 0,
    explicacion: '"Arrive at" para lugares puntuales como un aeropuerto o un edificio, y "arrive in" para ciudades y países. Nunca se dice "arrive to".',
  },
  {
    id: 'ing-089', tema: 'preposiciones', dificultad: 2,
    enunciado: 'The keys are ______ the table, next ______ the lamp.',
    opciones: ['on / to', 'in / to', 'at / of', 'on / of'],
    correcta: 0,
    explicacion: '"On" indica contacto con una superficie y "next to" significa al lado de.',
  },
  {
    id: 'ing-090', tema: 'preposiciones', dificultad: 3,
    enunciado: 'He apologised ______ being late.',
    opciones: ['for', 'of', 'about', 'to'],
    correcta: 0,
    explicacion: '"Apologise for" es la combinación correcta, y tras preposición el verbo va en gerundio: for being.',
  },
  {
    id: 'ing-091', tema: 'preposiciones', dificultad: 2,
    enunciado: 'They have been waiting ______ the bus ______ half an hour.',
    opciones: ['for / for', 'to / since', 'at / for', 'for / since'],
    correcta: 0,
    explicacion: 'El verbo es "wait for", y con un periodo de tiempo se usa "for"; "since" se reserva para un punto de inicio, como since 3 en punto.',
  },
  {
    id: 'ing-092', tema: 'preposiciones', dificultad: 2,
    enunciado: 'I am not very good ______ remembering names.',
    opciones: ['at', 'in', 'with', 'on'],
    correcta: 0,
    explicacion: '"Good at" para habilidades, seguido de gerundio cuando va un verbo.',
  },
  {
    id: 'ing-093', tema: 'cuantificadores', dificultad: 1,
    enunciado: 'How ______ sugar do you take in your coffee?',
    opciones: ['much', 'many', 'few', 'a lot'],
    correcta: 0,
    explicacion: '"Sugar" es incontable, así que se pregunta con "how much". Con contables se usa "how many".',
  },
  {
    id: 'ing-094', tema: 'cuantificadores', dificultad: 2,
    enunciado: 'There were ______ people at the concert; the hall was almost empty.',
    opciones: ['few', 'a few', 'little', 'much'],
    correcta: 0,
    explicacion: '"Few" sin artículo tiene sentido negativo: casi ninguno, que es lo que exige la segunda parte de la frase. "A few" significa algunos.',
  },
  {
    id: 'ing-095', tema: 'cuantificadores', dificultad: 2,
    enunciado: 'I would like ______ information about the course.',
    opciones: ['some', 'a', 'many', 'a few'],
    correcta: 0,
    explicacion: '"Information" es incontable en inglés: no admite artículo indefinido ni plural. Se dice some information o a piece of information.',
  },
  {
    id: 'ing-096', tema: 'cuantificadores', dificultad: 2,
    enunciado: 'She plays ______ guitar in ______ band.',
    opciones: ['the / a', 'a / the', '— / a', 'the / —'],
    correcta: 0,
    explicacion: 'Con instrumentos musicales se usa el artículo definido: play the guitar. La banda se menciona por primera vez, así que lleva artículo indefinido.',
  },
  {
    id: 'ing-097', tema: 'cuantificadores', dificultad: 3,
    enunciado: 'There is ______ milk left. We need to buy more.',
    opciones: ['hardly any', 'hardly no', 'a lot of', 'many'],
    correcta: 0,
    explicacion: '"Hardly any" significa casi nada y ya es negativo, así que no se combina con "no". En inglés no se admite doble negación.',
  },
  {
    id: 'ing-098', tema: 'cuantificadores', dificultad: 2,
    enunciado: '______ of the students passed the exam, so the teacher was happy.',
    opciones: ['Most', 'Almost', 'The most', 'Mostly'],
    correcta: 0,
    explicacion: '"Most of" significa la mayoría de. "Almost" es un adverbio (casi) y "mostly" significa principalmente.',
  },
  {
    id: 'ing-099', tema: 'cuantificadores', dificultad: 2,
    enunciado: 'We have ______ time, so we can walk instead of taking a taxi.',
    opciones: ['plenty of', 'plenty', 'many', 'a few'],
    correcta: 0,
    explicacion: '"Plenty of" significa de sobra y funciona con contables e incontables; "time" es incontable, así que descarta many y a few.',
  },
  {
    id: 'ing-100', tema: 'conectores', dificultad: 2,
    enunciado: '______ it was raining, we went for a walk.',
    opciones: ['Although', 'Despite', 'However', 'Because'],
    correcta: 0,
    explicacion: '"Although" va seguido de sujeto y verbo; "despite" necesitaría un sustantivo o un gerundio: despite the rain.',
  },
  {
    id: 'ing-101', tema: 'conectores', dificultad: 2,
    enunciado: 'We stayed at home ______ the storm.',
    opciones: ['because of', 'because', 'although', 'so'],
    correcta: 0,
    explicacion: '"Because of" va con un sustantivo y "because" con una oración completa: because there was a storm.',
  },
  {
    id: 'ing-102', tema: 'conectores', dificultad: 2,
    enunciado: 'The test was ______ difficult that nobody finished it.',
    opciones: ['so', 'such', 'too', 'very'],
    correcta: 0,
    explicacion: 'Con un adjetivo solo se usa "so... that". "Such" requiere un sustantivo detrás: such a difficult test that...',
  },
  {
    id: 'ing-103', tema: 'conectores', dificultad: 2,
    enunciado: 'I studied a lot; ______, I did not pass.',
    opciones: ['however', 'therefore', 'moreover', 'because'],
    correcta: 0,
    explicacion: '"However" introduce un contraste. "Therefore" indicaría consecuencia y "moreover" añadiría información en la misma dirección.',
  },
  {
    id: 'ing-104', tema: 'conectores', dificultad: 3,
    enunciado: '______ studying for weeks, he failed the exam.',
    opciones: ['In spite of', 'Although', 'However', 'Despite of'],
    correcta: 0,
    explicacion: '"In spite of" y "despite" van seguidos de gerundio o sustantivo. "Despite of" no existe: es uno de los errores más frecuentes.',
  },
  {
    id: 'ing-105', tema: 'conectores', dificultad: 2,
    enunciado: 'She saved money ______ she could travel in summer.',
    opciones: ['so that', 'so', 'because of', 'in spite of'],
    correcta: 0,
    explicacion: '"So that" introduce la finalidad y suele ir seguido de un modal como could o would.',
  },
  {
    id: 'ing-106', tema: 'conectores', dificultad: 2,
    enunciado: 'First, preheat the oven. ______, mix the ingredients.',
    opciones: ['Then', 'Although', 'However', 'Despite'],
    correcta: 0,
    explicacion: '"Then" marca la secuencia de pasos, igual que after that, next o finally.',
  },
  {
    id: 'ing-107', tema: 'phrasal-verbs', dificultad: 2,
    enunciado: 'We had to ______ the meeting because the manager was ill.',
    opciones: ['put off', 'put on', 'put up', 'put away'],
    correcta: 0,
    explicacion: '"Put off" es aplazar. "Put on" es ponerse una prenda y "put away" es guardar algo.',
  },
  {
    id: 'ing-108', tema: 'phrasal-verbs', dificultad: 2,
    enunciado: 'I get ______ well with my classmates.',
    opciones: ['on', 'up', 'over', 'through'],
    correcta: 0,
    explicacion: '"Get on with somebody" es llevarse bien con alguien. "Get over" es superar algo y "get up", levantarse.',
  },
  {
    id: 'ing-109', tema: 'phrasal-verbs', dificultad: 2,
    enunciado: 'The car broke ______ on the way to the airport.',
    opciones: ['down', 'up', 'in', 'off'],
    correcta: 0,
    explicacion: '"Break down" es averiarse. "Break up" es terminar una relación y "break in", entrar por la fuerza.',
  },
  {
    id: 'ing-110', tema: 'phrasal-verbs', dificultad: 2,
    enunciado: 'Please fill ______ this form before the interview.',
    opciones: ['in', 'on', 'up', 'over'],
    correcta: 0,
    explicacion: '"Fill in" o "fill out" es completar un formulario. "Fill up" es llenar un recipiente hasta el tope.',
  },
  {
    id: 'ing-111', tema: 'phrasal-verbs', dificultad: 3,
    enunciado: 'I ran ______ an old friend at the supermarket yesterday.',
    opciones: ['into', 'out of', 'over', 'away'],
    correcta: 0,
    explicacion: '"Run into somebody" es encontrárselo por casualidad. "Run out of" es quedarse sin algo y "run over", atropellar.',
  },
  {
    id: 'ing-112', tema: 'phrasal-verbs', dificultad: 2,
    enunciado: 'Could you turn ______ the music? I cannot hear you.',
    opciones: ['down', 'on', 'up', 'into'],
    correcta: 0,
    explicacion: '"Turn down" es bajar el volumen y "turn up", subirlo. Si no se oye a la otra persona, hay que bajarlo.',
  },
  {
    id: 'ing-113', tema: 'phrasal-verbs', dificultad: 3,
    enunciado: 'In which sentence is the phrasal verb used correctly?',
    opciones: [
      'I need to look after my little brother tonight.',
      'I need to look after for my little brother tonight.',
      'I need to look my little brother after tonight.',
      'I need to look for after my little brother.',
    ],
    correcta: 0,
    explicacion: '"Look after" es inseparable: el objeto va siempre después de la partícula y no lleva preposición adicional.',
  },
  {
    id: 'ing-114', tema: 'vocabulario', dificultad: 2,
    enunciado: 'Complete with the correct form of SUCCESS: "She is a very ______ businesswoman."',
    opciones: ['successful', 'success', 'succeed', 'successfully'],
    correcta: 0,
    explicacion: 'Delante de un sustantivo hace falta un adjetivo. "Successfully" es el adverbio y "succeed", el verbo.',
  },
  {
    id: 'ing-115', tema: 'vocabulario', dificultad: 2,
    enunciado: 'Which prefix makes the opposite of POSSIBLE?',
    opciones: ['im-', 'un-', 'dis-', 'in-'],
    correcta: 0,
    explicacion: 'Delante de p, b y m se usa im-: impossible, imbalance, immature. Con otras raíces se usan un-, in- o dis-.',
  },
  {
    id: 'ing-116', tema: 'vocabulario', dificultad: 3,
    enunciado: 'What does the false friend SENSIBLE mean in English?',
    opciones: ['Reasonable, showing good judgement', 'Easily hurt emotionally', 'Perceptible by the senses', 'Expensive'],
    correcta: 0,
    explicacion: 'En inglés "sensible" es sensato. Para el español "sensible" se usa "sensitive".',
  },
  {
    id: 'ing-117', tema: 'vocabulario', dificultad: 2,
    enunciado: 'Choose the correct collocation: "He ______ a mistake in the calculation."',
    opciones: ['made', 'did', 'took', 'had'],
    correcta: 0,
    explicacion: 'Se dice "make a mistake". "Do" acompaña tareas y obligaciones: do homework, do the dishes.',
  },
  {
    id: 'ing-118', tema: 'vocabulario', dificultad: 3,
    enunciado: 'Which word is closest in meaning to RELUCTANT?',
    opciones: ['unwilling', 'relaxed', 'brilliant', 'late'],
    correcta: 0,
    explicacion: '"Reluctant" describe a quien hace algo de mala gana o se resiste a hacerlo, es decir, unwilling.',
  },
  {
    id: 'ing-119', tema: 'reading', dificultad: 2, lectura: 'en-t1',
    enunciado: 'According to the text, why did the idea of tool libraries spread faster after 2008?',
    opciones: [
      'Because the financial crisis made people reconsider buying equipment they rarely used',
      'Because city councils started funding them',
      'Because new tools became more expensive to manufacture',
      'Because the first tool library closed that year',
    ],
    correcta: 0,
    explicacion: 'El segundo párrafo lo dice expresamente: la crisis hizo que la gente lo pensara dos veces antes de comprar equipos que casi no necesitaba.',
  },
  {
    id: 'ing-120', tema: 'reading', dificultad: 3, lectura: 'en-t2',
    enunciado: 'According to the text, what do transport researchers say about how people give up their cars?',
    opciones: [
      'They change when an alternative becomes slightly cheaper or more convenient, not because of information campaigns',
      'They change mainly when they learn about pollution',
      'They never change their transport habits',
      'They change only when driving becomes illegal',
    ],
    correcta: 0,
    explicacion: 'El segundo párrafo contrapone las campañas de información con el cambio real, que responde a la conveniencia y al costo. Ese es el razonamiento detrás del incentivo económico del programa.',
  },
  // ----- Ampliación por niveles -----
  {
    id: 'ing-121', tema: 'tiempos-verbales', dificultad: 3,
    enunciado: 'I ______ for three hours when she finally called.',
    opciones: ['had been waiting', 'have been waiting', 'was waiting', 'waited'],
    correcta: 0,
    explicacion: 'Past perfect continuous: una acción que venía ocurriendo durante un tiempo antes de otro momento del pasado. La llamada corta la espera.',
  },
  {
    id: 'ing-122', tema: 'tiempos-verbales', dificultad: 4,
    enunciado: 'This time next year, we ______ in our new house.',
    opciones: ['will be living', 'will live', 'are living', 'will have lived'],
    correcta: 0,
    explicacion: 'Future continuous: una acción en curso en un momento concreto del futuro. "This time next year" señala ese punto exacto.',
  },
  {
    id: 'ing-123', tema: 'tiempos-verbales', dificultad: 4,
    enunciado: 'By 2030, researchers ______ a vaccine for this disease.',
    opciones: ['will have developed', 'will develop', 'are developing', 'will be developing'],
    correcta: 0,
    explicacion: 'Future perfect: algo que estará terminado antes de un momento futuro. "By + fecha" es la señal típica de este tiempo.',
  },
  {
    id: 'ing-124', tema: 'tiempos-verbales', dificultad: 4,
    enunciado: 'No sooner ______ the door than the phone rang.',
    opciones: ['had I closed', 'I had closed', 'did I close', 'I closed'],
    correcta: 0,
    explicacion: 'Con expresiones negativas al principio de la frase (no sooner, never, hardly, rarely) el orden se invierte: auxiliar antes del sujeto. Y "no sooner" pide past perfect seguido de "than".',
  },
  {
    id: 'ing-125', tema: 'condicionales', dificultad: 4,
    enunciado: 'If I ______ about the traffic, I would have left earlier.',
    opciones: ['had known', 'knew', 'would know', 'have known'],
    correcta: 0,
    explicacion: 'Tercer condicional: habla de algo que ya no puede cambiarse. La estructura es "if + past perfect, would have + participio".',
  },
  {
    id: 'ing-126', tema: 'condicionales', dificultad: 4,
    enunciado: 'If she had studied medicine, she ______ a doctor now.',
    opciones: ['would be', 'would have been', 'will be', 'were'],
    correcta: 0,
    explicacion: 'Es un condicional mixto: la condición está en el pasado (had studied) pero la consecuencia se sitúa en el presente ("now"), así que se usa "would + infinitivo".',
  },
  {
    id: 'ing-127', tema: 'condicionales', dificultad: 4,
    enunciado: 'I wish I ______ how to swim.',
    opciones: ['knew', 'know', 'would know', 'have known'],
    correcta: 0,
    explicacion: 'Después de "I wish", para lamentar algo del presente se usa el pasado simple. Con "I wish I had known" se lamentaría algo del pasado.',
  },
  {
    id: 'ing-128', tema: 'modales', dificultad: 1,
    enunciado: "You ______ smoke here. It's strictly forbidden.",
    opciones: ["mustn't", "don't have to", 'might not', "couldn't"],
    correcta: 0,
    explicacion: '"Mustn\'t" expresa prohibición. "Don\'t have to" significa algo muy distinto: que no es necesario.',
  },
  {
    id: 'ing-129', tema: 'modales', dificultad: 3,
    enunciado: 'You ______ have told me you were ill. I was really worried.',
    opciones: ['should', 'must', 'can', 'would'],
    correcta: 0,
    explicacion: '"Should have + participio" se usa para reprochar algo que no se hizo y habría sido lo correcto.',
  },
  {
    id: 'ing-130', tema: 'modales', dificultad: 4,
    enunciado: "He ______ have missed the bus — I saw him arrive ten minutes ago.",
    opciones: ["can't", 'mustn’t', 'shouldn’t', 'needn’t'],
    correcta: 0,
    explicacion: '"Can\'t have + participio" expresa la certeza de que algo NO ocurrió. Para la certeza de que sí ocurrió se usa "must have".',
  },
  {
    id: 'ing-131', tema: 'modales', dificultad: 4,
    enunciado: 'We ______ take an umbrella; the forecast says it might rain.',
    opciones: ['had better', 'had better to', 'would better', 'better had'],
    correcta: 0,
    explicacion: '"Had better" se construye siempre con infinitivo sin "to" y da un consejo con un matiz de advertencia: es mejor hacerlo o habrá consecuencias.',
  },
  {
    id: 'ing-132', tema: 'modales', dificultad: 4,
    enunciado: "She ______ have been at the party, but I'm not sure.",
    opciones: ['may', 'must', "can't", 'should'],
    correcta: 0,
    explicacion: '"May/might have + participio" expresa una posibilidad sobre el pasado. "Must have" sería certeza y "can\'t have", certeza de lo contrario.',
  },
  {
    id: 'ing-133', tema: 'voz-pasiva', dificultad: 1,
    enunciado: 'The letter ______ yesterday.',
    opciones: ['was sent', 'sent', 'is sent', 'has sent'],
    correcta: 0,
    explicacion: 'Pasiva en pasado simple: was/were + participio. El sujeto (the letter) recibe la acción, no la hace.',
  },
  {
    id: 'ing-134', tema: 'voz-pasiva', dificultad: 3,
    enunciado: 'The bridge ______ at the moment, so you have to use the other road.',
    opciones: ['is being repaired', 'is repairing', 'has repaired', 'was repaired'],
    correcta: 0,
    explicacion: 'Pasiva en presente continuo: is/are being + participio. "At the moment" indica que la acción está en curso ahora.',
  },
  {
    id: 'ing-135', tema: 'voz-pasiva', dificultad: 4,
    enunciado: 'The documents ______ by the time you arrive.',
    opciones: ['will have been signed', 'will be signed', 'are signed', 'have signed'],
    correcta: 0,
    explicacion: 'Pasiva en future perfect: will have been + participio. "By the time" indica que la acción estará terminada antes de ese momento.',
  },
  {
    id: 'ing-136', tema: 'voz-pasiva', dificultad: 4,
    enunciado: 'She ______ to be the best candidate for the job.',
    opciones: ['is said', 'says', 'is saying', 'has said'],
    correcta: 0,
    explicacion: 'Es la pasiva impersonal: "It is said that she is..." se reformula como "She is said to be...". Sirve para atribuir una opinión sin nombrar a quien la sostiene.',
  },
  {
    id: 'ing-137', tema: 'voz-pasiva', dificultad: 4,
    enunciado: 'I ______ my hair cut yesterday.',
    opciones: ['had', 'have', 'was', 'did'],
    correcta: 0,
    explicacion: 'Es la estructura causativa "have something done": alguien más hizo la acción por uno. En pasado, "I had my hair cut" significa que me lo cortaron, no que yo me lo corté.',
  },
  {
    id: 'ing-138', tema: 'reported-speech', dificultad: 1,
    enunciado: 'She said, "I am tired." → She said she ______ tired.',
    opciones: ['was', 'is', 'were', 'has been'],
    correcta: 0,
    explicacion: 'Al pasar a estilo indirecto, el presente simple retrocede a pasado simple.',
  },
  {
    id: 'ing-139', tema: 'reported-speech', dificultad: 1,
    enunciado: '"I will call you," he said. → He said he ______ call me.',
    opciones: ['would', 'will', 'would have', 'is going to'],
    correcta: 0,
    explicacion: '"Will" se convierte en "would" en estilo indirecto, igual que "can" pasa a "could" y "may" a "might".',
  },
  {
    id: 'ing-140', tema: 'reported-speech', dificultad: 1,
    enunciado: '"I live in Cali," she said. → She said she ______ in Cali.',
    opciones: ['lived', 'lives', 'is living', 'has lived'],
    correcta: 0,
    explicacion: 'El presente simple del discurso directo pasa al pasado simple en el indirecto.',
  },
  {
    id: 'ing-141', tema: 'reported-speech', dificultad: 4,
    enunciado: '"Don\'t touch it," he told me. → He told me ______.',
    opciones: ['not to touch it', "don't touch it", 'to not touch it', 'that not touch it'],
    correcta: 0,
    explicacion: 'Las órdenes negativas se reportan con "not + to + infinitivo". El "not" va siempre antes del "to".',
  },
  {
    id: 'ing-142', tema: 'reported-speech', dificultad: 4,
    enunciado: '"Where do you work?" she asked. → She asked me where ______.',
    opciones: ['I worked', 'did I work', 'do I work', 'I did work'],
    correcta: 0,
    explicacion: 'Al reportar una pregunta, el orden vuelve a ser el de una frase afirmativa (sujeto + verbo) y desaparece el auxiliar "do/did".',
  },
  {
    id: 'ing-143', tema: 'reported-speech', dificultad: 4,
    enunciado: '"Did you finish the report?" he asked. → He asked ______.',
    opciones: ['if I had finished the report', 'if had I finished the report', 'did I finish the report', 'that I finished the report'],
    correcta: 0,
    explicacion: 'Las preguntas de sí o no se reportan con "if" o "whether", con orden afirmativo, y el past simple retrocede a past perfect.',
  },
  {
    id: 'ing-144', tema: 'relativas', dificultad: 1,
    enunciado: 'The man ______ lives next door is a doctor.',
    opciones: ['who', 'which', 'whose', 'where'],
    correcta: 0,
    explicacion: '"Who" se usa para personas; "which" para cosas y animales.',
  },
  {
    id: 'ing-145', tema: 'relativas', dificultad: 3,
    enunciado: 'That\'s the student ______ project won the prize.',
    opciones: ['whose', 'who', 'which', 'that'],
    correcta: 0,
    explicacion: '"Whose" indica posesión: el proyecto pertenece al estudiante. Funciona igual para personas y para cosas.',
  },
  {
    id: 'ing-146', tema: 'relativas', dificultad: 3,
    enunciado: 'This is the restaurant ______ we had dinner last week.',
    opciones: ['where', 'which', 'who', 'when'],
    correcta: 0,
    explicacion: '"Where" reemplaza a "in which" cuando el antecedente es un lugar. "When" se usaría con un momento en el tiempo.',
  },
  {
    id: 'ing-147', tema: 'relativas', dificultad: 4,
    enunciado: 'My brother, ______ lives in Spain, is coming for Christmas.',
    opciones: ['who', 'that', 'which', 'what'],
    correcta: 0,
    explicacion: 'Es una relativa explicativa, entre comas: añade información sobre alguien ya identificado. En ese tipo de frases nunca se usa "that".',
  },
  {
    id: 'ing-148', tema: 'relativas', dificultad: 4,
    enunciado: 'Nobody explained the reason ______ he resigned.',
    opciones: ['why', 'which', 'where', 'whose'],
    correcta: 0,
    explicacion: '"Why" acompaña a "the reason", igual que "where" acompaña a un lugar y "when" a un momento.',
  },
  {
    id: 'ing-149', tema: 'relativas', dificultad: 4,
    enunciado: 'She passed the exam without studying, ______ surprised everybody.',
    opciones: ['which', 'that', 'what', 'who'],
    correcta: 0,
    explicacion: 'Aquí "which" no se refiere a un sustantivo, sino a toda la oración anterior: lo que sorprendió fue el hecho completo. En ese uso solo cabe "which".',
  },
  {
    id: 'ing-150', tema: 'preposiciones', dificultad: 1,
    enunciado: 'I was born ______ 1998.',
    opciones: ['in', 'on', 'at', 'from'],
    correcta: 0,
    explicacion: '"In" para años, meses y estaciones; "on" para días y fechas; "at" para horas.',
  },
  {
    id: 'ing-151', tema: 'preposiciones', dificultad: 3,
    enunciado: 'She is very good ______ mathematics.',
    opciones: ['at', 'in', 'on', 'for'],
    correcta: 0,
    explicacion: '"Good at" es la combinación fija para hablar de habilidades. "Good for" significa que algo es beneficioso.',
  },
  {
    id: 'ing-152', tema: 'preposiciones', dificultad: 3,
    enunciado: 'We arrived ______ the airport two hours before the flight.',
    opciones: ['at', 'to', 'in', 'on'],
    correcta: 0,
    explicacion: '"Arrive" no lleva "to": se dice "arrive at" para lugares puntuales (aeropuerto, estación) y "arrive in" para ciudades o países.',
  },
  {
    id: 'ing-153', tema: 'preposiciones', dificultad: 4,
    enunciado: 'He apologised ______ being late.',
    opciones: ['for', 'of', 'about', 'to'],
    correcta: 0,
    explicacion: '"Apologise for + gerundio" es la construcción correcta. Se usa "apologise to somebody for something" cuando se menciona a quién se pide disculpas.',
  },
  {
    id: 'ing-154', tema: 'preposiciones', dificultad: 4,
    enunciado: 'They insisted ______ paying for dinner.',
    opciones: ['on', 'in', 'to', 'for'],
    correcta: 0,
    explicacion: '"Insist on + gerundio". Es uno de los verbos cuya preposición no coincide con la del español ("insistir en"), así que conviene memorizarlo junto con el verbo.',
  },
  {
    id: 'ing-155', tema: 'preposiciones', dificultad: 4,
    enunciado: 'The final result depends ______ several factors.',
    opciones: ['on', 'of', 'from', 'in'],
    correcta: 0,
    explicacion: '"Depend on" es fijo. Decir "depend of" es un calco del español y es uno de los errores más frecuentes.',
  },
  {
    id: 'ing-156', tema: 'cuantificadores', dificultad: 1,
    enunciado: "There isn't ______ milk left in the fridge.",
    opciones: ['much', 'many', 'a few', 'several'],
    correcta: 0,
    explicacion: '"Milk" es incontable, así que se usa "much". "Many" acompaña a sustantivos contables en plural.',
  },
  {
    id: 'ing-157', tema: 'cuantificadores', dificultad: 3,
    enunciado: "I have ______ money, so I can't buy the tickets.",
    opciones: ['little', 'a little', 'few', 'a few'],
    correcta: 0,
    explicacion: '"Little" (sin artículo) tiene sentido negativo: casi nada. "A little" sería positivo: algo, lo suficiente. Y "few / a few" van con contables.',
  },
  {
    id: 'ing-158', tema: 'cuantificadores', dificultad: 4,
    enunciado: '______ students passed the exam, which disappointed the teacher.',
    opciones: ['Few', 'A few', 'Little', 'Much'],
    correcta: 0,
    explicacion: 'El contexto ("disappointed") pide el matiz negativo, y "students" es contable: "few". Con "a few" la frase significaría que algunos sí pasaron, y no cuadraría con la decepción.',
  },
  {
    id: 'ing-159', tema: 'cuantificadores', dificultad: 4,
    enunciado: 'Neither of the answers ______ correct.',
    opciones: ['is', 'are', 'were', 'have been'],
    correcta: 0,
    explicacion: '"Neither", "either", "each" y "every" son singulares aunque vayan seguidos de un plural. El sujeto real es "neither", no "answers".',
  },
  {
    id: 'ing-160', tema: 'cuantificadores', dificultad: 4,
    enunciado: "There were ______ people at the concert that we couldn't move.",
    opciones: ['so many', 'so much', 'too many', 'such many'],
    correcta: 0,
    explicacion: 'La estructura "so + many/much + sustantivo + that" expresa consecuencia. Con contables va "many", y "such" se usaría sin cuantificador: "such a crowd that...".',
  },
  {
    id: 'ing-161', tema: 'conectores', dificultad: 1,
    enunciado: 'I was very tired, ______ I went to bed early.',
    opciones: ['so', 'but', 'because', 'although'],
    correcta: 0,
    explicacion: '"So" introduce la consecuencia. "Because" introduciría la causa y el orden de la frase sería el contrario.',
  },
  {
    id: 'ing-162', tema: 'conectores', dificultad: 1,
    enunciado: 'She likes tea ______ coffee.',
    opciones: ['and', 'but', 'so', 'because'],
    correcta: 0,
    explicacion: '"And" simplemente suma dos elementos, sin oponerlos ni explicarlos.',
  },
  {
    id: 'ing-163', tema: 'conectores', dificultad: 1,
    enunciado: 'He is very rich, ______ he is not happy.',
    opciones: ['but', 'and', 'so', 'because'],
    correcta: 0,
    explicacion: '"But" marca el contraste entre las dos ideas.',
  },
  {
    id: 'ing-164', tema: 'conectores', dificultad: 3,
    enunciado: '______ the rain, we decided to go out.',
    opciones: ['Despite', 'Although', 'However', 'Because'],
    correcta: 0,
    explicacion: '"Despite" e "in spite of" van seguidos de un sustantivo o gerundio; "although" necesita una oración completa con sujeto y verbo.',
  },
  {
    id: 'ing-165', tema: 'conectores', dificultad: 4,
    enunciado: "He hardly studied for the test; ______, he passed with a high score.",
    opciones: ['nevertheless', 'therefore', 'moreover', 'thus'],
    correcta: 0,
    explicacion: '"Nevertheless" y "however" introducen un contraste inesperado. "Therefore" y "thus" indicarían consecuencia, y "moreover" añadiría información en la misma línea.',
  },
  {
    id: 'ing-166', tema: 'conectores', dificultad: 4,
    enunciado: '______ she was ill, she went to work.',
    opciones: ['Although', 'Despite', 'However', 'In spite of'],
    correcta: 0,
    explicacion: 'Lo que sigue es una oración con sujeto y verbo ("she was ill"), así que hace falta una conjunción: "although" o "even though". "Despite" e "in spite of" exigirían un sustantivo.',
  },
  {
    id: 'ing-167', tema: 'conectores', dificultad: 4,
    enunciado: 'We left the house early ______ avoid the traffic.',
    opciones: ['in order to', 'for', 'so that', 'because'],
    correcta: 0,
    explicacion: '"In order to" y "so as to" van con infinitivo para expresar propósito. "So that" necesitaría una oración completa ("so that we could avoid...") y "for" no acompaña a un infinitivo en este uso.',
  },
  {
    id: 'ing-168', tema: 'phrasal-verbs', dificultad: 1,
    enunciado: "Please turn ______ the light; it's getting dark.",
    opciones: ['on', 'off', 'up', 'down'],
    correcta: 0,
    explicacion: '"Turn on" es encender y "turn off", apagar. "Turn up" y "turn down" se refieren a subir o bajar el volumen.',
  },
  {
    id: 'ing-169', tema: 'phrasal-verbs', dificultad: 1,
    enunciado: 'I get ______ at seven o’clock every morning.',
    opciones: ['up', 'on', 'in', 'over'],
    correcta: 0,
    explicacion: '"Get up" es levantarse de la cama. "Get on" es subirse a un transporte y "get over", recuperarse de algo.',
  },
  {
    id: 'ing-170', tema: 'phrasal-verbs', dificultad: 3,
    enunciado: 'I ran ______ an old friend downtown yesterday.',
    opciones: ['into', 'out of', 'over', 'after'],
    correcta: 0,
    explicacion: '"Run into somebody" es encontrarse con alguien por casualidad. "Run out of" es quedarse sin algo y "run over", atropellar.',
  },
  {
    id: 'ing-171', tema: 'phrasal-verbs', dificultad: 4,
    enunciado: 'The meeting was called ______ because of the strike.',
    opciones: ['off', 'on', 'up', 'for'],
    correcta: 0,
    explicacion: '"Call off" significa cancelar. "Call on" es visitar o pedir a alguien que intervenga, y "call up", llamar por teléfono.',
  },
  {
    id: 'ing-172', tema: 'phrasal-verbs', dificultad: 4,
    enunciado: 'She takes ______ her mother; they look almost identical.',
    opciones: ['after', 'up', 'over', 'off'],
    correcta: 0,
    explicacion: '"Take after somebody" es parecerse a un familiar. "Take over" es asumir el control y "take off", despegar o quitarse una prenda.',
  },
  {
    id: 'ing-173', tema: 'phrasal-verbs', dificultad: 4,
    enunciado: "I can't put ______ with this noise any longer.",
    opciones: ['up', 'off', 'out', 'away'],
    correcta: 0,
    explicacion: '"Put up with" es tolerar o soportar. Cambiar la partícula cambia el significado por completo: "put off" es aplazar y "put out", apagar un fuego.',
  },
  {
    id: 'ing-174', tema: 'vocabulario', dificultad: 1,
    enunciado: 'What is the opposite of "expensive"?',
    opciones: ['cheap', 'rich', 'large', 'heavy'],
    correcta: 0,
    explicacion: '"Cheap" es barato. "Rich" se refiere a las personas, no a los precios.',
  },
  {
    id: 'ing-175', tema: 'vocabulario', dificultad: 1,
    enunciado: 'A person who treats sick people in a hospital is a ______.',
    opciones: ['doctor', 'lawyer', 'engineer', 'teacher'],
    correcta: 0,
    explicacion: 'Vocabulario básico de profesiones: "lawyer" es abogado, "engineer" ingeniero y "teacher" profesor.',
  },
  {
    id: 'ing-176', tema: 'vocabulario', dificultad: 4,
    enunciado: 'In "Actually, I don’t agree with you", the word "actually" means:',
    opciones: ['in fact', 'currently', 'immediately', 'obviously'],
    correcta: 0,
    explicacion: 'Es un falso amigo clásico: "actually" no significa "actualmente" sino "en realidad". Para "actualmente" se usa "currently" o "nowadays".',
  },
  {
    id: 'ing-177', tema: 'vocabulario', dificultad: 4,
    enunciado: 'If someone says "She is a very sensible person", they mean she is:',
    opciones: ['practical and reasonable', 'easily hurt', 'very emotional', 'extremely intelligent'],
    correcta: 0,
    explicacion: 'Otro falso amigo: "sensible" es sensato. Para "sensible" en el sentido español, el inglés usa "sensitive".',
  },
  {
    id: 'ing-178', tema: 'vocabulario', dificultad: 4,
    enunciado: 'Choose the correct collocation: "We need to ______ a decision before Friday."',
    opciones: ['make', 'do', 'take', 'have'],
    correcta: 0,
    explicacion: 'En inglés las decisiones se "hacen" con "make", no con "take" como en español ni con "do". Las colocaciones se aprenden en bloque: "make a decision", "do homework", "take a photo".',
  },
  {
    id: 'ing-179', tema: 'reading', dificultad: 1, lectura: 'en-t2',
    enunciado: 'How much do cyclists in the Strasbourg scheme receive for each kilometre?',
    opciones: ['About twenty-five cents', 'About one euro', 'About eleven cents', 'The text does not say'],
    correcta: 0,
    explicacion: 'El primer párrafo lo dice: "around twenty-five cents". El once por ciento es el aumento del uso de la bicicleta, no el dinero.',
  },
  {
    id: 'ing-180', tema: 'reading', dificultad: 1, lectura: 'en-t2',
    enunciado: 'According to the text, who pays the cyclists?',
    opciones: ['The employer, who can deduct it from taxes', 'The city council', 'The national government', 'A private foundation'],
    correcta: 0,
    explicacion: 'El texto precisa que lo paga el empleador y que después puede descontarlo de impuestos.',
  },
  {
    id: 'ing-181', tema: 'reading', dificultad: 4, lectura: 'en-t1',
    enunciado: 'What does the text suggest about why tool libraries spread faster after 2008?',
    opciones: [
      'The financial crisis made people reconsider buying equipment they would hardly use',
      'City councils were legally obliged to open them',
      'New tools became much more expensive to manufacture',
      'Volunteers replaced paid staff and reduced costs',
    ],
    correcta: 0,
    explicacion: 'El texto conecta las dos cosas: "much faster after 2008, when the financial crisis made people think twice before buying equipment they rarely needed". No dice que hubiera una obligación legal ni que subieran los costos de fabricación.',
  },
  {
    id: 'ing-182', tema: 'reading', dificultad: 4, lectura: 'en-t2',
    enunciado: 'Which limitation of the Strasbourg study does the text mention?',
    opciones: [
      'It could not establish how many of the new cyclists had previously travelled by bus instead of by car',
      'It only measured results during one month',
      'It did not record how many kilometres people rode',
      'It excluded companies with fewer than fifty employees',
    ],
    correcta: 0,
    explicacion: 'Está en el tercer párrafo. Es una limitación importante: si quienes cambiaron venían del bus, el efecto sobre el tráfico y las emisiones sería mucho menor de lo que sugiere el aumento del once por ciento.',
    pista: 'Busca en el texto la frase que empieza con "though": suele introducir la reserva del autor.',
  },
  {
    id: 'ing-183', tema: 'reading', dificultad: 4, lectura: 'en-t2',
    enunciado: 'Why do critics think the money would be better spent on protected bike lanes?',
    opciones: [
      'Because lanes benefit everybody, not only employees of the companies that joined the scheme',
      'Because building lanes is cheaper than paying cyclists',
      'Because cyclists in the scheme were riding dangerously',
      'Because the city council refused to fund the payments',
    ],
    correcta: 0,
    explicacion: 'El argumento del texto es de alcance: el pago llega solo a quienes trabajan en empresas participantes, mientras que una ciclorruta sirve a cualquiera que pase por ahí. No se menciona el costo comparativo.',
  },
];
