/**
 * lectura.js — Banco de comprensión de lectura.
 *
 * Los textos son originales y están escritos a la medida del examen: entre 180
 * y 250 palabras, con una idea principal clara, datos que se pueden verificar
 * dentro del texto y al menos un lugar donde hay que inferir.
 *
 * Cada pregunta apunta a un texto con el campo `lectura`. Las opciones se
 * barajan al presentarlas (motor.js).
 */

export const LECTURAS = [
  {
    id: 'lec-t1',
    titulo: 'El mosquito que se mudó a la ciudad',
    parrafos: [
      'El Aedes aegypti no es un insecto del monte. Es un animal urbano, tan adaptado a nosotros como las palomas o las ratas. No necesita pantanos ni ríos: le basta con el agua limpia y quieta que se acumula en una llanta vieja, en el plato de una maceta o en un tanque destapado. Una tapa de botella con agua de lluvia puede sostener una generación entera.',
      'Esa domesticidad explica por qué las campañas de fumigación, por sí solas, rinden tan poco. El insecticida mata a los mosquitos adultos que están volando en ese momento, pero no toca los huevos, que resisten secos durante meses y eclosionan en cuanto vuelve a llover. Dos semanas después de la fumigación, el barrio vuelve a estar como antes.',
      'Los programas que sí han reducido los casos de dengue trabajan sobre los criaderos, casa por casa, y dependen de algo que ningún camión puede hacer: que los vecinos revisen sus patios cada semana. Es un trabajo lento, poco vistoso y difícil de fotografiar para un noticiero. Un alcalde que fumiga sale en la televisión; un alcalde que organiza a doscientas familias para vaciar floreros, no.',
      'Mientras el problema se siga midiendo en litros de insecticida y no en criaderos eliminados, seguiremos gastando mucho para cambiar poco.',
    ],
  },
  {
    id: 'lec-t2',
    titulo: 'La economía de la atención',
    parrafos: [
      'Durante siglos, el modelo de negocio de los medios fue vender contenidos a un público. Hoy, en buena parte de internet, es el revés exacto: se vende el público a los anunciantes. El contenido es solo el cebo, y el producto que se entrega es nuestro tiempo de pantalla.',
      'El cambio no es un detalle técnico. Cuando el ingreso depende de cuántos minutos permanecemos mirando, los sistemas que deciden qué vemos no están diseñados para informarnos mejor, sino para retenernos más. Y resulta que lo que mejor retiene no es lo más verdadero ni lo más útil, sino lo que provoca indignación, miedo o curiosidad incompleta.',
      'Quienes defienden estas plataformas responden que nadie obliga a nadie a usarlas. El argumento suena razonable, pero ignora una asimetría evidente: del otro lado de la pantalla hay equipos de ingenieros, psicólogos y millones de experimentos diseñados para vencer exactamente la fuerza de voluntad de un usuario promedio. Llamar "libre elección" a ese enfrentamiento es una manera elegante de no discutir el problema.',
      'No propongo prohibir nada. Propongo algo más modesto: que dejemos de hablar de estas herramientas como si fueran neutrales. Un martillo no tiene ningún interés en que lo uses ocho horas al día.',
    ],
  },
  {
    id: 'lec-t3',
    titulo: 'La casa de la calle Aranjuez',
    parrafos: [
      'Mi abuela vendió la casa un martes de noviembre, sin avisarle a nadie. Cuando llegamos el domingo, con el pan y las ganas de almuerzo de siempre, encontramos la puerta abierta y las paredes desnudas. Ella estaba sentada en una silla de plástico en medio de la sala, con el bolso sobre las rodillas, como si esperara un autobús.',
      '—Ya estaba muy grande esta casa para mí —dijo, y se quedó mirando la mancha clara que había dejado el espejo del recibidor.',
      'Mi madre empezó a hacer cuentas en voz alta: el precio, los papeles, lo que costaría el apartamento nuevo. Mi tío preguntó por los muebles. Nadie preguntó lo otro. Yo tenía once años y tampoco supe preguntarlo, pero recuerdo con exactitud que mi abuela no volvió a mirar hacia el patio en toda la tarde, ni siquiera cuando alguien mencionó el limonero.',
      'Años después entendí que la silla de plástico no era descuido: la había dejado a propósito, para no tener que sentarse en el suelo de una casa que ya no era suya. Nos costó una década entera darnos cuenta de que no nos había pedido permiso porque sabía perfectamente lo que le íbamos a decir.',
    ],
  },
  {
    id: 'lec-t4',
    titulo: 'El problema no es generar, es guardar',
    parrafos: [
      'La discusión sobre energías renovables suele quedarse en el precio de generar un kilovatio hora. Y ahí la batalla ya está ganada: en la última década, el costo de la electricidad solar cayó cerca de un 85 %, y hoy una planta fotovoltaica nueva produce más barato que una térmica a carbón en la mayor parte del mundo.',
      'El obstáculo está en otra parte. El sol alumbra al mediodía y el viento sopla cuando quiere, pero el consumo eléctrico de una ciudad tiene su pico entre las seis y las diez de la noche, justo cuando los paneles dejan de producir. Una red que se abastece de renovables sin almacenamiento produce de sobra a las dos de la tarde y se queda corta a las ocho de la noche.',
      'Por eso las baterías, las represas de bombeo y las redes de interconexión importan tanto como los paneles. Un sistema con 40 % de generación renovable y sin capacidad de guardar energía puede ser menos confiable que uno con 25 % bien respaldado.',
      'Quien celebre solo la cifra de capacidad instalada está mirando la mitad del tablero. La pregunta útil no es cuánto se genera, sino cuánto se puede entregar en el momento en que alguien enciende la luz.',
    ],
  },
  {
    id: 'lec-t5',
    titulo: 'Celulares en el aula',
    parrafos: [
      'El colegio decidió prohibir los celulares durante toda la jornada, y la medida dividió a la comunidad.',
      'Los profesores que la impulsaron señalan un hecho concreto: en las clases donde se recogen los teléfonos al entrar, las intervenciones de los estudiantes aumentaron y las tareas incompletas bajaron. Sostienen que la atención es un recurso limitado y que competir contra una pantalla con notificaciones es una pelea perdida.',
      'Varios padres se oponen. Su argumento principal es la seguridad: quieren poder comunicarse con sus hijos ante cualquier emergencia. Un segundo grupo agrega que prohibir no enseña nada, y que la escuela debería formar en el uso responsable en vez de esconder el problema hasta que los estudiantes se gradúen.',
      'Un tercer argumento circuló en el chat de padres y conviene mirarlo de cerca: "en mis tiempos no había celulares y nadie se murió". La frase es cierta, pero no dice nada sobre la decisión que hay que tomar hoy; que algo funcionara antes no demuestra que sea lo mejor ahora, ni al revés.',
      'La rectoría anunció que revisará la medida al final del semestre con los datos de asistencia, notas y reportes de convivencia. Es, hasta ahora, lo más sensato que se ha dicho en todo el debate.',
    ],
  },
  {
    id: 'lec-t6',
    titulo: 'El cacao antes del chocolate',
    parrafos: [
      'Antes de ser un dulce, el cacao fue una moneda y una bebida amarga. Los mexicas lo tomaban molido con agua, chile y flores, batido hasta levantar espuma, y lo reservaban para guerreros, comerciantes y nobles. Con los granos también se pagaba: en el siglo XVI, un conejo costaba unos treinta granos y una carga de leña unos cinco.',
      'Cuando el cacao llegó a Europa, el sabor no convenció a nadie. Las crónicas de la época lo describen como una bebida oscura, espesa y desagradable. Lo que cambió su destino fue el azúcar, que por entonces empezaba a llegar en cantidad desde las plantaciones del Caribe. Endulzado y servido caliente, el chocolate se volvió una costumbre de la corte española y de ahí pasó al resto del continente.',
      'El paso final llegó en el siglo XIX, cuando una prensa holandesa logró separar la manteca del cacao y obtener un polvo fino que se mezclaba fácilmente. Esa máquina, más que ninguna receta, hizo posible la barra de chocolate que hoy se compra en cualquier tienda.',
      'La historia del chocolate no es la de un alimento que se descubre, sino la de uno que se transforma tres veces hasta volverse irreconocible para quienes lo inventaron.',
    ],
  },
  {
    id: 'lec-t7',
    titulo: 'Carta al director',
    parrafos: [
      'Señor director:',
      'Leí con atención el reportaje del domingo sobre los nuevos buses eléctricos y quiero felicitar a su periódico por el detalle de las cifras. También quiero señalar lo que el reportaje no dijo.',
      'La nota celebra que la flota nueva reduce las emisiones en el centro de la ciudad. Es verdad y es una buena noticia. Pero omite que las tres rutas renovadas son justamente las que ya tenían mejor servicio, y que en los barrios del suroriente, donde vivo, la frecuencia sigue siendo de un bus cada cuarenta minutos en hora pico. Llevo seis años tomando ese bus y puedo asegurarle que la contaminación no es lo primero que uno piensa cuando lleva media hora esperando bajo el sol.',
      'No pido que dejen de informar sobre los avances. Pido que, cuando se publique una cifra de la alcaldía, alguien pregunte también a quién le tocó el avance. Un periódico que solo repite el comunicado de prensa nos deja peor informados que uno que no publica nada, porque nos deja convencidos de que ya sabemos.',
      'Atentamente, Luz Mariana Ordóñez, usuaria de la ruta 14.',
    ],
  },
  {
    id: 'lec-t8',
    titulo: 'Dormir para aprender',
    parrafos: [
      'Durante mucho tiempo se pensó que el sueño era una pausa: el cerebro se apagaba y descansaba. Los estudios de las últimas décadas muestran lo contrario. Mientras dormimos, el cerebro repite en cuestión de segundos las secuencias de actividad que ocurrieron durante el día y las traslada a redes de almacenamiento más estables. Aprender es, en buena parte, dormir después de haber estudiado.',
      'Un experimento clásico lo ilustra bien. Dos grupos de estudiantes memorizan la misma lista de palabras. Uno duerme ocho horas antes de la prueba; el otro permanece despierto el mismo tiempo. El grupo que durmió recuerda sistemáticamente más palabras, aunque ambos hayan dedicado el mismo tiempo a estudiar.',
      'Conviene, eso sí, leer bien lo que muestran estos datos. En las encuestas escolares suele aparecer que los estudiantes que duermen más tienen mejores notas, y de ahí se salta rápido a la conclusión de que dormir mejora el rendimiento. Podría ser al revés: quizá quienes van bien en clase tienen menos trabajo atrasado y por eso duermen más. También podría haber un tercer factor, como hogares más organizados, que explique las dos cosas a la vez.',
      'Los experimentos controlados, no las encuestas, son los que permiten afirmar que el sueño consolida la memoria.',
    ],
  },
  {
    id: 'lec-t9',
    titulo: 'El río que quisieron volver calle',
    parrafos: [
      'A mediados del siglo pasado, casi todas las ciudades de la región hicieron lo mismo con sus ríos urbanos: los enderezaron, los recubrieron de concreto y, en varios casos, los taparon para construir una avenida encima. La lógica de la época era impecable sobre el papel. Un río que se desborda es un problema; un río encauzado en un canal recto evacúa el agua más rápido y libera terreno para el tránsito.',
      'El resultado fue el contrario del esperado. Un canal recto y liso acelera el agua en lugar de retenerla, así que la crecida llega más rápido y con más fuerza al barrio de aguas abajo. Al eliminar las zonas inundables naturales —las vegas, los meandros, los humedales— se eliminó también la esponja que absorbía los picos de lluvia. Cada obra trasladó el problema unos kilómetros río abajo, donde a su vez hubo que construir otro canal.',
      'Varias ciudades están haciendo hoy el camino inverso y descubriendo que sale más caro deshacerlo que no haberlo hecho. Seúl destapó un arroyo que llevaba décadas bajo una autopista y el proyecto costó cientos de millones de dólares.',
      'No es que los ingenieros de entonces fueran torpes. Resolvieron con precisión el problema que se plantearon, que era sacar el agua de la vista lo más rápido posible. El error estuvo en la pregunta, no en la respuesta.',
    ],
  },
  {
    id: 'lec-t10',
    titulo: 'Nadie lee los términos y condiciones',
    parrafos: [
      'Aceptar los términos y condiciones de un servicio digital es, formalmente, firmar un contrato. En la práctica es pulsar un botón. Un estudio calculó que leer todas las políticas de privacidad con las que un usuario promedio se topa en un año le tomaría alrededor de setenta y seis días laborales. Nadie las lee, y el sistema está construido sobre la suposición de que sí.',
      'Se suele responder que el usuario es libre de no aceptar. Formalmente es cierto. Pero la alternativa a aceptar no es usar otro servicio equivalente con mejores condiciones: la alternativa es quedarse sin correo, sin transporte, sin banco o sin el grupo donde su colegio publica las tareas. Llamar elección a eso estira la palabra hasta romperla.',
      'La propuesta de que los textos se escriban en lenguaje sencillo es necesaria pero insuficiente. Un contrato de cuarenta páginas en lenguaje claro sigue siendo un contrato de cuarenta páginas. Las regulaciones que han funcionado no apuestan por que la gente lea más, sino por prohibir de antemano ciertas cláusulas, sin importar que el usuario las haya aceptado.',
      'El consentimiento informado exige dos cosas: consentimiento e información. Hemos construido un sistema que solo cumple la primera, y a veces ni eso.',
    ],
  },
  {
    id: 'lec-t11',
    titulo: 'La maestra de Pueblo Nuevo',
    parrafos: [
      'La señorita Elvira llegó a Pueblo Nuevo con dos maletas y un proyector que no servía. Tenía veintitrés años y era la cuarta maestra en tres años; las tres anteriores se habían ido antes de diciembre.',
      'El primer lunes pidió que cada estudiante llevara al día siguiente un objeto de su casa que tuviera una historia. Mi compañero Aurelio llevó un machete con el mango partido. Otros llevaron fotos, un radio, una piedra del río. Ella no dijo si el ejercicio estaba bien o mal: se sentó en el suelo con nosotros y escuchó.',
      'Cuando el inspector vino en octubre, se molestó porque el cuaderno de planeación estaba incompleto y porque encontró a treinta niños sentados en círculo en el patio en horario de clase. Ella le explicó lo que estábamos haciendo. Él anotó algo y se fue.',
      'Elvira se quedó cuatro años, más que ninguna otra. No transformó el pueblo ni el colegio siguió igual después de ella; las dos cosas se dicen a veces y las dos son falsas. Lo que hizo fue más pequeño y más difícil de contar: nos enseñó que lo que traíamos de la casa también era materia de estudio.',
    ],
  },
  {
    id: 'lec-t12',
    titulo: 'El malvavisco y lo que no decía el experimento',
    parrafos: [
      'A finales de los años sesenta, un experimento puso a niños pequeños frente a un malvavisco con una promesa: si esperaban unos minutos sin comérselo, recibirían dos. Años después, los investigadores reportaron que los niños que habían esperado obtenían mejores resultados académicos. El estudio se volvió célebre y su lectura popular fue simple: la capacidad de aplazar la recompensa predice el éxito.',
      'Esa lectura tenía dos problemas. El primero es de tamaño: participaron poco más de noventa niños, casi todos hijos de estudiantes y profesores de una misma universidad. El segundo es que el experimento medía la conducta, no su causa.',
      'Una replicación posterior, con una muestra mucho mayor y más diversa, encontró que el efecto seguía existiendo pero era bastante menor de lo que se creía, y que buena parte de él desaparecía al tener en cuenta el entorno económico de la familia. Un niño que ha aprendido que las promesas de los adultos no siempre se cumplen está tomando una decisión razonable al comerse el malvavisco de inmediato.',
      'El experimento original no era malo. Lo que falló fue el salto de un resultado acotado a una receta sobre el carácter.',
    ],
  },
  {
    id: 'lec-t13',
    titulo: 'Palabras de apertura',
    parrafos: [
      'Buenas noches. Agradezco la invitación a abrir este festival, y voy a ser breve, que es la única forma verdadera de agradecer una invitación a hablar.',
      'Se ha repetido mucho que este es el festival más grande de su historia: cuarenta y dos grupos, nueve escenarios, tres días. Los números son ciertos y son un logro de mucha gente que no va a subir a este escenario. Pero permítanme decir que no son la razón por la que estamos aquí.',
      'Hace once años este festival era una tarima prestada en una cancha de microfútbol y dos equipos de sonido que se apagaban solos. Lo que había entonces y sigue habiendo ahora es un acuerdo que nadie firmó: que la música de este lugar merece ser escuchada aquí, y no solo cuando alguien de afuera decide que vale la pena.',
      'A quienes vienen por primera vez les pido una sola cosa. Quédense para el último grupo de cada noche, el que toca cuando ya casi no queda nadie. Ahí es donde suele pasar lo mejor, y es el único consejo que tengo.',
      'Bienvenidos, y que empiece.',
    ],
  },
  {
    id: 'lec-t14',
    titulo: 'La cuenta que no aparece en el pasaje',
    parrafos: [
      'Cuando se discute si el transporte público debe ser gratuito, la conversación suele reducirse a una cifra: cuánto cuesta el pasaje. Es la cifra equivocada.',
      'En los sistemas de la región, la tarifa que paga el usuario cubre en promedio entre el 40 % y el 70 % del costo real de operar el servicio. El resto ya lo pone el Estado, es decir, todos los contribuyentes, viajen o no. La pregunta, entonces, nunca ha sido si el transporte se subsidia, sino cuánto y quién lo paga.',
      'Los defensores de la gratuidad señalan que cobrar tiene costos que casi nunca se contabilizan: torniquetes, tarjetas, recaudo, fiscalización y el tiempo que pierden miles de pasajeros haciendo fila. Sus críticos responden con un dato distinto: en las ciudades donde se ha eliminado la tarifa, el aumento de pasajeros ha venido sobre todo de personas que antes caminaban o iban en bicicleta, no de quienes usaban el automóvil.',
      'Las dos observaciones pueden ser ciertas a la vez, y eso es justamente lo incómodo del asunto. Si el objetivo es que la gente deje el carro, la gratuidad por sí sola no parece lograrlo; si el objetivo es que quien menos tiene llegue al trabajo, es probable que sí. Discutir la medida sin decir cuál de los dos objetivos se persigue garantiza que la discusión no termine nunca.',
    ],
  },
];

export const LECTURA = [
  // ----- Texto 1: el mosquito -----
  {
    id: 'lec-001', tema: 'idea-principal', dificultad: 2, lectura: 'lec-t1',
    enunciado: '¿Cuál es la idea principal del texto?',
    opciones: [
      'Fumigar sirve de poco porque el problema son los criaderos domésticos, que exigen trabajo constante de los vecinos',
      'El Aedes aegypti se reproduce en agua limpia y quieta',
      'Los alcaldes prefieren las medidas que salen en televisión',
      'El dengue es una enfermedad urbana que va en aumento',
    ],
    correcta: 0,
    explicacion: 'Las otras opciones son ciertas según el texto, pero son piezas del argumento: el primer dato aparece en el primer párrafo y la crítica a los alcaldes es un ejemplo. La idea que recorre todo el texto es que el control efectivo está en los criaderos y no en la fumigación.',
    pista: 'La idea principal debe cubrir el texto completo, no solo un párrafo.',
  },
  {
    id: 'lec-002', tema: 'detalles', dificultad: 1, lectura: 'lec-t1',
    enunciado: 'Según el texto, ¿por qué la fumigación pierde efecto a las pocas semanas?',
    opciones: [
      'Porque no destruye los huevos, que resisten secos y eclosionan con la lluvia',
      'Porque los mosquitos se vuelven resistentes al insecticida',
      'Porque los vecinos no abren las puertas de sus casas',
      'Porque el insecticida se diluye con el agua de lluvia',
    ],
    correcta: 0,
    explicacion: 'El segundo párrafo lo dice explícitamente: el insecticida mata a los adultos que vuelan en ese momento, pero no toca los huevos.',
  },
  {
    id: 'lec-003', tema: 'inferencias', dificultad: 3, lectura: 'lec-t1',
    enunciado: 'Del contraste entre "un alcalde que fumiga sale en la televisión" y "un alcalde que organiza a doscientas familias, no", se puede inferir que:',
    opciones: [
      'Las decisiones de salud pública a veces se toman pensando en su visibilidad política',
      'Los noticieros están aliados con las empresas de insecticidas',
      'Los vecinos no quieren colaborar con las campañas',
      'Organizar a las familias es imposible en una ciudad grande',
    ],
    correcta: 0,
    explicacion: 'El texto sugiere que lo vistoso se prefiere a lo eficaz, sin llegar a afirmar una alianza con los medios ni culpar a los vecinos. Las otras opciones añaden información que el texto no da.',
  },
  {
    id: 'lec-004', tema: 'vocabulario-contexto', dificultad: 2, lectura: 'lec-t1',
    enunciado: 'En "esa domesticidad explica por qué las campañas rinden tan poco", la palabra domesticidad se refiere a:',
    opciones: [
      'La costumbre del mosquito de vivir dentro de las casas humanas',
      'La docilidad del insecto frente al insecticida',
      'El trabajo doméstico de limpiar los patios',
      'La vida familiar de los vecinos del barrio',
    ],
    correcta: 0,
    explicacion: 'El párrafo anterior describe al mosquito como un animal urbano que se cría en macetas y tanques: domesticidad alude a esa vida dentro del hogar humano.',
  },

  // ----- Texto 2: economía de la atención -----
  {
    id: 'lec-005', tema: 'idea-principal', dificultad: 2, lectura: 'lec-t2',
    enunciado: '¿Cuál es la tesis que defiende el autor?',
    opciones: [
      'Las plataformas no son herramientas neutrales, porque su negocio depende de retener nuestra atención',
      'Las redes sociales deberían prohibirse',
      'La publicidad es la causa de la desinformación',
      'Los usuarios carecen por completo de fuerza de voluntad',
    ],
    correcta: 0,
    explicacion: 'El autor dice expresamente que no propone prohibir nada y que su propuesta es "más modesta": dejar de tratarlas como neutrales.',
  },
  {
    id: 'lec-006', tema: 'argumentacion', dificultad: 3, lectura: 'lec-t2',
    enunciado: '¿Cómo responde el autor al argumento de que "nadie obliga a nadie a usarlas"?',
    opciones: [
      'Señala que hay una asimetría entre el usuario y los equipos que diseñan la plataforma',
      'Afirma que es falso porque el uso es obligatorio en el trabajo',
      'Lo acepta y por eso pide regulación',
      'Responde atacando a quienes defienden las plataformas',
    ],
    correcta: 0,
    explicacion: 'El autor concede que el argumento "suena razonable" y luego lo refuta por la asimetría de recursos. No descalifica a las personas que lo sostienen ni lo declara falso.',
  },
  {
    id: 'lec-007', tema: 'proposito-tono', dificultad: 2, lectura: 'lec-t2',
    enunciado: 'El tono del texto se describe mejor como:',
    opciones: ['Crítico y razonado', 'Nostálgico', 'Neutral y descriptivo', 'Humorístico'],
    correcta: 0,
    explicacion: 'El autor toma partido con claridad y argumenta, pero sin insultos ni exageraciones; concede puntos al adversario antes de responder.',
  },
  {
    id: 'lec-008', tema: 'estructura', dificultad: 3, lectura: 'lec-t2',
    enunciado: '¿Qué función cumple la frase final sobre el martillo?',
    opciones: [
      'Cerrar con una comparación que resume la tesis sobre la neutralidad de las herramientas',
      'Introducir un tema nuevo para un texto posterior',
      'Suavizar la crítica con una broma',
      'Citar la opinión de un experto',
    ],
    correcta: 0,
    explicacion: 'El martillo funciona como contraejemplo de herramienta verdaderamente neutral y condensa en una línea el argumento de todo el texto.',
  },

  // ----- Texto 3: narrativo -----
  {
    id: 'lec-009', tema: 'inferencias', dificultad: 3, lectura: 'lec-t3',
    enunciado: '¿Por qué la abuela vendió la casa sin avisar a la familia?',
    opciones: [
      'Porque sabía que se lo iban a impedir o a discutir',
      'Porque necesitaba el dinero con urgencia',
      'Porque estaba enojada con sus hijos',
      'Porque el comprador le exigió discreción',
    ],
    correcta: 0,
    explicacion: 'La última frase lo dice de forma indirecta: "no nos había pedido permiso porque sabía perfectamente lo que le íbamos a decir".',
  },
  {
    id: 'lec-010', tema: 'detalles', dificultad: 2, lectura: 'lec-t3',
    enunciado: '¿Qué detalle muestra que a la abuela sí le dolía dejar la casa?',
    opciones: [
      'Que no volvió a mirar hacia el patio en toda la tarde',
      'Que llevó una silla de plástico',
      'Que dijo que la casa era muy grande para ella',
      'Que esperaba sentada con el bolso sobre las rodillas',
    ],
    correcta: 0,
    explicacion: 'Evitar mirar el patio, incluso cuando mencionan el limonero, delata lo que la abuela no dice en voz alta. Su frase sobre el tamaño de la casa es precisamente la explicación que da para no hablar del asunto.',
  },
  {
    id: 'lec-011', tema: 'proposito-tono', dificultad: 2, lectura: 'lec-t3',
    enunciado: '¿Qué actitud tiene el narrador adulto hacia lo que pasó aquel domingo?',
    opciones: [
      'Comprende tardíamente algo que de niño no supo preguntar',
      'Reprocha a su abuela la decisión que tomó',
      'Se burla de las cuentas que hacía su madre',
      'Recuerda el episodio con indiferencia',
    ],
    correcta: 0,
    explicacion: 'El narrador dice "años después entendí" y "tampoco supe preguntarlo": hay comprensión retrospectiva, no reproche.',
  },
  {
    id: 'lec-012', tema: 'estructura', dificultad: 3, lectura: 'lec-t3',
    enunciado: '¿Qué aporta la frase "nadie preguntó lo otro"?',
    opciones: [
      'Marca el contraste entre las preocupaciones prácticas de la familia y lo que la abuela sentía',
      'Indica que la familia desconocía el precio de la casa',
      'Revela que había un secreto sobre la herencia',
      'Anuncia que el narrador preguntará más adelante',
    ],
    correcta: 0,
    explicacion: 'Está justo después de las cuentas de la madre y la pregunta del tío por los muebles: señala que todos hablaron de dinero y nadie de la pérdida.',
  },

  // ----- Texto 4: renovables -----
  {
    id: 'lec-013', tema: 'idea-principal', dificultad: 2, lectura: 'lec-t4',
    enunciado: '¿Cuál es el planteamiento central del texto?',
    opciones: [
      'El reto actual de las renovables es el almacenamiento, no el costo de generación',
      'La energía solar todavía es más cara que el carbón',
      'Hay que dejar de instalar paneles solares',
      'El consumo eléctrico de las ciudades es imposible de predecir',
    ],
    correcta: 0,
    explicacion: 'El texto afirma que en costo "la batalla ya está ganada" y dedica el resto a explicar el problema de guardar la energía.',
  },
  {
    id: 'lec-014', tema: 'datos-texto', dificultad: 2, lectura: 'lec-t4',
    enunciado: 'Según el texto, ¿qué afirma el dato de la caída del 85 % en el costo de la electricidad solar?',
    opciones: [
      'Que generar electricidad solar hoy cuesta mucho menos que hace diez años',
      'Que el 85 % de la electricidad mundial ya es solar',
      'Que las plantas solares costaron 85 % menos que las de carbón',
      'Que el consumo eléctrico bajó un 85 %',
    ],
    correcta: 0,
    explicacion: 'El dato se refiere a la caída del costo de generación en la última década, no a la participación en la matriz ni al consumo.',
    pista: 'Vuelve al texto y fíjate exactamente de qué es ese porcentaje.',
  },
  {
    id: 'lec-015', tema: 'inferencias', dificultad: 3, lectura: 'lec-t4',
    enunciado: 'Del ejemplo del sistema con 40 % renovable frente al de 25 % se deduce que:',
    opciones: [
      'Un porcentaje alto de renovables no garantiza por sí solo un servicio confiable',
      'Conviene no pasar del 25 % de generación renovable',
      'Las baterías son más importantes que los paneles',
      'Los sistemas con carbón son siempre más confiables',
    ],
    correcta: 0,
    explicacion: 'El ejemplo muestra que la confiabilidad depende del respaldo, no solo del porcentaje instalado. El texto dice que el almacenamiento importa "tanto como" los paneles, no más.',
  },
  {
    id: 'lec-016', tema: 'vocabulario-contexto', dificultad: 2, lectura: 'lec-t4',
    enunciado: 'En "quien celebre solo la cifra de capacidad instalada está mirando la mitad del tablero", la expresión mirando la mitad del tablero significa:',
    opciones: [
      'Tener en cuenta solo una parte del problema',
      'Equivocarse en la mitad de los cálculos',
      'Observar el juego sin participar',
      'Confundir generación con consumo',
    ],
    correcta: 0,
    explicacion: 'La metáfora del tablero sugiere una visión incompleta de la situación: falta el lado del almacenamiento y la entrega.',
  },

  // ----- Texto 5: celulares -----
  {
    id: 'lec-017', tema: 'argumentacion', dificultad: 2, lectura: 'lec-t5',
    enunciado: '¿Cuál es el argumento principal de los profesores que impulsaron la prohibición?',
    opciones: [
      'Un resultado observado: más participación y menos tareas incompletas donde se recogen los teléfonos',
      'Que los celulares son caros y generan envidia entre estudiantes',
      'Que los padres interrumpen las clases con llamadas',
      'Que la tecnología no sirve para aprender',
    ],
    correcta: 0,
    explicacion: 'El texto presenta ese dato como "un hecho concreto" observado en las clases donde ya se aplica la medida.',
  },
  {
    id: 'lec-018', tema: 'argumentacion', dificultad: 3, lectura: 'lec-t5',
    enunciado: 'El argumento "en mis tiempos no había celulares y nadie se murió" falla porque:',
    opciones: [
      'Apela a cómo eran las cosas antes sin dar razones sobre la decisión actual',
      'Es una afirmación falsa sobre el pasado',
      'Ofende a los profesores del colegio',
      'Confunde causa con consecuencia',
    ],
    correcta: 0,
    explicacion: 'El propio texto lo explica: la frase puede ser cierta y aun así no decir nada sobre qué conviene hacer hoy. Es una apelación a la tradición.',
  },
  {
    id: 'lec-019', tema: 'estructura', dificultad: 2, lectura: 'lec-t5',
    enunciado: '¿Cómo está organizado el texto?',
    opciones: [
      'Presenta la medida, expone las posturas a favor y en contra, examina un argumento débil y cierra con la decisión de revisar los datos',
      'Narra en orden cronológico lo que pasó en el colegio durante el semestre',
      'Defiende desde el principio la prohibición y responde a las objeciones',
      'Compara dos colegios con reglas distintas',
    ],
    correcta: 0,
    explicacion: 'Cada párrafo cumple una de esas funciones, en ese orden.',
  },
  {
    id: 'lec-020', tema: 'proposito-tono', dificultad: 3, lectura: 'lec-t5',
    enunciado: '¿Cuál es la postura del autor del texto?',
    opciones: [
      'No toma partido entre prohibir o no, pero valora que la decisión se evalúe con datos',
      'Está a favor de la prohibición sin reservas',
      'Está en contra de la prohibición',
      'Considera que el debate no tiene ninguna importancia',
    ],
    correcta: 0,
    explicacion: 'La única valoración explícita del autor es la última frase: llama "lo más sensato" a revisar la medida con datos.',
  },

  // ----- Texto 6: cacao -----
  {
    id: 'lec-021', tema: 'detalles', dificultad: 1, lectura: 'lec-t6',
    enunciado: 'Según el texto, ¿cómo tomaban el cacao los mexicas?',
    opciones: [
      'Molido con agua, chile y flores, batido hasta hacer espuma',
      'Caliente y endulzado con azúcar',
      'En polvo fino mezclado con leche',
      'En barras sólidas, como dulce',
    ],
    correcta: 0,
    explicacion: 'Está en el primer párrafo. El azúcar y el polvo fino llegaron después, en Europa.',
  },
  {
    id: 'lec-022', tema: 'estructura', dificultad: 2, lectura: 'lec-t6',
    enunciado: 'El texto está organizado principalmente como:',
    opciones: [
      'Una secuencia cronológica de transformaciones',
      'Una comparación entre dos culturas',
      'Una lista de causas de un mismo efecto',
      'Un problema seguido de su solución',
    ],
    correcta: 0,
    explicacion: 'Va del uso mexica al traslado a Europa y de ahí a la prensa del siglo XIX, en orden temporal, como resume la última frase.',
  },
  {
    id: 'lec-023', tema: 'inferencias', dificultad: 2, lectura: 'lec-t6',
    enunciado: 'Del dato de que un conejo costaba unos treinta granos se puede concluir que:',
    opciones: [
      'Los granos de cacao funcionaban como dinero con precios establecidos',
      'Los conejos eran un alimento de lujo',
      'El cacao era muy barato en esa época',
      'Los mexicas preferían el trueque al dinero',
    ],
    correcta: 0,
    explicacion: 'Que existan precios expresados en granos indica un uso monetario, que es justo lo que el párrafo afirma.',
  },
  {
    id: 'lec-024', tema: 'idea-principal', dificultad: 3, lectura: 'lec-t6',
    enunciado: '¿Cuál sería el mejor título alternativo para el texto?',
    opciones: [
      'Tres transformaciones que convirtieron una bebida amarga en chocolate',
      'La bebida sagrada de los mexicas',
      'El azúcar del Caribe y la corte española',
      'Cómo funciona una prensa de cacao',
    ],
    correcta: 0,
    explicacion: 'Las otras opciones nombran partes del texto; solo la primera cubre el recorrido completo que el propio texto resume al final.',
  },

  // ----- Texto 7: carta -----
  {
    id: 'lec-025', tema: 'proposito-tono', dificultad: 2, lectura: 'lec-t7',
    enunciado: '¿Cuál es el propósito principal de la carta?',
    opciones: [
      'Señalar lo que el reportaje omitió y pedir un periodismo que pregunte a quién beneficia una cifra',
      'Protestar por la compra de buses eléctricos',
      'Solicitar que se aumente la frecuencia de la ruta 14',
      'Felicitar al periódico por su reportaje',
    ],
    correcta: 0,
    explicacion: 'La felicitación inicial es una cortesía; el cuerpo y el cierre de la carta piden explícitamente que se pregunte a quién le tocó el avance.',
  },
  {
    id: 'lec-026', tema: 'proposito-tono', dificultad: 2, lectura: 'lec-t7',
    enunciado: 'El tono de la autora es:',
    opciones: ['Respetuoso pero firme', 'Agresivo', 'Irónico y burlón', 'Indiferente'],
    correcta: 0,
    explicacion: 'Reconoce lo bueno del reportaje, aclara que no pide dejar de informar y al mismo tiempo mantiene su crítica sin descalificar a nadie.',
  },
  {
    id: 'lec-027', tema: 'detalles', dificultad: 1, lectura: 'lec-t7',
    enunciado: 'Según la carta, ¿qué ocurre en los barrios del suroriente?',
    opciones: [
      'La frecuencia sigue siendo de un bus cada cuarenta minutos en hora pico',
      'No llegan los buses eléctricos porque las calles están sin pavimentar',
      'Las emisiones aumentaron tras la renovación de la flota',
      'La ruta 14 fue eliminada del sistema',
    ],
    correcta: 0,
    explicacion: 'Es el dato concreto que la autora aporta desde su experiencia como usuaria.',
  },
  {
    id: 'lec-028', tema: 'argumentacion', dificultad: 3, lectura: 'lec-t7',
    enunciado: '¿Qué quiere decir la autora con que un periódico que solo repite el comunicado "nos deja peor informados que uno que no publica nada"?',
    opciones: [
      'Que la información incompleta produce una falsa sensación de estar informado',
      'Que los periódicos deberían dejar de publicar cifras oficiales',
      'Que los comunicados de la alcaldía contienen datos falsos',
      'Que es mejor no leer noticias sobre transporte',
    ],
    correcta: 0,
    explicacion: 'Ella misma lo explica: "nos deja convencidos de que ya sabemos". El problema no es que el dato sea falso, sino que sea parcial.',
  },

  // ----- Texto 8: sueño -----
  {
    id: 'lec-029', tema: 'idea-principal', dificultad: 2, lectura: 'lec-t8',
    enunciado: '¿Cuál es la idea principal del texto?',
    opciones: [
      'El sueño participa activamente en la consolidación de la memoria, y eso se demuestra con experimentos, no con encuestas',
      'Los estudiantes deberían dormir ocho horas antes de un examen',
      'Las encuestas escolares no sirven para nada',
      'El cerebro descansa mientras dormimos',
    ],
    correcta: 0,
    explicacion: 'El texto combina las dos cosas: qué hace el sueño con la memoria y por qué la evidencia buena viene de experimentos controlados. La última frase lo sintetiza.',
  },
  {
    id: 'lec-030', tema: 'datos-texto', dificultad: 3, lectura: 'lec-t8',
    enunciado: 'Según el texto, ¿por qué la relación entre dormir más y sacar mejores notas en las encuestas no demuestra que dormir mejore el rendimiento?',
    opciones: [
      'Porque la relación podría ir en el sentido contrario o deberse a un tercer factor',
      'Porque las encuestas escolares siempre tienen errores de medición',
      'Porque los estudiantes mienten sobre cuánto duermen',
      'Porque el número de estudiantes encuestados es pequeño',
    ],
    correcta: 0,
    explicacion: 'El texto propone las dos alternativas: que las buenas notas permitan dormir más, o que un tercer factor como la organización del hogar explique ambas cosas.',
    pista: 'Que dos cosas vayan juntas no dice cuál causa cuál.',
  },
  {
    id: 'lec-031', tema: 'inferencias', dificultad: 2, lectura: 'lec-t8',
    enunciado: '¿Por qué el experimento de la lista de palabras sí permite concluir algo que la encuesta no?',
    opciones: [
      'Porque los dos grupos estudian lo mismo y solo se diferencian en si durmieron',
      'Porque participan más estudiantes',
      'Porque se repitió muchas veces a lo largo de los años',
      'Porque mide las notas del curso completo',
    ],
    correcta: 0,
    explicacion: 'Al mantener todo igual excepto el sueño, la diferencia en el recuerdo se puede atribuir al sueño. Esa es la ventaja del experimento controlado.',
  },
  {
    id: 'lec-032', tema: 'vocabulario-contexto', dificultad: 2, lectura: 'lec-t8',
    enunciado: 'En el texto, la palabra consolida (en "el sueño consolida la memoria") significa:',
    opciones: [
      'Hace más estable y duradero lo aprendido',
      'Resume la información para ocupar menos espacio',
      'Une recuerdos distintos en uno solo',
      'Borra los recuerdos poco usados',
    ],
    correcta: 0,
    explicacion: 'El primer párrafo describe el proceso: el cerebro traslada lo aprendido "a redes de almacenamiento más estables".',
  },
  {
    id: 'lec-033', tema: 'datos-texto', dificultad: 3, lectura: 'lec-t4',
    enunciado: 'El texto señala que el consumo eléctrico de una ciudad tiene su pico entre las seis y las diez de la noche. ¿Qué implica ese dato para una red que dependa de energía solar?',
    opciones: [
      'Que la demanda máxima ocurre justo cuando los paneles han dejado de producir',
      'Que conviene instalar más paneles para cubrir esas horas',
      'Que el consumo nocturno es menor que el del mediodía',
      'Que las ciudades deberían consumir menos electricidad de noche',
    ],
    correcta: 0,
    explicacion: 'El texto usa ese dato justo para eso: el desfase entre la hora en que se produce y la hora en que se consume. Añadir paneles no resuelve nada a las ocho de la noche, que es la razón por la que el almacenamiento importa.',
  },
  {
    id: 'lec-034', tema: 'datos-texto', dificultad: 2, lectura: 'lec-t6',
    enunciado: 'Según los precios que da el texto, ¿a cuántas cargas de leña equivalía un conejo?',
    opciones: ['Seis', 'Cinco', 'Treinta', 'Tres'],
    correcta: 0,
    explicacion: 'El conejo costaba unos treinta granos y la carga de leña unos cinco: 30 ÷ 5 = 6 cargas de leña por conejo.',
    pista: 'Los dos precios están en la misma unidad, así que se pueden dividir.',
  },

  // ----- Complemento hasta la meta de 10 por tema -----
  {
    id: 'lec-035', tema: 'idea-principal', dificultad: 2, lectura: 'lec-t9',
    enunciado: '¿Cuál es la idea principal del texto?',
    opciones: [
      'Canalizar los ríos urbanos agravó las inundaciones porque resolvía el problema mal planteado',
      'Los ingenieros del siglo pasado cometieron errores de cálculo',
      'Seúl gastó cientos de millones en destapar un arroyo',
      'Las ciudades de la región crecieron demasiado rápido',
    ],
    correcta: 0,
    explicacion: 'La última frase lo sintetiza: el error estuvo en la pregunta, no en la respuesta. Seúl es un ejemplo y el texto dice expresamente que los ingenieros no fueron torpes.',
  },
  {
    id: 'lec-036', tema: 'detalles', dificultad: 1, lectura: 'lec-t9',
    enunciado: 'Según el texto, ¿qué efecto tiene un canal recto y liso sobre el agua?',
    opciones: [
      'La acelera, de modo que la crecida llega más rápido y con más fuerza aguas abajo',
      'La retiene durante más tiempo en el tramo canalizado',
      'La filtra hacia el subsuelo con mayor facilidad',
      'La reparte de forma pareja a lo largo del año',
    ],
    correcta: 0,
    explicacion: 'Está en el segundo párrafo: el canal acelera el agua en lugar de retenerla.',
  },
  {
    id: 'lec-037', tema: 'estructura', dificultad: 2, lectura: 'lec-t9',
    enunciado: '¿Qué función cumple el tercer párrafo, el que menciona a Seúl?',
    opciones: [
      'Aporta un ejemplo concreto del costo de revertir la obra',
      'Introduce la tesis central del texto',
      'Presenta una objeción a lo dicho antes',
      'Resume las conclusiones del autor',
    ],
    correcta: 0,
    explicacion: 'El párrafo ilustra con un caso real la afirmación de que deshacer la canalización sale más caro que no haberla hecho.',
  },
  {
    id: 'lec-038', tema: 'vocabulario-contexto', dificultad: 2, lectura: 'lec-t9',
    enunciado: 'En el texto, llamar "esponja" a las zonas inundables naturales significa que:',
    opciones: [
      'Absorbían el exceso de agua de las lluvias y lo liberaban poco a poco',
      'Eran terrenos blandos e inestables para construir',
      'Se llenaban de basura y sedimentos',
      'Se secaban por completo en verano',
    ],
    correcta: 0,
    explicacion: 'La metáfora apunta a la capacidad de absorber y soltar despacio, que es justo lo que se perdió al eliminarlas.',
  },
  {
    id: 'lec-039', tema: 'argumentacion', dificultad: 3, lectura: 'lec-t9',
    enunciado: 'Cuando el autor dice que "el error estuvo en la pregunta, no en la respuesta", quiere decir que:',
    opciones: [
      'La obra resolvía bien un objetivo mal definido: sacar el agua de la vista en vez de gestionar la crecida',
      'Los cálculos hidráulicos de la época estaban equivocados',
      'Nadie consultó a los habitantes de los barrios afectados',
      'Faltó presupuesto para terminar las obras correctamente',
    ],
    correcta: 0,
    explicacion: 'El autor concede explícitamente que la solución técnica era precisa. Lo que critica es el planteamiento del problema.',
    pista: 'El párrafo anterior aclara que no fueron torpes.',
  },
  {
    id: 'lec-040', tema: 'proposito-tono', dificultad: 2, lectura: 'lec-t9',
    enunciado: 'El tono del autor hacia los ingenieros del siglo pasado es:',
    opciones: ['Comprensivo pero crítico', 'Abiertamente burlón', 'Admirativo sin reservas', 'Indiferente'],
    correcta: 0,
    explicacion: 'Reconoce su competencia técnica y al mismo tiempo señala el error de fondo. Esa combinación es lo que define un tono crítico sin descalificación.',
  },
  {
    id: 'lec-041', tema: 'datos-texto', dificultad: 3, lectura: 'lec-t9',
    enunciado: 'El texto dice que cada obra "trasladó el problema unos kilómetros río abajo". ¿Qué se puede afirmar a partir de eso?',
    opciones: [
      'Que las canalizaciones no eliminaron el riesgo de inundación, sino que lo desplazaron a otro lugar',
      'Que las inundaciones desaparecieron en toda la cuenca',
      'Que el caudal total del río aumentó por la obra',
      'Que los barrios de aguas arriba quedaron desprotegidos',
    ],
    correcta: 0,
    explicacion: 'Desplazar no es eliminar: por eso, según el texto, aguas abajo hubo que construir otro canal. Los que quedan desprotegidos son los de abajo, no los de arriba.',
  },
  {
    id: 'lec-042', tema: 'idea-principal', dificultad: 2, lectura: 'lec-t10',
    enunciado: '¿Cuál es la tesis del autor?',
    opciones: [
      'El consentimiento digital actual es ficticio porque falta la parte informada',
      'Los términos y condiciones deberían eliminarse',
      'Los usuarios son negligentes por no leer lo que aceptan',
      'Las empresas digitales deberían ser prohibidas',
    ],
    correcta: 0,
    explicacion: 'El cierre lo resume: el consentimiento informado exige consentimiento e información, y el sistema solo cumple la primera. El autor no culpa al usuario.',
  },
  {
    id: 'lec-043', tema: 'detalles', dificultad: 1, lectura: 'lec-t10',
    enunciado: 'Según el estudio que cita el texto, leer todas las políticas de privacidad de un año tomaría:',
    opciones: ['Unos setenta y seis días laborales', 'Unas cuarenta páginas', 'Alrededor de un mes completo', 'Once años'],
    correcta: 0,
    explicacion: 'Es el dato del primer párrafo. Las cuarenta páginas aparecen después, en otro argumento.',
  },
  {
    id: 'lec-044', tema: 'argumentacion', dificultad: 3, lectura: 'lec-t10',
    enunciado: '¿Cómo responde el autor al argumento de que "el usuario es libre de no aceptar"?',
    opciones: [
      'Reconoce que es cierto formalmente, pero señala que la alternativa real es quedarse sin servicios esenciales',
      'Sostiene que el argumento es una mentira de las empresas',
      'Afirma que nadie ha dicho nunca eso en serio',
      'Responde que la ley prohíbe esa libertad',
    ],
    correcta: 0,
    explicacion: 'Concede primero y refuta después, igual que hace un buen argumento: no niega la libertad formal, discute que sea una elección real.',
  },
  {
    id: 'lec-045', tema: 'argumentacion', dificultad: 3, lectura: 'lec-t10',
    enunciado: 'Según el texto, ¿por qué escribir los términos en lenguaje sencillo no resuelve el problema?',
    opciones: [
      'Porque el obstáculo no es solo el lenguaje sino la extensión y la cantidad de contratos',
      'Porque los usuarios no entienden ni el lenguaje sencillo',
      'Porque las empresas se negarían a hacerlo',
      'Porque los contratos claros no tienen validez legal',
    ],
    correcta: 0,
    explicacion: 'El autor lo dice con una frase directa: un contrato de cuarenta páginas en lenguaje claro sigue siendo un contrato de cuarenta páginas.',
  },
  {
    id: 'lec-046', tema: 'vocabulario-contexto', dificultad: 3, lectura: 'lec-t10',
    enunciado: 'En "llamar elección a eso estira la palabra hasta romperla", la expresión subrayada indica que:',
    opciones: [
      'El término se usa tan lejos de su sentido real que deja de significar algo',
      'La palabra elección tiene varios significados posibles',
      'El autor propone inventar una palabra nueva',
      'La palabra se usa demasiado en los medios',
    ],
    correcta: 0,
    explicacion: 'La imagen de estirar hasta romper sugiere un uso forzado que vacía el término de contenido.',
  },
  {
    id: 'lec-047', tema: 'vocabulario-contexto', dificultad: 2, lectura: 'lec-t10',
    enunciado: 'En el texto, "insuficiente" (referido a escribir en lenguaje sencillo) significa que la medida es:',
    opciones: [
      'Necesaria, pero no basta por sí sola para resolver el problema',
      'Inútil y contraproducente',
      'Imposible de aplicar en la práctica',
      'Excesiva para el problema que enfrenta',
    ],
    correcta: 0,
    explicacion: 'El propio texto la califica de "necesaria pero insuficiente": las dos cosas a la vez. Confundir insuficiente con inútil cambia el sentido.',
  },
  {
    id: 'lec-048', tema: 'estructura', dificultad: 2, lectura: 'lec-t10',
    enunciado: '¿Cómo está organizado el texto?',
    opciones: [
      'Expone el problema, responde a una objeción, descarta una solución parcial y cierra con una definición',
      'Narra en orden cronológico la historia de los contratos digitales',
      'Compara dos servicios digitales distintos',
      'Presenta una lista de recomendaciones para el usuario',
    ],
    correcta: 0,
    explicacion: 'Cada párrafo cumple una de esas funciones en ese orden, y el último cierra volviendo al concepto de consentimiento informado.',
  },
  {
    id: 'lec-049', tema: 'proposito-tono', dificultad: 2, lectura: 'lec-t10',
    enunciado: 'El propósito principal del texto es:',
    opciones: [
      'Persuadir de que el problema no se arregla pidiéndole más al usuario, sino regulando las cláusulas',
      'Informar sobre cómo funcionan los contratos digitales',
      'Narrar la evolución de las políticas de privacidad',
      'Enseñar a leer un contrato en menos tiempo',
    ],
    correcta: 0,
    explicacion: 'El tercer párrafo señala qué regulaciones han funcionado: las que prohíben cláusulas de antemano, sin depender de que la gente lea.',
  },
  {
    id: 'lec-050', tema: 'idea-principal', dificultad: 3, lectura: 'lec-t11',
    enunciado: '¿Cuál sería el mejor título alternativo para el texto?',
    opciones: [
      'La maestra que se quedó y lo que nos enseñó a traer de casa',
      'El inspector que no entendió nada',
      'Cuatro maestras en tres años',
      'Cómo transformar una escuela rural',
    ],
    correcta: 0,
    explicacion: 'El narrador rechaza expresamente la idea de transformación y el inspector es un episodio menor. El texto gira en torno a la permanencia de Elvira y a lo que hizo con lo que los niños traían de su casa.',
  },
  {
    id: 'lec-051', tema: 'detalles', dificultad: 1, lectura: 'lec-t11',
    enunciado: '¿Qué pidió la maestra el primer lunes?',
    opciones: [
      'Que cada estudiante llevara un objeto de su casa con una historia',
      'Que escribieran una redacción sobre sus vacaciones',
      'Que trajeran el cuaderno de planeación al día',
      'Que se sentaran en círculo en el patio',
    ],
    correcta: 0,
    explicacion: 'Está en el segundo párrafo. El círculo en el patio es lo que vio el inspector meses después.',
  },
  {
    id: 'lec-052', tema: 'inferencias', dificultad: 3, lectura: 'lec-t11',
    enunciado: 'Del dato de que Elvira era la cuarta maestra en tres años se puede inferir que:',
    opciones: [
      'La escuela tenía dificultades para retener docentes',
      'Las maestras anteriores fueron despedidas por incompetentes',
      'El pueblo rechazaba a los maestros de afuera',
      'La escuela había crecido y necesitaba más personal',
    ],
    correcta: 0,
    explicacion: 'El texto dice que las tres anteriores se fueron antes de diciembre, lo que apunta a rotación, no a despidos ni a rechazo. Las otras opciones añaden causas que el texto no da.',
  },
  {
    id: 'lec-053', tema: 'proposito-tono', dificultad: 2, lectura: 'lec-t11',
    enunciado: '¿Qué actitud tiene el narrador hacia la maestra?',
    opciones: [
      'Reconocimiento sereno, sin exageraciones ni idealización',
      'Admiración desbordada por una figura heroica',
      'Resentimiento por lo que no logró',
      'Distancia irónica hacia lo que ocurrió',
    ],
    correcta: 0,
    explicacion: 'El último párrafo desmonta las dos frases hechas —que transformó el pueblo y que el colegio nunca fue el mismo— y sitúa el valor de su trabajo en algo más modesto.',
  },
  {
    id: 'lec-054', tema: 'inferencias', dificultad: 3, lectura: 'lec-t11',
    enunciado: '¿Por qué se molestó el inspector?',
    opciones: [
      'Porque evaluó la clase con criterios formales: papeles al día y estudiantes dentro del aula',
      'Porque los estudiantes no estaban aprendiendo nada',
      'Porque la maestra le respondió de mala manera',
      'Porque el proyector no funcionaba',
    ],
    correcta: 0,
    explicacion: 'Los dos motivos que da el texto son el cuaderno de planeación incompleto y los niños en el patio: ambos son formales, no de aprendizaje.',
  },
  {
    id: 'lec-055', tema: 'estructura', dificultad: 2, lectura: 'lec-t11',
    enunciado: '¿Qué aporta el último párrafo al relato?',
    opciones: [
      'Corrige las conclusiones grandilocuentes que se esperarían y precisa el verdadero alcance de lo ocurrido',
      'Introduce un personaje nuevo que cambia la historia',
      'Explica por qué la maestra terminó yéndose',
      'Resume cronológicamente los cuatro años',
    ],
    correcta: 0,
    explicacion: 'El narrador nombra dos conclusiones habituales, dice que las dos son falsas y ofrece en su lugar una más pequeña y más precisa.',
  },
  {
    id: 'lec-056', tema: 'vocabulario-contexto', dificultad: 2, lectura: 'lec-t11',
    enunciado: 'Cuando el narrador dice que lo que hizo Elvira fue "más difícil de contar", se refiere a que:',
    opciones: [
      'Fue un cambio real pero sutil, que no cabe en una frase efectista',
      'Nadie recuerda bien lo que ocurrió',
      'La maestra pidió que no se hablara de ello',
      'Los hechos ocurrieron hace demasiado tiempo',
    ],
    correcta: 0,
    explicacion: 'Se opone a las dos frases grandilocuentes que acaba de descartar: lo pequeño y verdadero se cuenta peor que lo grande y falso.',
  },
  {
    id: 'lec-057', tema: 'idea-principal', dificultad: 2, lectura: 'lec-t12',
    enunciado: '¿Cuál es la idea principal del texto?',
    opciones: [
      'La lectura popular del experimento fue más allá de lo que sus datos permitían concluir',
      'El experimento del malvavisco fue un fraude científico',
      'La capacidad de esperar no tiene ninguna relación con los resultados académicos',
      'Los estudios con niños pequeños no son confiables',
    ],
    correcta: 0,
    explicacion: 'El cierre lo dice expresamente: el experimento original no era malo; falló el salto de un resultado acotado a una receta sobre el carácter. El texto tampoco niega que el efecto exista.',
  },
  {
    id: 'lec-058', tema: 'datos-texto', dificultad: 3, lectura: 'lec-t12',
    enunciado: 'Según el texto, ¿por qué el tamaño de la muestra original es un problema?',
    opciones: [
      'Porque poco más de noventa niños de un entorno muy parecido no representan a la población general',
      'Porque noventa niños son demasiados para controlar el experimento',
      'Porque los niños eran muy pequeños para entender las reglas',
      'Porque no se midió cuántos comieron el malvavisco',
    ],
    correcta: 0,
    explicacion: 'El texto subraya las dos cosas: eran pocos y además casi todos hijos de estudiantes y profesores de una misma universidad. La homogeneidad es tan problemática como el número.',
  },
  {
    id: 'lec-059', tema: 'datos-texto', dificultad: 3, lectura: 'lec-t12',
    enunciado: '¿Qué encontró la replicación posterior?',
    opciones: [
      'Que el efecto existía pero era menor, y que buena parte se explicaba por el entorno económico familiar',
      'Que el efecto no existía en absoluto',
      'Que el efecto era todavía mayor de lo reportado',
      'Que los niños de familias acomodadas esperaban menos',
    ],
    correcta: 0,
    explicacion: 'Es exactamente lo que dice el tercer párrafo. Conviene no confundir "menor de lo que se creía" con "inexistente".',
  },
  {
    id: 'lec-060', tema: 'inferencias', dificultad: 3, lectura: 'lec-t12',
    enunciado: 'Según el texto, ¿por qué un niño podría comerse el malvavisco de inmediato por una razón sensata?',
    opciones: [
      'Porque ha aprendido que las promesas de los adultos no siempre se cumplen',
      'Porque tiene más hambre que los demás',
      'Porque no entiende las instrucciones del experimento',
      'Porque le gusta más el sabor que la recompensa doble',
    ],
    correcta: 0,
    explicacion: 'El texto lo plantea como una decisión razonable dada su experiencia previa: si la segunda porción es incierta, tomar la segura es lo racional.',
  },
  {
    id: 'lec-061', tema: 'estructura', dificultad: 2, lectura: 'lec-t12',
    enunciado: '¿Qué función cumple el segundo párrafo?',
    opciones: [
      'Enumera las dos objeciones que el autor hará al estudio y que desarrollará después',
      'Presenta la conclusión del texto',
      'Describe el procedimiento del experimento',
      'Aporta un ejemplo de aplicación práctica',
    ],
    correcta: 0,
    explicacion: 'Anuncia el problema de tamaño y el de causalidad, y el párrafo siguiente desarrolla ambos con la replicación.',
  },
  {
    id: 'lec-062', tema: 'detalles', dificultad: 1, lectura: 'lec-t12',
    enunciado: 'Según el texto, ¿qué recibían los niños que esperaban?',
    opciones: ['Dos malvaviscos', 'Un premio en dinero', 'Un diploma', 'Nada: solo se medía la espera'],
    correcta: 0,
    explicacion: 'La promesa era recibir dos si aguantaban unos minutos sin comerse el primero.',
  },
  {
    id: 'lec-063', tema: 'argumentacion', dificultad: 3, lectura: 'lec-t12',
    enunciado: 'El autor sostiene que el experimento "medía la conducta, no su causa". ¿Qué implica esa distinción?',
    opciones: [
      'Que saber quién esperó no dice por qué esperó, y las razones pueden cambiar por completo la conclusión',
      'Que el experimento no midió nada con precisión',
      'Que la conducta observada era falsa',
      'Que habría hecho falta un grupo de control',
    ],
    correcta: 0,
    explicacion: 'Es la distinción entre describir y explicar. El ejemplo del niño que desconfía de las promesas muestra cómo una causa distinta produce la misma conducta.',
  },
  {
    id: 'lec-064', tema: 'proposito-tono', dificultad: 2, lectura: 'lec-t13',
    enunciado: '¿Cuál es el propósito principal del discurso?',
    opciones: [
      'Abrir el festival recordando su origen y lo que lo sostiene, más allá de las cifras',
      'Agradecer a los organizadores y patrocinadores',
      'Convencer al público de asistir los tres días',
      'Presentar a los cuarenta y dos grupos participantes',
    ],
    correcta: 0,
    explicacion: 'El orador reconoce los números y acto seguido dice que no son la razón por la que están ahí; el resto lo dedica al origen y al acuerdo que lo sostiene.',
  },
  {
    id: 'lec-065', tema: 'proposito-tono', dificultad: 2, lectura: 'lec-t13',
    enunciado: 'El tono del discurso es:',
    opciones: ['Cercano y algo irónico consigo mismo', 'Solemne y distante', 'Crítico con los organizadores', 'Nostálgico y triste'],
    correcta: 0,
    explicacion: 'La broma sobre agradecer siendo breve y el consejo final marcan un registro cercano, sin solemnidad y sin reproches.',
  },
  {
    id: 'lec-066', tema: 'detalles', dificultad: 1, lectura: 'lec-t13',
    enunciado: '¿Cómo describe el orador el festival de hace once años?',
    opciones: [
      'Una tarima prestada en una cancha de microfútbol con dos equipos de sonido que fallaban',
      'Un festival de nueve escenarios en tres días',
      'Un evento organizado por artistas de afuera',
      'Una reunión privada sin público',
    ],
    correcta: 0,
    explicacion: 'Está en el tercer párrafo. Los nueve escenarios corresponden a la edición actual.',
  },
  {
    id: 'lec-067', tema: 'inferencias', dificultad: 3, lectura: 'lec-t13',
    enunciado: 'Al decir que la música del lugar merece ser escuchada allí "y no solo cuando alguien de afuera decide que vale la pena", el orador sugiere que:',
    opciones: [
      'La validación externa no debería ser la condición para reconocer lo propio',
      'Los artistas de fuera no deberían participar en el festival',
      'El público local no asistía a los conciertos',
      'El festival debería dejar de crecer',
    ],
    correcta: 0,
    explicacion: 'La frase reivindica el valor propio sin esperar el permiso de nadie. No dice nada en contra de los visitantes ni del crecimiento.',
  },
  {
    id: 'lec-068', tema: 'estructura', dificultad: 2, lectura: 'lec-t13',
    enunciado: '¿Qué función cumple el penúltimo párrafo, el del consejo sobre el último grupo de cada noche?',
    opciones: [
      'Cierra con una recomendación concreta que resume el espíritu del festival',
      'Presenta las reglas de asistencia del evento',
      'Introduce una crítica a la programación',
      'Enumera a los grupos más importantes',
    ],
    correcta: 0,
    explicacion: 'El consejo apunta a lo pequeño y poco visible, que es justo lo que el discurso viene defendiendo frente a los números grandes.',
  },
  {
    id: 'lec-069', tema: 'argumentacion', dificultad: 3, lectura: 'lec-t13',
    enunciado: '¿Qué hace el orador con la cifra de los cuarenta y dos grupos?',
    opciones: [
      'La acepta como cierta y como un logro, pero le niega el papel central',
      'La pone en duda por exagerada',
      'La usa como argumento principal del discurso',
      'La atribuye a los patrocinadores del evento',
    ],
    correcta: 0,
    explicacion: 'Dice que los números son ciertos y un logro de mucha gente, y acto seguido introduce un "pero" que los desplaza del centro. Conceder antes de matizar es una estrategia argumentativa.',
  },
  {
    id: 'lec-070', tema: 'vocabulario-contexto', dificultad: 2, lectura: 'lec-t13',
    enunciado: 'En el texto, "un acuerdo que nadie firmó" se refiere a:',
    opciones: [
      'Un compromiso compartido de forma implícita por la comunidad',
      'Un contrato que quedó sin validez legal',
      'Una promesa incumplida por los organizadores',
      'Un convenio con el municipio que no se concretó',
    ],
    correcta: 0,
    explicacion: 'La expresión juega con la idea de contrato para nombrar algo tácito: nadie lo firmó y sin embargo todos lo sostienen.',
  },
  {
    id: 'lec-071', tema: 'idea-principal', dificultad: 3, lectura: 'lec-t14',
    enunciado: '¿Cuál es el planteamiento central del texto?',
    opciones: [
      'La discusión sobre la gratuidad del transporte es estéril mientras no se defina qué objetivo se persigue',
      'El transporte público debería ser gratuito en toda la región',
      'La tarifa actual es demasiado alta para los usuarios',
      'Eliminar la tarifa no reduce el uso del automóvil',
    ],
    correcta: 0,
    explicacion: 'El último párrafo es explícito: discutir la medida sin decir cuál de los dos objetivos se persigue garantiza que la discusión no termine nunca. El dato sobre el automóvil es un argumento dentro del texto, no su tesis.',
  },
  {
    id: 'lec-072', tema: 'datos-texto', dificultad: 2, lectura: 'lec-t14',
    enunciado: 'Según el texto, ¿qué proporción del costo real de operación cubre la tarifa que paga el usuario?',
    opciones: [
      'Entre el 40 % y el 70 %, en promedio, en los sistemas de la región',
      'El 100 %, por eso no hace falta subsidio',
      'Menos del 10 %',
      'El texto no aporta ninguna cifra',
    ],
    correcta: 0,
    explicacion: 'Es el dato del segundo párrafo, y con él el autor demuestra que el transporte ya está subsidiado hoy.',
  },
  {
    id: 'lec-073', tema: 'datos-texto', dificultad: 3, lectura: 'lec-t14',
    enunciado: '¿Qué conclusión permite el dato de que el aumento de pasajeros vino de personas que antes caminaban o iban en bicicleta?',
    opciones: [
      'Que la gratuidad, por sí sola, no logra que la gente deje el automóvil',
      'Que la gratuidad no aumenta el número de pasajeros',
      'Que caminar es más costoso que usar el transporte público',
      'Que los automovilistas dejaron de viajar',
    ],
    correcta: 0,
    explicacion: 'Si los nuevos pasajeros no venían del carro, el efecto sobre el tráfico es mínimo. El dato sí confirma que los pasajeros aumentaron.',
    pista: 'Fíjate de dónde venían los pasajeros nuevos.',
  },
  {
    id: 'lec-074', tema: 'argumentacion', dificultad: 3, lectura: 'lec-t14',
    enunciado: 'El autor afirma que las observaciones de defensores y críticos "pueden ser ciertas a la vez". ¿Por qué?',
    opciones: [
      'Porque responden a preguntas distintas: una sobre los costos de cobrar y otra sobre quién se suma al sistema',
      'Porque ninguna de las dos está respaldada por datos',
      'Porque los dos grupos usan las mismas cifras',
      'Porque el autor no quiere tomar partido',
    ],
    correcta: 0,
    explicacion: 'No se contradicen: el ahorro por dejar de cobrar y el origen de los nuevos pasajeros son hechos independientes. Por eso el desacuerdo real está en el objetivo, no en los datos.',
  },
  {
    id: 'lec-075', tema: 'detalles', dificultad: 2, lectura: 'lec-t14',
    enunciado: 'Según el texto, ¿qué costos de cobrar señalan los defensores de la gratuidad?',
    opciones: [
      'Torniquetes, tarjetas, recaudo, fiscalización y el tiempo perdido en filas',
      'El costo del combustible y el mantenimiento de los buses',
      'Los subsidios que paga el Estado cada año',
      'La construcción de nuevas estaciones',
    ],
    correcta: 0,
    explicacion: 'Es la lista del tercer párrafo: el argumento es que cobrar también cuesta dinero y tiempo.',
  },
  {
    id: 'lec-076', tema: 'estructura', dificultad: 2, lectura: 'lec-t14',
    enunciado: '¿Cómo organiza el autor su exposición?',
    opciones: [
      'Descarta la cifra habitual, aporta el dato que reencuadra el problema, contrapone dos posturas y cierra señalando la pregunta de fondo',
      'Narra la historia del transporte público en la región',
      'Defiende la gratuidad y responde a las objeciones',
      'Compara los sistemas de dos ciudades concretas',
    ],
    correcta: 0,
    explicacion: 'Cada párrafo cumple una de esas funciones, y el texto no defiende ninguna de las dos posturas.',
  },
  {
    id: 'lec-077', tema: 'vocabulario-contexto', dificultad: 2, lectura: 'lec-t14',
    enunciado: 'En el título, "la cuenta que no aparece en el pasaje" se refiere a:',
    opciones: [
      'La parte del costo del servicio que pagan todos los contribuyentes y no el usuario',
      'El precio real del boleto antes de impuestos',
      'La deuda que tienen las empresas operadoras',
      'El dinero que pierden los pasajeros en las filas',
    ],
    correcta: 0,
    explicacion: 'El segundo párrafo explica que la tarifa cubre solo una parte y el resto lo pone el Estado: eso es lo que el pasaje no muestra.',
  },
  {
    id: 'lec-078', tema: 'inferencias', dificultad: 3, lectura: 'lec-t14',
    enunciado: 'Del texto se deduce que, para el autor, la pregunta "¿debe subsidiarse el transporte?" está mal planteada porque:',
    opciones: [
      'El transporte ya se subsidia: lo que está en discusión es la magnitud y el reparto de ese subsidio',
      'Los subsidios siempre son perjudiciales',
      'El transporte público no necesita recursos públicos',
      'Los usuarios pagan el costo completo del servicio',
    ],
    correcta: 0,
    explicacion: 'El texto lo dice de forma casi literal: la pregunta nunca ha sido si el transporte se subsidia, sino cuánto y quién lo paga.',
  },
  {
    id: 'lec-079', tema: 'inferencias', dificultad: 2, lectura: 'lec-t14',
    enunciado: 'Según el texto, si el objetivo fuera que quien menos tiene llegue al trabajo, la gratuidad:',
    opciones: [
      'Probablemente sí serviría, aunque no reduzca el uso del automóvil',
      'Sería igualmente inútil',
      'Debería aplicarse solo en horas pico',
      'Tendría que financiarse con un aumento de impuestos a los automovilistas',
    ],
    correcta: 0,
    explicacion: 'El último párrafo distingue los dos objetivos: para el del automóvil la medida no parece bastar, para el del acceso probablemente sí.',
  },
  {
    id: 'lec-080', tema: 'proposito-tono', dificultad: 2, lectura: 'lec-t14',
    enunciado: 'La postura del autor frente a la gratuidad del transporte es:',
    opciones: [
      'No se pronuncia a favor ni en contra: exige que se aclare el objetivo antes de decidir',
      'Está claramente a favor',
      'Está claramente en contra',
      'Considera que el tema carece de importancia',
    ],
    correcta: 0,
    explicacion: 'Presenta los argumentos de los dos lados y los reconoce compatibles. Su crítica es al modo de discutir, no a ninguna de las dos posiciones.',
  },
  {
    id: 'lec-081', tema: 'vocabulario-contexto', dificultad: 2, lectura: 'lec-t12',
    enunciado: 'En el texto, una "replicación" de un estudio es:',
    opciones: [
      'Repetirlo con otra muestra para comprobar si el resultado se sostiene',
      'Publicarlo de nuevo en otra revista',
      'Copiar sus conclusiones en un libro de divulgación',
      'Ampliar el experimento con una pregunta distinta',
    ],
    correcta: 0,
    explicacion: 'El texto la describe en funcionamiento: una muestra mayor y más diversa que pone a prueba el hallazgo original. Es el mecanismo con el que la ciencia se corrige a sí misma.',
  },
  {
    id: 'lec-082', tema: 'datos-texto', dificultad: 2, lectura: 'lec-t10',
    enunciado: '¿Qué uso hace el autor del dato de los setenta y seis días laborales?',
    opciones: [
      'Mostrar que leer todas las políticas es materialmente imposible, no una cuestión de voluntad',
      'Calcular cuánto dinero pierden los usuarios al año',
      'Comparar la extensión de dos contratos distintos',
      'Demostrar que las empresas alargan los textos a propósito',
    ],
    correcta: 0,
    explicacion: 'La cifra sostiene la frase siguiente: nadie las lee y el sistema supone que sí. El texto no afirma que la extensión sea deliberada.',
  },

  // ----- Textos discontinuos: leer gráficas -----
  {
    id: 'lec-083', tema: 'discontinuos', dificultad: 2,
    grafico: {
      tipo: 'barras', titulo: 'Estudiantes matriculados (en miles)', ejeY: 'miles',
      datos: [
        { etiqueta: '2019', valor: 32 }, { etiqueta: '2020', valor: 28 },
        { etiqueta: '2021', valor: 35 }, { etiqueta: '2022', valor: 41 },
      ],
    },
    enunciado: '¿Cuál fue el aumento de la matrícula entre 2020 y 2022?',
    opciones: ['13 mil estudiantes', '41 mil estudiantes', '9 mil estudiantes', '28 mil estudiantes'],
    correcta: 0,
    explicacion: '41 − 28 = 13 mil. La pregunta pide una diferencia, no el valor de una barra: leer solo el último dato es el error más común.',
  },
  {
    id: 'lec-084', tema: 'discontinuos', dificultad: 1,
    grafico: {
      tipo: 'barras', titulo: 'Material reciclado en el mes (toneladas)', ejeY: 'ton',
      datos: [
        { etiqueta: 'Papel', valor: 120 }, { etiqueta: 'Vidrio', valor: 85 },
        { etiqueta: 'Plástico', valor: 60 }, { etiqueta: 'Metal', valor: 35 },
      ],
    },
    enunciado: '¿Cuántas toneladas más de papel que de plástico se reciclaron?',
    opciones: ['60', '120', '180', '25'],
    correcta: 0,
    explicacion: '120 − 60 = 60 toneladas. También se puede decir que se recicló el doble de papel que de plástico.',
  },
  {
    id: 'lec-085', tema: 'discontinuos', dificultad: 3,
    grafico: {
      tipo: 'lineas', titulo: 'Hogares con acceso a internet (%)', ejeY: '%',
      etiquetas: ['2018', '2019', '2020', '2021', '2022'],
      series: [
        { nombre: 'Urbano', valores: [62, 64, 67, 70, 72] },
        { nombre: 'Rural', valores: [38, 37, 35, 34, 32] },
      ],
    },
    enunciado: '¿Qué afirmación describe correctamente lo que muestra el gráfico?',
    opciones: [
      'La brecha entre lo urbano y lo rural se amplió durante el periodo',
      'Las dos zonas mejoraron su acceso a internet',
      'El acceso rural creció más lento que el urbano, pero creció',
      'La brecha se mantuvo constante',
    ],
    correcta: 0,
    explicacion: 'En 2018 la diferencia era de 24 puntos y en 2022 de 40. Además el acceso rural no creció más lento: bajó, que es distinto.',
    pista: 'Calcula la distancia entre las dos líneas al principio y al final.',
  },
  {
    id: 'lec-086', tema: 'discontinuos', dificultad: 2,
    grafico: {
      tipo: 'circular', titulo: 'Distribución del gasto mensual de un hogar',
      datos: [
        { etiqueta: 'Vivienda', valor: 35 }, { etiqueta: 'Alimentación', valor: 28 },
        { etiqueta: 'Transporte', valor: 15 }, { etiqueta: 'Educación', valor: 12 },
        { etiqueta: 'Otros', valor: 10 },
      ],
    },
    enunciado: '¿Qué porcentaje del gasto se destina en conjunto a vivienda y alimentación?',
    opciones: ['63 %', '35 %', '28 %', '73 %'],
    correcta: 0,
    explicacion: '35 + 28 = 63 %. Casi dos terceras partes del presupuesto se van en esos dos rubros.',
  },
  {
    id: 'lec-087', tema: 'discontinuos', dificultad: 2,
    grafico: {
      tipo: 'pictograma', titulo: 'Libros prestados por mes', unidad: 50, nombreUnidad: 'libros',
      filas: [
        { etiqueta: 'Marzo', valor: 200 }, { etiqueta: 'Abril', valor: 300 }, { etiqueta: 'Mayo', valor: 150 },
      ],
    },
    enunciado: '¿Cuántos libros más se prestaron en abril que en mayo?',
    opciones: ['150', '3', '300', '450'],
    correcta: 0,
    explicacion: 'Abril tiene 6 círculos y mayo 3; la diferencia son 3 círculos, y cada uno equivale a 50 libros: 3 × 50 = 150. En un pictograma siempre hay que mirar primero cuánto vale el símbolo.',
  },
  {
    id: 'lec-088', tema: 'discontinuos', dificultad: 3,
    grafico: {
      tipo: 'barras', titulo: 'Quejas recibidas por servicio público', ejeY: 'quejas',
      datos: [
        { etiqueta: 'Agua', valor: 45 }, { etiqueta: 'Energía', valor: 30 },
        { etiqueta: 'Internet', valor: 25 }, { etiqueta: 'Gas', valor: 10 },
      ],
    },
    enunciado: '¿Cuál de estas afirmaciones NO se puede sostener con el gráfico?',
    opciones: [
      'El servicio de agua es el de peor calidad de la ciudad',
      'El servicio de agua recibió más quejas que ningún otro',
      'El gas recibió menos de la cuarta parte de las quejas del agua',
      'Los cuatro servicios recibieron quejas',
    ],
    correcta: 0,
    explicacion: 'El gráfico cuenta quejas, no calidad, y tampoco dice cuántos usuarios tiene cada servicio: si el agua llega a mucha más gente, más quejas no implica peor servicio. Las otras tres se leen directamente de las barras.',
  },
  {
    id: 'lec-089', tema: 'discontinuos', dificultad: 3,
    grafico: {
      tipo: 'lineas', titulo: 'Temperatura media anual de una ciudad (°C)', ejeY: '°C',
      etiquetas: ['2000', '2005', '2010', '2015', '2020'],
      series: [{ nombre: 'Media', valores: [21.4, 21.7, 22.1, 22.4, 22.9] }],
      tope: 25,
    },
    enunciado: '¿Qué conclusión es prudente a partir de este gráfico?',
    opciones: [
      'En el periodo medido la temperatura media mostró una tendencia al alza',
      'En 2050 la temperatura será de 25 °C',
      'El aumento se debe a la deforestación de la región',
      'La temperatura subirá indefinidamente al mismo ritmo',
    ],
    correcta: 0,
    explicacion: 'El gráfico muestra qué pasó, no por qué ni qué pasará. Extrapolar o atribuir una causa exige información adicional que aquí no aparece.',
  },
  {
    id: 'lec-090', tema: 'discontinuos', dificultad: 2,
    grafico: {
      tipo: 'circular', titulo: 'Modo de transporte al trabajo',
      datos: [
        { etiqueta: 'Bus', valor: 35 }, { etiqueta: 'A pie', valor: 30 },
        { etiqueta: 'Carro', valor: 20 }, { etiqueta: 'Bicicleta', valor: 10 },
        { etiqueta: 'Moto', valor: 5 },
      ],
    },
    enunciado: '¿Qué proporción de las personas se desplaza en medios no motorizados?',
    opciones: ['40 %', '30 %', '10 %', '65 %'],
    correcta: 0,
    explicacion: 'Los no motorizados son caminar (30 %) y bicicleta (10 %): 40 % en total. El bus, el carro y la moto sí llevan motor.',
  },
  {
    id: 'lec-091', tema: 'discontinuos', dificultad: 3,
    grafico: {
      tipo: 'barras', titulo: 'Satisfacción con tres proveedores (sobre 100)', ejeY: 'puntos',
      datos: [{ etiqueta: 'A', valor: 96 }, { etiqueta: 'B', valor: 98 }, { etiqueta: 'C', valor: 97 }],
      tope: 100,
    },
    enunciado: 'Una publicidad afirma que el proveedor B es "muy superior" a los demás. ¿Qué muestra en realidad el gráfico?',
    opciones: [
      'Que los tres tienen resultados casi iguales: la diferencia es de uno o dos puntos sobre cien',
      'Que B duplica la satisfacción de A',
      'Que C es el peor evaluado por un amplio margen',
      'Que los datos son insuficientes para comparar',
    ],
    correcta: 0,
    explicacion: 'Con el eje empezando en cero las tres barras se ven casi idénticas. Si el eje arrancara en 95, la de B parecería el triple que la de A: por eso, en un gráfico de barras, dónde empieza el eje vertical cambia por completo la impresión.',
    pista: 'Mira la escala del eje antes de mirar el tamaño de las barras.',
  },
  {
    id: 'lec-092', tema: 'discontinuos', dificultad: 2,
    grafico: {
      tipo: 'barras', titulo: 'Tasa de desempleo por trimestre (%)', ejeY: '%',
      datos: [
        { etiqueta: 'I', valor: 14.2 }, { etiqueta: 'II', valor: 13.8 },
        { etiqueta: 'III', valor: 12.9 }, { etiqueta: 'IV', valor: 12.1 },
      ],
      tope: 15,
    },
    enunciado: '¿Qué titular resume mejor la información del gráfico?',
    opciones: [
      'El desempleo bajó de forma sostenida a lo largo del año',
      'El desempleo se disparó durante el año',
      'El desempleo se redujo a la mitad en un año',
      'El desempleo se mantuvo estable en todos los trimestres',
    ],
    correcta: 0,
    explicacion: 'Bajó en los cuatro trimestres, de 14,2 % a 12,1 %: es una caída sostenida pero moderada, de poco más de dos puntos. Un titular exacto no exagera ni minimiza lo que muestran los datos.',
  },

  // ----- Análisis de la imagen -----
  {
    id: 'lec-093', tema: 'imagen', dificultad: 1,
    grafico: {
      tipo: 'plano', titulo: 'Plano de un apartamento',
      salas: [
        { x: 0, y: 0, w: 50, h: 50, etiqueta: 'Sala-comedor' },
        { x: 50, y: 0, w: 50, h: 25, etiqueta: 'Cocina' },
        { x: 50, y: 25, w: 50, h: 25, etiqueta: 'Baño' },
        { x: 0, y: 50, w: 100, h: 50, etiqueta: 'Habitación' },
      ],
    },
    enunciado: 'Según el plano, ¿qué espacio ocupa la mayor superficie?',
    opciones: ['La habitación', 'La sala-comedor', 'La cocina', 'El baño'],
    correcta: 0,
    explicacion: 'La habitación abarca todo el ancho y la mitad del fondo; la sala-comedor ocupa la mitad de eso. Leer un plano es comparar áreas, no solo contar espacios.',
  },
  {
    id: 'lec-094', tema: 'imagen', dificultad: 2,
    grafico: {
      tipo: 'mapa', titulo: 'Densidad de población por zona',
      zonas: [
        { x: 0, y: 0, w: 48, h: 48, etiqueta: 'Norte', nivel: 1 },
        { x: 52, y: 0, w: 48, h: 48, etiqueta: 'Oriente', nivel: 0 },
        { x: 0, y: 52, w: 48, h: 48, etiqueta: 'Centro', nivel: 3 },
        { x: 52, y: 52, w: 48, h: 48, etiqueta: 'Sur', nivel: 2 },
      ],
      leyenda: [
        { nivel: 3, texto: 'Alta' }, { nivel: 2, texto: 'Media' },
        { nivel: 1, texto: 'Baja' }, { nivel: 0, texto: 'Sin dato' },
      ],
    },
    enunciado: 'Según el mapa y su convención, ¿qué zona tiene la mayor densidad de población?',
    opciones: ['Centro', 'Sur', 'Norte', 'Oriente'],
    correcta: 0,
    explicacion: 'El sombreado más intenso corresponde a densidad alta, y la leyenda es la que permite traducirlo. Sin leer la convención, un mapa temático no se puede interpretar.',
  },
  {
    id: 'lec-095', tema: 'imagen', dificultad: 3,
    grafico: {
      tipo: 'mapa', titulo: 'Densidad de población por zona',
      zonas: [
        { x: 0, y: 0, w: 48, h: 48, etiqueta: 'Norte', nivel: 1 },
        { x: 52, y: 0, w: 48, h: 48, etiqueta: 'Oriente', nivel: 0 },
        { x: 0, y: 52, w: 48, h: 48, etiqueta: 'Centro', nivel: 3 },
        { x: 52, y: 52, w: 48, h: 48, etiqueta: 'Sur', nivel: 2 },
      ],
      leyenda: [
        { nivel: 3, texto: 'Alta' }, { nivel: 2, texto: 'Media' },
        { nivel: 1, texto: 'Baja' }, { nivel: 0, texto: 'Sin dato' },
      ],
    },
    enunciado: '¿Qué afirmación NO se puede sostener con este mapa?',
    opciones: [
      'La zona oriente está deshabitada',
      'El centro está más densamente poblado que el norte',
      'El sur tiene una densidad intermedia',
      'Hay una zona de la que no se tiene información',
    ],
    correcta: 0,
    explicacion: '"Sin dato" no significa cero: significa que no se midió. Confundir la ausencia de información con la ausencia del fenómeno es uno de los errores más frecuentes al leer mapas y tablas.',
  },
  {
    id: 'lec-096', tema: 'imagen', dificultad: 2,
    grafico: {
      tipo: 'plano', titulo: 'Plano de evacuación de un piso',
      salas: [
        { x: 0, y: 0, w: 40, h: 60, etiqueta: 'Aula 1' },
        { x: 40, y: 0, w: 20, h: 100, etiqueta: 'Pasillo' },
        { x: 60, y: 0, w: 40, h: 60, etiqueta: 'Aula 2' },
        { x: 0, y: 60, w: 40, h: 40, etiqueta: 'Laboratorio' },
        { x: 60, y: 60, w: 40, h: 40, etiqueta: 'Salida' },
      ],
    },
    enunciado: 'Una persona está en el laboratorio. Según el plano, para llegar a la salida debe:',
    opciones: [
      'Salir al pasillo y recorrerlo hasta el extremo opuesto',
      'Atravesar el aula 1 y luego el aula 2',
      'Salir directamente sin pasar por el pasillo',
      'Subir al piso superior',
    ],
    correcta: 0,
    explicacion: 'El pasillo es el único espacio que conecta los cuatro recintos con la salida. En un plano de evacuación lo primero que hay que identificar es la circulación, no las habitaciones.',
  },
  {
    id: 'lec-097', tema: 'imagen', dificultad: 2,
    enunciado: 'Al analizar una imagen se distingue entre denotación y connotación. La denotación es:',
    opciones: [
      'Lo que la imagen muestra literalmente, sin interpretación',
      'El mensaje oculto que el autor quiso transmitir',
      'La emoción que la imagen produce en quien la ve',
      'El contexto histórico en que fue creada',
    ],
    correcta: 0,
    explicacion: 'Primero se describe lo que hay (un hombre con un maletín frente a una puerta) y solo después se interpreta qué sugiere. Saltarse el primer paso lleva a ver en la imagen lo que uno ya pensaba.',
  },
  {
    id: 'lec-098', tema: 'imagen', dificultad: 3,
    enunciado: 'Una fotografía toma a una persona desde abajo, con la cámara a la altura de sus pies mirando hacia arriba. Ese ángulo, llamado contrapicado, suele producir el efecto de:',
    opciones: [
      'Engrandecer al sujeto y darle apariencia de autoridad o poder',
      'Hacerlo parecer más pequeño y vulnerable',
      'Eliminar cualquier intención del fotógrafo',
      'Mostrarlo de forma neutral y objetiva',
    ],
    correcta: 0,
    explicacion: 'El picado, desde arriba, produce el efecto contrario. Ninguna fotografía es neutral: el ángulo, el encuadre y lo que queda fuera son decisiones que construyen el mensaje.',
  },
  {
    id: 'lec-099', tema: 'imagen', dificultad: 3,
    enunciado: 'Para interpretar una caricatura política es indispensable:',
    opciones: [
      'Reconocer el contexto al que alude y los símbolos y exageraciones que emplea',
      'Tomar literalmente lo que muestra el dibujo',
      'Identificar al dibujante antes que el tema',
      'Evaluar la calidad técnica del trazo',
    ],
    correcta: 0,
    explicacion: 'La caricatura funciona por exageración y por referencia a hechos conocidos: sin el contexto, el chiste o la crítica no se entienden. Leerla literalmente es no leerla.',
  },
  {
    id: 'lec-100', tema: 'imagen', dificultad: 2,
    enunciado: 'Un aviso publicitario muestra a una familia sonriente en una cocina impecable junto al empaque de un producto. Lo que el aviso promete implícitamente es:',
    opciones: [
      'Una asociación entre el producto y el bienestar familiar, no una cualidad del producto',
      'Que el producto se fabrica en cocinas como esa',
      'Que el producto fue probado por esa familia',
      'Que el producto es el más barato del mercado',
    ],
    correcta: 0,
    explicacion: 'La publicidad emocional vende una asociación, no una propiedad verificable. Distinguir la afirmación comprobable de la sugerida es lo que la pregunta evalúa.',
  },
  {
    id: 'lec-101', tema: 'imagen', dificultad: 3,
    grafico: {
      tipo: 'barras', titulo: 'Resultados de la encuesta',
      datos: [
        { etiqueta: 'Opción A', valor: 62 }, { etiqueta: 'Opción B', valor: 38 },
      ],
      tope: 100,
    },
    enunciado: 'Una infografía presenta este gráfico sin más información. ¿Qué haría falta para poder valorar el resultado?',
    opciones: [
      'Saber a quiénes y a cuántas personas se preguntó, cuándo y quién hizo la encuesta',
      'Conocer el color corporativo de quien la publica',
      'Ver el gráfico en tamaño más grande',
      'Nada más: los porcentajes hablan por sí solos',
    ],
    correcta: 0,
    explicacion: 'Muestra, fecha, pregunta exacta y autoría son los datos que permiten juzgar si una cifra significa algo. Una infografía sin ficha técnica es una imagen, no una evidencia.',
  },
  {
    id: 'lec-102', tema: 'imagen', dificultad: 2,
    enunciado: 'Los tres elementos que permiten leer correctamente cualquier mapa son:',
    opciones: [
      'La leyenda o convenciones, la escala y la orientación',
      'El color, el tamaño y el autor',
      'El título, la fecha y el número de páginas',
      'La proyección, el idioma y el precio',
    ],
    correcta: 0,
    explicacion: 'La leyenda dice qué significa cada símbolo, la escala cuánto representa cada centímetro y la orientación hacia dónde está el norte. Sin alguno de los tres, el mapa se puede malinterpretar por completo.',
  },
];
