/**
 * lengua.js — Banco de lengua y escritura.
 *
 * Lectura crítica pregunta por lo que dice un texto; esta asignatura pregunta
 * por el idioma mismo: tilde, puntuación, gramática, sintaxis y redacción. Es
 * lo que evalúan la UNAL y varias privadas, y lo que hace falta para el módulo
 * de comunicación escrita del Saber Pro.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const LENGUA = [
  // ----- Acentuación y tilde -----
  {
    id: 'len-001', tema: 'acentuacion', dificultad: 1,
    enunciado: 'Las palabras agudas llevan tilde cuando terminan en:',
    opciones: ['Vocal, n o s', 'Consonante distinta de n o s', 'Cualquier consonante', 'Siempre llevan tilde'],
    correcta: 0,
    explicacion: 'Agudas como "camión", "café" o "además" llevan tilde; "reloj" o "papel" no, porque terminan en otra consonante.',
  },
  {
    id: 'len-002', tema: 'acentuacion', dificultad: 1,
    enunciado: '¿Cuál de estas palabras es esdrújula?',
    opciones: ['Médico', 'Camión', 'Árbol', 'Reloj'],
    correcta: 0,
    explicacion: 'La sílaba tónica de "mé-di-co" es la antepenúltima. "Camión" es aguda y "árbol", grave.',
  },
  {
    id: 'len-003', tema: 'acentuacion', dificultad: 1,
    enunciado: 'Todas las palabras esdrújulas y sobresdrújulas:',
    opciones: ['Llevan tilde sin excepción', 'Nunca llevan tilde', 'Llevan tilde solo si terminan en vocal', 'Llevan tilde solo si son verbos'],
    correcta: 0,
    explicacion: 'Es la regla más cómoda del español: "sábana", "último", "dígamelo". No hay que revisar la terminación.',
  },
  {
    id: 'len-004', tema: 'acentuacion', dificultad: 2,
    enunciado: '¿Cuál de estas palabras está correctamente acentuada?',
    opciones: ['Exámenes', 'Examenes', 'Éxamenes', 'Examénes'],
    correcta: 0,
    explicacion: '"Examen" es grave terminada en n y no lleva tilde, pero al pasar al plural la palabra se vuelve esdrújula y la necesita.',
  },
  {
    id: 'len-005', tema: 'acentuacion', dificultad: 2,
    enunciado: '¿Cuál de estas palabras NO debe llevar tilde?',
    opciones: ['Joven', 'Jóvenes', 'Árbol', 'Camión'],
    correcta: 0,
    explicacion: '"Joven" es grave terminada en n, así que no se tilda. En plural, "jóvenes" es esdrújula y sí.',
  },
  {
    id: 'len-006', tema: 'acentuacion', dificultad: 2,
    enunciado: '¿Por qué "día" lleva tilde?',
    opciones: [
      'Porque hay un hiato y la vocal débil tónica se tilda siempre',
      'Porque es una palabra aguda terminada en vocal',
      'Porque es esdrújula',
      'Porque todas las palabras de dos sílabas se tildan',
    ],
    correcta: 0,
    explicacion: 'La i tónica junto a una vocal fuerte rompe el diptongo y forma hiato. Por eso también llevan tilde "país", "reír" y "baúl", aunque las reglas generales no lo pidan.',
  },
  {
    id: 'len-007', tema: 'acentuacion', dificultad: 2,
    enunciado: '¿Cuál de estas palabras está mal escrita?',
    opciones: ['Heroe', 'Héroe', 'Aéreo', 'Línea'],
    correcta: 0,
    explicacion: 'Lo correcto es "héroe": hay hiato entre o y e, y la palabra resulta esdrújula, así que lleva tilde.',
  },
  {
    id: 'len-008', tema: 'acentuacion', dificultad: 2,
    enunciado: 'Por regla general, los monosílabos:',
    opciones: [
      'No llevan tilde, salvo cuando hay tilde diacrítica',
      'Llevan tilde siempre',
      'Llevan tilde si terminan en vocal',
      'Nunca llevan tilde, sin excepción',
    ],
    correcta: 0,
    explicacion: 'Por eso se escriben sin tilde "fue", "vio", "dio" o "fe". La excepción son pares como tú/tu o sé/se, donde la tilde distingue dos palabras distintas.',
  },
  {
    id: 'len-009', tema: 'acentuacion', dificultad: 3,
    enunciado: 'Completa correctamente: "No sé si ___ hermano vendrá a ___ casa."',
    opciones: ['tu … tu', 'tú … tú', 'tú … tu', 'tu … tú'],
    correcta: 0,
    explicacion: 'En los dos huecos es posesivo (de quién es el hermano, de quién es la casa), y el posesivo va sin tilde. "Tú" con tilde es el pronombre: "tú vendrás".',
    pista: 'Si puedes reemplazarlo por "mi", va sin tilde.',
  },
  {
    id: 'len-010', tema: 'acentuacion', dificultad: 3,
    enunciado: '¿En cuál de estas oraciones "mas" está bien escrito sin tilde?',
    opciones: [
      'Quiso venir, mas no pudo',
      'Quiero mas arroz',
      'Es mas alto que yo',
      'No pido mas de lo justo',
    ],
    correcta: 0,
    explicacion: '"Mas" sin tilde equivale a "pero". En los otros tres casos es la cantidad y debe escribirse "más".',
  },
  {
    id: 'len-011', tema: 'acentuacion', dificultad: 3,
    enunciado: 'Según la norma actual de la RAE, el adverbio "solo" (equivalente a "solamente"):',
    opciones: [
      'Se escribe sin tilde, aunque se admite tildarlo si hay riesgo real de ambigüedad',
      'Debe escribirse siempre con tilde',
      'Debe escribirse con tilde solo al inicio de la oración',
      'Ya no existe como adverbio',
    ],
    correcta: 0,
    explicacion: 'Desde 2010 la recomendación es no tildarlo. Lo mismo ocurre con los demostrativos: "este", "ese" y "aquel" van sin tilde aunque funcionen como pronombres.',
  },
  {
    id: 'len-012', tema: 'acentuacion', dificultad: 3,
    enunciado: '¿Cuál oración está correctamente acentuada?',
    opciones: [
      '¿Qué quieres que te diga? Sé que no es fácil.',
      '¿Que quieres que te diga? Se que no es facil.',
      '¿Qué quieres qué te diga? Sé qué no es fácil.',
      '¿Que quieres que te diga? Sé que no es fácil.',
    ],
    correcta: 0,
    explicacion: '"Qué" interrogativo lleva tilde; el "que" que solo enlaza, no. "Sé" del verbo saber se tilda para distinguirlo del pronombre "se", y "fácil" es grave terminada en l.',
  },
  {
    id: 'len-013', tema: 'acentuacion', dificultad: 4,
    enunciado: 'Completa: "___ así, decidió intentarlo, y ___ no ha terminado."',
    opciones: ['Aun … aún', 'Aún … aun', 'Aun … aun', 'Aún … aún'],
    correcta: 0,
    explicacion: '"Aun" sin tilde equivale a "incluso" o "hasta"; "aún" con tilde equivale a "todavía". En el primer hueco se puede decir "incluso así"; en el segundo, "todavía no ha terminado".',
    pista: 'Prueba a reemplazar por "todavía": si funciona, lleva tilde.',
  },
  {
    id: 'len-014', tema: 'acentuacion', dificultad: 4,
    enunciado: '¿Por qué "fácilmente" lleva tilde y "rapidamente" está mal escrito?',
    opciones: [
      'Porque los adverbios en -mente conservan la tilde del adjetivo del que vienen: fácil y rápida',
      'Porque los adverbios en -mente siempre llevan tilde',
      'Porque "fácilmente" es esdrújula y "rápidamente" no',
      'Porque la tilde depende de la longitud de la palabra',
    ],
    correcta: 0,
    explicacion: 'Lo correcto es "rápidamente", con tilde, porque "rápida" la lleva. En cambio "buenamente" o "felizmente" no la llevan, porque tampoco la llevan "buena" ni "feliz".',
  },
  {
    id: 'len-015', tema: 'acentuacion', dificultad: 4,
    enunciado: '¿Cuál de estas palabras compuestas está correctamente escrita?',
    opciones: ['Decimoséptimo', 'Décimoséptimo', 'Decimoseptimo', 'Décimo séptimo escrito así siempre'],
    correcta: 0,
    explicacion: 'Al soldarse en una sola palabra, solo se conserva la tilde del último componente. Por eso "así mismo" da "asimismo" y "tío vivo" da "tiovivo", sin la tilde del primer elemento.',
  },

  // ----- Ortografía de letras -----
  {
    id: 'len-016', tema: 'ortografia', dificultad: 1,
    enunciado: '¿Cuál de estas palabras está bien escrita?',
    opciones: ['Hubo', 'Ubo', 'Huvo', 'Uvo'],
    correcta: 0,
    explicacion: 'Es del verbo haber, que se escribe con h y con b: "hubo una reunión". "Uva" con v es la fruta.',
  },
  {
    id: 'len-017', tema: 'ortografia', dificultad: 1,
    enunciado: '¿Cómo se escribe correctamente?',
    opciones: ['Vergüenza', 'Verguenza', 'Bergüenza', 'Vergüensa'],
    correcta: 0,
    explicacion: 'La diéresis sobre la u indica que esa letra sí se pronuncia después de g. Sin ella, "gue" y "gui" suenan como en "guerra" o "guitarra".',
  },
  {
    id: 'len-018', tema: 'ortografia', dificultad: 1,
    enunciado: 'Se escriben con mayúscula inicial:',
    opciones: [
      'Los nombres propios de personas, lugares e instituciones',
      'Todos los sustantivos de la oración',
      'Los días de la semana y los meses',
      'Las palabras que el autor considere importantes',
    ],
    correcta: 0,
    explicacion: 'En español, a diferencia del inglés, los días, los meses, los idiomas y los gentilicios van en minúscula: "lunes", "marzo", "español", "colombiano".',
  },
  {
    id: 'len-019', tema: 'ortografia', dificultad: 2,
    enunciado: 'Completa: "Voy ___ que qué pasó, porque no puede ___ sucedido nada grave."',
    opciones: ['a ver … haber', 'haber … a ver', 'a ver … a ver', 'haber … haber'],
    correcta: 0,
    explicacion: '"A ver" es la preposición más el verbo ver, y suele ir con la idea de mirar o averiguar. "Haber" es el infinitivo del verbo auxiliar y acompaña a un participio.',
  },
  {
    id: 'len-020', tema: 'ortografia', dificultad: 2,
    enunciado: '¿Cuál oración está correctamente escrita?',
    opciones: [
      'Ahí hay un perro que dice ¡ay!',
      'Hay ahí un perro que dice ¡hay!',
      'Ay hay un perro que dice ¡ahí!',
      'Ahí ay un perro que dice ¡hay!',
    ],
    correcta: 0,
    explicacion: '"Ahí" es lugar, "hay" es del verbo haber y "ay" es la interjección de dolor. Las tres se pronuncian casi igual y son de los errores más frecuentes.',
  },
  {
    id: 'len-021', tema: 'ortografia', dificultad: 2,
    enunciado: 'Completa: "Yo ___ el trabajo que me pidieron" y "Le ___ de menos".',
    opciones: ['hice … echo', 'ice … hecho', 'hice … hecho', 'ise … echo'],
    correcta: 0,
    explicacion: '"Hice" viene de hacer y lleva h. "Echo" sin h es del verbo echar (echar de menos); "hecho" con h es el participio de hacer.',
  },
  {
    id: 'len-022', tema: 'ortografia', dificultad: 2,
    enunciado: '¿Cuál de estas palabras está mal escrita?',
    opciones: ['Exhuberante', 'Exuberante', 'Exhausto', 'Exhibir'],
    correcta: 0,
    explicacion: 'Lo correcto es "exuberante", sin h. "Exhausto" y "exhibir" sí la llevan, y por analogía mucha gente se la añade a la primera.',
  },
  {
    id: 'len-023', tema: 'ortografia', dificultad: 2,
    enunciado: '¿Cómo se escribe el plural de "lápiz"?',
    opciones: ['Lápices', 'Lápizes', 'Lapices', 'Lápiz'],
    correcta: 0,
    explicacion: 'Las palabras terminadas en z cambian a c en plural: lápiz/lápices, pez/peces, feliz/felices. La tilde se conserva porque la palabra sigue siendo esdrújula.',
  },
  {
    id: 'len-024', tema: 'ortografia', dificultad: 3,
    enunciado: 'Completa: "Espero que ___ bien el examen" y "No ___ nada al respecto".',
    opciones: ['te vaya … te valla', 'te valla … te vaya', 'te vaya … sé', 'te haya … te valla'],
    correcta: 2,
    explicacion: '"Vaya" es del verbo ir; "valla" es una cerca o un cartel publicitario; "baya" es un fruto. La segunda oración pide "sé" del verbo saber, no una de esas tres.',
  },
  {
    id: 'len-025', tema: 'ortografia', dificultad: 3,
    enunciado: '¿Cuál de estas oraciones está correctamente escrita?',
    opciones: [
      'Si no vienes, sino que llamas, avísame con tiempo',
      'Sino vienes, si no que llamas, avísame con tiempo',
      'Si no vienes, si no que llamas, avísame con tiempo',
      'Sino vienes, sino que llamas, avísame con tiempo',
    ],
    correcta: 0,
    explicacion: '"Si no" separado es condicional negativo: si no ocurre tal cosa. "Sino" junto es adversativo: no esto, sino aquello. La prueba es intentar meter una palabra entre "si" y "no".',
  },
  {
    id: 'len-026', tema: 'ortografia', dificultad: 3,
    enunciado: '¿Cuál de estas palabras está bien escrita?',
    opciones: ['Absorber', 'Absorver', 'Abzorber', 'Absorbher'],
    correcta: 0,
    explicacion: 'Se escribe con dos b, aunque su sustantivo sea "absorción" con c. El español no siempre mantiene la misma letra en toda la familia de palabras.',
  },
  {
    id: 'len-027', tema: 'ortografia', dificultad: 3,
    enunciado: 'Completa: "El equipo ___ el partido" / "El reloj da la ___".',
    opciones: ['tuvo … hora', 'tubo … hora', 'tuvo … ora', 'tubo … ora'],
    correcta: 0,
    explicacion: '"Tuvo" es del verbo tener y va con v; "tubo" con b es el objeto cilíndrico. "Hora" con h es el tiempo; "ora" sin h es del verbo orar.',
  },
  {
    id: 'len-028', tema: 'ortografia', dificultad: 4,
    enunciado: 'Según la norma vigente, ¿cuál de estas formas de escribir números es correcta?',
    opciones: [
      'Cuarenta y cinco mil se escribe "45 000", con espacio fino y sin punto',
      'Se escribe "45.000" en todos los contextos científicos',
      'Se escribe "45,000", con coma separadora de miles',
      'Los números de cinco cifras siempre se escriben con letras',
    ],
    correcta: 0,
    explicacion: 'La norma internacional, que la RAE recomienda, separa los millares con un espacio para evitar el choque entre el punto y la coma decimal, que se usan al revés en unos países y otros.',
  },
  {
    id: 'len-029', tema: 'ortografia', dificultad: 4,
    enunciado: '¿Cuál es la forma correcta?',
    opciones: [
      'Sobre todo lo demás, prefiero la verdad; sobretodo es una prenda de abrigo',
      'Sobretodo lo demás, prefiero la verdad',
      'Las dos formas son intercambiables',
      'Sobre todo es incorrecto en español',
    ],
    correcta: 0,
    explicacion: '"Sobre todo" separado es la locución que significa "principalmente". "Sobretodo" junto es un sustantivo: un abrigo largo. Es el mismo tipo de par que "por que" y "porque".',
  },
  {
    id: 'len-030', tema: 'ortografia', dificultad: 4,
    enunciado: '¿Cuál de estas oraciones usa correctamente las cuatro formas de "porque"?',
    opciones: [
      '¿Por qué llegaste tarde? Porque el bus se retrasó; ese es el porqué, y no hay razón por que preocuparse',
      'Porqué llegaste tarde? Por que el bus se retrasó',
      '¿Porque llegaste tarde? Por qué el bus se retrasó',
      '¿Por que llegaste tarde? Porqué el bus se retrasó',
    ],
    correcta: 0,
    explicacion: '"Por qué" pregunta, "porque" responde, "el porqué" es un sustantivo que admite artículo y plural, y "por que" separado y sin tilde equivale a "por el cual". El cuarto es el más raro y el que casi nadie usa bien.',
  },

  // ----- Puntuación -----
  {
    id: 'len-031', tema: 'puntuacion', dificultad: 1,
    enunciado: '¿Qué signo se usa para separar los elementos de una enumeración simple?',
    opciones: ['La coma', 'El punto', 'Los dos puntos', 'El punto y coma'],
    correcta: 0,
    explicacion: 'Se escribe "compré pan, leche, huevos y café": coma entre los elementos y la conjunción antes del último.',
  },
  {
    id: 'len-032', tema: 'puntuacion', dificultad: 1,
    enunciado: 'En español, los signos de interrogación:',
    opciones: [
      'Se escriben al principio y al final de la pregunta',
      'Se escriben solo al final, como en inglés',
      'Se escriben solo al principio',
      'Son opcionales en textos formales',
    ],
    correcta: 0,
    explicacion: 'El signo de apertura no es un adorno: marca dónde empieza la pregunta, que puede no coincidir con el inicio de la oración, como en "Si llegas temprano, ¿me avisas?".',
  },
  {
    id: 'len-033', tema: 'puntuacion', dificultad: 1,
    enunciado: '¿Para qué sirven los dos puntos?',
    opciones: [
      'Para anunciar lo que viene: una enumeración, una cita o una explicación',
      'Para separar el sujeto del verbo',
      'Para cerrar un párrafo',
      'Para indicar una pausa más larga que el punto',
    ],
    correcta: 0,
    explicacion: 'Funcionan como una flecha hacia adelante: "Traigo tres cosas: pan, queso y vino". Nunca deben separar el sujeto del verbo.',
  },
  {
    id: 'len-034', tema: 'puntuacion', dificultad: 2,
    enunciado: '¿Cuál de estas oraciones está correctamente puntuada?',
    opciones: [
      'Mi hermano, que vive en Cali, llegó ayer',
      'Mi hermano que vive en Cali, llegó ayer',
      'Mi hermano, que vive en Cali llegó ayer',
      'Mi hermano que, vive en Cali, llegó ayer',
    ],
    correcta: 0,
    explicacion: 'La aclaración va entre dos comas: se abre y se cierra. Dejar solo una de las dos es el error más común con los incisos.',
  },
  {
    id: 'len-035', tema: 'puntuacion', dificultad: 2,
    enunciado: '¿Cuál oración NO debe llevar coma?',
    opciones: [
      'Los estudiantes de último año presentaron el examen',
      'Los estudiantes, que estaban nerviosos, presentaron el examen',
      'Ayer, por la tarde, presentaron el examen',
      'Sin embargo, presentaron el examen',
    ],
    correcta: 0,
    explicacion: 'Nunca se separa el sujeto del verbo con una sola coma. En las otras tres la coma encierra un inciso o marca un conector.',
  },
  {
    id: 'len-036', tema: 'puntuacion', dificultad: 2,
    enunciado: '¿Qué signo se usa para introducir el parlamento de un personaje en un diálogo narrativo?',
    opciones: ['La raya (—)', 'El guion corto (-)', 'Las comillas simples', 'El punto y coma'],
    correcta: 0,
    explicacion: 'La raya es más larga que el guion y abre la intervención sin espacio después: "—No vengo —dijo—. Ya es tarde".',
  },
  {
    id: 'len-037', tema: 'puntuacion', dificultad: 2,
    enunciado: 'El punto y coma se usa principalmente para:',
    opciones: [
      'Separar elementos de una enumeración que ya llevan comas internas',
      'Reemplazar los dos puntos',
      'Cerrar una pregunta',
      'Separar el adjetivo del sustantivo',
    ],
    correcta: 0,
    explicacion: 'Ejemplo: "Vinieron Ana, la mayor; Luis, el del medio; y Sara, la menor". También une dos oraciones muy relacionadas cuando el punto sería demasiado.',
  },
  {
    id: 'len-038', tema: 'puntuacion', dificultad: 2,
    enunciado: '¿Dónde va el punto cuando una oración termina con un texto entre comillas?',
    opciones: [
      'Después de las comillas de cierre',
      'Antes de las comillas de cierre',
      'Se puede poner en cualquiera de los dos lugares',
      'No se pone punto',
    ],
    correcta: 0,
    explicacion: 'En español el punto va fuera: dijo que era «imposible». La costumbre de ponerlo dentro viene del inglés.',
  },
  {
    id: 'len-039', tema: 'puntuacion', dificultad: 3,
    enunciado: '¿En cuál de estas oraciones la coma cambia por completo el sentido?',
    opciones: [
      '"No, espere" frente a "No espere"',
      '"Vino Juan" frente a "Vino, Juan"',
      '"Llegó tarde" frente a "Llegó, tarde"',
      'Ninguna: la coma nunca cambia el sentido',
    ],
    correcta: 0,
    explicacion: 'Con coma es una negación seguida de una orden de esperar; sin coma es una orden de no esperar. Es el ejemplo clásico de que la puntuación no es decorativa.',
  },
  {
    id: 'len-040', tema: 'puntuacion', dificultad: 3,
    enunciado: '¿Cuál es el uso correcto de la coma antes de "pero"?',
    opciones: [
      'Se escribe coma antes de "pero" cuando une dos oraciones',
      'Nunca se escribe coma antes de "pero"',
      'Se escribe coma después de "pero", no antes',
      'Se escriben comas antes y después de "pero"',
    ],
    correcta: 0,
    explicacion: 'Ejemplo: "Quería ir, pero no tenía tiempo". Si lo que sigue es muy breve o no es una oración completa, la coma puede omitirse.',
  },
  {
    id: 'len-041', tema: 'puntuacion', dificultad: 3,
    enunciado: 'Los conectores como "sin embargo", "además" o "por lo tanto" al inicio de una oración:',
    opciones: [
      'Van seguidos de coma',
      'No llevan ningún signo',
      'Van seguidos de dos puntos',
      'Van entre comillas',
    ],
    correcta: 0,
    explicacion: 'Se escribe "Sin embargo, no vino". Si aparecen en medio de la oración, van entre comas: "No vino, sin embargo, avisó".',
  },
  {
    id: 'len-042', tema: 'puntuacion', dificultad: 3,
    enunciado: '¿Cuál de estas oraciones está bien puntuada?',
    opciones: [
      'Si llueve, no saldremos; si escampa, iremos al parque.',
      'Si llueve no saldremos, si escampa iremos al parque.',
      'Si llueve; no saldremos; si escampa; iremos al parque.',
      'Si llueve, no saldremos, si escampa, iremos al parque.',
    ],
    correcta: 0,
    explicacion: 'La condicional que va delante se separa con coma, y el punto y coma marca la frontera entre las dos oraciones largas. Unirlas con una simple coma es lo que se llama coma splice.',
  },
  {
    id: 'len-043', tema: 'puntuacion', dificultad: 4,
    enunciado: '"Vamos a comer niños" frente a "Vamos a comer, niños". La diferencia se explica porque la coma:',
    opciones: [
      'Marca el vocativo, es decir, a quién se le está hablando',
      'Indica una pausa para respirar',
      'Separa el verbo de su complemento directo',
      'Es opcional y solo aporta estilo',
    ],
    correcta: 0,
    explicacion: 'Sin coma, "niños" es el complemento directo de comer. Con coma es el vocativo: el destinatario del mensaje. El vocativo siempre se aísla con comas, vaya al principio, en medio o al final.',
  },
  {
    id: 'len-044', tema: 'puntuacion', dificultad: 4,
    enunciado: '¿Cuál es la diferencia entre "Los alumnos, que aprobaron, celebraron" y "Los alumnos que aprobaron celebraron"?',
    opciones: [
      'Con comas celebraron todos; sin comas celebraron solo los que aprobaron',
      'No hay diferencia de significado, solo de estilo',
      'Con comas la frase es incorrecta',
      'Sin comas la frase significa que ninguno aprobó',
    ],
    correcta: 0,
    explicacion: 'La relativa entre comas es explicativa y añade un dato sobre todo el grupo; sin comas es especificativa y recorta el grupo. Es la misma distinción que en inglés separa "which" de "that".',
    pista: 'Pregúntate si la frase entre comas se puede quitar sin cambiar de quién se habla.',
  },
  {
    id: 'len-045', tema: 'puntuacion', dificultad: 4,
    enunciado: '¿Cuál de estos usos de los puntos suspensivos es correcto?',
    opciones: [
      'Se escriben siempre tres, y si terminan la oración no se añade otro punto',
      'Se escriben cuatro para marcar una pausa larga',
      'Se escriben tres y después se añade un punto final',
      'Pueden escribirse tantos como se quiera para dar énfasis',
    ],
    correcta: 0,
    explicacion: 'Son tres exactamente, y el tercero hace de punto si la oración termina ahí. Si la oración continúa, la palabra siguiente va en minúscula.',
  },

  // ----- Categorías gramaticales -----
  {
    id: 'len-046', tema: 'gramatica', dificultad: 1,
    enunciado: 'En la oración "El perro negro corre rápido", ¿cuál es el adjetivo?',
    opciones: ['Negro', 'Perro', 'Corre', 'Rápido'],
    correcta: 0,
    explicacion: 'El adjetivo dice cómo es el sustantivo. "Rápido" aquí modifica al verbo, así que funciona como adverbio.',
  },
  {
    id: 'len-047', tema: 'gramatica', dificultad: 1,
    enunciado: '¿Qué categoría gramatical expresa acción, proceso o estado?',
    opciones: ['El verbo', 'El sustantivo', 'El adjetivo', 'La preposición'],
    correcta: 0,
    explicacion: 'El verbo es el núcleo del predicado y el único que se conjuga en persona, número, tiempo y modo.',
  },
  {
    id: 'len-048', tema: 'gramatica', dificultad: 1,
    enunciado: '¿Cuál de estas palabras es una preposición?',
    opciones: ['Hacia', 'Rápido', 'Correr', 'Nosotros'],
    correcta: 0,
    explicacion: 'Las preposiciones relacionan palabras: a, ante, bajo, con, contra, de, desde, en, entre, hacia, hasta, para, por, según, sin, sobre, tras.',
  },
  {
    id: 'len-049', tema: 'gramatica', dificultad: 2,
    enunciado: 'En "Ayer compré tres libros interesantes", ¿qué función cumple "tres"?',
    opciones: [
      'Es un determinante numeral que acompaña al sustantivo',
      'Es un adjetivo calificativo',
      'Es un adverbio de cantidad',
      'Es un pronombre',
    ],
    correcta: 0,
    explicacion: 'Los determinantes presentan al sustantivo y concretan su referencia: artículos, demostrativos, posesivos, numerales e indefinidos. "Interesantes" sí es adjetivo calificativo.',
  },
  {
    id: 'len-050', tema: 'gramatica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre un adjetivo y un adverbio?',
    opciones: [
      'El adjetivo modifica al sustantivo; el adverbio, al verbo, a un adjetivo o a otro adverbio',
      'El adjetivo va antes y el adverbio, después',
      'El adverbio siempre termina en -mente',
      'El adjetivo no varía en género ni número',
    ],
    correcta: 0,
    explicacion: 'En "habla claro", "claro" es adverbio porque dice cómo habla; en "un mensaje claro", es adjetivo porque dice cómo es el mensaje. La forma no cambia: cambia a qué palabra acompaña.',
  },
  {
    id: 'len-051', tema: 'gramatica', dificultad: 2,
    enunciado: 'En "Se lo dije a ella ayer", ¿cuántos pronombres hay?',
    opciones: ['Tres: se, lo, ella', 'Dos: se, lo', 'Uno: ella', 'Ninguno'],
    correcta: 0,
    explicacion: '"Se" y "lo" son pronombres átonos que reemplazan al complemento indirecto y al directo; "ella" es un pronombre personal tónico. "Ayer" es adverbio.',
  },
  {
    id: 'len-052', tema: 'gramatica', dificultad: 2,
    enunciado: '¿Qué tipo de palabra es "aunque"?',
    opciones: [
      'Una conjunción, porque enlaza dos oraciones',
      'Una preposición',
      'Un adverbio de modo',
      'Un determinante',
    ],
    correcta: 0,
    explicacion: 'Es una conjunción subordinante concesiva: introduce una objeción que no impide lo dicho en la oración principal.',
  },
  {
    id: 'len-053', tema: 'gramatica', dificultad: 2,
    enunciado: 'Los sustantivos se diferencian de los adjetivos en que:',
    opciones: [
      'Nombran seres, objetos o ideas y pueden funcionar solos como núcleo del sujeto',
      'Nunca cambian de género',
      'Siempre van acompañados de artículo',
      'No pueden formar plural',
    ],
    correcta: 0,
    explicacion: 'Un adjetivo puede sustantivarse ("los valientes"), pero para eso necesita un determinante que lo convierta en núcleo. Esa capacidad de sostener el sujeto por sí solo es lo propio del sustantivo.',
  },
  {
    id: 'len-054', tema: 'gramatica', dificultad: 3,
    enunciado: 'En "Bebe agua fría" y "El bebé duerme", la palabra "bebe/bebé":',
    opciones: [
      'Es verbo en la primera y sustantivo en la segunda',
      'Es sustantivo en las dos',
      'Es verbo en las dos',
      'Es adjetivo en la primera',
    ],
    correcta: 0,
    explicacion: 'La categoría de una palabra no está en la palabra sino en su función dentro de la oración. La tilde, además, distingue aquí el verbo del sustantivo.',
  },
  {
    id: 'len-055', tema: 'gramatica', dificultad: 3,
    enunciado: '¿Cuál de estas es una locución adverbial?',
    opciones: ['De vez en cuando', 'Sin embargo pero', 'El cual', 'Que sí'],
    correcta: 0,
    explicacion: 'Una locución es un grupo de palabras que funciona como una sola unidad. "De vez en cuando" equivale a "ocasionalmente", así que cumple el papel de un adverbio.',
  },
  {
    id: 'len-056', tema: 'gramatica', dificultad: 3,
    enunciado: 'En "Me gusta el café", ¿cuál es el sujeto?',
    opciones: ['El café', 'Me', 'Gusta', 'No hay sujeto'],
    correcta: 0,
    explicacion: 'Suena raro, pero "gustar" funciona al revés de lo que parece: lo que gusta es el sujeto y quien lo disfruta es el complemento indirecto. Se comprueba con el plural: "me gustan los cafés".',
    pista: 'Pon la frase en plural y mira con qué palabra concuerda el verbo.',
  },
  {
    id: 'len-057', tema: 'gramatica', dificultad: 3,
    enunciado: '¿Qué diferencia hay entre un pronombre y un determinante en "este libro" y "quiero este"?',
    opciones: [
      'En el primero acompaña al sustantivo y en el segundo lo reemplaza',
      'En el primero es pronombre y en el segundo, determinante',
      'Son la misma categoría en los dos casos',
      'El segundo es incorrecto en español',
    ],
    correcta: 0,
    explicacion: 'Acompañar o sustituir es justamente el criterio. Desde 2010 ninguno de los dos lleva tilde, precisamente porque la función ya se distingue por la posición.',
  },
  {
    id: 'len-058', tema: 'gramatica', dificultad: 4,
    enunciado: 'En "Lo importante es intentarlo", ¿qué función cumple "lo"?',
    opciones: [
      'Es un artículo neutro que sustantiva al adjetivo',
      'Es un pronombre de complemento directo',
      'Es un determinante masculino',
      'Es una preposición',
    ],
    correcta: 0,
    explicacion: 'El artículo neutro "lo" convierte adjetivos y adverbios en sustantivos abstractos: lo bueno, lo lejos que está. El "lo" pronombre aparece en "intentarlo", al final.',
  },
  {
    id: 'len-059', tema: 'gramatica', dificultad: 4,
    enunciado: '¿En cuál de estas oraciones "que" es un pronombre relativo y no una conjunción?',
    opciones: [
      'El libro que compré es caro',
      'Dijo que vendría mañana',
      'Es tan alto que no cabe',
      'Quiero que estudies',
    ],
    correcta: 0,
    explicacion: 'En la primera, "que" tiene antecedente ("el libro") y función dentro de su oración: es el complemento directo de "compré". En las otras solo enlaza, sin sustituir a nada.',
  },
  {
    id: 'len-060', tema: 'gramatica', dificultad: 4,
    enunciado: '¿Por qué "recién" no puede usarse como adjetivo en "el recién libro"?',
    opciones: [
      'Porque es un adverbio y solo modifica participios o verbos: "recién llegado", "recién salió"',
      'Porque es una palabra en desuso',
      'Porque le falta la terminación -mente',
      'Porque solo se usa en preguntas',
    ],
    correcta: 0,
    explicacion: 'La forma apocopada "recién" acompaña participios ("recién nacido") y, en América, verbos conjugados ("recién llegó"). Para acompañar a un sustantivo hay que decir "el libro reciente".',
  },

  // ----- El verbo: tiempo y modo -----
  {
    id: 'len-061', tema: 'verbos', dificultad: 1,
    enunciado: '¿Cuáles son los tres modos verbales del español?',
    opciones: [
      'Indicativo, subjuntivo e imperativo',
      'Presente, pasado y futuro',
      'Activo, pasivo y reflexivo',
      'Simple, compuesto y perifrástico',
    ],
    correcta: 0,
    explicacion: 'El modo expresa la actitud del hablante: el indicativo enuncia hechos, el subjuntivo expresa deseo o duda y el imperativo, órdenes. Presente y pasado son tiempos, no modos.',
  },
  {
    id: 'len-062', tema: 'verbos', dificultad: 1,
    enunciado: '¿Cuál es el participio del verbo "escribir"?',
    opciones: ['Escrito', 'Escribido', 'Escribiendo', 'Escribir'],
    correcta: 0,
    explicacion: 'Es un participio irregular, como "hecho", "dicho", "visto", "puesto" y "roto". "Escribiendo" es el gerundio.',
  },
  {
    id: 'len-063', tema: 'verbos', dificultad: 1,
    enunciado: 'En "Había estudiado antes del examen", el verbo está en:',
    opciones: ['Pretérito pluscuamperfecto', 'Presente', 'Futuro simple', 'Condicional'],
    correcta: 0,
    explicacion: 'El pluscuamperfecto sitúa una acción como anterior a otra acción pasada. Se forma con el imperfecto de haber más el participio.',
  },
  {
    id: 'len-064', tema: 'verbos', dificultad: 2,
    enunciado: 'Completa: "Si tuviera tiempo, ___ contigo."',
    opciones: ['iría', 'iré', 'fuera', 'vaya'],
    correcta: 0,
    explicacion: 'El esquema de la condicional irreal es imperfecto de subjuntivo en la condición y condicional simple en la consecuencia. Decir "si tuviera, iré" mezcla dos esquemas distintos.',
  },
  {
    id: 'len-065', tema: 'verbos', dificultad: 2,
    enunciado: '¿Cuál es la forma correcta del imperativo negativo de "venir" para "tú"?',
    opciones: ['No vengas', 'No ven', 'No viene', 'No venir'],
    correcta: 0,
    explicacion: 'El imperativo afirmativo es "ven", pero el negativo toma la forma del subjuntivo: "no vengas". Ocurre con todos los verbos: "haz" pero "no hagas".',
  },
  {
    id: 'len-066', tema: 'verbos', dificultad: 2,
    enunciado: 'Completa: "Espero que ___ pronto."',
    opciones: ['llegues', 'llegas', 'llegarás', 'llegaste'],
    correcta: 0,
    explicacion: 'Los verbos de deseo, duda o emoción piden subjuntivo en la oración subordinada. "Espero que llegas" es uno de los errores más marcados en la escritura.',
  },
  {
    id: 'len-067', tema: 'verbos', dificultad: 2,
    enunciado: '¿Qué expresa la perífrasis "ir a + infinitivo" en "voy a estudiar"?',
    opciones: [
      'Una acción futura o una intención',
      'Una acción terminada',
      'Una acción habitual del pasado',
      'Una orden',
    ],
    correcta: 0,
    explicacion: 'Es la forma más usada de futuro en el habla, por encima del futuro simple. Una perífrasis es un verbo auxiliar más una forma no personal que juntos expresan un matiz.',
  },
  {
    id: 'len-068', tema: 'verbos', dificultad: 2,
    enunciado: '¿Cuál es la primera persona del singular del pretérito perfecto simple de "andar"?',
    opciones: ['Anduve', 'Andé', 'Andí', 'Andaba'],
    correcta: 0,
    explicacion: 'Es un pretérito fuerte irregular, como "tuve", "estuve" o "supe". "Andé" es una regularización frecuente pero incorrecta.',
  },
  {
    id: 'len-069', tema: 'verbos', dificultad: 3,
    enunciado: '¿Cuál es la diferencia entre "Ayer comí" y "Hoy he comido"?',
    opciones: [
      'El primero cierra el hecho en un pasado terminado; el segundo lo vincula a un periodo que aún incluye el presente',
      'El segundo es incorrecto en español',
      'El primero es formal y el segundo, coloquial',
      'No hay ninguna diferencia',
    ],
    correcta: 0,
    explicacion: 'Por eso se dice "este año he viajado" pero "el año pasado viajé". En buena parte de América el pretérito simple cubre los dos usos, pero en la escritura formal la distinción se mantiene.',
  },
  {
    id: 'len-070', tema: 'verbos', dificultad: 3,
    enunciado: '¿Cuál de estos usos del gerundio es incorrecto?',
    opciones: [
      'Se cayó, rompiéndose el brazo tres horas después',
      'Llegó corriendo a la casa',
      'Estudiando así, vas a aprobar',
      'Estaba leyendo cuando sonó el teléfono',
    ],
    correcta: 0,
    explicacion: 'Es el gerundio de posterioridad: el gerundio debe expresar una acción simultánea o inmediatamente anterior, no algo que ocurre después. Se corrige con "y se rompió el brazo".',
  },
  {
    id: 'len-071', tema: 'verbos', dificultad: 3,
    enunciado: 'Completa: "Cuando ___ a casa, avísame."',
    opciones: ['llegues', 'llegarás', 'llegas', 'llegaste'],
    correcta: 0,
    explicacion: 'Cuando una temporal se refiere al futuro, el español usa subjuntivo, no futuro de indicativo. Es una diferencia importante con el inglés, que ahí usa presente.',
  },
  {
    id: 'len-072', tema: 'verbos', dificultad: 3,
    enunciado: 'En "Se vendieron todas las entradas", el verbo está en:',
    opciones: [
      'Pasiva refleja, con "las entradas" como sujeto',
      'Voz activa con sujeto tácito',
      'Imperativo',
      'Pasiva perifrástica',
    ],
    correcta: 0,
    explicacion: 'La pasiva refleja se forma con "se" y el verbo concuerda con el sujeto paciente, por eso va en plural. La pasiva perifrástica sería "fueron vendidas".',
  },
  {
    id: 'len-073', tema: 'verbos', dificultad: 4,
    enunciado: '¿Cuál es el uso correcto de "haber" como impersonal?',
    opciones: [
      '"Hubo muchos asistentes", siempre en singular',
      '"Hubieron muchos asistentes", concordando con el plural',
      'Las dos formas son igualmente válidas',
      'No puede usarse en pasado',
    ],
    correcta: 0,
    explicacion: 'Como impersonal, "haber" no tiene sujeto: lo que parece serlo es el complemento directo. Por eso se dice "hay dos" y también "hubo dos", "había dos", "habrá dos", siempre en singular.',
  },
  {
    id: 'len-074', tema: 'verbos', dificultad: 4,
    enunciado: '¿Qué diferencia hay entre "deber + infinitivo" y "deber de + infinitivo"?',
    opciones: [
      '"Debe estudiar" expresa obligación; "debe de estar cansado" expresa suposición',
      'Son intercambiables en todos los contextos',
      '"Deber de" es siempre incorrecto',
      '"Deber" sin preposición solo se usa en preguntas',
    ],
    correcta: 0,
    explicacion: 'La preposición cambia el significado: obligación frente a conjetura. En el habla se confunden, pero en un texto formal la distinción se aprecia.',
  },
  {
    id: 'len-075', tema: 'verbos', dificultad: 4,
    enunciado: 'En "Me dijo que viniera", ¿por qué el verbo subordinado va en imperfecto de subjuntivo?',
    opciones: [
      'Por la concordancia de tiempos: el verbo principal está en pasado y arrastra al subordinado',
      'Porque "venir" es irregular',
      'Porque expresa una condición imposible',
      'Porque el sujeto cambia entre las dos oraciones',
    ],
    correcta: 0,
    explicacion: 'Si el principal estuviera en presente sería "me dice que venga". Ese desplazamiento hacia atrás es la consecutio temporum, equivalente al backshift del estilo indirecto en inglés.',
  },

  // ----- Sintaxis de la oración -----
  {
    id: 'len-076', tema: 'sintaxis', dificultad: 1,
    enunciado: 'En "Los niños juegan en el parque", ¿cuál es el núcleo del sujeto?',
    opciones: ['Niños', 'Los', 'Juegan', 'Parque'],
    correcta: 0,
    explicacion: 'El núcleo del sujeto es el sustantivo con el que concuerda el verbo. "Los" es determinante y "juegan", el núcleo del predicado.',
  },
  {
    id: 'len-077', tema: 'sintaxis', dificultad: 1,
    enunciado: '¿Qué es el predicado de una oración?',
    opciones: [
      'Lo que se dice del sujeto, con el verbo como núcleo',
      'El conjunto de sustantivos de la oración',
      'La parte que va antes del verbo',
      'Cualquier grupo de palabras con sentido',
    ],
    correcta: 0,
    explicacion: 'Toda oración tiene sujeto y predicado, aunque el sujeto pueda estar tácito, como en "Llegamos tarde".',
  },
  {
    id: 'len-078', tema: 'sintaxis', dificultad: 1,
    enunciado: 'En "Ana compró un libro", ¿cuál es el complemento directo?',
    opciones: ['Un libro', 'Ana', 'Compró', 'No hay'],
    correcta: 0,
    explicacion: 'Es lo que recibe directamente la acción. Se comprueba sustituyéndolo por "lo": "Ana lo compró".',
  },
  {
    id: 'len-079', tema: 'sintaxis', dificultad: 2,
    enunciado: 'En "Le entregué el informe al jefe", ¿cuál es el complemento indirecto?',
    opciones: ['Al jefe', 'El informe', 'Le', 'Entregué'],
    correcta: 0,
    explicacion: 'El complemento indirecto es el destinatario y se sustituye por "le". Aquí aparece duplicado: el pronombre "le" y el grupo "al jefe" se refieren a lo mismo, algo normal en español.',
  },
  {
    id: 'len-080', tema: 'sintaxis', dificultad: 2,
    enunciado: '¿Cómo se comprueba que un grupo de palabras es complemento directo?',
    opciones: [
      'Sustituyéndolo por lo, la, los o las',
      'Sustituyéndolo por le o les',
      'Poniéndolo al inicio de la oración',
      'Comprobando que concuerda con el verbo',
    ],
    correcta: 0,
    explicacion: 'Si al sustituir aparece "le", es indirecto. También sirve pasar la oración a voz pasiva: el complemento directo es el que se convierte en sujeto.',
  },
  {
    id: 'len-081', tema: 'sintaxis', dificultad: 2,
    enunciado: 'En "Llegamos temprano a la reunión", "a la reunión" es:',
    opciones: [
      'Un complemento circunstancial de lugar',
      'Un complemento directo',
      'Un complemento indirecto',
      'El sujeto',
    ],
    correcta: 0,
    explicacion: 'Los circunstanciales dicen dónde, cuándo, cómo o por qué, y se pueden suprimir sin que la oración deje de funcionar.',
  },
  {
    id: 'len-082', tema: 'sintaxis', dificultad: 2,
    enunciado: '¿Cuál de estas es una oración compuesta?',
    opciones: [
      'Estudié mucho y aprobé el examen',
      'Estudié mucho para el examen de ayer',
      'Los estudiantes de último año estudiaron',
      'Aprobé el difícil examen de matemáticas',
    ],
    correcta: 0,
    explicacion: 'Una oración compuesta tiene más de un verbo conjugado y, por lo tanto, más de un predicado. En las otras tres hay un solo verbo, por larga que sea la frase.',
  },
  {
    id: 'len-083', tema: 'sintaxis', dificultad: 2,
    enunciado: 'En "El libro es interesante", ¿cómo se llama la función de "interesante"?',
    opciones: ['Atributo', 'Complemento directo', 'Complemento circunstancial', 'Sujeto'],
    correcta: 0,
    explicacion: 'Con los verbos copulativos ser, estar y parecer, lo que sigue es un atributo y se sustituye por "lo": "el libro lo es".',
  },
  {
    id: 'len-084', tema: 'sintaxis', dificultad: 3,
    enunciado: 'En "Quien llegue primero abrirá la puerta", la oración subordinada cumple la función de:',
    opciones: ['Sujeto', 'Complemento directo', 'Complemento circunstancial', 'Atributo'],
    correcta: 0,
    explicacion: '"Quien llegue primero" es quien realizará la acción de abrir, así que ocupa el lugar del sujeto. Se comprueba sustituyéndolo por un sustantivo: "Ana abrirá la puerta".',
  },
  {
    id: 'len-085', tema: 'sintaxis', dificultad: 3,
    enunciado: '¿Qué tipo de oración subordinada es "Me molesta que llegues tarde"?',
    opciones: [
      'Sustantiva, en función de sujeto',
      'Adjetiva o de relativo',
      'Adverbial de tiempo',
      'Coordinada adversativa',
    ],
    correcta: 0,
    explicacion: 'Lo que molesta es "que llegues tarde", así que la subordinada funciona como el sujeto del verbo molestar, igual que ocurría en "me gusta el café".',
  },
  {
    id: 'len-086', tema: 'sintaxis', dificultad: 3,
    enunciado: 'En "Aunque llovía, salimos", la subordinada "aunque llovía" es:',
    opciones: [
      'Adverbial concesiva',
      'Adverbial condicional',
      'Adverbial causal',
      'Sustantiva de complemento directo',
    ],
    correcta: 0,
    explicacion: 'Las concesivas presentan un obstáculo que no impide lo dicho en la principal. Si fuera causal diría "porque llovía" y el sentido sería el contrario.',
  },
  {
    id: 'len-087', tema: 'sintaxis', dificultad: 3,
    enunciado: '¿Cuál es la diferencia entre coordinación y subordinación?',
    opciones: [
      'En la coordinación las oraciones están al mismo nivel; en la subordinación una depende de la otra',
      'La coordinación solo usa la conjunción "y"',
      'La subordinación no lleva conectores',
      'La coordinación es siempre más formal',
    ],
    correcta: 0,
    explicacion: 'En "Llegó y se sentó" las dos podrían ir solas. En "Llegó cuando se sentó", la segunda no funciona aislada: depende de la primera y cumple una función dentro de ella.',
  },
  {
    id: 'len-088', tema: 'sintaxis', dificultad: 4,
    enunciado: 'En "Se arrepintió de su decisión", ¿qué función cumple "de su decisión"?',
    opciones: [
      'Complemento de régimen, porque el verbo exige esa preposición',
      'Complemento circunstancial de causa',
      'Complemento directo',
      'Atributo',
    ],
    correcta: 0,
    explicacion: 'Ciertos verbos piden una preposición fija: arrepentirse de, confiar en, depender de, insistir en. No se puede suprimir ni cambiar la preposición, a diferencia de un circunstancial.',
  },
  {
    id: 'len-089', tema: 'sintaxis', dificultad: 4,
    enunciado: 'En "Vi a María", ¿por qué aparece la preposición "a" si es complemento directo?',
    opciones: [
      'Porque el complemento directo de persona determinada lleva "a" en español',
      'Porque en realidad es un complemento indirecto',
      'Porque el verbo ver exige preposición',
      'Es un error frecuente que debería corregirse',
    ],
    correcta: 0,
    explicacion: 'Es la llamada "a" personal. Por eso se dice "busco un médico" (cualquiera) pero "busco a un médico" (uno concreto). La sustitución por "la" confirma que es directo: "la vi".',
    pista: 'Sustituye por lo/la: si funciona, es directo aunque lleve preposición.',
  },
  {
    id: 'len-090', tema: 'sintaxis', dificultad: 4,
    enunciado: '¿Cuál de estas oraciones tiene sujeto y cuál es impersonal?',
    opciones: [
      '"Se necesitan albañiles" tiene sujeto; "se trabaja mucho aquí" es impersonal',
      'Las dos son impersonales',
      'Las dos tienen sujeto',
      '"Se necesitan albañiles" es impersonal y la otra tiene sujeto',
    ],
    correcta: 0,
    explicacion: 'En la primera el verbo concuerda en plural con "albañiles", que es el sujeto paciente de una pasiva refleja. En la segunda no hay ningún elemento con el que concordar: es impersonal y el verbo queda fijo en singular.',
  },
  // ----- Concordancia y régimen -----
  {
    id: 'len-091', tema: 'concordancia', dificultad: 1,
    enunciado: '¿Cuál de estas frases tiene bien la concordancia?',
    opciones: ['Las casas blancas', 'Las casas blancos', 'El casas blanca', 'Las casa blancas'],
    correcta: 0,
    explicacion: 'El determinante y el adjetivo copian el género y el número del sustantivo: femenino y plural en los tres elementos.',
  },
  {
    id: 'len-092', tema: 'concordancia', dificultad: 1,
    enunciado: 'Completa: "Los estudiantes ___ al aula."',
    opciones: ['entraron', 'entró', 'entrará', 'entrando'],
    correcta: 0,
    explicacion: 'El verbo concuerda en número y persona con el sujeto. Si el sujeto es plural, el verbo también.',
  },
  {
    id: 'len-093', tema: 'concordancia', dificultad: 1,
    enunciado: '¿Cuál es la forma correcta?',
    opciones: ['El agua está fría', 'El agua está frío', 'La agua está fría', 'El agua está frías'],
    correcta: 0,
    explicacion: '"Agua" es femenino, pero lleva el artículo "el" porque empieza por a tónica. El adjetivo delata el género real: "fría", no "frío".',
  },
  {
    id: 'len-094', tema: 'concordancia', dificultad: 2,
    enunciado: 'Completa: "La mayoría de los asistentes ___ de acuerdo."',
    opciones: [
      'estaba o estaban: las dos formas se admiten',
      'solo estaba, nunca estaban',
      'solo estaban, nunca estaba',
      'estamos',
    ],
    correcta: 0,
    explicacion: 'Con sustantivos colectivos seguidos de un complemento en plural, la norma acepta la concordancia con el colectivo o con el complemento. Lo que no se puede es cambiar de criterio a mitad de frase.',
  },
  {
    id: 'len-095', tema: 'concordancia', dificultad: 2,
    enunciado: '¿Cuál de estas oraciones es correcta?',
    opciones: [
      'Se venden casas',
      'Se vende casas',
      'Se venden casa',
      'Se vendemos casas',
    ],
    correcta: 0,
    explicacion: 'Es una pasiva refleja: "casas" es el sujeto y el verbo debe ir en plural. El error de dejarlo en singular es frecuente en avisos.',
  },
  {
    id: 'len-096', tema: 'concordancia', dificultad: 2,
    enunciado: 'Completa: "Ni Juan ni Pedro ___ la respuesta."',
    opciones: ['sabían', 'sabía solamente', 'sabe', 'sabemos'],
    correcta: 0,
    explicacion: 'Dos sujetos unidos por "ni... ni" suman y piden plural, igual que con "y". La forma singular se admite solo si el verbo va antes de los dos sujetos.',
  },
  {
    id: 'len-097', tema: 'concordancia', dificultad: 2,
    enunciado: '¿Cuál es el uso correcto?',
    opciones: [
      'Un kilo de manzanas cuesta cinco mil pesos',
      'Un kilo de manzanas cuestan cinco mil pesos',
      'Unos kilo de manzanas cuesta cinco mil pesos',
      'Un kilo de manzana cuestan cinco mil pesos',
    ],
    correcta: 0,
    explicacion: 'El núcleo del sujeto es "kilo", en singular; "de manzanas" solo lo complementa. La atracción del plural cercano es lo que provoca el error.',
  },
  {
    id: 'len-098', tema: 'concordancia', dificultad: 2,
    enunciado: 'Completa: "Confío ___ ti" y "Insisto ___ el mismo punto".',
    opciones: ['en … en', 'de … en', 'en … de', 'a … en'],
    correcta: 0,
    explicacion: 'Confiar y insistir rigen la preposición "en". Cada verbo exige la suya y no se pueden intercambiar: se depende "de", se sueña "con", se accede "a".',
  },
  {
    id: 'len-099', tema: 'concordancia', dificultad: 3,
    enunciado: '¿Cuál de estas construcciones es correcta?',
    opciones: [
      'Es uno de los libros que más me han gustado',
      'Es uno de los libros que más me ha gustado',
      'Es uno de los libro que más me han gustado',
      'Son uno de los libros que más me han gustado',
    ],
    correcta: 0,
    explicacion: 'El antecedente del relativo es "los libros", en plural, así que el verbo de la subordinada va en plural. Es un caso que casi todo el mundo resuelve mal por oído.',
  },
  {
    id: 'len-100', tema: 'concordancia', dificultad: 3,
    enunciado: '¿Cuál es la forma correcta?',
    opciones: [
      'El veinte por ciento de los votantes se abstuvo',
      'El veinte por ciento de los votantes se abstuvieron obligatoriamente',
      'Los veinte por ciento de los votantes se abstuvo',
      'El veinte por cientos de los votantes se abstuvo',
    ],
    correcta: 0,
    explicacion: 'Con porcentajes precedidos de artículo, la concordancia en singular es la más recomendada, aunque el plural también se admite cuando el complemento está en plural.',
  },
  {
    id: 'len-101', tema: 'concordancia', dificultad: 3,
    enunciado: 'Completa: "Este problema es diferente ___ aquel."',
    opciones: ['de', 'que', 'a como', 'por'],
    correcta: 0,
    explicacion: '"Diferente de" es la forma tradicional y la más recomendada, aunque "diferente a" está extendida y se acepta. "Diferente que" no se considera correcta.',
  },
  {
    id: 'len-102', tema: 'concordancia', dificultad: 3,
    enunciado: 'En "Las tropas enemigas fueron derrotadas", el participio concuerda porque:',
    opciones: [
      'En la pasiva perifrástica el participio concuerda con el sujeto',
      'Los participios siempre concuerdan con el sustantivo más cercano',
      'El verbo "ser" obliga a poner todo en plural',
      'Los participios nunca varían',
    ],
    correcta: 0,
    explicacion: 'En la pasiva el participio funciona como atributo y copia género y número del sujeto. En cambio, con "haber" queda invariable: "las tropas han sido derrotadas", nunca "han sidas".',
  },
  {
    id: 'len-103', tema: 'concordancia', dificultad: 4,
    enunciado: '¿Cuál es la forma correcta?',
    opciones: [
      'Me alegro de que hayas venido',
      'Me alegro que hayas venido',
      'Me alegro de que has venido',
      'Me alegro que has venido',
    ],
    correcta: 0,
    explicacion: 'Se dice "alegrarse de algo", así que la preposición es obligatoria: quitarla es queísmo. Y el verbo de emoción pide subjuntivo, de ahí "hayas".',
  },
  {
    id: 'len-104', tema: 'concordancia', dificultad: 4,
    enunciado: '¿Cuál de estas concordancias es la correcta?',
    opciones: [
      'Fuimos los estudiantes quienes protestamos',
      'Fuimos los estudiantes quienes protestaron',
      'Fue los estudiantes quienes protestamos',
      'Fuimos los estudiantes quien protestó',
    ],
    correcta: 0,
    explicacion: 'En las construcciones enfáticas con "ser", el verbo de la relativa concuerda con la persona del sujeto, no con la tercera. Como el sujeto incluye al hablante, va en primera persona del plural.',
  },
  {
    id: 'len-105', tema: 'concordancia', dificultad: 4,
    enunciado: 'En "Un grupo de niños jugaba en el patio" frente a "Un grupo de niños jugaban en el patio":',
    opciones: [
      'Las dos son admisibles, pero la primera concuerda con el núcleo y la segunda con el sentido colectivo',
      'Solo la primera es correcta en cualquier contexto',
      'Solo la segunda es correcta',
      'Ninguna es correcta: falta el artículo',
    ],
    correcta: 0,
    explicacion: 'Es la llamada concordancia ad sensum. Con "un grupo de" la norma prefiere el singular, pero admite el plural cuando se piensa en los individuos y no en el conjunto.',
  },

  // ----- Errores frecuentes del español -----
  {
    id: 'len-106', tema: 'errores', dificultad: 1,
    enunciado: '¿Cuál de estas formas es incorrecta?',
    opciones: ['Haiga', 'Haya', 'Halla', 'Aya'],
    correcta: 0,
    explicacion: '"Haiga" no existe en la norma culta: la forma es "haya". "Halla" es del verbo hallar y "aya" es una cuidadora de niños.',
  },
  {
    id: 'len-107', tema: 'errores', dificultad: 1,
    enunciado: '¿Cómo se dice correctamente?',
    opciones: ['Hubo muchos problemas', 'Hubieron muchos problemas', 'Habían muchos problemas', 'Habrán muchos problemas'],
    correcta: 0,
    explicacion: 'Como impersonal, "haber" va siempre en singular: hay, había, hubo, habrá. Lo que parece el sujeto es en realidad el complemento directo.',
  },
  {
    id: 'len-108', tema: 'errores', dificultad: 1,
    enunciado: '¿Cuál es la forma correcta?',
    opciones: ['Dijiste', 'Dijistes', 'Dijite', 'Dicistes'],
    correcta: 0,
    explicacion: 'La segunda persona del pretérito no lleva s final: dijiste, viniste, hiciste. La s se añade por analogía con otros tiempos verbales.',
  },
  {
    id: 'len-109', tema: 'errores', dificultad: 2,
    enunciado: '¿Cuál de estas oraciones incurre en dequeísmo?',
    opciones: [
      'Pienso de que deberíamos irnos',
      'Estoy seguro de que vendrá',
      'Me acuerdo de que llovía',
      'Se olvidó de que había reunión',
    ],
    correcta: 0,
    explicacion: 'Se dice "pensar algo", no "pensar de algo": la preposición sobra. En las otras tres los verbos sí rigen "de" y quitarla sería queísmo.',
    pista: 'Reemplaza la subordinada por "eso": si suena "pienso de eso", algo falla.',
  },
  {
    id: 'len-110', tema: 'errores', dificultad: 2,
    enunciado: '¿Cuál de estas oraciones incurre en queísmo?',
    opciones: [
      'Me di cuenta que era tarde',
      'Me di cuenta de que era tarde',
      'Creo que era tarde',
      'Dijo que era tarde',
    ],
    correcta: 0,
    explicacion: 'La locución es "darse cuenta de algo", así que la preposición es obligatoria. El queísmo es el error contrario al dequeísmo: quitar una preposición que sí hace falta.',
  },
  {
    id: 'len-111', tema: 'errores', dificultad: 2,
    enunciado: '¿Cuál de estas oraciones es un caso de laísmo?',
    opciones: [
      'La dije que viniera',
      'Le dije que viniera',
      'La vi en la calle',
      'Le entregué el libro',
    ],
    correcta: 0,
    explicacion: 'El complemento indirecto se marca con "le", sea de hombre o de mujer. Usar "la" para el indirecto es laísmo; "la vi" sí es correcto porque ahí es complemento directo.',
  },
  {
    id: 'len-112', tema: 'errores', dificultad: 2,
    enunciado: '¿Cuál es la forma correcta?',
    opciones: [
      'Bajo mi punto de vista no, se dice "desde mi punto de vista"',
      'Bajo mi punto de vista es la única forma correcta',
      'Las dos son igual de correctas',
      'Lo correcto es "en mi punto de vista"',
    ],
    correcta: 0,
    explicacion: 'Un punto de vista es un lugar desde el que se mira, así que la preposición lógica es "desde". "Bajo" se usa con "bajo mi responsabilidad" o "bajo su mandato".',
  },
  {
    id: 'len-113', tema: 'errores', dificultad: 2,
    enunciado: '¿Qué error hay en "En base a los datos, concluimos que…"?',
    opciones: [
      'Lo recomendado es "con base en" o "sobre la base de"',
      'No hay error alguno',
      'Sobra la coma',
      'Debería decir "en base de"',
    ],
    correcta: 0,
    explicacion: 'Una base es algo sobre lo que se apoya: se está "sobre" ella, no "en" ella con la preposición "a". La forma más extendida en América es "con base en".',
  },
  {
    id: 'len-114', tema: 'errores', dificultad: 3,
    enunciado: '¿Cuál de estas oraciones contiene un anacoluto?',
    opciones: [
      'Los estudiantes que llegaron tarde, se les negó la entrada',
      'A los estudiantes que llegaron tarde se les negó la entrada',
      'Se negó la entrada a los estudiantes que llegaron tarde',
      'Los estudiantes que llegaron tarde no pudieron entrar',
    ],
    correcta: 0,
    explicacion: 'La frase arranca con un sujeto y termina con una construcción que ya no lo admite: el hilo sintáctico se rompe a la mitad. Se arregla con la preposición inicial, como en la segunda opción.',
  },
  {
    id: 'len-115', tema: 'errores', dificultad: 3,
    enunciado: '¿Cuál de estas expresiones es un pleonasmo innecesario?',
    opciones: [
      'Subir arriba',
      'Bajar del bus',
      'Salir temprano',
      'Entrar en la sala',
    ],
    correcta: 0,
    explicacion: 'Subir ya implica ir hacia arriba, así que el adverbio no aporta nada. Lo mismo ocurre con "lapso de tiempo", "nexo de unión" o "accidente fortuito".',
  },
  {
    id: 'len-116', tema: 'errores', dificultad: 3,
    enunciado: '¿Cuál es el uso correcto de "medio"?',
    opciones: [
      'Ella está medio cansada, porque aquí "medio" es adverbio e invariable',
      'Ella está media cansada',
      'Las dos formas son válidas',
      'Debería decirse "ella está mitad cansada"',
    ],
    correcta: 0,
    explicacion: 'Cuando "medio" modifica a un adjetivo funciona como adverbio y no cambia de forma. Solo varía cuando acompaña a un sustantivo: "media hora", "medio kilo".',
  },
  {
    id: 'len-117', tema: 'errores', dificultad: 3,
    enunciado: '¿Qué problema tiene la frase "Habemos muchos que pensamos distinto"?',
    opciones: [
      '"Haber" impersonal no admite primera persona: debe decirse "somos muchos los que pensamos distinto"',
      'Sobra la palabra "muchos"',
      'El verbo debería ir en futuro',
      'No tiene ningún problema',
    ],
    correcta: 0,
    explicacion: 'El impersonal solo existe en tercera del singular. "Habemos" es una forma muy extendida en el habla pero ajena a la norma culta escrita.',
  },
  {
    id: 'len-118', tema: 'errores', dificultad: 4,
    enunciado: '¿Cuál de estas construcciones es incorrecta según la norma?',
    opciones: [
      'Es por esto que decidí renunciar',
      'Por esto decidí renunciar',
      'Es por esto por lo que decidí renunciar',
      'Esta es la razón por la que decidí renunciar',
    ],
    correcta: 0,
    explicacion: 'Es el llamado "que galicado": la construcción enfática exige repetir la preposición o usar un relativo con artículo. En el habla está muy extendida, pero en un texto formal se corrige.',
  },
  {
    id: 'len-119', tema: 'errores', dificultad: 4,
    enunciado: '¿Cuál es el uso correcto del verbo "adolecer"?',
    opciones: [
      'El informe adolece de falta de datos significa que tiene ese defecto',
      'Adolecer significa carecer de algo bueno',
      'Adolecer se usa solo con enfermedades físicas',
      'Adolecer es sinónimo exacto de necesitar',
    ],
    correcta: 0,
    explicacion: 'Adolecer es padecer un defecto, no carecer. Por eso "adolece de falta de datos" significa que le falta información, mientras que "adolece de datos" diría, absurdamente, que tener datos es su problema.',
  },
  {
    id: 'len-120', tema: 'errores', dificultad: 4,
    enunciado: '¿Cuál de estas oraciones usa bien "cuyo"?',
    opciones: [
      'El autor, cuya obra leímos, vendrá mañana',
      'El autor, cuyo leímos su obra, vendrá mañana',
      'El autor, que su obra leímos, vendrá mañana',
      'El autor, cual obra leímos, vendrá mañana',
    ],
    correcta: 0,
    explicacion: '"Cuyo" es relativo y posesivo a la vez, y concuerda con lo poseído, no con el poseedor: por eso es "cuya obra". Reemplazarlo por "que su" es el error llamado quesuismo.',
  },

  // ----- Conectores y cohesión -----
  {
    id: 'len-121', tema: 'cohesion', dificultad: 1,
    enunciado: '¿Qué relación expresa el conector "sin embargo"?',
    opciones: ['Contraste u oposición', 'Causa', 'Consecuencia', 'Adición'],
    correcta: 0,
    explicacion: 'Introduce algo que va en contra de lo esperado, igual que "no obstante" o "en cambio".',
  },
  {
    id: 'len-122', tema: 'cohesion', dificultad: 1,
    enunciado: 'Completa: "Estudió mucho; ___, aprobó sin dificultad."',
    opciones: ['por lo tanto', 'sin embargo', 'aunque', 'a pesar de'],
    correcta: 0,
    explicacion: 'La segunda frase es la consecuencia lógica de la primera, así que pide un conector consecutivo.',
  },
  {
    id: 'len-123', tema: 'cohesion', dificultad: 1,
    enunciado: '¿Qué conector expresa causa?',
    opciones: ['Porque', 'Pero', 'Además', 'Finalmente'],
    correcta: 0,
    explicacion: '"Porque", "ya que", "puesto que" y "dado que" introducen la razón de lo dicho.',
  },
  {
    id: 'len-124', tema: 'cohesion', dificultad: 2,
    enunciado: 'Completa: "No tenía experiencia; ___, consiguió el trabajo."',
    opciones: ['no obstante', 'por consiguiente', 'es decir', 'asimismo'],
    correcta: 0,
    explicacion: 'Hay una oposición entre las dos ideas: lo esperable sería que no lo consiguiera. "Por consiguiente" indicaría lo contrario.',
  },
  {
    id: 'len-125', tema: 'cohesion', dificultad: 2,
    enunciado: '¿Qué función cumple "es decir" en un texto?',
    opciones: [
      'Reformular lo anterior con otras palabras',
      'Introducir una causa',
      'Marcar el final del texto',
      'Añadir un argumento nuevo',
    ],
    correcta: 0,
    explicacion: 'Es un conector de reformulación, como "o sea", "dicho de otro modo" o "en otras palabras". No añade información: la repite de forma más clara.',
  },
  {
    id: 'len-126', tema: 'cohesion', dificultad: 2,
    enunciado: 'En "Compré el libro. Lo leí en dos días", ¿qué mecanismo de cohesión aparece?',
    opciones: [
      'Referencia por pronombre: "lo" sustituye a "el libro"',
      'Repetición léxica',
      'Elipsis del verbo',
      'Conector de adición',
    ],
    correcta: 0,
    explicacion: 'Los pronombres evitan repetir y a la vez atan una frase con la anterior. Junto a los sinónimos y los conectores, son lo que hace que un texto no sea una lista de frases sueltas.',
  },
  {
    id: 'len-127', tema: 'cohesion', dificultad: 2,
    enunciado: 'Completa: "El proyecto es costoso; ___, requiere mucho tiempo."',
    opciones: ['además', 'en cambio', 'por el contrario', 'sin embargo'],
    correcta: 0,
    explicacion: 'Las dos ideas van en la misma dirección: los dos son inconvenientes. Por eso el conector debe ser de adición y no de contraste.',
  },
  {
    id: 'len-128', tema: 'cohesion', dificultad: 2,
    enunciado: '¿Qué conectores sirven para ordenar un texto?',
    opciones: [
      'En primer lugar, a continuación, por último',
      'Porque, ya que, dado que',
      'Pero, aunque, sin embargo',
      'Es decir, o sea, en otras palabras',
    ],
    correcta: 0,
    explicacion: 'Son conectores de ordenación: marcan el recorrido del texto y ayudan al lector a saber en qué parte del argumento está.',
  },
  {
    id: 'len-129', tema: 'cohesion', dificultad: 3,
    enunciado: '¿Cuál es el error en "Estudió poco, por lo tanto sacó la mejor nota del curso"?',
    opciones: [
      'El conector indica consecuencia, pero la relación real es de contraste',
      'Falta una coma después de "poco"',
      '"Por lo tanto" no existe en español',
      'El verbo debería ir en subjuntivo',
    ],
    correcta: 0,
    explicacion: 'Un conector mal elegido dice lo contrario de lo que el autor quiere. Aquí lo correcto sería "y sin embargo" o "aun así".',
  },
  {
    id: 'len-130', tema: 'cohesion', dificultad: 3,
    enunciado: 'En un párrafo, ¿qué problema genera repetir el mismo sustantivo en todas las frases?',
    opciones: [
      'Hace el texto monótono; se resuelve con pronombres, sinónimos o elipsis',
      'Hace el texto incorrecto gramaticalmente',
      'Impide usar conectores',
      'Obliga a cambiar de tiempo verbal',
    ],
    correcta: 0,
    explicacion: 'La repetición es un mecanismo de cohesión legítimo, pero abusar de él cansa. La alternancia con sinónimos y pronombres mantiene el hilo sin repetir.',
  },
  {
    id: 'len-131', tema: 'cohesion', dificultad: 3,
    enunciado: 'Completa: "___ el mal clima, el partido se jugó."',
    opciones: ['A pesar de', 'A pesar de que', 'Aunque', 'Puesto que'],
    correcta: 0,
    explicacion: '"A pesar de" va seguido de un sustantivo; "a pesar de que" y "aunque" necesitan una oración con verbo conjugado. Aquí lo que sigue es un grupo nominal.',
  },
  {
    id: 'len-132', tema: 'cohesion', dificultad: 3,
    enunciado: '¿Qué aporta la elipsis en "Ana estudió medicina; su hermano, derecho"?',
    opciones: [
      'Evita repetir el verbo, que se sobreentiende, y la coma marca esa omisión',
      'Señala que el hermano no estudió',
      'Indica una pausa para respirar',
      'Sustituye a un conector de causa',
    ],
    correcta: 0,
    explicacion: 'Esa coma se llama coma elíptica y ocupa el lugar del verbo omitido. Es un recurso de economía que exige que el verbo ya haya aparecido antes.',
  },
  {
    id: 'len-133', tema: 'cohesion', dificultad: 4,
    enunciado: '¿Cuál de estos pares de conectores NO es equivalente?',
    opciones: [
      '"En efecto" y "en cambio"',
      '"Por lo tanto" y "en consecuencia"',
      '"No obstante" y "sin embargo"',
      '"Es decir" y "o sea"',
    ],
    correcta: 0,
    explicacion: '"En efecto" confirma lo dicho; "en cambio" lo opone. Son de familias distintas, y confundirlos invierte el sentido del párrafo.',
  },
  {
    id: 'len-134', tema: 'cohesion', dificultad: 4,
    enunciado: 'En un texto argumentativo, ¿qué señala un conector como "ahora bien"?',
    opciones: [
      'Que el autor va a introducir una objeción o un matiz a lo que acaba de conceder',
      'Que el texto está por terminar',
      'Que empieza un ejemplo',
      'Que se repite la idea anterior',
    ],
    correcta: 0,
    explicacion: 'Suele aparecer después de una concesión: el autor reconoce algo y enseguida marca el límite de esa concesión. Reconocer esos giros es clave para seguir un argumento largo.',
  },
  {
    id: 'len-135', tema: 'cohesion', dificultad: 4,
    enunciado: '¿Por qué es problemático empezar un párrafo con "Esto demuestra que…" sin más?',
    opciones: [
      'Porque "esto" puede no tener un referente claro y el lector no sabe a qué remite',
      'Porque no se puede empezar un párrafo con un demostrativo',
      'Porque "demostrar" es un verbo prohibido en textos académicos',
      'Porque falta una coma después de "esto"',
    ],
    correcta: 0,
    explicacion: 'Los demostrativos aislados al inicio de párrafo producen referencia ambigua: no se sabe si remiten a la última frase, al último párrafo o a todo el argumento. Se arregla nombrando el referente: "esta caída de los precios demuestra que…".',
  },

  // ----- Léxico y precisión -----
  {
    id: 'len-136', tema: 'lexico', dificultad: 1,
    enunciado: '¿Cuál es un sinónimo de "efímero"?',
    opciones: ['Pasajero', 'Eterno', 'Enorme', 'Costoso'],
    correcta: 0,
    explicacion: 'Efímero es lo que dura muy poco. Su antónimo sería "duradero" o "perenne".',
  },
  {
    id: 'len-137', tema: 'lexico', dificultad: 1,
    enunciado: '¿Cuál es el antónimo de "generoso"?',
    opciones: ['Tacaño', 'Amable', 'Rico', 'Callado'],
    correcta: 0,
    explicacion: 'Un antónimo expresa el significado contrario dentro del mismo campo: dar frente a retener.',
  },
  {
    id: 'len-138', tema: 'lexico', dificultad: 1,
    enunciado: 'El prefijo "in-" en "incapaz" indica:',
    opciones: ['Negación', 'Repetición', 'Exceso', 'Anterioridad'],
    correcta: 0,
    explicacion: 'Igual que en "injusto" o "increíble". Ante b y p se convierte en "im-": imposible, imborrable.',
  },
  {
    id: 'len-139', tema: 'lexico', dificultad: 2,
    enunciado: '¿Qué significa "álgido" en su sentido correcto?',
    opciones: [
      'El punto culminante o crítico de un proceso',
      'Algo muy caliente',
      'Algo confuso',
      'Algo muy largo',
    ],
    correcta: 0,
    explicacion: 'Originalmente significaba "muy frío", pero el uso fijó el sentido de momento crítico. Lo que nunca ha significado es "caldeado" o "acalorado".',
  },
  {
    id: 'len-140', tema: 'lexico', dificultad: 2,
    enunciado: 'Completa: "El gobierno ___ un castigo severo" / "El conductor ___ la norma".',
    opciones: ['infligió … infringió', 'infringió … infligió', 'infligió … infligió', 'infringió … infringió'],
    correcta: 0,
    explicacion: 'Infligir es imponer un daño o un castigo; infringir es incumplir una norma. Se parecen tanto que se intercambian constantemente.',
  },
  {
    id: 'len-141', tema: 'lexico', dificultad: 2,
    enunciado: '¿Cuál es el significado de "exhaustivo"?',
    opciones: [
      'Que agota el tema, completo y minucioso',
      'Que deja agotado a quien lo lee',
      'Que es demasiado largo',
      'Que está mal hecho',
    ],
    correcta: 0,
    explicacion: 'Viene de "exhaurire", agotar: un estudio exhaustivo no deja nada por revisar. "Exhausto" sí se refiere al cansancio.',
  },
  {
    id: 'len-142', tema: 'lexico', dificultad: 2,
    enunciado: '¿Qué significa el sufijo "-itis" en "gastritis"?',
    opciones: ['Inflamación', 'Extirpación', 'Estudio de', 'Dolor leve'],
    correcta: 0,
    explicacion: 'Gastritis es inflamación del estómago. "-ectomía" es extirpación y "-logía", estudio: apendicectomía, cardiología.',
  },
  {
    id: 'len-143', tema: 'lexico', dificultad: 2,
    enunciado: '¿Cuál de estas palabras es un extranjerismo con equivalente en español?',
    opciones: [
      '"Link", que equivale a "enlace"',
      '"Computador", que no tiene equivalente',
      '"Teléfono", que es un extranjerismo crudo',
      '"Mesa", que viene del inglés',
    ],
    correcta: 0,
    explicacion: 'Usar extranjerismos no es un error en sí mismo, pero cuando hay una palabra española equivalente y de uso normal, la norma recomienda preferirla en textos formales.',
  },
  {
    id: 'len-144', tema: 'lexico', dificultad: 3,
    enunciado: 'En "El político hizo unas declaraciones polémicas", ¿qué verbo daría más precisión que "hizo"?',
    opciones: ['Formuló', 'Realizó', 'Efectuó', 'Llevó a cabo'],
    correcta: 0,
    explicacion: '"Realizar", "efectuar" y "llevar a cabo" son tan vagos como "hacer", solo que más largos. "Formular" dice exactamente qué se hizo con unas declaraciones.',
  },
  {
    id: 'len-145', tema: 'lexico', dificultad: 3,
    enunciado: '¿Cuál es la diferencia entre "eficaz", "eficiente" y "efectivo"?',
    opciones: [
      'Eficaz logra el objetivo; eficiente lo logra con pocos recursos; efectivo funciona en la práctica',
      'Son tres formas de decir lo mismo',
      'Eficiente se aplica a personas y eficaz a cosas, sin más diferencia',
      'Efectivo solo se usa para hablar de dinero',
    ],
    correcta: 0,
    explicacion: 'Un método puede ser eficaz pero no eficiente si consigue el resultado gastando el triple de lo necesario. En un informe, confundirlos borra la distinción entre lograr algo y lograrlo bien.',
  },
  {
    id: 'len-146', tema: 'lexico', dificultad: 3,
    enunciado: '¿Qué significa "sesgo" en un contexto científico?',
    opciones: [
      'Una desviación sistemática que distorsiona el resultado',
      'Un error de cálculo aislado',
      'Una diferencia de opinión entre investigadores',
      'La inclinación de una línea en un gráfico',
    ],
    correcta: 0,
    explicacion: 'Lo que lo define es que sea sistemático: no se corrige repitiendo la medición, porque empuja siempre hacia el mismo lado. El error aleatorio sí se promedia.',
  },
  {
    id: 'len-147', tema: 'lexico', dificultad: 3,
    enunciado: 'Completa: "Su actitud fue ___ con lo que había dicho antes."',
    opciones: ['coherente', 'coherencia', 'coherentemente', 'cohesionada'],
    correcta: 0,
    explicacion: 'Hace falta un adjetivo que califique a "actitud". "Coherencia" es sustantivo, "coherentemente" adverbio, y "cohesionada" pertenece a otra familia de significado.',
  },
  {
    id: 'len-148', tema: 'lexico', dificultad: 4,
    enunciado: '¿Cuál es la diferencia entre connotación y denotación?',
    opciones: [
      'La denotación es el significado objetivo; la connotación, las asociaciones que la palabra arrastra',
      'La connotación es el significado del diccionario',
      'Son sinónimos usados en contextos distintos',
      'La denotación solo existe en textos literarios',
    ],
    correcta: 0,
    explicacion: '"Barato" y "económico" denotan casi lo mismo, pero la primera connota baja calidad y la segunda, buen criterio. En un texto argumentativo, la elección entre las dos es una decisión persuasiva.',
  },
  {
    id: 'len-149', tema: 'lexico', dificultad: 4,
    enunciado: '¿Qué es un eufemismo y qué efecto tiene en un texto?',
    opciones: [
      'Una expresión suave que reemplaza a otra incómoda y puede ocultar responsabilidad',
      'Una palabra culta que da prestigio al texto',
      'Una figura que exagera una cualidad',
      'Un sinónimo exacto de otra palabra',
    ],
    correcta: 0,
    explicacion: 'Decir "flexibilización laboral" en vez de "despidos" no es solo cortesía: desdibuja quién hace qué. Detectar eufemismos es parte de leer críticamente un discurso público.',
  },
  {
    id: 'len-150', tema: 'lexico', dificultad: 4,
    enunciado: 'En "Se produjo un incremento en el número de casos", ¿por qué la versión "Los casos aumentaron" suele ser mejor?',
    opciones: [
      'Porque sustituye una nominalización por un verbo y elimina palabras vacías',
      'Porque es más corta y las frases cortas siempre son mejores',
      'Porque "incremento" es un extranjerismo',
      'Porque la primera versión es gramaticalmente incorrecta',
    ],
    correcta: 0,
    explicacion: 'Convertir acciones en sustantivos ("incremento", "realización", "implementación") obliga a añadir verbos huecos como "producirse" o "llevarse a cabo". Devolverle la acción al verbo aligera el texto sin perder nada.',
  },

  // ----- Redacción del párrafo -----
  {
    id: 'len-151', tema: 'redaccion', dificultad: 1,
    enunciado: '¿Qué contiene la oración temática de un párrafo?',
    opciones: [
      'La idea principal que el resto del párrafo desarrolla',
      'Un ejemplo concreto',
      'La conclusión de todo el texto',
      'Una cita de autoridad',
    ],
    correcta: 0,
    explicacion: 'Suele ir al comienzo y funciona como promesa: anuncia de qué trata el párrafo y compromete al resto a cumplirlo.',
  },
  {
    id: 'len-152', tema: 'redaccion', dificultad: 1,
    enunciado: '¿Cuándo conviene empezar un párrafo nuevo?',
    opciones: [
      'Cuando se pasa a una idea distinta',
      'Cada cinco líneas exactamente',
      'Cada vez que aparece una coma',
      'Solo al cambiar de capítulo',
    ],
    correcta: 0,
    explicacion: 'El párrafo es una unidad de sentido, no de longitud. Un cambio de idea pide punto y aparte aunque el párrafo sea corto.',
  },
  {
    id: 'len-153', tema: 'redaccion', dificultad: 1,
    enunciado: 'En un texto argumentativo, la introducción debe:',
    opciones: [
      'Presentar el tema y anunciar la postura que se va a defender',
      'Resumir todas las conclusiones con detalle',
      'Incluir todas las citas del trabajo',
      'Explicar por qué el tema es difícil de tratar',
    ],
    correcta: 0,
    explicacion: 'El lector debe saber desde el principio de qué se habla y hacia dónde va el texto. Guardar la tesis para el final funciona en una novela, no en un ensayo.',
  },
  {
    id: 'len-154', tema: 'redaccion', dificultad: 2,
    enunciado: '¿Cuál es el principal problema de esta frase? "En relación con lo anteriormente mencionado, cabe señalar que se debe tener en cuenta que el proyecto es costoso."',
    opciones: [
      'Tiene demasiado relleno antes de llegar a la idea',
      'Le falta un conector',
      'El verbo está mal conjugado',
      'Es demasiado corta',
    ],
    correcta: 0,
    explicacion: 'Veinticuatro palabras para decir "el proyecto es costoso". Fórmulas como "cabe señalar que" o "se debe tener en cuenta que" rara vez aportan algo.',
  },
  {
    id: 'len-155', tema: 'redaccion', dificultad: 2,
    enunciado: '¿Qué caracteriza a un párrafo bien construido?',
    opciones: [
      'Una idea principal, oraciones de apoyo que la desarrollan y un cierre o transición',
      'Exactamente cinco oraciones',
      'Al menos una cita textual',
      'Una pregunta retórica al final',
    ],
    correcta: 0,
    explicacion: 'Si un párrafo contiene tres ideas distintas, lo que hay son tres párrafos mal separados. Si no contiene ninguna, sobra.',
  },
  {
    id: 'len-156', tema: 'redaccion', dificultad: 2,
    enunciado: '¿Cuál de estas versiones es más clara?',
    opciones: [
      'El comité aprobó el presupuesto',
      'El presupuesto fue aprobado por parte del comité',
      'Se procedió a la aprobación del presupuesto por el comité',
      'Tuvo lugar la aprobación presupuestal comitiva',
    ],
    correcta: 0,
    explicacion: 'Sujeto, verbo y complemento, en ese orden y sin rodeos. La voz pasiva y las nominalizaciones alargan la frase y esconden quién actúa.',
  },
  {
    id: 'len-157', tema: 'redaccion', dificultad: 2,
    enunciado: 'En la conclusión de un texto argumentativo NO conviene:',
    opciones: [
      'Introducir un argumento nuevo que no se desarrolló antes',
      'Retomar la tesis con otras palabras',
      'Señalar una consecuencia de lo argumentado',
      'Cerrar con una pregunta abierta bien traída',
    ],
    correcta: 0,
    explicacion: 'Un argumento nuevo al final queda sin defender y deja al lector con la sensación de que el texto se interrumpió.',
  },
  {
    id: 'len-158', tema: 'redaccion', dificultad: 2,
    enunciado: '¿Qué registro corresponde a un ensayo académico?',
    opciones: [
      'Formal: sin coloquialismos, con precisión y sin exceso de rodeos',
      'Coloquial, para que el texto resulte cercano',
      'Técnico al extremo, aunque el lector no entienda',
      'Literario, con abundancia de metáforas',
    ],
    correcta: 0,
    explicacion: 'Formal no significa rebuscado. Un texto académico puede y debe ser claro: la dificultad debe estar en las ideas, no en la sintaxis.',
  },
  {
    id: 'len-159', tema: 'redaccion', dificultad: 3,
    enunciado: '¿Cuál es el problema de una oración de cincuenta palabras con cuatro subordinadas encadenadas?',
    opciones: [
      'El lector pierde el hilo entre el sujeto y el verbo; conviene partirla en dos o tres',
      'Que las oraciones largas están prohibidas en español',
      'Que obliga a usar punto y coma',
      'Que no admite conectores',
    ],
    correcta: 0,
    explicacion: 'No hay un límite oficial de palabras, pero sí un límite de memoria del lector. Alternar frases largas y cortas es lo que da ritmo a un texto.',
  },
  {
    id: 'len-160', tema: 'redaccion', dificultad: 3,
    enunciado: 'En un texto académico, el uso de la primera persona ("en este trabajo sostengo que…"):',
    opciones: [
      'Se acepta cada vez más y aporta claridad sobre quién afirma qué',
      'Está siempre prohibido',
      'Es obligatorio en todas las disciplinas',
      'Solo se admite en la bibliografía',
    ],
    correcta: 0,
    explicacion: 'Varía por disciplina y por revista. Lo que sí conviene evitar es el impersonal sistemático que borra al autor y deja frases como "se considera que", donde nadie se hace responsable.',
  },
  {
    id: 'len-161', tema: 'redaccion', dificultad: 3,
    enunciado: '¿Cómo se corrige "El estudio demuestra que sí funciona. Esto es importante."?',
    opciones: [
      'Precisando qué funciona y por qué es importante, porque las dos frases son huecas',
      'Uniendo las dos oraciones con una coma',
      'Cambiando el verbo a voz pasiva',
      'Añadiendo un conector de contraste',
    ],
    correcta: 0,
    explicacion: 'Son frases que parecen decir algo sin decirlo: falta el contenido. Reescribirlas exige responder qué funciona, en qué medida y para quién.',
  },
  {
    id: 'len-162', tema: 'redaccion', dificultad: 3,
    enunciado: '¿Qué función cumple la transición entre párrafos?',
    opciones: [
      'Mostrar la relación lógica entre la idea que termina y la que empieza',
      'Rellenar el espacio entre dos párrafos',
      'Repetir la idea anterior con otras palabras',
      'Anunciar la conclusión del texto',
    ],
    correcta: 0,
    explicacion: 'Sin transición, un texto parece una lista de párrafos. Basta a veces con una frase que retome lo dicho y anuncie el giro.',
  },
  {
    id: 'len-163', tema: 'redaccion', dificultad: 4,
    enunciado: '¿Por qué conviene evitar frases como "es de público conocimiento que" o "nadie puede negar que"?',
    opciones: [
      'Porque dan por probado lo que habría que argumentar y cierran la discusión de antemano',
      'Porque son demasiado largas',
      'Porque contienen errores gramaticales',
      'Porque solo se usan en textos literarios',
    ],
    correcta: 0,
    explicacion: 'Presentar una afirmación como evidente es una estrategia retórica, no un argumento. Un lector atento la identifica de inmediato y la lee como una señal de debilidad.',
  },
  {
    id: 'len-164', tema: 'redaccion', dificultad: 4,
    enunciado: 'Un párrafo empieza con "La educación rural en Colombia enfrenta tres obstáculos" y solo desarrolla dos. ¿Qué falla?',
    opciones: [
      'La oración temática promete algo que el párrafo no cumple, y eso desorienta al lector',
      'Nada: el tercero puede quedar implícito',
      'El párrafo es demasiado corto',
      'Falta una cita de autoridad',
    ],
    correcta: 0,
    explicacion: 'Anunciar un número obliga a cumplirlo. Es un error frecuente al reescribir: se elimina un apartado y se olvida ajustar la frase que lo anunciaba.',
  },
  {
    id: 'len-165', tema: 'redaccion', dificultad: 4,
    enunciado: '¿Cuál es la mejor forma de corregir "Se realizó la implementación de una metodología de carácter cualitativo"?',
    opciones: [
      '"Se usó una metodología cualitativa"',
      '"Se procedió a implementar una metodología cualitativa"',
      '"La implementación metodológica cualitativa fue realizada"',
      '"Se efectuó la implementación de una metodología cualitativa"',
    ],
    correcta: 0,
    explicacion: 'Se pasa de nueve palabras a cinco sin perder un gramo de información. "Realizar la implementación de" es un verbo vacío sosteniendo un sustantivo que ya era un verbo.',
  },

  // ----- Citación y uso de fuentes -----
  {
    id: 'len-166', tema: 'citacion', dificultad: 1,
    enunciado: '¿Qué es una cita textual?',
    opciones: [
      'La reproducción exacta de las palabras de otro autor, entre comillas y con su referencia',
      'Un resumen de lo que dijo un autor',
      'Una idea propia inspirada en otra fuente',
      'La lista de libros consultados',
    ],
    correcta: 0,
    explicacion: 'Si se cambia una sola palabra ya no es textual: es paráfrasis. Y en los dos casos hay que dar la referencia.',
  },
  {
    id: 'len-167', tema: 'citacion', dificultad: 1,
    enunciado: '¿Qué es el plagio?',
    opciones: [
      'Presentar como propias las ideas o palabras de otra persona',
      'Citar demasiadas fuentes en un trabajo',
      'Usar fuentes antiguas',
      'Copiar una frase entre comillas y citarla',
    ],
    correcta: 0,
    explicacion: 'Lo que define el plagio es la falta de atribución, no la copia en sí. Citar correctamente es lo que convierte una copia en una cita.',
  },
  {
    id: 'len-168', tema: 'citacion', dificultad: 1,
    enunciado: '¿Qué datos mínimos lleva una referencia bibliográfica de un libro?',
    opciones: [
      'Autor, año, título y editorial',
      'Solo el título',
      'Autor y número de páginas',
      'Título y precio de venta',
    ],
    correcta: 0,
    explicacion: 'Con esos cuatro datos cualquier lector puede localizar la obra. Los formatos concretos (APA, MLA, Chicago) cambian el orden y la puntuación, pero no la información.',
  },
  {
    id: 'len-169', tema: 'citacion', dificultad: 2,
    enunciado: '¿Qué es una paráfrasis correcta?',
    opciones: [
      'Reformular la idea de un autor con palabras propias y citar la fuente',
      'Copiar la frase cambiando dos o tres palabras',
      'Resumir sin mencionar de dónde salió',
      'Traducir literalmente un texto en otro idioma',
    ],
    correcta: 0,
    explicacion: 'Cambiar sinónimos manteniendo la estructura sigue siendo plagio, aunque se cite. Parafrasear bien exige entender la idea y reconstruirla.',
  },
  {
    id: 'len-170', tema: 'citacion', dificultad: 2,
    enunciado: 'En formato APA, la cita dentro del texto incluye:',
    opciones: [
      'Apellido del autor y año, por ejemplo (García, 2019)',
      'Nombre completo y título de la obra',
      'Solo el número de página',
      'El nombre de la editorial',
    ],
    correcta: 0,
    explicacion: 'Si la cita es textual se añade la página: (García, 2019, p. 45). La referencia completa va al final, en la lista de referencias.',
  },
  {
    id: 'len-171', tema: 'citacion', dificultad: 2,
    enunciado: '¿Para qué sirven los puntos suspensivos entre corchetes […] dentro de una cita?',
    opciones: [
      'Para indicar que se omitió una parte del texto original',
      'Para señalar que el autor dudaba',
      'Para marcar el final de la cita',
      'Para añadir un comentario propio',
    ],
    correcta: 0,
    explicacion: 'Los corchetes distinguen lo que hace quien cita de lo que estaba en el original. Se usan también para añadir una aclaración: "él [el ministro] dijo que…".',
  },
  {
    id: 'len-172', tema: 'citacion', dificultad: 2,
    enunciado: '¿Qué significa "et al." en una cita?',
    opciones: [
      '"Y otros": indica que la obra tiene más autores de los que se nombran',
      '"Es decir"',
      '"Sin fecha"',
      '"Citado en otra fuente"',
    ],
    correcta: 0,
    explicacion: 'Viene del latín "et alii". "Sin fecha" se abrevia s. f., y "citado en" se marca con "como se citó en".',
  },
  {
    id: 'len-173', tema: 'citacion', dificultad: 3,
    enunciado: '¿Cuándo NO hace falta citar una fuente?',
    opciones: [
      'Cuando se trata de conocimiento común y verificable, como que Colombia limita con Ecuador',
      'Cuando el texto es un trabajo de clase y no se va a publicar',
      'Cuando la fuente es una página de internet',
      'Cuando se parafrasea en vez de copiar',
    ],
    correcta: 0,
    explicacion: 'El conocimiento general no necesita respaldo. Todo dato específico, cifra, interpretación o idea ajena sí, se copie o se parafrasee.',
  },
  {
    id: 'len-174', tema: 'citacion', dificultad: 3,
    enunciado: '¿Cómo se cita una idea que se leyó en un autor que a su vez citaba a otro?',
    opciones: [
      'Como cita secundaria: (Pérez, 1990, como se citó en Gómez, 2020)',
      'Citando solo al autor original, como si se hubiera leído',
      'Citando solo al segundo autor y omitiendo al primero',
      'No se puede citar en ese caso',
    ],
    correcta: 0,
    explicacion: 'Atribuir directamente algo que no se leyó es deshonesto y arrastra los errores de quien lo citó primero. Lo ideal es ir a la fuente original; si no se puede, se declara.',
  },
  {
    id: 'len-175', tema: 'citacion', dificultad: 3,
    enunciado: '¿Qué distingue a una fuente primaria de una secundaria?',
    opciones: [
      'La primaria es el documento original o el dato de primera mano; la secundaria lo comenta o interpreta',
      'La primaria es más antigua',
      'La secundaria siempre es menos confiable',
      'La primaria es la que aparece primero en la bibliografía',
    ],
    correcta: 0,
    explicacion: 'Una ley, una entrevista o los datos de un experimento son primarias; un artículo que las analiza es secundaria. Las dos sirven, pero conviene saber cuál se está usando.',
  },
  {
    id: 'len-176', tema: 'citacion', dificultad: 3,
    enunciado: 'Un trabajo con muchas citas textuales largas y pocas frases propias tiene el problema de que:',
    opciones: [
      'No muestra el trabajo intelectual del autor, aunque todo esté bien citado',
      'Infringe automáticamente los derechos de autor',
      'Es demasiado corto',
      'No puede llevar bibliografía',
    ],
    correcta: 0,
    explicacion: 'Citar bien evita el plagio, pero no reemplaza al análisis. La cita debe apoyar un argumento propio, no ocupar su lugar.',
  },
  {
    id: 'len-177', tema: 'citacion', dificultad: 4,
    enunciado: '¿Por qué el autoplagio se considera una falta académica?',
    opciones: [
      'Porque presenta como nuevo un trabajo ya entregado o publicado, engañando sobre el aporte real',
      'Porque nadie puede citarse a sí mismo',
      'Porque los derechos pasan siempre a la editorial',
      'No se considera falta en ningún contexto',
    ],
    correcta: 0,
    explicacion: 'El problema no es reutilizar lo propio, sino hacerlo sin declararlo: el lector o el evaluador creen estar ante material inédito. Se resuelve citando el trabajo anterior.',
  },
  {
    id: 'len-178', tema: 'citacion', dificultad: 4,
    enunciado: 'Al usar un texto generado por una herramienta de inteligencia artificial en un trabajo académico, lo apropiado es:',
    opciones: [
      'Declarar su uso según lo que exija la institución y verificar toda la información antes de incluirla',
      'Usarlo sin mencionarlo, porque no es obra de una persona',
      'Citarlo como si fuera un autor humano con apellido y año',
      'Evitarlo por completo en cualquier circunstancia',
    ],
    correcta: 0,
    explicacion: 'Las políticas varían entre instituciones y revistas, pero coinciden en dos puntos: transparencia sobre el uso y responsabilidad del autor humano por lo que afirma el texto.',
  },
  {
    id: 'len-179', tema: 'citacion', dificultad: 4,
    enunciado: 'Un estudiante encuentra una cifra en un blog que no dice de dónde la sacó. ¿Qué debe hacer?',
    opciones: [
      'Buscar la fuente original del dato y citar esa, o no usarlo',
      'Citar el blog y dar el dato por bueno',
      'Usar el dato sin citar nada, ya que el blog tampoco cita',
      'Cambiar la cifra por una aproximación propia',
    ],
    correcta: 0,
    explicacion: 'Un dato sin origen no es verificable, y citar la fuente intermedia solo traslada el problema. Rastrear la cifra hasta quien la produjo es parte del trabajo.',
  },
  {
    id: 'len-180', tema: 'citacion', dificultad: 4,
    enunciado: '¿Qué función cumple la lista de referencias al final de un trabajo, más allá de cumplir un requisito?',
    opciones: [
      'Permite al lector verificar cada afirmación y continuar la investigación por su cuenta',
      'Demuestra cuántos libros leyó el autor',
      'Sirve para alargar el documento',
      'Protege legalmente al autor ante cualquier demanda',
    ],
    correcta: 0,
    explicacion: 'Es lo que hace acumulativo al conocimiento: cada trabajo deja el rastro para que otro pueda revisarlo o seguir desde ahí. Por eso una referencia incompleta es un problema real, no un descuido de formato.',
  },
];
