/**
 * literatura.js — Banco de literatura.
 *
 * Lo que las pruebas dan por sabido: reconocer un género y una figura, contar
 * un verso, identificar quién narra, y ubicar las obras y los movimientos que
 * aparecen una y otra vez. El análisis pesa más que la lista de títulos.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const LITERATURA = [
  // ----- Géneros literarios -----
  {
    id: 'lit-001', tema: 'generos', dificultad: 1,
    enunciado: '¿Cuáles son los tres grandes géneros literarios?',
    opciones: ['Narrativo, lírico y dramático', 'Novela, cuento y poema', 'Épico, cómico y trágico', 'Prosa, verso y diálogo'],
    correcta: 0,
    explicacion: 'Novela y cuento son subgéneros narrativos; tragedia y comedia, subgéneros dramáticos. Prosa y verso son formas de escritura, no géneros.',
  },
  {
    id: 'lit-002', tema: 'generos', dificultad: 1,
    enunciado: '¿Qué caracteriza al género lírico?',
    opciones: [
      'Expresa la subjetividad del hablante: emociones, ideas, estados de ánimo',
      'Narra una historia con personajes y acciones',
      'Está escrito para ser representado en un escenario',
      'Siempre se escribe en prosa',
    ],
    correcta: 0,
    explicacion: 'Lo lírico no cuenta: expresa. Puede escribirse en verso o en prosa poética, y su eje no es la acción sino la voz que habla.',
  },
  {
    id: 'lit-003', tema: 'generos', dificultad: 1,
    enunciado: 'Una fábula se distingue de otros relatos porque:',
    opciones: [
      'Suele tener personajes animales y termina con una enseñanza',
      'Siempre está escrita en verso libre',
      'No tiene narrador',
      'Es más larga que una novela',
    ],
    correcta: 0,
    explicacion: 'La moraleja es su rasgo definitorio. Esopo, Samaniego e Iriarte son los nombres clásicos del subgénero.',
  },
  {
    id: 'lit-004', tema: 'generos', dificultad: 2,
    enunciado: '¿Cuál es la diferencia principal entre un cuento y una novela?',
    opciones: [
      'El cuento busca un efecto único y concentrado; la novela desarrolla varias líneas y personajes',
      'El cuento es para niños y la novela para adultos',
      'El cuento no tiene conflicto',
      'La novela nunca usa diálogos',
    ],
    correcta: 0,
    explicacion: 'No es solo cuestión de extensión. Como decía Cortázar, la novela gana por puntos y el cuento por nocaut: todo en él debe apuntar al mismo blanco.',
  },
  {
    id: 'lit-005', tema: 'generos', dificultad: 2,
    enunciado: '¿Qué distingue a la tragedia de la comedia en el teatro clásico?',
    opciones: [
      'La tragedia presenta un héroe que cae por un destino o un error; la comedia termina bien y corrige costumbres',
      'La tragedia es en verso y la comedia en prosa',
      'La comedia no tiene conflicto dramático',
      'La tragedia es más corta',
    ],
    correcta: 0,
    explicacion: 'Aristóteles describió el efecto de la tragedia como catarsis: compasión y temor que purgan al espectador. La comedia trabaja con personajes comunes y desenlace feliz.',
  },
  {
    id: 'lit-006', tema: 'generos', dificultad: 2,
    enunciado: 'El ensayo pertenece al género:',
    opciones: [
      'Didáctico o expositivo-argumentativo, fuera de los tres grandes géneros de ficción',
      'Narrativo, porque cuenta hechos',
      'Lírico, porque expresa opiniones',
      'Dramático, porque discute',
    ],
    correcta: 0,
    explicacion: 'Montaigne lo inauguró en el siglo XVI. No inventa un mundo: argumenta sobre el real, aunque lo haga con recursos literarios.',
  },
  {
    id: 'lit-007', tema: 'generos', dificultad: 2,
    enunciado: '¿Qué es una acotación en un texto dramático?',
    opciones: [
      'La indicación del autor sobre escenografía, gestos o movimientos, que no se pronuncia',
      'Un parlamento breve de un personaje secundario',
      'El resumen de la obra al inicio',
      'La división en actos',
    ],
    correcta: 0,
    explicacion: 'Suele ir entre paréntesis o en cursiva. Es la única voz del autor en un género donde todo lo demás son palabras de los personajes.',
  },
  {
    id: 'lit-008', tema: 'generos', dificultad: 2,
    enunciado: '¿Qué caracteriza a la épica clásica?',
    opciones: [
      'Narra en verso las hazañas de un héroe que representa los valores de un pueblo',
      'Expresa los sentimientos íntimos del poeta',
      'Se escribe siempre en prosa breve',
      'Carece de elementos sobrenaturales',
    ],
    correcta: 0,
    explicacion: 'La Ilíada, la Odisea y la Eneida son sus modelos. Los dioses intervienen constantemente, y el héroe encarna lo que su comunidad admira.',
  },
  {
    id: 'lit-009', tema: 'generos', dificultad: 3,
    enunciado: '¿Por qué "Cien años de soledad" es una novela y no una epopeya, si narra la historia de un pueblo entero?',
    opciones: [
      'Porque está en prosa, con un narrador moderno y personajes individuales, no en verso con un héroe ejemplar',
      'Porque es demasiado extensa para ser epopeya',
      'Porque no incluye elementos sobrenaturales',
      'Porque fue escrita en el siglo XX',
    ],
    correcta: 0,
    explicacion: 'El alcance colectivo no define el género: lo definen la forma, la voz narrativa y el tratamiento del personaje. Macondo tiene aire épico, pero sus Buendía son individuos contradictorios, no héroes ejemplares.',
  },
  {
    id: 'lit-010', tema: 'generos', dificultad: 3,
    enunciado: '¿Qué es el subgénero de la novela de formación o Bildungsroman?',
    opciones: [
      'Aquella que sigue la maduración de un protagonista desde la juventud',
      'La que enseña un oficio al lector',
      'La que se ambienta en una escuela',
      'La que se escribe para adolescentes',
    ],
    correcta: 0,
    explicacion: 'El eje es el aprendizaje interior del personaje frente al mundo. El público al que va dirigida es otra cosa: hay Bildungsromane densos escritos para adultos.',
  },
  {
    id: 'lit-011', tema: 'generos', dificultad: 3,
    enunciado: 'La crónica periodística de autor se sitúa entre dos territorios porque:',
    opciones: [
      'Usa recursos narrativos literarios pero se compromete con hechos verificables',
      'Mezcla poesía y teatro',
      'Se publica en libro y no en prensa',
      'No tiene narrador identificable',
    ],
    correcta: 0,
    explicacion: 'Es el terreno de "Relato de un náufrago" o de la llamada nueva crónica latinoamericana: escena, diálogo y tensión narrativa al servicio de algo que ocurrió de verdad.',
  },
  {
    id: 'lit-012', tema: 'generos', dificultad: 3,
    enunciado: '¿Qué distingue a un microrrelato de una anécdota?',
    opciones: [
      'El microrrelato tiene estructura narrativa completa y suele apoyarse en un giro final',
      'El microrrelato es siempre humorístico',
      'La anécdota está escrita en verso',
      'No hay diferencia: son sinónimos',
    ],
    correcta: 0,
    explicacion: 'En pocas líneas debe haber situación, tensión y desenlace. El clásico de Monterroso —"Cuando despertó, el dinosaurio todavía estaba allí"— funciona porque implica un antes y un después.',
  },
  {
    id: 'lit-013', tema: 'generos', dificultad: 4,
    enunciado: '¿Por qué se dice que las fronteras entre géneros son históricas y no naturales?',
    opciones: [
      'Porque cada época redefine qué cuenta como novela, poema o teatro, y muchas obras nacen justamente cruzando esos límites',
      'Porque los géneros los inventó la crítica del siglo XX',
      'Porque solo existen en las lenguas europeas',
      'Porque los autores desconocen las reglas',
    ],
    correcta: 0,
    explicacion: 'La novela fue considerada un género menor durante siglos; el verso libre escandalizó cuando apareció. Clasificar sirve para leer, pero no explica lo que una obra hace.',
  },
  {
    id: 'lit-014', tema: 'generos', dificultad: 4,
    enunciado: 'Un texto narra hechos reales de la vida del autor con estructura de novela y admite que altera algunos detalles. ¿Cómo se clasifica mejor?',
    opciones: [
      'Como autoficción: un territorio deliberadamente ambiguo entre autobiografía y novela',
      'Como autobiografía pura',
      'Como novela realista sin más',
      'Como ensayo personal',
    ],
    correcta: 0,
    explicacion: 'La autobiografía promete verdad; la novela no promete nada. La autoficción explota esa tensión: el pacto con el lector queda intencionalmente sin resolver.',
  },
  {
    id: 'lit-015', tema: 'generos', dificultad: 4,
    enunciado: '¿Qué es el "pacto de lectura" y por qué importa para el género?',
    opciones: [
      'El acuerdo implícito sobre cómo debe leerse un texto: como ficción, como testimonio o como argumento',
      'El contrato entre el autor y su editorial',
      'La promesa del autor de terminar la obra',
      'El precio acordado de un libro',
    ],
    correcta: 0,
    explicacion: 'Leer un diario como novela o una novela como confesión cambia todo lo que el texto significa. Buena parte de la literatura contemporánea juega precisamente con romper ese pacto.',
  },

  // ----- Figuras literarias -----
  {
    id: 'lit-016', tema: 'figuras', dificultad: 1,
    enunciado: 'En "sus ojos son dos luceros", ¿qué figura aparece?',
    opciones: ['Metáfora', 'Símil', 'Hipérbole', 'Anáfora'],
    correcta: 0,
    explicacion: 'La metáfora identifica dos términos sin usar nexo comparativo. Si dijera "como dos luceros" sería un símil.',
  },
  {
    id: 'lit-017', tema: 'figuras', dificultad: 1,
    enunciado: '"El viento susurraba entre los árboles" es un ejemplo de:',
    opciones: ['Personificación', 'Hipérbole', 'Metonimia', 'Paradoja'],
    correcta: 0,
    explicacion: 'Susurrar es una acción humana atribuida a algo que no lo es. También se le llama prosopopeya.',
  },
  {
    id: 'lit-018', tema: 'figuras', dificultad: 1,
    enunciado: '"Te lo he dicho un millón de veces" es un ejemplo de:',
    opciones: ['Hipérbole', 'Símil', 'Metáfora', 'Aliteración'],
    correcta: 0,
    explicacion: 'La hipérbole exagera deliberadamente para dar intensidad, sin pretender ser tomada al pie de la letra.',
  },
  {
    id: 'lit-019', tema: 'figuras', dificultad: 2,
    enunciado: 'En "el ruido con que rueda la ronca tempestad", ¿qué figura predomina?',
    opciones: ['Aliteración', 'Anáfora', 'Hipérbaton', 'Elipsis'],
    correcta: 0,
    explicacion: 'La repetición del sonido r imita el estruendo de la tormenta. La aliteración busca un efecto sonoro que refuerza el sentido.',
  },
  {
    id: 'lit-020', tema: 'figuras', dificultad: 2,
    enunciado: '"Temprano levantó la muerte el vuelo, / temprano madrugó la madrugada". ¿Qué figura se repite al inicio de los versos?',
    opciones: ['Anáfora', 'Aliteración', 'Metonimia', 'Sinécdoque'],
    correcta: 0,
    explicacion: 'La anáfora es la repetición de una o más palabras al comienzo de versos u oraciones sucesivas. Aquí, además, hay una derivación entre "madrugó" y "madrugada".',
  },
  {
    id: 'lit-021', tema: 'figuras', dificultad: 2,
    enunciado: 'En "leí a Cervantes", ¿qué figura se emplea?',
    opciones: [
      'Metonimia: se nombra al autor por su obra',
      'Metáfora',
      'Hipérbole',
      'Personificación',
    ],
    correcta: 0,
    explicacion: 'La metonimia sustituye un término por otro con el que tiene una relación de contigüidad: autor por obra, continente por contenido, causa por efecto.',
  },
  {
    id: 'lit-022', tema: 'figuras', dificultad: 2,
    enunciado: '¿Qué figura aparece en "un silencio ensordecedor"?',
    opciones: ['Oxímoron', 'Símil', 'Anáfora', 'Elipsis'],
    correcta: 0,
    explicacion: 'El oxímoron une dos términos contradictorios en una misma expresión. Si la contradicción es de toda una idea y no de dos palabras contiguas, se llama paradoja.',
  },
  {
    id: 'lit-023', tema: 'figuras', dificultad: 2,
    enunciado: '"Del salón en el ángulo oscuro… veíase el arpa" altera el orden normal de las palabras. Eso es:',
    opciones: ['Hipérbaton', 'Anáfora', 'Elipsis', 'Aliteración'],
    correcta: 0,
    explicacion: 'El hipérbaton desordena la sintaxis habitual por razones de ritmo, rima o énfasis. Es muy frecuente en la poesía del Siglo de Oro.',
  },
  {
    id: 'lit-024', tema: 'figuras', dificultad: 3,
    enunciado: '¿Cuál es la diferencia entre metáfora y símil?',
    opciones: [
      'El símil mantiene el nexo comparativo ("como", "cual"); la metáfora lo suprime e identifica los términos',
      'La metáfora solo se usa en poesía',
      'El símil compara cosas reales y la metáfora, imaginarias',
      'No hay diferencia formal, solo de intensidad',
    ],
    correcta: 0,
    explicacion: '"Sus dientes son como perlas" es símil; "sus dientes son perlas" es metáfora; "las perlas de su boca" es una metáfora que ya ni nombra el término real.',
  },
  {
    id: 'lit-025', tema: 'figuras', dificultad: 3,
    enunciado: 'En "pidió la mano de su hija" y "tiene veinte cabezas de ganado", ¿qué figura comparten?',
    opciones: [
      'Sinécdoque: se nombra la parte por el todo',
      'Metáfora',
      'Hipérbole',
      'Paradoja',
    ],
    correcta: 0,
    explicacion: 'La sinécdoque es un caso particular de metonimia basado en la relación parte-todo. "Mano" está por la persona entera y "cabezas" por los animales completos.',
  },
  {
    id: 'lit-026', tema: 'figuras', dificultad: 3,
    enunciado: '"Vivo sin vivir en mí" (Santa Teresa) es un ejemplo de:',
    opciones: ['Paradoja', 'Oxímoron', 'Metonimia', 'Símil'],
    correcta: 0,
    explicacion: 'La paradoja plantea una contradicción aparente que encierra un sentido profundo. A diferencia del oxímoron, no se limita a dos palabras contiguas: afecta a toda la proposición.',
  },
  {
    id: 'lit-027', tema: 'figuras', dificultad: 3,
    enunciado: 'Cuando un narrador dice "qué gran idea" ante un desastre evidente, emplea:',
    opciones: ['Ironía', 'Hipérbole', 'Aliteración', 'Anáfora'],
    correcta: 0,
    explicacion: 'La ironía dice lo contrario de lo que se quiere dar a entender y confía en que el lector lo note. Cuando se vuelve amarga y agresiva se llama sarcasmo.',
  },
  {
    id: 'lit-028', tema: 'figuras', dificultad: 4,
    enunciado: '¿Por qué "la ciudad dormía" y "la ciudad votó por el cambio" son figuras distintas?',
    opciones: [
      'La primera es personificación; la segunda, metonimia de los habitantes por el lugar',
      'Las dos son personificaciones',
      'Las dos son metáforas',
      'La segunda no contiene ninguna figura',
    ],
    correcta: 0,
    explicacion: 'Dormir atribuye a la ciudad una condición humana. Votar, en cambio, no la humaniza: sustituye a quienes votan por el lugar donde viven, que es una relación de contigüidad.',
    pista: 'Pregúntate si la figura humaniza algo o si simplemente lo nombra por otra cosa cercana.',
  },
  {
    id: 'lit-029', tema: 'figuras', dificultad: 4,
    enunciado: 'En "Es tan corto el amor y tan largo el olvido" (Neruda), ¿qué recurso organiza el verso?',
    opciones: [
      'Un paralelismo con antítesis: dos estructuras iguales que oponen sus términos',
      'Una aliteración de consonantes suaves',
      'Un hipérbaton que altera el sujeto',
      'Una sinécdoque del sentimiento',
    ],
    correcta: 0,
    explicacion: 'La estructura "tan + adjetivo + sustantivo" se repite idéntica, y sobre ese molde se enfrentan corto/largo y amor/olvido. El paralelismo hace que la oposición se sienta inevitable.',
  },
  {
    id: 'lit-030', tema: 'figuras', dificultad: 4,
    enunciado: '¿Qué distingue una metáfora viva de una metáfora lexicalizada como "la pata de la mesa"?',
    opciones: [
      'La lexicalizada ya se integró al idioma y no se percibe como figura; la viva produce un efecto de extrañeza',
      'La lexicalizada es incorrecta gramaticalmente',
      'La viva solo aparece en poesía culta',
      'No existe tal distinción',
    ],
    correcta: 0,
    explicacion: 'Nadie imagina un animal al oír "pata de la mesa": la imagen murió por uso. Buena parte del trabajo poético consiste en devolverle a la lengua esa capacidad de sorprender.',
  },

  // ----- Verso, métrica y rima -----
  {
    id: 'lit-031', tema: 'verso', dificultad: 1,
    enunciado: '¿Cuántas sílabas tiene un verso endecasílabo?',
    opciones: ['Once', 'Diez', 'Doce', 'Ocho'],
    correcta: 0,
    explicacion: 'El endecasílabo es el verso del soneto clásico. El octosílabo, de ocho, es el del romance y la copla.',
  },
  {
    id: 'lit-032', tema: 'verso', dificultad: 1,
    enunciado: '¿Qué es la rima consonante?',
    opciones: [
      'La coincidencia de todos los sonidos, vocales y consonantes, desde la última vocal acentuada',
      'La coincidencia solo de las vocales',
      'La repetición de la misma palabra al final',
      'La ausencia de rima',
    ],
    correcta: 0,
    explicacion: '"Canción" y "razón" riman en consonante. "Canto" y "barco" riman en asonante, porque solo coinciden las vocales a-o.',
  },
  {
    id: 'lit-033', tema: 'verso', dificultad: 1,
    enunciado: '¿Cuántos versos tiene un soneto?',
    opciones: ['Catorce', 'Diez', 'Doce', 'Dieciséis'],
    correcta: 0,
    explicacion: 'Se reparten en dos cuartetos y dos tercetos. El modelo llegó de Italia y se aclimató en España en el siglo XVI.',
  },
  {
    id: 'lit-034', tema: 'verso', dificultad: 2,
    enunciado: '¿Qué es la sinalefa?',
    opciones: [
      'La unión en una sola sílaba métrica de la vocal final de una palabra y la inicial de la siguiente',
      'La separación de un diptongo dentro de una palabra',
      'La repetición de un sonido al final del verso',
      'El acento en la última sílaba del verso',
    ],
    correcta: 0,
    explicacion: 'En "la alta torre", "la al" cuenta como una sola sílaba. Sin tener en cuenta la sinalefa es imposible medir bien un verso castellano.',
  },
  {
    id: 'lit-035', tema: 'verso', dificultad: 2,
    enunciado: 'Si un verso termina en palabra aguda, para el cómputo métrico:',
    opciones: ['Se suma una sílaba', 'Se resta una sílaba', 'No se altera el cómputo', 'Se suman dos sílabas'],
    correcta: 0,
    explicacion: 'Y si termina en esdrújula se resta una. Es la ley del acento final, que compensa el peso rítmico del cierre del verso.',
  },
  {
    id: 'lit-036', tema: 'verso', dificultad: 2,
    enunciado: '¿Qué caracteriza al romance como forma métrica?',
    opciones: [
      'Serie indefinida de versos octosílabos con rima asonante en los pares',
      'Catorce versos endecasílabos con rima consonante',
      'Cuatro versos de arte mayor',
      'Versos libres sin rima ni medida',
    ],
    correcta: 0,
    explicacion: 'Es la forma más característica de la tradición oral española, y por eso Lorca la recuperó en su "Romancero gitano".',
  },
  {
    id: 'lit-037', tema: 'verso', dificultad: 2,
    enunciado: '¿Cómo se llaman los versos de más de ocho sílabas?',
    opciones: ['De arte mayor', 'De arte menor', 'Versos blancos', 'Versos libres'],
    correcta: 0,
    explicacion: 'Los de ocho sílabas o menos son de arte menor. Es una frontera tradicional que separa el tono popular del culto.',
  },
  {
    id: 'lit-038', tema: 'verso', dificultad: 2,
    enunciado: '¿Qué es un verso blanco?',
    opciones: [
      'El que tiene medida regular pero carece de rima',
      'El que no tiene ni medida ni rima',
      'El que se deja en blanco a propósito',
      'El que rima consigo mismo',
    ],
    correcta: 0,
    explicacion: 'Se distingue del verso libre, que abandona también la medida fija. El endecasílabo blanco es habitual en el teatro en verso.',
  },
  {
    id: 'lit-039', tema: 'verso', dificultad: 3,
    enunciado: '¿Cuántas sílabas métricas tiene el verso "Volverán las oscuras golondrinas"?',
    opciones: ['Once', 'Doce', 'Diez', 'Trece'],
    correcta: 0,
    explicacion: 'Vol-ve-rán-las-os-cu-ras-go-lon-dri-nas son once sílabas: no hay sinalefa posible y la palabra final es grave, así que no se corrige nada. Es un endecasílabo.',
    pista: 'Separa en sílabas, busca vocales que choquen entre palabras y revisa el acento de la última palabra.',
  },
  {
    id: 'lit-040', tema: 'verso', dificultad: 3,
    enunciado: 'En el par "canto / barco", ¿qué tipo de rima hay?',
    opciones: [
      'Asonante: coinciden las vocales a-o pero no las consonantes',
      'Consonante: coinciden todos los sonidos finales',
      'No hay rima de ningún tipo',
      'Rima interna',
    ],
    correcta: 0,
    explicacion: 'Desde la última vocal acentuada, las vocales son a-o en las dos palabras, pero las consonantes difieren (nt frente a rc). Para que fuera consonante tendrían que coincidir todos los sonidos, como en "canto / manto".',
  },
  {
    id: 'lit-041', tema: 'verso', dificultad: 3,
    enunciado: '¿Qué es el encabalgamiento?',
    opciones: [
      'Cuando la unidad sintáctica no termina con el verso y continúa en el siguiente',
      'Cuando dos versos riman entre sí',
      'Cuando un verso tiene más sílabas de las debidas',
      'Cuando se repite una palabra al final de cada estrofa',
    ],
    correcta: 0,
    explicacion: 'Crea una tensión entre la pausa del verso y la de la frase, y suele usarse para acelerar el ritmo o destacar la palabra que queda colgando al final.',
  },
  {
    id: 'lit-042', tema: 'verso', dificultad: 3,
    enunciado: '¿Cuál es el esquema de rima más habitual de los cuartetos de un soneto clásico?',
    opciones: ['ABBA ABBA', 'ABAB CDCD', 'AABB CCDD', 'ABCD ABCD'],
    correcta: 0,
    explicacion: 'Es la rima abrazada. Los tercetos admiten más variación: CDC DCD, CDE CDE y otras combinaciones.',
  },
  {
    id: 'lit-043', tema: 'verso', dificultad: 4,
    enunciado: '¿Qué efecto busca un poeta al usar versos muy cortos frente a versos largos?',
    opciones: [
      'Los cortos aceleran y fragmentan el ritmo; los largos favorecen el desarrollo amplio y pausado',
      'Los cortos son siempre más fáciles de escribir',
      'Los largos impiden la rima',
      'La longitud no tiene ningún efecto rítmico',
    ],
    correcta: 0,
    explicacion: 'La pausa al final de cada verso es una unidad de respiración. Cuantas más pausas por línea de texto, más entrecortado se percibe el poema.',
  },
  {
    id: 'lit-044', tema: 'verso', dificultad: 4,
    enunciado: 'El verso libre no significa ausencia de forma porque:',
    opciones: [
      'Sustituye la medida fija por otros principios de organización: repetición, imagen, respiración, disposición en la página',
      'Siempre conserva la rima aunque no la medida',
      'Solo puede usarse en poemas breves',
      'Exige que todos los versos tengan el mismo número de palabras',
    ],
    correcta: 0,
    explicacion: 'Abandonar el metro obliga a construir el ritmo por otros medios. Un poema en verso libre mal hecho se nota precisamente porque no hay nada sosteniéndolo.',
  },
  {
    id: 'lit-045', tema: 'verso', dificultad: 4,
    enunciado: '¿Por qué la traducción de poesía plantea un problema que la de prosa no tiene en la misma medida?',
    opciones: [
      'Porque el sentido está ligado al sonido, la medida y la rima, que rara vez se conservan al cambiar de lengua',
      'Porque los poemas usan palabras más difíciles',
      'Porque los poemas son más antiguos',
      'Porque la poesía no admite notas al pie',
    ],
    correcta: 0,
    explicacion: 'El traductor debe elegir qué sacrificar: la literalidad o la música. De ahí el viejo dicho italiano "traduttore, traditore".',
  },
  // ----- Narrador y punto de vista -----
  {
    id: 'lit-046', tema: 'narrador', dificultad: 1,
    enunciado: 'Un narrador que dice "yo caminaba por la calle" es:',
    opciones: ['Narrador en primera persona', 'Narrador omnisciente', 'Narrador observador', 'Narrador en segunda persona'],
    correcta: 0,
    explicacion: 'El uso del "yo" indica que quien narra participa en la historia, como protagonista o como testigo.',
  },
  {
    id: 'lit-047', tema: 'narrador', dificultad: 1,
    enunciado: '¿Qué caracteriza al narrador omnisciente?',
    opciones: [
      'Conoce los pensamientos y sentimientos de todos los personajes',
      'Solo sabe lo que ve desde fuera',
      'Es siempre un personaje de la historia',
      'Se dirige al lector como "tú"',
    ],
    correcta: 0,
    explicacion: 'Narra en tercera persona y puede entrar y salir de cualquier conciencia, además de adelantar o retroceder en el tiempo a voluntad.',
  },
  {
    id: 'lit-048', tema: 'narrador', dificultad: 1,
    enunciado: '¿Qué es un flashback o analepsis?',
    opciones: [
      'Un salto hacia atrás en el tiempo del relato',
      'Un salto hacia el futuro',
      'La repetición de una escena idéntica',
      'El final abierto de una historia',
    ],
    correcta: 0,
    explicacion: 'La prolepsis es lo contrario: adelantar algo que ocurrirá después, como el célebre comienzo de "Cien años de soledad".',
  },
  {
    id: 'lit-049', tema: 'narrador', dificultad: 2,
    enunciado: '¿Qué distingue al narrador protagonista del narrador testigo?',
    opciones: [
      'El protagonista cuenta su propia historia; el testigo narra en primera persona la de otro',
      'El testigo narra siempre en tercera persona',
      'El protagonista es omnisciente',
      'No hay diferencia: los dos usan el "yo"',
    ],
    correcta: 0,
    explicacion: 'Los dos usan "yo", pero el foco cambia. El doctor Watson es el ejemplo clásico de testigo: narra las hazañas de Sherlock Holmes, no las suyas.',
  },
  {
    id: 'lit-050', tema: 'narrador', dificultad: 2,
    enunciado: 'El narrador que solo registra lo que se ve y se oye, sin entrar en la mente de nadie, se llama:',
    opciones: ['Objetivo o cámara', 'Omnisciente', 'Protagonista', 'Editor'],
    correcta: 0,
    explicacion: 'Funciona como una cámara de cine: muestra, no explica. Hemingway lo llevó al extremo en cuentos como "Colinas como elefantes blancos".',
  },
  {
    id: 'lit-051', tema: 'narrador', dificultad: 2,
    enunciado: '¿Qué es un narrador poco fiable?',
    opciones: [
      'Aquel cuya versión el lector tiene motivos para poner en duda',
      'Aquel que comete errores gramaticales',
      'Aquel que no conoce el final de la historia',
      'Aquel que cambia de persona verbal',
    ],
    correcta: 0,
    explicacion: 'Puede mentir, estar loco, ser un niño que no entiende lo que ve o tener interés en ocultar algo. El lector debe reconstruir los hechos contra la voz que los cuenta.',
  },
  {
    id: 'lit-052', tema: 'narrador', dificultad: 2,
    enunciado: 'La diferencia entre autor y narrador consiste en que:',
    opciones: [
      'El autor es la persona real que escribe; el narrador es la voz construida dentro del texto',
      'Son lo mismo en toda obra de ficción',
      'El narrador siempre es un personaje',
      'El autor aparece siempre en primera persona',
    ],
    correcta: 0,
    explicacion: 'Confundirlos lleva a atribuirle al escritor las opiniones de sus personajes. La voz que narra es una creación más de la obra.',
  },
  {
    id: 'lit-053', tema: 'narrador', dificultad: 2,
    enunciado: '¿Qué es el monólogo interior?',
    opciones: [
      'La transcripción del flujo de pensamiento de un personaje, con su desorden incluido',
      'Un parlamento largo dicho en voz alta en el teatro',
      'Una carta que el personaje se escribe a sí mismo',
      'Un resumen de lo pensado, hecho por el narrador',
    ],
    correcta: 0,
    explicacion: 'Joyce y Woolf lo convirtieron en técnica central. Se distingue del estilo indirecto libre, donde el narrador se acerca al personaje pero conserva la tercera persona.',
  },
  {
    id: 'lit-054', tema: 'narrador', dificultad: 3,
    enunciado: 'En "Pensó que todo estaba perdido. Qué tontería haber venido hasta allí", ¿qué técnica aparece en la segunda frase?',
    opciones: [
      'Estilo indirecto libre: la voz del personaje invade la narración sin marcas de cita',
      'Diálogo directo',
      'Monólogo interior puro',
      'Narración omnisciente neutra',
    ],
    correcta: 0,
    explicacion: 'No hay verbo introductor ni comillas, pero el juicio ("qué tontería") es claramente del personaje. Es el recurso que Flaubert popularizó y que borra la frontera entre narrador y conciencia narrada.',
    pista: 'Fíjate en quién está valorando lo que se dice, aunque el verbo esté en tercera persona.',
  },
  {
    id: 'lit-055', tema: 'narrador', dificultad: 3,
    enunciado: '¿Qué efecto produce narrar en presente en vez de en pasado?',
    opciones: [
      'Da inmediatez y suspenso, porque el desenlace parece no estar decidido',
      'Hace el relato más objetivo',
      'Obliga a usar narrador omnisciente',
      'Impide los saltos temporales',
    ],
    correcta: 0,
    explicacion: 'El pasado sugiere que alguien ya conoce el final y lo está contando. El presente elimina esa distancia y pone al lector dentro de la escena.',
  },
  {
    id: 'lit-056', tema: 'narrador', dificultad: 3,
    enunciado: '¿Qué es la focalización en el análisis narrativo?',
    opciones: [
      'El punto desde el cual se percibe lo narrado, que no siempre coincide con quién narra',
      'El tema central de la obra',
      'La cantidad de personajes que intervienen',
      'El lugar donde ocurre la historia',
    ],
    correcta: 0,
    explicacion: 'Genette distinguió "quién ve" de "quién habla". Un narrador en tercera persona puede contar limitándose a lo que percibe un solo personaje: eso es focalización interna.',
  },
  {
    id: 'lit-057', tema: 'narrador', dificultad: 3,
    enunciado: 'Si una novela cuenta los mismos hechos desde tres personajes distintos, el efecto principal es:',
    opciones: [
      'Relativizar la verdad de lo ocurrido y obligar al lector a comparar versiones',
      'Alargar la obra innecesariamente',
      'Facilitar la lectura al repetir la información',
      'Eliminar la necesidad de un narrador',
    ],
    correcta: 0,
    explicacion: 'Es la estructura de "Rashomon" o de "El sonido y la furia". El lector deja de recibir una historia y pasa a construirla.',
  },
  {
    id: 'lit-058', tema: 'narrador', dificultad: 4,
    enunciado: '¿Por qué un narrador en segunda persona ("caminas por la calle y no la reconoces") resulta tan poco frecuente?',
    opciones: [
      'Porque impone al lector un papel dentro del relato y esa tensión es difícil de sostener en obras largas',
      'Porque es gramaticalmente incorrecto',
      'Porque impide usar diálogos',
      'Porque no permite saltos temporales',
    ],
    correcta: 0,
    explicacion: 'El "tú" puede ser el lector, un desdoblamiento del propio narrador o un destinatario interno. "Aura", de Carlos Fuentes, es de los pocos casos célebres que lo sostienen en toda una obra.',
  },
  {
    id: 'lit-059', tema: 'narrador', dificultad: 4,
    enunciado: 'En un relato de narrador poco fiable, ¿cómo advierte el autor al lector sin decírselo?',
    opciones: [
      'Sembrando contradicciones, silencios y detalles que no encajan con la versión que se ofrece',
      'Cambiando de tiempo verbal en cada capítulo',
      'Nombrando al narrador desde la primera página',
      'Anunciándolo en el prólogo',
    ],
    correcta: 0,
    explicacion: 'La desconfianza debe construirse dentro del texto: un dato que se contradice, una reacción desproporcionada, una laguna sospechosa. Si el autor lo explicita, el efecto se pierde.',
  },
  {
    id: 'lit-060', tema: 'narrador', dificultad: 4,
    enunciado: '¿Qué diferencia hay entre el tiempo de la historia y el tiempo del relato?',
    opciones: [
      'El de la historia es el orden real de los hechos; el del relato, el orden y la duración con que se cuentan',
      'Son sinónimos en el análisis narrativo',
      'El del relato es siempre más corto',
      'El de la historia solo existe en novelas realistas',
    ],
    correcta: 0,
    explicacion: 'Una novela puede despachar veinte años en una línea y dedicar cincuenta páginas a una tarde. Esa desproporción deliberada es una de las herramientas más potentes del narrador.',
  },

  // ----- Literatura universal -----
  {
    id: 'lit-061', tema: 'universal', dificultad: 1,
    enunciado: '¿Quién es el autor al que se atribuyen la Ilíada y la Odisea?',
    opciones: ['Homero', 'Virgilio', 'Sófocles', 'Herodoto'],
    correcta: 0,
    explicacion: 'Virgilio escribió la Eneida, ya en Roma; Sófocles fue dramaturgo y Herodoto, historiador.',
  },
  {
    id: 'lit-062', tema: 'universal', dificultad: 1,
    enunciado: '¿Quién escribió "Romeo y Julieta" y "Hamlet"?',
    opciones: ['William Shakespeare', 'Christopher Marlowe', 'Charles Dickens', 'Molière'],
    correcta: 0,
    explicacion: 'Shakespeare es el dramaturgo central del teatro isabelino inglés. Molière es su equivalente francés en la comedia, un siglo después.',
  },
  {
    id: 'lit-063', tema: 'universal', dificultad: 1,
    enunciado: '¿A qué movimiento pertenece una obra que exalta el sentimiento, la libertad individual y la naturaleza frente a la razón?',
    opciones: ['Romanticismo', 'Neoclasicismo', 'Realismo', 'Renacimiento'],
    correcta: 0,
    explicacion: 'El Romanticismo surge a finales del siglo XVIII como reacción contra el racionalismo ilustrado y las reglas neoclásicas.',
  },
  {
    id: 'lit-064', tema: 'universal', dificultad: 2,
    enunciado: '¿Qué caracteriza a la tragedia griega clásica?',
    opciones: [
      'Un héroe de alta condición cae por un error o un destino ineludible, ante un coro que comenta',
      'Los personajes son campesinos y el final es feliz',
      'No hay intervención divina',
      'Se escribía en prosa y se leía en privado',
    ],
    correcta: 0,
    explicacion: 'Edipo rey, de Sófocles, es el modelo: el protagonista busca la verdad y esa búsqueda lo destruye. El coro funciona como voz de la comunidad.',
  },
  {
    id: 'lit-065', tema: 'universal', dificultad: 2,
    enunciado: '¿Qué distingue al Realismo del siglo XIX?',
    opciones: [
      'La observación detallada de la sociedad y de los conflictos de la vida corriente',
      'La exaltación de lo sobrenatural',
      'El rechazo de la novela como forma',
      'La ambientación exclusiva en la Antigüedad',
    ],
    correcta: 0,
    explicacion: 'Balzac, Flaubert, Tolstói y Galdós documentan su época casi como sociólogos. El Naturalismo de Zola lleva ese programa al extremo, con el determinismo como método.',
  },
  {
    id: 'lit-066', tema: 'universal', dificultad: 2,
    enunciado: '¿Quién escribió "La metamorfosis", donde un hombre despierta convertido en insecto?',
    opciones: ['Franz Kafka', 'Thomas Mann', 'Albert Camus', 'Hermann Hesse'],
    correcta: 0,
    explicacion: 'El relato inaugura una forma de lo absurdo que se volvió adjetivo: lo kafkiano nombra la lógica implacable de una situación inexplicable.',
  },
  {
    id: 'lit-067', tema: 'universal', dificultad: 2,
    enunciado: 'Las vanguardias de comienzos del siglo XX (surrealismo, futurismo, dadaísmo) comparten:',
    opciones: [
      'La ruptura con la tradición y la búsqueda de formas radicalmente nuevas',
      'La vuelta a las reglas clásicas',
      'El rechazo de la poesía como género',
      'La defensa del realismo documental',
    ],
    correcta: 0,
    explicacion: 'Nacen en un mundo sacudido por la guerra y la industrialización. Cada una elige un frente: el inconsciente, la velocidad, el azar, la destrucción del sentido.',
  },
  {
    id: 'lit-068', tema: 'universal', dificultad: 2,
    enunciado: '¿Qué obra narra el viaje del caballero que confunde molinos con gigantes?',
    opciones: ['Don Quijote de la Mancha', 'La Divina Comedia', 'Los miserables', 'Robinson Crusoe'],
    correcta: 0,
    explicacion: 'La novela de Cervantes (1605 y 1615) suele considerarse la primera novela moderna por su juego con la ficción y la profundidad de sus personajes.',
  },
  {
    id: 'lit-069', tema: 'universal', dificultad: 3,
    enunciado: '¿Por qué "La Divina Comedia" de Dante se considera una obra bisagra?',
    opciones: [
      'Porque recoge el pensamiento medieval pero escribe en lengua vulgar y da un peso inédito al yo del poeta',
      'Porque fue la primera obra impresa de Europa',
      'Porque rechaza la religión de su tiempo',
      'Porque está escrita en prosa',
    ],
    correcta: 0,
    explicacion: 'Escribirla en toscano y no en latín fue una decisión decisiva: contribuyó a fundar el italiano literario y abrió el camino a las lenguas modernas.',
  },
  {
    id: 'lit-070', tema: 'universal', dificultad: 3,
    enunciado: '¿Qué plantea una novela distópica como "1984" o "Un mundo feliz"?',
    opciones: [
      'Una sociedad futura organizada de forma opresiva, que funciona como crítica del presente del autor',
      'Un mundo ideal y perfecto',
      'Una reconstrucción histórica rigurosa',
      'Una historia sin conflicto social',
    ],
    correcta: 0,
    explicacion: 'La distopía es utopía invertida: proyecta hacia adelante tendencias que el autor ya observa. Orwell escribe sobre el totalitarismo que conoció, no sobre el año 1984.',
  },
  {
    id: 'lit-071', tema: 'universal', dificultad: 3,
    enunciado: '¿Qué caracteriza al teatro del absurdo (Beckett, Ionesco)?',
    opciones: [
      'Situaciones sin lógica aparente y diálogos que fracasan, para mostrar la falta de sentido',
      'Tramas históricas muy documentadas',
      'Finales felices y personajes heroicos',
      'La estricta unidad de tiempo, lugar y acción',
    ],
    correcta: 0,
    explicacion: 'En "Esperando a Godot" no pasa nada, dos veces. La forma misma encarna el argumento: si el mundo carece de sentido, la obra tampoco debe ofrecerlo.',
  },
  {
    id: 'lit-072', tema: 'universal', dificultad: 3,
    enunciado: 'El Renacimiento literario se caracteriza por:',
    opciones: [
      'La recuperación de los modelos clásicos y una visión centrada en el ser humano',
      'El rechazo de la Antigüedad grecolatina',
      'La preeminencia absoluta de la literatura religiosa',
      'El abandono del verso',
    ],
    correcta: 0,
    explicacion: 'El humanismo pone al hombre en el centro sin romper con lo religioso. Petrarca, Garcilaso y Shakespeare beben de ese redescubrimiento de lo clásico.',
  },
  {
    id: 'lit-073', tema: 'universal', dificultad: 4,
    enunciado: '¿Por qué se dice que Dostoievski anticipa la novela psicológica del siglo XX?',
    opciones: [
      'Porque traslada el conflicto al interior de la conciencia y deja que voces contradictorias convivan sin que el autor las resuelva',
      'Porque escribió en primera persona todas sus obras',
      'Porque evitó los temas sociales',
      'Porque inventó el monólogo interior',
    ],
    correcta: 0,
    explicacion: 'Bajtín llamó "polifonía" a ese rasgo: los personajes no ilustran la tesis del autor, discuten con ella. El crimen de Raskólnikov importa menos que lo que ocurre dentro de su cabeza.',
  },
  {
    id: 'lit-074', tema: 'universal', dificultad: 4,
    enunciado: '¿Qué implica que una obra sea considerada "canónica"?',
    opciones: [
      'Que las instituciones culturales la han consagrado como referencia, decisión que puede discutirse y cambia con el tiempo',
      'Que fue escrita antes del siglo XIX',
      'Que vendió más ejemplares que las demás',
      'Que su calidad literaria es un hecho objetivo e indiscutible',
    ],
    correcta: 0,
    explicacion: 'El canon lo forman la academia, la crítica, la escuela y las editoriales. Por eso ha sido objeto de disputa: qué autoras, qué lenguas y qué regiones quedaron fuera y por qué.',
  },
  {
    id: 'lit-075', tema: 'universal', dificultad: 4,
    enunciado: '¿Qué relación hay entre la novela moderna y el ascenso de la burguesía?',
    opciones: [
      'La novela se consolida con un público lector urbano que se reconoce en personajes individuales y conflictos privados',
      'La novela nació en las cortes aristocráticas medievales',
      'No hay ninguna relación documentada',
      'La novela desapareció con la burguesía',
    ],
    correcta: 0,
    explicacion: 'La imprenta, la alfabetización y el tiempo de ocio crearon lectores; la novela les ofreció lo que la epopeya no daba: vidas privadas, dinero, matrimonio, ambición y fracaso.',
  },

  // ----- Literatura española -----
  {
    id: 'lit-076', tema: 'espanola', dificultad: 1,
    enunciado: '¿Quién escribió "Don Quijote de la Mancha"?',
    opciones: ['Miguel de Cervantes', 'Lope de Vega', 'Francisco de Quevedo', 'Luis de Góngora'],
    correcta: 0,
    explicacion: 'Cervantes publicó la primera parte en 1605 y la segunda en 1615, tras aparecer una continuación apócrifa firmada por Avellaneda.',
  },
  {
    id: 'lit-077', tema: 'espanola', dificultad: 1,
    enunciado: '¿Cómo se llama el periodo de esplendor de las letras españolas de los siglos XVI y XVII?',
    opciones: ['Siglo de Oro', 'Generación del 98', 'Ilustración', 'Modernismo'],
    correcta: 0,
    explicacion: 'Abarca en realidad casi dos siglos e incluye a Cervantes, Lope, Góngora, Quevedo, Calderón, Santa Teresa y san Juan de la Cruz.',
  },
  {
    id: 'lit-078', tema: 'espanola', dificultad: 1,
    enunciado: '¿Quién escribió el "Romancero gitano" y "La casa de Bernarda Alba"?',
    opciones: ['Federico García Lorca', 'Antonio Machado', 'Rafael Alberti', 'Miguel Hernández'],
    correcta: 0,
    explicacion: 'Lorca cultivó con igual fuerza la poesía y el teatro. Fue asesinado en 1936, al comienzo de la Guerra Civil.',
  },
  {
    id: 'lit-079', tema: 'espanola', dificultad: 2,
    enunciado: '¿Qué es el "Lazarillo de Tormes" y por qué es importante?',
    opciones: [
      'La primera novela picaresca: un antihéroe de origen humilde narra su vida y critica a la sociedad',
      'Un libro de caballerías',
      'Una obra de teatro del Siglo de Oro',
      'Un tratado religioso',
    ],
    correcta: 0,
    explicacion: 'Publicada anónimamente en 1554, invierte el modelo heroico: el protagonista sobrevive con astucia, no con virtud, y su ascenso social es una miseria disfrazada.',
  },
  {
    id: 'lit-080', tema: 'espanola', dificultad: 2,
    enunciado: 'El culteranismo de Góngora y el conceptismo de Quevedo se diferencian en que:',
    opciones: [
      'El primero complica la forma y el lenguaje; el segundo, la agudeza de la idea',
      'El primero es en prosa y el segundo en verso',
      'El conceptismo rechaza las figuras retóricas',
      'Son dos nombres para el mismo estilo',
    ],
    correcta: 0,
    explicacion: 'Góngora acumula cultismos, hipérbatos y alusiones mitológicas; Quevedo condensa juegos conceptuales en fórmulas breves. Los dos son barrocos y se detestaron cordialmente.',
  },
  {
    id: 'lit-081', tema: 'espanola', dificultad: 2,
    enunciado: '¿Qué preocupación une a los autores de la Generación del 98?',
    opciones: [
      'La reflexión sobre la identidad y la decadencia de España tras la pérdida de las últimas colonias',
      'La defensa del Romanticismo',
      'La renovación del teatro musical',
      'El rechazo de la novela y el ensayo',
    ],
    correcta: 0,
    explicacion: 'Unamuno, Baroja, Azorín, Machado y Valle-Inclán escriben tras el desastre de 1898. El paisaje castellano y la pregunta por "el problema de España" atraviesan sus obras.',
  },
  {
    id: 'lit-082', tema: 'espanola', dificultad: 2,
    enunciado: '¿Qué caracterizó a la Generación del 27?',
    opciones: [
      'Unió la tradición clásica española con las vanguardias europeas',
      'Rechazó toda la poesía anterior a ellos',
      'Se dedicó exclusivamente al teatro',
      'Escribió solo en prosa realista',
    ],
    correcta: 0,
    explicacion: 'El nombre viene del homenaje a Góngora en 1927. Lorca, Alberti, Cernuda, Salinas, Guillén y Aleixandre combinan el soneto con el surrealismo sin ver contradicción.',
  },
  {
    id: 'lit-083', tema: 'espanola', dificultad: 2,
    enunciado: '¿Quién escribió "Campos de Castilla"?',
    opciones: ['Antonio Machado', 'Juan Ramón Jiménez', 'Luis Cernuda', 'Vicente Aleixandre'],
    correcta: 0,
    explicacion: 'Machado es la voz más reconocible de la Generación del 98 en poesía. Juan Ramón Jiménez, autor de "Platero y yo", recibió el Nobel en 1956.',
  },
  {
    id: 'lit-084', tema: 'espanola', dificultad: 3,
    enunciado: '¿Por qué se considera que el Quijote inaugura la novela moderna?',
    opciones: [
      'Porque sus personajes cambian a lo largo de la obra y el texto reflexiona sobre su propia condición de ficción',
      'Porque fue la primera obra escrita en castellano',
      'Porque es la novela más extensa de su época',
      'Porque abandona por completo el humor',
    ],
    correcta: 0,
    explicacion: 'En la segunda parte, los personajes han leído la primera. Ese juego de espejos, sumado a la evolución de don Quijote y Sancho, es lo que la aparta del relato episódico anterior.',
  },
  {
    id: 'lit-085', tema: 'espanola', dificultad: 3,
    enunciado: 'En "La casa de Bernarda Alba", el encierro de las hijas funciona sobre todo como:',
    opciones: [
      'Símbolo de la represión social y moral que pesa sobre las mujeres',
      'Un recurso para reducir el número de escenarios',
      'Una alusión a la cárcel política',
      'Un detalle costumbrista sin más alcance',
    ],
    correcta: 0,
    explicacion: 'Lorca subtituló la obra "drama de mujeres en los pueblos de España". Las paredes blancas, el luto de ocho años y el bastón de Bernarda son la forma visible de una autoridad asfixiante.',
  },
  {
    id: 'lit-086', tema: 'espanola', dificultad: 3,
    enunciado: '¿Qué aportó Lope de Vega al teatro español?',
    opciones: [
      'Fijó la comedia nueva: tres actos, mezcla de lo trágico y lo cómico y ruptura de las unidades clásicas',
      'Impuso la estricta unidad de tiempo, lugar y acción',
      'Sustituyó el verso por la prosa',
      'Prohibió los personajes populares en escena',
    ],
    correcta: 0,
    explicacion: 'Lo explicó él mismo en "Arte nuevo de hacer comedias": escribía para un público, no para los preceptistas. El honor, el rey y el villano son sus ejes temáticos.',
  },
  {
    id: 'lit-087', tema: 'espanola', dificultad: 3,
    enunciado: '¿Qué tienen en común "La Regenta" de Clarín y "Fortunata y Jacinta" de Galdós?',
    opciones: [
      'Son grandes novelas realistas que retratan la sociedad española del XIX a través de un conflicto íntimo',
      'Son obras de teatro en verso',
      'Pertenecen a la literatura de vanguardia',
      'Están ambientadas en la Edad Media',
    ],
    correcta: 0,
    explicacion: 'En las dos, la ciudad —Vetusta y Madrid— funciona casi como un personaje, y el destino individual sirve para diagnosticar una sociedad entera.',
  },
  {
    id: 'lit-088', tema: 'espanola', dificultad: 4,
    enunciado: '¿Qué es el esperpento de Valle-Inclán?',
    opciones: [
      'Una deformación sistemática de la realidad, como en un espejo cóncavo, para mostrar lo grotesco de España',
      'Un tipo de soneto satírico',
      'Una corriente del teatro realista',
      'Un subgénero de la novela histórica',
    ],
    correcta: 0,
    explicacion: 'Lo formula en "Luces de bohemia": el sentido trágico de la vida española solo puede darse con una estética deliberadamente deformada. No es caricatura gratuita, es método.',
  },
  {
    id: 'lit-089', tema: 'espanola', dificultad: 4,
    enunciado: '¿Por qué la poesía mística de san Juan de la Cruz usa el lenguaje del amor humano?',
    opciones: [
      'Porque la experiencia mística es inefable y solo puede sugerirse con la imagen más intensa disponible',
      'Porque el autor rechazaba la religión',
      'Porque era la moda literaria del momento y carecía de intención religiosa',
      'Porque estaba prohibido escribir sobre temas espirituales',
    ],
    correcta: 0,
    explicacion: 'La noche, la amada y el encuentro son símbolos de la unión del alma con Dios. Lo que no se puede decir se rodea con imágenes, y de ahí la fuerza poética de esos textos.',
  },
  {
    id: 'lit-090', tema: 'espanola', dificultad: 4,
    enunciado: '¿Qué efecto tuvo la Guerra Civil y el exilio en la literatura española del siglo XX?',
    opciones: [
      'Partió en dos el panorama: una literatura del interior sometida a censura y otra escrita fuera por los exiliados',
      'No tuvo ningún efecto apreciable en la producción literaria',
      'Provocó el abandono definitivo de la poesía',
      'Unificó los estilos de todos los autores',
    ],
    correcta: 0,
    explicacion: 'Cernuda, Alberti, Salinas y tantos otros escribieron desde México, Argentina o Estados Unidos. Dentro, la censura franquista obligó al símbolo y al silencio, y varias obras solo pudieron publicarse décadas después.',
  },
  // ----- Literatura latinoamericana -----
  {
    id: 'lit-091', tema: 'latinoamericana', dificultad: 1,
    enunciado: '¿Quién es el máximo representante del Modernismo hispanoamericano?',
    opciones: ['Rubén Darío', 'Pablo Neruda', 'Octavio Paz', 'Jorge Luis Borges'],
    correcta: 0,
    explicacion: 'El nicaragüense Rubén Darío publicó "Azul" en 1888, obra que suele tomarse como punto de partida del movimiento.',
  },
  {
    id: 'lit-092', tema: 'latinoamericana', dificultad: 1,
    enunciado: '¿Qué poeta chileno escribió "Veinte poemas de amor y una canción desesperada"?',
    opciones: ['Pablo Neruda', 'Nicanor Parra', 'Vicente Huidobro', 'Gonzalo Rojas'],
    correcta: 0,
    explicacion: 'Neruda lo publicó en 1924, con apenas veinte años. Recibió el Premio Nobel de Literatura en 1971.',
  },
  {
    id: 'lit-093', tema: 'latinoamericana', dificultad: 1,
    enunciado: '¿Quién fue la primera persona latinoamericana en recibir el Premio Nobel de Literatura?',
    opciones: ['Gabriela Mistral', 'Pablo Neruda', 'Miguel Ángel Asturias', 'Octavio Paz'],
    correcta: 0,
    explicacion: 'La chilena Gabriela Mistral lo recibió en 1945. Después vinieron Asturias (1967), Neruda (1971), García Márquez (1982), Paz (1990) y Vargas Llosa (2010).',
  },
  {
    id: 'lit-094', tema: 'latinoamericana', dificultad: 2,
    enunciado: '¿Qué fue el "boom" latinoamericano?',
    opciones: [
      'El auge editorial e internacional de la novela latinoamericana en los años sesenta',
      'Un movimiento poético de vanguardia de los años veinte',
      'Una corriente del teatro popular',
      'Un grupo de críticos literarios españoles',
    ],
    correcta: 0,
    explicacion: 'Cortázar, García Márquez, Vargas Llosa y Fuentes fueron sus figuras centrales. No fue una escuela con programa común: fue un fenómeno de lectura y de mercado que coincidió con obras excepcionales.',
  },
  {
    id: 'lit-095', tema: 'latinoamericana', dificultad: 2,
    enunciado: '¿Quién escribió "Pedro Páramo", novela en la que los muertos hablan en Comala?',
    opciones: ['Juan Rulfo', 'Carlos Fuentes', 'Juan José Arreola', 'Mariano Azuela'],
    correcta: 0,
    explicacion: 'El mexicano Juan Rulfo la publicó en 1955. Con "El llano en llamas" forma una obra brevísima y decisiva: García Márquez reconoció su influencia directa.',
  },
  {
    id: 'lit-096', tema: 'latinoamericana', dificultad: 2,
    enunciado: '¿Qué caracteriza la obra de Jorge Luis Borges?',
    opciones: [
      'Relatos breves construidos como enigmas intelectuales: laberintos, bibliotecas, espejos e infinitos',
      'Novelas extensas de denuncia social',
      'Poesía romántica de tema amoroso',
      'Teatro histórico argentino',
    ],
    correcta: 0,
    explicacion: 'Nunca escribió una novela. "Ficciones" y "El Aleph" reúnen cuentos que discuten filosofía con forma de relato policial o fantástico.',
  },
  {
    id: 'lit-097', tema: 'latinoamericana', dificultad: 2,
    enunciado: '¿Quién escribió "Rayuela", novela que propone al lector varios órdenes de lectura?',
    opciones: ['Julio Cortázar', 'Ernesto Sabato', 'Adolfo Bioy Casares', 'Juan Carlos Onetti'],
    correcta: 0,
    explicacion: 'Cortázar publicó "Rayuela" en 1963 con un "tablero de dirección" que permite leer los capítulos salteados. El lector deja de ser pasivo, que era justamente su propósito.',
  },
  {
    id: 'lit-098', tema: 'latinoamericana', dificultad: 2,
    enunciado: '¿Qué poeta peruano escribió "Los heraldos negros" y "Trilce"?',
    opciones: ['César Vallejo', 'José María Arguedas', 'Mario Vargas Llosa', 'Ciro Alegría'],
    correcta: 0,
    explicacion: 'Vallejo llevó el español a un punto de ruptura: inventa palabras, quiebra la sintaxis y escribe el dolor de una forma que no se parece a nada anterior.',
  },
  {
    id: 'lit-099', tema: 'latinoamericana', dificultad: 3,
    enunciado: '¿Qué distingue al realismo mágico de la literatura fantástica?',
    opciones: [
      'En el realismo mágico lo extraordinario se narra como algo natural y nadie se asombra',
      'El realismo mágico no incluye hechos sobrenaturales',
      'La literatura fantástica ocurre siempre en el pasado',
      'Son exactamente lo mismo',
    ],
    correcta: 0,
    explicacion: 'En un cuento fantástico lo insólito rompe el orden y provoca inquietud. En Macondo, una lluvia de cuatro años se cuenta con el mismo tono que una cosecha: el asombro se traslada al lector.',
  },
  {
    id: 'lit-100', tema: 'latinoamericana', dificultad: 3,
    enunciado: '¿Qué relación tiene la literatura latinoamericana del siglo XX con la identidad continental?',
    opciones: [
      'Buscó un lenguaje propio para nombrar una realidad que los moldes europeos no alcanzaban a describir',
      'Se limitó a imitar los modelos franceses',
      'Rechazó toda referencia local',
      'Se escribió mayoritariamente en lenguas indígenas',
    ],
    correcta: 0,
    explicacion: 'Carpentier hablaba de "lo real maravilloso" americano. La pregunta por cómo contar este continente atraviesa desde "La vorágine" hasta Arguedas y García Márquez.',
  },
  {
    id: 'lit-101', tema: 'latinoamericana', dificultad: 3,
    enunciado: '¿Qué aportó el Modernismo a la lengua poética en español?',
    opciones: [
      'Renovó el ritmo, el léxico y la musicalidad, y abrió la poesía a la sensibilidad cosmopolita',
      'Volvió a las formas medievales',
      'Rechazó la métrica y la rima',
      'Se limitó a temas políticos',
    ],
    correcta: 0,
    explicacion: 'Fue el primer movimiento nacido en América que influyó de vuelta en España. Cisnes, princesas y versos de largo aliento escandalizaron y luego se volvieron canon.',
  },
  {
    id: 'lit-102', tema: 'latinoamericana', dificultad: 3,
    enunciado: 'La novela indigenista de autores como José María Arguedas se propone:',
    opciones: [
      'Representar desde dentro el mundo andino y su lengua, más allá del retrato pintoresco',
      'Idealizar el pasado precolombino sin referirse al presente',
      'Escribir exclusivamente en quechua',
      'Defender el orden colonial',
    ],
    correcta: 0,
    explicacion: 'Arguedas, criado entre el quechua y el español, buscó una escritura capaz de sostener las dos visiones del mundo a la vez. Es su diferencia con el indigenismo anterior, más externo y compasivo.',
  },
  {
    id: 'lit-103', tema: 'latinoamericana', dificultad: 4,
    enunciado: '¿Por qué se critica a veces la etiqueta "realismo mágico" aplicada a toda la literatura latinoamericana?',
    opciones: [
      'Porque reduce una producción muy diversa a una fórmula exótica que el mercado internacional espera',
      'Porque García Márquez nunca la usó',
      'Porque solo se aplica a la poesía',
      'Porque describe con precisión a todos los autores del continente',
    ],
    correcta: 0,
    explicacion: 'Autores posteriores, como los reunidos en torno al manifiesto McOndo, rechazaron explícitamente la expectativa de escribir pueblos mágicos. Una etiqueta que primero abrió puertas terminó funcionando como corsé.',
  },
  {
    id: 'lit-104', tema: 'latinoamericana', dificultad: 4,
    enunciado: 'En "El Aleph", Borges describe un punto que contiene todos los puntos del universo. ¿Qué problema literario plantea esa imagen?',
    opciones: [
      'La imposibilidad de que un lenguaje sucesivo represente lo simultáneo e infinito',
      'La dificultad de traducir del inglés al español',
      'La censura de la época',
      'La falta de vocabulario técnico en español',
    ],
    correcta: 0,
    explicacion: 'El propio narrador lo confiesa: lo que vio fue simultáneo y lo que escribe es sucesivo. La enumeración vertiginosa no resuelve el problema, lo exhibe.',
  },
  {
    id: 'lit-105', tema: 'latinoamericana', dificultad: 4,
    enunciado: '¿Qué tienen en común "Pedro Páramo" y "Cien años de soledad" en su tratamiento del tiempo?',
    opciones: [
      'Abandonan la cronología lineal: el tiempo se repite, se superpone o parece circular',
      'Narran los hechos en estricto orden cronológico',
      'Abarcan un solo día',
      'Sitúan la acción en el futuro',
    ],
    correcta: 0,
    explicacion: 'En Comala las voces de distintas épocas se cruzan sin aviso; en Macondo los nombres se repiten y con ellos los destinos. En los dos casos la forma del tiempo es parte del significado.',
    pista: 'Pregúntate qué pasaría si reordenaras los episodios en orden cronológico: ¿qué se perdería?',
  },

  // ----- Literatura colombiana -----
  {
    id: 'lit-106', tema: 'colombiana', dificultad: 1,
    enunciado: '¿Quién escribió "María", la gran novela romántica colombiana?',
    opciones: ['Jorge Isaacs', 'Tomás Carrasquilla', 'José Eustasio Rivera', 'José Asunción Silva'],
    correcta: 0,
    explicacion: 'Publicada en 1867 y ambientada en el valle del Cauca, es la novela romántica más leída del siglo XIX hispanoamericano.',
  },
  {
    id: 'lit-107', tema: 'colombiana', dificultad: 1,
    enunciado: '¿En qué año recibió Gabriel García Márquez el Premio Nobel de Literatura?',
    opciones: ['1982', '1967', '1975', '1990'],
    correcta: 0,
    explicacion: '1967 es el año de publicación de "Cien años de soledad"; el Nobel llegó quince años después.',
  },
  {
    id: 'lit-108', tema: 'colombiana', dificultad: 1,
    enunciado: '¿Cómo se llama el pueblo imaginario donde transcurre "Cien años de soledad"?',
    opciones: ['Macondo', 'Comala', 'Santa María', 'Vetusta'],
    correcta: 0,
    explicacion: 'Comala es de Rulfo, Santa María de Onetti y Vetusta de Clarín. Los cuatro son lugares inventados que funcionan como mundo completo.',
  },
  {
    id: 'lit-109', tema: 'colombiana', dificultad: 2,
    enunciado: '¿Qué denuncia "La vorágine" de José Eustasio Rivera?',
    opciones: [
      'La explotación de los caucheros en la selva amazónica',
      'La corrupción de la administración colonial',
      'El conflicto entre liberales y conservadores en Bogotá',
      'Las condiciones de las minas de oro del Chocó',
    ],
    correcta: 0,
    explicacion: 'Publicada en 1924, combina la novela de la selva con el reportaje de denuncia. Su cierre —"¡Se los tragó la selva!"— es una de las frases más citadas de la literatura colombiana.',
  },
  {
    id: 'lit-110', tema: 'colombiana', dificultad: 2,
    enunciado: '¿Quién es el autor de "El olvido que seremos", sobre el asesinato de su padre en Medellín?',
    opciones: ['Héctor Abad Faciolince', 'Fernando Vallejo', 'Juan Gabriel Vásquez', 'Laura Restrepo'],
    correcta: 0,
    explicacion: 'El libro, de 2006, es un homenaje al médico Héctor Abad Gómez y a la vez un retrato de la violencia de los años ochenta.',
  },
  {
    id: 'lit-111', tema: 'colombiana', dificultad: 2,
    enunciado: '¿Qué poeta colombiano del siglo XIX escribió el "Nocturno" ("Una noche, / una noche toda llena de murmullos…")?',
    opciones: ['José Asunción Silva', 'Rafael Pombo', 'Guillermo Valencia', 'Julio Flórez'],
    correcta: 0,
    explicacion: 'Silva es una figura de transición hacia el Modernismo. El "Nocturno" destaca por su ritmo innovador, construido sobre una unidad métrica que se repite y se expande.',
  },
  {
    id: 'lit-112', tema: 'colombiana', dificultad: 2,
    enunciado: '¿Qué autor antioqueño es el principal representante del costumbrismo colombiano?',
    opciones: ['Tomás Carrasquilla', 'Jorge Isaacs', 'Eduardo Caballero Calderón', 'Manuel Mejía Vallejo'],
    correcta: 0,
    explicacion: 'Carrasquilla llevó a la literatura el habla y la vida de los pueblos antioqueños, con obras como "La marquesa de Yolombó" y "Frutos de mi tierra".',
  },
  {
    id: 'lit-113', tema: 'colombiana', dificultad: 2,
    enunciado: '¿Quién creó al personaje de Maqroll el Gaviero?',
    opciones: ['Álvaro Mutis', 'Gabriel García Márquez', 'Germán Espinosa', 'Andrés Caicedo'],
    correcta: 0,
    explicacion: 'Mutis lo hizo protagonista de una saga de novelas y poemas. Recibió el Premio Cervantes en 2001 y fue amigo cercano de García Márquez durante décadas.',
  },
  {
    id: 'lit-114', tema: 'colombiana', dificultad: 3,
    enunciado: '¿Qué rasgo de "Cien años de soledad" refleja la historia real de Colombia?',
    opciones: [
      'La masacre de los trabajadores bananeros, inspirada en los hechos de 1928',
      'La independencia de Panamá en 1903',
      'La fundación de Bogotá en 1538',
      'El plebiscito de 1957',
    ],
    correcta: 0,
    explicacion: 'En la novela, el único sobreviviente insiste en que hubo muertos y nadie le cree: el olvido oficial es parte del episodio. La ficción retiene lo que el registro histórico dejó sin cifras.',
  },
  {
    id: 'lit-115', tema: 'colombiana', dificultad: 3,
    enunciado: '¿Qué caracteriza a la llamada literatura del conflicto o de la violencia en Colombia?',
    opciones: [
      'Aborda las causas y los efectos de la violencia desde la experiencia de las víctimas y la memoria',
      'Se limita a narrar batallas militares',
      'Evita cualquier referencia política',
      'Solo se escribió durante La Violencia de los años cincuenta',
    ],
    correcta: 0,
    explicacion: 'Va de "El Cristo de espaldas" de Caballero Calderón a Evelio Rosero, Laura Restrepo o Juan Gabriel Vásquez. El eje no es el hecho bélico sino lo que deja en las personas y en el lenguaje.',
  },
  {
    id: 'lit-116', tema: 'colombiana', dificultad: 3,
    enunciado: 'Candelario Obeso es reconocido por:',
    opciones: [
      'Llevar a la poesía escrita el habla y la experiencia de las comunidades negras del Caribe colombiano',
      'Fundar el Modernismo colombiano',
      'Escribir la primera novela de la selva',
      'Traducir a los clásicos griegos',
    ],
    correcta: 0,
    explicacion: 'Sus "Cantos populares de mi tierra" (1877) incorporan la fonética del habla bogana. Durante mucho tiempo se leyó como curiosidad costumbrista, y hoy se lee como un gesto político y literario deliberado.',
  },
  {
    id: 'lit-117', tema: 'colombiana', dificultad: 3,
    enunciado: '¿Qué narra "La virgen de los sicarios", de Fernando Vallejo?',
    opciones: [
      'El regreso de un hombre a Medellín en la época del sicariato, con un tono de diatriba permanente',
      'La vida de un cauchero en la Amazonía',
      'La historia de una familia durante cien años',
      'El asesinato de un candidato presidencial',
    ],
    correcta: 0,
    explicacion: 'Publicada en 1994, es un relato en primera persona que mezcla la crónica urbana con el insulto y la elegía. Su voz beligerante es inseparable de lo que cuenta.',
  },
  {
    id: 'lit-118', tema: 'colombiana', dificultad: 4,
    enunciado: '¿Por qué se dice que "Cien años de soledad" es a la vez una novela familiar y una alegoría de América Latina?',
    opciones: [
      'Porque la historia de los Buendía reproduce los ciclos de fundación, guerra civil, intervención extranjera y olvido del continente',
      'Porque menciona a todos los países latinoamericanos',
      'Porque fue escrita en varios países',
      'Porque su protagonista es un político',
    ],
    correcta: 0,
    explicacion: 'Las guerras del coronel Aureliano, la llegada de la compañía bananera y la peste del insomnio funcionan en dos registros a la vez. La saga familiar es el vehículo, no el tema.',
  },
  {
    id: 'lit-119', tema: 'colombiana', dificultad: 4,
    enunciado: '¿Qué aporta el periodismo a la obra narrativa de García Márquez?',
    opciones: [
      'La precisión del detalle concreto, que hace creíble lo inverosímil',
      'La tendencia a explicar las causas de cada hecho',
      'El rechazo del diálogo en la narración',
      'La estructura de pirámide invertida en sus novelas',
    ],
    correcta: 0,
    explicacion: 'Él mismo lo explicó: si dices que volaban elefantes nadie te cree, pero si dices que volaban cuatrocientos veinticinco elefantes, probablemente sí. El dato exacto sostiene lo increíble.',
  },
  {
    id: 'lit-120', tema: 'colombiana', dificultad: 4,
    enunciado: '¿Qué problema plantea que la literatura colombiana se identifique casi exclusivamente con García Márquez?',
    opciones: [
      'Deja en la sombra tradiciones muy distintas: la poesía, el Caribe negro, lo urbano, lo indígena y las autoras',
      'No plantea ningún problema, porque él resume toda la tradición',
      'Impide traducir otras obras',
      'Obliga a leer solo novelas extensas',
    ],
    correcta: 0,
    explicacion: 'Silva, Mutis, Obeso, Carrasquilla, Andrés Caicedo o Marvel Moreno responden a proyectos muy distintos. Un canon con un solo nombre empobrece la lectura de todo lo demás.',
  },

  // ----- Análisis del texto literario -----
  {
    id: 'lit-121', tema: 'analisis', dificultad: 1,
    enunciado: '¿Qué es el tema de una obra literaria?',
    opciones: [
      'La idea central que la recorre, formulada de manera abstracta',
      'El resumen de lo que ocurre',
      'El lugar donde transcurre la acción',
      'El número de personajes',
    ],
    correcta: 0,
    explicacion: 'El argumento cuenta qué pasa; el tema dice de qué trata en el fondo. "Romeo y Julieta" tiene por argumento un amor entre dos familias enfrentadas y por tema el conflicto entre deseo y orden social.',
  },
  {
    id: 'lit-122', tema: 'analisis', dificultad: 1,
    enunciado: '¿Qué es un símbolo en literatura?',
    opciones: [
      'Un elemento concreto que remite a una idea más amplia',
      'Una palabra difícil',
      'El nombre del protagonista',
      'Una figura de repetición sonora',
    ],
    correcta: 0,
    explicacion: 'La paloma remite a la paz, y un camino a la vida. El símbolo literario suele ser más personal: adquiere su sentido dentro de la obra que lo usa.',
  },
  {
    id: 'lit-123', tema: 'analisis', dificultad: 1,
    enunciado: '¿Qué es el conflicto en un relato?',
    opciones: [
      'La oposición de fuerzas que pone en marcha la historia',
      'El desenlace de la obra',
      'La descripción del ambiente',
      'El número de capítulos',
    ],
    correcta: 0,
    explicacion: 'Puede ser con otro personaje, con el entorno, con una norma social o con uno mismo. Sin oposición no hay historia, solo sucesión de hechos.',
  },
  {
    id: 'lit-124', tema: 'analisis', dificultad: 2,
    enunciado: '¿Qué diferencia hay entre un personaje plano y uno redondo?',
    opciones: [
      'El plano se define por uno o dos rasgos fijos; el redondo es complejo y puede cambiar',
      'El plano aparece poco y el redondo, mucho',
      'El redondo siempre es el protagonista',
      'El plano no tiene nombre',
    ],
    correcta: 0,
    explicacion: 'La distinción es de E. M. Forster. Un personaje plano no es un defecto: cumple su función, y una obra llena de personajes redondos sería ilegible.',
  },
  {
    id: 'lit-125', tema: 'analisis', dificultad: 2,
    enunciado: 'En el análisis literario, el "ambiente" o atmósfera se refiere a:',
    opciones: [
      'El clima emocional que el texto crea mediante el espacio, el tono y los detalles',
      'La lista de lugares donde ocurre la acción',
      'La época en que vivió el autor',
      'El número de descripciones del texto',
    ],
    correcta: 0,
    explicacion: 'El espacio físico es un ingrediente, pero la atmósfera es el efecto: una casa vacía puede resultar apacible u opresiva según cómo se narre.',
  },
  {
    id: 'lit-126', tema: 'analisis', dificultad: 2,
    enunciado: '¿Qué es un motivo literario?',
    opciones: [
      'Un elemento que se repite a lo largo de la obra y va cargándose de sentido',
      'La razón por la que el autor escribió el libro',
      'El primer capítulo de una novela',
      'La moraleja final',
    ],
    correcta: 0,
    explicacion: 'El viaje, el espejo, la lluvia o una frase que vuelve. La repetición es lo que lo distingue de un detalle cualquiera.',
  },
  {
    id: 'lit-127', tema: 'analisis', dificultad: 2,
    enunciado: '¿Cuál es la estructura narrativa tradicional de un relato?',
    opciones: [
      'Planteamiento, nudo y desenlace',
      'Introducción, desarrollo y bibliografía',
      'Prólogo, epílogo y notas',
      'Tesis, argumentos y conclusión',
    ],
    correcta: 0,
    explicacion: 'Muchas obras la alteran empezando por el final o dejando el desenlace abierto, pero el esquema sigue sirviendo como referencia para notar esas alteraciones.',
  },
  {
    id: 'lit-128', tema: 'analisis', dificultad: 2,
    enunciado: '¿Qué significa que una obra tenga final abierto?',
    opciones: [
      'Que no resuelve del todo el conflicto y deja la interpretación al lector',
      'Que el autor no alcanzó a terminarla',
      'Que tiene varios volúmenes',
      'Que carece de conflicto',
    ],
    correcta: 0,
    explicacion: 'Es una decisión de forma, no un descuido. Obliga al lector a hacerse cargo de lo que falta, y suele producir una lectura más duradera.',
  },
  {
    id: 'lit-129', tema: 'analisis', dificultad: 3,
    enunciado: 'Un relato dedica tres páginas a describir una habitación vacía antes de que entre el personaje. ¿Qué es lo más probable que busque?',
    opciones: [
      'Crear una atmósfera y una expectativa que condicionen cómo leeremos lo que ocurra allí',
      'Rellenar espacio porque no hay más que contar',
      'Demostrar el vocabulario del autor',
      'Evitar el uso de diálogos',
    ],
    correcta: 0,
    explicacion: 'La duración que un texto concede a algo es un juicio de importancia. Si el narrador se detiene, está pidiendo que nos detengamos.',
  },
  {
    id: 'lit-130', tema: 'analisis', dificultad: 3,
    enunciado: '¿Por qué el título de una obra forma parte del análisis?',
    opciones: [
      'Porque orienta la lectura desde antes de empezar y a veces cambia de sentido al terminar',
      'Porque siempre resume el argumento',
      'Porque lo elige la editorial y revela el mercado al que apunta',
      'Porque indica el género con precisión',
    ],
    correcta: 0,
    explicacion: '"Cien años de soledad" anuncia una duración y una condición, y solo al final se entiende por qué esa soledad era irremediable. El título es la primera clave interpretativa que el autor entrega.',
  },
  {
    id: 'lit-131', tema: 'analisis', dificultad: 3,
    enunciado: '¿Qué implica analizar la relación entre forma y contenido?',
    opciones: [
      'Mostrar cómo la manera de narrar o versificar produce parte del significado',
      'Separar el estilo del tema para estudiarlos por aparte',
      'Contar cuántas figuras retóricas hay',
      'Comparar la obra con la biografía del autor',
    ],
    correcta: 0,
    explicacion: 'Si una novela sobre la incomunicación está escrita con frases entrecortadas, la forma no adorna el tema: lo ejecuta. Señalar esa coincidencia es el núcleo del análisis.',
  },
  {
    id: 'lit-132', tema: 'analisis', dificultad: 3,
    enunciado: '¿Qué distingue una interpretación sostenible de una arbitraria?',
    opciones: [
      'Que pueda apoyarse en elementos concretos del texto y explique el mayor número de ellos',
      'Que sea original y no la haya dicho nadie',
      'Que coincida con lo que el autor declaró en entrevistas',
      'Que sea la más sencilla posible',
    ],
    correcta: 0,
    explicacion: 'Un texto admite varias lecturas, pero no cualquiera. La prueba es siempre la misma: mostrar dónde dice el texto lo que se afirma.',
  },
  {
    id: 'lit-133', tema: 'analisis', dificultad: 4,
    enunciado: '¿Qué problema plantea interpretar una obra apelando solo a la intención del autor?',
    opciones: [
      'Que el texto puede significar más o distinto de lo que su autor se propuso, y esa intención no siempre es accesible ni decisiva',
      'Que los autores nunca explican sus obras',
      'Que la intención del autor es siempre falsa',
      'Que impide usar el contexto histórico',
    ],
    correcta: 0,
    explicacion: 'La crítica llamó a esto "falacia intencional". Saber qué quiso hacer un autor es interesante, pero la obra funciona con lo que efectivamente hizo.',
  },
  {
    id: 'lit-134', tema: 'analisis', dificultad: 4,
    enunciado: 'Una novela cuenta un episodio de violencia con lenguaje sereno y frases breves. ¿Cómo se lee ese contraste?',
    opciones: [
      'La contención del estilo puede aumentar el impacto y sugerir el entumecimiento de quien narra',
      'Indica que el autor no domina el tema',
      'Obliga a interpretar la escena como irónica',
      'Demuestra que la escena no es importante',
    ],
    correcta: 0,
    explicacion: 'Bajar el volumen cuando el contenido lo sube obliga al lector a poner la emoción. Es el efecto contrario al del énfasis, y a menudo más eficaz.',
  },
  {
    id: 'lit-135', tema: 'analisis', dificultad: 4,
    enunciado: 'Si en un poema el ritmo se quiebra justo en el verso que habla de una ruptura, ¿qué conviene concluir?',
    opciones: [
      'Que la forma está realizando el contenido, y el análisis debe señalar esa correspondencia',
      'Que el poeta cometió un error de métrica',
      'Que el poema está mal transcrito',
      'Que la métrica no tiene relación con el sentido',
    ],
    correcta: 0,
    explicacion: 'Conviene comprobar antes que el resto del poema sí es regular: solo sobre un patrón establecido una ruptura significa algo. Si nada es regular, no hay quiebre que interpretar.',
    pista: 'Una irregularidad solo es significativa si hay una regla que romper.',
  },

  // ----- Literatura y contexto -----
  {
    id: 'lit-136', tema: 'contexto', dificultad: 1,
    enunciado: '¿Qué es el contexto histórico de una obra?',
    opciones: [
      'Las circunstancias sociales, políticas y culturales en que fue escrita',
      'El lugar donde ocurre la trama',
      'La biografía completa del autor',
      'La lista de obras anteriores del mismo género',
    ],
    correcta: 0,
    explicacion: 'Conocerlo ayuda a entender a qué responde un texto, aunque no agote lo que el texto significa.',
  },
  {
    id: 'lit-137', tema: 'contexto', dificultad: 1,
    enunciado: '¿Qué es la intertextualidad?',
    opciones: [
      'La relación de un texto con otros que cita, imita o transforma',
      'La traducción de un texto a otra lengua',
      'La división de un libro en capítulos',
      'El diálogo entre personajes',
    ],
    correcta: 0,
    explicacion: 'Una obra nunca nace de la nada: responde, parodia o continúa a otras. El Quijote es intertextual de principio a fin, porque vive de los libros de caballerías que se burla.',
  },
  {
    id: 'lit-138', tema: 'contexto', dificultad: 1,
    enunciado: '¿Qué es el canon literario?',
    opciones: [
      'El conjunto de obras que una cultura consagra como fundamentales',
      'Las obras más vendidas de cada año',
      'La lista de premios literarios existentes',
      'El reglamento de las editoriales',
    ],
    correcta: 0,
    explicacion: 'Se forma por decisiones de la escuela, la crítica y las instituciones, y cambia con el tiempo: autores olvidados se recuperan y otros caen.',
  },
  {
    id: 'lit-139', tema: 'contexto', dificultad: 2,
    enunciado: '¿Por qué importa saber que "La vorágine" se publicó en 1924?',
    opciones: [
      'Porque la denuncia de las caucherías remite a hechos contemporáneos del autor y a un debate político en curso',
      'Porque en esa época no existía la novela en Colombia',
      'Porque determina el género de la obra',
      'Porque explica su extensión',
    ],
    correcta: 0,
    explicacion: 'Rivera conoció la región como miembro de una comisión de límites. La novela funciona como testimonio y como acusación, y eso solo se ve con la fecha delante.',
  },
  {
    id: 'lit-140', tema: 'contexto', dificultad: 2,
    enunciado: '¿Qué efecto tiene la censura sobre la literatura de un país?',
    opciones: [
      'Empuja a escribir con símbolos, alegorías y sobreentendidos, y deja obras sin publicar durante años',
      'Mejora la calidad literaria al exigir más esfuerzo',
      'No afecta la producción, solo la distribución',
      'Elimina por completo la literatura crítica',
    ],
    correcta: 0,
    explicacion: 'La escritura indirecta es una respuesta documentada, pero no conviene idealizarla: la censura también silencia, exilia y destruye obras que nunca llegaron a existir.',
  },
  {
    id: 'lit-141', tema: 'contexto', dificultad: 2,
    enunciado: '¿Qué significa que una obra sea "de su tiempo" y a la vez perdure?',
    opciones: [
      'Que responde a preocupaciones concretas de su época pero plantea problemas que siguen vigentes',
      'Que fue escrita hace mucho tiempo',
      'Que no menciona hechos históricos',
      'Que se reedita cada año',
    ],
    correcta: 0,
    explicacion: 'Antígona discute un caso muy concreto de la Grecia clásica y sigue leyéndose porque el conflicto entre la ley y la conciencia no caducó.',
  },
  {
    id: 'lit-142', tema: 'contexto', dificultad: 2,
    enunciado: 'La recepción de una obra se refiere a:',
    opciones: [
      'Cómo la leyeron y valoraron los lectores y la crítica en distintos momentos',
      'La cantidad de ejemplares impresos',
      'El proceso de edición del manuscrito',
      'La opinión del autor sobre su propio libro',
    ],
    correcta: 0,
    explicacion: 'Muchas obras fracasaron al salir y se volvieron centrales después, como "Moby Dick". La historia de sus lecturas es parte de su historia.',
  },
  {
    id: 'lit-143', tema: 'contexto', dificultad: 3,
    enunciado: '¿Qué aporta leer una obra desde la perspectiva de las autoras silenciadas de su época?',
    opciones: [
      'Permite ver qué voces quedaron fuera del canon y por qué razones no literarias',
      'Demuestra que las obras canónicas carecen de valor',
      'Sustituye el análisis del texto por el del contexto',
      'Solo sirve para obras del siglo XX',
    ],
    correcta: 0,
    explicacion: 'Sor Juana escribió sobre esa exclusión en el siglo XVII. Recuperar lo que no se publicó, no se reeditó o no se estudió cambia el mapa sin necesidad de derribar nada.',
  },
  {
    id: 'lit-144', tema: 'contexto', dificultad: 3,
    enunciado: '¿Qué es una parodia literaria?',
    opciones: [
      'La imitación deliberada de una obra o un género con intención crítica o humorística',
      'La copia no autorizada de un texto',
      'La traducción libre de una obra extranjera',
      'La continuación de una novela por otro autor',
    ],
    correcta: 0,
    explicacion: 'Necesita que el lector reconozca el modelo: sin ese reconocimiento no hay parodia, solo un texto raro. Es la forma extrema de la intertextualidad.',
  },
  {
    id: 'lit-145', tema: 'contexto', dificultad: 3,
    enunciado: '¿Cómo influyó la imprenta en la literatura?',
    opciones: [
      'Multiplicó la circulación de los textos, amplió el público lector y consolidó las lenguas vernáculas',
      'Redujo el número de obras escritas',
      'Impuso el latín como lengua literaria',
      'No tuvo efectos sobre la creación, solo sobre el comercio',
    ],
    correcta: 0,
    explicacion: 'Un texto que puede copiarse mil veces cambia lo que se escribe y para quién. La novela moderna es impensable sin lectores individuales y libros baratos.',
  },
  {
    id: 'lit-146', tema: 'contexto', dificultad: 3,
    enunciado: 'Cuando una obra antigua se adapta al cine con cambios importantes, ¿qué ocurre?',
    opciones: [
      'Se produce una nueva interpretación, que dialoga con el original y con el presente del adaptador',
      'Se traiciona necesariamente la obra',
      'Se reemplaza el original para siempre',
      'Se trata de un plagio',
    ],
    correcta: 0,
    explicacion: 'Cada época reescribe los clásicos según sus preguntas. Comparar la adaptación con el original suele revelar más sobre el presente que sobre el texto adaptado.',
  },
  {
    id: 'lit-147', tema: 'contexto', dificultad: 4,
    enunciado: '¿Por qué el estudio del contexto no debe sustituir la lectura del texto?',
    opciones: [
      'Porque explicar de dónde viene una obra no explica cómo funciona ni por qué sigue importando',
      'Porque el contexto histórico suele ser desconocido',
      'Porque los autores mienten sobre su época',
      'Porque el contexto solo interesa a los historiadores',
    ],
    correcta: 0,
    explicacion: 'Reducir una obra a su contexto la vuelve un documento: útil para conocer una época, prescindible como literatura. El contexto ilumina la lectura; no la reemplaza.',
  },
  {
    id: 'lit-148', tema: 'contexto', dificultad: 4,
    enunciado: '¿Qué tensión plantea leer hoy una obra clásica con valores hoy inaceptables?',
    opciones: [
      'Exige sostener a la vez el juicio crítico y la comprensión histórica, sin borrar la obra ni excusarla',
      'Obliga a retirar la obra de circulación',
      'Impide cualquier lectura seria',
      'Solo afecta a obras del siglo XX',
    ],
    correcta: 0,
    explicacion: 'Ni "era su época, no se le puede juzgar" ni "hay que dejar de leerlo". Las dos salidas evitan el trabajo: entender qué hace el texto, de dónde viene eso y qué se hace hoy con ello.',
  },
  {
    id: 'lit-149', tema: 'contexto', dificultad: 4,
    enunciado: '¿Qué revela que un mismo libro se lea de forma muy distinta en dos países o dos décadas?',
    opciones: [
      'Que el significado no está solo en el texto: se produce en el encuentro con lectores situados',
      'Que una de las dos lecturas es equivocada',
      'Que el libro está mal escrito',
      'Que las traducciones alteraron el contenido',
    ],
    correcta: 0,
    explicacion: 'Es la tesis central de la estética de la recepción. El texto fija unos límites, pero dentro de ellos cada comunidad de lectores encuentra sus propias preguntas.',
  },
  {
    id: 'lit-150', tema: 'contexto', dificultad: 4,
    enunciado: '¿Por qué el premio Nobel de García Márquez tuvo un efecto que excedió su obra personal?',
    opciones: [
      'Consolidó la visibilidad internacional de la literatura latinoamericana y abrió mercados de traducción para otros autores',
      'Hizo que se dejara de leer a los demás autores del continente',
      'Cambió las reglas del premio',
      'Obligó a traducir su obra al inglés por primera vez',
    ],
    correcta: 0,
    explicacion: 'Los premios operan sobre el canon y sobre la industria a la vez. El reconocimiento de 1982 llegó cuando el boom ya había abierto camino, y multiplicó su efecto sobre la circulación de toda una literatura.',
  },
];
