/**
 * matematicas.js — Banco de matemáticas.
 *
 * Cada pregunta: tema del temario, dificultad (1 básico, 2 intermedio,
 * 3 avanzado), cuatro opciones, la correcta y por qué. La explicación importa
 * tanto como la respuesta: sin ella, practicar es solo adivinar.
 *
 * Las opciones se barajan al presentar la pregunta (motor.js), así que el orden
 * en que están escritas aquí no da ninguna pista.
 */

export const MATEMATICAS = [
  // ----- Números y operaciones -----
  {
    id: 'mat-001', tema: 'aritmetica', dificultad: 1,
    enunciado: '¿Cuál es el resultado de 2 + 3 × (8 − 5)² ÷ 9?',
    opciones: ['5', '11', '3', '15'],
    correcta: 0,
    explicacion: 'Primero el paréntesis: 8 − 5 = 3. Luego la potencia: 3² = 9. Después multiplicación y división de izquierda a derecha: 3 × 9 = 27 y 27 ÷ 9 = 3. Al final la suma: 2 + 3 = 5.',
    pista: 'Paréntesis, potencias, multiplicación y división, y por último suma y resta.',
  },
  {
    id: 'mat-002', tema: 'aritmetica', dificultad: 2,
    enunciado: '¿Cuál es el mínimo común múltiplo de 12, 18 y 30?',
    opciones: ['90', '180', '360', '60'],
    correcta: 1,
    explicacion: '12 = 2²·3, 18 = 2·3², 30 = 2·3·5. El mcm toma cada primo con su mayor exponente: 2²·3²·5 = 4·9·5 = 180.',
  },
  {
    id: 'mat-003', tema: 'aritmetica', dificultad: 2,
    enunciado: 'Si a = −3 y b = 4, ¿cuánto vale a² − |a − b| + 2b?',
    opciones: ['10', '16', '9', '2'],
    correcta: 0,
    explicacion: 'a² = 9. a − b = −3 − 4 = −7, y |−7| = 7. 2b = 8. Entonces 9 − 7 + 8 = 10.',
  },
  {
    id: 'mat-004', tema: 'aritmetica', dificultad: 2,
    enunciado: '¿Cuál de estos números es divisible entre 3 y entre 4 a la vez?',
    opciones: ['132', '122', '138', '116'],
    correcta: 0,
    explicacion: 'Un número es divisible entre 3 si la suma de sus cifras lo es, y entre 4 si sus dos últimas cifras forman un múltiplo de 4. En 132: 1 + 3 + 2 = 6 (divisible entre 3) y 32 es múltiplo de 4. En 138 falla el 4, en 116 falla el 3 y en 122 fallan los dos.',
    pista: 'Aplica las dos reglas por separado y descarta.',
  },

  // ----- Fracciones, decimales y notación científica -----
  {
    id: 'mat-005', tema: 'fracciones', dificultad: 1,
    enunciado: 'Calcula 3/4 + 2/5 − 1/2.',
    opciones: ['13/20', '4/7', '23/20', '11/20'],
    correcta: 0,
    explicacion: 'Con denominador común 20: 15/20 + 8/20 − 10/20 = 13/20.',
  },
  {
    id: 'mat-006', tema: 'fracciones', dificultad: 2,
    enunciado: 'Un tanque está lleno hasta 3/5 de su capacidad. Si se consumen 2/3 del agua que contiene, ¿qué fracción del tanque queda con agua?',
    opciones: ['1/5', '2/5', '4/15', '1/3'],
    correcta: 0,
    explicacion: 'Queda 1/3 de lo que había: (1/3)·(3/5) = 3/15 = 1/5 del tanque.',
    pista: '"De" significa multiplicar.',
  },
  {
    id: 'mat-007', tema: 'fracciones', dificultad: 2,
    enunciado: '¿Cuál es el resultado de (3,2 × 10⁵)(2 × 10⁻³)?',
    opciones: ['6,4 × 10²', '6,4 × 10⁸', '6,4 × 10⁻¹⁵', '3,2 × 10²'],
    correcta: 0,
    explicacion: 'Se multiplican los números (3,2 × 2 = 6,4) y se suman los exponentes (5 + (−3) = 2): 6,4 × 10².',
  },
  {
    id: 'mat-008', tema: 'fracciones', dificultad: 2,
    enunciado: 'Ordena de menor a mayor: 0,7 ; 2/3 ; 5/8.',
    opciones: ['5/8 ; 2/3 ; 0,7', '2/3 ; 5/8 ; 0,7', '0,7 ; 2/3 ; 5/8', '5/8 ; 0,7 ; 2/3'],
    correcta: 0,
    explicacion: 'En decimales: 5/8 = 0,625; 2/3 ≈ 0,667; y 0,7. Por lo tanto 5/8 < 2/3 < 0,7.',
  },

  // ----- Razones, proporciones y regla de tres -----
  {
    id: 'mat-009', tema: 'razones', dificultad: 1,
    enunciado: 'Dos números están en razón 3 : 5 y su suma es 64. ¿Cuál es el mayor?',
    opciones: ['40', '24', '35', '45'],
    correcta: 0,
    explicacion: 'Si son 3k y 5k, entonces 8k = 64 y k = 8. El mayor es 5k = 40.',
  },
  {
    id: 'mat-010', tema: 'razones', dificultad: 2,
    enunciado: 'Seis obreros terminan una obra en 12 días. Trabajando al mismo ritmo, ¿en cuántos días la terminarían 9 obreros?',
    opciones: ['8', '18', '9', '6'],
    correcta: 0,
    explicacion: 'Es proporción inversa: a más obreros, menos días. El total de trabajo es 6 × 12 = 72 obreros-día; entre 9 obreros son 72 ÷ 9 = 8 días.',
    pista: 'Si una cantidad sube y la otra baja, multiplica en lugar de dividir.',
  },
  {
    id: 'mat-011', tema: 'razones', dificultad: 2,
    enunciado: 'En un mapa a escala 1 : 50 000, dos ciudades están separadas 4 cm. ¿Cuál es la distancia real?',
    opciones: ['2 km', '20 km', '200 m', '5 km'],
    correcta: 0,
    explicacion: '4 cm × 50 000 = 200 000 cm. Como 100 000 cm = 1 km, son 2 km.',
  },
  {
    id: 'mat-012', tema: 'razones', dificultad: 3,
    enunciado: 'Se reparten $4 500 entre tres personas en partes proporcionales a 2, 3 y 4. ¿Cuánto recibe la segunda?',
    opciones: ['$1 500', '$1 000', '$2 000', '$1 200'],
    correcta: 0,
    explicacion: 'Las partes suman 2 + 3 + 4 = 9, así que cada parte vale 4 500 ÷ 9 = 500. La segunda recibe 3 × 500 = $1 500.',
  },

  // ----- Porcentajes -----
  {
    id: 'mat-013', tema: 'porcentajes', dificultad: 1,
    enunciado: '¿Cuánto es el 15 % de 240?',
    opciones: ['36', '24', '360', '16'],
    correcta: 0,
    explicacion: '240 × 0,15 = 36. Atajo: el 10 % es 24 y el 5 % es 12; 24 + 12 = 36.',
  },
  {
    id: 'mat-014', tema: 'porcentajes', dificultad: 2,
    enunciado: 'Un artículo cuesta $80. Primero sube 25 % y después baja 20 %. ¿Cuál es el precio final?',
    opciones: ['$80', '$84', '$76', '$85'],
    correcta: 0,
    explicacion: '80 × 1,25 = 100 y 100 × 0,80 = 80. Los porcentajes sucesivos se multiplican, no se suman: por eso subir 25 % y bajar 20 % deja el precio igual.',
    pista: 'Aplica el segundo porcentaje al precio nuevo, no al original.',
  },
  {
    id: 'mat-015', tema: 'porcentajes', dificultad: 2,
    enunciado: 'Con un descuento del 18 %, una chaqueta cuesta $246. ¿Cuál era su precio sin descuento?',
    opciones: ['$300', '$290', '$320', '$264'],
    correcta: 0,
    explicacion: 'El precio con descuento es el 82 % del original: 0,82·x = 246, entonces x = 246 ÷ 0,82 = 300.',
  },
  {
    id: 'mat-016', tema: 'porcentajes', dificultad: 3,
    enunciado: 'Se depositan $2 000 al 10 % anual de interés compuesto. ¿Cuánto hay al cabo de 2 años?',
    opciones: ['$2 420', '$2 400', '$2 200', '$2 442'],
    correcta: 0,
    explicacion: '2 000 × 1,10² = 2 000 × 1,21 = 2 420. Con interés simple serían 2 400: la diferencia de $20 es el interés que generaron los intereses del primer año.',
  },

  // ----- Potencias y radicales -----
  {
    id: 'mat-017', tema: 'potencias', dificultad: 1,
    enunciado: 'Simplifica (2³)² · 2⁻⁴.',
    opciones: ['4', '16', '2', '64'],
    correcta: 0,
    explicacion: '(2³)² = 2⁶. Luego 2⁶ · 2⁻⁴ = 2⁶⁻⁴ = 2² = 4.',
  },
  {
    id: 'mat-018', tema: 'potencias', dificultad: 2,
    enunciado: '¿Cuál es la forma simplificada de √72, es decir, con el menor radical posible?',
    opciones: ['6√2', '2√18', '8√2', '36√2'],
    correcta: 0,
    explicacion: '72 = 36 × 2, y √36 = 6, así que √72 = 6√2. La opción 2√18 es igual en valor pero no está simplificada.',
  },
  {
    id: 'mat-019', tema: 'potencias', dificultad: 2,
    enunciado: 'Simplifica (a³b⁻²)² · (a⁻¹b³).',
    opciones: ['a⁵/b', 'a⁵b', 'a⁷b⁻⁷', 'a⁵b⁷'],
    correcta: 0,
    explicacion: '(a³b⁻²)² = a⁶b⁻⁴. Al multiplicar por a⁻¹b³ se suman exponentes: a⁶⁻¹ b⁻⁴⁺³ = a⁵b⁻¹ = a⁵/b.',
  },
  {
    id: 'mat-020', tema: 'potencias', dificultad: 2,
    enunciado: 'Racionaliza el denominador de 6/√3.',
    opciones: ['2√3', '6√3', '√3/2', '3√2'],
    correcta: 0,
    explicacion: 'Se multiplica arriba y abajo por √3: (6√3)/3 = 2√3.',
  },
  {
    id: 'mat-021', tema: 'potencias', dificultad: 3,
    enunciado: '¿Cuál es el valor de 8^(2/3) + 16^(−1/2)?',
    opciones: ['4,25', '4,5', '5', '8,25'],
    correcta: 0,
    explicacion: '8^(2/3) = (∛8)² = 2² = 4. 16^(−1/2) = 1/√16 = 1/4 = 0,25. La suma es 4,25.',
  },

  // ----- Logaritmos -----
  {
    id: 'mat-022', tema: 'logaritmos', dificultad: 1,
    enunciado: '¿Cuánto vale log₂ 32?',
    opciones: ['5', '4', '6', '16'],
    correcta: 0,
    explicacion: 'Se busca el exponente al que hay que elevar 2 para obtener 32. Como 2⁵ = 32, el logaritmo vale 5.',
  },
  {
    id: 'mat-023', tema: 'logaritmos', dificultad: 2,
    enunciado: 'Si log x = 2 log 3 + log 4, ¿cuánto vale x?',
    opciones: ['36', '24', '12', '10'],
    correcta: 0,
    explicacion: '2 log 3 = log 9, y log 9 + log 4 = log 36. Como los logaritmos son iguales, x = 36.',
  },
  {
    id: 'mat-024', tema: 'logaritmos', dificultad: 2,
    enunciado: 'Resuelve 3^(2x−1) = 81.',
    opciones: ['x = 2,5', 'x = 2', 'x = 3', 'x = 4,5'],
    correcta: 0,
    explicacion: '81 = 3⁴, así que 2x − 1 = 4, de donde 2x = 5 y x = 2,5.',
    pista: 'Escribe los dos lados con la misma base.',
  },
  {
    id: 'mat-025', tema: 'logaritmos', dificultad: 3,
    enunciado: 'Si log₅ (x − 1) = 2, ¿cuánto vale x?',
    opciones: ['26', '11', '25', '6'],
    correcta: 0,
    explicacion: 'La definición da x − 1 = 5² = 25, así que x = 26.',
  },

  // ----- Álgebra -----
  {
    id: 'mat-026', tema: 'algebra', dificultad: 1,
    enunciado: 'Desarrolla (2x − 3)².',
    opciones: ['4x² − 12x + 9', '4x² + 9', '4x² − 6x + 9', '2x² − 12x + 9'],
    correcta: 0,
    explicacion: 'Cuadrado de una diferencia: (a − b)² = a² − 2ab + b², con a = 2x y b = 3, da 4x² − 12x + 9.',
  },
  {
    id: 'mat-027', tema: 'algebra', dificultad: 2,
    enunciado: 'Factoriza x² − 5x + 6.',
    opciones: ['(x − 2)(x − 3)', '(x + 2)(x + 3)', '(x − 6)(x + 1)', '(x − 1)(x − 6)'],
    correcta: 0,
    explicacion: 'Se buscan dos números que multiplicados den 6 y sumados den −5: son −2 y −3.',
  },
  {
    id: 'mat-028', tema: 'algebra', dificultad: 2,
    enunciado: 'Simplifica (x² − 9)/(x² + x − 12), con x ≠ 3 y x ≠ −4.',
    opciones: ['(x + 3)/(x + 4)', '(x − 3)/(x − 4)', '9/12', '(x + 3)/(x − 4)'],
    correcta: 0,
    explicacion: 'x² − 9 = (x − 3)(x + 3) y x² + x − 12 = (x + 4)(x − 3). Se cancela (x − 3) y queda (x + 3)/(x + 4).',
  },
  {
    id: 'mat-029', tema: 'algebra', dificultad: 3,
    enunciado: 'Si x + 1/x = 5, ¿cuánto vale x² + 1/x²?',
    opciones: ['23', '25', '27', '24'],
    correcta: 0,
    explicacion: 'Al elevar al cuadrado: (x + 1/x)² = x² + 2 + 1/x² = 25. Restando 2 queda x² + 1/x² = 23.',
  },

  // ----- Ecuaciones y sistemas -----
  {
    id: 'mat-030', tema: 'ecuaciones', dificultad: 1,
    enunciado: 'Resuelve 3(x − 2) = 2x + 5.',
    opciones: ['x = 11', 'x = 1', 'x = −11', 'x = 3'],
    correcta: 0,
    explicacion: '3x − 6 = 2x + 5. Restando 2x: x − 6 = 5, y por lo tanto x = 11.',
  },
  {
    id: 'mat-031', tema: 'ecuaciones', dificultad: 2,
    enunciado: 'Resuelve el sistema: 2x + 3y = 12 ; x − y = 1.',
    opciones: ['x = 3, y = 2', 'x = 2, y = 3', 'x = 4, y = 3', 'x = 1, y = 0'],
    correcta: 0,
    explicacion: 'De la segunda, x = y + 1. Sustituyendo: 2(y + 1) + 3y = 12, es decir 5y = 10, y = 2 y x = 3.',
  },
  {
    id: 'mat-032', tema: 'ecuaciones', dificultad: 2,
    enunciado: 'La suma de dos números es 45 y su diferencia es 11. ¿Cuál es el menor?',
    opciones: ['17', '28', '16', '22'],
    correcta: 0,
    explicacion: 'x + y = 45 y x − y = 11. Sumando las ecuaciones: 2x = 56, x = 28; entonces y = 17.',
  },
  {
    id: 'mat-033', tema: 'ecuaciones', dificultad: 3,
    enunciado: 'Resuelve (x + 2)/3 − (x − 1)/4 = 2.',
    opciones: ['x = 13', 'x = 7', 'x = 11', 'x = 5'],
    correcta: 0,
    explicacion: 'Multiplicando todo por 12: 4(x + 2) − 3(x − 1) = 24, o sea 4x + 8 − 3x + 3 = 24, es decir x + 11 = 24 y x = 13.',
  },

  // ----- Cuadráticas -----
  {
    id: 'mat-034', tema: 'cuadraticas', dificultad: 1,
    enunciado: '¿Cuáles son las soluciones de x² − 7x + 10 = 0?',
    opciones: ['2 y 5', '−2 y −5', '1 y 10', '3 y 4'],
    correcta: 0,
    explicacion: 'Factorizando: (x − 2)(x − 5) = 0, así que x = 2 o x = 5.',
  },
  {
    id: 'mat-035', tema: 'cuadraticas', dificultad: 2,
    enunciado: '¿Para qué valores de k la ecuación x² + kx + 9 = 0 tiene una única raíz real (doble)?',
    opciones: ['k = 6 o k = −6', 'k = 9', 'k = 3 o k = −3', 'k = 0'],
    correcta: 0,
    explicacion: 'Hay raíz doble cuando el discriminante es cero: k² − 4·1·9 = 0, entonces k² = 36 y k = ±6.',
  },
  {
    id: 'mat-036', tema: 'cuadraticas', dificultad: 3,
    enunciado: 'Si r y s son las raíces de 2x² − 8x + 6 = 0, ¿cuánto vale r² + s²?',
    opciones: ['10', '16', '13', '22'],
    correcta: 0,
    explicacion: 'r + s = 8/2 = 4 y r·s = 6/2 = 3. Como r² + s² = (r + s)² − 2rs, queda 16 − 6 = 10.',
    pista: 'No hace falta hallar las raíces: usa suma y producto.',
  },
  {
    id: 'mat-037', tema: 'cuadraticas', dificultad: 2,
    enunciado: 'El área de un rectángulo es 96 m² y su largo mide 4 m más que su ancho. ¿Cuánto mide el ancho?',
    opciones: ['8 m', '12 m', '6 m', '10 m'],
    correcta: 0,
    explicacion: 'x(x + 4) = 96, es decir x² + 4x − 96 = 0, que factoriza como (x + 12)(x − 8) = 0. La solución con sentido físico es x = 8 m.',
  },

  // ----- Desigualdades -----
  {
    id: 'mat-038', tema: 'desigualdades', dificultad: 1,
    enunciado: 'Resuelve 3 − 2x ≤ 9.',
    opciones: ['x ≥ −3', 'x ≤ −3', 'x ≥ 3', 'x ≤ 6'],
    correcta: 0,
    explicacion: 'Restando 3: −2x ≤ 6. Al dividir entre −2 se invierte el sentido: x ≥ −3.',
    pista: 'Dividir entre un número negativo voltea la desigualdad.',
  },
  {
    id: 'mat-039', tema: 'desigualdades', dificultad: 2,
    enunciado: '¿Cuál es el conjunto solución de |2x − 5| < 3?',
    opciones: ['(1, 4)', '(−1, 4)', '(−∞, 1) ∪ (4, ∞)', '[1, 4]'],
    correcta: 0,
    explicacion: '|A| < 3 equivale a −3 < 2x − 5 < 3. Sumando 5: 2 < 2x < 8, y dividiendo entre 2: 1 < x < 4.',
  },
  {
    id: 'mat-040', tema: 'desigualdades', dificultad: 3,
    enunciado: '¿Para qué valores de x se cumple (x − 2)(x + 3) > 0?',
    opciones: ['x < −3 o x > 2', '−3 < x < 2', 'x > 2 solamente', 'x < 2'],
    correcta: 0,
    explicacion: 'El producto es positivo cuando los dos factores tienen el mismo signo: ambos negativos si x < −3, ambos positivos si x > 2.',
  },

  // ----- Funciones -----
  {
    id: 'mat-041', tema: 'funciones', dificultad: 1,
    enunciado: 'Si f(x) = 2x² − 3x + 1, ¿cuánto vale f(−2)?',
    opciones: ['15', '3', '−1', '11'],
    correcta: 0,
    explicacion: 'f(−2) = 2(4) − 3(−2) + 1 = 8 + 6 + 1 = 15. El error típico es olvidar que (−2)² es positivo.',
  },
  {
    id: 'mat-042', tema: 'funciones', dificultad: 2,
    enunciado: '¿Cuál es el dominio de f(x) = √(x − 3)/(x − 5)?',
    opciones: ['x ≥ 3 y x ≠ 5', 'x > 3', 'x ≠ 5', 'x ≥ 3'],
    correcta: 0,
    explicacion: 'La raíz exige x − 3 ≥ 0, o sea x ≥ 3; el denominador exige x ≠ 5. Se cumplen las dos condiciones a la vez.',
  },
  {
    id: 'mat-043', tema: 'funciones', dificultad: 2,
    enunciado: 'Si f(x) = 3x − 2 y g(x) = x² + 1, ¿cuánto vale (f ∘ g)(2)?',
    opciones: ['13', '17', '10', '5'],
    correcta: 0,
    explicacion: 'Primero g(2) = 4 + 1 = 5, después f(5) = 15 − 2 = 13. En f ∘ g se aplica primero g.',
  },
  {
    id: 'mat-044', tema: 'funciones', dificultad: 3,
    enunciado: 'La parábola y = x² − 6x + 5 tiene su vértice en:',
    opciones: ['(3, −4)', '(−3, 32)', '(3, 4)', '(6, 5)'],
    correcta: 0,
    explicacion: 'La abscisa del vértice es x = −b/(2a) = 6/2 = 3. Sustituyendo: y = 9 − 18 + 5 = −4.',
  },

  // ----- Sucesiones -----
  {
    id: 'mat-045', tema: 'sucesiones', dificultad: 1,
    enunciado: 'En la progresión aritmética 5, 9, 13, 17, … ¿cuál es el término número 20?',
    opciones: ['81', '85', '77', '80'],
    correcta: 0,
    explicacion: 'aₙ = a₁ + (n − 1)d = 5 + 19 × 4 = 5 + 76 = 81.',
  },
  {
    id: 'mat-046', tema: 'sucesiones', dificultad: 2,
    enunciado: '¿Cuál es la suma de los 8 primeros términos de la progresión geométrica 3, 6, 12, 24, …?',
    opciones: ['765', '384', '768', '381'],
    correcta: 0,
    explicacion: 'Sₙ = a₁(rⁿ − 1)/(r − 1) = 3(2⁸ − 1)/(2 − 1) = 3 × 255 = 765.',
  },
  {
    id: 'mat-047', tema: 'sucesiones', dificultad: 2,
    enunciado: 'La suma de los primeros 50 números naturales (1 + 2 + … + 50) es:',
    opciones: ['1 275', '2 550', '1 250', '1 225'],
    correcta: 0,
    explicacion: 'n(n + 1)/2 = 50 × 51 / 2 = 1 275.',
  },

  // ----- Geometría plana -----
  {
    id: 'mat-048', tema: 'geometria-plana', dificultad: 1,
    enunciado: 'Un triángulo tiene base 12 cm y altura 7 cm. ¿Cuál es su área?',
    opciones: ['42 cm²', '84 cm²', '19 cm²', '21 cm²'],
    correcta: 0,
    explicacion: 'Área = base × altura / 2 = 12 × 7 / 2 = 42 cm².',
  },
  {
    id: 'mat-049', tema: 'geometria-plana', dificultad: 1,
    enunciado: 'En un triángulo rectángulo, un cateto mide 9 cm y la hipotenusa 15 cm. ¿Cuánto mide el otro cateto?',
    opciones: ['12 cm', '6 cm', '√306 cm', '18 cm'],
    correcta: 0,
    explicacion: 'Por Pitágoras: c² = 15² − 9² = 225 − 81 = 144, así que c = 12 cm.',
  },
  {
    id: 'mat-050', tema: 'geometria-plana', dificultad: 2,
    enunciado: 'Los ángulos de un triángulo están en razón 2 : 3 : 4. ¿Cuánto mide el mayor?',
    opciones: ['80°', '90°', '75°', '100°'],
    correcta: 0,
    explicacion: '2k + 3k + 4k = 180°, es decir 9k = 180° y k = 20°. El mayor es 4k = 80°.',
  },
  {
    id: 'mat-051', tema: 'geometria-plana', dificultad: 2,
    enunciado: 'Un círculo tiene radio 6 cm. ¿Cuál es el área de un sector de 60°?',
    opciones: ['6π cm²', '12π cm²', '36π cm²', '3π cm²'],
    correcta: 0,
    explicacion: 'El área total es 36π cm². Un sector de 60° es 60/360 = 1/6 del círculo: 36π/6 = 6π cm².',
  },
  {
    id: 'mat-052', tema: 'geometria-plana', dificultad: 3,
    enunciado: 'Si a cada lado de un cuadrado se le aumenta un 20 %, ¿en qué porcentaje aumenta su área?',
    opciones: ['44 %', '40 %', '20 %', '24 %'],
    correcta: 0,
    explicacion: 'El área se multiplica por 1,2² = 1,44, es decir crece un 44 %. El área no crece en la misma proporción que el lado.',
  },

  // ----- Cuerpos -----
  {
    id: 'mat-053', tema: 'geometria-espacio', dificultad: 1,
    enunciado: 'Un cilindro tiene radio 3 cm y altura 10 cm. ¿Cuál es su volumen?',
    opciones: ['90π cm³', '30π cm³', '60π cm³', '180π cm³'],
    correcta: 0,
    explicacion: 'V = πr²h = π × 9 × 10 = 90π cm³ (unos 282,7 cm³).',
  },
  {
    id: 'mat-054', tema: 'geometria-espacio', dificultad: 2,
    enunciado: '¿Cuál es el volumen de una esfera de radio 3 cm?',
    opciones: ['36π cm³', '27π cm³', '12π cm³', '108π cm³'],
    correcta: 0,
    explicacion: 'V = (4/3)πr³ = (4/3)π × 27 = 36π cm³.',
  },
  {
    id: 'mat-055', tema: 'geometria-espacio', dificultad: 3,
    enunciado: 'Si el radio de una esfera se duplica, su volumen se multiplica por:',
    opciones: ['8', '2', '4', '6'],
    correcta: 0,
    explicacion: 'El volumen depende del cubo del radio, así que al duplicar el radio el volumen se multiplica por 2³ = 8.',
  },

  // ----- Geometría analítica -----
  {
    id: 'mat-056', tema: 'geometria-analitica', dificultad: 1,
    enunciado: '¿Cuál es la pendiente de la recta que pasa por (2, −1) y (6, 7)?',
    opciones: ['2', '1/2', '−2', '4'],
    correcta: 0,
    explicacion: 'm = (y₂ − y₁)/(x₂ − x₁) = (7 − (−1))/(6 − 2) = 8/4 = 2.',
  },
  {
    id: 'mat-057', tema: 'geometria-analitica', dificultad: 2,
    enunciado: '¿Cuál es la distancia entre los puntos (−1, 2) y (3, 5)?',
    opciones: ['5', '7', '√7', '25'],
    correcta: 0,
    explicacion: 'd = √((3 + 1)² + (5 − 2)²) = √(16 + 9) = √25 = 5.',
  },
  {
    id: 'mat-058', tema: 'geometria-analitica', dificultad: 3,
    enunciado: '¿Cuál es la ecuación de la recta perpendicular a y = −(2/3)x + 4 que pasa por el punto (2, 1)?',
    opciones: ['y = (3/2)x − 2', 'y = −(3/2)x + 4', 'y = (2/3)x − 1/3', 'y = (3/2)x + 2'],
    correcta: 0,
    explicacion: 'La pendiente perpendicular es el recíproco con signo cambiado: 3/2. Con el punto (2, 1): 1 = (3/2)(2) + b, de donde b = −2.',
  },
  {
    id: 'mat-059', tema: 'geometria-analitica', dificultad: 2,
    enunciado: 'La circunferencia (x − 3)² + (y + 2)² = 16 tiene centro y radio:',
    opciones: ['Centro (3, −2), radio 4', 'Centro (−3, 2), radio 4', 'Centro (3, −2), radio 16', 'Centro (−3, 2), radio 16'],
    correcta: 0,
    explicacion: 'En (x − h)² + (y − k)² = r², el centro es (h, k) = (3, −2) y el radio es √16 = 4.',
  },

  // ----- Estadística -----
  {
    id: 'mat-060', tema: 'estadistica', dificultad: 1,
    enunciado: 'Para los datos 4, 7, 9, 10, 10, ¿cuáles son la media y la mediana?',
    opciones: ['Media 8, mediana 9', 'Media 9, mediana 8', 'Media 8, mediana 10', 'Media 10, mediana 9'],
    correcta: 0,
    explicacion: 'La media es (4 + 7 + 9 + 10 + 10)/5 = 40/5 = 8. Con cinco datos ordenados, la mediana es el tercero: 9.',
  },
  {
    id: 'mat-061', tema: 'estadistica', dificultad: 2,
    enunciado: 'La media de cinco números es 12. Si se quita uno, la media de los cuatro restantes es 13. ¿Qué número se quitó?',
    opciones: ['8', '10', '12', '7'],
    correcta: 0,
    explicacion: 'La suma inicial es 5 × 12 = 60 y la final 4 × 13 = 52. El número retirado es 60 − 52 = 8.',
  },
  {
    id: 'mat-062', tema: 'estadistica', dificultad: 2,
    enunciado: 'Un estudiante tiene 70 en un examen que vale 40 % y 85 en otro que vale 60 %. ¿Cuál es su nota final?',
    opciones: ['79', '77,5', '80', '78'],
    correcta: 0,
    explicacion: 'Media ponderada: 70 × 0,4 + 85 × 0,6 = 28 + 51 = 79.',
  },

  // ----- Probabilidad -----
  {
    id: 'mat-063', tema: 'probabilidad', dificultad: 1,
    enunciado: 'Se lanzan dos dados. ¿Cuál es la probabilidad de que la suma sea 7?',
    opciones: ['1/6', '1/12', '7/36', '1/9'],
    correcta: 0,
    explicacion: 'Hay 36 resultados posibles y 6 dan suma 7: (1,6), (2,5), (3,4), (4,3), (5,2) y (6,1). Entonces 6/36 = 1/6.',
  },
  {
    id: 'mat-064', tema: 'probabilidad', dificultad: 2,
    enunciado: 'Una urna tiene 4 bolas rojas y 6 azules. Se sacan dos sin reponer. ¿Cuál es la probabilidad de que ambas sean rojas?',
    opciones: ['2/15', '4/25', '1/5', '3/20'],
    correcta: 0,
    explicacion: '(4/10) × (3/9) = 12/90 = 2/15. Al no reponer, la segunda probabilidad cambia.',
  },
  {
    id: 'mat-065', tema: 'probabilidad', dificultad: 2,
    enunciado: '¿De cuántas maneras se puede formar un comité de 3 personas a partir de un grupo de 8?',
    opciones: ['56', '336', '24', '112'],
    correcta: 0,
    explicacion: 'El orden no importa, así que es una combinación: C(8,3) = 8·7·6/(3·2·1) = 56.',
    pista: 'Si el orden importara, serían 336 (permutaciones).',
  },
  {
    id: 'mat-066', tema: 'probabilidad', dificultad: 3,
    enunciado: 'La probabilidad de que un estudiante apruebe matemáticas es 0,8 y la de que apruebe inglés es 0,7, de forma independiente. ¿Cuál es la probabilidad de que apruebe al menos una?',
    opciones: ['0,94', '0,56', '0,75', '0,50'],
    correcta: 0,
    explicacion: 'Es más fácil por el complemento: que falle las dos es 0,2 × 0,3 = 0,06. Entonces al menos una es 1 − 0,06 = 0,94.',
  },

  // ----- Problemas de aplicación -----
  {
    id: 'mat-067', tema: 'problemas', dificultad: 2,
    enunciado: '¿Cuántos litros de solución al 60 % hay que añadir a 20 L de solución al 30 % para obtener una mezcla al 40 %?',
    opciones: ['10 L', '20 L', '15 L', '5 L'],
    correcta: 0,
    explicacion: '(0,30 × 20 + 0,60x)/(20 + x) = 0,40. Entonces 6 + 0,6x = 8 + 0,4x, es decir 0,2x = 2 y x = 10 L.',
  },
  {
    id: 'mat-068', tema: 'problemas', dificultad: 2,
    enunciado: 'Dos autos salen al mismo tiempo de ciudades separadas 300 km y viajan uno hacia el otro a 60 km/h y 90 km/h. ¿En cuánto tiempo se encuentran?',
    opciones: ['2 h', '2,5 h', '3 h', '1,5 h'],
    correcta: 0,
    explicacion: 'Se acercan a 60 + 90 = 150 km/h. El tiempo es 300 ÷ 150 = 2 h.',
  },
  {
    id: 'mat-069', tema: 'problemas', dificultad: 2,
    enunciado: 'Ana pinta una pared en 6 horas y Beto en 3 horas. Trabajando juntos, ¿cuánto tardan?',
    opciones: ['2 h', '4,5 h', '3 h', '1,5 h'],
    correcta: 0,
    explicacion: 'En una hora hacen 1/6 + 1/3 = 1/2 de la pared, así que la terminan en 2 horas.',
    pista: 'Suma trabajos por hora, no tiempos.',
  },
  {
    id: 'mat-070', tema: 'problemas', dificultad: 2,
    enunciado: 'Ana tiene el doble de la edad de Beto. Dentro de 6 años, la suma de sus edades será 42. ¿Cuántos años tiene Ana?',
    opciones: ['20', '18', '24', '22'],
    correcta: 0,
    explicacion: 'Si Beto tiene b, Ana tiene 2b. Dentro de 6 años: (2b + 6) + (b + 6) = 42, es decir 3b = 30 y b = 10. Ana tiene 20.',
  },

  // ----- Complemento hasta la meta de 10 por tema -----
  {
    id: 'mat-071', tema: 'aritmetica', dificultad: 1,
    enunciado: 'Calcula 15 − 3 × (2 + 4) ÷ 2.',
    opciones: ['6', '21', '36', '12'],
    correcta: 0,
    explicacion: 'Primero el paréntesis: 2 + 4 = 6. Luego 3 × 6 = 18 y 18 ÷ 2 = 9. Por último 15 − 9 = 6.',
  },
  {
    id: 'mat-072', tema: 'aritmetica', dificultad: 2,
    enunciado: '¿Cuál es el máximo común divisor de 48 y 180?',
    opciones: ['12', '6', '24', '36'],
    correcta: 0,
    explicacion: '48 = 2⁴·3 y 180 = 2²·3²·5. El mcd toma los primos comunes con el menor exponente: 2²·3 = 12.',
  },
  {
    id: 'mat-073', tema: 'aritmetica', dificultad: 2,
    enunciado: 'Calcula −5 − (−8) + (−3).',
    opciones: ['0', '−16', '−10', '6'],
    correcta: 0,
    explicacion: 'Restar un negativo es sumar: −5 + 8 = 3, y 3 + (−3) = 0.',
  },
  {
    id: 'mat-074', tema: 'aritmetica', dificultad: 2,
    enunciado: '¿Cuál de estos números es múltiplo de 6?',
    opciones: ['114', '115', '116', '117'],
    correcta: 0,
    explicacion: 'Un múltiplo de 6 debe ser par y divisible entre 3. 114 es par y 1+1+4 = 6, múltiplo de 3. El 116 es par pero no divisible entre 3, y el 117 sí es divisible entre 3 pero es impar.',
  },
  {
    id: 'mat-075', tema: 'aritmetica', dificultad: 1,
    enunciado: 'Calcula 2³ + 3² − √16.',
    opciones: ['13', '21', '9', '17'],
    correcta: 0,
    explicacion: 'Se resuelven primero las potencias y la raíz: 2³ = 8, 3² = 9 y √16 = 4. Después 8 + 9 − 4 = 13.',
  },
  {
    id: 'mat-076', tema: 'aritmetica', dificultad: 3,
    enunciado: 'Al dividir un número entre 7 se obtiene cociente 8 y residuo 3. ¿Cuál es el número?',
    opciones: ['59', '56', '38', '24'],
    correcta: 0,
    explicacion: 'Dividendo = divisor × cociente + residuo = 7 × 8 + 3 = 59. El residuo siempre es menor que el divisor.',
  },
  {
    id: 'mat-077', tema: 'fracciones', dificultad: 2,
    enunciado: 'Calcula (2/3) ÷ (4/9).',
    opciones: ['3/2', '8/27', '2/3', '6/4'],
    correcta: 0,
    explicacion: 'Dividir es multiplicar por el recíproco: (2/3) × (9/4) = 18/12 = 3/2.',
  },
  {
    id: 'mat-078', tema: 'fracciones', dificultad: 1,
    enunciado: '¿Cuál es la fracción irreducible equivalente a 0,25?',
    opciones: ['1/4', '25/10', '1/25', '2/5'],
    correcta: 0,
    explicacion: '0,25 = 25/100, y al simplificar entre 25 queda 1/4.',
  },
  {
    id: 'mat-079', tema: 'fracciones', dificultad: 2,
    enunciado: 'De un tanque con 60 litros se usan 2/5 del contenido. ¿Cuántos litros quedan?',
    opciones: ['36', '24', '30', '40'],
    correcta: 0,
    explicacion: 'Se usan 24 litros (2/5 de 60), así que quedan 36. También se puede calcular directamente los 3/5 que sobran.',
  },
  {
    id: 'mat-080', tema: 'fracciones', dificultad: 3,
    enunciado: 'Ordena de menor a mayor: 3/7, 2/5 y 5/11.',
    opciones: ['2/5 ; 3/7 ; 5/11', '3/7 ; 2/5 ; 5/11', '5/11 ; 3/7 ; 2/5', '2/5 ; 5/11 ; 3/7'],
    correcta: 0,
    explicacion: 'En decimales: 2/5 = 0,400; 3/7 ≈ 0,429; 5/11 ≈ 0,455. Convertir a decimal es más rápido que buscar denominador común cuando solo hay que ordenar.',
  },
  {
    id: 'mat-081', tema: 'fracciones', dificultad: 2,
    enunciado: 'Escribe 5,2 × 10⁻⁴ en notación decimal.',
    opciones: ['0,00052', '0,0052', '52 000', '0,000052'],
    correcta: 0,
    explicacion: 'El exponente −4 mueve la coma cuatro lugares a la izquierda: 0,00052.',
  },
  {
    id: 'mat-082', tema: 'fracciones', dificultad: 3,
    enunciado: 'Calcula (1/2 + 1/3) ÷ (5/6).',
    opciones: ['1', '5/6', '6/5', '25/36'],
    correcta: 0,
    explicacion: '1/2 + 1/3 = 5/6, y (5/6) ÷ (5/6) = 1.',
  },
  {
    id: 'mat-083', tema: 'razones', dificultad: 2,
    enunciado: 'Dos cantidades están en razón 4 : 7 y la menor vale 24. ¿Cuánto vale la mayor?',
    opciones: ['42', '28', '48', '35'],
    correcta: 0,
    explicacion: 'Si 4k = 24, entonces k = 6 y la mayor es 7k = 42.',
  },
  {
    id: 'mat-084', tema: 'razones', dificultad: 2,
    enunciado: 'Cinco máquinas iguales producen un lote en 8 horas. ¿Cuánto tardarían 4 máquinas?',
    opciones: ['10 horas', '6,4 horas', '9 horas', '12 horas'],
    correcta: 0,
    explicacion: 'Es proporción inversa: el trabajo total es 5 × 8 = 40 máquinas-hora, y 40 ÷ 4 = 10 horas.',
  },
  {
    id: 'mat-085', tema: 'razones', dificultad: 1,
    enunciado: 'Si 3 kg de un producto cuestan $12 000, ¿cuánto cuestan 7 kg?',
    opciones: ['$28 000', '$24 000', '$21 000', '$36 000'],
    correcta: 0,
    explicacion: 'Regla de tres directa: el kilo vale 4 000, así que 7 kg cuestan 28 000.',
  },
  {
    id: 'mat-086', tema: 'razones', dificultad: 2,
    enunciado: 'Se prepara una mezcla de 40 litros con agua y concentrado en razón 2 : 3. ¿Cuántos litros de concentrado lleva?',
    opciones: ['24', '16', '20', '15'],
    correcta: 0,
    explicacion: 'Las partes suman 5, así que cada parte son 8 litros. El concentrado son 3 partes: 24 litros.',
  },
  {
    id: 'mat-087', tema: 'razones', dificultad: 2,
    enunciado: 'En un plano a escala 1 : 200, ¿con qué longitud se dibuja una pieza que mide 6 m en la realidad?',
    opciones: ['3 cm', '30 cm', '12 cm', '1,2 m'],
    correcta: 0,
    explicacion: '6 m son 600 cm, y 600 ÷ 200 = 3 cm.',
  },
  {
    id: 'mat-088', tema: 'razones', dificultad: 2,
    enunciado: 'Resuelve la proporción 5/x = 15/12.',
    opciones: ['x = 4', 'x = 3', 'x = 6', 'x = 36'],
    correcta: 0,
    explicacion: 'Multiplicando en cruz: 15x = 60, así que x = 4.',
  },
  {
    id: 'mat-089', tema: 'porcentajes', dificultad: 1,
    enunciado: '¿Qué porcentaje de 180 es 45?',
    opciones: ['25 %', '40 %', '4 %', '35 %'],
    correcta: 0,
    explicacion: '45 ÷ 180 = 0,25, es decir el 25 %.',
  },
  {
    id: 'mat-090', tema: 'porcentajes', dificultad: 2,
    enunciado: 'Un valor pasa de 200 a 250. ¿Cuál fue el aumento porcentual?',
    opciones: ['25 %', '20 %', '50 %', '5 %'],
    correcta: 0,
    explicacion: 'El aumento es 50 sobre el valor inicial: 50 ÷ 200 = 0,25, es decir 25 %. El porcentaje siempre se calcula sobre el valor de partida.',
  },
  {
    id: 'mat-091', tema: 'porcentajes', dificultad: 3,
    enunciado: 'Un valor pasa de 250 a 200. ¿Cuál fue la disminución porcentual?',
    opciones: ['20 %', '25 %', '50 %', '80 %'],
    correcta: 0,
    explicacion: '50 ÷ 250 = 0,20, es decir 20 %. Subir de 200 a 250 es un 25 % y bajar de 250 a 200 es un 20 %: la base cambia y por eso los porcentajes no coinciden.',
    pista: 'Divide siempre entre el valor inicial, no entre el final.',
  },
  {
    id: 'mat-092', tema: 'porcentajes', dificultad: 2,
    enunciado: 'El 40 % de un número es 32. ¿Cuál es el número?',
    opciones: ['80', '12,8', '72', '128'],
    correcta: 0,
    explicacion: '0,40 · x = 32, de donde x = 32 ÷ 0,40 = 80.',
  },
  {
    id: 'mat-093', tema: 'porcentajes', dificultad: 2,
    enunciado: 'Un producto cuesta $238 con un impuesto del 19 % incluido. ¿Cuál es el precio sin impuesto?',
    opciones: ['$200', '$219', '$192,78', '$180'],
    correcta: 0,
    explicacion: 'Se divide entre 1,19: 238 ÷ 1,19 = 200. Restar el 19 % de 238 daría 192,78, que es el error más frecuente.',
  },
  {
    id: 'mat-094', tema: 'porcentajes', dificultad: 3,
    enunciado: 'Un precio recibe un descuento del 25 % y después otro 25 % sobre el resultado. ¿Cuál es el descuento total?',
    opciones: ['43,75 %', '50 %', '56,25 %', '25 %'],
    correcta: 0,
    explicacion: '0,75 × 0,75 = 0,5625, así que se paga el 56,25 % y el descuento total es del 43,75 %. Los descuentos sucesivos se multiplican.',
  },
  {
    id: 'mat-095', tema: 'potencias', dificultad: 2,
    enunciado: 'Calcula (3⁻²)⁻¹.',
    opciones: ['9', '1/9', '−9', '6'],
    correcta: 0,
    explicacion: 'Al elevar una potencia a otra se multiplican los exponentes: (−2)(−1) = 2, así que queda 3² = 9.',
  },
  {
    id: 'mat-096', tema: 'potencias', dificultad: 1,
    enunciado: '¿Cuánto vale √0,25?',
    opciones: ['0,5', '0,05', '0,125', '2,5'],
    correcta: 0,
    explicacion: '0,5 × 0,5 = 0,25. La raíz de un número entre 0 y 1 es mayor que el número original.',
  },
  {
    id: 'mat-097', tema: 'potencias', dificultad: 2,
    enunciado: 'Simplifica (x⁵)³ ÷ x⁹.',
    opciones: ['x⁶', 'x⁵', 'x¹²', 'x²'],
    correcta: 0,
    explicacion: '(x⁵)³ = x¹⁵, y al dividir se restan los exponentes: x¹⁵⁻⁹ = x⁶.',
  },
  {
    id: 'mat-098', tema: 'potencias', dificultad: 1,
    enunciado: '¿Cuánto vale la raíz cúbica de 64?',
    opciones: ['4', '8', '16', '32'],
    correcta: 0,
    explicacion: '4³ = 64. La raíz cuadrada de 64 sería 8: conviene no confundir el índice.',
  },
  {
    id: 'mat-099', tema: 'potencias', dificultad: 2,
    enunciado: '¿A qué equivale 2⁻³?',
    opciones: ['1/8', '−8', '−6', '8'],
    correcta: 0,
    explicacion: 'Un exponente negativo indica el recíproco: 2⁻³ = 1/2³ = 1/8. El signo del exponente no hace negativo el resultado.',
  },
  {
    id: 'mat-100', tema: 'logaritmos', dificultad: 1,
    enunciado: '¿Cuánto vale log₃ 81?',
    opciones: ['4', '3', '27', '9'],
    correcta: 0,
    explicacion: 'Se busca el exponente al que hay que elevar 3 para obtener 81: como 3⁴ = 81, el logaritmo es 4.',
  },
  {
    id: 'mat-101', tema: 'logaritmos', dificultad: 1,
    enunciado: 'Para cualquier base válida, log 1 vale:',
    opciones: ['0', '1', 'La base', 'No está definido'],
    correcta: 0,
    explicacion: 'Cualquier número elevado a 0 da 1, así que el logaritmo de 1 siempre es 0. Lo que no está definido es el logaritmo de 0 o de un número negativo.',
  },
  {
    id: 'mat-102', tema: 'logaritmos', dificultad: 2,
    enunciado: 'Calcula log₂ (8 · 4).',
    opciones: ['5', '6', '32', '12'],
    correcta: 0,
    explicacion: 'El logaritmo de un producto es la suma de los logaritmos: log₂8 + log₂4 = 3 + 2 = 5. También: 8 · 4 = 32 = 2⁵.',
  },
  {
    id: 'mat-103', tema: 'logaritmos', dificultad: 2,
    enunciado: 'Si 2^x = 1/8, ¿cuánto vale x?',
    opciones: ['−3', '3', '1/3', '−1/3'],
    correcta: 0,
    explicacion: '1/8 = 2⁻³, así que x = −3.',
  },
  {
    id: 'mat-104', tema: 'logaritmos', dificultad: 2,
    enunciado: 'Calcula log₅ 125 − log₅ 5.',
    opciones: ['2', '3', '1', '25'],
    correcta: 0,
    explicacion: 'log₅125 = 3 y log₅5 = 1, así que la diferencia es 2. También: log₅(125/5) = log₅25 = 2.',
  },
  {
    id: 'mat-105', tema: 'logaritmos', dificultad: 1,
    enunciado: 'Para cualquier base válida b, log_b b vale:',
    opciones: ['1', '0', 'b', 'No se puede calcular'],
    correcta: 0,
    explicacion: 'b¹ = b, así que el exponente buscado es 1.',
  },
  {
    id: 'mat-106', tema: 'algebra', dificultad: 1,
    enunciado: 'Desarrolla (x + 5)(x − 5).',
    opciones: ['x² − 25', 'x² + 25', 'x² + 10x − 25', 'x² − 10x + 25'],
    correcta: 0,
    explicacion: 'Es una suma por diferencia: el resultado es la diferencia de cuadrados, x² − 25. Los términos en x se cancelan.',
  },
  {
    id: 'mat-107', tema: 'algebra', dificultad: 2,
    enunciado: 'Factoriza x² + 7x + 12.',
    opciones: ['(x + 3)(x + 4)', '(x − 3)(x − 4)', '(x + 6)(x + 2)', '(x + 12)(x + 1)'],
    correcta: 0,
    explicacion: 'Se buscan dos números que multiplicados den 12 y sumados 7: son 3 y 4.',
  },
  {
    id: 'mat-108', tema: 'algebra', dificultad: 2,
    enunciado: 'Factoriza 6x³ − 9x² sacando factor común.',
    opciones: ['3x²(2x − 3)', '3x(2x² − 3)', 'x²(6x − 9)', '3x²(2x + 3)'],
    correcta: 0,
    explicacion: 'El factor común numérico es 3 y el literal es x², así que queda 3x²(2x − 3).',
  },
  {
    id: 'mat-109', tema: 'algebra', dificultad: 3,
    enunciado: 'Si a + b = 7 y a · b = 10, ¿cuánto vale a² + b²?',
    opciones: ['29', '49', '39', '19'],
    correcta: 0,
    explicacion: '(a + b)² = a² + 2ab + b² = 49. Restando 2ab = 20 queda a² + b² = 29.',
  },
  {
    id: 'mat-110', tema: 'algebra', dificultad: 2,
    enunciado: 'Simplifica (6x²y)/(3xy³), con x ≠ 0 e y ≠ 0.',
    opciones: ['2x/y²', '2xy', '2x²/y³', 'x/2y²'],
    correcta: 0,
    explicacion: '6/3 = 2, x²/x = x y y/y³ = 1/y². El resultado es 2x/y².',
  },
  {
    id: 'mat-111', tema: 'algebra', dificultad: 3,
    enunciado: 'Desarrolla (x − 2)(x² + 2x + 4).',
    opciones: ['x³ − 8', 'x³ + 8', 'x³ − 4x − 8', 'x³ + 4x² − 8'],
    correcta: 0,
    explicacion: 'Es la diferencia de cubos: (a − b)(a² + ab + b²) = a³ − b³, con a = x y b = 2.',
  },
  {
    id: 'mat-112', tema: 'ecuaciones', dificultad: 1,
    enunciado: 'Resuelve 5x − 7 = 3x + 9.',
    opciones: ['x = 8', 'x = 1', 'x = 2', 'x = 16'],
    correcta: 0,
    explicacion: 'Restando 3x: 2x − 7 = 9. Sumando 7: 2x = 16, así que x = 8.',
  },
  {
    id: 'mat-113', tema: 'ecuaciones', dificultad: 1,
    enunciado: 'Resuelve x/3 + 4 = 10.',
    opciones: ['x = 18', 'x = 2', 'x = 42', 'x = 6'],
    correcta: 0,
    explicacion: 'x/3 = 6, y multiplicando por 3 queda x = 18.',
  },
  {
    id: 'mat-114', tema: 'ecuaciones', dificultad: 2,
    enunciado: 'Resuelve el sistema: 3x + y = 11 ; x + y = 5.',
    opciones: ['x = 3, y = 2', 'x = 2, y = 3', 'x = 4, y = 1', 'x = 1, y = 4'],
    correcta: 0,
    explicacion: 'Restando la segunda de la primera: 2x = 6, así que x = 3 y entonces y = 2.',
  },
  {
    id: 'mat-115', tema: 'ecuaciones', dificultad: 2,
    enunciado: 'Resuelve 2(x + 3) − 4 = 3x − 1.',
    opciones: ['x = 3', 'x = 1', 'x = −3', 'x = 9'],
    correcta: 0,
    explicacion: '2x + 6 − 4 = 3x − 1, o sea 2x + 2 = 3x − 1. Restando 2x: 2 = x − 1, así que x = 3.',
  },
  {
    id: 'mat-116', tema: 'ecuaciones', dificultad: 1,
    enunciado: 'La suma de un número y su triple es 48. ¿Cuál es el número?',
    opciones: ['12', '16', '24', '36'],
    correcta: 0,
    explicacion: 'x + 3x = 4x = 48, así que x = 12.',
  },
  {
    id: 'mat-117', tema: 'ecuaciones', dificultad: 2,
    enunciado: 'Resuelve el sistema: x + 2y = 10 ; 3x − 2y = 6.',
    opciones: ['x = 4, y = 3', 'x = 3, y = 4', 'x = 2, y = 4', 'x = 6, y = 2'],
    correcta: 0,
    explicacion: 'Sumando las dos ecuaciones se elimina y: 4x = 16, así que x = 4. Sustituyendo: 4 + 2y = 10, y = 3.',
  },
  {
    id: 'mat-118', tema: 'cuadraticas', dificultad: 1,
    enunciado: 'Resuelve x² − 9 = 0.',
    opciones: ['x = 3 y x = −3', 'x = 3 solamente', 'x = 9 y x = −9', 'No tiene solución real'],
    correcta: 0,
    explicacion: 'x² = 9 tiene dos soluciones reales: 3 y −3. Olvidar la negativa es el error más frecuente.',
  },
  {
    id: 'mat-119', tema: 'cuadraticas', dificultad: 2,
    enunciado: 'Resuelve x² + 6x + 9 = 0.',
    opciones: ['x = −3 (raíz doble)', 'x = 3 (raíz doble)', 'x = −3 y x = 3', 'No tiene solución real'],
    correcta: 0,
    explicacion: 'Es un trinomio cuadrado perfecto: (x + 3)² = 0, así que la única solución es x = −3, con multiplicidad dos.',
  },
  {
    id: 'mat-120', tema: 'cuadraticas', dificultad: 2,
    enunciado: '¿Cuántas soluciones reales tiene x² − 4x + 5 = 0?',
    opciones: ['Ninguna', 'Una', 'Dos', 'Infinitas'],
    correcta: 0,
    explicacion: 'El discriminante es 16 − 20 = −4. Al ser negativo no hay raíces reales: la parábola no corta el eje x.',
  },
  {
    id: 'mat-121', tema: 'cuadraticas', dificultad: 2,
    enunciado: '¿Cuál es la suma de las raíces de x² − 5x + 6 = 0?',
    opciones: ['5', '6', '−5', '1'],
    correcta: 0,
    explicacion: 'La suma de las raíces es −b/a = 5 y el producto, c/a = 6. Comprobado: las raíces son 2 y 3.',
  },
  {
    id: 'mat-122', tema: 'cuadraticas', dificultad: 3,
    enunciado: 'Resuelve 2x² + 5x − 3 = 0.',
    opciones: ['x = 1/2 y x = −3', 'x = −1/2 y x = 3', 'x = 1 y x = −3', 'x = 3 y x = −2'],
    correcta: 0,
    explicacion: 'Con la fórmula general: x = (−5 ± √(25 + 24))/4 = (−5 ± 7)/4, que da 2/4 = 1/2 y −12/4 = −3.',
  },
  {
    id: 'mat-123', tema: 'cuadraticas', dificultad: 3,
    enunciado: '¿Cuál es el valor mínimo de la función y = x² − 4x + 7?',
    opciones: ['3', '7', '2', '−3'],
    correcta: 0,
    explicacion: 'El vértice está en x = −b/(2a) = 2, y al sustituir: 4 − 8 + 7 = 3. Como a > 0 la parábola abre hacia arriba, así que el vértice es el mínimo.',
  },
  {
    id: 'mat-124', tema: 'desigualdades', dificultad: 1,
    enunciado: 'Resuelve 2x + 5 > 13.',
    opciones: ['x > 4', 'x < 4', 'x > 9', 'x < 9'],
    correcta: 0,
    explicacion: '2x > 8, y al dividir entre 2 (positivo) el sentido se mantiene: x > 4.',
  },
  {
    id: 'mat-125', tema: 'desigualdades', dificultad: 2,
    enunciado: 'Resuelve −3x ≥ 12.',
    opciones: ['x ≤ −4', 'x ≥ −4', 'x ≤ 4', 'x ≥ 4'],
    correcta: 0,
    explicacion: 'Al dividir entre −3 hay que invertir el sentido de la desigualdad: x ≤ −4.',
  },
  {
    id: 'mat-126', tema: 'desigualdades', dificultad: 2,
    enunciado: '¿Cuál es el conjunto solución de |x| ≤ 5?',
    opciones: ['[−5, 5]', '(−5, 5)', '(−∞, −5] ∪ [5, ∞)', '[0, 5]'],
    correcta: 0,
    explicacion: 'El valor absoluto mide la distancia al cero, así que se buscan los puntos que están a 5 o menos: de −5 a 5, con los extremos incluidos.',
  },
  {
    id: 'mat-127', tema: 'desigualdades', dificultad: 2,
    enunciado: 'Resuelve la desigualdad doble 4 < x + 2 < 9.',
    opciones: ['2 < x < 7', '4 < x < 9', '6 < x < 11', '2 < x < 11'],
    correcta: 0,
    explicacion: 'Se resta 2 en las tres partes a la vez: 2 < x < 7.',
  },
  {
    id: 'mat-128', tema: 'desigualdades', dificultad: 1,
    enunciado: 'El intervalo [2, 7) representa los números que:',
    opciones: [
      'Son mayores o iguales que 2 y menores que 7',
      'Son mayores que 2 y menores o iguales que 7',
      'Están entre 2 y 7 sin incluir ninguno de los dos',
      'Incluyen tanto el 2 como el 7',
    ],
    correcta: 0,
    explicacion: 'El corchete incluye el extremo y el paréntesis lo excluye. Aquí el 2 entra y el 7 no.',
  },
  {
    id: 'mat-129', tema: 'desigualdades', dificultad: 3,
    enunciado: 'Resuelve x² ≤ 9.',
    opciones: ['−3 ≤ x ≤ 3', 'x ≤ 3', 'x ≤ −3 o x ≥ 3', 'x ≤ 9'],
    correcta: 0,
    explicacion: 'x² ≤ 9 equivale a |x| ≤ 3, es decir −3 ≤ x ≤ 3. Sacar raíz y quedarse solo con x ≤ 3 pierde la restricción por abajo.',
    pista: 'Comprueba con x = −5: da 25, que no cumple.',
  },
  {
    id: 'mat-130', tema: 'desigualdades', dificultad: 3,
    enunciado: '¿Cuál es el conjunto solución de |x − 3| > 2?',
    opciones: ['x < 1 o x > 5', '1 < x < 5', 'x > 5 solamente', '−5 < x < 1'],
    correcta: 0,
    explicacion: 'La distancia de x a 3 es mayor que 2, así que x se aleja por los dos lados: x − 3 > 2 da x > 5, y x − 3 < −2 da x < 1.',
  },
  {
    id: 'mat-131', tema: 'funciones', dificultad: 1,
    enunciado: 'Si f(x) = 5 − 2x, ¿cuánto vale f(3)?',
    opciones: ['−1', '1', '11', '−11'],
    correcta: 0,
    explicacion: 'f(3) = 5 − 2(3) = 5 − 6 = −1.',
  },
  {
    id: 'mat-132', tema: 'funciones', dificultad: 2,
    enunciado: '¿Cuál es el dominio de f(x) = 1/(x − 4)?',
    opciones: ['Todos los reales excepto 4', 'Todos los reales excepto 0', 'x > 4', 'Todos los reales'],
    correcta: 0,
    explicacion: 'El denominador no puede ser cero, así que se excluye x = 4. En los demás puntos la función está definida.',
  },
  {
    id: 'mat-133', tema: 'funciones', dificultad: 1,
    enunciado: '¿En qué punto corta la recta y = 4x − 6 al eje y?',
    opciones: ['(0, −6)', '(−6, 0)', '(0, 4)', '(1,5, 0)'],
    correcta: 0,
    explicacion: 'Se evalúa en x = 0: y = −6. En la forma y = mx + b, el término independiente b es siempre el corte con el eje y.',
  },
  {
    id: 'mat-134', tema: 'funciones', dificultad: 2,
    enunciado: 'Si f(x) = x² y g(x) = x + 1, ¿cuánto vale (g ∘ f)(3)?',
    opciones: ['10', '16', '12', '9'],
    correcta: 0,
    explicacion: 'En g ∘ f se aplica primero f: f(3) = 9, y después g(9) = 10. Invertir el orden daría 16.',
  },
  {
    id: 'mat-135', tema: 'funciones', dificultad: 3,
    enunciado: '¿Cuál es la función inversa de f(x) = 2x + 6?',
    opciones: ['(x − 6)/2', '(x + 6)/2', '2x − 6', '1/(2x + 6)'],
    correcta: 0,
    explicacion: 'Se escribe y = 2x + 6, se despeja x = (y − 6)/2 y se intercambian los nombres. La inversa deshace lo que hace la función, no es su recíproco.',
  },
  {
    id: 'mat-136', tema: 'funciones', dificultad: 2,
    enunciado: 'Una gráfica representa una función si:',
    opciones: [
      'Ninguna recta vertical la corta en más de un punto',
      'Ninguna recta horizontal la corta en más de un punto',
      'Pasa por el origen',
      'Es una línea recta',
    ],
    correcta: 0,
    explicacion: 'Es el criterio de la recta vertical: a cada valor de x le puede corresponder un solo valor de y. El criterio de la recta horizontal sirve para saber si es inyectiva.',
  },
  {
    id: 'mat-137', tema: 'sucesiones', dificultad: 1,
    enunciado: 'En la progresión aritmética 3, 7, 11, 15, … ¿cuál es el término número 15?',
    opciones: ['59', '63', '55', '60'],
    correcta: 0,
    explicacion: 'aₙ = a₁ + (n − 1)d = 3 + 14 × 4 = 3 + 56 = 59.',
  },
  {
    id: 'mat-138', tema: 'sucesiones', dificultad: 2,
    enunciado: '¿Cuál es la suma de los 10 primeros términos de la progresión 2, 5, 8, 11, …?',
    opciones: ['155', '145', '160', '290'],
    correcta: 0,
    explicacion: 'El décimo término es 2 + 9 × 3 = 29. La suma es n(a₁ + aₙ)/2 = 10(2 + 29)/2 = 155.',
  },
  {
    id: 'mat-139', tema: 'sucesiones', dificultad: 2,
    enunciado: 'En la progresión geométrica 2, 6, 18, … ¿cuál es el sexto término?',
    opciones: ['486', '162', '1 458', '243'],
    correcta: 0,
    explicacion: 'aₙ = a₁·r^(n−1) = 2 × 3⁵ = 2 × 243 = 486.',
  },
  {
    id: 'mat-140', tema: 'sucesiones', dificultad: 1,
    enunciado: '¿Cuál es la razón de la progresión geométrica 80, 40, 20, 10, …?',
    opciones: ['1/2', '2', '−40', '−1/2'],
    correcta: 0,
    explicacion: 'Cada término se obtiene multiplicando el anterior por 1/2, es decir, dividiendo entre 2.',
  },
  {
    id: 'mat-141', tema: 'sucesiones', dificultad: 2,
    enunciado: '¿Qué número sigue? 1, 3, 6, 10, 15, …',
    opciones: ['21', '20', '18', '25'],
    correcta: 0,
    explicacion: 'Las diferencias crecen de uno en uno: 2, 3, 4, 5 y ahora 6. Son los números triangulares: 15 + 6 = 21.',
  },
  {
    id: 'mat-142', tema: 'sucesiones', dificultad: 2,
    enunciado: '¿Cuál es el término general de la sucesión 5, 8, 11, 14, …?',
    opciones: ['3n + 2', '2n + 3', '3n − 2', 'n + 3'],
    correcta: 0,
    explicacion: 'La diferencia constante es 3, así que el término general es de la forma 3n + k. Con n = 1 debe dar 5, de donde k = 2.',
  },
  {
    id: 'mat-143', tema: 'sucesiones', dificultad: 3,
    enunciado: '¿Cuál es la suma de la progresión geométrica infinita 8 + 4 + 2 + 1 + …?',
    opciones: ['16', '15', 'Infinita', '8'],
    correcta: 0,
    explicacion: 'Cuando |r| < 1 la suma converge: S = a₁/(1 − r) = 8/(1 − 0,5) = 16. Sumar infinitos términos no siempre da infinito.',
  },
  {
    id: 'mat-144', tema: 'geometria-plana', dificultad: 1,
    enunciado: '¿Cuál es el perímetro de un rectángulo de 8 cm por 5 cm?',
    opciones: ['26 cm', '40 cm', '13 cm', '20 cm'],
    correcta: 0,
    explicacion: 'P = 2(largo + ancho) = 2(13) = 26 cm. Los 40 cm serían el área.',
  },
  {
    id: 'mat-145', tema: 'geometria-plana', dificultad: 2,
    enunciado: 'Un trapecio tiene bases de 10 cm y 6 cm y altura 4 cm. ¿Cuál es su área?',
    opciones: ['32 cm²', '64 cm²', '40 cm²', '20 cm²'],
    correcta: 0,
    explicacion: 'Área = (B + b)·h/2 = (10 + 6)(4)/2 = 32 cm².',
  },
  {
    id: 'mat-146', tema: 'geometria-plana', dificultad: 2,
    enunciado: '¿Cuánto suman los ángulos interiores de un pentágono?',
    opciones: ['540°', '360°', '720°', '450°'],
    correcta: 0,
    explicacion: 'La fórmula es 180°(n − 2) = 180° × 3 = 540°.',
  },
  {
    id: 'mat-147', tema: 'geometria-plana', dificultad: 1,
    enunciado: '¿Cuál es la longitud de una circunferencia de radio 7 cm?',
    opciones: ['14π cm', '49π cm', '7π cm', '28π cm'],
    correcta: 0,
    explicacion: 'L = 2πr = 14π cm. El área sería 49π cm².',
  },
  {
    id: 'mat-148', tema: 'geometria-plana', dificultad: 2,
    enunciado: 'Si dos ángulos son complementarios y uno mide 35°, ¿cuánto mide el otro?',
    opciones: ['55°', '145°', '65°', '35°'],
    correcta: 0,
    explicacion: 'Los complementarios suman 90°: 90 − 35 = 55. Los suplementarios son los que suman 180°.',
  },
  {
    id: 'mat-149', tema: 'geometria-espacio', dificultad: 1,
    enunciado: '¿Cuál es el volumen de un cubo de 5 cm de arista?',
    opciones: ['125 cm³', '25 cm³', '150 cm³', '75 cm³'],
    correcta: 0,
    explicacion: 'V = a³ = 5³ = 125 cm³.',
  },
  {
    id: 'mat-150', tema: 'geometria-espacio', dificultad: 2,
    enunciado: '¿Cuál es el área total de un cubo de 4 cm de arista?',
    opciones: ['96 cm²', '64 cm²', '16 cm²', '48 cm²'],
    correcta: 0,
    explicacion: 'Tiene 6 caras cuadradas de 16 cm² cada una: 6 × 16 = 96 cm².',
  },
  {
    id: 'mat-151', tema: 'geometria-espacio', dificultad: 1,
    enunciado: '¿Cuál es el volumen de un prisma rectangular de 3 cm × 4 cm × 10 cm?',
    opciones: ['120 cm³', '17 cm³', '34 cm³', '100 cm³'],
    correcta: 0,
    explicacion: 'V = largo × ancho × alto = 3 × 4 × 10 = 120 cm³.',
  },
  {
    id: 'mat-152', tema: 'geometria-espacio', dificultad: 2,
    enunciado: '¿Cuál es el volumen de un cono de radio 3 cm y altura 4 cm?',
    opciones: ['12π cm³', '36π cm³', '4π cm³', '9π cm³'],
    correcta: 0,
    explicacion: 'V = (1/3)πr²h = (1/3)π(9)(4) = 12π cm³. El cono es la tercera parte del cilindro con la misma base y altura.',
  },
  {
    id: 'mat-153', tema: 'geometria-espacio', dificultad: 2,
    enunciado: 'Una pirámide de base cuadrada tiene lado 6 cm y altura 10 cm. ¿Cuál es su volumen?',
    opciones: ['120 cm³', '360 cm³', '60 cm³', '180 cm³'],
    correcta: 0,
    explicacion: 'V = (1/3)·área de la base·altura = (1/3)(36)(10) = 120 cm³.',
  },
  {
    id: 'mat-154', tema: 'geometria-espacio', dificultad: 3,
    enunciado: 'Si la arista de un cubo se triplica, su volumen se multiplica por:',
    opciones: ['27', '3', '9', '6'],
    correcta: 0,
    explicacion: 'El volumen depende del cubo de la arista: 3³ = 27. El área total, en cambio, se multiplicaría por 9.',
  },
  {
    id: 'mat-155', tema: 'geometria-espacio', dificultad: 2,
    enunciado: '¿Cuál es el área lateral de un cilindro de radio 5 cm y altura 10 cm?',
    opciones: ['100π cm²', '50π cm²', '250π cm²', '150π cm²'],
    correcta: 0,
    explicacion: 'Al desenrollar la cara lateral queda un rectángulo de base 2πr y altura h: 2π(5)(10) = 100π cm².',
  },
  {
    id: 'mat-156', tema: 'geometria-analitica', dificultad: 1,
    enunciado: '¿Cuál es el punto medio del segmento con extremos (2, 4) y (8, 10)?',
    opciones: ['(5, 7)', '(10, 14)', '(3, 3)', '(6, 6)'],
    correcta: 0,
    explicacion: 'Se promedian las coordenadas: ((2 + 8)/2, (4 + 10)/2) = (5, 7).',
  },
  {
    id: 'mat-157', tema: 'geometria-analitica', dificultad: 2,
    enunciado: '¿Cuál es la pendiente de la recta y = 5?',
    opciones: ['0', '5', 'No está definida', '1'],
    correcta: 0,
    explicacion: 'Es una recta horizontal: y no cambia al variar x, así que la pendiente es 0. La pendiente indefinida corresponde a las rectas verticales, del tipo x = 5.',
  },
  {
    id: 'mat-158', tema: 'geometria-analitica', dificultad: 1,
    enunciado: '¿Cuál es la pendiente de cualquier recta paralela a y = 3x − 2?',
    opciones: ['3', '−3', '−1/3', '1/3'],
    correcta: 0,
    explicacion: 'Las rectas paralelas tienen la misma pendiente. La perpendicular tendría pendiente −1/3.',
  },
  {
    id: 'mat-159', tema: 'geometria-analitica', dificultad: 2,
    enunciado: '¿Pertenece el punto (2, 5) a la recta y = 2x + 1?',
    opciones: [
      'Sí, porque al sustituir x = 2 se obtiene y = 5',
      'No, porque 2 + 5 no es 1',
      'Sí, porque la pendiente es 2',
      'No se puede saber sin graficar',
    ],
    correcta: 0,
    explicacion: 'Un punto pertenece a una recta si sus coordenadas satisfacen la ecuación: 2(2) + 1 = 5.',
  },
  {
    id: 'mat-160', tema: 'geometria-analitica', dificultad: 2,
    enunciado: '¿Cuál es la ecuación de la recta de pendiente 2 que corta al eje y en −3?',
    opciones: ['y = 2x − 3', 'y = −3x + 2', 'y = 2x + 3', 'y = 3x − 2'],
    correcta: 0,
    explicacion: 'En la forma y = mx + b, m es la pendiente y b el corte con el eje y.',
  },
  {
    id: 'mat-161', tema: 'geometria-analitica', dificultad: 2,
    enunciado: '¿Cuál es la distancia del origen al punto (6, 8)?',
    opciones: ['10', '14', '√14', '48'],
    correcta: 0,
    explicacion: 'd = √(6² + 8²) = √100 = 10. Es el triángulo 3-4-5 multiplicado por 2.',
  },
  {
    id: 'mat-162', tema: 'estadistica', dificultad: 1,
    enunciado: '¿Cuál es la moda del conjunto 3, 5, 5, 7, 9, 5?',
    opciones: ['5', '6', '5,67', '9'],
    correcta: 0,
    explicacion: 'La moda es el dato que más se repite: el 5 aparece tres veces.',
  },
  {
    id: 'mat-163', tema: 'estadistica', dificultad: 1,
    enunciado: '¿Cuál es el rango del conjunto 4, 9, 12, 20?',
    opciones: ['16', '11,25', '20', '8'],
    correcta: 0,
    explicacion: 'El rango es la diferencia entre el mayor y el menor: 20 − 4 = 16.',
  },
  {
    id: 'mat-164', tema: 'estadistica', dificultad: 2,
    enunciado: '¿Cuál es la mediana del conjunto 2, 4, 6, 8?',
    opciones: ['5', '4', '6', '4,5'],
    correcta: 0,
    explicacion: 'Con una cantidad par de datos, la mediana es el promedio de los dos centrales: (4 + 6)/2 = 5.',
  },
  {
    id: 'mat-165', tema: 'estadistica', dificultad: 1,
    enunciado: '¿Cuál es la media de 10, 20, 30 y 40?',
    opciones: ['25', '30', '20', '100'],
    correcta: 0,
    explicacion: '(10 + 20 + 30 + 40)/4 = 100/4 = 25.',
  },
  {
    id: 'mat-166', tema: 'estadistica', dificultad: 2,
    enunciado: 'En un gráfico circular, un sector que representa el 25 % del total abarca un ángulo de:',
    opciones: ['90°', '25°', '120°', '45°'],
    correcta: 0,
    explicacion: 'El círculo completo son 360°, y el 25 % de 360 es 90°.',
  },
  {
    id: 'mat-167', tema: 'estadistica', dificultad: 3,
    enunciado: 'Si a todos los datos de un conjunto se les suma 5, ¿qué ocurre con la media y con el rango?',
    opciones: [
      'La media aumenta 5 y el rango no cambia',
      'Los dos aumentan 5',
      'La media no cambia y el rango aumenta 5',
      'Ninguno de los dos cambia',
    ],
    correcta: 0,
    explicacion: 'Sumar una constante desplaza todo el conjunto, así que la media se mueve con él. El rango mide distancia entre extremos, y esa distancia no se altera.',
  },
  {
    id: 'mat-168', tema: 'estadistica', dificultad: 3,
    enunciado: 'La tabla muestra las notas de un curso. ¿Cuál es la nota promedio?',
    codigo: [
      'Nota      Número de estudiantes',
      '  2                 4',
      '  3                 6',
      '  4                 8',
      '  5                 2',
    ].join('\n'),
    opciones: ['3,4', '3,5', '4,0', '20'],
    correcta: 0,
    explicacion: 'Suma ponderada: 2(4) + 3(6) + 4(8) + 5(2) = 8 + 18 + 32 + 10 = 68, dividido entre 20 estudiantes da 3,4. Promediar solo las notas (2, 3, 4, 5) ignoraría cuántos las obtuvieron.',
    pista: 'Cada nota pesa según el número de estudiantes que la sacó.',
  },
  {
    id: 'mat-169', tema: 'probabilidad', dificultad: 1,
    enunciado: 'Al lanzar un dado, ¿cuál es la probabilidad de obtener un número par?',
    opciones: ['1/2', '1/3', '1/6', '2/3'],
    correcta: 0,
    explicacion: 'Hay 3 casos favorables (2, 4, 6) de 6 posibles: 3/6 = 1/2.',
  },
  {
    id: 'mat-170', tema: 'probabilidad', dificultad: 2,
    enunciado: 'De una baraja de 52 cartas se saca una al azar. ¿Cuál es la probabilidad de que sea de corazones?',
    opciones: ['1/4', '1/13', '1/52', '1/2'],
    correcta: 0,
    explicacion: 'Hay 13 corazones de 52 cartas: 13/52 = 1/4, que es la proporción de cada palo.',
  },
  {
    id: 'mat-171', tema: 'probabilidad', dificultad: 1,
    enunciado: 'Se lanzan dos monedas. ¿Cuál es la probabilidad de obtener dos caras?',
    opciones: ['1/4', '1/2', '1/3', '3/4'],
    correcta: 0,
    explicacion: 'Los resultados posibles son CC, CS, SC y SS: uno de cuatro es favorable. Contar "dos caras, dos sellos o mixto" como tres casos iguales es el error clásico.',
  },
  {
    id: 'mat-172', tema: 'probabilidad', dificultad: 1,
    enunciado: 'Una bolsa tiene 3 bolas rojas y 5 azules. ¿Cuál es la probabilidad de sacar una roja?',
    opciones: ['3/8', '3/5', '1/3', '5/8'],
    correcta: 0,
    explicacion: 'Hay 8 bolas en total y 3 son rojas: 3/8.',
  },
  {
    id: 'mat-173', tema: 'probabilidad', dificultad: 2,
    enunciado: '¿De cuántas formas distintas pueden sentarse 4 personas en una fila de 4 sillas?',
    opciones: ['24', '16', '12', '4'],
    correcta: 0,
    explicacion: 'Es una permutación: 4! = 4 × 3 × 2 × 1 = 24. Aquí el orden sí importa.',
  },
  {
    id: 'mat-174', tema: 'probabilidad', dificultad: 2,
    enunciado: 'Si la probabilidad de que ocurra un evento A es 0,3, ¿cuál es la probabilidad de que NO ocurra?',
    opciones: ['0,7', '0,3', '0,5', '1,3'],
    correcta: 0,
    explicacion: 'La probabilidad del complemento es 1 − P(A) = 1 − 0,3 = 0,7.',
  },
  {
    id: 'mat-175', tema: 'problemas', dificultad: 2,
    enunciado: 'Dos llaves llenan un tanque en 4 y 6 horas respectivamente. Abiertas a la vez, ¿en cuánto tiempo lo llenan?',
    opciones: ['2,4 horas', '5 horas', '2 horas', '10 horas'],
    correcta: 0,
    explicacion: 'En una hora llenan 1/4 + 1/6 = 5/12 del tanque, así que tardan 12/5 = 2,4 horas.',
  },
  {
    id: 'mat-176', tema: 'problemas', dificultad: 3,
    enunciado: 'Un auto sale a 60 km/h. Dos horas después sale otro por la misma vía a 90 km/h. ¿Cuánto tarda el segundo en alcanzarlo?',
    opciones: ['4 horas', '2 horas', '3 horas', '6 horas'],
    correcta: 0,
    explicacion: 'Cuando el segundo sale, el primero lleva 120 km de ventaja y la diferencia de velocidades es 30 km/h: 120 ÷ 30 = 4 horas.',
    pista: 'Calcula la ventaja inicial y la velocidad con que se reduce.',
  },
  {
    id: 'mat-177', tema: 'problemas', dificultad: 2,
    enunciado: 'Dentro de 10 años, Pedro tendrá el doble de la edad que tiene ahora. ¿Cuántos años tiene?',
    opciones: ['10', '20', '5', '15'],
    correcta: 0,
    explicacion: 'x + 10 = 2x, de donde x = 10.',
  },
  {
    id: 'mat-178', tema: 'problemas', dificultad: 3,
    enunciado: 'Se quieren preparar 10 kg de una mezcla de café que cueste $15 000 el kilo, usando café de $12 000 y de $18 000. ¿Cuántos kilos de cada uno se necesitan?',
    opciones: ['5 kg y 5 kg', '4 kg y 6 kg', '6 kg y 4 kg', '3 kg y 7 kg'],
    correcta: 0,
    explicacion: 'El precio deseado está justo en el punto medio entre 12 000 y 18 000, así que la mezcla es mitad y mitad. Comprobación: 5(12 000) + 5(18 000) = 150 000, que entre 10 kg da 15 000.',
  },
  {
    id: 'mat-179', tema: 'problemas', dificultad: 2,
    enunciado: 'En un salón el 40 % son mujeres y hay 18 hombres. ¿Cuántos estudiantes hay en total?',
    opciones: ['30', '45', '25', '36'],
    correcta: 0,
    explicacion: 'Los hombres son el 60 %, así que 0,60·x = 18 y x = 30. El error común es calcular el total a partir del 40 %.',
  },
  {
    id: 'mat-180', tema: 'problemas', dificultad: 2,
    enunciado: 'Tres personas hacen un trabajo en 12 días. ¿Cuántas personas se necesitan para hacerlo en 4 días?',
    opciones: ['9', '6', '4', '12'],
    correcta: 0,
    explicacion: 'El trabajo total es 3 × 12 = 36 persona-día. Para 4 días: 36 ÷ 4 = 9 personas. Es proporción inversa.',
  },

  // ----- Completar los cuatro niveles en cada tema -----
  {
    id: 'mat-181', tema: 'aritmetica', dificultad: 3,
    enunciado: '¿Cuál es el menor número de tres cifras divisible a la vez entre 6 y entre 8?',
    opciones: ['120', '102', '144', '108'],
    correcta: 0,
    explicacion: 'Debe ser múltiplo del mcm(6, 8) = 24. El primer múltiplo de 24 con tres cifras es 120, porque 24 × 4 = 96 y 24 × 5 = 120.',
  },
  {
    id: 'mat-182', tema: 'aritmetica', dificultad: 3,
    enunciado: '¿Cuántos divisores positivos tiene el número 36?',
    opciones: ['9', '6', '8', '12'],
    correcta: 0,
    explicacion: 'Son 1, 2, 3, 4, 6, 9, 12, 18 y 36. Con la descomposición 36 = 2²·3², el conteo es (2+1)(2+1) = 9.',
  },
  {
    id: 'mat-183', tema: 'aritmetica', dificultad: 4,
    enunciado: 'Dos luces parpadean cada 12 y cada 18 segundos. Si acaban de coincidir, ¿cuántas veces volverán a coincidir en la siguiente hora exacta?',
    opciones: ['100', '60', '200', '36'],
    correcta: 0,
    explicacion: 'Coinciden cada mcm(12, 18) = 36 segundos. En 3 600 segundos eso ocurre 3 600 ÷ 36 = 100 veces.',
    pista: 'Primero halla cada cuánto coinciden; después cuántas veces cabe eso en una hora.',
  },
  {
    id: 'mat-184', tema: 'aritmetica', dificultad: 4,
    enunciado: 'El máximo común divisor de dos números es 12 y su mínimo común múltiplo es 72. Si uno de ellos es 24, ¿cuál es el otro?',
    opciones: ['36', '48', '6', '144'],
    correcta: 0,
    explicacion: 'El producto de dos números es igual al producto de su mcd por su mcm: a·b = 12 × 72 = 864. Entonces el otro es 864 ÷ 24 = 36.',
  },
  {
    id: 'mat-185', tema: 'aritmetica', dificultad: 4,
    enunciado: '¿Cuál es la cifra de las unidades de 7²⁰²⁴?',
    opciones: ['1', '7', '9', '3'],
    correcta: 0,
    explicacion: 'Las unidades de las potencias de 7 se repiten en ciclos de cuatro: 7, 9, 3, 1. Como 2 024 es múltiplo de 4, corresponde al último del ciclo: 1.',
    pista: 'Escribe las unidades de 7¹, 7², 7³ y 7⁴ y busca el patrón.',
  },
  {
    id: 'mat-186', tema: 'fracciones', dificultad: 1,
    enunciado: '¿Cuánto es 1/2 de 3/4?',
    opciones: ['3/8', '5/4', '2/3', '3/2'],
    correcta: 0,
    explicacion: '"De" significa multiplicar: (1/2)(3/4) = 3/8.',
  },
  {
    id: 'mat-187', tema: 'fracciones', dificultad: 3,
    enunciado: 'Un depósito se llena 2/5 el primer día y 1/3 del total el segundo. ¿Qué fracción del depósito falta por llenar?',
    opciones: ['4/15', '1/2', '3/8', '2/15'],
    correcta: 0,
    explicacion: 'Se llenó 2/5 + 1/3 = 6/15 + 5/15 = 11/15. Falta 1 − 11/15 = 4/15.',
  },
  {
    id: 'mat-188', tema: 'fracciones', dificultad: 4,
    enunciado: 'De una herencia, el hijo mayor recibe 1/3. El segundo recibe 1/4 de lo que quedó y sobran $18 000 000. ¿A cuánto ascendía la herencia?',
    opciones: ['$36 000 000', '$27 000 000', '$45 000 000', '$32 000 000'],
    correcta: 0,
    explicacion: 'Tras el mayor queda 2/3. El segundo toma 1/4 de eso, es decir 1/6 del total. Entre los dos se llevan 1/3 + 1/6 = 1/2, así que lo que sobra es la otra mitad: 18 millones = H/2, de donde H = 36 millones.',
    pista: 'El segundo recibe 1/4 del resto, no 1/4 del total.',
  },
  {
    id: 'mat-189', tema: 'fracciones', dificultad: 4,
    enunciado: '¿Cuál es el resultado de (1 − 1/2)(1 − 1/3)(1 − 1/4) … (1 − 1/10)?',
    opciones: ['1/10', '1/2', '9/10', '1/45'],
    correcta: 0,
    explicacion: 'Cada factor es (n − 1)/n: (1/2)(2/3)(3/4)…(9/10). Todos los numeradores se cancelan con el denominador siguiente y queda 1/10.',
  },
  {
    id: 'mat-190', tema: 'fracciones', dificultad: 4,
    enunciado: 'Un grifo llena 3/8 de un tanque en 45 minutos. ¿Cuánto tarda en llenarlo por completo?',
    opciones: ['2 horas', '1 hora y 30 minutos', '2 horas y 15 minutos', '1 hora y 45 minutos'],
    correcta: 0,
    explicacion: 'Si 3/8 tardan 45 min, 1/8 tarda 15 min y el tanque entero (8/8) tarda 120 min, es decir 2 horas.',
  },
  {
    id: 'mat-191', tema: 'razones', dificultad: 1,
    enunciado: 'En un salón hay 3 niñas por cada 2 niños. Si hay 12 niñas, ¿cuántos niños hay?',
    opciones: ['8', '18', '6', '10'],
    correcta: 0,
    explicacion: '12 niñas equivalen a 4 grupos de 3, así que hay 4 grupos de 2 niños: 8.',
  },
  {
    id: 'mat-192', tema: 'razones', dificultad: 3,
    enunciado: 'Una fotografía de 12 cm × 8 cm se amplía hasta que su lado largo mide 30 cm. ¿Cuánto mide el lado corto?',
    opciones: ['20 cm', '26 cm', '24 cm', '18 cm'],
    correcta: 0,
    explicacion: 'El factor de ampliación es 30 ÷ 12 = 2,5, y se aplica a los dos lados: 8 × 2,5 = 20 cm. Sumar la diferencia (18 cm) deformaría la imagen.',
  },
  {
    id: 'mat-193', tema: 'razones', dificultad: 3,
    enunciado: 'Si a : b = 2 : 3 y b : c = 4 : 5, ¿cuál es la razón a : c?',
    opciones: ['8 : 15', '2 : 5', '1 : 2', '6 : 20'],
    correcta: 0,
    explicacion: 'Hay que igualar el valor de b: multiplicando la primera por 4 y la segunda por 3 queda a : b : c = 8 : 12 : 15. Entonces a : c = 8 : 15.',
    pista: 'Lleva las dos razones a un mismo valor de b antes de comparar a con c.',
  },
  {
    id: 'mat-194', tema: 'razones', dificultad: 4,
    enunciado: 'Se reparten $1 300 entre tres personas de forma inversamente proporcional a 2, 3 y 4. ¿Cuánto recibe la primera?',
    opciones: ['$600', '$200', '$433', '$650'],
    correcta: 0,
    explicacion: 'En un reparto inverso se usan los recíprocos 1/2, 1/3 y 1/4, que con denominador común 12 son 6, 4 y 3. Suman 13 partes, así que cada parte vale 100: la primera recibe 6 × 100 = $600.',
  },
  {
    id: 'mat-195', tema: 'razones', dificultad: 4,
    enunciado: 'Ocho obreros terminan una obra en 6 días trabajando 5 horas diarias. ¿Cuántos días tardarían 10 obreros trabajando 4 horas diarias?',
    opciones: ['6', '5', '8', '4'],
    correcta: 0,
    explicacion: 'El trabajo total es 8 × 6 × 5 = 240 obrero-hora. Con 10 obreros a 4 horas se avanzan 40 obrero-hora por día: 240 ÷ 40 = 6 días.',
  },
  {
    id: 'mat-196', tema: 'razones', dificultad: 4,
    enunciado: 'Una aleación tiene oro y plata en razón 3 : 2. Si se añaden 10 g de oro, la razón pasa a ser 2 : 1. ¿Cuánto oro había al principio?',
    opciones: ['30 g', '20 g', '15 g', '40 g'],
    correcta: 0,
    explicacion: 'Si había 3k de oro y 2k de plata, entonces (3k + 10)/(2k) = 2, de donde 3k + 10 = 4k y k = 10. El oro inicial era 3k = 30 g.',
  },
  {
    id: 'mat-197', tema: 'porcentajes', dificultad: 1,
    enunciado: '¿Cuánto es el 50 % de 86?',
    opciones: ['43', '46', '38', '50'],
    correcta: 0,
    explicacion: 'El 50 % es la mitad: 86 ÷ 2 = 43.',
  },
  {
    id: 'mat-198', tema: 'porcentajes', dificultad: 4,
    enunciado: 'Un precio sube un 20 %. ¿Qué porcentaje debe bajar después para volver al precio original?',
    opciones: ['16,7 %', '20 %', '25 %', '18 %'],
    correcta: 0,
    explicacion: 'Si el original es 100, sube a 120. Para volver a 100 hay que quitar 20 sobre 120, es decir 20 ÷ 120 = 0,1667. El porcentaje de bajada no es igual al de subida porque la base cambió.',
    pista: 'La rebaja se calcula sobre el precio nuevo, no sobre el original.',
  },
  {
    id: 'mat-199', tema: 'porcentajes', dificultad: 4,
    enunciado: 'En una votación, A obtiene el 45 % y B el 40 %; el resto votó en blanco. Si A sacó 1 800 votos más que B, ¿cuántas personas votaron?',
    opciones: ['36 000', '40 000', '18 000', '72 000'],
    correcta: 0,
    explicacion: 'La diferencia es de 5 puntos porcentuales, que equivalen a 1 800 votos. Entonces el 1 % son 360 votos y el 100 % son 36 000.',
  },
  {
    id: 'mat-200', tema: 'porcentajes', dificultad: 4,
    enunciado: 'Un artículo baja un 20 % y después sube un 20 %. ¿Cuál es la variación neta respecto al precio inicial?',
    opciones: ['Queda un 4 % más barato', 'Queda igual', 'Queda un 4 % más caro', 'Queda un 40 % más barato'],
    correcta: 0,
    explicacion: '0,80 × 1,20 = 0,96, es decir el 96 % del precio original. Los porcentajes sucesivos se multiplican y no se compensan, porque el segundo se aplica sobre una base menor.',
  },
  {
    id: 'mat-201', tema: 'potencias', dificultad: 3,
    enunciado: '¿Cuántas veces es mayor 2²⁰ que 2¹⁵?',
    opciones: ['32 veces', '5 veces', '2 veces', '1 024 veces'],
    correcta: 0,
    explicacion: 'Al dividir se restan los exponentes: 2²⁰ ÷ 2¹⁵ = 2⁵ = 32. Restar los exponentes no da la diferencia de los números, da su cociente.',
  },
  {
    id: 'mat-202', tema: 'potencias', dificultad: 3,
    enunciado: 'Simplifica √(x⁶y⁴), con x e y positivos.',
    opciones: ['x³y²', 'x³y', 'x²y²', 'x⁶y⁴'],
    correcta: 0,
    explicacion: 'La raíz cuadrada divide los exponentes entre dos: x⁶ᐟ² y⁴ᐟ² = x³y².',
  },
  {
    id: 'mat-203', tema: 'potencias', dificultad: 4,
    enunciado: 'Si 2ˣ = 5, ¿cuánto vale 2ˣ⁺³?',
    opciones: ['40', '15', '125', '8'],
    correcta: 0,
    explicacion: '2ˣ⁺³ = 2ˣ · 2³ = 5 × 8 = 40. No hace falta despejar x.',
  },
  {
    id: 'mat-204', tema: 'potencias', dificultad: 4,
    enunciado: 'Ordena de menor a mayor: 2³⁰, 3²⁰ y 5¹⁰.',
    opciones: ['5¹⁰ < 2³⁰ < 3²⁰', '2³⁰ < 3²⁰ < 5¹⁰', '3²⁰ < 2³⁰ < 5¹⁰', '5¹⁰ < 3²⁰ < 2³⁰'],
    correcta: 0,
    explicacion: 'Se igualan los exponentes: 2³⁰ = 8¹⁰ y 3²⁰ = 9¹⁰. Con el mismo exponente basta comparar las bases: 5 < 8 < 9.',
    pista: 'Lleva las tres potencias al mismo exponente.',
  },
  {
    id: 'mat-205', tema: 'potencias', dificultad: 4,
    enunciado: 'Simplifica (4⁵ · 8³) ÷ 2²⁰.',
    opciones: ['1/2', '2', '4', '1'],
    correcta: 0,
    explicacion: 'Todo se expresa en base 2: 4⁵ = 2¹⁰ y 8³ = 2⁹, así que el numerador es 2¹⁹. Entonces 2¹⁹ ÷ 2²⁰ = 2⁻¹ = 1/2.',
  },
  {
    id: 'mat-206', tema: 'logaritmos', dificultad: 3,
    enunciado: 'Si log 2 = 0,301, ¿cuánto vale log 200?',
    opciones: ['2,301', '0,602', '2,000', '3,010'],
    correcta: 0,
    explicacion: '200 = 2 × 100, así que log 200 = log 2 + log 100 = 0,301 + 2 = 2,301.',
  },
  {
    id: 'mat-207', tema: 'logaritmos', dificultad: 3,
    enunciado: 'Si log_a 8 = 3, ¿cuál es el valor de a?',
    opciones: ['2', '3', '8', '1/2'],
    correcta: 0,
    explicacion: 'La definición dice a³ = 8, y el número que elevado al cubo da 8 es 2.',
  },
  {
    id: 'mat-208', tema: 'logaritmos', dificultad: 4,
    enunciado: 'Resuelve log x + log (x − 3) = 1, con logaritmos en base 10.',
    opciones: ['x = 5', 'x = 5 y x = −2', 'x = −2', 'No tiene solución'],
    correcta: 0,
    explicacion: 'La suma de logaritmos es el logaritmo del producto: x(x − 3) = 10, es decir x² − 3x − 10 = 0, con soluciones 5 y −2. La negativa se descarta porque no existe el logaritmo de un número negativo.',
    pista: 'Comprueba las dos soluciones en la ecuación original antes de responder.',
  },
  {
    id: 'mat-209', tema: 'logaritmos', dificultad: 4,
    enunciado: 'Con log 2 = 0,301 y log 3 = 0,477, ¿cuánto vale log 12?',
    opciones: ['1,079', '0,778', '1,431', '0,602'],
    correcta: 0,
    explicacion: '12 = 2² × 3, así que log 12 = 2 log 2 + log 3 = 0,602 + 0,477 = 1,079.',
  },
  {
    id: 'mat-210', tema: 'logaritmos', dificultad: 4,
    enunciado: 'Si log 2 = 0,301, ¿cuántas cifras tiene el número 2⁵⁰?',
    opciones: ['16', '15', '50', '17'],
    correcta: 0,
    explicacion: 'log(2⁵⁰) = 50 × 0,301 = 15,05. Un número cuyo logaritmo está entre 15 y 16 tiene 16 cifras: se toma la parte entera y se suma uno.',
  },
  {
    id: 'mat-211', tema: 'algebra', dificultad: 1,
    enunciado: 'Simplifica 3x + 5x − 2x.',
    opciones: ['6x', '10x', '6x³', '8x'],
    correcta: 0,
    explicacion: 'Solo se suman y restan los coeficientes de los términos semejantes: 3 + 5 − 2 = 6.',
  },
  {
    id: 'mat-212', tema: 'algebra', dificultad: 4,
    enunciado: 'Si x + y = 10 y x² + y² = 58, ¿cuánto vale xy?',
    opciones: ['21', '42', '29', '16'],
    correcta: 0,
    explicacion: '(x + y)² = x² + 2xy + y² = 100. Restando 58 queda 2xy = 42, así que xy = 21.',
  },
  {
    id: 'mat-213', tema: 'algebra', dificultad: 4,
    enunciado: 'Factoriza completamente x³ − x.',
    opciones: ['x(x − 1)(x + 1)', 'x(x² − 1)', '(x − 1)(x + 1)', 'x²(x − 1)'],
    correcta: 0,
    explicacion: 'Primero el factor común x, y después la diferencia de cuadrados: x(x² − 1) = x(x − 1)(x + 1). Dejarlo en x(x² − 1) es correcto pero no está factorizado del todo.',
  },
  {
    id: 'mat-214', tema: 'algebra', dificultad: 4,
    enunciado: 'Si x + 1/x = 3, ¿cuánto vale x³ + 1/x³?',
    opciones: ['18', '27', '9', '21'],
    correcta: 0,
    explicacion: 'De (x + 1/x)³ = x³ + 1/x³ + 3(x + 1/x) se despeja: x³ + 1/x³ = 27 − 3(3) = 18.',
    pista: 'Eleva al cubo la expresión que te dan y mira qué sobra.',
  },
  {
    id: 'mat-215', tema: 'ecuaciones', dificultad: 3,
    enunciado: 'Resuelve 2/x = 6, con x ≠ 0.',
    opciones: ['x = 1/3', 'x = 3', 'x = 12', 'x = 1/12'],
    correcta: 0,
    explicacion: 'Multiplicando en cruz: 6x = 2, de donde x = 1/3.',
  },
  {
    id: 'mat-216', tema: 'ecuaciones', dificultad: 3,
    enunciado: '¿Qué ocurre con el sistema 2x + 3y = 6 y 4x + 6y = 15?',
    opciones: [
      'No tiene solución: las rectas son paralelas',
      'Tiene una única solución',
      'Tiene infinitas soluciones',
      'Tiene exactamente dos soluciones',
    ],
    correcta: 0,
    explicacion: 'La segunda ecuación es el doble de la primera en los coeficientes, pero no en el término independiente (sería 12, no 15). Las rectas tienen la misma pendiente y distinto corte: nunca se cruzan.',
  },
  {
    id: 'mat-217', tema: 'ecuaciones', dificultad: 4,
    enunciado: 'Resuelve el sistema x + y = 7, y + z = 9, x + z = 12. ¿Cuánto vale z?',
    opciones: ['7', '5', '2', '9'],
    correcta: 0,
    explicacion: 'Sumando las tres ecuaciones: 2(x + y + z) = 28, así que x + y + z = 14. Restando la primera (x + y = 7) queda z = 7.',
    pista: 'Suma las tres ecuaciones antes de despejar nada.',
  },
  {
    id: 'mat-218', tema: 'ecuaciones', dificultad: 4,
    enunciado: 'Resuelve √(2x + 3) = x.',
    opciones: ['x = 3', 'x = 3 y x = −1', 'x = −1', 'No tiene solución'],
    correcta: 0,
    explicacion: 'Al elevar al cuadrado: 2x + 3 = x², es decir x² − 2x − 3 = 0, con raíces 3 y −1. La raíz cuadrada no puede dar un resultado negativo, así que x = −1 es una solución extraña y se descarta.',
  },
  {
    id: 'mat-219', tema: 'ecuaciones', dificultad: 4,
    enunciado: 'Un padre tiene 40 años y su hijo 10. ¿Dentro de cuántos años la edad del padre será el doble de la del hijo?',
    opciones: ['20', '10', '15', '30'],
    correcta: 0,
    explicacion: '40 + t = 2(10 + t), de donde 40 + t = 20 + 2t y t = 20. El error frecuente es olvidar que los dos envejecen a la vez.',
  },
  {
    id: 'mat-220', tema: 'cuadraticas', dificultad: 1,
    enunciado: '¿Cuáles son las soluciones de x² = 16?',
    opciones: ['x = 4 y x = −4', 'Solo x = 4', 'x = 8 y x = −8', 'x = 256'],
    correcta: 0,
    explicacion: 'Tanto 4² como (−4)² valen 16. Quedarse solo con la positiva es el error más común de la ecuación cuadrática más simple.',
  },
  {
    id: 'mat-221', tema: 'cuadraticas', dificultad: 4,
    enunciado: 'Una de las raíces de x² + bx + 12 = 0 es 3. ¿Cuál es la otra raíz y cuánto vale b?',
    opciones: ['La otra raíz es 4 y b = −7', 'La otra raíz es −4 y b = 7', 'La otra raíz es 9 y b = −12', 'La otra raíz es 4 y b = 7'],
    correcta: 0,
    explicacion: 'El producto de las raíces es 12, así que la otra es 12 ÷ 3 = 4. La suma es 3 + 4 = 7 y equivale a −b, de donde b = −7.',
  },
  {
    id: 'mat-222', tema: 'cuadraticas', dificultad: 4,
    enunciado: '¿Para qué valores de k la ecuación x² + kx + 4 = 0 tiene dos raíces reales distintas?',
    opciones: ['k < −4 o k > 4', '−4 < k < 4', 'Solo k = 4', 'Para cualquier valor de k'],
    correcta: 0,
    explicacion: 'Hacen falta dos raíces distintas, así que el discriminante debe ser positivo: k² − 16 > 0, es decir |k| > 4. Con k = ±4 habría una sola raíz doble.',
  },
  {
    id: 'mat-223', tema: 'cuadraticas', dificultad: 4,
    enunciado: 'Un rectángulo tiene 34 cm de perímetro y 60 cm² de área. ¿Cuánto miden sus lados?',
    opciones: ['12 cm y 5 cm', '10 cm y 6 cm', '15 cm y 4 cm', '17 cm y 3,5 cm'],
    correcta: 0,
    explicacion: 'Si los lados son x e y: x + y = 17 y xy = 60. Son las raíces de t² − 17t + 60 = 0, que son 12 y 5.',
    pista: 'El semiperímetro es la suma de los lados, no el perímetro.',
  },
  {
    id: 'mat-224', tema: 'desigualdades', dificultad: 4,
    enunciado: '¿Para qué valores de x se cumple (x − 1)/(x + 2) > 0?',
    opciones: ['x < −2 o x > 1', '−2 < x < 1', 'x > 1 solamente', 'x > −2'],
    correcta: 0,
    explicacion: 'El cociente es positivo cuando numerador y denominador tienen el mismo signo: los dos negativos si x < −2, los dos positivos si x > 1. En x = −2 la expresión no está definida.',
  },
  {
    id: 'mat-225', tema: 'desigualdades', dificultad: 4,
    enunciado: '¿Para qué valores de x se cumple x² < x?',
    opciones: ['0 < x < 1', 'x < 1', 'x < 0', 'x > 1'],
    correcta: 0,
    explicacion: 'x² − x < 0 equivale a x(x − 1) < 0, lo que ocurre solo entre 0 y 1. Dividir entre x sin más daría "x < 1", que es falso para los negativos: con x = −2 se tiene 4 < −2, que no se cumple.',
    pista: 'No dividas entre x: no sabes si es positivo o negativo.',
  },
  {
    id: 'mat-226', tema: 'desigualdades', dificultad: 4,
    enunciado: 'Si −2 ≤ x ≤ 3, ¿entre qué valores está x²?',
    opciones: ['0 ≤ x² ≤ 9', '4 ≤ x² ≤ 9', '−4 ≤ x² ≤ 9', '0 ≤ x² ≤ 4'],
    correcta: 0,
    explicacion: 'El mayor valor lo da el extremo de mayor valor absoluto: 3² = 9. El menor no lo da ningún extremo, lo da x = 0, que está dentro del intervalo y produce 0.',
  },
  {
    id: 'mat-227', tema: 'funciones', dificultad: 3,
    enunciado: '¿Cuál es el rango de f(x) = x² + 3?',
    opciones: ['[3, ∞)', '(−∞, ∞)', '[0, ∞)', '(3, ∞)'],
    correcta: 0,
    explicacion: 'x² nunca es negativo, así que el menor valor posible es 0 y se alcanza en x = 0: el mínimo de la función es 3 y sí se alcanza, por eso el corchete.',
  },
  {
    id: 'mat-228', tema: 'funciones', dificultad: 4,
    enunciado: 'Si f(x) = 2x − 1, ¿cuánto vale f(f(3))?',
    opciones: ['9', '5', '11', '17'],
    correcta: 0,
    explicacion: 'Primero f(3) = 5, y después f(5) = 2(5) − 1 = 9.',
  },
  {
    id: 'mat-229', tema: 'funciones', dificultad: 4,
    enunciado: 'La gráfica de y = f(x − 2) + 3 se obtiene de la de y = f(x):',
    opciones: [
      'Desplazándola 2 unidades a la derecha y 3 hacia arriba',
      'Desplazándola 2 a la izquierda y 3 hacia abajo',
      'Estirándola 2 veces en horizontal y 3 en vertical',
      'Reflejándola respecto del eje y',
    ],
    correcta: 0,
    explicacion: 'Lo que ocurre dentro del paréntesis actúa al revés de como se lee: restar 2 mueve hacia la derecha. Lo que se suma fuera actúa de forma directa: sube 3.',
  },
  {
    id: 'mat-230', tema: 'funciones', dificultad: 4,
    enunciado: 'Si f(x + 1) = 3x + 2, ¿cuánto vale f(4)?',
    opciones: ['11', '14', '5', '13'],
    correcta: 0,
    explicacion: 'Se busca el valor de x que hace x + 1 = 4, es decir x = 3. Entonces f(4) = 3(3) + 2 = 11. Sustituir directamente 4 en 3x + 2 daría f(5), no f(4).',
    pista: 'La fórmula está escrita en términos de x + 1, no de x.',
  },
  {
    id: 'mat-231', tema: 'sucesiones', dificultad: 3,
    enunciado: '¿Cuántos términos tiene la progresión aritmética 5, 9, 13, …, 101?',
    opciones: ['25', '24', '26', '96'],
    correcta: 0,
    explicacion: '101 = 5 + (n − 1)(4), de donde (n − 1) = 24 y n = 25. Olvidar sumar el primer término es el error habitual.',
  },
  {
    id: 'mat-232', tema: 'sucesiones', dificultad: 3,
    enunciado: 'En una progresión geométrica de términos positivos, el segundo término es 6 y el cuarto es 54. ¿Cuál es la razón?',
    opciones: ['3', '9', '6', '2'],
    correcta: 0,
    explicacion: 'Del segundo al cuarto se multiplica dos veces por la razón: r² = 54 ÷ 6 = 9, así que r = 3 (se descarta −3 porque los términos son positivos).',
  },
  {
    id: 'mat-233', tema: 'sucesiones', dificultad: 4,
    enunciado: '¿Cuál es la suma de los 20 primeros números impares (1 + 3 + 5 + … )?',
    opciones: ['400', '380', '420', '200'],
    correcta: 0,
    explicacion: 'La suma de los n primeros impares siempre es n²: 20² = 400. También sale con la fórmula de la progresión aritmética, cuyo término 20 es 39: 20(1 + 39)/2 = 400.',
  },
  {
    id: 'mat-234', tema: 'sucesiones', dificultad: 4,
    enunciado: 'En una progresión aritmética, el tercer término es 11 y el séptimo es 27. ¿Cuál es el primer término?',
    opciones: ['3', '5', '7', '1'],
    correcta: 0,
    explicacion: 'Entre el tercero y el séptimo hay cuatro saltos: d = (27 − 11)/4 = 4. Retrocediendo dos saltos desde el tercero: 11 − 8 = 3.',
  },
  {
    id: 'mat-235', tema: 'sucesiones', dificultad: 4,
    enunciado: 'Una pelota se deja caer desde 8 m y en cada rebote alcanza 3/4 de la altura anterior. ¿Qué distancia total recorre hasta detenerse?',
    opciones: ['56 m', '48 m', '32 m', '24 m'],
    correcta: 0,
    explicacion: 'La primera caída son 8 m. Después sube y baja cada altura: 2 × [6 + 4,5 + …], una progresión geométrica infinita de razón 3/4 cuya suma es 6 ÷ (1 − 3/4) = 24. El total es 8 + 2(24) = 56 m.',
    pista: 'Después del primer impacto, cada altura se recorre dos veces.',
  },
  {
    id: 'mat-236', tema: 'geometria-plana', dificultad: 3,
    enunciado: 'Un rombo tiene diagonales de 10 cm y 6 cm. ¿Cuál es su área?',
    opciones: ['30 cm²', '60 cm²', '16 cm²', '15 cm²'],
    correcta: 0,
    explicacion: 'El área del rombo es el producto de las diagonales dividido entre dos: (10 × 6)/2 = 30 cm².',
  },
  {
    id: 'mat-237', tema: 'geometria-plana', dificultad: 3,
    enunciado: '¿Cuánto mide cada ángulo interior de un hexágono regular?',
    opciones: ['120°', '60°', '135°', '108°'],
    correcta: 0,
    explicacion: 'La suma de los ángulos interiores es 180°(6 − 2) = 720°, y al ser regular se reparte en partes iguales: 720 ÷ 6 = 120°.',
  },
  {
    id: 'mat-238', tema: 'geometria-plana', dificultad: 4,
    enunciado: 'Un cuadrado está inscrito en una circunferencia de radio 5 cm. ¿Cuál es el área del cuadrado?',
    opciones: ['50 cm²', '100 cm²', '25 cm²', '78,5 cm²'],
    correcta: 0,
    explicacion: 'La diagonal del cuadrado es el diámetro: 10 cm. Como la diagonal es lado × √2, el lado es 10/√2 y el área, lado², vale 100/2 = 50 cm².',
    pista: 'La diagonal del cuadrado coincide con el diámetro del círculo.',
  },
  {
    id: 'mat-239', tema: 'geometria-plana', dificultad: 4,
    enunciado: 'Si se duplica el radio de un círculo, ¿qué ocurre con su perímetro y con su área?',
    opciones: [
      'El perímetro se duplica y el área se cuadruplica',
      'Los dos se duplican',
      'Los dos se cuadruplican',
      'El perímetro se cuadruplica y el área se duplica',
    ],
    correcta: 0,
    explicacion: 'El perímetro depende de r de forma lineal y el área, de r². Al duplicar r, el área se multiplica por 2² = 4.',
  },
  {
    id: 'mat-240', tema: 'geometria-plana', dificultad: 4,
    enunciado: 'Dos triángulos son semejantes con razón de semejanza 2 : 3. Si el área del menor es 16 cm², ¿cuál es la del mayor?',
    opciones: ['36 cm²', '24 cm²', '32 cm²', '48 cm²'],
    correcta: 0,
    explicacion: 'Las áreas están en la razón de los cuadrados: (3/2)² = 9/4. Entonces 16 × 9/4 = 36 cm². Multiplicar por 3/2 sería el error.',
  },
  {
    id: 'mat-241', tema: 'geometria-espacio', dificultad: 3,
    enunciado: 'Una caja tiene 2 cm × 3 cm × 4 cm. ¿Cuál es su área total?',
    opciones: ['52 cm²', '24 cm²', '26 cm²', '104 cm²'],
    correcta: 0,
    explicacion: 'Las caras van por parejas: 2(2×3) + 2(2×4) + 2(3×4) = 12 + 16 + 24 = 52 cm². El volumen sería 24 cm³.',
  },
  {
    id: 'mat-242', tema: 'geometria-espacio', dificultad: 4,
    enunciado: 'Un tanque cilíndrico tiene 2 m de diámetro y 3 m de altura. ¿Cuántos litros de agua caben aproximadamente? (π ≈ 3,14)',
    opciones: ['9 420 L', '18 840 L', '942 L', '3 140 L'],
    correcta: 0,
    explicacion: 'El radio es 1 m, así que V = π(1²)(3) ≈ 9,42 m³. Como 1 m³ son 1 000 litros, caben unos 9 420 L. Usar el diámetro como radio duplicaría el resultado por cuatro.',
    pista: 'Te dan el diámetro, no el radio.',
  },
  {
    id: 'mat-243', tema: 'geometria-espacio', dificultad: 4,
    enunciado: 'Un cono tiene 6 cm de radio y 8 cm de altura. ¿Cuánto mide su generatriz?',
    opciones: ['10 cm', '14 cm', '48 cm', '√28 cm'],
    correcta: 0,
    explicacion: 'La generatriz es la hipotenusa del triángulo que forman el radio y la altura: √(6² + 8²) = √100 = 10 cm.',
  },
  {
    id: 'mat-244', tema: 'geometria-espacio', dificultad: 4,
    enunciado: 'Se funde un cubo de 6 cm de arista y con el material se hacen cubos de 2 cm de arista. ¿Cuántos se obtienen?',
    opciones: ['27', '3', '9', '108'],
    correcta: 0,
    explicacion: 'Los volúmenes son 216 cm³ y 8 cm³: 216 ÷ 8 = 27. Dividir las aristas (6 ÷ 2 = 3) es el error clásico, porque el volumen crece con el cubo de la longitud.',
  },
  {
    id: 'mat-245', tema: 'geometria-analitica', dificultad: 3,
    enunciado: '¿Cuál es la ecuación de la recta que pasa por (0, 0) y (3, 6)?',
    opciones: ['y = 2x', 'y = x + 3', 'y = 3x', 'y = x/2'],
    correcta: 0,
    explicacion: 'La pendiente es 6/3 = 2 y, al pasar por el origen, el término independiente es 0.',
  },
  {
    id: 'mat-246', tema: 'geometria-analitica', dificultad: 3,
    enunciado: 'Los extremos de un diámetro de una circunferencia son (2, 3) y (8, 11). ¿Cuál es su centro?',
    opciones: ['(5, 7)', '(6, 8)', '(10, 14)', '(3, 4)'],
    correcta: 0,
    explicacion: 'El centro es el punto medio del diámetro: ((2 + 8)/2, (3 + 11)/2) = (5, 7).',
  },
  {
    id: 'mat-247', tema: 'geometria-analitica', dificultad: 4,
    enunciado: '¿Cuál es el área del triángulo con vértices en (0, 0), (4, 0) y (0, 3)?',
    opciones: ['6', '12', '7', '5'],
    correcta: 0,
    explicacion: 'Los catetos están sobre los ejes y miden 4 y 3: el área es (4 × 3)/2 = 6.',
  },
  {
    id: 'mat-248', tema: 'geometria-analitica', dificultad: 4,
    enunciado: '¿Qué relación tienen las rectas y = 2x + 1 y 2y − 4x = 7?',
    opciones: ['Son paralelas', 'Son perpendiculares', 'Se cortan en un punto', 'Son la misma recta'],
    correcta: 0,
    explicacion: 'Despejando la segunda: y = 2x + 3,5. Tienen la misma pendiente y distinto corte con el eje y, así que nunca se cruzan.',
  },
  {
    id: 'mat-249', tema: 'geometria-analitica', dificultad: 4,
    enunciado: 'La circunferencia x² + y² − 6x + 4y − 12 = 0 tiene radio:',
    opciones: ['5', '12', '√12', '25'],
    correcta: 0,
    explicacion: 'Completando cuadrados: (x − 3)² − 9 + (y + 2)² − 4 − 12 = 0, es decir (x − 3)² + (y + 2)² = 25. El radio es √25 = 5 y el centro (3, −2).',
    pista: 'Completa cuadrados en x y en y por separado.',
  },
  {
    id: 'mat-250', tema: 'estadistica', dificultad: 3,
    enunciado: 'Para el conjunto 3, 5, 7, 9 y 100, ¿qué medida representa mejor el centro de los datos?',
    opciones: [
      'La mediana, porque la media se distorsiona con el valor atípico',
      'La media, porque usa todos los datos',
      'La moda, porque es la más estable',
      'El rango, porque mide la dispersión',
    ],
    correcta: 0,
    explicacion: 'La media es 24,8, un valor por encima de casi todos los datos. La mediana es 7 y describe mucho mejor al grupo. El rango no es una medida de centro.',
  },
  {
    id: 'mat-251', tema: 'estadistica', dificultad: 4,
    enunciado: 'La media de 8 datos es 15. Se agrega un dato más y la media pasa a 16. ¿Cuál es el dato agregado?',
    opciones: ['24', '17', '16', '31'],
    correcta: 0,
    explicacion: 'La suma pasa de 8 × 15 = 120 a 9 × 16 = 144. El dato nuevo es la diferencia: 24.',
  },
  {
    id: 'mat-252', tema: 'estadistica', dificultad: 4,
    enunciado: 'Un curso evalúa con tres notas: 60 (peso 30 %), 80 (peso 50 %) y 90 (peso 20 %). ¿Cuál es la nota definitiva?',
    opciones: ['76', '76,7', '80', '78'],
    correcta: 0,
    explicacion: '60(0,30) + 80(0,50) + 90(0,20) = 18 + 40 + 18 = 76. El promedio simple daría 76,7, que no es lo que corresponde cuando los pesos son distintos.',
  },
  {
    id: 'mat-253', tema: 'estadistica', dificultad: 4,
    enunciado: 'Si todos los datos de un conjunto se multiplican por 3, ¿qué ocurre con la media y con el rango?',
    opciones: [
      'Los dos se multiplican por 3',
      'La media se multiplica por 3 y el rango no cambia',
      'Ninguno de los dos cambia',
      'La media no cambia y el rango se multiplica por 3',
    ],
    correcta: 0,
    explicacion: 'Multiplicar reescala todo el conjunto: cambian el centro y la dispersión en la misma proporción. Es distinto de sumar una constante, que mueve la media y deja el rango igual.',
  },
  {
    id: 'mat-254', tema: 'probabilidad', dificultad: 3,
    enunciado: 'Se lanzan dos dados. ¿Cuál es la probabilidad de que los dos muestren número par?',
    opciones: ['1/4', '1/2', '1/3', '1/6'],
    correcta: 0,
    explicacion: 'Cada dado tiene probabilidad 1/2 de salir par y los lanzamientos son independientes: (1/2)(1/2) = 1/4.',
  },
  {
    id: 'mat-255', tema: 'probabilidad', dificultad: 3,
    enunciado: 'En una reunión de 5 personas todos se saludan de mano una sola vez. ¿Cuántos apretones hay?',
    opciones: ['10', '20', '25', '5'],
    correcta: 0,
    explicacion: 'Es elegir parejas sin importar el orden: C(5, 2) = 10. Contar 5 × 4 = 20 duplicaría cada saludo.',
  },
  {
    id: 'mat-256', tema: 'probabilidad', dificultad: 4,
    enunciado: 'Se lanza un dado dos veces. ¿Cuál es la probabilidad de obtener al menos un seis?',
    opciones: ['11/36', '1/3', '1/36', '2/6'],
    correcta: 0,
    explicacion: 'Es más fácil por el complemento: la probabilidad de no sacar ningún seis es (5/6)² = 25/36, así que al menos uno es 1 − 25/36 = 11/36. Sumar 1/6 + 1/6 cuenta dos veces el caso de dos seises.',
    pista: 'Calcula primero la probabilidad de que no ocurra.',
  },
  {
    id: 'mat-257', tema: 'probabilidad', dificultad: 4,
    enunciado: 'Una urna tiene 4 bolas rojas y 6 azules. Se sacan dos sin reponer. ¿Cuál es la probabilidad de que sean de distinto color?',
    opciones: ['8/15', '2/15', '1/3', '24/100'],
    correcta: 0,
    explicacion: 'Hay dos formas: roja y luego azul, (4/10)(6/9), o azul y luego roja, (6/10)(4/9). Cada una vale 24/90 y juntas suman 48/90 = 8/15.',
  },
  {
    id: 'mat-258', tema: 'probabilidad', dificultad: 4,
    enunciado: 'En un curso, el 60 % son mujeres y el 30 % de ellas usa gafas. Si se elige una persona al azar, ¿cuál es la probabilidad de que sea una mujer con gafas?',
    opciones: ['0,18', '0,30', '0,60', '0,90'],
    correcta: 0,
    explicacion: 'Se multiplican las dos condiciones: 0,60 × 0,30 = 0,18, es decir el 18 %. El 30 % está calculado solo sobre las mujeres, no sobre el curso completo.',
  },
  {
    id: 'mat-259', tema: 'problemas', dificultad: 1,
    enunciado: 'Si un lápiz cuesta $800, ¿cuánto cuestan 6 lápices?',
    opciones: ['$4 800', '$4 200', '$5 600', '$800'],
    correcta: 0,
    explicacion: 'Se multiplica el precio unitario por la cantidad: 800 × 6 = 4 800 pesos.',
  },
  {
    id: 'mat-260', tema: 'problemas', dificultad: 1,
    enunciado: 'Un bus sale a las 7:15 y llega a las 9:40. ¿Cuánto dura el viaje?',
    opciones: ['2 horas y 25 minutos', '2 horas y 35 minutos', '1 hora y 25 minutos', '2 horas y 15 minutos'],
    correcta: 0,
    explicacion: 'De 7:15 a 9:15 hay 2 horas, y de 9:15 a 9:40 hay 25 minutos más.',
  },
  {
    id: 'mat-261', tema: 'problemas', dificultad: 1,
    enunciado: 'Un artículo cuesta $25 000 y tiene un 10 % de descuento. ¿Cuánto se paga?',
    opciones: ['$22 500', '$24 000', '$2 500', '$23 500'],
    correcta: 0,
    explicacion: 'El descuento es 2 500, así que se paga 25 000 − 2 500 = 22 500. También: 25 000 × 0,9.',
  },
  {
    id: 'mat-262', tema: 'problemas', dificultad: 3,
    enunciado: 'Una llave llena un tanque en 3 horas y un desagüe lo vacía en 6. Si se abren las dos a la vez con el tanque vacío, ¿cuánto tarda en llenarse?',
    opciones: ['6 horas', '2 horas', '9 horas', 'Nunca se llena'],
    correcta: 0,
    explicacion: 'En una hora entra 1/3 y sale 1/6, así que el avance neto es 1/3 − 1/6 = 1/6 del tanque por hora: 6 horas. Si el desagüe fuera más rápido que la llave, entonces sí no se llenaría nunca.',
  },
  {
    id: 'mat-263', tema: 'problemas', dificultad: 4,
    enunciado: 'Un comerciante compra un artículo en $40 000 y quiere que su ganancia sea el 20 % del precio de venta. ¿A cuánto debe venderlo?',
    opciones: ['$50 000', '$48 000', '$52 000', '$44 000'],
    correcta: 0,
    explicacion: 'Si la ganancia es el 20 % de la venta, el costo es el 80 %: 0,80·PV = 40 000, de donde PV = 50 000. Calcular el 20 % sobre el costo daría 48 000, que es una ganancia sobre otra base.',
    pista: 'Fíjate sobre qué cantidad se calcula el porcentaje: la venta o el costo.',
  },
  {
    id: 'mat-264', tema: 'problemas', dificultad: 4,
    enunciado: 'Dos trenes salen a la vez del mismo punto en sentidos opuestos, a 60 y 80 km/h. ¿Cuánto tardan en estar separados 350 km?',
    opciones: ['2,5 horas', '5 horas', '3,5 horas', '2 horas'],
    correcta: 0,
    explicacion: 'Se separan a 60 + 80 = 140 km/h, así que 350 ÷ 140 = 2,5 horas. En sentidos opuestos las velocidades se suman igual que cuando van uno hacia el otro.',
  },
  {
    id: 'mat-265', tema: 'problemas', dificultad: 4,
    enunciado: 'Hace 6 años, la edad de Ana era el triple de la de Bruno. Hoy es el doble. ¿Cuántos años tiene Ana?',
    opciones: ['24', '18', '30', '36'],
    correcta: 0,
    explicacion: 'Con A = 2B hoy y A − 6 = 3(B − 6) hace seis años: 2B − 6 = 3B − 18, de donde B = 12 y A = 24. Comprobación: hace 6 años tenían 18 y 6, y 18 es el triple de 6.',
  },
];
