/**
 * quimica.js — Banco de química.
 *
 * Componente químico de la prueba de ciencias naturales del Saber 11 y parte
 * del componente de ciencias naturales del examen de admisión de la UNAL.
 *
 * Las masas atómicas se redondean como en el examen (H = 1, C = 12, N = 14,
 * O = 16, Na = 23, Cl = 35,5, Ca = 40, S = 32) para que todo se pueda resolver
 * a mano.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const QUIMICA = [
  // ----- La materia y sus transformaciones -----
  {
    id: 'qui-001', tema: 'materia', dificultad: 1,
    enunciado: '¿Cuál de estas es una mezcla homogénea?',
    opciones: ['Agua con sal disuelta', 'Agua con aceite', 'Arena con piedras', 'Ensalada de frutas'],
    correcta: 0,
    explicacion: 'En una mezcla homogénea no se distinguen los componentes a simple vista ni con microscopio óptico: forman una sola fase. Las otras tres son heterogéneas.',
  },
  {
    id: 'qui-002', tema: 'materia', dificultad: 1,
    enunciado: '¿Qué método sirve para separar un sólido insoluble de un líquido?',
    opciones: ['La filtración', 'La destilación', 'La evaporación', 'La cromatografía'],
    correcta: 0,
    explicacion: 'El filtro deja pasar el líquido y retiene las partículas sólidas. La destilación separa líquidos por su punto de ebullición.',
  },
  {
    id: 'qui-003', tema: 'materia', dificultad: 2,
    enunciado: 'La destilación permite separar dos líquidos mezclados aprovechando que tienen distinto:',
    opciones: ['Punto de ebullición', 'Color', 'Peso molecular exacto', 'Tamaño de partícula'],
    correcta: 0,
    explicacion: 'Se calienta la mezcla: el de menor punto de ebullición se evapora primero y se recoge al condensarlo. Así se separan el agua y el alcohol.',
  },
  {
    id: 'qui-004', tema: 'materia', dificultad: 2,
    enunciado: '¿Cuál de estos es un cambio químico y no físico?',
    opciones: [
      'La combustión de un papel',
      'La fusión del hielo',
      'La disolución de azúcar en agua',
      'El corte de una lámina de metal',
    ],
    correcta: 0,
    explicacion: 'En un cambio químico aparecen sustancias nuevas y el proceso no se revierte fácilmente. Derretir, disolver o cortar no alteran la identidad de la sustancia.',
  },
  {
    id: 'qui-005', tema: 'materia', dificultad: 1,
    enunciado: 'En el estado gaseoso, las partículas de una sustancia:',
    opciones: [
      'Están muy separadas y se mueven con gran libertad',
      'Ocupan posiciones fijas y solo vibran',
      'Están muy juntas pero pueden deslizarse',
      'No se mueven en absoluto',
    ],
    correcta: 0,
    explicacion: 'En el sólido las partículas ocupan posiciones fijas y en el líquido se deslizan manteniéndose unidas. Por eso solo el gas se comprime con facilidad.',
  },
  {
    id: 'qui-006', tema: 'materia', dificultad: 2,
    enunciado: '¿Cuál de estas es una sustancia pura?',
    opciones: ['El oxígeno (O₂)', 'El aire', 'El agua de mar', 'El acero'],
    correcta: 0,
    explicacion: 'El aire, el agua de mar y el acero son mezclas, aunque sean homogéneas. Una sustancia pura tiene composición fija y propiedades constantes.',
  },
  {
    id: 'qui-007', tema: 'materia', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre un elemento y un compuesto?',
    opciones: [
      'El elemento está formado por un solo tipo de átomo y el compuesto por dos o más combinados químicamente',
      'El elemento es sólido y el compuesto líquido',
      'El compuesto se puede separar por filtración',
      'El elemento siempre es un metal',
    ],
    correcta: 0,
    explicacion: 'El agua es un compuesto de hidrógeno y oxígeno, y solo se separa por métodos químicos como la electrólisis, nunca por filtración.',
  },
  {
    id: 'qui-008', tema: 'materia', dificultad: 1,
    enunciado: 'Derretir un cubo de hielo es un cambio:',
    opciones: [
      'Físico, porque sigue siendo agua',
      'Químico, porque cambia de estado',
      'Químico, porque absorbe calor',
      'Nuclear, porque cambian los átomos',
    ],
    correcta: 0,
    explicacion: 'La composición no se altera: H₂O sólida pasa a H₂O líquida. Que absorba calor no lo convierte en un cambio químico.',
  },
  {
    id: 'qui-009', tema: 'materia', dificultad: 2,
    enunciado: 'La ley de conservación de la masa, enunciada por Lavoisier, afirma que en una reacción química:',
    opciones: [
      'La masa total de los reactivos es igual a la masa total de los productos',
      'La masa siempre disminuye porque se libera energía',
      'La masa aumenta al formarse nuevos compuestos',
      'La masa solo se conserva en recipientes abiertos',
    ],
    correcta: 0,
    explicacion: 'Los átomos se reorganizan pero no desaparecen. Si un experimento parece perder masa, casi siempre es porque se escapó un gas.',
  },
  {
    id: 'qui-010', tema: 'materia', dificultad: 3,
    enunciado: 'La densidad es una propiedad intensiva. Eso significa que:',
    opciones: [
      'No depende de la cantidad de sustancia: un gramo y un kilo de hierro tienen la misma densidad',
      'Aumenta cuando aumenta la masa',
      'Solo se puede medir en sólidos',
      'Cambia con la forma del objeto',
    ],
    correcta: 0,
    explicacion: 'La masa y el volumen son propiedades extensivas, porque dependen de cuánta sustancia hay; su cociente, la densidad, no. Por eso sirve para identificar sustancias.',
  },

  // ----- Estructura atómica -----
  {
    id: 'qui-011', tema: 'atomo', dificultad: 1,
    enunciado: '¿Cuáles son las cargas del protón, el neutrón y el electrón?',
    opciones: [
      'Positiva, neutra y negativa',
      'Negativa, neutra y positiva',
      'Positiva, negativa y neutra',
      'Las tres son neutras',
    ],
    correcta: 0,
    explicacion: 'Protones y neutrones están en el núcleo; los electrones ocupan la región externa. La masa del electrón es casi despreciable frente a las otras dos.',
  },
  {
    id: 'qui-012', tema: 'atomo', dificultad: 1,
    enunciado: 'El número atómico (Z) de un elemento indica:',
    opciones: [
      'El número de protones de su núcleo',
      'La suma de protones y neutrones',
      'El número de niveles de energía',
      'La masa del átomo en gramos',
    ],
    correcta: 0,
    explicacion: 'El número atómico define al elemento: cambiarlo lo convierte en otro elemento distinto. La suma de protones y neutrones es el número másico.',
  },
  {
    id: 'qui-013', tema: 'atomo', dificultad: 2,
    enunciado: 'El número másico (A) de un átomo es igual a:',
    opciones: [
      'La suma de protones y neutrones',
      'El número de electrones',
      'La suma de protones y electrones',
      'El número de neutrones únicamente',
    ],
    correcta: 0,
    explicacion: 'Los electrones no se cuentan porque su masa es unas 1 800 veces menor que la de un protón.',
  },
  {
    id: 'qui-014', tema: 'atomo', dificultad: 2,
    enunciado: 'Dos isótopos del mismo elemento se diferencian en:',
    opciones: [
      'El número de neutrones',
      'El número de protones',
      'La carga eléctrica total',
      'El grupo de la tabla periódica al que pertenecen',
    ],
    correcta: 0,
    explicacion: 'Comparten el número atómico, así que son el mismo elemento y tienen las mismas propiedades químicas, pero distinta masa. El carbono 12 y el carbono 14 son isótopos.',
  },
  {
    id: 'qui-015', tema: 'atomo', dificultad: 1,
    enunciado: 'En un átomo eléctricamente neutro:',
    opciones: [
      'El número de protones es igual al de electrones',
      'No hay electrones',
      'El número de neutrones es igual al de protones',
      'La carga del núcleo es cero',
    ],
    correcta: 0,
    explicacion: 'Las cargas positivas y negativas se compensan. Si gana o pierde electrones se convierte en un ion.',
  },
  {
    id: 'qui-016', tema: 'atomo', dificultad: 2,
    enunciado: 'Casi toda la masa de un átomo se concentra en:',
    opciones: ['El núcleo', 'La nube de electrones', 'El último nivel de energía', 'El espacio vacío entre partículas'],
    correcta: 0,
    explicacion: 'El núcleo es diminuto comparado con el átomo completo, pero reúne protones y neutrones. El átomo es, en su mayor parte, espacio vacío.',
  },
  {
    id: 'qui-017', tema: 'atomo', dificultad: 2,
    enunciado: 'Un átomo de sodio tiene número atómico 11 y número másico 23. ¿Cuántos neutrones tiene?',
    opciones: ['12', '11', '23', '34'],
    correcta: 0,
    explicacion: 'Neutrones = A − Z = 23 − 11 = 12.',
  },
  {
    id: 'qui-018', tema: 'atomo', dificultad: 2,
    enunciado: 'Cuando un átomo pierde electrones se convierte en:',
    opciones: [
      'Un catión, con carga positiva',
      'Un anión, con carga negativa',
      'Un isótopo del mismo elemento',
      'Un átomo de otro elemento',
    ],
    correcta: 0,
    explicacion: 'Al perder cargas negativas queda un exceso de positivas. Ganar electrones produce un anión, y en ningún caso cambia el elemento: eso solo pasa si cambian los protones.',
  },
  {
    id: 'qui-019', tema: 'atomo', dificultad: 2,
    enunciado: '¿Cuántos electrones caben como máximo en el primer nivel de energía?',
    opciones: ['2', '8', '18', '1'],
    correcta: 0,
    explicacion: 'El primer nivel admite 2 electrones y el segundo, 8. Por eso el helio, con 2 electrones, ya tiene su nivel completo y es un gas noble.',
  },
  {
    id: 'qui-020', tema: 'atomo', dificultad: 3,
    enunciado: 'El experimento de la lámina de oro de Rutherford permitió concluir que el átomo:',
    opciones: [
      'Tiene un núcleo muy pequeño, denso y positivo, rodeado de espacio casi vacío',
      'Es una esfera maciza de carga positiva uniforme',
      'No contiene partículas con carga',
      'Tiene los electrones en el centro',
    ],
    correcta: 0,
    explicacion: 'La mayoría de las partículas atravesaba la lámina sin desviarse, pero unas pocas rebotaban con fuerza. Eso desmontó el modelo anterior, el del "pudín de pasas" de Thomson.',
  },

  // ----- Tabla periódica -----
  {
    id: 'qui-021', tema: 'tabla-periodica', dificultad: 1,
    enunciado: 'En la tabla periódica actual, los elementos están ordenados por:',
    opciones: [
      'Número atómico creciente',
      'Masa atómica creciente',
      'Orden alfabético de su nombre',
      'Fecha de descubrimiento',
    ],
    correcta: 0,
    explicacion: 'Mendeléyev los ordenó por masa atómica, pero el criterio actual es el número atómico, que resuelve las inconsistencias de aquella primera versión.',
  },
  {
    id: 'qui-022', tema: 'tabla-periodica', dificultad: 2,
    enunciado: 'Los elementos de un mismo grupo (columna) comparten:',
    opciones: [
      'El número de electrones en su último nivel, y por eso propiedades químicas parecidas',
      'El mismo número de niveles de energía',
      'La misma masa atómica',
      'El mismo estado físico',
    ],
    correcta: 0,
    explicacion: 'Los electrones de valencia determinan cómo reacciona un elemento. Compartir el número de niveles es lo que caracteriza a un periodo, no a un grupo.',
  },
  {
    id: 'qui-023', tema: 'tabla-periodica', dificultad: 2,
    enunciado: 'Los elementos de un mismo periodo (fila) comparten:',
    opciones: [
      'El número de niveles de energía ocupados',
      'Las mismas propiedades químicas',
      'La misma valencia',
      'El mismo número de protones',
    ],
    correcta: 0,
    explicacion: 'A lo largo de un periodo las propiedades cambian de forma gradual, de metálicas a no metálicas.',
  },
  {
    id: 'qui-024', tema: 'tabla-periodica', dificultad: 1,
    enunciado: 'Los gases nobles son poco reactivos porque:',
    opciones: [
      'Tienen su último nivel de energía completo',
      'Son muy pesados',
      'No tienen electrones',
      'Se encuentran en estado gaseoso',
    ],
    correcta: 0,
    explicacion: 'Al tener el octeto completo no ganan ni pierden electrones con facilidad. Por eso el helio se usa en globos sin riesgo de que arda.',
  },
  {
    id: 'qui-025', tema: 'tabla-periodica', dificultad: 2,
    enunciado: 'Los metales alcalinos, del grupo 1, se caracterizan por:',
    opciones: [
      'Ser muy reactivos y perder con facilidad su único electrón de valencia',
      'Ser prácticamente inertes',
      'Formar aniones con facilidad',
      'Ser gases a temperatura ambiente',
    ],
    correcta: 0,
    explicacion: 'Sodio y potasio reaccionan violentamente con el agua, así que se guardan sumergidos en aceite.',
  },
  {
    id: 'qui-026', tema: 'tabla-periodica', dificultad: 2,
    enunciado: 'El cloro, el flúor y el yodo pertenecen a la familia de los:',
    opciones: ['Halógenos', 'Gases nobles', 'Metales alcalinos', 'Metales de transición'],
    correcta: 0,
    explicacion: 'Están en el grupo 17, tienen siete electrones de valencia y ganan uno con facilidad para completar el octeto.',
  },
  {
    id: 'qui-027', tema: 'tabla-periodica', dificultad: 3,
    enunciado: 'En la tabla periódica, la electronegatividad en general:',
    opciones: [
      'Aumenta hacia la derecha y hacia arriba',
      'Aumenta hacia la izquierda y hacia abajo',
      'Es la misma en todos los elementos',
      'Solo varía dentro de cada periodo',
    ],
    correcta: 0,
    explicacion: 'El flúor, arriba a la derecha (sin contar los gases nobles), es el elemento más electronegativo. La electronegatividad mide la tendencia a atraer los electrones de un enlace.',
  },
  {
    id: 'qui-028', tema: 'tabla-periodica', dificultad: 3,
    enunciado: 'El radio atómico, dentro de un mismo grupo, al bajar:',
    opciones: [
      'Aumenta, porque se añaden niveles de energía',
      'Disminuye, porque hay más protones',
      'No cambia',
      'Aumenta solo en los metales',
    ],
    correcta: 0,
    explicacion: 'Cada periodo añade una capa. Dentro de un mismo periodo, en cambio, el radio disminuye hacia la derecha porque la carga nuclear atrae más los electrones.',
  },
  {
    id: 'qui-029', tema: 'tabla-periodica', dificultad: 1,
    enunciado: 'En la tabla periódica, los metales se ubican principalmente:',
    opciones: [
      'A la izquierda y en el centro',
      'A la derecha, junto a los gases nobles',
      'Solo en la última fila',
      'Repartidos al azar',
    ],
    correcta: 0,
    explicacion: 'Los no metales quedan arriba a la derecha y entre ambos grupos están los metaloides, con propiedades intermedias, como el silicio.',
  },
  {
    id: 'qui-030', tema: 'tabla-periodica', dificultad: 2,
    enunciado: '¿A qué elementos corresponden los símbolos Na, K y Fe?',
    opciones: [
      'Sodio, potasio y hierro',
      'Nitrógeno, kriptón y flúor',
      'Sodio, kriptón y fósforo',
      'Níquel, potasio y fermio',
    ],
    correcta: 0,
    explicacion: 'Varios símbolos vienen del latín: natrium, kalium y ferrum. Otros casos frecuentes son Ag (plata), Au (oro) y Pb (plomo).',
  },

  // ----- Enlace químico -----
  {
    id: 'qui-031', tema: 'enlace', dificultad: 2,
    enunciado: 'Un enlace iónico se forma característicamente:',
    opciones: [
      'Entre un metal y un no metal, por transferencia de electrones',
      'Entre dos no metales, compartiendo electrones',
      'Entre dos metales, con electrones libres',
      'Entre dos gases nobles',
    ],
    correcta: 0,
    explicacion: 'El metal cede electrones y se vuelve catión; el no metal los recibe y se vuelve anión. La atracción entre las cargas opuestas mantiene unido el compuesto.',
  },
  {
    id: 'qui-032', tema: 'enlace', dificultad: 2,
    enunciado: 'En un enlace covalente, los átomos:',
    opciones: [
      'Comparten pares de electrones',
      'Se transfieren electrones por completo',
      'Intercambian protones',
      'Se unen por atracción magnética',
    ],
    correcta: 0,
    explicacion: 'Es el enlace típico entre no metales, y el que forma las moléculas de agua, oxígeno o metano.',
  },
  {
    id: 'qui-033', tema: 'enlace', dificultad: 1,
    enunciado: 'El cloruro de sodio (NaCl) es un compuesto:',
    opciones: ['Iónico', 'Covalente apolar', 'Metálico', 'Orgánico'],
    correcta: 0,
    explicacion: 'El sodio es un metal y el cloro un no metal: hay transferencia de electrones. Por eso forma una red cristalina con alto punto de fusión.',
  },
  {
    id: 'qui-034', tema: 'enlace', dificultad: 2,
    enunciado: 'El enlace metálico explica por qué los metales:',
    opciones: [
      'Conducen la electricidad y el calor y son maleables',
      'Son frágiles y se rompen con facilidad',
      'No reaccionan con otras sustancias',
      'Tienen puntos de fusión muy bajos',
    ],
    correcta: 0,
    explicacion: 'Los electrones de valencia se mueven libremente entre los cationes, como un mar de electrones: eso transporta carga y permite deformar el material sin romperlo.',
  },
  {
    id: 'qui-035', tema: 'enlace', dificultad: 2,
    enunciado: 'La regla del octeto establece que los átomos tienden a:',
    opciones: [
      'Alcanzar ocho electrones en su último nivel',
      'Tener ocho protones en el núcleo',
      'Formar ocho enlaces como máximo',
      'Repartirse en ocho niveles de energía',
    ],
    correcta: 0,
    explicacion: 'Buscan la configuración estable del gas noble más cercano. El hidrógeno y el helio son la excepción: se estabilizan con dos.',
  },
  {
    id: 'qui-036', tema: 'enlace', dificultad: 3,
    enunciado: 'La molécula de agua es polar porque:',
    opciones: [
      'El oxígeno atrae más los electrones y la molécula tiene forma angular',
      'Contiene hidrógeno, que siempre genera polaridad',
      'Sus enlaces son iónicos',
      'Es una molécula muy pequeña',
    ],
    correcta: 0,
    explicacion: 'Hacen falta las dos condiciones: diferencia de electronegatividad y una geometría que no cancele los dipolos. El CO₂ también tiene enlaces polares, pero al ser lineal la molécula resulta apolar.',
  },
  {
    id: 'qui-037', tema: 'enlace', dificultad: 2,
    enunciado: 'Los compuestos iónicos conducen la electricidad:',
    opciones: [
      'Cuando están disueltos en agua o fundidos, no en estado sólido',
      'Siempre, en cualquier estado',
      'Nunca, porque no tienen electrones libres',
      'Solo en estado sólido',
    ],
    correcta: 0,
    explicacion: 'En el sólido los iones están fijos en la red. Al disolverse o fundirse quedan libres para moverse y transportar la carga.',
  },
  {
    id: 'qui-038', tema: 'enlace', dificultad: 3,
    enunciado: '¿Por qué el agua tiene un punto de ebullición mucho más alto de lo que corresponde a su tamaño molecular?',
    opciones: [
      'Por los puentes de hidrógeno entre sus moléculas',
      'Porque sus enlaces internos son iónicos',
      'Porque es una molécula muy pesada',
      'Porque contiene oxígeno disuelto',
    ],
    correcta: 0,
    explicacion: 'Esas atracciones entre moléculas hay que vencerlas para hervir el agua. Los puentes de hidrógeno explican también por qué el hielo flota y por qué el agua tiene tanta tensión superficial.',
  },
  {
    id: 'qui-039', tema: 'enlace', dificultad: 2,
    enunciado: 'En la molécula de oxígeno (O₂), los dos átomos se unen mediante:',
    opciones: [
      'Un enlace covalente doble',
      'Un enlace iónico',
      'Un enlace metálico',
      'Un puente de hidrógeno',
    ],
    correcta: 0,
    explicacion: 'Cada átomo de oxígeno tiene seis electrones de valencia y necesita dos más: comparten dos pares. Al ser átomos iguales, el enlace es covalente apolar.',
  },
  {
    id: 'qui-040', tema: 'enlace', dificultad: 2,
    enunciado: '¿Por qué el aceite no se mezcla con el agua?',
    opciones: [
      'Porque el aceite es apolar y el agua es polar: lo semejante disuelve a lo semejante',
      'Porque el aceite es menos denso',
      'Porque el aceite es una sustancia pura',
      'Porque el agua está más fría',
    ],
    correcta: 0,
    explicacion: 'La diferencia de densidad explica cuál queda arriba, no por qué no se mezclan. Los jabones funcionan porque tienen una parte polar y otra apolar.',
  },

  // ----- Nomenclatura y fórmulas -----
  {
    id: 'qui-041', tema: 'nomenclatura', dificultad: 1,
    enunciado: '¿Qué compuesto representa la fórmula CO₂?',
    opciones: ['Dióxido de carbono', 'Monóxido de carbono', 'Carbonato de calcio', 'Ácido carbónico'],
    correcta: 0,
    explicacion: 'El prefijo di- indica dos átomos de oxígeno. El monóxido de carbono es CO y es tóxico; el dióxido es el que exhalamos.',
  },
  {
    id: 'qui-042', tema: 'nomenclatura', dificultad: 1,
    enunciado: 'El NaCl se denomina:',
    opciones: ['Cloruro de sodio', 'Clorato de sodio', 'Ácido clorhídrico', 'Hidróxido de sodio'],
    correcta: 0,
    explicacion: 'Es la sal de cocina. El ácido clorhídrico es HCl y el hidróxido de sodio, NaOH.',
  },
  {
    id: 'qui-043', tema: 'nomenclatura', dificultad: 2,
    enunciado: '¿Cuál es el nombre del H₂SO₄?',
    opciones: ['Ácido sulfúrico', 'Ácido sulfuroso', 'Sulfato de hidrógeno', 'Ácido clorhídrico'],
    correcta: 0,
    explicacion: 'Es uno de los ácidos más usados en la industria. El ácido sulfuroso es H₂SO₃, con un oxígeno menos.',
  },
  {
    id: 'qui-044', tema: 'nomenclatura', dificultad: 2,
    enunciado: 'El calcio actúa con valencia 2 y el oxígeno con valencia 2. ¿Cuál es la fórmula del óxido de calcio?',
    opciones: ['CaO', 'Ca₂O', 'CaO₂', 'Ca₂O₂'],
    correcta: 0,
    explicacion: 'Al tener la misma valencia, los subíndices se simplifican y queda uno de cada átomo.',
  },
  {
    id: 'qui-045', tema: 'nomenclatura', dificultad: 2,
    enunciado: 'El NaOH es:',
    opciones: [
      'Hidróxido de sodio, una base',
      'Un ácido fuerte',
      'Una sal neutra',
      'Un óxido metálico',
    ],
    correcta: 0,
    explicacion: 'El grupo OH⁻ caracteriza a los hidróxidos, que son bases. Se conoce como soda cáustica.',
  },
  {
    id: 'qui-046', tema: 'nomenclatura', dificultad: 2,
    enunciado: '¿Cuántos átomos de oxígeno hay en una molécula de H₂SO₄?',
    opciones: ['4', '2', '1', '7'],
    correcta: 0,
    explicacion: 'El subíndice que sigue a un símbolo indica cuántos átomos de ese elemento hay: cuatro oxígenos, dos hidrógenos y un azufre.',
  },
  {
    id: 'qui-047', tema: 'nomenclatura', dificultad: 2,
    enunciado: '¿Cuántos átomos en total tiene una unidad de CaCO₃?',
    opciones: ['5', '3', '6', '4'],
    correcta: 0,
    explicacion: 'Un calcio, un carbono y tres oxígenos: 1 + 1 + 3 = 5 átomos.',
  },
  {
    id: 'qui-048', tema: 'nomenclatura', dificultad: 3,
    enunciado: 'En la expresión 2 H₂O, ¿cuántos átomos de hidrógeno hay en total?',
    opciones: ['4', '2', '6', '3'],
    correcta: 0,
    explicacion: 'El coeficiente 2 multiplica toda la fórmula: 2 × 2 hidrógenos = 4. También hay 2 átomos de oxígeno.',
    pista: 'El coeficiente va delante y afecta a toda la molécula; el subíndice solo al átomo que lo precede.',
  },
  {
    id: 'qui-049', tema: 'nomenclatura', dificultad: 1,
    enunciado: 'El ácido clorhídrico, presente en el jugo gástrico, tiene la fórmula:',
    opciones: ['HCl', 'NaCl', 'HClO', 'Cl₂'],
    correcta: 0,
    explicacion: 'Los hidrácidos combinan hidrógeno con un no metal y no llevan oxígeno.',
  },
  {
    id: 'qui-050', tema: 'nomenclatura', dificultad: 2,
    enunciado: '¿Qué compuesto corresponde a la fórmula NH₃?',
    opciones: ['Amoniaco', 'Ácido nítrico', 'Nitrato de amonio', 'Óxido de nitrógeno'],
    correcta: 0,
    explicacion: 'Un nitrógeno con tres hidrógenos. Se usa en fertilizantes y en productos de limpieza.',
  },

  // ----- Reacciones químicas -----
  {
    id: 'qui-051', tema: 'reacciones', dificultad: 1,
    enunciado: 'En una ecuación química, las sustancias que están a la izquierda de la flecha son:',
    opciones: ['Los reactivos', 'Los productos', 'Los catalizadores', 'Los precipitados'],
    correcta: 0,
    explicacion: 'La flecha se lee como "produce" o "da lugar a": reactivos a la izquierda, productos a la derecha.',
  },
  {
    id: 'qui-052', tema: 'reacciones', dificultad: 2,
    enunciado: '¿Por qué hay que balancear una ecuación química?',
    opciones: [
      'Para que se cumpla la conservación de la masa: el mismo número de átomos de cada elemento a ambos lados',
      'Para que la reacción sea más rápida',
      'Para que los productos sean más puros',
      'Para que la reacción libere energía',
    ],
    correcta: 0,
    explicacion: 'Balancear es contabilidad de átomos: no se crean ni se destruyen. Solo se pueden ajustar los coeficientes, nunca los subíndices.',
  },
  {
    id: 'qui-053', tema: 'reacciones', dificultad: 2,
    enunciado: 'Balancea: ___ H₂ + ___ O₂ → ___ H₂O. Los coeficientes correctos son:',
    opciones: ['2, 1, 2', '1, 1, 1', '2, 2, 2', '1, 2, 1'],
    correcta: 0,
    explicacion: 'Con 2 H₂ hay 4 hidrógenos y con 1 O₂ hay 2 oxígenos, que forman exactamente 2 H₂O. Así quedan 4 H y 2 O a cada lado.',
  },
  {
    id: 'qui-054', tema: 'reacciones', dificultad: 2,
    enunciado: 'Una reacción del tipo AB → A + B se clasifica como:',
    opciones: ['Descomposición', 'Síntesis', 'Sustitución simple', 'Doble sustitución'],
    correcta: 0,
    explicacion: 'Un compuesto se separa en sustancias más simples. La síntesis es la reacción inversa: A + B → AB.',
  },
  {
    id: 'qui-055', tema: 'reacciones', dificultad: 2,
    enunciado: 'En la combustión completa de un hidrocarburo se obtiene:',
    opciones: [
      'Dióxido de carbono y agua',
      'Monóxido de carbono y hidrógeno',
      'Carbono sólido y oxígeno',
      'Solamente calor, sin productos nuevos',
    ],
    correcta: 0,
    explicacion: 'Si el oxígeno es insuficiente, la combustión es incompleta y aparecen monóxido de carbono y hollín. El monóxido es el gas que hace peligrosos los calentadores mal ventilados.',
  },
  {
    id: 'qui-056', tema: 'reacciones', dificultad: 2,
    enunciado: 'Una reacción exotérmica es aquella que:',
    opciones: [
      'Libera energía, normalmente en forma de calor',
      'Absorbe energía del entorno',
      'No intercambia energía',
      'Solo ocurre a altas temperaturas',
    ],
    correcta: 0,
    explicacion: 'La combustión y la neutralización son exotérmicas. Las endotérmicas, como las de las bolsas de frío instantáneo, enfrían su entorno.',
  },
  {
    id: 'qui-057', tema: 'reacciones', dificultad: 3,
    enunciado: 'Un catalizador en una reacción química:',
    opciones: [
      'Aumenta la velocidad de la reacción sin consumirse en ella',
      'Aumenta la cantidad de producto que se obtiene al final',
      'Se transforma en uno de los productos',
      'Solo funciona en reacciones exotérmicas',
    ],
    correcta: 0,
    explicacion: 'Ofrece un camino con menor energía de activación. No cambia cuánto producto se forma, solo cuán rápido. Las enzimas son los catalizadores del cuerpo.',
  },
  {
    id: 'qui-058', tema: 'reacciones', dificultad: 2,
    enunciado: '¿Cuál de estos factores NO aumenta la velocidad de una reacción química?',
    opciones: [
      'Disminuir la temperatura',
      'Aumentar la concentración de los reactivos',
      'Pulverizar un reactivo sólido',
      'Añadir un catalizador',
    ],
    correcta: 0,
    explicacion: 'Bajar la temperatura reduce la frecuencia y la energía de los choques entre partículas: por eso la comida se conserva en la nevera.',
  },
  {
    id: 'qui-059', tema: 'reacciones', dificultad: 3,
    enunciado: 'En una reacción de oxidación-reducción, oxidarse significa:',
    opciones: [
      'Perder electrones',
      'Ganar electrones',
      'Combinarse necesariamente con oxígeno',
      'Aumentar de masa',
    ],
    correcta: 0,
    explicacion: 'El nombre viene de las reacciones con oxígeno, pero la definición moderna es la pérdida de electrones. Lo que se oxida cede electrones a lo que se reduce, y las dos cosas ocurren a la vez.',
  },
  {
    id: 'qui-060', tema: 'reacciones', dificultad: 2,
    enunciado: '¿Cuál de estas NO es evidencia de que ocurrió una reacción química?',
    opciones: [
      'Que la mezcla cambie de forma al agitarla',
      'Que se forme un precipitado',
      'Que se desprenda un gas',
      'Que cambie el color de manera permanente',
    ],
    correcta: 0,
    explicacion: 'Agitar cambia la disposición, no la identidad de las sustancias. Precipitados, gases, cambios de color permanentes y variaciones de temperatura sí son indicios.',
  },

  // ----- Estequiometría -----
  {
    id: 'qui-061', tema: 'estequiometria', dificultad: 2,
    enunciado: 'Un mol de cualquier sustancia contiene:',
    opciones: [
      '6,022 × 10²³ partículas',
      '1 gramo de sustancia',
      '100 partículas',
      '22,4 partículas',
    ],
    correcta: 0,
    explicacion: 'Es el número de Avogadro. El valor 22,4 corresponde a los litros que ocupa un mol de gas ideal en condiciones normales.',
  },
  {
    id: 'qui-062', tema: 'estequiometria', dificultad: 2,
    enunciado: 'Con H = 1 y O = 16, ¿cuál es la masa molar del agua (H₂O)?',
    opciones: ['18 g/mol', '17 g/mol', '34 g/mol', '16 g/mol'],
    correcta: 0,
    explicacion: '2 × 1 + 16 = 18 g/mol.',
  },
  {
    id: 'qui-063', tema: 'estequiometria', dificultad: 2,
    enunciado: '¿Cuántos moles hay en 36 g de agua? (masa molar 18 g/mol)',
    opciones: ['2 mol', '0,5 mol', '18 mol', '36 mol'],
    correcta: 0,
    explicacion: 'n = masa ÷ masa molar = 36 ÷ 18 = 2 mol.',
  },
  {
    id: 'qui-064', tema: 'estequiometria', dificultad: 2,
    enunciado: 'Con C = 12 y O = 16, ¿cuál es la masa molar del CO₂?',
    opciones: ['44 g/mol', '28 g/mol', '40 g/mol', '56 g/mol'],
    correcta: 0,
    explicacion: '12 + 2(16) = 12 + 32 = 44 g/mol.',
  },
  {
    id: 'qui-065', tema: 'estequiometria', dificultad: 3,
    enunciado: 'En la reacción 2 H₂ + O₂ → 2 H₂O, ¿cuántos moles de O₂ se necesitan para consumir 4 moles de H₂?',
    opciones: ['2 mol', '4 mol', '8 mol', '1 mol'],
    correcta: 0,
    explicacion: 'La relación es 2 : 1, así que 4 moles de H₂ requieren 2 de O₂. Los coeficientes de la ecuación balanceada son la receta de la reacción.',
  },
  {
    id: 'qui-066', tema: 'estequiometria', dificultad: 3,
    enunciado: 'El reactivo límite de una reacción es:',
    opciones: [
      'El que se agota primero y determina cuánto producto se obtiene',
      'El que sobra al final de la reacción',
      'El que tiene mayor masa molar',
      'El que se añade en último lugar',
    ],
    correcta: 0,
    explicacion: 'Si hay pan para diez sándwiches y queso para cuatro, se hacen cuatro: el queso es el reactivo límite y el pan, el reactivo en exceso.',
  },
  {
    id: 'qui-067', tema: 'estequiometria', dificultad: 2,
    enunciado: '¿Cuál es la masa de 3 moles de NaCl, si su masa molar es 58,5 g/mol?',
    opciones: ['175,5 g', '58,5 g', '19,5 g', '61,5 g'],
    correcta: 0,
    explicacion: 'masa = n × masa molar = 3 × 58,5 = 175,5 g.',
  },
  {
    id: 'qui-068', tema: 'estequiometria', dificultad: 2,
    enunciado: 'En la ecuación N₂ + 3 H₂ → 2 NH₃, la relación molar entre H₂ y NH₃ es:',
    opciones: ['3 a 2', '1 a 1', '2 a 3', '3 a 1'],
    correcta: 0,
    explicacion: 'Se leen directamente los coeficientes: por cada 3 moles de hidrógeno se producen 2 de amoniaco.',
  },
  {
    id: 'qui-069', tema: 'estequiometria', dificultad: 2,
    enunciado: '¿Cuántas moléculas hay en 2 moles de una sustancia?',
    opciones: [
      'Aproximadamente 1,2 × 10²⁴',
      'Aproximadamente 6,022 × 10²³',
      'Exactamente 2',
      'Aproximadamente 3 × 10²³',
    ],
    correcta: 0,
    explicacion: '2 × 6,022 × 10²³ = 1,2044 × 10²⁴ moléculas.',
  },
  {
    id: 'qui-070', tema: 'estequiometria', dificultad: 3,
    enunciado: 'Una reacción debería producir 50 g de producto, pero en el laboratorio se obtienen 40 g. El rendimiento porcentual es:',
    opciones: ['80 %', '125 %', '10 %', '20 %'],
    correcta: 0,
    explicacion: 'Rendimiento = real ÷ teórico × 100 = 40 ÷ 50 × 100 = 80 %. Las pérdidas por manipulación y las reacciones incompletas explican la diferencia.',
  },

  // ----- Soluciones -----
  {
    id: 'qui-071', tema: 'soluciones', dificultad: 1,
    enunciado: 'En una solución de azúcar en agua:',
    opciones: [
      'El azúcar es el soluto y el agua el solvente',
      'El agua es el soluto y el azúcar el solvente',
      'Los dos son solventes',
      'No hay soluto porque el azúcar desaparece',
    ],
    correcta: 0,
    explicacion: 'El solvente es el componente que está en mayor proporción y el soluto, el que se dispersa en él.',
  },
  {
    id: 'qui-072', tema: 'soluciones', dificultad: 2,
    enunciado: 'Se disuelven 0,5 moles de soluto en 2 litros de solución. ¿Cuál es la molaridad?',
    opciones: ['0,25 M', '1 M', '4 M', '2,5 M'],
    correcta: 0,
    explicacion: 'M = moles ÷ litros = 0,5 ÷ 2 = 0,25 mol/L.',
  },
  {
    id: 'qui-073', tema: 'soluciones', dificultad: 2,
    enunciado: 'Una solución contiene 20 g de soluto en 100 g de solución. Su concentración en porcentaje masa/masa es:',
    opciones: ['20 %', '25 %', '80 %', '2 %'],
    correcta: 0,
    explicacion: '20 ÷ 100 × 100 = 20 %. Ojo: son 100 g de solución, no de solvente; el solvente aporta los otros 80 g.',
  },
  {
    id: 'qui-074', tema: 'soluciones', dificultad: 2,
    enunciado: 'Al añadir más solvente a una solución sin cambiar la cantidad de soluto:',
    opciones: [
      'La concentración disminuye: la solución se diluye',
      'La concentración aumenta',
      'La concentración no cambia',
      'El soluto precipita',
    ],
    correcta: 0,
    explicacion: 'La misma cantidad de soluto queda repartida en más volumen. Los moles de soluto se conservan, y de ahí sale la fórmula de dilución.',
  },
  {
    id: 'qui-075', tema: 'soluciones', dificultad: 2,
    enunciado: 'Una solución saturada es aquella que:',
    opciones: [
      'Contiene la máxima cantidad de soluto que puede disolver a esa temperatura',
      'Tiene muy poco soluto',
      'Ya no es una mezcla homogénea',
      'Contiene dos solutos distintos',
    ],
    correcta: 0,
    explicacion: 'Si se añade más soluto, queda sin disolver en el fondo. Al calentar suele poder disolverse más.',
  },
  {
    id: 'qui-076', tema: 'soluciones', dificultad: 2,
    enunciado: 'En general, la solubilidad de un sólido en agua al aumentar la temperatura:',
    opciones: ['Aumenta', 'Disminuye', 'No cambia', 'Se vuelve cero'],
    correcta: 0,
    explicacion: 'Por eso el azúcar se disuelve mejor en café caliente. Con los gases ocurre lo contrario.',
  },
  {
    id: 'qui-077', tema: 'soluciones', dificultad: 3,
    enunciado: '¿Por qué una gaseosa tibia pierde el gas más rápido que una fría?',
    opciones: [
      'Porque la solubilidad de los gases disminuye al aumentar la temperatura',
      'Porque el azúcar se disuelve mejor en caliente',
      'Porque el envase se dilata',
      'Porque el CO₂ reacciona con el agua al calentarse',
    ],
    correcta: 0,
    explicacion: 'Los gases se comportan al revés que los sólidos. El mismo fenómeno explica por qué el agua caliente de un río retiene menos oxígeno disuelto y afecta a los peces.',
  },
  {
    id: 'qui-078', tema: 'soluciones', dificultad: 2,
    enunciado: '¿Cuántos moles de soluto hay en 0,5 L de una solución 2 M?',
    opciones: ['1 mol', '4 mol', '0,25 mol', '2,5 mol'],
    correcta: 0,
    explicacion: 'n = M × V = 2 × 0,5 = 1 mol.',
  },
  {
    id: 'qui-079', tema: 'soluciones', dificultad: 3,
    enunciado: '¿Qué diferencia a un coloide, como la leche, de una solución verdadera?',
    opciones: [
      'Sus partículas son más grandes y dispersan la luz, aunque no se sedimentan',
      'Sus partículas se separan al dejarlo en reposo',
      'No tiene soluto ni solvente',
      'Siempre es de color blanco',
    ],
    correcta: 0,
    explicacion: 'La dispersión de la luz se llama efecto Tyndall y es lo que hace visible el haz de una linterna en la niebla. En una solución verdadera el haz no se ve.',
  },
  {
    id: 'qui-080', tema: 'soluciones', dificultad: 2,
    enunciado: 'Al agua se le llama solvente universal porque:',
    opciones: [
      'Su polaridad le permite disolver una gran cantidad de sustancias',
      'Disuelve absolutamente todas las sustancias conocidas',
      'Es el líquido más abundante del planeta',
      'No reacciona con ninguna sustancia',
    ],
    correcta: 0,
    explicacion: 'El nombre es una exageración útil: no disuelve las sustancias apolares, como los aceites. Su capacidad viene de que sus moléculas polares rodean a los iones y los separan.',
  },

  // ----- Ácidos, bases y pH -----
  {
    id: 'qui-081', tema: 'acidos-bases', dificultad: 1,
    enunciado: 'En la escala de pH, una sustancia con pH 4 es:',
    opciones: ['Ácida', 'Básica', 'Neutra', 'Imposible de medir'],
    correcta: 0,
    explicacion: 'Por debajo de 7 es ácida, exactamente 7 es neutra y por encima de 7 es básica o alcalina.',
  },
  {
    id: 'qui-082', tema: 'acidos-bases', dificultad: 3,
    enunciado: '¿Cuántas veces más ácida es una sustancia de pH 3 que una de pH 5?',
    opciones: ['100 veces', '2 veces', '10 veces', '1 000 veces'],
    correcta: 0,
    explicacion: 'La escala es logarítmica: cada unidad de pH equivale a un factor de 10, así que dos unidades son 10² = 100 veces más concentración de iones H⁺.',
    pista: 'Cada punto de pH multiplica o divide por diez.',
  },
  {
    id: 'qui-083', tema: 'acidos-bases', dificultad: 2,
    enunciado: 'La reacción entre un ácido y una base produce:',
    opciones: ['Una sal y agua', 'Un óxido y un gas', 'Dos ácidos más débiles', 'Un precipitado metálico'],
    correcta: 0,
    explicacion: 'Es la neutralización: el H⁺ del ácido y el OH⁻ de la base forman agua, y los iones restantes forman la sal.',
  },
  {
    id: 'qui-084', tema: 'acidos-bases', dificultad: 1,
    enunciado: '¿Para qué sirve el papel tornasol o la fenolftaleína?',
    opciones: [
      'Para indicar con un cambio de color si una sustancia es ácida o básica',
      'Para medir la temperatura de una solución',
      'Para filtrar impurezas',
      'Para acelerar una reacción',
    ],
    correcta: 0,
    explicacion: 'Son indicadores ácido-base. Dan una lectura cualitativa; para un valor numérico se usa un pH-metro.',
  },
  {
    id: 'qui-085', tema: 'acidos-bases', dificultad: 2,
    enunciado: 'Según Arrhenius, un ácido es una sustancia que en solución acuosa:',
    opciones: [
      'Libera iones hidrógeno (H⁺)',
      'Libera iones hidroxilo (OH⁻)',
      'No se disocia',
      'Neutraliza cualquier sal',
    ],
    correcta: 0,
    explicacion: 'Las bases, en cambio, liberan OH⁻. Es la definición más sencilla de las varias que existen.',
  },
  {
    id: 'qui-086', tema: 'acidos-bases', dificultad: 2,
    enunciado: '¿Cuál de estas sustancias es una base?',
    opciones: ['El hidróxido de magnesio', 'El vinagre', 'El jugo de limón', 'El ácido sulfúrico'],
    correcta: 0,
    explicacion: 'Los hidróxidos son bases. El vinagre contiene ácido acético y el limón, ácido cítrico.',
  },
  {
    id: 'qui-087', tema: 'acidos-bases', dificultad: 2,
    enunciado: 'El jugo gástrico del estómago tiene un pH cercano a 2. Eso significa que es:',
    opciones: [
      'Fuertemente ácido',
      'Ligeramente básico',
      'Neutro',
      'Fuertemente básico',
    ],
    correcta: 0,
    explicacion: 'Esa acidez ayuda a digerir las proteínas y a eliminar microorganismos. La mucosa gástrica protege la pared del estómago de su propio ácido.',
  },
  {
    id: 'qui-088', tema: 'acidos-bases', dificultad: 2,
    enunciado: '¿Por qué el bicarbonato de sodio alivia la acidez estomacal?',
    opciones: [
      'Porque es una sustancia básica que neutraliza parte del ácido',
      'Porque diluye el contenido del estómago',
      'Porque aumenta la producción de jugo gástrico',
      'Porque recubre la pared del estómago con una capa aislante',
    ],
    correcta: 0,
    explicacion: 'La reacción produce además dióxido de carbono, que es la causa del eructo característico.',
  },
  {
    id: 'qui-089', tema: 'acidos-bases', dificultad: 2,
    enunciado: 'El agua pura a temperatura ambiente tiene un pH de:',
    opciones: ['7', '0', '14', '1'],
    correcta: 0,
    explicacion: 'Es el punto neutro de la escala: igual concentración de iones H⁺ y OH⁻. El agua de lluvia normal es ligeramente ácida por el CO₂ disuelto.',
  },
  {
    id: 'qui-090', tema: 'acidos-bases', dificultad: 3,
    enunciado: 'Se considera lluvia ácida la que tiene un pH claramente menor de 5,6. La causan principalmente:',
    opciones: [
      'Los óxidos de azufre y de nitrógeno emitidos por industrias y vehículos',
      'El exceso de oxígeno en la atmósfera',
      'El vapor de agua de los océanos',
      'Los gases refrigerantes',
    ],
    correcta: 0,
    explicacion: 'Esos óxidos reaccionan con el agua atmosférica y forman ácido sulfúrico y nítrico. Los gases refrigerantes afectan a la capa de ozono, que es otro problema.',
  },

  // ----- Química orgánica -----
  {
    id: 'qui-091', tema: 'organica', dificultad: 1,
    enunciado: 'La química orgánica estudia principalmente los compuestos que contienen:',
    opciones: ['Carbono', 'Hierro', 'Silicio', 'Sodio'],
    correcta: 0,
    explicacion: 'El carbono forma cadenas largas y estables, lo que permite una variedad de compuestos que ningún otro elemento alcanza.',
  },
  {
    id: 'qui-092', tema: 'organica', dificultad: 2,
    enunciado: '¿Cuántos enlaces covalentes forma normalmente un átomo de carbono?',
    opciones: ['4', '2', '6', '1'],
    correcta: 0,
    explicacion: 'Tiene cuatro electrones de valencia y necesita cuatro más para completar el octeto. Esa tetravalencia es la base de toda la química orgánica.',
  },
  {
    id: 'qui-093', tema: 'organica', dificultad: 1,
    enunciado: 'Un hidrocarburo es un compuesto formado únicamente por:',
    opciones: ['Carbono e hidrógeno', 'Carbono y oxígeno', 'Hidrógeno y oxígeno', 'Carbono y nitrógeno'],
    correcta: 0,
    explicacion: 'El petróleo y el gas natural son mezclas de hidrocarburos, y de ahí salen los combustibles y los plásticos.',
  },
  {
    id: 'qui-094', tema: 'organica', dificultad: 2,
    enunciado: '¿Cuál es la fórmula del metano, el hidrocarburo más simple?',
    opciones: ['CH₄', 'C₂H₆', 'CH₃', 'CO₂'],
    correcta: 0,
    explicacion: 'Un carbono unido a cuatro hidrógenos. Es el componente principal del gas natural y un gas de efecto invernadero potente.',
  },
  {
    id: 'qui-095', tema: 'organica', dificultad: 2,
    enunciado: '¿Qué distingue a un alqueno de un alcano?',
    opciones: [
      'El alqueno tiene al menos un enlace doble entre carbonos',
      'El alqueno no contiene hidrógeno',
      'El alcano tiene un triple enlace',
      'El alqueno siempre es un gas',
    ],
    correcta: 0,
    explicacion: 'Alcanos solo con enlaces simples, alquenos con al menos uno doble y alquinos con al menos uno triple.',
  },
  {
    id: 'qui-096', tema: 'organica', dificultad: 2,
    enunciado: 'El grupo funcional −OH unido a una cadena de carbonos caracteriza a los:',
    opciones: ['Alcoholes', 'Ácidos carboxílicos', 'Aldehídos', 'Éteres'],
    correcta: 0,
    explicacion: 'El grupo de los ácidos carboxílicos es −COOH. El grupo funcional es lo que determina las propiedades químicas de la molécula.',
  },
  {
    id: 'qui-097', tema: 'organica', dificultad: 2,
    enunciado: 'El alcohol presente en las bebidas alcohólicas es:',
    opciones: ['El etanol', 'El metanol', 'El glicerol', 'El fenol'],
    correcta: 0,
    explicacion: 'El metanol es tóxico y puede causar ceguera o la muerte: por eso el licor adulterado es tan peligroso.',
  },
  {
    id: 'qui-098', tema: 'organica', dificultad: 2,
    enunciado: '¿Cuáles son las cuatro grandes familias de biomoléculas?',
    opciones: [
      'Carbohidratos, lípidos, proteínas y ácidos nucleicos',
      'Ácidos, bases, sales y óxidos',
      'Metales, no metales, gases nobles y metaloides',
      'Alcanos, alquenos, alquinos y aromáticos',
    ],
    correcta: 0,
    explicacion: 'Todas son compuestos orgánicos construidos sobre esqueletos de carbono, y cumplen funciones de energía, estructura, catálisis e información.',
  },
  {
    id: 'qui-099', tema: 'organica', dificultad: 3,
    enunciado: 'Un polímero es una molécula formada por:',
    opciones: [
      'Muchas unidades pequeñas repetidas, llamadas monómeros',
      'Dos átomos de carbono unidos por triple enlace',
      'Una mezcla homogénea de dos plásticos',
      'Un metal recubierto de plástico',
    ],
    correcta: 0,
    explicacion: 'Los plásticos son polímeros sintéticos, pero también lo son el almidón, la celulosa y las proteínas, que son polímeros naturales.',
  },
  {
    id: 'qui-100', tema: 'organica', dificultad: 3,
    enunciado: 'Dos compuestos isómeros son aquellos que:',
    opciones: [
      'Tienen la misma fórmula molecular pero distinta estructura y, por tanto, distintas propiedades',
      'Tienen la misma estructura y distinta fórmula',
      'Son el mismo compuesto con dos nombres',
      'Se diferencian solo en su masa molar',
    ],
    correcta: 0,
    explicacion: 'La isomería explica por qué el carbono genera tantísimos compuestos: con los mismos átomos se pueden armar moléculas distintas que se comportan de manera diferente.',
  },
];
