/**
 * salud.js — Banco de biología y salud.
 *
 * Cubre el componente biológico de la prueba de ciencias naturales —célula,
 * genética, ecología, evolución, biodiversidad e indagación científica— y la
 * educación para la salud, que es lo que preguntan con más frecuencia las
 * carreras del área y lo que además sirve fuera del examen: prevención,
 * primeros auxilios, nutrición y salud mental.
 *
 * Aquí se explican conceptos, no se receta nada: ante un síntoma real, el
 * destino es un profesional de salud, no un banco de preguntas.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const SALUD = [
  // ----- Sistemas del cuerpo humano -----
  {
    id: 'sal-001', tema: 'cuerpo-sistemas', dificultad: 1,
    enunciado: '¿Cuál es la función principal del sistema circulatorio?',
    opciones: [
      'Transportar oxígeno, nutrientes, hormonas y desechos por todo el cuerpo',
      'Producir las hormonas que regulan el crecimiento',
      'Filtrar la sangre y formar la orina',
      'Absorber los nutrientes de los alimentos',
    ],
    correcta: 0,
    explicacion: 'El corazón bombea y los vasos distribuyen. Filtrar la sangre le corresponde a los riñones y absorber nutrientes, al intestino delgado.',
  },
  {
    id: 'sal-002', tema: 'cuerpo-sistemas', dificultad: 1,
    enunciado: '¿En qué estructura de los pulmones ocurre el intercambio de oxígeno y dióxido de carbono?',
    opciones: ['En los alvéolos', 'En la tráquea', 'En los bronquios', 'En la laringe'],
    correcta: 0,
    explicacion: 'Los alvéolos son sacos minúsculos rodeados de capilares: su pared finísima permite que el oxígeno pase a la sangre y el dióxido de carbono salga. El resto son vías de conducción del aire.',
  },
  {
    id: 'sal-003', tema: 'cuerpo-sistemas', dificultad: 2,
    enunciado: '¿En qué parte del aparato digestivo se absorbe la mayor parte de los nutrientes?',
    opciones: ['En el intestino delgado', 'En el estómago', 'En el intestino grueso', 'En el esófago'],
    correcta: 0,
    explicacion: 'Sus vellosidades multiplican enormemente la superficie de absorción. En el estómago hay sobre todo digestión química y en el intestino grueso se absorben agua y sales.',
  },
  {
    id: 'sal-004', tema: 'cuerpo-sistemas', dificultad: 2,
    enunciado: '¿Qué órgano produce la bilis, necesaria para digerir las grasas?',
    opciones: ['El hígado', 'La vesícula biliar', 'El páncreas', 'El estómago'],
    correcta: 0,
    explicacion: 'El hígado la produce y la vesícula solo la almacena y la libera cuando llega el alimento. El páncreas aporta otras enzimas digestivas.',
  },
  {
    id: 'sal-005', tema: 'cuerpo-sistemas', dificultad: 2,
    enunciado: 'La función principal de los riñones es:',
    opciones: [
      'Filtrar la sangre, eliminar desechos y regular el agua y las sales del organismo',
      'Producir los glóbulos rojos',
      'Almacenar la orina hasta su expulsión',
      'Neutralizar los ácidos del estómago',
    ],
    correcta: 0,
    explicacion: 'Filtran unos 180 litros de sangre al día y devuelven casi todo: lo que sobra sale como orina. Almacenarla es tarea de la vejiga.',
  },
  {
    id: 'sal-006', tema: 'cuerpo-sistemas', dificultad: 2,
    enunciado: 'El sistema nervioso central está formado por:',
    opciones: [
      'El encéfalo y la médula espinal',
      'Los nervios que recorren brazos y piernas',
      'El cerebro y el corazón',
      'Las neuronas sensoriales de la piel',
    ],
    correcta: 0,
    explicacion: 'Los nervios que salen hacia el resto del cuerpo forman el sistema nervioso periférico, que lleva información hacia el centro y órdenes de vuelta.',
  },
  {
    id: 'sal-007', tema: 'cuerpo-sistemas', dificultad: 2,
    enunciado: '¿Qué hormonas produce el páncreas para regular la glucosa en la sangre?',
    opciones: [
      'Insulina y glucagón',
      'Adrenalina y cortisol',
      'Estrógeno y testosterona',
      'Tiroxina y calcitonina',
    ],
    correcta: 0,
    explicacion: 'La insulina hace que la glucosa entre a las células y baja su nivel en sangre; el glucagón hace lo contrario. Cuando ese equilibrio falla aparece la diabetes.',
  },
  {
    id: 'sal-008', tema: 'cuerpo-sistemas', dificultad: 2,
    enunciado: 'Por definición, una arteria es un vaso que:',
    opciones: [
      'Lleva sangre desde el corazón hacia los tejidos',
      'Siempre transporta sangre rica en oxígeno',
      'Lleva sangre desde los tejidos hacia el corazón',
      'Conecta directamente un capilar con otro',
    ],
    correcta: 0,
    explicacion: 'La definición es por la dirección del flujo, no por el contenido de oxígeno. Las venas son las que regresan la sangre al corazón.',
  },
  {
    id: 'sal-009', tema: 'cuerpo-sistemas', dificultad: 3,
    enunciado: '¿Por qué la arteria pulmonar transporta sangre pobre en oxígeno, si las arterias suelen llevar sangre oxigenada?',
    opciones: [
      'Porque va del corazón hacia los pulmones, justamente a recoger oxígeno',
      'Porque en realidad es una vena mal nombrada',
      'Porque el oxígeno se consume dentro del propio vaso',
      'Porque solo lleva sangre pobre en oxígeno durante el ejercicio',
    ],
    correcta: 0,
    explicacion: 'Es la excepción que confirma la definición: arteria significa que sale del corazón. Sale del ventrículo derecho con sangre venosa y regresa oxigenada por las venas pulmonares, la otra excepción.',
    pista: 'La definición depende de la dirección, no del color de la sangre.',
  },
  {
    id: 'sal-010', tema: 'cuerpo-sistemas', dificultad: 2,
    enunciado: '¿Cuál es la función de los glóbulos blancos o leucocitos?',
    opciones: [
      'Defender al organismo frente a infecciones y sustancias extrañas',
      'Transportar el oxígeno por la sangre',
      'Formar coágulos para detener las hemorragias',
      'Producir las hormonas del crecimiento',
    ],
    correcta: 0,
    explicacion: 'Los glóbulos rojos transportan oxígeno gracias a la hemoglobina y las plaquetas participan en la coagulación.',
  },

  // ----- Célula, herencia y genética -----
  {
    id: 'sal-011', tema: 'celula-genetica', dificultad: 1,
    enunciado: 'La unidad estructural y funcional básica de todos los seres vivos es:',
    opciones: ['La célula', 'El tejido', 'El órgano', 'La molécula de ADN'],
    correcta: 0,
    explicacion: 'Es uno de los postulados de la teoría celular: todo ser vivo está formado por células y toda célula proviene de otra célula.',
  },
  {
    id: 'sal-012', tema: 'celula-genetica', dificultad: 2,
    enunciado: '¿Cuál es la función de las mitocondrias?',
    opciones: [
      'Obtener energía para la célula mediante la respiración celular',
      'Guardar la información genética',
      'Fabricar las proteínas a partir del ARN',
      'Digerir sustancias de desecho dentro de la célula',
    ],
    correcta: 0,
    explicacion: 'Convierten los nutrientes y el oxígeno en ATP, la moneda energética celular. Las proteínas se fabrican en los ribosomas y la digestión intracelular ocurre en los lisosomas.',
  },
  {
    id: 'sal-013', tema: 'celula-genetica', dificultad: 1,
    enunciado: 'El ADN de las células humanas se encuentra principalmente en:',
    opciones: ['El núcleo', 'El citoplasma', 'La membrana celular', 'El aparato de Golgi'],
    correcta: 0,
    explicacion: 'Está organizado en cromosomas dentro del núcleo. También existe una pequeña cantidad de ADN propio dentro de las mitocondrias.',
  },
  {
    id: 'sal-014', tema: 'celula-genetica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia esencial entre mitosis y meiosis?',
    opciones: [
      'La mitosis produce células idénticas a la original y la meiosis produce gametos con la mitad de los cromosomas',
      'La mitosis solo ocurre en los animales y la meiosis en las plantas',
      'La mitosis ocurre en el núcleo y la meiosis en el citoplasma',
      'La mitosis produce dos células y la meiosis, una sola',
    ],
    correcta: 0,
    explicacion: 'La mitosis sirve para crecer y reparar tejidos; la meiosis produce óvulos y espermatozoides, y al reducir a la mitad los cromosomas permite que la fecundación restablezca el número normal.',
  },
  {
    id: 'sal-015', tema: 'celula-genetica', dificultad: 1,
    enunciado: '¿Cuántos cromosomas tiene una célula somática humana normal?',
    opciones: ['46, organizados en 23 pares', '23 cromosomas sueltos', '46 pares de cromosomas', '48, organizados en 24 pares'],
    correcta: 0,
    explicacion: 'Cada par tiene un cromosoma aportado por la madre y otro por el padre. Los gametos, en cambio, tienen 23 cromosomas.',
  },
  {
    id: 'sal-016', tema: 'celula-genetica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre genotipo y fenotipo?',
    opciones: [
      'El genotipo es la información genética que se tiene; el fenotipo es la característica que se manifiesta',
      'El genotipo se hereda y el fenotipo no tiene relación con los genes',
      'El genotipo es visible y el fenotipo está oculto en el ADN',
      'Son sinónimos usados en distintas ramas de la biología',
    ],
    correcta: 0,
    explicacion: 'Dos personas con el mismo fenotipo pueden tener genotipos distintos: alguien de ojos oscuros puede llevar o no un alelo recesivo para ojos claros. El ambiente también influye en el fenotipo.',
  },
  {
    id: 'sal-017', tema: 'celula-genetica', dificultad: 3,
    enunciado: 'Dos personas con genotipo Aa tienen un hijo, siendo A dominante y a recesivo. ¿Qué probabilidad hay de que el hijo manifieste el rasgo recesivo?',
    opciones: ['25 %', '50 %', '75 %', '0 %'],
    correcta: 0,
    explicacion: 'Las combinaciones posibles son AA, Aa, aA y aa. Solo aa manifiesta el rasgo recesivo: una de cuatro, es decir, 25 %. El 75 % restante muestra el rasgo dominante.',
    pista: 'Arma el cuadro de Punnett con las cuatro combinaciones.',
  },
  {
    id: 'sal-018', tema: 'celula-genetica', dificultad: 2,
    enunciado: 'En la especie humana, el sexo cromosómico del bebé queda determinado por:',
    opciones: [
      'El gameto paterno, que puede aportar un cromosoma X o uno Y',
      'El gameto materno, que puede aportar X o Y',
      'La alimentación de la madre durante el embarazo',
      'El momento del ciclo en que ocurre la fecundación',
    ],
    correcta: 0,
    explicacion: 'El óvulo siempre aporta X; el espermatozoide puede aportar X (XX) o Y (XY). Culpar a la madre por el sexo del bebé es un error biológico con siglos de historia.',
  },
  {
    id: 'sal-019', tema: 'celula-genetica', dificultad: 3,
    enunciado: 'Una mutación es un cambio en la secuencia del ADN. ¿Cuál de estas afirmaciones es correcta?',
    opciones: [
      'Puede ser perjudicial, neutra o ventajosa según el caso',
      'Siempre produce una enfermedad',
      'Solo ocurre por exposición a radiación',
      'Nunca se transmite a la descendencia',
    ],
    correcta: 0,
    explicacion: 'La mayoría son neutras. Las que ocurren en los gametos sí se heredan, y la variación que generan es la materia prima de la evolución.',
  },
  {
    id: 'sal-020', tema: 'celula-genetica', dificultad: 2,
    enunciado: '¿Por qué los hermanos se parecen entre sí pero no son idénticos (salvo los gemelos univitelinos)?',
    opciones: [
      'Porque cada gameto lleva una combinación distinta de los cromosomas de cada progenitor',
      'Porque el ADN cambia con la edad de los padres',
      'Porque cada hijo hereda solo de uno de los dos progenitores',
      'Porque la alimentación determina qué genes se heredan',
    ],
    correcta: 0,
    explicacion: 'En la meiosis los cromosomas se reparten al azar y además intercambian fragmentos. Cada óvulo y cada espermatozoide es una combinación nueva.',
  },

  // ----- Nutrición y alimentación -----
  {
    id: 'sal-021', tema: 'nutricion', dificultad: 1,
    enunciado: 'Los tres macronutrientes de la alimentación son:',
    opciones: [
      'Carbohidratos, proteínas y grasas',
      'Vitaminas, minerales y agua',
      'Fibra, azúcar y sal',
      'Calcio, hierro y zinc',
    ],
    correcta: 0,
    explicacion: 'Se llaman macro porque se necesitan en cantidades grandes y aportan energía. Vitaminas y minerales son micronutrientes: imprescindibles, pero en dosis mínimas.',
  },
  {
    id: 'sal-022', tema: 'nutricion', dificultad: 1,
    enunciado: '¿Cuál es la función principal de las proteínas en el organismo?',
    opciones: [
      'Construir y reparar tejidos, y formar enzimas y anticuerpos',
      'Ser la fuente de energía más rápida y disponible',
      'Almacenar energía a largo plazo',
      'Regular el tránsito intestinal',
    ],
    correcta: 0,
    explicacion: 'Los carbohidratos son la energía rápida y las grasas, la reserva a largo plazo. El tránsito intestinal lo regula la fibra.',
  },
  {
    id: 'sal-023', tema: 'nutricion', dificultad: 2,
    enunciado: 'El índice de masa corporal se calcula dividiendo el peso entre el cuadrado de la estatura. ¿Cuál es el IMC de una persona de 70 kg y 1,75 m?',
    opciones: ['22,9', '40,0', '18,4', '25,6'],
    correcta: 0,
    explicacion: '1,75² = 3,0625 y 70 ÷ 3,0625 ≈ 22,9, dentro del rango considerado normal. El IMC es un indicador poblacional: no distingue entre músculo y grasa, así que en un deportista puede engañar.',
  },
  {
    id: 'sal-024', tema: 'nutricion', dificultad: 2,
    enunciado: '¿Cuál es el principal beneficio de la fibra alimentaria?',
    opciones: [
      'Favorece el tránsito intestinal y aumenta la sensación de saciedad',
      'Aporta la mayor parte de la energía de la dieta',
      'Sustituye a las proteínas de origen animal',
      'Elimina las grasas ya almacenadas en el cuerpo',
    ],
    correcta: 0,
    explicacion: 'No se digiere ni aporta prácticamente energía, y justamente por eso es útil: da volumen, retrasa la absorción del azúcar y alimenta la microbiota. Está en frutas, verduras, legumbres y granos enteros.',
  },
  {
    id: 'sal-025', tema: 'nutricion', dificultad: 3,
    enunciado: 'Un producto trae esta información nutricional. Si una persona consume el paquete entero, ¿cuánta azúcar ingiere?',
    codigo: [
      'INFORMACIÓN NUTRICIONAL',
      'Porción: 30 g          Porciones por envase: 4',
      '',
      '                     Por porción     Por 100 g',
      'Energía                 130 kcal       433 kcal',
      'Azúcares totales          9 g           30 g',
      'Sodio                    150 mg        500 mg',
    ].join('\n'),
    opciones: ['36 g', '9 g', '30 g', '120 g'],
    correcta: 0,
    explicacion: 'El envase trae 4 porciones de 9 g de azúcar cada una: 4 × 9 = 36 g, unas nueve cucharaditas. El truco habitual de las etiquetas es declarar por porción una cantidad mucho menor que la del paquete que la gente se come de una vez.',
    pista: 'Fíjate en cuántas porciones trae el envase, no solo en la columna por porción.',
  },
  {
    id: 'sal-026', tema: 'nutricion', dificultad: 2,
    enunciado: 'El consumo excesivo de azúcares añadidos se asocia principalmente con:',
    opciones: [
      'Caries, sobrepeso y mayor riesgo de diabetes tipo 2',
      'Deficiencia de hierro y anemia',
      'Aumento del colesterol bueno',
      'Mejor rendimiento deportivo sostenido',
    ],
    correcta: 0,
    explicacion: 'Aportan energía sin nutrientes que la acompañen, lo que se conoce como calorías vacías. El azúcar naturalmente presente en la fruta entera viene con fibra, agua y vitaminas, y no se comporta igual.',
  },
  {
    id: 'sal-027', tema: 'nutricion', dificultad: 3,
    enunciado: 'Un producto se anuncia como "0 % grasa". ¿Qué conviene revisar antes de asumir que es saludable?',
    opciones: [
      'La cantidad de azúcares y de sodio, que suelen aumentar para compensar el sabor',
      'Solo el total de calorías por envase',
      'Únicamente la fecha de vencimiento',
      'Nada: sin grasa ya es un producto saludable',
    ],
    correcta: 0,
    explicacion: 'Las declaraciones destacadas en el frente del empaque seleccionan el dato más favorable. La información completa está en la tabla nutricional y en la lista de ingredientes, ordenada de mayor a menor cantidad.',
  },
  {
    id: 'sal-028', tema: 'nutricion', dificultad: 2,
    enunciado: 'La anemia más frecuente en el mundo se debe a la deficiencia de:',
    opciones: ['Hierro', 'Calcio', 'Vitamina C', 'Sodio'],
    correcta: 0,
    explicacion: 'Sin hierro no se forma bien la hemoglobina y la sangre transporta menos oxígeno: de ahí el cansancio y la palidez. La vitamina C no la previene por sí sola, pero mejora la absorción del hierro de origen vegetal.',
  },
  {
    id: 'sal-029', tema: 'nutricion', dificultad: 1,
    enunciado: 'Para hidratarse a diario, la mejor opción es:',
    opciones: [
      'El agua, porque hidrata sin aportar azúcar ni calorías',
      'Las bebidas deportivas, porque reponen sales siempre',
      'Los jugos industriales, porque aportan vitaminas',
      'Las bebidas gaseosas, porque contienen mucha agua',
    ],
    correcta: 0,
    explicacion: 'Las bebidas deportivas tienen sentido en ejercicio intenso y prolongado; en el día a día solo suman azúcar. Un vaso de gaseosa puede llevar el equivalente a varias cucharaditas.',
  },
  {
    id: 'sal-030', tema: 'nutricion', dificultad: 3,
    enunciado: '¿Cómo puede una persona con sobrepeso estar malnutrida?',
    opciones: [
      'Porque puede consumir muchas calorías y a la vez carecer de vitaminas y minerales esenciales',
      'Porque el sobrepeso impide absorber cualquier nutriente',
      'Porque la malnutrición solo se mide con el peso',
      'No es posible: el sobrepeso excluye la malnutrición',
    ],
    correcta: 0,
    explicacion: 'Es la llamada doble carga de la malnutrición, frecuente en América Latina: dietas baratas y muy energéticas pero pobres en micronutrientes. Desnutrición y malnutrición no son lo mismo.',
  },

  // ----- Enfermedades transmisibles -----
  {
    id: 'sal-031', tema: 'enfermedades-transmisibles', dificultad: 1,
    enunciado: 'Las enfermedades infecciosas son causadas por:',
    opciones: [
      'Microorganismos como virus, bacterias, hongos y parásitos',
      'Un desequilibrio hormonal del propio organismo',
      'La herencia genética de los padres',
      'El desgaste natural de los tejidos con la edad',
    ],
    correcta: 0,
    explicacion: 'Son transmisibles porque el agente pasa de un huésped a otro. Las enfermedades hormonales, genéticas o degenerativas no se contagian.',
  },
  {
    id: 'sal-032', tema: 'enfermedades-transmisibles', dificultad: 1,
    enunciado: '¿Por qué los antibióticos no sirven para tratar una gripe común?',
    opciones: [
      'Porque la gripe la causa un virus y los antibióticos solo actúan contra bacterias',
      'Porque la dosis necesaria sería demasiado alta',
      'Porque la gripe dura menos de lo que tarda el antibiótico en actuar',
      'Porque los antibióticos solo funcionan en niños',
    ],
    correcta: 0,
    explicacion: 'Los antibióticos atacan estructuras que los virus no tienen. Tomarlos para una infección viral no cura nada y sí contribuye a la resistencia bacteriana.',
  },
  {
    id: 'sal-033', tema: 'enfermedades-transmisibles', dificultad: 2,
    enunciado: '¿Qué favorece la aparición de bacterias resistentes a los antibióticos?',
    opciones: [
      'Usarlos sin necesidad o abandonar el tratamiento antes de terminarlo',
      'Tomarlos siempre con alimentos',
      'Usar el mismo antibiótico durante toda la vida',
      'Guardarlos en la nevera',
    ],
    correcta: 0,
    explicacion: 'Si el tratamiento se corta, sobreviven las bacterias más resistentes y son las que se multiplican y se transmiten. La resistencia es hoy una de las principales amenazas sanitarias globales.',
  },
  {
    id: 'sal-034', tema: 'enfermedades-transmisibles', dificultad: 1,
    enunciado: 'El dengue se transmite a las personas a través de:',
    opciones: [
      'La picadura de un mosquito infectado',
      'El contacto directo con una persona enferma',
      'El agua contaminada que se bebe',
      'Los alimentos mal cocidos',
    ],
    correcta: 0,
    explicacion: 'Es una enfermedad de transmisión vectorial: el mosquito Aedes aegypti actúa como vector. Por eso la prevención se centra en eliminar los criaderos de agua estancada.',
  },
  {
    id: 'sal-035', tema: 'enfermedades-transmisibles', dificultad: 1,
    enunciado: '¿Cuál es la medida individual más sencilla y efectiva para prevenir muchas infecciones?',
    opciones: [
      'Lavarse las manos con agua y jabón de forma frecuente y completa',
      'Tomar vitaminas todos los días',
      'Usar antibióticos preventivos',
      'Evitar salir de casa durante el invierno',
    ],
    correcta: 0,
    explicacion: 'Interrumpe la transmisión por contacto, que es la vía de entrada de infecciones respiratorias y digestivas. Su costo es mínimo y su impacto poblacional, enorme.',
  },
  {
    id: 'sal-036', tema: 'enfermedades-transmisibles', dificultad: 2,
    enunciado: 'El periodo de incubación de una enfermedad infecciosa es:',
    opciones: [
      'El tiempo entre el contagio y la aparición de los primeros síntomas',
      'El tiempo que dura la enfermedad completa',
      'El tiempo que el enfermo debe permanecer hospitalizado',
      'El tiempo que tarda una vacuna en hacer efecto',
    ],
    correcta: 0,
    explicacion: 'Importa mucho para el control: en varias enfermedades la persona ya contagia durante ese periodo, cuando todavía se siente sana. Es la razón de las cuarentenas.',
  },
  {
    id: 'sal-037', tema: 'enfermedades-transmisibles', dificultad: 2,
    enunciado: 'El consumo de agua no potable se asocia sobre todo con:',
    opciones: [
      'Enfermedades diarreicas, cólera y parasitosis',
      'Enfermedades respiratorias crónicas',
      'Enfermedades de transmisión sexual',
      'Enfermedades cardiovasculares',
    ],
    correcta: 0,
    explicacion: 'Es la vía fecal-oral: patógenos que salen en las heces y llegan a la boca a través del agua o los alimentos. Sigue siendo una de las principales causas de muerte infantil evitable.',
  },
  {
    id: 'sal-038', tema: 'enfermedades-transmisibles', dificultad: 3,
    enunciado: 'Un portador asintomático es una persona que:',
    opciones: [
      'Tiene el agente infeccioso y puede transmitirlo aunque no presente síntomas',
      'Ya superó la enfermedad y quedó inmune',
      'Recibió la vacuna y por eso no se enferma',
      'Presenta síntomas leves que pasan desapercibidos',
    ],
    correcta: 0,
    explicacion: 'Complica el control porque nadie lo identifica a tiempo: no se siente enfermo y sigue su vida normal. De ahí que en un brote se recomienden medidas generales y no solo aislar a quienes tienen síntomas.',
  },
  {
    id: 'sal-039', tema: 'enfermedades-transmisibles', dificultad: 2,
    enunciado: 'La tuberculosis se transmite principalmente por:',
    opciones: [
      'El aire, al inhalar gotitas expulsadas por una persona enferma al toser o hablar',
      'El contacto con la piel de una persona enferma',
      'La picadura de un insecto',
      'Compartir utensilios de cocina',
    ],
    correcta: 0,
    explicacion: 'Es de transmisión aérea, y su tratamiento dura meses. Abandonarlo al sentirse mejor es la causa principal de las formas resistentes, mucho más difíciles de curar.',
  },
  {
    id: 'sal-040', tema: 'enfermedades-transmisibles', dificultad: 3,
    enunciado: 'Durante un brote, ¿por qué aislar a las personas enfermas reduce el número total de casos?',
    opciones: [
      'Porque corta la cadena de transmisión: cada persona aislada deja de contagiar a otras',
      'Porque acelera la recuperación de quien está enfermo',
      'Porque hace que el microorganismo desaparezca del ambiente',
      'Porque aumenta la inmunidad de quienes no se contagian',
    ],
    correcta: 0,
    explicacion: 'El contagio es multiplicativo: si cada enfermo infecta a dos y se le aísla, se evitan no solo esos dos casos, sino todos los que ellos habrían generado después.',
  },

  // ----- Enfermedades crónicas y factores de riesgo -----
  {
    id: 'sal-041', tema: 'enfermedades-cronicas', dificultad: 1,
    enunciado: '¿Cuál de estas es una enfermedad crónica no transmisible?',
    opciones: ['La diabetes tipo 2', 'La tuberculosis', 'El dengue', 'La hepatitis A'],
    correcta: 0,
    explicacion: 'Las crónicas no transmisibles —diabetes, hipertensión, cáncer, enfermedad cardiovascular y respiratoria crónica— son hoy la principal causa de muerte en el mundo. Las otras tres son infecciosas.',
  },
  {
    id: 'sal-042', tema: 'enfermedades-cronicas', dificultad: 2,
    enunciado: '¿Cuál de estos es un factor de riesgo modificable?',
    opciones: ['El sedentarismo', 'La edad', 'El sexo', 'Los antecedentes familiares'],
    correcta: 0,
    explicacion: 'Los modificables —sedentarismo, tabaco, alcohol, alimentación— son sobre los que se puede actuar. Los no modificables no se cambian, pero sí obligan a vigilar más de cerca a quien los tiene.',
  },
  {
    id: 'sal-043', tema: 'enfermedades-cronicas', dificultad: 2,
    enunciado: '¿Por qué a la hipertensión arterial se le llama el asesino silencioso?',
    opciones: [
      'Porque durante años no produce síntomas mientras va dañando corazón, riñones y arterias',
      'Porque solo aparece durante el sueño',
      'Porque no existe tratamiento disponible',
      'Porque no se puede medir sin exámenes de laboratorio',
    ],
    correcta: 0,
    explicacion: 'Mucha gente se entera cuando ya hubo un infarto o un accidente cerebrovascular. Se detecta con algo tan simple como medir la presión, y por eso el control periódico importa tanto.',
  },
  {
    id: 'sal-044', tema: 'enfermedades-cronicas', dificultad: 2,
    enunciado: '¿En qué se diferencian la diabetes tipo 1 y la tipo 2?',
    opciones: [
      'En la tipo 1 el organismo casi no produce insulina; en la tipo 2 la produce pero las células responden mal a ella',
      'La tipo 1 aparece por comer azúcar y la tipo 2 se hereda',
      'La tipo 1 es contagiosa y la tipo 2 no',
      'La tipo 1 no necesita tratamiento y la tipo 2 sí',
    ],
    correcta: 0,
    explicacion: 'La tipo 1 suele aparecer en la infancia o juventud y requiere insulina desde el inicio. La tipo 2 se asocia al exceso de peso y al sedentarismo, y es la más frecuente.',
  },
  {
    id: 'sal-045', tema: 'enfermedades-cronicas', dificultad: 1,
    enunciado: 'El tabaquismo es el principal factor de riesgo evitable de:',
    opciones: [
      'Cáncer de pulmón y enfermedad pulmonar obstructiva crónica',
      'Anemia por deficiencia de hierro',
      'Fracturas por caídas',
      'Enfermedades transmitidas por alimentos',
    ],
    correcta: 0,
    explicacion: 'Además multiplica el riesgo cardiovascular y el de otros cánceres. El humo de segunda mano afecta a quienes conviven con el fumador, incluso sin fumar.',
  },
  {
    id: 'sal-046', tema: 'enfermedades-cronicas', dificultad: 3,
    enunciado: 'Se considera hipertensión una presión arterial habitual igual o superior a 140/90 mmHg. Una persona registra de forma sostenida 150/95. ¿Qué se concluye?',
    opciones: [
      'Cumple el criterio de hipertensión y debe consultar para confirmar y tratar',
      'Está en el rango normal porque el segundo número es menor de 100',
      'Solo importa el primer número, así que está bien',
      'Solo hay hipertensión si además presenta dolor de cabeza',
    ],
    correcta: 0,
    explicacion: 'Los dos valores están por encima del umbral: 150 ≥ 140 y 95 ≥ 90. Con que uno solo lo supere de forma sostenida ya se cumple el criterio, y la ausencia de síntomas no descarta nada.',
  },
  {
    id: 'sal-047', tema: 'enfermedades-cronicas', dificultad: 2,
    enunciado: 'El exceso de colesterol en la sangre aumenta el riesgo cardiovascular porque:',
    opciones: [
      'Favorece la formación de placas que estrechan las arterias',
      'Aumenta directamente la frecuencia cardiaca',
      'Impide que la sangre coagule',
      'Reduce la cantidad de glóbulos rojos',
    ],
    correcta: 0,
    explicacion: 'Es la aterosclerosis: las arterias se estrechan y se endurecen, y si una placa se rompe puede formarse un coágulo que provoque un infarto o un accidente cerebrovascular.',
  },
  {
    id: 'sal-048', tema: 'enfermedades-cronicas', dificultad: 2,
    enunciado: '¿Para qué sirven los programas de tamizaje o detección temprana, como la citología o la mamografía?',
    opciones: [
      'Para encontrar la enfermedad antes de que dé síntomas, cuando el tratamiento es más efectivo',
      'Para curar la enfermedad sin necesidad de tratamiento posterior',
      'Para confirmar un diagnóstico en personas que ya tienen síntomas',
      'Para reemplazar las consultas médicas periódicas',
    ],
    correcta: 0,
    explicacion: 'El tamizaje se aplica a personas sanas de un grupo de riesgo. Un resultado positivo no es un diagnóstico: obliga a confirmar con otras pruebas.',
  },
  {
    id: 'sal-049', tema: 'enfermedades-cronicas', dificultad: 3,
    enunciado: 'Una persona con hipertensión se siente bien y decide suspender su medicación. ¿Por qué es riesgoso?',
    opciones: [
      'Porque se siente bien gracias al tratamiento: al suspenderlo la presión vuelve a subir y el daño continúa en silencio',
      'Porque el medicamento genera dependencia física',
      'Porque los síntomas reaparecen de inmediato y son muy dolorosos',
      'Porque la presión bajaría demasiado al suspenderlo',
    ],
    correcta: 0,
    explicacion: 'Confundir el control con la curación es uno de los errores más comunes en enfermedades crónicas. El tratamiento mantiene el valor bajo, no elimina la condición.',
  },
  {
    id: 'sal-050', tema: 'enfermedades-cronicas', dificultad: 2,
    enunciado: 'La obesidad se considera un problema de salud porque:',
    opciones: [
      'Aumenta el riesgo de diabetes, hipertensión, problemas articulares y varios tipos de cáncer',
      'Únicamente afecta la apariencia física',
      'Impide practicar cualquier actividad física',
      'Siempre se debe a falta de voluntad de la persona',
    ],
    correcta: 0,
    explicacion: 'Es una condición multifactorial: influyen la genética, el entorno alimentario, el sueño, el nivel socioeconómico y la actividad física. Reducirla a un asunto de voluntad no explica por qué creció en todo el mundo a la vez.',
  },

  // ----- Vacunas, prevención y salud pública -----
  {
    id: 'sal-051', tema: 'vacunas-salud-publica', dificultad: 1,
    enunciado: '¿Cómo funciona una vacuna?',
    opciones: [
      'Entrena al sistema inmunitario para reconocer un agente sin tener que sufrir la enfermedad',
      'Mata directamente a los microorganismos que ya están en el cuerpo',
      'Sustituye a los glóbulos blancos durante un tiempo',
      'Bloquea la entrada de cualquier microorganismo por la piel',
    ],
    correcta: 0,
    explicacion: 'Presenta al organismo una versión inofensiva del agente o de una de sus partes. El sistema inmunitario genera memoria y responde rápido si alguna vez llega el agente real.',
  },
  {
    id: 'sal-052', tema: 'vacunas-salud-publica', dificultad: 2,
    enunciado: '¿En qué consiste la inmunidad de rebaño o comunitaria?',
    opciones: [
      'En que al estar vacunada una proporción alta de la población, el agente circula poco y protege indirectamente a quienes no pueden vacunarse',
      'En que las personas vacunadas transmiten la inmunidad a sus contactos',
      'En que la enfermedad desaparece del planeta',
      'En que basta con vacunar a los adultos para proteger a los niños',
    ],
    correcta: 0,
    explicacion: 'La inmunidad no se contagia: lo que se corta es la circulación del agente. Por eso hay bebés, personas inmunosuprimidas o alérgicas que dependen de que el resto se vacune.',
  },
  {
    id: 'sal-053', tema: 'vacunas-salud-publica', dificultad: 2,
    enunciado: '¿Cuál es la única enfermedad humana que ha sido erradicada del planeta gracias a la vacunación?',
    opciones: ['La viruela', 'La polio', 'El sarampión', 'La tuberculosis'],
    correcta: 0,
    explicacion: 'Se declaró erradicada en 1980. La polio está cerca, con circulación limitada a unas pocas zonas, y el sarampión resurge cada vez que bajan las coberturas.',
  },
  {
    id: 'sal-054', tema: 'vacunas-salud-publica', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre endemia, epidemia y pandemia?',
    opciones: [
      'La endemia es la presencia habitual en una zona; la epidemia es un aumento inusual de casos; la pandemia se extiende a varios continentes',
      'Son tres nombres para lo mismo, según la gravedad',
      'La endemia afecta a animales, la epidemia a personas y la pandemia a ambos',
      'La epidemia dura semanas y la pandemia, años',
    ],
    correcta: 0,
    explicacion: 'Lo que distingue a la epidemia no es el número absoluto de casos, sino que supere lo esperado para esa zona y ese momento.',
  },
  {
    id: 'sal-055', tema: 'vacunas-salud-publica', dificultad: 2,
    enunciado: 'Además de las vacunas, ¿qué intervención de salud pública ha salvado más vidas históricamente?',
    opciones: [
      'El acceso a agua potable y saneamiento básico',
      'La construcción de hospitales especializados',
      'El desarrollo de nuevos medicamentos oncológicos',
      'Las campañas de donación de sangre',
    ],
    correcta: 0,
    explicacion: 'Agua limpia y manejo de excretas cortaron de raíz las enfermedades transmitidas por vía fecal-oral. Es una intervención poco visible, sin protagonista, y por eso se subestima.',
  },
  {
    id: 'sal-056', tema: 'vacunas-salud-publica', dificultad: 3,
    enunciado: 'En un colegio, la cobertura de vacunación contra el sarampión baja del 95 % al 80 %. ¿Qué es previsible?',
    opciones: [
      'Que aumente el riesgo de brote, incluso entre algunos vacunados, porque el virus vuelve a circular',
      'Que no pase nada mientras la mayoría siga vacunada',
      'Que solo se enfermen quienes no se vacunaron, sin más consecuencias',
      'Que la enfermedad se vuelva más leve al circular más',
    ],
    correcta: 0,
    explicacion: 'El sarampión es extremadamente contagioso y necesita coberturas muy altas para no circular. Ninguna vacuna es 100 % efectiva, así que al aumentar la circulación también sube el riesgo residual de los vacunados.',
  },
  {
    id: 'sal-057', tema: 'vacunas-salud-publica', dificultad: 2,
    enunciado: 'Al evaluar una vacuna, ¿cómo se comparan sus efectos secundarios con la enfermedad que previene?',
    opciones: [
      'Los efectos frecuentes suelen ser leves y pasajeros, frente a un riesgo de enfermedad grave mucho mayor',
      'Los efectos secundarios son siempre más peligrosos que la enfermedad',
      'Las vacunas aprobadas no tienen ningún efecto secundario',
      'No es posible comparar ambas cosas',
    ],
    correcta: 0,
    explicacion: 'Dolor en el brazo, febrícula o malestar de un día son lo común. La decisión sanitaria siempre es comparativa: riesgo de la vacuna frente a riesgo de la enfermedad, no riesgo cero frente a riesgo.',
  },
  {
    id: 'sal-058', tema: 'vacunas-salud-publica', dificultad: 2,
    enunciado: 'La cadena de frío en un programa de vacunación sirve para:',
    opciones: [
      'Mantener las vacunas en el rango de temperatura que conserva su eficacia',
      'Transportar las vacunas más rápido entre ciudades',
      'Evitar que las vacunas se contaminen con bacterias',
      'Alargar indefinidamente la fecha de vencimiento',
    ],
    correcta: 0,
    explicacion: 'Una vacuna que se calentó puede perder su capacidad de generar inmunidad sin que nada lo delate a simple vista: se aplica igual y no protege.',
  },
  {
    id: 'sal-059', tema: 'vacunas-salud-publica', dificultad: 3,
    enunciado: 'En un brote hay 2 000 contagiados y 40 muertes. La letalidad de la enfermedad es:',
    opciones: ['2 %', '0,2 %', '20 %', '40 %'],
    correcta: 0,
    explicacion: 'Letalidad es muertes entre contagiados: 40 ÷ 2 000 = 0,02, es decir 2 %. La mortalidad, en cambio, se calcula sobre la población total, no solo sobre los enfermos.',
    pista: 'Letalidad: sobre los enfermos. Mortalidad: sobre toda la población.',
  },
  {
    id: 'sal-060', tema: 'vacunas-salud-publica', dificultad: 2,
    enunciado: 'La vigilancia epidemiológica consiste en:',
    opciones: [
      'Recoger y analizar datos de casos de forma continua para detectar a tiempo cambios en la situación de salud',
      'Vigilar que los pacientes cumplan sus tratamientos',
      'Inspeccionar los hospitales una vez al año',
      'Controlar la entrada de extranjeros al país',
    ],
    correcta: 0,
    explicacion: 'Es el sistema de alarma temprana de un país: sin datos oportunos, un brote solo se descubre cuando ya es grande.',
  },

  // ----- Salud sexual y reproductiva -----
  {
    id: 'sal-061', tema: 'salud-sexual', dificultad: 1,
    enunciado: 'Los ovarios y los testículos cumplen dos funciones:',
    opciones: [
      'Producir gametos y producir hormonas sexuales',
      'Producir gametos y filtrar la sangre',
      'Almacenar gametos y producir orina',
      'Producir hormonas y almacenar nutrientes',
    ],
    correcta: 0,
    explicacion: 'Son gónadas: fabrican óvulos o espermatozoides y además segregan estrógenos, progesterona o testosterona, responsables de los caracteres sexuales secundarios.',
  },
  {
    id: 'sal-062', tema: 'salud-sexual', dificultad: 2,
    enunciado: 'En un ciclo menstrual regular de 28 días, la ovulación ocurre aproximadamente:',
    opciones: [
      'Hacia la mitad del ciclo, alrededor del día 14',
      'El primer día de la menstruación',
      'Justo antes de que comience la menstruación',
      'Todos los días del ciclo por igual',
    ],
    correcta: 0,
    explicacion: 'El día 1 es el primero de sangrado. Conviene recordar que muchos ciclos no son de 28 días exactos, y por eso calcular los días fértiles resulta poco confiable como método anticonceptivo.',
  },
  {
    id: 'sal-063', tema: 'salud-sexual', dificultad: 2,
    enunciado: '¿Dónde ocurre normalmente la fecundación?',
    opciones: ['En las trompas de Falopio', 'En el útero', 'En los ovarios', 'En la vagina'],
    correcta: 0,
    explicacion: 'El espermatozoide se encuentra con el óvulo en la trompa; el cigoto resultante viaja hacia el útero, donde se implanta unos días después.',
  },
  {
    id: 'sal-064', tema: 'salud-sexual', dificultad: 1,
    enunciado: '¿Cuál de estas NO es una vía de transmisión del VIH?',
    opciones: [
      'Compartir utensilios, abrazar o dar la mano a una persona con VIH',
      'Relaciones sexuales sin protección',
      'Compartir jeringas o agujas',
      'De la madre al hijo durante el embarazo, el parto o la lactancia',
    ],
    correcta: 0,
    explicacion: 'El virus no se transmite por contacto cotidiano, saliva, sudor ni picaduras de insectos. Desmontar ese mito importa porque el estigma aleja a la gente de la prueba y del tratamiento.',
  },
  {
    id: 'sal-065', tema: 'salud-sexual', dificultad: 2,
    enunciado: '¿Cuál es el único método que previene a la vez el embarazo y las infecciones de transmisión sexual?',
    opciones: ['El preservativo o condón', 'La píldora anticonceptiva', 'El dispositivo intrauterino', 'El implante subdérmico'],
    correcta: 0,
    explicacion: 'Los métodos hormonales y el DIU son muy eficaces contra el embarazo, pero no ponen ninguna barrera frente a las infecciones. Por eso se recomienda el método doble.',
  },
  {
    id: 'sal-066', tema: 'salud-sexual', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre tener VIH y tener sida?',
    opciones: [
      'El VIH es el virus; el sida es la fase avanzada que aparece si la infección no se trata',
      'Son exactamente lo mismo con dos nombres',
      'El VIH se transmite y el sida no',
      'El sida es la fase inicial y el VIH la avanzada',
    ],
    correcta: 0,
    explicacion: 'Con tratamiento antirretroviral una persona con VIH puede mantener el virus indetectable, no transmitirlo por vía sexual y no desarrollar sida. De ahí la importancia del diagnóstico temprano.',
  },
  {
    id: 'sal-067', tema: 'salud-sexual', dificultad: 3,
    enunciado: 'Al comparar métodos anticonceptivos, ¿por qué el llamado método del ritmo o del calendario es poco confiable?',
    opciones: [
      'Porque los ciclos varían y los espermatozoides sobreviven varios días en el tracto femenino',
      'Porque exige control médico permanente',
      'Porque tiene efectos secundarios hormonales',
      'Porque solo funciona en ciclos superiores a 30 días',
    ],
    correcta: 0,
    explicacion: 'La ventana fértil es más ancha e imprevisible de lo que sugiere el cálculo. Su tasa de fallo en uso real es de las más altas entre todos los métodos.',
  },
  {
    id: 'sal-068', tema: 'salud-sexual', dificultad: 2,
    enunciado: 'La vacuna contra el virus del papiloma humano (VPH) previene principalmente:',
    opciones: [
      'El cáncer de cuello uterino y otros cánceres asociados a ese virus',
      'Todas las infecciones de transmisión sexual',
      'El embarazo no deseado',
      'La infección por VIH',
    ],
    correcta: 0,
    explicacion: 'Es una de las pocas vacunas que previene un cáncer. Se aplica antes del inicio de la vida sexual para que genere inmunidad previa a la exposición.',
  },
  {
    id: 'sal-069', tema: 'salud-sexual', dificultad: 3,
    enunciado: 'Desde el punto de vista de la salud y los derechos, el consentimiento en una relación sexual debe ser:',
    opciones: [
      'Libre, informado, específico y revocable en cualquier momento',
      'Otorgado una sola vez y válido para el futuro',
      'Deducido del silencio o de la ausencia de resistencia',
      'Dado por sentado dentro de una relación de pareja',
    ],
    correcta: 0,
    explicacion: 'Ni el silencio ni una relación previa equivalen a consentimiento, y este puede retirarse en cualquier punto. No hay consentimiento válido si hay presión, engaño o incapacidad para decidir.',
  },
  {
    id: 'sal-070', tema: 'salud-sexual', dificultad: 2,
    enunciado: 'El embarazo en la adolescencia se considera un problema de salud pública porque:',
    opciones: [
      'Implica mayores riesgos para la madre y el bebé y suele interrumpir la trayectoria educativa',
      'Los bebés nacen siempre con malformaciones',
      'Las adolescentes no pueden llevar un embarazo a término',
      'Es más costoso para el sistema de salud que cualquier otro embarazo',
    ],
    correcta: 0,
    explicacion: 'Hay riesgo obstétrico aumentado y consecuencias sociales que se prolongan durante años. La educación sexual integral y el acceso a anticoncepción son las intervenciones con mejor evidencia para reducirlo.',
  },

  // ----- Primeros auxilios -----
  {
    id: 'sal-071', tema: 'primeros-auxilios', dificultad: 1,
    enunciado: 'Ante un accidente, ¿cuál es el primer paso antes de auxiliar a la víctima?',
    opciones: [
      'Asegurar la escena para no convertirse en una segunda víctima',
      'Mover a la víctima a un lugar cómodo',
      'Darle agua para que se reanime',
      'Buscar sus documentos de identidad',
    ],
    correcta: 0,
    explicacion: 'La secuencia clásica es proteger, avisar y socorrer. Un auxiliador herido deja de ayudar y suma un paciente más.',
  },
  {
    id: 'sal-072', tema: 'primeros-auxilios', dificultad: 2,
    enunciado: 'En una reanimación cardiopulmonar a un adulto, las compresiones se hacen:',
    opciones: [
      'En el centro del pecho, fuertes y rápidas, a un ritmo de 100 a 120 por minuto',
      'Sobre el abdomen, justo encima del ombligo',
      'En el lado izquierdo del pecho, con una sola mano',
      'Suavemente, para no romper las costillas',
    ],
    correcta: 0,
    explicacion: 'Lo que mantiene la circulación es la profundidad y el ritmo. Comprimir con miedo es el error más común y hace la maniobra inútil: sin compresiones, la víctima no tiene ninguna posibilidad.',
  },
  {
    id: 'sal-073', tema: 'primeros-auxilios', dificultad: 2,
    enunciado: 'Una persona se atraganta y NO puede toser, hablar ni respirar. ¿Qué corresponde hacer?',
    opciones: [
      'Aplicar compresiones abdominales (maniobra de Heimlich) y pedir ayuda',
      'Darle agua para que el alimento baje',
      'Esperar a que tosa por sí sola',
      'Acostarla boca arriba y sujetarle la lengua',
    ],
    correcta: 0,
    explicacion: 'Si la persona tose con fuerza, lo mejor es animarla a seguir tosiendo: la tos es el mecanismo más eficaz. La maniobra se reserva para la obstrucción completa, cuando no entra aire.',
  },
  {
    id: 'sal-074', tema: 'primeros-auxilios', dificultad: 1,
    enunciado: 'Ante una herida que sangra abundantemente, la primera medida es:',
    opciones: [
      'Hacer presión directa sobre la herida con un paño limpio',
      'Aplicar un torniquete de inmediato',
      'Lavar la herida con alcohol',
      'Retirar cualquier objeto clavado en ella',
    ],
    correcta: 0,
    explicacion: 'La presión directa detiene la mayoría de las hemorragias. El torniquete se reserva para casos extremos y un objeto clavado no se retira: puede estar taponando el vaso.',
  },
  {
    id: 'sal-075', tema: 'primeros-auxilios', dificultad: 2,
    enunciado: 'Ante una quemadura leve, lo correcto es:',
    opciones: [
      'Enfriarla con agua corriente a temperatura ambiente durante varios minutos',
      'Aplicar hielo directamente sobre la piel',
      'Cubrirla con pasta dental o mantequilla',
      'Reventar las ampollas para que drenen',
    ],
    correcta: 0,
    explicacion: 'El agua templada retira el calor sin dañar más el tejido. El hielo puede causar una lesión adicional, y las pastas caseras contaminan y dificultan la atención posterior.',
  },
  {
    id: 'sal-076', tema: 'primeros-auxilios', dificultad: 3,
    enunciado: '¿Por qué no se debe mover a una persona accidentada si se sospecha lesión de columna?',
    opciones: [
      'Porque un movimiento inadecuado puede dañar la médula espinal y causar una lesión permanente',
      'Porque aumenta el dolor de la víctima',
      'Porque podría perder el conocimiento',
      'Porque la ley lo prohíbe en todos los casos',
    ],
    correcta: 0,
    explicacion: 'Solo se mueve si hay un peligro inmediato mayor, como fuego. Fuera de eso, lo indicado es inmovilizar, acompañar y esperar a los servicios de emergencia.',
  },
  {
    id: 'sal-077', tema: 'primeros-auxilios', dificultad: 2,
    enunciado: 'Si alguien se desmaya y respira con normalidad, lo indicado es:',
    opciones: [
      'Acostarlo boca arriba y elevarle las piernas, aflojando la ropa ajustada',
      'Sentarlo con la cabeza entre las rodillas y darle de beber',
      'Sacudirlo hasta que reaccione',
      'Dejarlo de pie con apoyo hasta que se recupere',
    ],
    correcta: 0,
    explicacion: 'Elevar las piernas favorece el retorno de sangre al cerebro. No se da nada de beber a una persona con la conciencia alterada, por el riesgo de atragantamiento.',
  },
  {
    id: 'sal-078', tema: 'primeros-auxilios', dificultad: 1,
    enunciado: '¿Cuál de estos elementos NO debería faltar en un botiquín básico?',
    opciones: [
      'Gasas estériles, vendas, guantes y antiséptico',
      'Antibióticos de amplio espectro',
      'Jeringas para inyectar medicamentos',
      'Analgésicos inyectables',
    ],
    correcta: 0,
    explicacion: 'Un botiquín doméstico sirve para atender lo menor y estabilizar mientras llega la ayuda. Guardar antibióticos en casa favorece la automedicación y la resistencia bacteriana.',
  },
  {
    id: 'sal-079', tema: 'primeros-auxilios', dificultad: 3,
    enunciado: 'Ante una intoxicación por ingestión de un producto de limpieza, ¿qué NO se debe hacer?',
    opciones: [
      'Provocar el vómito por iniciativa propia',
      'Llamar a emergencias o al centro toxicológico',
      'Conservar el envase del producto para mostrarlo',
      'Mantener a la persona despierta y acompañada',
    ],
    correcta: 0,
    explicacion: 'Con sustancias corrosivas el vómito vuelve a quemar el esófago al subir. Guardar el envase permite identificar el tóxico y acelerar el tratamiento correcto.',
  },
  {
    id: 'sal-080', tema: 'primeros-auxilios', dificultad: 2,
    enunciado: 'Ante la sospecha de una fractura en un brazo, lo correcto es:',
    opciones: [
      'Inmovilizar el miembro en la posición en que quedó y buscar atención médica',
      'Intentar alinear el hueso antes de trasladar a la persona',
      'Aplicar calor para reducir la hinchazón',
      'Hacer que mueva el brazo para comprobar si está roto',
    ],
    correcta: 0,
    explicacion: 'Alinear o manipular puede dañar vasos y nervios cercanos. El frío, no el calor, ayuda a reducir la inflamación mientras llega la atención.',
  },

  // ----- Salud mental y adicciones -----
  {
    id: 'sal-081', tema: 'salud-mental', dificultad: 1,
    enunciado: 'Según la definición de la Organización Mundial de la Salud, la salud es:',
    opciones: [
      'Un estado de completo bienestar físico, mental y social, y no solo la ausencia de enfermedad',
      'La ausencia de enfermedades y dolencias',
      'La capacidad de trabajar sin limitaciones',
      'El resultado de una buena alimentación y ejercicio',
    ],
    correcta: 0,
    explicacion: 'Lo relevante de esa definición es que incorpora lo mental y lo social: alguien sin ninguna enfermedad diagnosticada puede no estar sano.',
  },
  {
    id: 'sal-082', tema: 'salud-mental', dificultad: 2,
    enunciado: '¿Cuál es la diferencia entre estrés agudo y estrés crónico?',
    opciones: [
      'El agudo es una respuesta puntual y adaptativa; el crónico se mantiene en el tiempo y deteriora la salud',
      'El agudo es siempre dañino y el crónico es inofensivo',
      'El agudo afecta el cuerpo y el crónico solo la mente',
      'El agudo solo lo sufren los adultos',
    ],
    correcta: 0,
    explicacion: 'Una dosis de estrés antes de un examen ayuda a concentrarse. Sostenido durante meses, en cambio, se asocia a insomnio, problemas digestivos, hipertensión y ansiedad.',
  },
  {
    id: 'sal-083', tema: 'salud-mental', dificultad: 2,
    enunciado: '¿Qué distingue a un episodio depresivo de la tristeza normal?',
    opciones: [
      'Su duración, su intensidad y que afecta el funcionamiento diario de la persona',
      'Que aparece sin ningún motivo aparente',
      'Que solo ocurre en personas adultas',
      'Que la tristeza normal no incluye llanto',
    ],
    correcta: 0,
    explicacion: 'La tristeza es una emoción sana ante una pérdida. La depresión es un cuadro clínico sostenido, con pérdida de interés, alteraciones del sueño y del apetito, y necesita atención profesional.',
  },
  {
    id: 'sal-084', tema: 'salud-mental', dificultad: 2,
    enunciado: 'La ansiedad se vuelve un problema de salud cuando:',
    opciones: [
      'Es desproporcionada, persistente e interfiere con la vida cotidiana',
      'Aparece antes de una situación importante',
      'Provoca aceleración del pulso',
      'Se presenta más de una vez al mes',
    ],
    correcta: 0,
    explicacion: 'La ansiedad es un mecanismo de alarma útil ante una amenaza real. El trastorno aparece cuando la alarma se dispara sin peligro proporcionado y no se apaga.',
  },
  {
    id: 'sal-085', tema: 'salud-mental', dificultad: 3,
    enunciado: '¿Por qué el estigma asociado a los problemas de salud mental agrava el problema?',
    opciones: [
      'Porque retrasa o impide que la persona pida ayuda, y cuanto más tarde se atiende, peor es el pronóstico',
      'Porque hace que los tratamientos sean más caros',
      'Porque los profesionales se niegan a atender esos casos',
      'Porque convierte un problema leve en uno hereditario',
    ],
    correcta: 0,
    explicacion: 'Pedir ayuda a tiempo es lo que más cambia el desenlace. Hablar de salud mental como de cualquier otra área de la salud es, en sí mismo, una medida preventiva.',
  },
  {
    id: 'sal-086', tema: 'salud-mental', dificultad: 2,
    enunciado: 'Dormir poco de forma habitual durante la adolescencia se asocia con:',
    opciones: [
      'Peor rendimiento académico, irritabilidad y mayor riesgo de problemas de ánimo',
      'Mayor capacidad de concentración por costumbre',
      'Un metabolismo más eficiente',
      'Ningún efecto mientras se compense el fin de semana',
    ],
    correcta: 0,
    explicacion: 'En la adolescencia se recomiendan entre ocho y diez horas. El sueño consolida lo aprendido durante el día, así que dormir mal también es estudiar mal.',
  },
  {
    id: 'sal-087', tema: 'salud-mental', dificultad: 2,
    enunciado: 'Desde el punto de vista farmacológico, el alcohol es:',
    opciones: [
      'Un depresor del sistema nervioso central',
      'Un estimulante del sistema nervioso central',
      'Un alucinógeno',
      'Un analgésico sin efectos sobre el sistema nervioso',
    ],
    correcta: 0,
    explicacion: 'La desinhibición inicial confunde: no es estimulación, es la pérdida del freno inhibitorio. A dosis altas deprime funciones vitales como la respiración.',
  },
  {
    id: 'sal-088', tema: 'salud-mental', dificultad: 2,
    enunciado: 'En una adicción, la tolerancia consiste en que:',
    opciones: [
      'Se necesita cada vez más cantidad para obtener el mismo efecto',
      'El cuerpo deja de sentir cualquier efecto de la sustancia',
      'La persona puede dejar el consumo cuando quiera',
      'Aparecen síntomas físicos al suspender el consumo',
    ],
    correcta: 0,
    explicacion: 'Los síntomas al suspender son el síndrome de abstinencia, el otro rasgo característico. Tolerancia y abstinencia juntas describen la dependencia física.',
  },
  {
    id: 'sal-089', tema: 'salud-mental', dificultad: 3,
    enunciado: 'Se ha descrito que el uso intensivo de redes sociales puede afectar el ánimo. El mecanismo más citado es:',
    opciones: [
      'La comparación constante con versiones editadas y favorables de la vida de otros',
      'La radiación que emiten los dispositivos',
      'La pérdida de memoria por exceso de información',
      'El consumo de datos móviles',
    ],
    correcta: 0,
    explicacion: 'Se compara la vida propia completa, con sus días malos, contra el resumen más favorable de la de los demás. A eso se suma el desplazamiento del sueño y del contacto presencial.',
  },
  {
    id: 'sal-090', tema: 'salud-mental', dificultad: 2,
    enunciado: 'Si un amigo expresa ideas de hacerse daño, lo más adecuado es:',
    opciones: [
      'Tomarlo en serio, acompañarlo y buscar de inmediato ayuda de un adulto o profesional',
      'Guardar el secreto porque lo pidió',
      'Restarle importancia para que se distraiga',
      'Esperar a ver si lo repite en los próximos días',
    ],
    correcta: 0,
    explicacion: 'Es la única situación en la que no guardar un secreto es lo correcto. Preguntar directamente no induce la conducta: abre la puerta a hablar y a buscar ayuda.',
  },

  // ----- Actividad física y hábitos -----
  {
    id: 'sal-091', tema: 'actividad-fisica', dificultad: 1,
    enunciado: 'La recomendación general de actividad física para adolescentes es de al menos:',
    opciones: [
      '60 minutos diarios de actividad moderada a intensa',
      '20 minutos diarios de actividad ligera',
      'Dos horas semanales de ejercicio intenso',
      'Una sesión larga de ejercicio el fin de semana',
    ],
    correcta: 0,
    explicacion: 'Para adultos la recomendación es de unos 150 minutos semanales de actividad moderada. Repartirla en varios días funciona mejor que concentrarla en una sola sesión.',
  },
  {
    id: 'sal-092', tema: 'actividad-fisica', dificultad: 2,
    enunciado: 'El sedentarismo se considera un factor de riesgo independiente porque:',
    opciones: [
      'Aumenta el riesgo cardiovascular y metabólico incluso en personas con peso normal',
      'Solo afecta a quienes tienen sobrepeso',
      'Provoca directamente infecciones respiratorias',
      'Reduce la estatura con el tiempo',
    ],
    correcta: 0,
    explicacion: 'Pasar muchas horas sentado tiene efectos propios sobre el metabolismo, aparte del peso. De ahí la recomendación de interrumpir el tiempo sentado cada cierto rato, aunque se entrene.',
  },
  {
    id: 'sal-093', tema: 'actividad-fisica', dificultad: 2,
    enunciado: 'Una estimación habitual de la frecuencia cardiaca máxima es 220 menos la edad. ¿Cuál sería la de una persona de 20 años?',
    opciones: ['200 latidos por minuto', '220 latidos por minuto', '180 latidos por minuto', '100 latidos por minuto'],
    correcta: 0,
    explicacion: '220 − 20 = 200. Es una fórmula aproximada, útil para definir zonas de entrenamiento, no un límite exacto para cada persona.',
  },
  {
    id: 'sal-094', tema: 'actividad-fisica', dificultad: 1,
    enunciado: '¿Para qué sirve el calentamiento antes de la actividad física?',
    opciones: [
      'Para preparar músculos, articulaciones y sistema cardiovascular y reducir el riesgo de lesión',
      'Para quemar la mayor parte de las calorías de la sesión',
      'Para aumentar la masa muscular',
      'Para sustituir el estiramiento posterior',
    ],
    correcta: 0,
    explicacion: 'Eleva la temperatura muscular y la frecuencia cardiaca de forma progresiva. Empezar en frío con esfuerzo máximo es una de las causas más frecuentes de lesión.',
  },
  {
    id: 'sal-095', tema: 'actividad-fisica', dificultad: 2,
    enunciado: 'Durante una actividad física prolongada, lo recomendable respecto a la hidratación es:',
    opciones: [
      'Beber agua de forma regular, sin esperar a tener sed',
      'Beber solo al terminar el ejercicio',
      'Evitar los líquidos para no sentir pesadez',
      'Beber únicamente bebidas azucaradas',
    ],
    correcta: 0,
    explicacion: 'La sed aparece cuando ya hay cierto grado de deshidratación. En ejercicios largos o con mucho calor conviene además reponer sales.',
  },
  {
    id: 'sal-096', tema: 'actividad-fisica', dificultad: 3,
    enunciado: 'Además de sus efectos físicos, el ejercicio regular se asocia con:',
    opciones: [
      'Mejoras en el estado de ánimo y reducción de síntomas de ansiedad y depresión leve',
      'Aumento del estrés por el esfuerzo adicional',
      'Ningún efecto sobre la salud mental',
      'Dificultades para conciliar el sueño',
    ],
    correcta: 0,
    explicacion: 'Es una de las intervenciones con mejor evidencia en salud mental, y tiende además a mejorar la calidad del sueño. No sustituye al tratamiento cuando el cuadro es moderado o grave.',
  },
  {
    id: 'sal-097', tema: 'actividad-fisica', dificultad: 2,
    enunciado: 'Para prevenir dolores de espalda y cuello al estudiar frente a una pantalla, lo recomendable es:',
    opciones: [
      'Mantener la pantalla a la altura de los ojos, la espalda apoyada y hacer pausas periódicas',
      'Estudiar acostado para que la espalda descanse',
      'Sostener el dispositivo en el regazo durante horas',
      'Evitar moverse para no perder la concentración',
    ],
    correcta: 0,
    explicacion: 'La postura sostenida importa más que la postura puntual: ninguna es buena durante cuatro horas seguidas. Levantarse cada cierto tiempo es parte de la solución.',
  },
  {
    id: 'sal-098', tema: 'actividad-fisica', dificultad: 2,
    enunciado: 'Entre los efectos cardiovasculares del ejercicio regular está:',
    opciones: [
      'La reducción de la presión arterial en reposo y la mejora del perfil de lípidos',
      'El aumento permanente de la frecuencia cardiaca en reposo',
      'El engrosamiento de las arterias por las placas',
      'La disminución de la capacidad pulmonar',
    ],
    correcta: 0,
    explicacion: 'Un corazón entrenado bombea más sangre en cada latido, así que necesita menos latidos en reposo. El pulso bajo en reposo es un indicador de buena condición física.',
  },
  {
    id: 'sal-099', tema: 'actividad-fisica', dificultad: 3,
    enunciado: 'Es común oír que "cuanto más se suda, más grasa se quema". ¿Por qué es falso?',
    opciones: [
      'Porque el sudor es pérdida de agua para regular la temperatura, no de grasa',
      'Porque sudar impide que el cuerpo use la grasa como energía',
      'Porque la grasa solo se quema en reposo',
      'Porque el sudor contiene la energía que ya se gastó',
    ],
    correcta: 0,
    explicacion: 'El peso perdido en una sesión de sudor intenso se recupera al beber agua. Por eso los trajes plásticos o las saunas no adelgazan: deshidratan, y eso sí es riesgoso.',
  },
  {
    id: 'sal-100', tema: 'actividad-fisica', dificultad: 2,
    enunciado: 'Al empezar a entrenar después de mucho tiempo inactivo, lo aconsejable es:',
    opciones: [
      'Aumentar la carga de forma progresiva e incluir días de descanso',
      'Entrenar al máximo desde el primer día para adaptarse rápido',
      'Entrenar todos los días sin descanso hasta ver resultados',
      'Empezar directamente con pesos elevados y pocas repeticiones',
    ],
    correcta: 0,
    explicacion: 'La adaptación ocurre durante el descanso, no durante el esfuerzo. Subir la carga demasiado rápido produce lesiones y abandono, que es la causa número uno de fracaso.',
  },

  // ----- Ecología y ecosistemas -----
  {
    id: 'sal-101', tema: 'ecologia', dificultad: 1,
    enunciado: 'Un ecosistema está formado por:',
    opciones: [
      'Los seres vivos de un lugar y el medio físico con el que interactúan',
      'Únicamente los animales de una región',
      'El conjunto de plantas de un territorio',
      'El clima y el relieve de una zona',
    ],
    correcta: 0,
    explicacion: 'Incluye los factores bióticos (los organismos) y los abióticos (agua, suelo, luz, temperatura). Lo que define al ecosistema son las relaciones entre unos y otros.',
  },
  {
    id: 'sal-102', tema: 'ecologia', dificultad: 1,
    enunciado: 'En una cadena trófica, los organismos que fabrican su propio alimento se llaman:',
    opciones: ['Productores', 'Consumidores primarios', 'Descomponedores', 'Depredadores'],
    correcta: 0,
    explicacion: 'Las plantas y las algas capturan energía solar por fotosíntesis. Los descomponedores, como hongos y bacterias, devuelven la materia al suelo.',
  },
  {
    id: 'sal-103', tema: 'ecologia', dificultad: 2,
    enunciado: 'En un ecosistema, la energía:',
    opciones: [
      'Fluye en un solo sentido y se va perdiendo como calor en cada nivel',
      'Circula en ciclo cerrado, igual que la materia',
      'Se conserva íntegra al pasar de un nivel a otro',
      'Solo la aprovechan los depredadores',
    ],
    correcta: 0,
    explicacion: 'La materia sí se recicla en ciclos; la energía no. Por eso el ecosistema necesita una entrada permanente de energía solar.',
  },
  {
    id: 'sal-104', tema: 'ecologia', dificultad: 3,
    enunciado: 'Al pasar de un nivel trófico al siguiente, la energía disponible es aproximadamente:',
    opciones: [
      'El 10 % de la del nivel anterior',
      'El 90 % de la del nivel anterior',
      'La misma que en el nivel anterior',
      'El doble que en el nivel anterior',
    ],
    correcta: 0,
    explicacion: 'El resto se disipa en respiración, movimiento y calor. Esa regla explica por qué las cadenas tróficas rara vez pasan de cuatro o cinco eslabones y por qué hay pocos grandes depredadores.',
    pista: 'Piensa cuánta energía usa un animal solo en mantenerse vivo.',
  },
  {
    id: 'sal-105', tema: 'ecologia', dificultad: 2,
    enunciado: 'La fotosíntesis y la respiración celular se relacionan porque:',
    opciones: [
      'Una consume CO₂ y libera O₂, y la otra hace lo contrario',
      'Las dos liberan oxígeno',
      'Las dos ocurren solo de día',
      'Ninguna interviene en el ciclo del carbono',
    ],
    correcta: 0,
    explicacion: 'Juntas mantienen el ciclo del carbono y del oxígeno. Las plantas también respiran: la fotosíntesis es adicional, no un reemplazo.',
  },
  {
    id: 'sal-106', tema: 'ecologia', dificultad: 2,
    enunciado: 'Ordena de menor a mayor: comunidad, población, ecosistema.',
    opciones: [
      'Población, comunidad, ecosistema',
      'Comunidad, población, ecosistema',
      'Ecosistema, comunidad, población',
      'Población, ecosistema, comunidad',
    ],
    correcta: 0,
    explicacion: 'Población es un conjunto de individuos de la misma especie; comunidad reúne a todas las poblaciones del lugar; el ecosistema añade el medio físico.',
  },
  {
    id: 'sal-107', tema: 'ecologia', dificultad: 2,
    enunciado: 'La relación entre una garrapata y un perro es un ejemplo de:',
    opciones: ['Parasitismo', 'Mutualismo', 'Comensalismo', 'Competencia'],
    correcta: 0,
    explicacion: 'Uno se beneficia y el otro resulta perjudicado. En el mutualismo ganan los dos y en el comensalismo uno gana y el otro ni gana ni pierde.',
  },
  {
    id: 'sal-108', tema: 'ecologia', dificultad: 3,
    enunciado: 'Si en un ecosistema se eliminan los depredadores de una especie herbívora, lo más probable a corto plazo es que:',
    opciones: [
      'La población de herbívoros crezca y la vegetación disminuya',
      'La población de herbívoros se mantenga igual',
      'La vegetación aumente sin límite',
      'Los herbívoros se extingan por falta de competencia',
    ],
    correcta: 0,
    explicacion: 'Al quitar el control, los herbívoros se multiplican hasta agotar su alimento, y entonces la población colapsa. Es un efecto en cascada típico de las cadenas tróficas.',
  },
  {
    id: 'sal-109', tema: 'ecologia', dificultad: 2,
    enunciado: 'La capacidad de carga de un ecosistema es:',
    opciones: [
      'El número máximo de individuos de una especie que puede sostener de forma indefinida',
      'El peso total de la vegetación que contiene',
      'La cantidad de energía solar que recibe al año',
      'El número de especies distintas que alberga',
    ],
    correcta: 0,
    explicacion: 'La fijan los recursos disponibles: alimento, agua y espacio. Superarla conduce a un deterioro del ambiente y a una caída de la población.',
  },
  {
    id: 'sal-110', tema: 'ecologia', dificultad: 3,
    enunciado: 'Un contaminante persistente se encuentra en mayor concentración en los peces grandes que en los pequeños. El fenómeno se llama:',
    opciones: [
      'Bioacumulación a lo largo de la cadena trófica',
      'Fotosíntesis acelerada',
      'Eutrofización del agua',
      'Deriva génica',
    ],
    correcta: 0,
    explicacion: 'Cada depredador acumula lo que traían todas sus presas, así que la concentración sube nivel a nivel. Por eso se recomienda moderar el consumo de peces grandes con mercurio.',
  },

  // ----- Evolución -----
  {
    id: 'sal-111', tema: 'evolucion', dificultad: 1,
    enunciado: 'La selección natural propuesta por Darwin sostiene que:',
    opciones: [
      'Los individuos mejor adaptados a su ambiente dejan en promedio más descendencia',
      'Los organismos desarrollan las características que necesitan',
      'Todas las especies evolucionan hacia formas más complejas',
      'Los cambios del ambiente modifican directamente el ADN',
    ],
    correcta: 0,
    explicacion: 'La variación ya existe en la población y el ambiente filtra cuál se reproduce más. La idea de que el uso genera el órgano es la hipótesis de Lamarck, hoy descartada.',
  },
  {
    id: 'sal-112', tema: 'evolucion', dificultad: 3,
    enunciado: 'Una jirafa no tiene el cuello largo porque sus ancestros lo estiraran. La explicación evolutiva correcta es que:',
    opciones: [
      'Ya existían variaciones en la longitud del cuello y las de cuello más largo sobrevivieron y se reprodujeron más',
      'El esfuerzo de estirarse modificó los genes que heredaron',
      'El ambiente ordenó a la especie alargar el cuello',
      'Todas las jirafas cambiaron a la vez',
    ],
    correcta: 0,
    explicacion: 'La mutación y la recombinación producen variación al azar; la selección actúa después. Es la diferencia central entre Darwin y Lamarck, y una de las preguntas más frecuentes del examen.',
    pista: 'Pregúntate si la variación aparece antes o después de la necesidad.',
  },
  {
    id: 'sal-113', tema: 'evolucion', dificultad: 2,
    enunciado: '¿Cuál de estas NO es una evidencia de la evolución?',
    opciones: [
      'La existencia de individuos más fuertes dentro de una especie',
      'El registro fósil',
      'Las semejanzas en el ADN entre especies emparentadas',
      'Las estructuras homólogas en distintos vertebrados',
    ],
    correcta: 0,
    explicacion: 'Que haya diferencias entre individuos es variación, no evidencia de descendencia con modificación. Las otras tres sí muestran el parentesco entre especies.',
  },
  {
    id: 'sal-114', tema: 'evolucion', dificultad: 2,
    enunciado: 'La aparición de bacterias resistentes a los antibióticos es un ejemplo de:',
    opciones: [
      'Selección natural observable en tiempo real',
      'Mutación provocada intencionalmente por la bacteria',
      'Adaptación aprendida y transmitida por contacto',
      'Un fenómeno sin relación con la evolución',
    ],
    correcta: 0,
    explicacion: 'El antibiótico elimina a las sensibles y deja que se multipliquen las que ya eran resistentes por azar. Por eso completar los tratamientos y no automedicarse es una medida evolutiva, además de médica.',
  },
  {
    id: 'sal-115', tema: 'evolucion', dificultad: 3,
    enunciado: 'Dos poblaciones de una misma especie quedan separadas por una cordillera durante miles de años. Lo más probable es que:',
    opciones: [
      'Acumulen diferencias y con el tiempo puedan convertirse en especies distintas',
      'Permanezcan idénticas indefinidamente',
      'Se extingan las dos por falta de contacto',
      'Se fusionen en una sola población mayor',
    ],
    correcta: 0,
    explicacion: 'Es la especiación por aislamiento geográfico: sin intercambio de genes, las mutaciones y la selección actúan por separado en cada población.',
  },
  {
    id: 'sal-116', tema: 'evolucion', dificultad: 3,
    enunciado: 'El ala de un murciélago y el brazo humano son estructuras homólogas porque:',
    opciones: [
      'Comparten el mismo origen y plan estructural aunque cumplan funciones distintas',
      'Cumplen la misma función aunque tengan orígenes distintos',
      'Tienen exactamente el mismo tamaño',
      'Evolucionaron de forma independiente',
    ],
    correcta: 0,
    explicacion: 'Las estructuras análogas son lo contrario: el ala de un insecto y la de un ave cumplen la misma función pero no comparten origen. Las homologías apuntan a un ancestro común.',
  },
  {
    id: 'sal-117', tema: 'evolucion', dificultad: 2,
    enunciado: 'Los pinzones de las islas Galápagos fueron importantes para Darwin porque:',
    opciones: [
      'Mostraban picos distintos según el alimento disponible en cada isla',
      'Eran idénticos entre sí en todas las islas',
      'No se reproducían en cautiverio',
      'Eran la única especie de ave del archipiélago',
    ],
    correcta: 0,
    explicacion: 'La variación de los picos sugería que una población original se había diversificado al ocupar ambientes distintos: es un caso de radiación adaptativa.',
  },
  {
    id: 'sal-118', tema: 'evolucion', dificultad: 2,
    enunciado: 'En términos evolutivos, una adaptación es:',
    opciones: [
      'Una característica heredable que mejora la supervivencia o la reproducción en un ambiente dado',
      'Un cambio que el individuo decide hacer para sobrevivir',
      'Una costumbre que se aprende y se transmite',
      'Una característica que aparece cuando el organismo la necesita',
    ],
    correcta: 0,
    explicacion: 'Tiene que ser heredable: lo que un individuo aprende o desarrolla durante su vida no se transmite en los genes.',
  },
  {
    id: 'sal-119', tema: 'evolucion', dificultad: 3,
    enunciado: 'Una población pequeña queda aislada tras una catástrofe y sus frecuencias genéticas cambian solo por azar. Eso se llama:',
    opciones: [
      'Deriva génica',
      'Selección natural',
      'Mutación dirigida',
      'Flujo génico',
    ],
    correcta: 0,
    explicacion: 'En poblaciones pequeñas el azar pesa más que la selección. El flujo génico, en cambio, es el intercambio de genes entre poblaciones distintas.',
  },
  {
    id: 'sal-120', tema: 'evolucion', dificultad: 2,
    enunciado: 'La evolución actúa sobre:',
    opciones: [
      'Las poblaciones a lo largo de generaciones, no sobre los individuos durante su vida',
      'Cada individuo, que evoluciona mientras vive',
      'Las especies completas de forma simultánea',
      'Solo los organismos de reproducción sexual',
    ],
    correcta: 0,
    explicacion: 'Un individuo nace, vive y muere con el genoma que le tocó. Lo que cambia con el tiempo es la frecuencia de las variantes dentro de la población.',
  },

  // ----- Biodiversidad y clasificación -----
  {
    id: 'sal-121', tema: 'biodiversidad', dificultad: 2,
    enunciado: 'La biodiversidad se mide en tres niveles:',
    opciones: [
      'Genética, de especies y de ecosistemas',
      'Vegetal, animal y mineral',
      'Terrestre, acuática y aérea',
      'Local, nacional e internacional',
    ],
    correcta: 0,
    explicacion: 'Perder variabilidad genética dentro de una especie también es perder biodiversidad, aunque la especie siga existiendo: la deja más vulnerable ante enfermedades.',
  },
  {
    id: 'sal-122', tema: 'biodiversidad', dificultad: 2,
    enunciado: '¿Cuál es el orden correcto de las categorías taxonómicas, de la más amplia a la más específica?',
    opciones: [
      'Reino, filo, clase, orden, familia, género, especie',
      'Especie, género, familia, orden, clase, filo, reino',
      'Reino, clase, filo, familia, orden, especie, género',
      'Filo, reino, orden, clase, género, familia, especie',
    ],
    correcta: 0,
    explicacion: 'Cada categoría agrupa a las inferiores. La especie es la unidad básica de la clasificación.',
  },
  {
    id: 'sal-123', tema: 'biodiversidad', dificultad: 2,
    enunciado: 'El nombre científico de una especie, como Homo sapiens, está formado por:',
    opciones: [
      'El género, con inicial mayúscula, y el epíteto específico, en minúscula',
      'El reino y la familia',
      'El país de origen y el descubridor',
      'Dos nombres comunes traducidos al latín',
    ],
    correcta: 0,
    explicacion: 'Es la nomenclatura binomial de Linneo. Se escribe en cursiva o subrayada, y evita la confusión que producen los nombres comunes de cada región.',
  },
  {
    id: 'sal-124', tema: 'biodiversidad', dificultad: 3,
    enunciado: 'El criterio biológico más usado para definir una especie es que sus individuos:',
    opciones: [
      'Pueden cruzarse entre sí y dejar descendencia fértil',
      'Tienen el mismo aspecto externo',
      'Viven en la misma región geográfica',
      'Se alimentan de lo mismo',
    ],
    correcta: 0,
    explicacion: 'Por eso el caballo y el burro son especies distintas: su cruce produce mulas, que son estériles. El aspecto externo puede engañar en los dos sentidos.',
  },
  {
    id: 'sal-125', tema: 'biodiversidad', dificultad: 2,
    enunciado: '¿Cuál es la diferencia fundamental entre una célula procariota y una eucariota?',
    opciones: [
      'La eucariota tiene núcleo definido y organelos membranosos; la procariota no',
      'La procariota es más grande',
      'La eucariota no tiene ADN',
      'La procariota solo existe en los virus',
    ],
    correcta: 0,
    explicacion: 'Las bacterias son procariotas y su ADN está libre en el citoplasma. Animales, plantas, hongos y protistas son eucariotas.',
  },
  {
    id: 'sal-126', tema: 'biodiversidad', dificultad: 3,
    enunciado: '¿Por qué los virus no se consideran seres vivos en el sentido estricto?',
    opciones: [
      'Porque no tienen metabolismo propio y solo se reproducen dentro de una célula huésped',
      'Porque no contienen material genético',
      'Porque son demasiado pequeños',
      'Porque no causan enfermedades en todos los organismos',
    ],
    correcta: 0,
    explicacion: 'Sí tienen material genético, pero fuera de una célula son partículas inertes. Es un caso donde la frontera de la definición de vida se vuelve borrosa.',
  },
  {
    id: 'sal-127', tema: 'biodiversidad', dificultad: 1,
    enunciado: 'En la fotosíntesis, las plantas transforman:',
    opciones: [
      'Dióxido de carbono y agua en glucosa y oxígeno, usando energía luminosa',
      'Oxígeno y glucosa en dióxido de carbono y agua',
      'Nitrógeno del aire en proteínas',
      'Minerales del suelo en energía luminosa',
    ],
    correcta: 0,
    explicacion: 'Ocurre en los cloroplastos, gracias a la clorofila. Es la puerta de entrada de la energía a casi todos los ecosistemas.',
  },
  {
    id: 'sal-128', tema: 'biodiversidad', dificultad: 2,
    enunciado: '¿Cuál es hoy la principal causa de pérdida de biodiversidad en el mundo?',
    opciones: [
      'La destrucción y fragmentación de los hábitats',
      'Las erupciones volcánicas',
      'La competencia natural entre especies',
      'Los cambios en la órbita terrestre',
    ],
    correcta: 0,
    explicacion: 'Le siguen las especies invasoras, la sobreexplotación, la contaminación y el cambio climático. Casi todas tienen origen humano.',
  },
  {
    id: 'sal-129', tema: 'biodiversidad', dificultad: 2,
    enunciado: 'La polinización realizada por abejas y otros insectos es un ejemplo de:',
    opciones: [
      'Servicio ecosistémico del que depende buena parte de la producción de alimentos',
      'Una relación de parasitismo',
      'Un proceso exclusivo de las plantas ornamentales',
      'Un fenómeno sin valor económico',
    ],
    correcta: 0,
    explicacion: 'Una fracción muy alta de los cultivos que consumimos depende de polinizadores. Es la razón por la que su declive se considera un problema económico y no solo ambiental.',
  },
  {
    id: 'sal-130', tema: 'biodiversidad', dificultad: 2,
    enunciado: 'Una especie endémica de un territorio es aquella que:',
    opciones: [
      'Solo existe de forma natural en ese lugar',
      'Fue introducida desde otro continente',
      'Está presente en todos los continentes',
      'Se encuentra en peligro de extinción',
    ],
    correcta: 0,
    explicacion: 'El endemismo eleva el valor de conservación: si desaparece allí, desaparece del planeta. No es lo mismo que estar amenazada, aunque muchas endémicas lo estén.',
  },

  // ----- Indagación y método científico -----
  {
    id: 'sal-131', tema: 'indagacion', dificultad: 2,
    enunciado: '¿Cuál de estas es una pregunta investigable científicamente?',
    opciones: [
      '¿Influye la cantidad de luz en el crecimiento de una planta de frijol?',
      '¿Cuál es la planta más bonita del jardín?',
      '¿Deberían las personas tener plantas en casa?',
      '¿Qué significa para mí cuidar una planta?',
    ],
    correcta: 0,
    explicacion: 'Una pregunta investigable se puede poner a prueba con observaciones o experimentos y tiene variables medibles. Las demás son de gusto, de valor o de significado personal.',
  },
  {
    id: 'sal-132', tema: 'indagacion', dificultad: 2,
    enunciado: 'Una hipótesis científica es:',
    opciones: [
      'Una explicación provisional que se puede poner a prueba y resultar falsa',
      'Una conclusión ya demostrada',
      'Una opinión personal sobre el tema',
      'El resultado final del experimento',
    ],
    correcta: 0,
    explicacion: 'Si no hay manera de que los datos la contradigan, no es una hipótesis científica. Poder ser falsada es justamente lo que la hace útil.',
  },
  {
    id: 'sal-133', tema: 'indagacion', dificultad: 2,
    enunciado: 'En un experimento sobre el efecto del fertilizante en el crecimiento de unas plantas, la variable independiente es:',
    opciones: [
      'La cantidad de fertilizante aplicada',
      'La altura alcanzada por las plantas',
      'La cantidad de agua recibida',
      'El tipo de maceta utilizada',
    ],
    correcta: 0,
    explicacion: 'La independiente es la que el investigador manipula; la dependiente es la que se mide como resultado, en este caso la altura. Las demás deben mantenerse constantes.',
  },
  {
    id: 'sal-134', tema: 'indagacion', dificultad: 2,
    enunciado: '¿Para qué sirve el grupo control en un experimento?',
    opciones: [
      'Para comparar: es igual al grupo experimental salvo en la variable que se estudia',
      'Para repetir el experimento una segunda vez',
      'Para aumentar el número de participantes',
      'Para confirmar la hipótesis del investigador',
    ],
    correcta: 0,
    explicacion: 'Sin un punto de comparación no se sabe si el cambio se debe al tratamiento o habría ocurrido de todos modos.',
  },
  {
    id: 'sal-135', tema: 'indagacion', dificultad: 3,
    enunciado: 'Un estudiante cambia a la vez el tipo de suelo y la cantidad de agua entre sus dos grupos de plantas. El problema de ese diseño es que:',
    opciones: [
      'No podrá saber cuál de las dos variables causó la diferencia',
      'Necesita más plantas en cada grupo',
      'El experimento dura demasiado tiempo',
      'No hay ninguno: cambiar dos variables acelera el estudio',
    ],
    correcta: 0,
    explicacion: 'Es el principio de la variable única: para atribuir un efecto hay que cambiar una sola cosa y dejar el resto igual. Con dos cambios simultáneos el resultado es ininterpretable.',
    pista: 'Si dos cosas cambian a la vez, ¿cuál explica el resultado?',
  },
  {
    id: 'sal-136', tema: 'indagacion', dificultad: 2,
    enunciado: '¿Por qué un experimento debe repetirse varias veces?',
    opciones: [
      'Para reducir el efecto del azar y comprobar que el resultado es consistente',
      'Para que dure más y parezca más serio',
      'Porque la primera medición siempre está mal',
      'Para poder cambiar la hipótesis si hace falta',
    ],
    correcta: 0,
    explicacion: 'Un solo dato puede ser una casualidad. La repetición, propia y de otros equipos, es lo que convierte un resultado en un hallazgo confiable.',
  },
  {
    id: 'sal-137', tema: 'indagacion', dificultad: 3,
    enunciado: 'La tabla muestra el resultado de un experimento con tres grupos de plantas regadas con distintas cantidades de agua. ¿Qué conclusión se puede sostener con estos datos?',
    codigo: [
      'Grupo   Agua por día   Altura a los 30 días',
      '  A         50 mL            12 cm',
      '  B        100 mL            21 cm',
      '  C        200 mL            11 cm',
    ].join('\n'),
    opciones: [
      'Existe una cantidad intermedia de agua que favorece más el crecimiento',
      'A más agua, mayor crecimiento siempre',
      'El agua no influye en el crecimiento',
      'El grupo C recibió una planta defectuosa',
    ],
    correcta: 0,
    explicacion: 'La relación no es lineal: sube hasta 100 mL y vuelve a bajar con 200 mL, probablemente por exceso de agua. Conviene no extrapolar más allá de lo medido ni inventar causas que los datos no muestran.',
  },
  {
    id: 'sal-138', tema: 'indagacion', dificultad: 2,
    enunciado: 'Si los resultados de un experimento contradicen la hipótesis inicial, lo correcto es:',
    opciones: [
      'Reportarlos tal como son y revisar la hipótesis',
      'Repetir el experimento hasta obtener el resultado esperado',
      'Descartar los datos que no encajan',
      'Cambiar la hipótesis y presentarla como si hubiera sido la original',
    ],
    correcta: 0,
    explicacion: 'Una hipótesis refutada es un resultado legítimo y a veces el más valioso. Seleccionar solo los datos que confirman lo esperado es una de las formas más comunes de mala ciencia.',
  },
  {
    id: 'sal-139', tema: 'indagacion', dificultad: 3,
    enunciado: 'Un estudio observa que los niños que desayunan tienen mejores notas. Antes de concluir que el desayuno mejora el rendimiento, hay que considerar que:',
    opciones: [
      'Podría haber un tercer factor, como el entorno familiar, que explique las dos cosas',
      'La muestra siempre es demasiado pequeña en este tipo de estudios',
      'Las notas no son un dato medible',
      'El desayuno no tiene ninguna relación con el aprendizaje',
    ],
    correcta: 0,
    explicacion: 'Es un estudio observacional, no un experimento: muestra asociación, no causa. Para afirmar causalidad haría falta asignar el desayuno al azar y comparar grupos.',
  },
  {
    id: 'sal-140', tema: 'indagacion', dificultad: 2,
    enunciado: 'En ciencia, una teoría es:',
    opciones: [
      'Una explicación amplia y bien respaldada por evidencia acumulada',
      'Una suposición sin comprobar',
      'Una idea menos segura que una hipótesis',
      'Una opinión de un científico reconocido',
    ],
    correcta: 0,
    explicacion: 'En el lenguaje cotidiano "teoría" sugiere una conjetura; en ciencia es lo contrario. La teoría de la evolución o la teoría celular están entre los conocimientos mejor sustentados que existen.',
  },
];
