/**
 * trigonometria.js — Banco de trigonometría.
 *
 * Del triángulo rectángulo a las identidades y las leyes de senos y cosenos.
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const TRIGONOMETRIA = [
  // ----- Ángulos, grados y radianes -----
  {
    id: 'tri-001', tema: 'angulos', dificultad: 1,
    enunciado: '¿A cuántos radianes equivalen 135°?',
    opciones: ['3π/4', '2π/3', '5π/6', '4π/3'],
    correcta: 0,
    explicacion: 'Se multiplica por π/180: 135 × π/180 = 135π/180 = 3π/4.',
  },
  {
    id: 'tri-002', tema: 'angulos', dificultad: 1,
    enunciado: '¿A cuántos grados equivalen 5π/6 radianes?',
    opciones: ['150°', '120°', '210°', '135°'],
    correcta: 0,
    explicacion: 'Se multiplica por 180/π: (5π/6)(180/π) = 5 × 30 = 150°.',
  },
  {
    id: 'tri-003', tema: 'angulos', dificultad: 2,
    enunciado: '¿Cuál es el menor ángulo positivo coterminal con −100°?',
    opciones: ['260°', '280°', '100°', '160°'],
    correcta: 0,
    explicacion: 'Se suma una vuelta completa: −100° + 360° = 260°.',
  },
  {
    id: 'tri-004', tema: 'angulos', dificultad: 2,
    enunciado: 'En una circunferencia de radio 6 cm, ¿cuál es la longitud del arco que abarca un ángulo central de π/3 radianes?',
    opciones: ['2π cm', 'π cm', '6π cm', '3π cm'],
    correcta: 0,
    explicacion: 's = rθ con θ en radianes: 6 × π/3 = 2π cm.',
    pista: 'La fórmula s = rθ solo sirve con el ángulo en radianes.',
  },
  {
    id: 'tri-005', tema: 'angulos', dificultad: 3,
    enunciado: '¿Cuál es el ángulo de referencia de 225°?',
    opciones: ['45°', '135°', '225°', '30°'],
    correcta: 0,
    explicacion: '225° está en el tercer cuadrante, así que el ángulo de referencia es 225° − 180° = 45°.',
  },

  // ----- Triángulo rectángulo -----
  {
    id: 'tri-006', tema: 'triangulo-rectangulo', dificultad: 1,
    enunciado: 'En un triángulo rectángulo los catetos miden 3 y 4. ¿Cuál es el seno del ángulo opuesto al cateto de 3?',
    opciones: ['3/5', '4/5', '3/4', '5/3'],
    correcta: 0,
    explicacion: 'La hipotenusa es 5. El seno es cateto opuesto sobre hipotenusa: 3/5.',
  },
  {
    id: 'tri-007', tema: 'triangulo-rectangulo', dificultad: 2,
    enunciado: 'Si tan θ = 5/12 y θ es agudo, ¿cuánto vale sec θ?',
    opciones: ['13/12', '12/13', '13/5', '5/13'],
    correcta: 0,
    explicacion: 'Con cateto opuesto 5 y adyacente 12, la hipotenusa es 13. Como sec θ = hipotenusa/adyacente, vale 13/12.',
  },
  {
    id: 'tri-008', tema: 'triangulo-rectangulo', dificultad: 2,
    enunciado: 'Si cos θ = 8/17 y θ es agudo, ¿cuánto vale sen θ?',
    opciones: ['15/17', '17/15', '8/15', '15/8'],
    correcta: 0,
    explicacion: 'El cateto opuesto es √(17² − 8²) = √(289 − 64) = √225 = 15, así que sen θ = 15/17.',
  },
  {
    id: 'tri-009', tema: 'triangulo-rectangulo', dificultad: 2,
    enunciado: 'En un triángulo rectángulo, la hipotenusa mide 20 cm y un ángulo agudo mide 30°. ¿Cuánto mide el cateto opuesto a ese ángulo?',
    opciones: ['10 cm', '10√3 cm', '20√3 cm', '15 cm'],
    correcta: 0,
    explicacion: 'cateto opuesto = 20 · sen 30° = 20 × 0,5 = 10 cm.',
  },

  // ----- Ángulos notables -----
  {
    id: 'tri-010', tema: 'notables', dificultad: 1,
    enunciado: '¿Cuánto vale sen 30° + cos 60°?',
    opciones: ['1', '1/2', '√3/2', '0'],
    correcta: 0,
    explicacion: 'sen 30° = 1/2 y cos 60° = 1/2, así que la suma es 1.',
  },
  {
    id: 'tri-011', tema: 'notables', dificultad: 2,
    enunciado: '¿Cuánto vale tan 60° · cos 30°?',
    opciones: ['3/2', '√3/2', '1', '3'],
    correcta: 0,
    explicacion: 'tan 60° = √3 y cos 30° = √3/2. El producto es √3 × √3/2 = 3/2.',
  },
  {
    id: 'tri-012', tema: 'notables', dificultad: 2,
    enunciado: '¿Cuál es el valor exacto de sen 45° · cos 45° + sen 30°?',
    opciones: ['1', '1/2', '√2/2', '3/4'],
    correcta: 0,
    explicacion: 'sen 45° · cos 45° = (√2/2)(√2/2) = 2/4 = 1/2. Sumando sen 30° = 1/2 da 1.',
  },
  {
    id: 'tri-013', tema: 'notables', dificultad: 3,
    enunciado: 'Evalúa 2 sen²60° + 3 cos²30° − tan²45°.',
    opciones: ['11/4', '5/4', '2', '15/4'],
    correcta: 0,
    explicacion: 'sen²60° = 3/4 y cos²30° = 3/4, y tan 45° = 1. Entonces 2(3/4) + 3(3/4) − 1 = 3/2 + 9/4 − 1 = 11/4.',
  },

  // ----- Circunferencia unitaria -----
  {
    id: 'tri-014', tema: 'circunferencia', dificultad: 1,
    enunciado: 'Si un ángulo está en el segundo cuadrante, ¿cuál de estas razones es positiva?',
    opciones: ['El seno', 'El coseno', 'La tangente', 'La secante'],
    correcta: 0,
    explicacion: 'En el segundo cuadrante x es negativa y y positiva: solo el seno (y su recíproca, la cosecante) es positivo.',
    pista: 'Todas, Seno, Tangente, Coseno: el orden de los cuadrantes I, II, III y IV.',
  },
  {
    id: 'tri-015', tema: 'circunferencia', dificultad: 2,
    enunciado: '¿Cuánto vale sen 210°?',
    opciones: ['−1/2', '1/2', '−√3/2', '√3/2'],
    correcta: 0,
    explicacion: '210° está en el tercer cuadrante (seno negativo) y su ángulo de referencia es 30°, así que sen 210° = −sen 30° = −1/2.',
  },
  {
    id: 'tri-016', tema: 'circunferencia', dificultad: 2,
    enunciado: '¿Cuánto vale cos 300°?',
    opciones: ['1/2', '−1/2', '√3/2', '−√3/2'],
    correcta: 0,
    explicacion: '300° está en el cuarto cuadrante (coseno positivo) con ángulo de referencia 60°: cos 300° = cos 60° = 1/2.',
  },
  {
    id: 'tri-017', tema: 'circunferencia', dificultad: 3,
    enunciado: 'Si sen θ = −3/5 y θ está en el cuarto cuadrante, ¿cuánto vale tan θ?',
    opciones: ['−3/4', '3/4', '−4/3', '4/3'],
    correcta: 0,
    explicacion: 'En el cuarto cuadrante el coseno es positivo: cos θ = 4/5. Entonces tan θ = (−3/5)/(4/5) = −3/4.',
  },

  // ----- Identidades -----
  {
    id: 'tri-018', tema: 'identidades', dificultad: 1,
    enunciado: 'Simplifica sec²x − tan²x.',
    opciones: ['1', '0', 'sen²x', 'sec x'],
    correcta: 0,
    explicacion: 'Es una identidad pitagórica: 1 + tan²x = sec²x, así que sec²x − tan²x = 1.',
  },
  {
    id: 'tri-019', tema: 'identidades', dificultad: 2,
    enunciado: 'Simplifica (1 − cos²x)/sen x, con sen x ≠ 0.',
    opciones: ['sen x', 'cos x', 'tan x', 'csc x'],
    correcta: 0,
    explicacion: '1 − cos²x = sen²x, y sen²x/sen x = sen x.',
  },
  {
    id: 'tri-020', tema: 'identidades', dificultad: 2,
    enunciado: 'Simplifica sen²x (1 + cot²x).',
    opciones: ['1', 'sen²x', 'cos²x', 'tan²x'],
    correcta: 0,
    explicacion: '1 + cot²x = csc²x, y sen²x · csc²x = sen²x / sen²x = 1.',
  },
  {
    id: 'tri-021', tema: 'identidades', dificultad: 3,
    enunciado: 'Simplifica (1 + tan²x)/csc²x.',
    opciones: ['tan²x', 'sec²x', '1', 'cot²x'],
    correcta: 0,
    explicacion: '1 + tan²x = sec²x, y dividir entre csc²x es multiplicar por sen²x: sec²x · sen²x = sen²x/cos²x = tan²x.',
  },

  // ----- Suma, resta y ángulo doble -----
  {
    id: 'tri-022', tema: 'suma-angulos', dificultad: 1,
    enunciado: '¿A qué es igual cos(A − B)?',
    opciones: ['cos A cos B + sen A sen B', 'cos A cos B − sen A sen B', 'sen A cos B − cos A sen B', 'cos A − cos B'],
    correcta: 0,
    explicacion: 'En la resta de cosenos el signo del desarrollo se invierte respecto al de la suma: cos(A − B) = cos A cos B + sen A sen B.',
  },
  {
    id: 'tri-023', tema: 'suma-angulos', dificultad: 2,
    enunciado: '¿Cuál es el valor exacto de sen 75°?',
    opciones: ['(√6 + √2)/4', '(√6 − √2)/4', '(√3 + 1)/2', '√2/2'],
    correcta: 0,
    explicacion: 'sen 75° = sen(45° + 30°) = sen45·cos30 + cos45·sen30 = (√2/2)(√3/2) + (√2/2)(1/2) = (√6 + √2)/4.',
  },
  {
    id: 'tri-024', tema: 'suma-angulos', dificultad: 2,
    enunciado: 'Si sen x = 3/5 y x es agudo, ¿cuánto vale sen 2x?',
    opciones: ['24/25', '6/5', '7/25', '12/25'],
    correcta: 0,
    explicacion: 'cos x = 4/5. Entonces sen 2x = 2 sen x cos x = 2(3/5)(4/5) = 24/25.',
  },
  {
    id: 'tri-025', tema: 'suma-angulos', dificultad: 3,
    enunciado: 'Si cos x = 1/3, ¿cuánto vale cos 2x?',
    opciones: ['−7/9', '7/9', '2/9', '−1/9'],
    correcta: 0,
    explicacion: 'cos 2x = 2cos²x − 1 = 2(1/9) − 1 = 2/9 − 1 = −7/9.',
  },

  // ----- Ecuaciones trigonométricas -----
  {
    id: 'tri-026', tema: 'ecuaciones-trig', dificultad: 1,
    enunciado: 'Resuelve 2 sen x − 1 = 0 en el intervalo [0°, 360°).',
    opciones: ['30° y 150°', '30° y 330°', '60° y 120°', 'Solo 30°'],
    correcta: 0,
    explicacion: 'sen x = 1/2. El seno es positivo en los cuadrantes I y II: x = 30° y x = 180° − 30° = 150°.',
  },
  {
    id: 'tri-027', tema: 'ecuaciones-trig', dificultad: 2,
    enunciado: 'Resuelve tan x = −1 en el intervalo [0, 2π).',
    opciones: ['3π/4 y 7π/4', 'π/4 y 5π/4', '3π/4 y 5π/4', 'π/4 y 7π/4'],
    correcta: 0,
    explicacion: 'La tangente es negativa en los cuadrantes II y IV, con ángulo de referencia π/4: x = 3π/4 y x = 7π/4.',
  },
  {
    id: 'tri-028', tema: 'ecuaciones-trig', dificultad: 3,
    enunciado: 'Resuelve 2cos²x − cos x − 1 = 0 en [0°, 360°).',
    opciones: ['0°, 120° y 240°', '60° y 300°', '0° y 180°', '120° y 240°'],
    correcta: 0,
    explicacion: 'Factorizando en la variable cos x: (2cos x + 1)(cos x − 1) = 0. De cos x = 1 sale x = 0°; de cos x = −1/2 salen 120° y 240°.',
    pista: 'Trátala como una cuadrática en cos x.',
  },

  // ----- Gráficas -----
  {
    id: 'tri-029', tema: 'graficas-trig', dificultad: 2,
    enunciado: 'En y = 3 sen(2x − π), ¿cuáles son la amplitud y el periodo?',
    opciones: ['Amplitud 3, periodo π', 'Amplitud 3, periodo 2π', 'Amplitud 2, periodo π', 'Amplitud 6, periodo π/2'],
    correcta: 0,
    explicacion: 'La amplitud es |A| = 3 y el periodo es 2π/|B| = 2π/2 = π.',
  },
  {
    id: 'tri-030', tema: 'graficas-trig', dificultad: 2,
    enunciado: '¿Cuál es el periodo de y = tan(3x)?',
    opciones: ['π/3', '2π/3', 'π', '3π'],
    correcta: 0,
    explicacion: 'La tangente tiene periodo π, así que el de tan(Bx) es π/|B| = π/3.',
    pista: 'Ojo: el periodo de la tangente no es 2π.',
  },
  {
    id: 'tri-031', tema: 'graficas-trig', dificultad: 3,
    enunciado: '¿Cuál es el rango de y = −2 cos(x/2) + 1?',
    opciones: ['[−1, 3]', '[−2, 2]', '[−3, 1]', '[0, 2]'],
    correcta: 0,
    explicacion: 'cos varía entre −1 y 1, así que −2cos varía entre −2 y 2; sumando 1 el rango queda [−1, 3]. El factor x/2 cambia el periodo, no el rango.',
  },

  // ----- Leyes de senos y cosenos -----
  {
    id: 'tri-032', tema: 'leyes', dificultad: 2,
    enunciado: 'En un triángulo, a = 10, A = 30° y B = 45°. ¿Cuánto mide el lado b?',
    opciones: ['10√2', '10√3', '5√2', '20'],
    correcta: 0,
    explicacion: 'Por la ley de senos: b = a·sen B/sen A = 10 × (√2/2)/(1/2) = 10√2 ≈ 14,14.',
  },
  {
    id: 'tri-033', tema: 'leyes', dificultad: 2,
    enunciado: 'Dos lados de un triángulo miden 5 y 8, y el ángulo entre ellos es 60°. ¿Cuánto mide el tercer lado?',
    opciones: ['7', '√89', '9', '11'],
    correcta: 0,
    explicacion: 'Ley de cosenos: c² = 25 + 64 − 2(5)(8)cos60° = 89 − 40 = 49, así que c = 7.',
  },
  {
    id: 'tri-034', tema: 'leyes', dificultad: 3,
    enunciado: 'Un triángulo tiene lados 7, 8 y 9. ¿Cuánto vale el coseno del ángulo opuesto al lado 9?',
    opciones: ['2/7', '1/7', '3/7', '11/14'],
    correcta: 0,
    explicacion: 'cos C = (7² + 8² − 9²)/(2·7·8) = (49 + 64 − 81)/112 = 32/112 = 2/7.',
  },
  {
    id: 'tri-035', tema: 'leyes', dificultad: 2,
    enunciado: '¿Cuál es el área de un triángulo con lados 12 y 9 que forman un ángulo de 30°?',
    opciones: ['27', '54', '108', '13,5'],
    correcta: 0,
    explicacion: 'Área = (1/2)ab·sen C = (1/2)(12)(9)(0,5) = 27.',
  },

  // ----- Aplicaciones -----
  {
    id: 'tri-036', tema: 'aplicaciones', dificultad: 2,
    enunciado: 'Desde un punto en el suelo, a 60 m de la base de una torre, el ángulo de elevación de su punta es 30°. ¿Cuál es la altura de la torre?',
    opciones: ['20√3 m', '30 m', '60√3 m', '30√3 m'],
    correcta: 0,
    explicacion: 'h = 60 · tan 30° = 60 × (√3/3) = 20√3 ≈ 34,6 m.',
  },
  {
    id: 'tri-037', tema: 'aplicaciones', dificultad: 2,
    enunciado: 'Una escalera de 10 m se apoya en una pared formando 60° con el suelo. ¿A qué altura llega sobre la pared?',
    opciones: ['5√3 m', '5 m', '10√3 m', '8 m'],
    correcta: 0,
    explicacion: 'La altura es el cateto opuesto al ángulo: 10 · sen 60° = 10(√3/2) = 5√3 ≈ 8,66 m.',
  },
  {
    id: 'tri-038', tema: 'aplicaciones', dificultad: 3,
    enunciado: 'Desde lo alto de un faro de 45 m, el ángulo de depresión de un bote es 45°. ¿A qué distancia horizontal está el bote de la base del faro?',
    opciones: ['45 m', '45√2 m', '22,5 m', '90 m'],
    correcta: 0,
    explicacion: 'El ángulo de depresión desde arriba es igual al de elevación desde el bote. Con 45°, la tangente vale 1, así que la distancia horizontal es igual a la altura: 45 m.',
  },

  // ----- Complemento hasta la meta de 10 por tema -----
  {
    id: 'tri-039', tema: 'angulos', dificultad: 1,
    enunciado: '¿A cuántos radianes equivalen 210°?',
    opciones: ['7π/6', '5π/6', '4π/3', '11π/6'],
    correcta: 0,
    explicacion: '210 × π/180 = 210π/180 = 7π/6.',
  },
  {
    id: 'tri-040', tema: 'angulos', dificultad: 1,
    enunciado: '¿A cuántos grados equivalen 3π/4 radianes?',
    opciones: ['135°', '120°', '45°', '225°'],
    correcta: 0,
    explicacion: '(3π/4)(180/π) = 3 × 45 = 135°.',
  },
  {
    id: 'tri-041', tema: 'angulos', dificultad: 2,
    enunciado: '¿Cuál es el ángulo de referencia de 300°?',
    opciones: ['60°', '30°', '120°', '300°'],
    correcta: 0,
    explicacion: '300° está en el cuarto cuadrante, así que su ángulo de referencia es 360° − 300° = 60°.',
  },
  {
    id: 'tri-042', tema: 'angulos', dificultad: 2,
    enunciado: 'En una circunferencia de radio 4, ¿cuál es el área del sector que abarca un ángulo central de π/2 radianes?',
    opciones: ['4π', '2π', '8π', '16π'],
    correcta: 0,
    explicacion: 'Área del sector = (1/2)r²θ = (1/2)(16)(π/2) = 4π. También se ve como un cuarto del círculo: 16π/4 = 4π.',
  },
  {
    id: 'tri-043', tema: 'angulos', dificultad: 2,
    enunciado: '¿Cuál es el menor ángulo positivo coterminal con 400°?',
    opciones: ['40°', '80°', '360°', '140°'],
    correcta: 0,
    explicacion: 'Se resta una vuelta completa: 400° − 360° = 40°.',
  },
  {
    id: 'tri-044', tema: 'triangulo-rectangulo', dificultad: 1,
    enunciado: 'Si tan θ = 2/3, ¿cuánto vale cot θ?',
    opciones: ['3/2', '2/3', '√13/3', '1/6'],
    correcta: 0,
    explicacion: 'La cotangente es el recíproco de la tangente: cot θ = 1/tan θ = 3/2.',
  },
  {
    id: 'tri-045', tema: 'triangulo-rectangulo', dificultad: 2,
    enunciado: 'Si sen θ = 7/25 y θ es agudo, ¿cuánto vale cos θ?',
    opciones: ['24/25', '25/24', '7/24', '18/25'],
    correcta: 0,
    explicacion: 'El cateto adyacente es √(25² − 7²) = √(625 − 49) = √576 = 24, así que cos θ = 24/25.',
  },
  {
    id: 'tri-046', tema: 'triangulo-rectangulo', dificultad: 2,
    enunciado: 'Si csc θ = 5/3 y θ es agudo, ¿cuánto vale cos θ?',
    opciones: ['4/5', '3/5', '5/4', '3/4'],
    correcta: 0,
    explicacion: 'csc θ = 5/3 implica sen θ = 3/5. Con el triángulo 3-4-5, cos θ = 4/5.',
  },
  {
    id: 'tri-047', tema: 'triangulo-rectangulo', dificultad: 2,
    enunciado: 'En un triángulo rectángulo la hipotenusa mide 26 y un cateto 10. ¿Cuánto mide el otro cateto?',
    opciones: ['24', '16', '36', '√776'],
    correcta: 0,
    explicacion: 'Por Pitágoras: 26² − 10² = 676 − 100 = 576, y √576 = 24. Es el triángulo 5-12-13 multiplicado por 2.',
  },
  {
    id: 'tri-048', tema: 'triangulo-rectangulo', dificultad: 1,
    enunciado: 'Si un ángulo agudo cumple cos θ = 1/2, ¿cuánto mide?',
    opciones: ['60°', '30°', '45°', '90°'],
    correcta: 0,
    explicacion: 'cos 60° = 1/2. El error frecuente es confundirlo con sen 30°, que también vale 1/2 pero corresponde a otro ángulo.',
  },
  {
    id: 'tri-049', tema: 'triangulo-rectangulo', dificultad: 3,
    enunciado: 'En un triángulo rectángulo uno de los ángulos agudos mide 45° y un cateto mide 6. ¿Cuánto mide el otro cateto?',
    opciones: ['6', '6√2', '3', '12'],
    correcta: 0,
    explicacion: 'Si un ángulo agudo mide 45°, el otro también, así que el triángulo es isósceles y los dos catetos son iguales. La hipotenusa sería 6√2.',
  },
  {
    id: 'tri-050', tema: 'notables', dificultad: 1,
    enunciado: '¿Cuánto vale cos 0° + sen 90°?',
    opciones: ['2', '1', '0', '√2'],
    correcta: 0,
    explicacion: 'cos 0° = 1 y sen 90° = 1, así que la suma es 2.',
  },
  {
    id: 'tri-051', tema: 'notables', dificultad: 1,
    enunciado: '¿Cuál es el valor exacto de tan 30°?',
    opciones: ['√3/3', '√3', '1/2', '√2/2'],
    correcta: 0,
    explicacion: 'tan 30° = sen 30°/cos 30° = (1/2)/(√3/2) = 1/√3, que racionalizado es √3/3.',
  },
  {
    id: 'tri-052', tema: 'notables', dificultad: 2,
    enunciado: '¿Cuánto vale sen²30° + cos²30°?',
    opciones: ['1', '1/2', '3/4', '√3/2'],
    correcta: 0,
    explicacion: 'Por la identidad pitagórica fundamental vale 1 para cualquier ángulo. Comprobado: 1/4 + 3/4 = 1.',
  },
  {
    id: 'tri-053', tema: 'notables', dificultad: 2,
    enunciado: '¿Cuánto vale sec 60°?',
    opciones: ['2', '1/2', '√3', '2√3/3'],
    correcta: 0,
    explicacion: 'sec 60° = 1/cos 60° = 1/(1/2) = 2.',
  },
  {
    id: 'tri-054', tema: 'notables', dificultad: 2,
    enunciado: 'Evalúa 4 · sen 30° · cos 60°.',
    opciones: ['1', '2', '1/2', '4'],
    correcta: 0,
    explicacion: 'sen 30° = 1/2 y cos 60° = 1/2, así que 4 × (1/2) × (1/2) = 1.',
  },
  {
    id: 'tri-055', tema: 'notables', dificultad: 2,
    enunciado: '¿Cuánto vale cot 45° + tan 45°?',
    opciones: ['2', '1', '0', '√2'],
    correcta: 0,
    explicacion: 'tan 45° = 1 y cot 45° = 1, así que la suma es 2.',
  },
  {
    id: 'tri-056', tema: 'circunferencia', dificultad: 2,
    enunciado: '¿Cuánto vale tan 135°?',
    opciones: ['−1', '1', '−√3', '√3/3'],
    correcta: 0,
    explicacion: '135° está en el segundo cuadrante, donde la tangente es negativa, y su ángulo de referencia es 45°: tan 135° = −tan 45° = −1.',
  },
  {
    id: 'tri-057', tema: 'circunferencia', dificultad: 1,
    enunciado: '¿Cuánto vale sen 180°?',
    opciones: ['0', '1', '−1', '1/2'],
    correcta: 0,
    explicacion: 'En la circunferencia unitaria, 180° corresponde al punto (−1, 0). El seno es la coordenada y, así que vale 0.',
  },
  {
    id: 'tri-058', tema: 'circunferencia', dificultad: 2,
    enunciado: '¿Cuánto vale cos 270°?',
    opciones: ['0', '−1', '1', '−1/2'],
    correcta: 0,
    explicacion: '270° corresponde al punto (0, −1). El coseno es la coordenada x, así que vale 0; el seno vale −1.',
  },
  {
    id: 'tri-059', tema: 'circunferencia', dificultad: 2,
    enunciado: 'Si un ángulo está en el tercer cuadrante, ¿qué razón es positiva?',
    opciones: ['La tangente', 'El seno', 'El coseno', 'La secante'],
    correcta: 0,
    explicacion: 'En el tercer cuadrante x e y son negativas, así que seno y coseno lo son; su cociente, la tangente, resulta positivo.',
  },
  {
    id: 'tri-060', tema: 'circunferencia', dificultad: 2,
    enunciado: '¿Cuánto vale sen(−30°)?',
    opciones: ['−1/2', '1/2', '−√3/2', '√3/2'],
    correcta: 0,
    explicacion: 'El seno es una función impar: sen(−x) = −sen(x). Por eso sen(−30°) = −1/2. El coseno, en cambio, es par.',
  },
  {
    id: 'tri-061', tema: 'circunferencia', dificultad: 3,
    enunciado: 'Al reducir 500° a un ángulo entre 0° y 360°, se obtiene:',
    opciones: ['140°', '180°', '40°', '220°'],
    correcta: 0,
    explicacion: '500° − 360° = 140°, que está en el segundo cuadrante con ángulo de referencia 40°.',
  },
  {
    id: 'tri-062', tema: 'identidades', dificultad: 1,
    enunciado: 'Simplifica tan x · cos x.',
    opciones: ['sen x', 'cos x', '1', 'sec x'],
    correcta: 0,
    explicacion: 'tan x = sen x / cos x, así que al multiplicar por cos x queda sen x.',
  },
  {
    id: 'tri-063', tema: 'identidades', dificultad: 1,
    enunciado: 'Simplifica csc x · sen x.',
    opciones: ['1', 'sen²x', 'cot x', 'cos x'],
    correcta: 0,
    explicacion: 'La cosecante es el recíproco del seno, así que su producto es 1.',
  },
  {
    id: 'tri-064', tema: 'identidades', dificultad: 1,
    enunciado: '¿A qué equivale 1 − sen²x?',
    opciones: ['cos²x', 'tan²x', 'sec²x', 'cot²x'],
    correcta: 0,
    explicacion: 'De sen²x + cos²x = 1 se despeja directamente cos²x = 1 − sen²x.',
  },
  {
    id: 'tri-065', tema: 'identidades', dificultad: 2,
    enunciado: 'Simplifica sec x · cos x.',
    opciones: ['1', 'sen x', 'tan x', 'cos²x'],
    correcta: 0,
    explicacion: 'La secante es el recíproco del coseno, de modo que el producto vale 1 siempre que cos x ≠ 0.',
  },
  {
    id: 'tri-066', tema: 'identidades', dificultad: 2,
    enunciado: '¿A qué equivale cos²x − 1?',
    opciones: ['−sen²x', 'sen²x', 'tan²x', '−1'],
    correcta: 0,
    explicacion: 'Como cos²x = 1 − sen²x, restar 1 deja −sen²x. Es el mismo despeje con el signo cambiado.',
  },
  {
    id: 'tri-067', tema: 'identidades', dificultad: 2,
    enunciado: '¿A qué equivale cot x?',
    opciones: ['cos x / sen x', 'sen x / cos x', '1 / cos x', '1 / sen x'],
    correcta: 0,
    explicacion: 'La cotangente es el recíproco de la tangente, y como tan x = sen x/cos x, se invierte el cociente.',
  },
  {
    id: 'tri-068', tema: 'suma-angulos', dificultad: 2,
    enunciado: '¿Cuál es el valor exacto de cos 75°?',
    opciones: ['(√6 − √2)/4', '(√6 + √2)/4', '(√3 − 1)/2', '√2/2'],
    correcta: 0,
    explicacion: 'cos 75° = cos(45° + 30°) = cos45·cos30 − sen45·sen30 = (√2/2)(√3/2) − (√2/2)(1/2) = (√6 − √2)/4.',
  },
  {
    id: 'tri-069', tema: 'suma-angulos', dificultad: 1,
    enunciado: '¿A qué es igual sen(A + B)?',
    opciones: [
      'sen A cos B + cos A sen B',
      'sen A cos B − cos A sen B',
      'cos A cos B − sen A sen B',
      'sen A + sen B',
    ],
    correcta: 0,
    explicacion: 'En el seno los términos se cruzan y el signo acompaña al de la suma; en el coseno el signo se invierte.',
  },
  {
    id: 'tri-070', tema: 'suma-angulos', dificultad: 2,
    enunciado: '¿A qué es igual tan 2x?',
    opciones: ['2 tan x / (1 − tan²x)', '2 tan x', 'tan²x − 1', '(1 − tan²x) / 2 tan x'],
    correcta: 0,
    explicacion: 'Sale de aplicar la fórmula de tan(A + B) con A = B = x.',
  },
  {
    id: 'tri-071', tema: 'suma-angulos', dificultad: 2,
    enunciado: 'Si cos x = 3/5 y x es agudo, ¿cuánto vale sen 2x?',
    opciones: ['24/25', '6/5', '7/25', '12/25'],
    correcta: 0,
    explicacion: 'Con cos x = 3/5, sen x = 4/5. Entonces sen 2x = 2 sen x cos x = 2(4/5)(3/5) = 24/25.',
  },
  {
    id: 'tri-072', tema: 'suma-angulos', dificultad: 3,
    enunciado: '¿Cuál es el valor exacto de cos 15°?',
    opciones: ['(√6 + √2)/4', '(√6 − √2)/4', '(√3 + 1)/4', '√3/2'],
    correcta: 0,
    explicacion: 'cos 15° = cos(45° − 30°) = cos45·cos30 + sen45·sen30 = (√6 + √2)/4. Coincide con sen 75°, porque son ángulos complementarios.',
  },
  {
    id: 'tri-073', tema: 'suma-angulos', dificultad: 2,
    enunciado: 'Si sen x = 1/2 y x es agudo, ¿cuánto vale sen 2x?',
    opciones: ['√3/2', '1', '1/2', '√3/4'],
    correcta: 0,
    explicacion: 'Con sen x = 1/2 el ángulo es 30° y cos x = √3/2. Entonces sen 2x = 2(1/2)(√3/2) = √3/2, que es justamente sen 60°.',
  },
  {
    id: 'tri-074', tema: 'ecuaciones-trig', dificultad: 1,
    enunciado: 'Resuelve cos x = 0 en el intervalo [0, 2π).',
    opciones: ['π/2 y 3π/2', 'Solo π/2', '0 y π', 'π y 2π'],
    correcta: 0,
    explicacion: 'El coseno es la coordenada x en la circunferencia unitaria y vale 0 en los puntos (0, 1) y (0, −1).',
  },
  {
    id: 'tri-075', tema: 'ecuaciones-trig', dificultad: 1,
    enunciado: 'Resuelve sen x = 0 en el intervalo [0°, 360°).',
    opciones: ['0° y 180°', 'Solo 0°', '90° y 270°', '180° y 360°'],
    correcta: 0,
    explicacion: 'El seno es la coordenada y y vale 0 en (1, 0) y (−1, 0). El 360° queda fuera del intervalo porque es abierto en ese extremo.',
  },
  {
    id: 'tri-076', tema: 'ecuaciones-trig', dificultad: 3,
    enunciado: '¿Cuántas soluciones tiene sen 2x = 0 en el intervalo [0, 2π)?',
    opciones: ['Cuatro', 'Dos', 'Tres', 'Una'],
    correcta: 0,
    explicacion: 'Si 2x recorre de 0 a 4π, el seno se anula en 0, π, 2π y 3π, lo que da x = 0, π/2, π y 3π/2. Al duplicar el ángulo se duplica el número de soluciones.',
    pista: 'Piensa qué intervalo recorre 2x cuando x va de 0 a 2π.',
  },
  {
    id: 'tri-077', tema: 'ecuaciones-trig', dificultad: 2,
    enunciado: 'Resuelve tan x = √3 en el intervalo [0°, 360°).',
    opciones: ['60° y 240°', '60° y 120°', '30° y 210°', 'Solo 60°'],
    correcta: 0,
    explicacion: 'La tangente es positiva en los cuadrantes I y III y su ángulo de referencia es 60°: x = 60° y x = 180° + 60° = 240°.',
  },
  {
    id: 'tri-078', tema: 'ecuaciones-trig', dificultad: 2,
    enunciado: 'Resuelve 2 cos x + √3 = 0 en [0°, 360°).',
    opciones: ['150° y 210°', '30° y 330°', '120° y 240°', '150° y 330°'],
    correcta: 0,
    explicacion: 'cos x = −√3/2. El coseno es negativo en los cuadrantes II y III y el ángulo de referencia es 30°: 180° − 30° = 150° y 180° + 30° = 210°.',
  },
  {
    id: 'tri-079', tema: 'ecuaciones-trig', dificultad: 3,
    enunciado: 'Resuelve sen²x = 1/4 en [0°, 360°).',
    opciones: ['30°, 150°, 210° y 330°', '30° y 150°', '60° y 120°', '210° y 330°'],
    correcta: 0,
    explicacion: 'Al sacar raíz aparecen dos casos: sen x = 1/2 da 30° y 150°, y sen x = −1/2 da 210° y 330°. Olvidar el signo negativo es el error clásico.',
  },
  {
    id: 'tri-080', tema: 'ecuaciones-trig', dificultad: 3,
    enunciado: 'Resuelve 4 sen²x − 3 = 0 en [0°, 360°).',
    opciones: ['60°, 120°, 240° y 300°', '60° y 120°', '30°, 150°, 210° y 330°', '240° y 300°'],
    correcta: 0,
    explicacion: 'sen²x = 3/4, así que sen x = ±√3/2. El positivo da 60° y 120°; el negativo, 240° y 300°.',
  },
  {
    id: 'tri-081', tema: 'graficas-trig', dificultad: 1,
    enunciado: '¿Cuál es la amplitud de y = −4 cos x?',
    opciones: ['4', '−4', '1', '8'],
    correcta: 0,
    explicacion: 'La amplitud es el valor absoluto del coeficiente: |−4| = 4. El signo negativo refleja la gráfica, pero no cambia su altura.',
  },
  {
    id: 'tri-082', tema: 'graficas-trig', dificultad: 1,
    enunciado: 'En y = sen x + 3, el término +3 produce:',
    opciones: [
      'Un desplazamiento vertical de 3 unidades hacia arriba',
      'Un aumento de la amplitud a 3',
      'Un desplazamiento horizontal de 3 unidades',
      'Un cambio de periodo a 3',
    ],
    correcta: 0,
    explicacion: 'En y = A sen(Bx + C) + D, el parámetro D mueve la gráfica verticalmente. El rango pasa de [−1, 1] a [2, 4].',
  },
  {
    id: 'tri-083', tema: 'graficas-trig', dificultad: 2,
    enunciado: '¿Cuál es el periodo de y = cos(x/2)?',
    opciones: ['4π', '2π', 'π', 'π/2'],
    correcta: 0,
    explicacion: 'El periodo es 2π/|B| con B = 1/2, así que 2π ÷ (1/2) = 4π. Al reducir B la gráfica se estira.',
  },
  {
    id: 'tri-084', tema: 'graficas-trig', dificultad: 1,
    enunciado: '¿Cuál es el rango de y = 2 sen x?',
    opciones: ['[−2, 2]', '[0, 2]', '[−1, 1]', '[−2, 0]'],
    correcta: 0,
    explicacion: 'El seno varía entre −1 y 1; al multiplicar por 2 el rango se estira a [−2, 2].',
  },
  {
    id: 'tri-085', tema: 'graficas-trig', dificultad: 2,
    enunciado: '¿Cuáles de estas funciones tienen periodo 2π?',
    opciones: ['sen x y cos x', 'tan x y cot x', 'sen 2x y cos 2x', 'sec 2x y csc 2x'],
    correcta: 0,
    explicacion: 'Seno y coseno completan un ciclo en 2π. La tangente y la cotangente lo hacen en π, y al duplicar el argumento el periodo se reduce a la mitad.',
  },
  {
    id: 'tri-086', tema: 'graficas-trig', dificultad: 3,
    enunciado: 'En y = sen(x − π/3), el desfase es:',
    opciones: [
      'π/3 hacia la derecha',
      'π/3 hacia la izquierda',
      'π/3 hacia arriba',
      'No hay desfase, solo cambia la amplitud',
    ],
    correcta: 0,
    explicacion: 'Restar dentro del argumento desplaza la gráfica hacia la derecha; sumar la desplaza hacia la izquierda. Es el sentido contrario al que sugiere la intuición.',
  },
  {
    id: 'tri-087', tema: 'graficas-trig', dificultad: 2,
    enunciado: '¿En qué punto corta la gráfica de y = 3 cos x al eje y?',
    opciones: ['(0, 3)', '(0, 0)', '(3, 0)', '(0, −3)'],
    correcta: 0,
    explicacion: 'Se evalúa en x = 0: y = 3 cos 0 = 3 × 1 = 3.',
  },
  {
    id: 'tri-088', tema: 'leyes', dificultad: 2,
    enunciado: '¿Cuándo conviene usar la ley de senos?',
    opciones: [
      'Cuando se conocen dos ángulos y un lado, o dos lados y un ángulo opuesto a uno de ellos',
      'Cuando se conocen los tres lados',
      'Cuando se conocen dos lados y el ángulo entre ellos',
      'Únicamente en triángulos rectángulos',
    ],
    correcta: 0,
    explicacion: 'La ley de senos relaciona cada lado con el seno de su ángulo opuesto, así que hace falta tener al menos una pareja completa lado-ángulo.',
  },
  {
    id: 'tri-089', tema: 'leyes', dificultad: 2,
    enunciado: '¿Cuándo hay que usar la ley de cosenos?',
    opciones: [
      'Cuando se conocen los tres lados, o dos lados y el ángulo comprendido entre ellos',
      'Cuando se conocen dos ángulos y un lado',
      'Cuando el triángulo es rectángulo',
      'Cuando se conoce solo un lado',
    ],
    correcta: 0,
    explicacion: 'Son los casos en los que no hay ninguna pareja lado-ángulo opuesto completa. De hecho, con un ángulo de 90° la ley de cosenos se reduce al teorema de Pitágoras.',
  },
  {
    id: 'tri-090', tema: 'leyes', dificultad: 3,
    enunciado: 'Un triángulo tiene lados de 8 y 5 con un ángulo de 120° entre ellos. ¿Cuánto mide el tercer lado?',
    opciones: ['√129', '√49', '√89', '13'],
    correcta: 0,
    explicacion: 'c² = 64 + 25 − 2(8)(5)cos120°. Como cos 120° = −1/2, queda 89 + 40 = 129, así que c = √129 ≈ 11,4. El signo del coseno de un ángulo obtuso hace que el término se sume.',
  },
  {
    id: 'tri-091', tema: 'leyes', dificultad: 1,
    enunciado: '¿Cuál es el área de un triángulo cuyos lados de 10 y 6 forman un ángulo de 90°?',
    opciones: ['30', '60', '15', '30√2'],
    correcta: 0,
    explicacion: 'Área = (1/2)ab·sen C = (1/2)(10)(6)(1) = 30. Con 90° la fórmula coincide con base por altura sobre dos.',
  },
  {
    id: 'tri-092', tema: 'leyes', dificultad: 3,
    enunciado: 'En un triángulo, A = 45°, B = 60° y el lado a = 12. ¿Cuánto mide el lado b?',
    opciones: ['6√6', '12√3', '6√2', '18'],
    correcta: 0,
    explicacion: 'Por la ley de senos: b = a·sen B/sen A = 12(√3/2)/(√2/2) = 12√3/√2 = 6√6 ≈ 14,7.',
  },
  {
    id: 'tri-093', tema: 'leyes', dificultad: 2,
    enunciado: 'Un triángulo tiene lados 3, 4 y 5. ¿Cuánto mide el ángulo opuesto al lado 5?',
    opciones: ['90°', '60°', '120°', '45°'],
    correcta: 0,
    explicacion: 'cos C = (9 + 16 − 25)/(2·3·4) = 0/24 = 0, y el coseno vale 0 en 90°. Es el triángulo rectángulo más conocido.',
  },
  {
    id: 'tri-094', tema: 'aplicaciones', dificultad: 1,
    enunciado: 'Una rampa de 5 m de longitud forma un ángulo de 30° con el suelo. ¿Qué altura alcanza?',
    opciones: ['2,5 m', '5√3/2 m', '10 m', '5 m'],
    correcta: 0,
    explicacion: 'La altura es el cateto opuesto: 5 · sen 30° = 5 × 0,5 = 2,5 m.',
  },
  {
    id: 'tri-095', tema: 'aplicaciones', dificultad: 2,
    enunciado: 'Un árbol de 12 m proyecta una sombra cuando el Sol está a 45° sobre el horizonte. ¿Cuánto mide la sombra?',
    opciones: ['12 m', '6 m', '12√2 m', '24 m'],
    correcta: 0,
    explicacion: 'tan 45° = altura/sombra = 1, así que la sombra mide lo mismo que el árbol: 12 m.',
  },
  {
    id: 'tri-096', tema: 'aplicaciones', dificultad: 2,
    enunciado: 'Desde un punto a 30 m de la base de un edificio, la punta se observa con un ángulo de elevación de 60°. ¿Cuál es la altura del edificio?',
    opciones: ['30√3 m', '30 m', '15√3 m', '60 m'],
    correcta: 0,
    explicacion: 'h = 30 · tan 60° = 30√3 ≈ 51,96 m.',
  },
  {
    id: 'tri-097', tema: 'aplicaciones', dificultad: 3,
    enunciado: 'Un avión vuela a 3 000 m de altura y ve un punto del suelo con un ángulo de depresión de 30°. ¿A qué distancia horizontal está ese punto?',
    opciones: ['3 000√3 m', '3 000 m', '1 500√3 m', '6 000 m'],
    correcta: 0,
    explicacion: 'tan 30° = 3 000 / d, así que d = 3 000 / tan30° = 3 000√3 ≈ 5 196 m. El ángulo de depresión desde el avión es igual al de elevación desde el suelo.',
  },
  {
    id: 'tri-098', tema: 'aplicaciones', dificultad: 3,
    enunciado: 'Una escalera de 6 m apoya su base a 3 m de la pared. ¿Qué ángulo forma con el suelo?',
    opciones: ['60°', '30°', '45°', '75°'],
    correcta: 0,
    explicacion: 'cos θ = 3/6 = 1/2, y el ángulo cuyo coseno vale 1/2 es 60°.',
  },
  {
    id: 'tri-099', tema: 'aplicaciones', dificultad: 3,
    enunciado: 'Un poste de 9 m proyecta una sombra de 9√3 m. ¿Cuál es el ángulo de elevación del Sol?',
    opciones: ['30°', '60°', '45°', '15°'],
    correcta: 0,
    explicacion: 'tan θ = 9/(9√3) = 1/√3 = √3/3, que corresponde a 30°. Sombras largas significan sol bajo.',
  },
  {
    id: 'tri-100', tema: 'aplicaciones', dificultad: 2,
    enunciado: 'Un barco navega 40 km hacia el este y luego 30 km hacia el norte. ¿A qué distancia está del punto de partida?',
    opciones: ['50 km', '70 km', '35 km', '10 km'],
    correcta: 0,
    explicacion: 'Los dos tramos son perpendiculares, así que por Pitágoras: √(40² + 30²) = √2 500 = 50 km. Es el triángulo 3-4-5 multiplicado por 10.',
  },
];
