/**
 * universal.js — Banco de historia universal.
 *
 * El banco ya tenía historia de Colombia, pero el Saber 11 también pregunta
 * por el mundo: revoluciones, guerras mundiales, Guerra Fría y globalización.
 * Aquí se privilegian las causas y las consecuencias sobre las fechas sueltas.
 *
 * Las opciones se barajan al presentarlas (motor.js).
 */

export const UNIVERSAL = [
  // ----- Civilizaciones antiguas -----
  {
    id: 'uni-001', tema: 'antiguas', dificultad: 1,
    enunciado: '¿Qué cambio marcó la revolución neolítica?',
    opciones: [
      'El paso de la caza y la recolección a la agricultura y la ganadería',
      'La invención de la máquina de vapor',
      'El descubrimiento del fuego',
      'La aparición de la escritura alfabética',
    ],
    correcta: 0,
    explicacion: 'Producir alimento en lugar de buscarlo permitió la vida sedentaria, el excedente y, con él, las primeras ciudades.',
  },
  {
    id: 'uni-002', tema: 'antiguas', dificultad: 1,
    enunciado: '¿En qué región surgieron las primeras ciudades y la escritura cuneiforme?',
    opciones: ['Mesopotamia', 'Escandinavia', 'La Amazonía', 'Australia'],
    correcta: 0,
    explicacion: 'Entre el Tigris y el Éufrates, en el actual Irak. Sumerios y acadios levantaron allí ciudades como Ur y Uruk.',
  },
  {
    id: 'uni-003', tema: 'antiguas', dificultad: 1,
    enunciado: '¿Qué fue el código de Hammurabi?',
    opciones: [
      'Uno de los primeros conjuntos de leyes escritas, en la Babilonia del siglo XVIII a. C.',
      'Un texto religioso egipcio',
      'Un tratado de astronomía china',
      'Un manual de agricultura griego',
    ],
    correcta: 0,
    explicacion: 'Su principio más conocido es el talión, "ojo por ojo". Lo decisivo es que la norma quedara escrita y pública, y no sujeta al criterio del momento.',
  },
  {
    id: 'uni-004', tema: 'antiguas', dificultad: 2,
    enunciado: '¿Por qué las primeras civilizaciones surgieron junto a grandes ríos?',
    opciones: [
      'Porque las crecidas fertilizaban el suelo y permitían excedentes agrícolas y regadío',
      'Porque el agua servía para generar energía',
      'Porque los ríos impedían las invasiones',
      'Porque allí había más minerales',
    ],
    correcta: 0,
    explicacion: 'Nilo, Tigris, Éufrates, Indo y Huang He. Organizar el riego exigió además administración, cálculo y registro: la burocracia nace de la necesidad hidráulica.',
  },
  {
    id: 'uni-005', tema: 'antiguas', dificultad: 2,
    enunciado: '¿Qué función cumplía la escritura en las primeras civilizaciones?',
    opciones: [
      'Registrar transacciones, impuestos y cosechas antes que expresar literatura',
      'Difundir poesía entre la población',
      'Comunicarse entre personas comunes',
      'Enseñar en escuelas públicas',
    ],
    correcta: 0,
    explicacion: 'Las primeras tablillas son inventarios y recibos. La contabilidad precede al relato: se escribe para controlar un excedente.',
  },
  {
    id: 'uni-006', tema: 'antiguas', dificultad: 2,
    enunciado: '¿Qué caracterizó a la organización política del Egipto faraónico?',
    opciones: [
      'Un Estado centralizado donde el faraón concentraba poder político y religioso',
      'Una federación de ciudades independientes',
      'Una democracia con asamblea de ciudadanos',
      'Una confederación de tribus nómadas',
    ],
    correcta: 0,
    explicacion: 'El faraón era considerado un dios en la tierra. Esa fusión de autoridad política y sagrada es la llamada teocracia, y explica la escala de las obras públicas.',
  },
  {
    id: 'uni-007', tema: 'antiguas', dificultad: 2,
    enunciado: '¿Qué aportó la civilización india antigua al pensamiento matemático?',
    opciones: [
      'El sistema decimal posicional y el uso del cero como número',
      'La geometría euclidiana',
      'El cálculo diferencial',
      'La notación algebraica moderna',
    ],
    correcta: 0,
    explicacion: 'Llegó a Europa a través del mundo árabe, y por eso llamamos "arábigos" a unos números de origen indio. Sin el cero posicional no habría cálculo moderno.',
  },
  {
    id: 'uni-008', tema: 'antiguas', dificultad: 2,
    enunciado: 'La estratificación social de las primeras civilizaciones se explica sobre todo por:',
    opciones: [
      'La aparición de un excedente que unos pocos pudieron controlar y administrar',
      'Diferencias físicas entre los individuos',
      'La llegada de invasores extranjeros',
      'El azar de las primeras migraciones',
    ],
    correcta: 0,
    explicacion: 'Mientras todo lo producido se consume, hay poco que acumular. El excedente hace posible que existan sacerdotes, guerreros y funcionarios que no cultivan.',
  },
  {
    id: 'uni-009', tema: 'antiguas', dificultad: 3,
    enunciado: '¿Por qué la revolución neolítica se considera un cambio ambivalente y no solo un progreso?',
    opciones: [
      'Aumentó la población y la complejidad social, pero trajo peor dieta, más enfermedades y desigualdad',
      'Porque redujo la población mundial',
      'Porque no modificó la forma de vida',
      'Porque solo ocurrió en una región del planeta',
    ],
    correcta: 0,
    explicacion: 'Los restos óseos muestran menor estatura y más caries tras la adopción de la agricultura. La sociedad ganó en número y organización; el individuo medio, no necesariamente en salud.',
  },
  {
    id: 'uni-010', tema: 'antiguas', dificultad: 3,
    enunciado: '¿Qué relación hay entre el excedente agrícola y la aparición del Estado?',
    opciones: [
      'El excedente debe almacenarse, defenderse y redistribuirse, y eso exige una autoridad permanente',
      'El Estado apareció antes que la agricultura',
      'No existe relación documentada entre ambos',
      'El excedente hizo innecesaria toda autoridad',
    ],
    correcta: 0,
    explicacion: 'Alguien debe decidir qué se guarda, quién accede y cómo se defiende el granero. Templos y palacios funcionaron como los primeros centros administrativos.',
  },
  {
    id: 'uni-011', tema: 'antiguas', dificultad: 3,
    enunciado: '¿Por qué se dice que la agricultura se inventó varias veces de forma independiente?',
    opciones: [
      'Porque surgió por separado en Medio Oriente, China, Mesoamérica y los Andes, con cultivos distintos',
      'Porque los pueblos antiguos viajaban constantemente',
      'Porque el clima era idéntico en todo el planeta',
      'Porque hubo un único centro que difundió la técnica',
    ],
    correcta: 0,
    explicacion: 'Trigo, arroz, maíz y papa fueron domesticados en regiones sin contacto entre sí. Es un caso de convergencia: condiciones similares produjeron respuestas similares.',
  },
  {
    id: 'uni-012', tema: 'antiguas', dificultad: 3,
    enunciado: '¿Qué papel cumplió la religión en los Estados antiguos?',
    opciones: [
      'Legitimó el poder, ordenó el calendario agrícola y justificó la jerarquía social',
      'Se mantuvo separada del poder político',
      'Solo servía para consolar a los pobres',
      'Estuvo prohibida por los gobernantes',
    ],
    correcta: 0,
    explicacion: 'Los sacerdotes controlaban el saber astronómico que decía cuándo sembrar, y esa utilidad práctica reforzaba su autoridad. Religión y administración fueron durante milenios la misma cosa.',
  },
  {
    id: 'uni-013', tema: 'antiguas', dificultad: 4,
    enunciado: '¿Por qué la tesis de que la geografía determina el destino de los pueblos es discutida?',
    opciones: [
      'Porque explica condiciones iniciales pero no las decisiones políticas y culturales que produjeron trayectorias distintas en entornos parecidos',
      'Porque la geografía no influye en nada',
      'Porque todos los continentes tienen los mismos recursos',
      'Porque solo se aplica a Europa',
    ],
    correcta: 0,
    explicacion: 'El determinismo geográfico ilumina por qué ciertas regiones partieron con ventaja, pero tiende a borrar la agencia humana y a naturalizar desigualdades construidas históricamente.',
  },
  {
    id: 'uni-014', tema: 'antiguas', dificultad: 4,
    enunciado: '¿Qué muestra que civilizaciones como la del valle del Indo tuvieran ciudades planificadas con alcantarillado?',
    opciones: [
      'Que el desarrollo técnico y urbano no sigue una única línea de progreso desde Mesopotamia hacia Europa',
      'Que la escritura no era necesaria',
      'Que no existían jerarquías sociales',
      'Que fueron contemporáneas de Roma',
    ],
    correcta: 0,
    explicacion: 'Mohenjo-Daro y Harappa tenían trazado en cuadrícula y saneamiento cuando buena parte del mundo no lo tenía. Su escritura sigue sin descifrarse, lo que limita cuánto podemos afirmar sobre ellas.',
  },
  {
    id: 'uni-015', tema: 'antiguas', dificultad: 4,
    enunciado: '¿Por qué el colapso de una civilización antigua rara vez tiene una sola causa?',
    opciones: [
      'Porque suelen combinarse presión ambiental, conflictos internos, invasiones y crisis económicas que se refuerzan',
      'Porque siempre se debió a una invasión militar',
      'Porque los registros escritos son falsos',
      'Porque en realidad ninguna civilización colapsó',
    ],
    correcta: 0,
    explicacion: 'Las explicaciones monocausales son atractivas y casi siempre insuficientes. Una sequía prolongada golpea más fuerte a una sociedad ya tensionada por guerras o desigualdad.',
  },

  // ----- Grecia y Roma -----
  {
    id: 'uni-016', tema: 'clasica', dificultad: 1,
    enunciado: '¿Qué era la polis griega?',
    opciones: [
      'Una ciudad-Estado independiente con su propio gobierno y leyes',
      'Un imperio que unificaba toda Grecia',
      'Una asamblea religiosa',
      'Una provincia romana',
    ],
    correcta: 0,
    explicacion: 'Atenas, Esparta y Corinto compartían lengua y religión pero eran políticamente autónomas, y con frecuencia estuvieron en guerra entre sí.',
  },
  {
    id: 'uni-017', tema: 'clasica', dificultad: 1,
    enunciado: '¿En qué ciudad griega se desarrolló la democracia en el siglo V a. C.?',
    opciones: ['Atenas', 'Esparta', 'Tebas', 'Corinto'],
    correcta: 0,
    explicacion: 'Esparta tenía un sistema mixto con dos reyes y un fuerte componente militar. Atenas es la referencia de la democracia directa.',
  },
  {
    id: 'uni-018', tema: 'clasica', dificultad: 1,
    enunciado: '¿Cuál es una de las herencias más duraderas de Roma?',
    opciones: [
      'El derecho, base de los sistemas jurídicos de gran parte del mundo',
      'El sistema decimal',
      'La democracia directa',
      'La escritura cuneiforme',
    ],
    correcta: 0,
    explicacion: 'Conceptos como persona jurídica, contrato, propiedad o presunción de inocencia proceden del derecho romano, sistematizado después en el Corpus Iuris de Justiniano.',
  },
  {
    id: 'uni-019', tema: 'clasica', dificultad: 2,
    enunciado: '¿Quiénes podían participar en la democracia ateniense?',
    opciones: [
      'Solo los varones libres nacidos de padres atenienses: quedaban fuera mujeres, esclavos y extranjeros',
      'Todos los habitantes de la ciudad',
      'Únicamente los propietarios de tierras',
      'Solo los militares',
    ],
    correcta: 0,
    explicacion: 'Se estima que participaba entre el 10 % y el 20 % de la población. Fue un experimento radical para su época y a la vez profundamente excluyente según criterios actuales.',
  },
  {
    id: 'uni-020', tema: 'clasica', dificultad: 2,
    enunciado: '¿Qué diferencia hay entre la República y el Imperio romano?',
    opciones: [
      'En la República el poder se repartía entre magistrados y el Senado; en el Imperio se concentró en el emperador',
      'La República fue posterior al Imperio',
      'En la República gobernaban los reyes',
      'El Imperio no tuvo Senado',
    ],
    correcta: 0,
    explicacion: 'El Senado sobrevivió como institución, pero vaciado de poder efectivo. La transición, tras las guerras civiles, la consolidó Augusto sin abolir formalmente las instituciones republicanas.',
  },
  {
    id: 'uni-021', tema: 'clasica', dificultad: 2,
    enunciado: '¿Qué fue la Pax Romana?',
    opciones: [
      'Un largo periodo de estabilidad interna que facilitó el comercio y la difusión cultural en el Imperio',
      'Un tratado de paz con los persas',
      'La rendición de Cartago',
      'El fin del Imperio romano',
    ],
    correcta: 0,
    explicacion: 'Duró unos dos siglos desde Augusto. La paz era interna y relativa: en las fronteras la guerra continuaba, y se sostenía sobre conquistas previas y sobre la esclavitud.',
  },
  {
    id: 'uni-022', tema: 'clasica', dificultad: 2,
    enunciado: '¿Qué papel tuvo la esclavitud en la economía grecorromana?',
    opciones: [
      'Fue una base estructural de la producción agrícola, minera y doméstica',
      'Fue marginal y poco frecuente',
      'Estuvo prohibida en Atenas',
      'Solo existió durante el Imperio',
    ],
    correcta: 0,
    explicacion: 'El tiempo libre que permitía a los ciudadanos atenienses deliberar en la asamblea descansaba sobre el trabajo de quienes no eran ciudadanos.',
  },
  {
    id: 'uni-023', tema: 'clasica', dificultad: 2,
    enunciado: '¿Qué extendió Alejandro Magno por Oriente?',
    opciones: [
      'La cultura griega, en la síntesis que se conoce como helenismo',
      'El derecho romano',
      'El cristianismo',
      'El sistema feudal',
    ],
    correcta: 0,
    explicacion: 'Su imperio se fragmentó al morir, pero la lengua griega y sus formas culturales se mezclaron con las locales desde Egipto hasta la India durante siglos.',
  },
  {
    id: 'uni-024', tema: 'clasica', dificultad: 3,
    enunciado: '¿Por qué la democracia ateniense se llama directa y no representativa?',
    opciones: [
      'Porque los ciudadanos votaban en persona las decisiones en la asamblea, sin delegar en representantes',
      'Porque el pueblo elegía directamente a los senadores',
      'Porque solo había un gobernante',
      'Porque las decisiones las tomaban los jueces',
    ],
    correcta: 0,
    explicacion: 'Muchos cargos se asignaban además por sorteo, no por elección, porque la elección se consideraba un mecanismo aristocrático que favorecía a los notables.',
  },
  {
    id: 'uni-025', tema: 'clasica', dificultad: 3,
    enunciado: '¿Qué factores explican la expansión territorial de Roma?',
    opciones: [
      'Un ejército profesional y disciplinado, la integración de los vencidos y una red de vías y ciudades',
      'Únicamente su superioridad tecnológica',
      'La ausencia de rivales en el Mediterráneo',
      'El apoyo del cristianismo desde el inicio',
    ],
    correcta: 0,
    explicacion: 'La capacidad de conceder ciudadanía y absorber élites locales fue tan decisiva como las legiones: convertía a antiguos enemigos en contribuyentes y soldados.',
  },
  {
    id: 'uni-026', tema: 'clasica', dificultad: 3,
    enunciado: '¿Qué causas se señalan para la caída del Imperio romano de Occidente?',
    opciones: [
      'Crisis económica y fiscal, presión de pueblos germánicos, inestabilidad política y división administrativa',
      'Una única invasión que lo destruyó en un año',
      'Un terremoto que arrasó Roma',
      'La conversión al cristianismo como causa exclusiva',
    ],
    correcta: 0,
    explicacion: 'El proceso duró siglos y el Imperio de Oriente sobrevivió mil años más como Bizancio. La fecha de 476 es una convención cómoda, no un corte real.',
  },
  {
    id: 'uni-027', tema: 'clasica', dificultad: 3,
    enunciado: '¿Por qué el latín dio origen a tantas lenguas actuales?',
    opciones: [
      'Porque el latín hablado evolucionó de forma distinta en cada provincia tras la fragmentación del Imperio',
      'Porque se enseñaba en las escuelas medievales',
      'Porque la Iglesia lo impuso en América',
      'Porque era la lengua materna de los germanos',
    ],
    correcta: 0,
    explicacion: 'Español, portugués, francés, italiano y rumano derivan del latín vulgar, no del clásico. Al romperse la unidad administrativa, cada región siguió su propio camino lingüístico.',
  },
  {
    id: 'uni-028', tema: 'clasica', dificultad: 4,
    enunciado: '¿Por qué se discute que la democracia moderna sea heredera directa de la ateniense?',
    opciones: [
      'Porque la moderna es representativa, se basa en derechos individuales y en una ciudadanía universal ajena al modelo ateniense',
      'Porque los griegos no tuvieron ninguna forma de gobierno colectivo',
      'Porque Atenas nunca existió como ciudad',
      'Porque la democracia moderna se inventó en Roma',
    ],
    correcta: 0,
    explicacion: 'Los fundadores de las repúblicas modernas admiraban más a Roma que a Atenas y desconfiaban de la democracia directa. La continuidad es más de vocabulario que de institución.',
  },
  {
    id: 'uni-029', tema: 'clasica', dificultad: 4,
    enunciado: '¿Qué implicó la concesión de la ciudadanía romana a todos los habitantes libres del Imperio en 212?',
    opciones: [
      'Amplió la base fiscal y jurídica, y diluyó la ciudadanía como privilegio distintivo',
      'Abolió la esclavitud',
      'Terminó con el poder del emperador',
      'Excluyó a las provincias del Imperio',
    ],
    correcta: 0,
    explicacion: 'La Constitución Antoniniana tuvo un móvil recaudatorio evidente, ya que ciertos impuestos gravaban a los ciudadanos. Al universalizarse, el estatus dejó de ser una recompensa.',
  },
  {
    id: 'uni-030', tema: 'clasica', dificultad: 4,
    enunciado: '¿Por qué el pensamiento político clásico distinguía entre "buenas" y "malas" formas de gobierno?',
    opciones: [
      'Porque juzgaba si el poder se ejercía en beneficio común o en provecho de quien gobierna, más allá del número de gobernantes',
      'Porque prefería siempre la monarquía',
      'Porque consideraba que solo importaba la eficacia',
      'Porque clasificaba según el tamaño del territorio',
    ],
    correcta: 0,
    explicacion: 'Aristóteles opuso monarquía a tiranía, aristocracia a oligarquía y politeia a democracia degenerada. El criterio no era cuántos mandan, sino para quién.',
  },
  // ----- Edad Media -----
  {
    id: 'uni-031', tema: 'medieval', dificultad: 1,
    enunciado: '¿En qué consistía el feudalismo?',
    opciones: [
      'Un sistema en que el señor concedía tierras a cambio de fidelidad y servicio militar, y los campesinos trabajaban el feudo',
      'Un régimen de propiedad colectiva de la tierra',
      'Un sistema basado en el comercio marítimo',
      'Una forma de gobierno democrático',
    ],
    correcta: 0,
    explicacion: 'El vínculo personal sustituyó a la administración estatal: la fidelidad entre señor y vasallo hacía las veces del Estado que había desaparecido con Roma.',
  },
  {
    id: 'uni-032', tema: 'medieval', dificultad: 1,
    enunciado: 'La sociedad medieval europea se dividía tradicionalmente en:',
    opciones: [
      'Quienes rezaban, quienes combatían y quienes trabajaban',
      'Patricios y plebeyos',
      'Ciudadanos y metecos',
      'Burgueses y proletarios',
    ],
    correcta: 0,
    explicacion: 'Clero, nobleza y campesinado. Era un orden estamental cerrado: se nacía en un estamento y casi nunca se salía de él.',
  },
  {
    id: 'uni-033', tema: 'medieval', dificultad: 1,
    enunciado: '¿Qué fue la peste negra del siglo XIV?',
    opciones: [
      'Una epidemia que mató a cerca de un tercio de la población europea',
      'Una guerra entre Francia e Inglaterra',
      'Una hambruna causada por sequías',
      'Una persecución religiosa',
    ],
    correcta: 0,
    explicacion: 'Llegó por las rutas comerciales desde Asia. Su efecto demográfico transformó la economía: al escasear la mano de obra, subieron los salarios y se resquebrajó la servidumbre.',
  },
  {
    id: 'uni-034', tema: 'medieval', dificultad: 2,
    enunciado: '¿Qué aportó el mundo islámico medieval a la cultura europea?',
    opciones: [
      'Conservó y amplió el saber griego, y transmitió matemáticas, medicina y astronomía',
      'Impidió todo contacto cultural con Europa',
      'Introdujo el sistema feudal',
      'Difundió el derecho romano',
    ],
    correcta: 0,
    explicacion: 'Textos de Aristóteles llegaron a Europa traducidos del árabe. Al-Ándalus y las escuelas de traductores fueron una vía central de esa transmisión.',
  },
  {
    id: 'uni-035', tema: 'medieval', dificultad: 2,
    enunciado: '¿Qué fueron las cruzadas?',
    opciones: [
      'Expediciones militares cristianas hacia Tierra Santa, con motivaciones religiosas, políticas y económicas',
      'Guerras entre reinos cristianos europeos',
      'Peregrinaciones pacíficas a Roma',
      'Campañas contra la peste negra',
    ],
    correcta: 0,
    explicacion: 'Junto a la motivación religiosa pesaron el control de rutas comerciales, la búsqueda de tierras por segundones nobles y el interés del papado en canalizar la violencia feudal.',
  },
  {
    id: 'uni-036', tema: 'medieval', dificultad: 2,
    enunciado: '¿Qué era el Imperio bizantino?',
    opciones: [
      'La continuación del Imperio romano de Oriente, con capital en Constantinopla',
      'Un reino germánico del norte de Europa',
      'Un califato islámico',
      'Una confederación de ciudades italianas',
    ],
    correcta: 0,
    explicacion: 'Sobrevivió casi mil años a la caída de Occidente y cayó en 1453 ante los otomanos. Preservó el derecho romano y la cultura griega durante toda la Edad Media.',
  },
  {
    id: 'uni-037', tema: 'medieval', dificultad: 2,
    enunciado: '¿Qué papel cumplieron los monasterios en la Alta Edad Media?',
    opciones: [
      'Conservaron textos antiguos, organizaron la producción agrícola y sostuvieron la alfabetización',
      'Se dedicaron exclusivamente a la oración',
      'Funcionaron como fortalezas militares',
      'Administraban el comercio internacional',
    ],
    correcta: 0,
    explicacion: 'Los scriptoria copiaron obras clásicas que de otro modo se habrían perdido. Eran a la vez centros religiosos, económicos y culturales.',
  },
  {
    id: 'uni-038', tema: 'medieval', dificultad: 2,
    enunciado: '¿Qué significó el renacimiento urbano de los siglos XI a XIII?',
    opciones: [
      'El crecimiento de ciudades y del comercio, y la aparición de una burguesía distinta de nobles y campesinos',
      'El abandono de las ciudades',
      'La vuelta al sistema esclavista romano',
      'La desaparición del feudalismo en toda Europa',
    ],
    correcta: 0,
    explicacion: 'Con las ciudades llegaron los gremios, las ferias, las universidades y una forma de riqueza no basada en la tierra: el germen del mundo moderno.',
  },
  {
    id: 'uni-039', tema: 'medieval', dificultad: 3,
    enunciado: '¿Por qué la peste negra favoreció indirectamente a los campesinos supervivientes?',
    opciones: [
      'Porque la escasez de mano de obra aumentó su capacidad de negociar salarios y libertades',
      'Porque los señores repartieron sus tierras voluntariamente',
      'Porque la Iglesia abolió la servidumbre',
      'Porque el rey prohibió los impuestos',
    ],
    correcta: 0,
    explicacion: 'Los señores intentaron fijar los salarios por ley y hubo revueltas cuando fracasaron. Es un ejemplo claro de cómo un desastre demográfico altera relaciones de poder.',
  },
  {
    id: 'uni-040', tema: 'medieval', dificultad: 3,
    enunciado: '¿Por qué la expresión "edad oscura" aplicada a toda la Edad Media es cuestionada por los historiadores?',
    opciones: [
      'Porque hubo innovación técnica, universidades y florecimiento cultural, y el término nació como descalificación renacentista',
      'Porque en realidad no existió ese periodo',
      'Porque solo fue oscura en Asia',
      'Porque duró apenas un siglo',
    ],
    correcta: 0,
    explicacion: 'El arado de vertedera, el molino, las catedrales góticas y las primeras universidades son medievales. La etiqueta la acuñaron humanistas interesados en presentarse como restauradores.',
  },
  {
    id: 'uni-041', tema: 'medieval', dificultad: 3,
    enunciado: '¿Qué tensión atravesó la relación entre el papado y los reyes medievales?',
    opciones: [
      'La disputa por quién tenía autoridad última, visible en el conflicto por el nombramiento de obispos',
      'Un acuerdo pacífico sin conflictos',
      'La discusión sobre el sistema monetario',
      'La rivalidad por el control de Constantinopla',
    ],
    correcta: 0,
    explicacion: 'La querella de las investiduras enfrentó a papas y emperadores durante décadas. De esa pugna nace buena parte de la reflexión occidental sobre los límites del poder.',
  },
  {
    id: 'uni-042', tema: 'medieval', dificultad: 3,
    enunciado: '¿Qué fue la Carta Magna de 1215 y por qué se recuerda?',
    opciones: [
      'Un documento que obligó al rey inglés a aceptar límites legales a su poder frente a los nobles',
      'La primera constitución democrática del mundo',
      'Un tratado de paz entre Francia e Inglaterra',
      'Una bula papal sobre las cruzadas',
    ],
    correcta: 0,
    explicacion: 'No era democrática: protegía privilegios de barones. Su importancia está en el precedente de que el rey también queda sometido a la ley.',
  },
  {
    id: 'uni-043', tema: 'medieval', dificultad: 4,
    enunciado: '¿Por qué el feudalismo no puede describirse como un sistema uniforme en toda Europa?',
    opciones: [
      'Porque las relaciones de dependencia variaron mucho por regiones y siglos, y el término es una construcción posterior de los historiadores',
      'Porque el feudalismo nunca existió',
      'Porque solo se aplicó en Francia durante un año',
      'Porque todos los campesinos eran libres',
    ],
    correcta: 0,
    explicacion: 'La palabra se generalizó en el siglo XVIII. Sirve como modelo, pero oculta enormes diferencias entre el norte y el sur, y entre la Alta y la Baja Edad Media.',
  },
  {
    id: 'uni-044', tema: 'medieval', dificultad: 4,
    enunciado: '¿Qué consecuencia de largo plazo tuvo la caída de Constantinopla en 1453?',
    opciones: [
      'Dificultó las rutas terrestres hacia Asia e impulsó la búsqueda de vías marítimas alternativas',
      'Provocó de inmediato la Revolución industrial',
      'Terminó con el comercio mediterráneo',
      'Causó la peste negra',
    ],
    correcta: 0,
    explicacion: 'El control otomano encareció el comercio de especias y sedas. La exploración atlántica portuguesa y española responde, entre otras causas, a ese bloqueo.',
  },
  {
    id: 'uni-045', tema: 'medieval', dificultad: 4,
    enunciado: '¿Qué muestra la existencia de universidades medievales como Bolonia o París?',
    opciones: [
      'Que hubo una institucionalización del saber con autonomía corporativa, antecedente directo de la universidad moderna',
      'Que la educación era universal y gratuita',
      'Que la Iglesia prohibía el estudio',
      'Que no existía la enseñanza superior antes del Renacimiento',
    ],
    correcta: 0,
    explicacion: 'Nacieron como gremios de maestros y estudiantes con privilegios propios. La estructura de facultades, grados y claustro que seguimos usando procede de ahí.',
  },

  // ----- Renacimiento y expansión europea -----
  {
    id: 'uni-046', tema: 'moderna', dificultad: 1,
    enunciado: '¿Qué caracterizó al humanismo renacentista?',
    opciones: [
      'El interés por el ser humano, la recuperación de los clásicos y la confianza en la educación',
      'El rechazo de la Antigüedad grecolatina',
      'La prohibición de la lectura',
      'La vuelta al orden feudal',
    ],
    correcta: 0,
    explicacion: 'No supuso abandonar la religión: Erasmo y Tomás Moro eran cristianos convencidos. Lo que cambia es el lugar del hombre y el método de acceso a los textos.',
  },
  {
    id: 'uni-047', tema: 'moderna', dificultad: 1,
    enunciado: '¿Quién desarrolló la imprenta de tipos móviles en Europa hacia 1450?',
    opciones: ['Johannes Gutenberg', 'Leonardo da Vinci', 'Nicolás Copérnico', 'Martín Lutero'],
    correcta: 0,
    explicacion: 'La técnica existía antes en Asia, pero la combinación de tipos móviles metálicos, prensa y tinta oleosa de Gutenberg la hizo viable a gran escala en Europa.',
  },
  {
    id: 'uni-048', tema: 'moderna', dificultad: 1,
    enunciado: '¿Qué propuso Copérnico en el siglo XVI?',
    opciones: [
      'Que la Tierra y los planetas giran alrededor del Sol',
      'Que la Tierra es el centro del universo',
      'Que la Tierra es plana',
      'Que el universo es infinito y sin centro',
    ],
    correcta: 0,
    explicacion: 'El modelo heliocéntrico desplazó a la Tierra del centro. Galileo aportó después observaciones telescópicas que lo respaldaban, y Newton la física que lo explicaba.',
  },
  {
    id: 'uni-049', tema: 'moderna', dificultad: 2,
    enunciado: '¿Qué consecuencias tuvo la imprenta?',
    opciones: [
      'Abarató y multiplicó los libros, aceleró la difusión de ideas y favoreció la alfabetización y la Reforma',
      'Redujo la circulación de textos',
      'Impuso el latín como única lengua escrita',
      'Fue prohibida en toda Europa',
    ],
    correcta: 0,
    explicacion: 'Las tesis de Lutero se difundieron en semanas por media Europa. Sin imprenta, la Reforma probablemente habría sido un conflicto local más.',
  },
  {
    id: 'uni-050', tema: 'moderna', dificultad: 2,
    enunciado: '¿Qué cuestionó Martín Lutero en 1517?',
    opciones: [
      'La venta de indulgencias y la autoridad del papa como intermediario necesario',
      'La existencia de Dios',
      'La traducción de la Biblia al latín',
      'La validez de los sacramentos en su totalidad',
    ],
    correcta: 0,
    explicacion: 'Sus principios fueron la salvación por la fe y la Biblia como única autoridad. Traducirla al alemán fue un acto teológico y también político y lingüístico.',
  },
  {
    id: 'uni-051', tema: 'moderna', dificultad: 2,
    enunciado: '¿Qué fue el intercambio colombino?',
    opciones: [
      'El traslado masivo de plantas, animales, personas y enfermedades entre América, Europa y África',
      'Un tratado comercial entre España y Portugal',
      'La ruta de la seda hacia Asia',
      'El sistema de flotas del Caribe',
    ],
    correcta: 0,
    explicacion: 'La papa y el maíz transformaron la dieta europea; el caballo y el trigo, la americana. Y las enfermedades del Viejo Mundo causaron el mayor colapso demográfico documentado.',
  },
  {
    id: 'uni-052', tema: 'moderna', dificultad: 2,
    enunciado: '¿En qué consistió el comercio triangular atlántico?',
    opciones: [
      'Manufacturas de Europa a África, personas esclavizadas de África a América y materias primas de América a Europa',
      'Un intercambio entre tres ciudades italianas',
      'La ruta de las especias hacia Asia',
      'Un acuerdo entre las potencias para repartirse el Pacífico',
    ],
    correcta: 0,
    explicacion: 'Más de doce millones de personas fueron embarcadas forzadamente. Ese sistema sostuvo la economía de plantación y financió buena parte de la acumulación europea.',
  },
  {
    id: 'uni-053', tema: 'moderna', dificultad: 2,
    enunciado: '¿Qué caracterizó al mercantilismo?',
    opciones: [
      'La idea de que la riqueza de un país se mide por sus metales preciosos y exige exportar más de lo que se importa',
      'La defensa del libre comercio sin aranceles',
      'La eliminación de las colonias',
      'La prohibición de la moneda',
    ],
    correcta: 0,
    explicacion: 'De ahí el monopolio comercial con las colonias y el proteccionismo. Adam Smith escribiría después contra esta doctrina, defendiendo que la riqueza está en la producción y no en el oro.',
  },
  {
    id: 'uni-054', tema: 'moderna', dificultad: 3,
    enunciado: '¿Por qué la revolución científica del siglo XVII fue algo más que nuevos descubrimientos?',
    opciones: [
      'Porque instauró un método: hipótesis, experimentación, matematización y revisión por pares',
      'Porque se limitó a corregir errores de los griegos',
      'Porque solo afectó a la astronomía',
      'Porque rechazó el uso de las matemáticas',
    ],
    correcta: 0,
    explicacion: 'Lo decisivo no fue qué se descubrió sino cómo: un procedimiento reproducible y público que permite corregir al propio autor. Ahí está la diferencia con el saber anterior.',
  },
  {
    id: 'uni-055', tema: 'moderna', dificultad: 3,
    enunciado: '¿Qué relación hay entre la Reforma protestante y la formación de los Estados modernos?',
    opciones: [
      'Debilitó el poder universal del papado y reforzó a los príncipes, que ganaron control sobre la Iglesia en sus territorios',
      'No tuvo ninguna consecuencia política',
      'Unificó toda Europa bajo un solo poder',
      'Eliminó las monarquías',
    ],
    correcta: 0,
    explicacion: 'La paz de Augsburgo consagró que cada príncipe fijara la religión de su territorio. Es un paso hacia la soberanía territorial que culminará en Westfalia en 1648.',
  },
  {
    id: 'uni-056', tema: 'moderna', dificultad: 3,
    enunciado: '¿Qué efecto tuvo en Europa la llegada masiva de plata americana?',
    opciones: [
      'Provocó una larga inflación y financió guerras, sin generar una industria sólida en España',
      'Estabilizó los precios durante dos siglos',
      'Permitió abolir los impuestos',
      'Impulsó la Revolución industrial española',
    ],
    correcta: 0,
    explicacion: 'Es la llamada revolución de los precios. El metal financió deudas y ejércitos y terminó beneficiando a los países que vendían manufacturas a España.',
  },
  {
    id: 'uni-057', tema: 'moderna', dificultad: 3,
    enunciado: '¿Qué discusión planteó Bartolomé de Las Casas en el siglo XVI?',
    opciones: [
      'La legitimidad de la conquista y los derechos de los pueblos indígenas frente a la encomienda',
      'La conveniencia de abandonar América',
      'La superioridad técnica de los europeos',
      'La necesidad de ampliar el comercio de especias',
    ],
    correcta: 0,
    explicacion: 'La controversia de Valladolid, frente a Sepúlveda, es uno de los primeros debates documentados sobre derechos humanos. Sus consecuencias prácticas fueron limitadas.',
  },
  {
    id: 'uni-058', tema: 'moderna', dificultad: 4,
    enunciado: '¿Por qué se discute la idea de que Europa "descubrió" América?',
    opciones: [
      'Porque el continente estaba habitado por millones de personas con civilizaciones propias: el término adopta un único punto de vista',
      'Porque los europeos nunca llegaron a América',
      'Porque el viaje fue posterior al que se cree',
      'Porque no hay pruebas arqueológicas',
    ],
    correcta: 0,
    explicacion: 'Se prefieren términos como encuentro, invasión o conquista según el aspecto que se quiera subrayar. La discusión no es de etiqueta: cada palabra implica una narrativa distinta.',
  },
  {
    id: 'uni-059', tema: 'moderna', dificultad: 4,
    enunciado: '¿Qué vínculo establecen los historiadores entre la esclavitud atlántica y el desarrollo económico europeo?',
    opciones: [
      'Las plantaciones y el tráfico generaron capitales, seguros y rutas que alimentaron el crecimiento industrial posterior',
      'No existió ninguna relación económica',
      'La esclavitud empobreció a las potencias coloniales',
      'El comercio de personas fue marginal en volumen',
    ],
    correcta: 0,
    explicacion: 'La magnitud exacta del aporte se debate, pero puertos como Liverpool, Nantes o Bristol crecieron con ese tráfico, y su financiación desarrolló instrumentos bancarios y aseguradores.',
  },
  {
    id: 'uni-060', tema: 'moderna', dificultad: 4,
    enunciado: '¿Por qué el caso de Galileo suele presentarse mal como un simple choque entre ciencia y religión?',
    opciones: [
      'Porque intervinieron también rivalidades académicas, el contexto de la Contrarreforma y la forma en que él presentó sus tesis',
      'Porque Galileo nunca fue juzgado',
      'Porque la Iglesia aceptó de inmediato el heliocentrismo',
      'Porque sus observaciones eran erróneas',
    ],
    correcta: 0,
    explicacion: 'El conflicto fue real, pero la versión simplificada oculta que varios jesuitas apoyaban sus observaciones y que el momento político tras el concilio de Trento endureció posiciones.',
  },
  // ----- Revoluciones burguesas -----
  {
    id: 'uni-061', tema: 'revoluciones', dificultad: 1,
    enunciado: '¿En qué año comenzó la Revolución francesa?',
    opciones: ['1789', '1776', '1815', '1848'],
    correcta: 0,
    explicacion: '1776 es la independencia de Estados Unidos y 1815, la derrota de Napoleón en Waterloo. La toma de la Bastilla fue el 14 de julio de 1789.',
  },
  {
    id: 'uni-062', tema: 'revoluciones', dificultad: 1,
    enunciado: '¿Qué proclamaba la Declaración de los Derechos del Hombre y del Ciudadano de 1789?',
    opciones: [
      'La libertad, la igualdad ante la ley y la soberanía de la nación',
      'La restauración del poder absoluto del rey',
      'La abolición inmediata de la propiedad privada',
      'La supremacía de la nobleza',
    ],
    correcta: 0,
    explicacion: 'Es uno de los textos fundacionales del constitucionalismo moderno. Olympe de Gouges publicó dos años después una declaración paralela para las mujeres, excluidas del texto original.',
  },
  {
    id: 'uni-063', tema: 'revoluciones', dificultad: 1,
    enunciado: '¿Qué era el Antiguo Régimen?',
    opciones: [
      'El orden social y político anterior a 1789: monarquía absoluta, sociedad estamental y privilegios',
      'El gobierno de Napoleón',
      'La república instaurada tras la revolución',
      'El sistema económico industrial',
    ],
    correcta: 0,
    explicacion: 'Tres estamentos, privilegios fiscales para nobleza y clero, y un rey que gobernaba por derecho divino. La revolución se define por oposición a ese orden.',
  },
  {
    id: 'uni-064', tema: 'revoluciones', dificultad: 2,
    enunciado: '¿Qué ideas ilustradas influyeron en las revoluciones del siglo XVIII?',
    opciones: [
      'Soberanía popular, separación de poderes, derechos naturales y contrato social',
      'El derecho divino de los reyes',
      'La superioridad de la tradición sobre la razón',
      'La defensa del sistema estamental',
    ],
    correcta: 0,
    explicacion: 'Locke, Montesquieu y Rousseau aparecen citados en los debates revolucionarios a ambos lados del Atlántico. Las ideas no causan revoluciones por sí solas, pero dan forma a las demandas.',
  },
  {
    id: 'uni-065', tema: 'revoluciones', dificultad: 2,
    enunciado: '¿Cuál fue una causa económica inmediata de la Revolución francesa?',
    opciones: [
      'La crisis fiscal del Estado y las malas cosechas que dispararon el precio del pan',
      'La caída del comercio con Asia',
      'El exceso de producción industrial',
      'La escasez de metales preciosos americanos',
    ],
    correcta: 0,
    explicacion: 'La convocatoria de los Estados Generales en 1789 se debió precisamente a la quiebra de la hacienda. El hambre urbana convirtió una crisis fiscal en una revuelta.',
  },
  {
    id: 'uni-066', tema: 'revoluciones', dificultad: 2,
    enunciado: '¿Qué fue la Revolución haitiana?',
    opciones: [
      'La rebelión de personas esclavizadas que logró la independencia y la abolición de la esclavitud en 1804',
      'Una revuelta de colonos franceses contra los impuestos',
      'Una guerra entre España y Francia',
      'Un movimiento pacífico de reforma agraria',
    ],
    correcta: 0,
    explicacion: 'Fue la única revolución de esclavizados que fundó un Estado. Las potencias esclavistas la aislaron durante décadas y Francia le impuso una indemnización que la endeudó por más de un siglo.',
  },
  {
    id: 'uni-067', tema: 'revoluciones', dificultad: 2,
    enunciado: '¿Qué difundió Napoleón por Europa pese a su carácter autoritario?',
    opciones: [
      'El código civil, la igualdad ante la ley y el fin de los privilegios feudales en los territorios ocupados',
      'El sistema estamental',
      'La monarquía absoluta de derecho divino',
      'La servidumbre de la gleba',
    ],
    correcta: 0,
    explicacion: 'El Código Napoleónico sigue siendo la base de muchos sistemas jurídicos, incluido el colombiano por vía del derecho civil francés. La ocupación también despertó nacionalismos en su contra.',
  },
  {
    id: 'uni-068', tema: 'revoluciones', dificultad: 2,
    enunciado: '¿Qué relación hay entre la independencia de Estados Unidos y la Revolución francesa?',
    opciones: [
      'La primera inspiró a la segunda y, además, el apoyo francés a los colonos agravó la crisis fiscal de Francia',
      'Ocurrieron en el mismo año',
      'No tuvieron ninguna conexión',
      'La francesa fue anterior a la norteamericana',
    ],
    correcta: 0,
    explicacion: 'Oficiales como Lafayette volvieron con ideas republicanas, y la guerra dejó las finanzas francesas al borde de la quiebra. Ambos efectos empujaron en la misma dirección.',
  },
  {
    id: 'uni-069', tema: 'revoluciones', dificultad: 3,
    enunciado: '¿Por qué se llama "burguesas" a las revoluciones de los siglos XVIII y XIX?',
    opciones: [
      'Porque las impulsó una clase con poder económico pero sin poder político, que exigió igualdad jurídica y libertad económica',
      'Porque las dirigieron los campesinos',
      'Porque ocurrieron en pequeños burgos',
      'Porque las promovió la nobleza',
    ],
    correcta: 0,
    explicacion: 'La igualdad que reclamaban era ante la ley, no material. Por eso el sufragio censitario posterior limitó el voto a los propietarios: la revolución fue política, no social.',
  },
  {
    id: 'uni-070', tema: 'revoluciones', dificultad: 3,
    enunciado: '¿Qué fue el Terror durante la Revolución francesa?',
    opciones: [
      'Un periodo de represión política con ejecuciones masivas, justificado como defensa de la revolución amenazada',
      'La invasión de Francia por Inglaterra',
      'Una hambruna generalizada',
      'El regreso de la monarquía absoluta',
    ],
    correcta: 0,
    explicacion: 'Bajo Robespierre y el Comité de Salvación Pública. Plantea un problema clásico: hasta dónde puede una revolución suspender sus propios principios para sobrevivir.',
  },
  {
    id: 'uni-071', tema: 'revoluciones', dificultad: 3,
    enunciado: '¿Qué buscó el Congreso de Viena de 1815?',
    opciones: [
      'Restaurar el orden monárquico y reconfigurar el mapa europeo tras la derrota de Napoleón',
      'Proclamar repúblicas en toda Europa',
      'Abolir las fronteras nacionales',
      'Crear la Organización de las Naciones Unidas',
    ],
    correcta: 0,
    explicacion: 'El principio de legitimidad buscaba devolver los tronos anteriores. Funcionó durante unas décadas, pero no pudo contener el liberalismo ni los nacionalismos que estallaron en 1830 y 1848.',
  },
  {
    id: 'uni-072', tema: 'revoluciones', dificultad: 3,
    enunciado: '¿Qué relación hubo entre las revoluciones atlánticas y las independencias hispanoamericanas?',
    opciones: [
      'Compartieron ideas ilustradas y se aceleraron con la crisis de la monarquía española tras la invasión napoleónica',
      'Fueron procesos sin ninguna conexión',
      'Las independencias fueron anteriores a la Revolución francesa',
      'España concedió la independencia voluntariamente',
    ],
    correcta: 0,
    explicacion: 'Cuando Napoleón depuso a Fernando VII en 1808, las juntas americanas se formaron inicialmente en nombre del rey cautivo. De ahí a la independencia hubo un camino corto pero no automático.',
  },
  {
    id: 'uni-073', tema: 'revoluciones', dificultad: 4,
    enunciado: '¿Por qué la Declaración de 1789 hablaba de "hombre y ciudadano" y no incluía a todos?',
    opciones: [
      'Porque el universalismo proclamado convivió con exclusiones de mujeres, personas esclavizadas y no propietarios',
      'Porque el francés no tiene género neutro',
      'Porque era un documento provisional',
      'Porque se refería solo a los nobles',
    ],
    correcta: 0,
    explicacion: 'Esa contradicción fue el instrumento de las luchas posteriores: abolicionistas y sufragistas exigieron que se cumpliera lo que el texto ya afirmaba.',
  },
  {
    id: 'uni-074', tema: 'revoluciones', dificultad: 4,
    enunciado: '¿Por qué la Revolución haitiana recibió mucha menos atención histórica que la francesa o la norteamericana?',
    opciones: [
      'Porque cuestionaba directamente el orden esclavista y colonial del que dependían las potencias que escribían la historia',
      'Porque fue un episodio muy breve',
      'Porque no dejó documentos escritos',
      'Porque fracasó en sus objetivos',
    ],
    correcta: 0,
    explicacion: 'Triunfó, y precisamente por eso resultaba inquietante. El historiador Michel-Rolph Trouillot la describió como un acontecimiento "impensable" para las categorías de la época.',
  },
  {
    id: 'uni-075', tema: 'revoluciones', dificultad: 4,
    enunciado: '¿Qué muestra que tras las revoluciones el sufragio siguiera siendo censitario durante décadas?',
    opciones: [
      'Que la igualdad proclamada era jurídica y no política ni económica: el poder siguió ligado a la propiedad',
      'Que las revoluciones nunca ocurrieron',
      'Que el voto universal existía desde 1789',
      'Que la nobleza recuperó todos sus privilegios',
    ],
    correcta: 0,
    explicacion: 'El sufragio universal masculino llegó en Europa a lo largo del siglo XIX y el femenino, ya entrado el XX. La ampliación del derecho al voto fue una conquista posterior y lenta.',
  },

  // ----- Revolución industrial -----
  {
    id: 'uni-076', tema: 'industrial', dificultad: 1,
    enunciado: '¿En qué país comenzó la Revolución industrial a finales del siglo XVIII?',
    opciones: ['Inglaterra', 'Francia', 'Alemania', 'Estados Unidos'],
    correcta: 0,
    explicacion: 'Reunía carbón, hierro, capital acumulado, mano de obra disponible y un mercado colonial. Desde allí se extendió al resto de Europa y a Norteamérica.',
  },
  {
    id: 'uni-077', tema: 'industrial', dificultad: 1,
    enunciado: '¿Qué invento simboliza el inicio de la industrialización?',
    opciones: ['La máquina de vapor', 'La imprenta', 'El telégrafo', 'La bombilla eléctrica'],
    correcta: 0,
    explicacion: 'Perfeccionada por James Watt, liberó a la producción de la dependencia de ríos y fuerza animal, y permitió instalar fábricas donde conviniera.',
  },
  {
    id: 'uni-078', tema: 'industrial', dificultad: 1,
    enunciado: '¿Qué nueva clase social surgió con la industrialización?',
    opciones: [
      'El proletariado industrial, trabajadores asalariados sin medios de producción',
      'La nobleza terrateniente',
      'El clero regular',
      'Los artesanos gremiales',
    ],
    correcta: 0,
    explicacion: 'Muchos venían del campo o de oficios artesanales desplazados por la máquina. Vender su fuerza de trabajo por un salario era la única opción disponible.',
  },
  {
    id: 'uni-079', tema: 'industrial', dificultad: 2,
    enunciado: '¿Qué condiciones laborales caracterizaron a las primeras fábricas?',
    opciones: [
      'Jornadas de doce a dieciséis horas, trabajo infantil, salarios bajos y ninguna protección',
      'Jornada de ocho horas y vacaciones pagadas',
      'Contratos indefinidos con seguridad social',
      'Trabajo voluntario sin remuneración',
    ],
    correcta: 0,
    explicacion: 'Las primeras leyes fabriles inglesas, ya en el siglo XIX, se limitaron a restringir el trabajo de los menores. Todo lo que hoy se da por normal fue conquista posterior.',
  },
  {
    id: 'uni-080', tema: 'industrial', dificultad: 2,
    enunciado: '¿Qué fue el movimiento ludita?',
    opciones: [
      'La destrucción de máquinas por trabajadores que veían en ellas la causa de su desempleo y su miseria',
      'Un partido político obrero',
      'Una corriente artística industrial',
      'Un sindicato de ingenieros',
    ],
    correcta: 0,
    explicacion: 'Se suele citar como ejemplo de resistencia irracional al progreso, pero atacaban máquinas concretas en conflictos laborales concretos: era una táctica, no una fobia.',
  },
  {
    id: 'uni-081', tema: 'industrial', dificultad: 2,
    enunciado: '¿Qué efecto demográfico y urbano tuvo la industrialización?',
    opciones: [
      'Un crecimiento acelerado de las ciudades por migración desde el campo, con hacinamiento y problemas sanitarios',
      'El despoblamiento de las ciudades',
      'La desaparición de la agricultura',
      'La reducción de la población total',
    ],
    correcta: 0,
    explicacion: 'Manchester multiplicó su población en pocas décadas. Los brotes de cólera en barrios obreros impulsaron después las grandes obras de alcantarillado y salud pública.',
  },
  {
    id: 'uni-082', tema: 'industrial', dificultad: 2,
    enunciado: '¿Qué caracterizó a la segunda revolución industrial, desde finales del siglo XIX?',
    opciones: [
      'El uso de electricidad y petróleo, el acero, la química y la producción en cadena',
      'La vuelta a la energía hidráulica',
      'El abandono de la producción fabril',
      'La sustitución del ferrocarril por la navegación a vela',
    ],
    correcta: 0,
    explicacion: 'Cambia la escala y también la organización: aparecen las grandes corporaciones, la investigación aplicada y el taylorismo como forma de organizar el trabajo.',
  },
  {
    id: 'uni-083', tema: 'industrial', dificultad: 2,
    enunciado: '¿Qué respuestas políticas surgieron ante las condiciones obreras del siglo XIX?',
    opciones: [
      'Sindicatos, socialismo, anarquismo y doctrina social de la Iglesia',
      'Únicamente el liberalismo económico',
      'El feudalismo renovado',
      'El mercantilismo clásico',
    ],
    correcta: 0,
    explicacion: 'La llamada cuestión social generó respuestas muy distintas, desde la revolución hasta la reforma. La jornada de ocho horas y el derecho de asociación salen de esas luchas.',
  },
  {
    id: 'uni-084', tema: 'industrial', dificultad: 3,
    enunciado: '¿Por qué la Revolución industrial empezó en Inglaterra y no en otro lugar?',
    opciones: [
      'Por una combinación de carbón accesible, capital, instituciones favorables, mercado colonial y cercado de tierras que liberó mano de obra',
      'Por la superioridad intelectual de sus científicos',
      'Porque era el país más poblado',
      'Porque carecía de agricultura',
    ],
    correcta: 0,
    explicacion: 'Ninguno de esos factores basta por sí solo, y el debate historiográfico sigue abierto sobre el peso de cada uno. Lo que ningún historiador sostiene es una explicación monocausal.',
  },
  {
    id: 'uni-085', tema: 'industrial', dificultad: 3,
    enunciado: '¿Qué significó el paso del taller artesanal a la fábrica para el trabajador?',
    opciones: [
      'Perdió control sobre el ritmo, el proceso y el producto de su trabajo, sometido a la disciplina del reloj y de la máquina',
      'Ganó autonomía sobre su horario',
      'Mantuvo intacta su forma de trabajar',
      'Aumentó de inmediato su nivel de vida',
    ],
    correcta: 0,
    explicacion: 'El artesano dominaba todo el oficio; el obrero fabril ejecuta una parte. Esa pérdida de control es lo que Marx analizó bajo el concepto de alienación.',
  },
  {
    id: 'uni-086', tema: 'industrial', dificultad: 3,
    enunciado: '¿Por qué el ferrocarril fue más que un medio de transporte?',
    opciones: [
      'Integró mercados nacionales, abarató el transporte, impulsó la siderurgia y cambió la percepción del tiempo y la distancia',
      'Solo sirvió para el turismo',
      'Fue un invento sin consecuencias económicas',
      'Sustituyó por completo a la navegación',
    ],
    correcta: 0,
    explicacion: 'La necesidad de coordinar horarios llevó incluso a unificar la hora en cada país, que antes variaba de ciudad en ciudad. La técnica reorganizó la vida cotidiana.',
  },
  {
    id: 'uni-087', tema: 'industrial', dificultad: 3,
    enunciado: '¿Qué relación hay entre industrialización y colonialismo en el siglo XIX?',
    opciones: [
      'Las colonias proveían materias primas baratas y mercados cautivos para las manufacturas europeas',
      'El colonialismo terminó con la industrialización',
      'No hubo relación económica entre ambos procesos',
      'Las colonias se industrializaron al mismo ritmo',
    ],
    correcta: 0,
    explicacion: 'India pasó de exportar textiles a comprarlos de Inglaterra. La relación no fue solo comercial: incluyó medidas deliberadas para desmontar industrias locales competidoras.',
  },
  {
    id: 'uni-088', tema: 'industrial', dificultad: 4,
    enunciado: '¿Por qué se discute si la industrialización mejoró el nivel de vida en el corto plazo?',
    opciones: [
      'Porque los indicadores de salarios, estatura y esperanza de vida de las primeras generaciones obreras empeoraron o se estancaron durante décadas',
      'Porque no existen datos de la época',
      'Porque todos los historiadores coinciden en que mejoró de inmediato',
      'Porque el nivel de vida no puede medirse',
    ],
    correcta: 0,
    explicacion: 'Es el debate entre optimistas y pesimistas. A largo plazo el crecimiento fue indiscutible; la discusión es quién pagó el costo de la transición y durante cuánto tiempo.',
  },
  {
    id: 'uni-089', tema: 'industrial', dificultad: 4,
    enunciado: '¿Qué papel cumplió el cercado de tierras comunales inglés en el proceso industrial?',
    opciones: [
      'Privatizó tierras de uso común y expulsó a campesinos que pasaron a engrosar la mano de obra urbana',
      'Repartió tierras entre los campesinos pobres',
      'Impidió el crecimiento de las ciudades',
      'No tuvo relación con la industria',
    ],
    correcta: 0,
    explicacion: 'Los enclosures aumentaron la productividad agrícola y a la vez crearon una población sin medios propios de subsistencia. Las fábricas encontraron así trabajadores disponibles.',
  },
  {
    id: 'uni-090', tema: 'industrial', dificultad: 4,
    enunciado: '¿Qué legado ambiental dejó la industrialización que hoy se estudia como punto de inflexión?',
    opciones: [
      'El uso masivo de combustibles fósiles, origen del aumento sostenido de CO₂ atmosférico',
      'La reforestación de Europa',
      'La reducción de la contaminación urbana',
      'La estabilización del clima global',
    ],
    correcta: 0,
    explicacion: 'Varios científicos proponen situar ahí el comienzo del Antropoceno. La responsabilidad histórica de las emisiones es hoy un argumento central en las negociaciones climáticas.',
  },
  // ----- Imperialismo y siglo XIX -----
  {
    id: 'uni-091', tema: 'imperialismo', dificultad: 1,
    enunciado: '¿Qué fue el imperialismo del siglo XIX?',
    opciones: [
      'La expansión y dominación política y económica de las potencias europeas sobre África y Asia',
      'La unificación de los Estados europeos',
      'Un movimiento artístico de la época victoriana',
      'La independencia de las colonias americanas',
    ],
    correcta: 0,
    explicacion: 'Se distingue del colonialismo anterior por su escala, su velocidad y su justificación explícitamente racial y civilizatoria.',
  },
  {
    id: 'uni-092', tema: 'imperialismo', dificultad: 1,
    enunciado: '¿Qué decidió la Conferencia de Berlín de 1884-1885?',
    opciones: [
      'Las reglas del reparto de África entre las potencias europeas, sin participación africana',
      'La independencia de las colonias africanas',
      'El fin de la esclavitud en el mundo',
      'La creación de la Sociedad de Naciones',
    ],
    correcta: 0,
    explicacion: 'Las fronteras trazadas con regla sobre el mapa ignoraron pueblos y territorios previos, y siguen siendo fuente de conflictos.',
  },
  {
    id: 'uni-093', tema: 'imperialismo', dificultad: 1,
    enunciado: '¿Qué países se unificaron como Estados nacionales en 1870-1871?',
    opciones: ['Italia y Alemania', 'España y Portugal', 'Francia y Bélgica', 'Rusia y Polonia'],
    correcta: 0,
    explicacion: 'Dos territorios fragmentados durante siglos se convirtieron en potencias. La unificación alemana, liderada por Prusia y Bismarck, alteró el equilibrio europeo.',
  },
  {
    id: 'uni-094', tema: 'imperialismo', dificultad: 2,
    enunciado: '¿Qué causas económicas impulsaron el imperialismo?',
    opciones: [
      'La búsqueda de materias primas, mercados para las manufacturas y destinos para el capital excedente',
      'La falta de población en Europa',
      'La escasez de tierras cultivables en las colonias',
      'El desinterés por el comercio internacional',
    ],
    correcta: 0,
    explicacion: 'Caucho, algodón, cobre y estaño alimentaban la industria. Hobson y Lenin analizaron además la exportación de capitales como motor específico de la fase imperialista.',
  },
  {
    id: 'uni-095', tema: 'imperialismo', dificultad: 2,
    enunciado: '¿Con qué ideas se justificó ideológicamente el imperialismo?',
    opciones: [
      'El darwinismo social y la idea de una misión civilizadora de Europa sobre pueblos considerados inferiores',
      'La igualdad de todas las culturas',
      'El principio de autodeterminación de los pueblos',
      'La doctrina del libre comercio equitativo',
    ],
    correcta: 0,
    explicacion: 'Aplicar la selección natural a las sociedades era un error científico y una coartada política eficaz: convertía la dominación en ley natural y hasta en deber moral.',
  },
  {
    id: 'uni-096', tema: 'imperialismo', dificultad: 2,
    enunciado: '¿Qué caracterizó al nacionalismo del siglo XIX?',
    opciones: [
      'La idea de que cada nación, definida por lengua, cultura o historia, debe tener su propio Estado',
      'La defensa de los imperios multiétnicos',
      'El rechazo de las fronteras',
      'La preferencia por el gobierno extranjero',
    ],
    correcta: 0,
    explicacion: 'Sirvió tanto para unificar (Italia, Alemania) como para disgregar imperios (el austrohúngaro, el otomano). Es una fuerza política ambivalente desde su origen.',
  },
  {
    id: 'uni-097', tema: 'imperialismo', dificultad: 2,
    enunciado: '¿Qué fue el sistema de alianzas previo a 1914?',
    opciones: [
      'Dos bloques enfrentados —Triple Alianza y Triple Entente— que convirtieron un conflicto local en guerra general',
      'Un acuerdo de desarme entre las potencias',
      'Una unión aduanera europea',
      'Un pacto para repartirse América',
    ],
    correcta: 0,
    explicacion: 'Los tratados obligaban a entrar en guerra si un aliado era atacado. Ese mecanismo automático es lo que hizo que el atentado de Sarajevo arrastrara a todo el continente.',
  },
  {
    id: 'uni-098', tema: 'imperialismo', dificultad: 2,
    enunciado: '¿Qué fue la paz armada?',
    opciones: [
      'El periodo previo a 1914 de carrera armamentista y tensión creciente sin guerra declarada',
      'Un tratado firmado en 1900',
      'El desarme general de Europa',
      'La ocupación militar de los Balcanes',
    ],
    correcta: 0,
    explicacion: 'La competencia naval entre Alemania y Gran Bretaña es el caso más citado. Prepararse para la guerra como forma de evitarla terminó haciéndola más probable.',
  },
  {
    id: 'uni-099', tema: 'imperialismo', dificultad: 3,
    enunciado: '¿Por qué las fronteras africanas trazadas en el siglo XIX siguen generando conflictos?',
    opciones: [
      'Porque dividieron pueblos y agruparon comunidades rivales sin atender a realidades previas',
      'Porque fueron modificadas cada década',
      'Porque los Estados africanos las rechazaron al independizarse',
      'Porque siguieron exactamente los límites étnicos',
    ],
    correcta: 0,
    explicacion: 'La Organización de la Unidad Africana decidió en 1964 respetarlas pese a su origen, por temor a guerras masivas de revisión. El problema quedó congelado, no resuelto.',
  },
  {
    id: 'uni-100', tema: 'imperialismo', dificultad: 3,
    enunciado: '¿Qué significó para India el dominio británico en términos económicos?',
    opciones: [
      'Pasó de ser un gran exportador de textiles a un proveedor de materias primas y comprador de manufacturas británicas',
      'Se industrializó al mismo ritmo que Gran Bretaña',
      'Mantuvo intacta su estructura productiva',
      'Se benefició de un comercio equitativo',
    ],
    correcta: 0,
    explicacion: 'Aranceles asimétricos y decisiones administrativas desmontaron la industria textil local. Es el ejemplo más estudiado de desindustrialización colonial.',
  },
  {
    id: 'uni-101', tema: 'imperialismo', dificultad: 3,
    enunciado: '¿Qué papel tuvieron los Balcanes en el origen de la Primera Guerra Mundial?',
    opciones: [
      'Fueron el punto de choque entre nacionalismos locales y los intereses de Austria-Hungría y Rusia',
      'Permanecieron neutrales durante todo el conflicto',
      'Eran una región sin importancia estratégica',
      'Estaban unificados bajo un solo Estado',
    ],
    correcta: 0,
    explicacion: 'Se les llamó "el polvorín de Europa". La decadencia otomana dejó un vacío que dos imperios rivales intentaron llenar, con los nacionalismos eslavos de por medio.',
  },
  {
    id: 'uni-102', tema: 'imperialismo', dificultad: 3,
    enunciado: '¿Qué fue el Congo de Leopoldo II?',
    opciones: [
      'Una colonia administrada como propiedad personal del rey belga, con trabajo forzado y violencia extrema por el caucho',
      'Una colonia modelo con autogobierno local',
      'Un protectorado francés',
      'Un territorio independiente reconocido en Berlín',
    ],
    correcta: 0,
    explicacion: 'Las denuncias internacionales obligaron a Bélgica a asumir su administración en 1908. Las estimaciones de muertes se cuentan por millones y el caso marcó la primera gran campaña humanitaria moderna.',
  },
  {
    id: 'uni-103', tema: 'imperialismo', dificultad: 4,
    enunciado: '¿Por qué decir que la Primera Guerra Mundial fue causada por el atentado de Sarajevo es insuficiente?',
    opciones: [
      'Porque el atentado fue el detonante de tensiones acumuladas: alianzas, imperialismo, nacionalismo y carrera armamentista',
      'Porque el atentado nunca ocurrió',
      'Porque la guerra comenzó años antes',
      'Porque las potencias no tenían ejércitos',
    ],
    correcta: 0,
    explicacion: 'Distinguir causas profundas de detonante es una operación básica del análisis histórico. Sin el contexto, un asesinato político en una ciudad periférica no habría movilizado a millones.',
    pista: 'Pregúntate por qué ese hecho concreto pudo tener consecuencias tan desproporcionadas.',
  },
  {
    id: 'uni-104', tema: 'imperialismo', dificultad: 4,
    enunciado: '¿Qué tensión encierra que potencias que proclamaban libertad y derechos mantuvieran imperios coloniales?',
    opciones: [
      'Se resolvió negando la plena humanidad o madurez política de los pueblos colonizados, mediante teorías raciales y tutelares',
      'No existió tal tensión',
      'Se resolvió concediendo ciudadanía plena a las colonias',
      'Los imperios abandonaron el discurso de los derechos',
    ],
    correcta: 0,
    explicacion: 'La figura del "mandato" en la Sociedad de Naciones ilustra el mecanismo: dominación presentada como tutela transitoria hacia una autonomía que se postergaba indefinidamente.',
  },
  {
    id: 'uni-105', tema: 'imperialismo', dificultad: 4,
    enunciado: '¿Por qué el nacionalismo pudo ser a la vez emancipador y agresivo?',
    opciones: [
      'Porque el mismo principio que justifica liberarse de un imperio puede justificar imponerse sobre otros pueblos considerados inferiores',
      'Porque cambió de significado en el siglo XX',
      'Porque siempre fue exclusivamente defensivo',
      'Porque no tuvo consecuencias políticas',
    ],
    correcta: 0,
    explicacion: 'La autodeterminación de los pueblos y la expansión imperial se apoyaron en la misma idea de nación. Todo depende de dónde se trace la frontera de quién forma parte de ella.',
  },

  // ----- Las guerras mundiales -----
  {
    id: 'uni-106', tema: 'guerras', dificultad: 1,
    enunciado: '¿Entre qué años se desarrolló la Primera Guerra Mundial?',
    opciones: ['1914-1918', '1939-1945', '1900-1910', '1920-1925'],
    correcta: 0,
    explicacion: 'Se la llamó "la Gran Guerra" hasta que estalló la segunda. Dejó cerca de diez millones de muertos militares.',
  },
  {
    id: 'uni-107', tema: 'guerras', dificultad: 1,
    enunciado: '¿Qué impuso el Tratado de Versalles a Alemania en 1919?',
    opciones: [
      'La responsabilidad de la guerra, fuertes reparaciones económicas y limitaciones militares y territoriales',
      'Un trato de igualdad con los vencedores',
      'La devolución de todas sus colonias',
      'La creación de un imperio ampliado',
    ],
    correcta: 0,
    explicacion: 'La cláusula de culpabilidad y las reparaciones alimentaron el resentimiento que el nazismo explotó después. Keynes advirtió de ello en 1919 y no fue escuchado.',
  },
  {
    id: 'uni-108', tema: 'guerras', dificultad: 1,
    enunciado: '¿Qué fue el Holocausto?',
    opciones: [
      'El exterminio sistemático de unos seis millones de judíos por el régimen nazi, junto a otros grupos perseguidos',
      'Una batalla del frente oriental',
      'Un plan de reconstrucción europea',
      'Un tratado de paz firmado en 1945',
    ],
    correcta: 0,
    explicacion: 'También fueron perseguidos y asesinados gitanos, personas con discapacidad, homosexuales, opositores políticos y prisioneros soviéticos.',
  },
  {
    id: 'uni-109', tema: 'guerras', dificultad: 2,
    enunciado: '¿Qué caracterizó a la guerra de trincheras de 1914-1918?',
    opciones: [
      'Frentes estáticos durante años, con enormes pérdidas humanas por avances mínimos',
      'Avances rápidos con tanques y aviación',
      'Combates exclusivamente navales',
      'Una guerra breve y con pocas bajas',
    ],
    correcta: 0,
    explicacion: 'La ametralladora y la artillería favorecían al defensor. El desfase entre la tecnología defensiva y la táctica ofensiva explica la matanza de batallas como el Somme o Verdún.',
  },
  {
    id: 'uni-110', tema: 'guerras', dificultad: 2,
    enunciado: '¿Qué fue la crisis de 1929?',
    opciones: [
      'El desplome bursátil en Estados Unidos que desencadenó la Gran Depresión mundial',
      'Una guerra comercial entre Europa y Asia',
      'La quiebra del sistema colonial',
      'Una epidemia que paralizó la economía',
    ],
    correcta: 0,
    explicacion: 'El desempleo masivo y la caída del comercio internacional crearon el terreno social en el que crecieron los movimientos autoritarios de los años treinta.',
  },
  {
    id: 'uni-111', tema: 'guerras', dificultad: 2,
    enunciado: '¿Qué caracteriza a un régimen totalitario como el nazi o el estalinista?',
    opciones: [
      'Partido único, control de la información, terror policial y pretensión de dominar todos los aspectos de la vida',
      'Elecciones competitivas con varios partidos',
      'Separación estricta de poderes',
      'Libertad de prensa garantizada',
    ],
    correcta: 0,
    explicacion: 'Arendt subrayó que no se conforman con la obediencia externa, como las dictaduras tradicionales: buscan transformar a las personas y ocupar también su vida privada.',
  },
  {
    id: 'uni-112', tema: 'guerras', dificultad: 2,
    enunciado: '¿Qué fue el New Deal?',
    opciones: [
      'El programa de intervención estatal de Roosevelt para salir de la Gran Depresión mediante obra pública y regulación',
      'Un tratado militar entre Estados Unidos y Europa',
      'Un plan de reducción del gasto público',
      'Un acuerdo comercial con Japón',
    ],
    correcta: 0,
    explicacion: 'Rompió con la ortodoxia del laissez-faire y sentó las bases de la seguridad social estadounidense. Es también el momento en que las ideas keynesianas entran en la política práctica.',
  },
  {
    id: 'uni-113', tema: 'guerras', dificultad: 2,
    enunciado: '¿Qué fue la política de apaciguamiento de finales de los años treinta?',
    opciones: [
      'Las concesiones de Francia y Gran Bretaña a las exigencias territoriales de Hitler para evitar una guerra',
      'Un pacto de desarme entre las potencias',
      'La alianza militar contra la URSS',
      'El plan de reconstrucción de posguerra',
    ],
    correcta: 0,
    explicacion: 'Los acuerdos de Múnich de 1938 son su símbolo. El término quedó como sinónimo de ceder ante un agresor con la esperanza, luego frustrada, de que se conforme.',
  },
  {
    id: 'uni-114', tema: 'guerras', dificultad: 3,
    enunciado: '¿Por qué la Primera Guerra Mundial se considera una "guerra total"?',
    opciones: [
      'Porque movilizó toda la economía y la población civil, y no solo a los ejércitos',
      'Porque participaron todos los países del mundo',
      'Porque duró más que cualquier otra guerra',
      'Porque se libró únicamente en Europa',
    ],
    correcta: 0,
    explicacion: 'Industria reconvertida, racionamiento, propaganda y mujeres incorporadas masivamente al trabajo. La frontera entre frente y retaguardia se difumina, y con ella la del objetivo militar.',
  },
  {
    id: 'uni-115', tema: 'guerras', dificultad: 3,
    enunciado: '¿Qué relación hay entre el Tratado de Versalles y el ascenso del nazismo?',
    opciones: [
      'Creó un clima de humillación y crisis que el nazismo capitalizó, aunque no fue su única causa',
      'Fue la causa exclusiva y suficiente del nazismo',
      'No tuvo ninguna relación con lo ocurrido en los años treinta',
      'Impidió cualquier movimiento autoritario en Alemania',
    ],
    correcta: 0,
    explicacion: 'La hiperinflación, la crisis de 1929 y la debilidad institucional de Weimar pesaron tanto como el tratado. Reducirlo a una sola causa simplifica un proceso con varias capas.',
  },
  {
    id: 'uni-116', tema: 'guerras', dificultad: 3,
    enunciado: '¿Qué significó el uso de la bomba atómica en 1945?',
    opciones: [
      'Aceleró la rendición de Japón e inauguró la era nuclear, con un debate ético abierto hasta hoy',
      'No tuvo efecto sobre el fin de la guerra',
      'Fue utilizada contra Alemania',
      'Se empleó únicamente como prueba en el desierto',
    ],
    correcta: 0,
    explicacion: 'La discusión sobre si era necesaria, dada la situación militar japonesa y la entrada soviética en la guerra, sigue viva entre los historiadores.',
  },
  {
    id: 'uni-117', tema: 'guerras', dificultad: 3,
    enunciado: '¿Qué establecieron los juicios de Núremberg?',
    opciones: [
      'Que existen crímenes contra la humanidad por los que responden individuos, y que obedecer órdenes no exime de responsabilidad',
      'Que solo los Estados pueden ser juzgados',
      'Que los vencedores no pueden juzgar a los vencidos',
      'Que la guerra no genera responsabilidades penales',
    ],
    correcta: 0,
    explicacion: 'Sentaron las bases del derecho penal internacional y, en última instancia, de la Corte Penal Internacional. Se les criticó por ser justicia de vencedores y por aplicar figuras creadas después de los hechos.',
  },
  {
    id: 'uni-118', tema: 'guerras', dificultad: 4,
    enunciado: '¿Por qué el Holocausto se estudia como fenómeno moderno y no solo como una explosión de barbarie?',
    opciones: [
      'Porque requirió burocracia, tecnología, registros y división del trabajo: el aparato de un Estado moderno puesto al servicio del exterminio',
      'Porque ocurrió en el siglo XX',
      'Porque fue un hecho espontáneo y desorganizado',
      'Porque no dejó documentación',
    ],
    correcta: 0,
    explicacion: 'Bauman desarrolló esta tesis: no fue un retroceso a la barbarie sino una posibilidad inscrita en la racionalidad instrumental moderna. Por eso la pregunta no es cómo evitar el salvajismo, sino cómo limitar la obediencia técnica.',
  },
  {
    id: 'uni-119', tema: 'guerras', dificultad: 4,
    enunciado: '¿Por qué algunos historiadores hablan de una "guerra de treinta años" entre 1914 y 1945?',
    opciones: [
      'Porque interpretan las dos guerras y el periodo intermedio como fases de un mismo conflicto no resuelto',
      'Porque hubo combates continuos durante treinta años',
      'Porque fue el nombre oficial de la época',
      'Porque coincidió con la guerra del siglo XVII',
    ],
    correcta: 0,
    explicacion: 'La tesis subraya la continuidad: las condiciones impuestas en 1919 no cerraron el conflicto, sino que lo pospusieron. Otros historiadores objetan que borra diferencias importantes entre ambas guerras.',
  },
  {
    id: 'uni-120', tema: 'guerras', dificultad: 4,
    enunciado: '¿Qué instituciones nacieron tras 1945 para evitar una nueva guerra mundial?',
    opciones: [
      'La ONU, el sistema de Bretton Woods y la Declaración Universal de Derechos Humanos',
      'La Sociedad de Naciones y el Pacto de Varsovia',
      'La OTAN y la Unión Europea únicamente',
      'El Congreso de Viena y la Santa Alianza',
    ],
    correcta: 0,
    explicacion: 'La Sociedad de Naciones es de 1919 y fracasó. El diseño de 1945 combinó seguridad colectiva, estabilidad monetaria y derechos humanos, en la convicción de que los tres problemas estaban ligados.',
  },
  // ----- Guerra Fría y descolonización -----
  {
    id: 'uni-121', tema: 'guerra-fria', dificultad: 1,
    enunciado: '¿Qué dos potencias protagonizaron la Guerra Fría?',
    opciones: ['Estados Unidos y la Unión Soviética', 'Alemania y Japón', 'Francia y el Reino Unido', 'China e India'],
    correcta: 0,
    explicacion: 'Se llamó "fría" porque las dos superpotencias nunca se enfrentaron directamente, aunque sí lo hicieron a través de terceros países.',
  },
  {
    id: 'uni-122', tema: 'guerra-fria', dificultad: 1,
    enunciado: '¿Qué simbolizó el Muro de Berlín?',
    opciones: [
      'La división de Europa en dos bloques enfrentados',
      'La unificación alemana',
      'El fin de la Segunda Guerra Mundial',
      'La creación de la Unión Europea',
    ],
    correcta: 0,
    explicacion: 'Levantado en 1961 y derribado en 1989. Su caída se toma como el símbolo del fin de la Guerra Fría, dos años antes de la disolución de la URSS.',
  },
  {
    id: 'uni-123', tema: 'guerra-fria', dificultad: 1,
    enunciado: '¿Qué fue la descolonización?',
    opciones: [
      'El proceso por el que las colonias de África y Asia accedieron a la independencia tras 1945',
      'La conquista de nuevos territorios por Europa',
      'La unificación de los imperios coloniales',
      'El traslado de población europea a las colonias',
    ],
    correcta: 0,
    explicacion: 'Entre 1945 y 1975 nacieron decenas de Estados. Unos por negociación, como India, y otros tras guerras prolongadas, como Argelia o Vietnam.',
  },
  {
    id: 'uni-124', tema: 'guerra-fria', dificultad: 2,
    enunciado: '¿Qué fue el Plan Marshall?',
    opciones: [
      'La ayuda económica estadounidense para reconstruir Europa occidental y frenar la expansión del comunismo',
      'Un plan militar de invasión de Europa del Este',
      'Un tratado de desarme nuclear',
      'Un programa soviético de industrialización',
    ],
    correcta: 0,
    explicacion: 'Combinaba generosidad y cálculo estratégico: una Europa próspera sería un mercado y un muro de contención. La URSS impidió que los países de su órbita participaran.',
  },
  {
    id: 'uni-125', tema: 'guerra-fria', dificultad: 2,
    enunciado: '¿En qué consistió la doctrina de la contención?',
    opciones: [
      'La estrategia estadounidense de impedir la expansión de la influencia soviética sin atacarla directamente',
      'El desarme unilateral de las potencias',
      'La ocupación militar de Europa del Este',
      'La renuncia a las armas nucleares',
    ],
    correcta: 0,
    explicacion: 'La formuló el diplomático George Kennan. Explica intervenciones muy distintas, desde el Plan Marshall hasta Corea o Vietnam.',
  },
  {
    id: 'uni-126', tema: 'guerra-fria', dificultad: 2,
    enunciado: '¿Qué fue la crisis de los misiles de 1962?',
    opciones: [
      'El momento de mayor riesgo de guerra nuclear, por el despliegue de misiles soviéticos en Cuba',
      'Una guerra abierta entre Estados Unidos y la URSS',
      'La invasión soviética de Afganistán',
      'El lanzamiento del primer satélite artificial',
    ],
    correcta: 0,
    explicacion: 'Se resolvió con la retirada de los misiles de Cuba y, discretamente, de los estadounidenses en Turquía. Tras el susto se instaló el teléfono rojo entre Washington y Moscú.',
  },
  {
    id: 'uni-127', tema: 'guerra-fria', dificultad: 2,
    enunciado: '¿Qué fue el Movimiento de Países No Alineados?',
    opciones: [
      'Un bloque de países que rechazó alinearse con Washington o Moscú y reivindicó una voz propia del Sur global',
      'Una alianza militar contra la URSS',
      'Un organismo económico europeo',
      'Un grupo de países neutrales durante la Segunda Guerra Mundial',
    ],
    correcta: 0,
    explicacion: 'Se consolidó en la conferencia de Bandung en 1955, con India, Egipto, Indonesia y Yugoslavia entre sus impulsores. Colombia ha participado en él.',
  },
  {
    id: 'uni-128', tema: 'guerra-fria', dificultad: 2,
    enunciado: '¿Qué caracterizó a la carrera espacial?',
    opciones: [
      'La competencia tecnológica y simbólica entre las dos superpotencias, del Sputnik a la llegada a la Luna',
      'Una colaboración científica entre ambos bloques',
      'Un programa exclusivamente civil sin implicaciones militares',
      'Una iniciativa de las Naciones Unidas',
    ],
    correcta: 0,
    explicacion: 'Los mismos cohetes servían para poner satélites y para lanzar ojivas. El prestigio internacional y la capacidad militar avanzaban juntos.',
  },
  {
    id: 'uni-129', tema: 'guerra-fria', dificultad: 3,
    enunciado: '¿Por qué se habla de "guerras por delegación" durante la Guerra Fría?',
    opciones: [
      'Porque las superpotencias apoyaron bandos opuestos en conflictos locales sin enfrentarse entre sí',
      'Porque delegaron la guerra en la ONU',
      'Porque los combates los libraban mercenarios exclusivamente',
      'Porque no hubo ningún conflicto armado',
    ],
    correcta: 0,
    explicacion: 'Corea, Vietnam, Angola, Afganistán y varios conflictos latinoamericanos. La expresión no debe hacer olvidar que esos países tenían conflictos propios anteriores a la intervención externa.',
  },
  {
    id: 'uni-130', tema: 'guerra-fria', dificultad: 3,
    enunciado: '¿Qué fue la doctrina de la destrucción mutua asegurada?',
    opciones: [
      'La idea de que ningún bando atacaría primero porque la respuesta nuclear destruiría también al agresor',
      'Un plan para eliminar todas las armas nucleares',
      'Una estrategia de invasión simultánea',
      'Un tratado firmado en 1945',
    ],
    correcta: 0,
    explicacion: 'La disuasión convirtió la vulnerabilidad en garantía de paz, una lógica tan eficaz como frágil: dependía de que ambas partes fueran racionales y estuvieran bien informadas.',
  },
  {
    id: 'uni-131', tema: 'guerra-fria', dificultad: 3,
    enunciado: '¿Qué dificultades enfrentaron muchos Estados africanos al independizarse?',
    opciones: [
      'Fronteras artificiales, economías dependientes de un solo producto y élites administrativas escasas',
      'Exceso de industria pesada',
      'Ausencia total de recursos naturales',
      'Poblaciones homogéneas sin diversidad',
    ],
    correcta: 0,
    explicacion: 'La independencia política no trajo independencia económica. A eso se sumó la injerencia de las potencias durante la Guerra Fría, que apoyó regímenes según su alineamiento.',
  },
  {
    id: 'uni-132', tema: 'guerra-fria', dificultad: 3,
    enunciado: '¿Qué causas explican la disolución de la URSS en 1991?',
    opciones: [
      'Estancamiento económico, costo de la carrera armamentista, presiones nacionalistas internas y las reformas de Gorbachov',
      'Una invasión militar extranjera',
      'Una única mala cosecha',
      'La decisión unilateral de Estados Unidos',
    ],
    correcta: 0,
    explicacion: 'Perestroika y glásnost buscaban reformar el sistema y terminaron acelerando su desintegración: la apertura informativa hizo visibles problemas que el régimen no podía resolver.',
  },
  {
    id: 'uni-133', tema: 'guerra-fria', dificultad: 4,
    enunciado: '¿Por qué la descolonización no siempre significó autonomía real?',
    opciones: [
      'Porque persistieron dependencias económicas, deuda y control sobre recursos por parte de las antiguas metrópolis y empresas extranjeras',
      'Porque las colonias pidieron volver a serlo',
      'Porque la independencia fue solo nominal en el papel',
      'Porque la ONU no reconoció a los nuevos Estados',
    ],
    correcta: 0,
    explicacion: 'Es lo que se denominó neocolonialismo. El poder dejó de ejercerse por administración directa y pasó a ejercerse por contratos, deuda y condicionamientos.',
  },
  {
    id: 'uni-134', tema: 'guerra-fria', dificultad: 4,
    enunciado: '¿Qué significó para América Latina la Doctrina de Seguridad Nacional durante la Guerra Fría?',
    opciones: [
      'La identificación del enemigo interno como amenaza principal, que justificó dictaduras y represión política',
      'Un plan de desarrollo económico regional',
      'La neutralidad frente a los dos bloques',
      'Un acuerdo de integración comercial',
    ],
    correcta: 0,
    explicacion: 'Bajo esa lógica, opositores, sindicalistas y estudiantes pasaron a ser tratados como enemigos militares. Explica en parte el ciclo de golpes de Estado de los años sesenta y setenta.',
  },
  {
    id: 'uni-135', tema: 'guerra-fria', dificultad: 4,
    enunciado: '¿Por qué la tesis del "fin de la historia" tras 1991 resultó prematura?',
    opciones: [
      'Porque la democracia liberal no se impuso universalmente y surgieron nuevos conflictos identitarios, religiosos y autoritarios',
      'Porque la Guerra Fría continuó hasta 2001',
      'Porque la URSS no llegó a disolverse',
      'Porque todos los países adoptaron el mismo modelo',
    ],
    correcta: 0,
    explicacion: 'Fukuyama planteaba el triunfo definitivo de un modelo, no el final de los acontecimientos. Las guerras balcánicas, el ascenso de China y los populismos posteriores mostraron que el proceso no era irreversible.',
  },

  // ----- Mundo contemporáneo -----
  {
    id: 'uni-136', tema: 'actual', dificultad: 1,
    enunciado: '¿Qué es la globalización?',
    opciones: [
      'La creciente interconexión económica, cultural y tecnológica entre países',
      'La unificación política del mundo en un solo Estado',
      'El cierre de las fronteras comerciales',
      'La desaparición de las lenguas nacionales',
    ],
    correcta: 0,
    explicacion: 'No es un fenómeno nuevo, pero su velocidad y alcance cambiaron con los contenedores, las telecomunicaciones y la liberalización comercial desde los años ochenta.',
  },
  {
    id: 'uni-137', tema: 'actual', dificultad: 1,
    enunciado: '¿Cuál es el principal organismo internacional creado en 1945 para preservar la paz?',
    opciones: [
      'La Organización de las Naciones Unidas',
      'La Sociedad de Naciones',
      'La OTAN',
      'La Organización Mundial del Comercio',
    ],
    correcta: 0,
    explicacion: 'La Sociedad de Naciones fue su antecesora, creada en 1919 y fracasada en los años treinta. La OTAN es una alianza militar y la OMC, un organismo comercial.',
  },
  {
    id: 'uni-138', tema: 'actual', dificultad: 1,
    enunciado: '¿Qué acontecimiento marcó el inicio de la llamada "guerra contra el terrorismo"?',
    opciones: [
      'Los atentados del 11 de septiembre de 2001 en Estados Unidos',
      'La caída del Muro de Berlín',
      'La crisis financiera de 2008',
      'La disolución de la URSS',
    ],
    correcta: 0,
    explicacion: 'Derivó en las intervenciones en Afganistán e Irak y en un debate aún abierto sobre el equilibrio entre seguridad y libertades civiles.',
  },
  {
    id: 'uni-139', tema: 'actual', dificultad: 2,
    enunciado: '¿Qué originó la crisis financiera de 2008?',
    opciones: [
      'El colapso del mercado hipotecario estadounidense y los productos financieros construidos sobre él',
      'Una guerra comercial entre China y Europa',
      'La subida del precio del petróleo',
      'El fin del patrón oro',
    ],
    correcta: 0,
    explicacion: 'Las hipotecas de alto riesgo se empaquetaron y se vendieron como activos seguros. Cuando el impago se generalizó, el riesgo estaba repartido por todo el sistema financiero mundial.',
  },
  {
    id: 'uni-140', tema: 'actual', dificultad: 2,
    enunciado: '¿Qué es la Unión Europea?',
    opciones: [
      'Un proyecto de integración económica y política entre Estados europeos, con instituciones y moneda común para varios de ellos',
      'Una alianza militar',
      'Un Estado federal único',
      'Una organización exclusivamente comercial sin instituciones',
    ],
    correcta: 0,
    explicacion: 'Nació tras la Segunda Guerra Mundial con la idea de que integrar economías haría impensable otra guerra entre sus miembros. El euro circula desde 2002.',
  },
  {
    id: 'uni-141', tema: 'actual', dificultad: 2,
    enunciado: '¿Qué transformó internet en las últimas décadas?',
    opciones: [
      'El acceso a la información, la comunicación global, el comercio y las formas de organización política',
      'Únicamente la industria del entretenimiento',
      'Solo el ámbito académico',
      'Nada sustancial fuera de la informática',
    ],
    correcta: 0,
    explicacion: 'Su efecto es ambivalente: facilitó movilizaciones y acceso al conocimiento, y también la desinformación, la vigilancia y la concentración de poder en pocas plataformas.',
  },
  {
    id: 'uni-142', tema: 'actual', dificultad: 2,
    enunciado: '¿Qué caracteriza a las migraciones contemporáneas?',
    opciones: [
      'Son masivas y multicausales: guerras, pobreza, persecución y, cada vez más, causas ambientales',
      'Se deben exclusivamente a motivos económicos',
      'Han disminuido respecto al siglo XX',
      'Solo afectan a países europeos',
    ],
    correcta: 0,
    explicacion: 'La mayor parte del desplazamiento ocurre dentro del Sur global, no hacia los países ricos. La migración venezolana hacia Colombia es uno de los casos más grandes del mundo reciente.',
  },
  {
    id: 'uni-143', tema: 'actual', dificultad: 3,
    enunciado: '¿Por qué se dice que la globalización produjo ganadores y perdedores dentro de cada país?',
    opciones: [
      'Porque benefició a sectores exportadores y a consumidores, y perjudicó a industrias y trabajadores expuestos a la competencia externa',
      'Porque solo perjudicó a los países pobres',
      'Porque benefició por igual a toda la población',
      'Porque no tuvo efectos distributivos',
    ],
    correcta: 0,
    explicacion: 'La desindustrialización de regiones enteras en países ricos es parte del contexto de los populismos recientes. El agregado nacional puede crecer mientras zonas concretas se hunden.',
  },
  {
    id: 'uni-144', tema: 'actual', dificultad: 3,
    enunciado: '¿Qué muestra la pandemia de covid-19 sobre el mundo globalizado?',
    opciones: [
      'Que la interconexión acelera la propagación y a la vez permite respuestas científicas coordinadas, con acceso muy desigual a ellas',
      'Que la globalización se detuvo definitivamente',
      'Que los organismos internacionales son innecesarios',
      'Que las fronteras cerradas resolvieron el problema',
    ],
    correcta: 0,
    explicacion: 'Las vacunas se desarrollaron en tiempo récord gracias a la cooperación científica, y su reparto reprodujo las desigualdades existentes entre países.',
  },
  {
    id: 'uni-145', tema: 'actual', dificultad: 3,
    enunciado: '¿Por qué el cambio climático se considera un problema histórico y político, no solo científico?',
    opciones: [
      'Porque sus causas están en un modelo energético construido históricamente y su solución exige decisiones políticas sobre quién asume los costos',
      'Porque la ciencia no tiene consenso al respecto',
      'Porque es un fenómeno natural sin relación con la actividad humana',
      'Porque solo afecta a las generaciones pasadas',
    ],
    correcta: 0,
    explicacion: 'La responsabilidad histórica de las emisiones y la capacidad actual de reducirlas están repartidas de forma desigual. Por eso cada cumbre climática es, ante todo, una negociación sobre justicia.',
  },
  {
    id: 'uni-146', tema: 'actual', dificultad: 3,
    enunciado: '¿Qué papel juega China en el orden mundial del siglo XXI?',
    opciones: [
      'Se consolidó como segunda economía mundial y actor geopolítico central, desafiando la hegemonía estadounidense',
      'Sigue siendo una economía cerrada y marginal',
      'Abandonó el comercio internacional',
      'Se integró plenamente al bloque occidental',
    ],
    correcta: 0,
    explicacion: 'Su crecimiento desde las reformas de 1978 sacó de la pobreza a cientos de millones de personas. La Nueva Ruta de la Seda extiende su influencia en infraestructura por Asia, África y América Latina.',
  },
  {
    id: 'uni-147', tema: 'actual', dificultad: 4,
    enunciado: '¿Qué tensión existe entre soberanía nacional y organismos internacionales?',
    opciones: [
      'Los problemas globales exigen decisiones supranacionales, pero los Estados se resisten a ceder competencias y la legitimidad democrática de esos organismos es discutida',
      'No existe ninguna tensión',
      'Los organismos internacionales sustituyeron a los Estados',
      'Los Estados perdieron toda capacidad de decisión',
    ],
    correcta: 0,
    explicacion: 'Clima, pandemias, evasión fiscal y regulación tecnológica desbordan las fronteras. Pero quien decide en esas instancias no es elegido por los ciudadanos afectados, y ahí está el problema.',
  },
  {
    id: 'uni-148', tema: 'actual', dificultad: 4,
    enunciado: '¿Por qué la desigualdad global y la desigualdad dentro de los países evolucionaron de forma distinta en las últimas décadas?',
    opciones: [
      'La distancia entre países se redujo por el crecimiento asiático, mientras la desigualdad interna aumentó en buena parte del mundo',
      'Las dos aumentaron al mismo ritmo',
      'Las dos se redujeron sostenidamente',
      'No existen datos comparables',
    ],
    correcta: 0,
    explicacion: 'Es lo que ilustra la llamada curva del elefante: ganaron las clases medias emergentes de Asia y el 1 % más rico, y se estancaron las clases trabajadoras de los países desarrollados.',
  },
  {
    id: 'uni-149', tema: 'actual', dificultad: 4,
    enunciado: '¿Qué riesgo plantea la concentración del debate público en pocas plataformas privadas?',
    opciones: [
      'Que empresas no elegidas definan qué información circula, con criterios comerciales y sin control democrático',
      'Que aumente el costo de acceso a internet',
      'Que desaparezcan los medios tradicionales',
      'Que se reduzca la velocidad de conexión',
    ],
    correcta: 0,
    explicacion: 'La moderación de contenidos enfrenta un dilema real, pero la decisión sobre qué se amplifica y qué se oculta tiene efectos políticos y hoy la toman actores privados.',
  },
  {
    id: 'uni-150', tema: 'actual', dificultad: 4,
    enunciado: '¿Por qué estudiar historia universal ayuda a interpretar los conflictos actuales?',
    opciones: [
      'Porque muchos conflictos presentes tienen raíces en fronteras, deudas y agravios heredados que no se entienden sin su origen',
      'Porque la historia se repite de forma exacta',
      'Porque permite predecir con certeza el futuro',
      'Porque los conflictos actuales carecen de antecedentes',
    ],
    correcta: 0,
    explicacion: 'Ni repetición mecánica ni profecía: lo que ofrece la historia es la capacidad de reconocer procesos y de preguntar de dónde viene una situación antes de opinar sobre ella.',
  },
];
